{100}{}{你看见一个电脑操作员。}
{101}{}{你看见保罗修士。}
{102}{}{这个修士看上去是一个电脑操作员。}

{200}{}{嗨！}
{201}{}{你好。}
{202}{}{现在，今天我备份了这些文件了了吗...}
{203}{}{报歉，我没时间。}

{300}{}{是的？}
{301}{}{你这家伙在这有很多电脑嘛。}
{302}{}{关于阿比你能告诉我什么？}
{303}{}{和我说说你们的领导者。}
{304}{}{你知道伊甸园创造器吗？}
{305}{}{你知道哪能找到13号避难所吗？}
{306}{}{再见。}
{307}{}{我很需要知道一些特别的消息。}
{308}{}{好的，比如什么？}

{400}{}{是的，我们有。在我看来很多。每天都要备份所有的文件那真是烦人。太多资料要保存，不过必需这样做。}
{401}{}{我可以想像。我还有一些别的问题。}
{402}{}{我们是一个独立的团体。长久以来我们欢迎任何人表现他们自我。}
{403}{}{好的。}
{404}{}{他是一个好的领导者。怪物杀了托马斯修士之后他有一些暴躁。}
{405}{}{什么样的怪物？}
{406}{}{我没见过不过我认为是一只巨大的辐射蝎。}
{407}{}{为什么你认为是一只巨大的辐射蝎？}
{408}{}{因为我听见过洞穴传来的声音，听起来就像辐射蝎发出的。}
{409}{}{对。}
{410}{}{实际上我们做了。看看那边的电脑。用这个通行卡解开文件。(他给你一把通行卡)}
{411}{}{噢，非常感谢！}
{412}{}{我不知道13号避难所。不过南边有一个避难所掩体市。也许那有你需要的迅息。}
{413}{}{谢谢。}
{414}{}{我身边的电脑里有一些相关的信息。用他你需要一把通行卡。我不通常不会给任何人的，所以得先和我们的领导者谈谈获得许可。}
{415}{}{好的，谢谢。}

{420}{}{你真的读了很多书，包括非技术方面的和技术方面的，贯穿你的一生，对吧？有什么你特别感兴趣的科目的吗？}

#new in RP 1.3
{421}{}{Hmm, let's see. Did you know a notch in a tree will remain the same distance from the ground as the tree grows?}
{4210}{}{Uh, no, I can't say I knew that. That's...interesting.}
{4211}{}{And did you know a cucumber is 96% water?}
{4212}{}{Wow, 96%, huh? Fascinating. But, um, what's a cucumber?}
{4213}{}{I've never seen one, but I've read about them. [He looks around nervously and lowers his voice.] I know we're not supposed to actually study these books, but when I was transcribing a book on botany, I just couldn't help but get sucked into it. The world of plants is simply captivating. Perhaps, if, during your travels, you happen upon some botany information, you could bring it to me? I'd be most grateful. Of course, it'd have to be our secret.}
{422}{}{Sure. If I come across anything like that, I'll be sure to let you know.}
{4220}{}{I don't think I want to contribute to your plant obsession. Sorry.}
{4221}{}{Oh, well then. Fine, forget I asked.}
{4222}{}{Let me ask you something else.}
#end
{423}{}{Right...Well, I have some other questions.}
{424}{}{Would you? I'd appreciate that.}
{425}{}{No problem. I have some other questions.}
{426}{}{Any time. Well, see you around.}

{430}{}{I found some information about Botany that might interest you.}
{431}{}{Really?! That's great. Please, do tell immediately.}
{432}{}{Fascinating! I shall take this holodisk and add it to the computer database immediately. I appreciate you taking the time to find this for me. Thank you for collecting this for me.}
{433}{}{Well you see...Understanding habitat destruction and species extinction is dependent on an accurate and complete catalog of plant systematics and taxonomy. And then this means that...}
{434}{}{Any time. I have some other questions though.}
{435}{}{No problem. See you around.}
{436}{}{Fascinating! I appreciate you taking the time to find this for me. Please go and upload this information to our computers.}
{437}{}{No problem, I'll do that now. See you around.}

{500}{}{Stop that, moron!}

{550}{}{That computer near me should have some information about it. You now have access, so take a look for yourself.}

{600}{}{The Abbot gave me permission to access the computers here.}
{601}{}{Ah yes, I heard about what you did. Thanks for taking care of that situation. Here is the access key. (He hands you the key.) Enjoy!}
{602}{}{Thanks. See you around.}

{650}{}{Greetings traveler! I am Brother Paul and I am in charge of the collection of information for the Abbey. What can I do for you?}
{651}{}{Nice to meet you, Paul. I have some questions.}
{652}{}{Nothing. See you around.}
