{100}{}{你看见一个流浪者。}
{101}{}{你看见一个又脏又臭的男人。}
{102}{}{你看见一个又脏又臭的女人。}

{103}{}{嗨伙计，我们先来的。你想干嘛？}
{104}{}{我觉得丹恩城的孩子们需要一个地方生活，我觉得这栋建筑很适合做这个。因此我来看看。}
{105}{}{等等，什么？你不是认真的吧...}
{106}{}{我是认真的。我们需要一栋大建筑来开办孤儿院，这正好很合适。唯一的问题是你和你的朋友住在这。}
{107}{}{等等...你是在驱逐我吗？那一点也不酷。混蛋...开打吧！}
{108}{}{听着，你有两个选择要么是平静的离开这，要么把你们的尸体打包扔出去。}
{109}{}{(这个人看看了你) 不伙计，没人能让我们离开这。我们会为我们的地盘而战的。}
{110}{}{(这个人强忍住) 好的，不需要为这么生气。不过我们能去哪？出去我们没什么任何地方可住院。}
{111}{}{我不知道。那不是我的问题。}
{112}{}{这样啊，你们有兴趣在孤儿院工作吗？整理一下你们自己，如果你们愿意可以做这的清洁工，你们还可以得到免费食物和一些钱。}
{113}{}{不伙计，我改变主意了。我们不离开。我们就在这，开打吧。}
{114}{}{那听起来不错！我会告诉我的朋友这事的。你可以相信我们。不用担心，我们会保证这些孩子安全的。}
{115}{}{别介意。}

#new for RP 1.3
{116}{}{She's not going to pay you. But I'm here to offer you a new deal: You and your friends walk away from here now, and you get to keep your lives.}
{117}{}{Alright, well, I gave it a shot. Bye.}


{120}{}{This is a great idea. We'll get things ready.}

{200}{}{Huh?}
{201}{}{This is our turf.}
{202}{}{You squatting here too?}
{203}{}{Got anything to eat?}

{300}{}{You see a man in work clothes.}
{301}{}{You see a woman in work clothes.}

{310}{}{Hey, thanks for helping to set this up for us. We'll work hard.}
{311}{}{You better. Make sure the children stay out of trouble too.}
{312}{}{We'll do our best.}
{313}{}{Bye.}

#third way to finish quest -added after initial creation, but before official release
{350}{}{Anywhere but here. The Den's a big place, I'm sure you can find somewhere else to crash. Come on, do you really want the children to live on the streets?}
{351}{}{Nah, you're right, that ain't cool for the children. Alright, we'll pack our things and move out. This place had a leaky roof anyway.}
{352}{}{Thanks. This will mean a lot to them. Take care.}
{353}{}{Nah, that ain't our problem. If Mom thinks it's that important to get those kids off the streets, then she should stop being stingy with her cash and share the wealth. Yeah, I've changed my mind, we're staying until she pays up. Now this conversation's over, so you better leave if you know what's good for you.}

{360}{}{Alright. No need for this to get out of control. I'll leave you alone.}
{361}{}{Time to clean this place up then. (Attack)}

{400}{}{Thanks again!}
{401}{}{We'll work hard.}
{402}{}{Thanks for being so cool about things.}
{403}{}{We won't let you down.}

{500}{}{We'll collect our things and be out of here soon.}
{600}{}{You've cleared out all the squatters.}
