{100}{}{你看到一个店员。}
{101}{}{你看到了朱流，一个店员。}
{102}{}{你看到一个穿着整齐的男人。}
{103}{}{你好！欢迎来到我的商店，八飞龙。}
{104}{}{我可以帮你什么吗？}
{105}{}{嗯嗯！}
{106}{}{东西！}
{107}{}{你好吗？}
{108}{}{我正在寻找一些器材。}
{109}{}{我正在寻找一些讯息。}
{110}{}{再见。}
{111}{}{你要买什么东西吗？}
{112}{}{::点头::}
{113}{}{::摇头::}
{114}{}{这是我们有的东西。}
{115}{}{- 结束 -}
{116}{}{我恐怕那就是我能够帮你的了。再见。}
{117}{}{[完成]}
{118}{}{我是朱流，是这边的负责人，而这里是八飞龙，一间商店，也是一个交易“消息”的地方。}
{119}{}{什么样的消息？}
{120}{}{我知道了。我想要一些器材。}
{121}{}{在这个镇里发生的事很少有我不知道的。当然，你知道你想要问什么，对不对？你想要知道什么？}
{122}{}{我正想要升级我的器材。}
{123}{}{我在那边可以找到飞鸟设计图？}
{124}{}{我想要找一些燃料。}
{125}{}{我知道我需要一个ＦＯＢ才能够使用油轮的电脑。}
{126}{}{我需要一些油轮的导航晶片。}
{127}{}{我正在找一个脾脏。}
{128}{}{我听说一些飞行的机器把一堆村人都带到这一带来了。}
{129}{}{没事，再见。}
{130}{}{去与克拉克特谈吧，他就在哈伯教的营里。他是他们的主要科学家。}
{131}{}{谢谢，我需要再问一些事。}
{132}{}{谢谢。再见。}
{133}{}{到北方去看看，在那瓦罗。在那边的加油站附近有一个秘密的基地。}
{134}{}{谢谢，我需要再问一些事。}
{135}{}{谢谢。再见。}
{136}{}{你有试着到旧的避难所去找找看吗？我听说那里面有许多的资料以及科技。}
{137}{}{谢谢，我需要再问一些事。}
{138}{}{谢谢。再见。}
{139}{}{一个脾脏？哈哈！是，基德在一场赌局中输了自己的脾脏。我把它卖给了王博士。他好像对那很有兴趣。}
{140}{}{王博士？我在那边可以找到他？}
{141}{}{你怎样让脾脏不见的呢？}
{142}{}{谢谢，我需要再问一些事。}
{143}{}{谢谢。再见。}
{144}{}{王博士是钢铁王宫的科学家，到那边去找他吧。}
{145}{}{你怎样让脾脏不见的呢？}
{146}{}{谢谢，我需要再问一些事。}
{147}{}{谢谢。再见。}
{148}{}{他喝醉了。非常的醉。他整个晚上都提到他的脾脏，最后他把它拿去赌了。}
{149}{}{你把他的脾脏拿走了？}
{150}{}{我知道了，我还有一些问题要问。}
{151}{}{是的。}
{152}{}{我知道了，我还有一些问题要问。}
{153}{}{你有病，不是吗？}
{154}{}{再见。}
{155}{}{你是一个不知羞耻的人。我不要你在我的店里。下次再来吧。}
{156}{}{随便你。}
{157}{}{他们没有。他们从北方来并且飞过我们这边，并且往海的方向飞去了。}
{158}{}{飞到海上？我要怎才能够到那边去？}
{159}{}{骗鬼吧，跟我说真话，不然我就把你杀了。}
{160}{}{嗯．．我们没有一艘船可以航行那么远的。除了．．}
{161}{}{除了．．？}
{162}{}{谢谢你的“帮助”。我会去问别人的意见的。}
{163}{}{．．除非你能够开动那艘旧油轮。那是一艘老船，但是却能够航行长距离。}
{164}{}{谢谢，我需要再问一些事。}
{165}{}{谢谢。再见。}
{166}{}{有人说哈伯教取得了大量的燃料。去跟他们谈吧。}
{167}{}{谢谢，我需要再问一些事。}
{168}{}{谢谢。再见。}
{169}{}{你应该去问问始族的科学家，也许他们能够帮你吧。}
{170}{}{谢谢，我需要再问一些事。}
{171}{}{谢谢。再见。}
{172}{}{你是我们的敌人。死吧！}
{173}{}{你将ＡＨＳ－９杀了，对我们帮助很大。我希望我能够帮你。}
{174}{}{你是谁？}
{175}{}{我正在寻找一些器材。}
{176}{}{我正在寻找一些讯息。}
{177}{}{再见。}
{178}{}{你已经将它们给了哈伯教徒，不是吗？}
{179}{}{嗯．．我可以问你一些事吗？}
{180}{}{嗯．．再见。}


#RP 1.3
{200}{}{What else can you tell me about the tanker?}

{210}{}{Even if you could get the NavCom working and the tanker fueled up, you'll still need considerable good fortune if you really want the ship to sail again.}
{211}{}{What do you mean by 'considerable good fortune?'}

{220}{}{I mean, the hunk of junk is older than most ghouls. It would be a miracle if it didn't sink on you. That is all I meant.}
{221}{}{I have a feeling that there's something you're not telling me about the tanker.}

{230}{}{Perhaps there is. (smiles) Perhaps the wasteland has made you paranoid.}
{231}{}{Listen, I need to find my tribe. Those bastards who took them are dangerous and need to be stopped.}
{232}{}{Come on. What's so special about the tanker? We're just two people talking.}
{233}{}{You sure? I'll make it worth your while.} #female
{234}{}{I don't have time for these mind games. Goodbye.}

#SPEECH >90%  Listen...
{240}{}{Bah. They are nothing. However, it's not the tanker that's special. It's just a big rusty tanker like you said. Our submarine, on the other hand...}
{241}{}{Submarine?}

#SPEECH <90%  Come on...
{250}{}{Let's talk, then. But there's nothing special about the tanker. I give you my word.}
{251}{}{What if I paid you to tell me?}

{260}{}{Hmm... Business has been slow lately. I could use more customers. Or a donation from a very generous one. Say, $2000?}
{261}{}{Here you go. But your information better be worth it.}
{262}{}{$1500 and that's my final offer.}
{263}{}{I don't think so. That's too much.}

{270}{}{(Lao Chou pockets the $2000.) It's not the tanker that's special. It's just a big rusty tanker like you said. Our submarine, on the other hand...}
{271}{}{Submarine?}

{280}{}{We have nothing further to discuss, then.}
{281}{}{You sure? My lovely wife Miria will certainly make it worth your while.}
{282}{}{Goodbye.}

{285}{}{You drive a hard bargain. Fine, $1500.}
{286}{}{Here you go. But your information better be worth it.}
{287}{}{(Lao Chou pockets the $1500.) It's not the tanker that's special. It's just a big rusty tanker like you said. Our submarine, on the other hand...}
{288}{}{Submarine?}

#SPEECH <90% BUT PC IS FEMALE AND CH >=7 OR SEX APPEAL
{290}{}{Well if you put it that way, I have been cooped up in this dusty shop for a long time. It has been a quite a while since I enjoyed the company of a charming woman like yourself.}
{291}{}{[CONTINUE]}

{300}{}{[Hours past with no end in sight. You begin to suspect that Lao Chou may not be completely human. You black out, eventually.]}
{301}{}{hhh... What happened?}

{310}{}{You fainted as I moved us into the triple-lotus position, and I had to finish pleasuring myself with the grinning-panda kata. But a deal's a deal. It's not the tanker that's special -- it's just a big rusty tanker like you said. Our submarine, on the other hand...}
{311}{}{Submarine?} 
#IF SPEECH <90% BUT PC IS FEMALE AND CH <7
{330}{}{I... don't think so.}
{331}{}{Don't try and fight it now. You want me and you know it.}

{340}{}{No, actually. You are not my type.}
{341}{}{Oh, I see. You're not into women.}

{350}{}{I am. I just do not find you very attractive. Perhaps if I were drunk.}
{351}{}{You're obviously blind. Whatever. It's your loss.}

#IF SPEECH <90% BUT PC W/ MIRIA
{360}{}{What are you proposing? Ahh... well, I have been cooped up in this shop for a long time. I will reveal all I know in exchange for a sample of your lady friend's charms.}
{361}{}{Miria, honey... I guess you'll have to, erm, pump this guy for information.}
{362}{}{I was joking, old man. Like I'd let you make time with my wife... I'm leaving.}

{370}{}{[You wait outside and hear faint moans from inside the Flying Dragon 8. An hour passes, and then another. You bang on the door, shouting, "Hurry up in there!" Finally, the moans become a primal scream.]}
{371}{}{[Bang on the door] Hey, what are you two doing in there!?}

{380}{}{A smiling Lao Chou emerges from his bedroom, still pulling on his pants. A few moments later Miria stumbles out behind him, looking dazed and confused but deeply satisfied] Your wife is a great deal more experienced than she looks.}
{381}{}{I, erm, know. Now pull your damn pants up and tell me what's so special about the tanker.}

{390}{}{There's nothing special about the tanker. It's just a big rusty tanker like you said. Our submarine, on the other hand...}
{391}{}{Submarine?}

#Submarine?
{400}{}{The Shi-Huang-Ti. My great grandfather, Ye Li, was its captain. He unleashed her nuclear fires like a horrible dragon upon California's coast.}
{401}{}{No shit.}

{410}{}{Ironically, a malfunctioning missile from our own ancestral nation went off course and exploded over the ocean near the submarine's location. The blast knocked out the Shi-Huang-Ti's systems, leaving Captain Ye Li and his crew stranded at sea.}
{411}{}{That's karma for you.}

{420}{}{But there was salvation. After weeks of drifting, the sub finally came to rest out in the shallow waters of the San Francisco bay. This city became our new home. We eventually restored the Shi-Huang-Ti; its targeting systems, its weapons. It has enough firepower to blow any potential invaders out of the water. So even if you got that old tanker running, it wouldn't get far, as the submarine will destroy any non-Chinese vessel that sails through the bay.}
{421}{}{That sounds like a problem alright. So how would I get to the submarine?}

{430}{}{You swim. Or take the motorboat at the docks. It is guarded, though, by one of our best soldiers, and he will not let an outsider like you past him.}
{431}{}{You have any idea how I can get past him then, without shooting him in the face?}

{440}{}{He's under strict orders to guard it 24/7. He will not let anyone without the right password through.}
{441}{}{I don't suppose you know it?}

{450}{}{That depends. I don't suppose you have $10000 to ensure the continued prosperity of my shop?}
{451}{}{Here's your $10000.}
{452}{}{That's outrageous for a simple password. I'll only go as high as $5000.}
{453}{}{No deal.}

#here's the $5000
{460}{}{Ah, much appreciated. The password is XY8QIV2SHI. Others may be watching me after this, so don't forget the password. If ever we discuss it again, I'll need even more money for bribes.}
{461}{}{Thank you. Goodbye.}

#pass barter check
{470}{}{You are a crafty one, I'll give you that. Fine. I accept your offer. The password is XY8QIV2SHI. Don't forget it, or you'll have buy it from me again.}
{471}{}{Thank you. Goodbye.}

#fail barter check
{480}{}{Don't insult me with your meager offers. $10000. Take it or leave it.}
{481}{}{Fine. Here's your $10000.}
{482}{}{No deal.}

#No deal.
{490}{}{Your loss then. I don't believe we have anything else to discuss. Goodbye.}
{491}{}{Bye.}
