{100}{}{你看到一个戴着船长帽的人。}
{101}{}{你看到朗麦尔船长。}
{102}{}{你看到一个戴着船长帽的混混。}
{103}{}{你他妈的要什么？我不与朋友之外的人说话。帮我的朋友忙，我就跟你说话。}
{104}{}{[完成]}
{105}{}{我听说你帮我的朋友一个大忙，谢谢你。我可以帮你吗？}
{106}{}{你是谁？}
{107}{}{我听说你是知道这艘船所有事的人。}
{108}{}{为什么他们叫你船长？}
{109}{}{你要怎样才能让这东西运作呢？}
{110}{}{没事。}
{111}{}{我是船长，负责这船的一切。如果你有问题，去问别人。我没有时间。}
{112}{}{[完成]}
{113}{}{这艘船是波斯当油轮。上面装满了战争之前的科技。它上面有一个ＦＯＢ可以让你与导航电脑室连线，而且它上面还有一个ＩＦＦ探知器。}
{114}{}{你怎么知道这些事呢？}
{115}{}{什么是ＩＦＦ？}
{116}{}{你要怎样才能让它运作呢？}
{117}{}{谢谢，再见。}
{118}{}{我原本是帮英克雷军工作的。后来我发现我根本不是在为美国而战，而是帮一些不想放弃他们手中权力的老混蛋。现在，我离开他们到这边来与比较诚实的人一起居住。}
{119}{}{比较诚实的人？你是说这一些人？}
{120}{}{英克雷军到底是什么？}
{121}{}{要怎才能让这东西启动？}
{122}{}{再见。}
{123}{}{要怎样操作这个东西呢？加一些燃料进去－问问始族或是哈伯教的人－然后按下按钮。电脑就会操作其它的事了．．如果它还能运作的话。它将会自动的离开油台的。也就是说，你需要ＩＦＦ、ＦＯＢ、好的电脑、还有燃料。简单吧！}
{124}{}{你怎么会知道这些事呢?}
{125}{}{ＩＦＦ还有ＦＯＢ是什么？}
{126}{}{什么油台？}
{127}{}{再见。}
{128}{}{ＩＦＦ：敌友分析器。也就是说它会放出这是一艘波斯当油轮的讯号。这样一来，波斯当的防卫系统就不会攻击我们了。ＦＯＢ则是一个英克雷军的科技，可以让你通过门。你也许要在他们的基地才能找到那样的一个东西吧。}
{129}{}{你怎么知道这些的？}
{130}{}{什么油台？}
{131}{}{谢谢，再见。}
{132}{}{是的。跟这一些人在一起，你可以清楚的知道你在干什么。他们不会耍什么招数的。英克雷军则是像一堆狼一样－随时都会反过来对付你。}
{133}{}{英克雷军到底是什么？}
{134}{}{你是怎样认识他们的？}
{135}{}{英克雷军是以前的组织。如果你能够过海到油台那边的话，你就会知道了。}
{136}{}{我要如何操作他呢？}
{137}{}{什么油台？}
{138}{}{很简单。我有一天离开了那瓦罗基地，然后就到这边来了。}
{139}{}{英克雷军到底是什么？}
{140}{}{谢谢，再见。}
{141}{}{在海上有一个大型的波斯当钻油台。那里是英克雷军最后的一个基地}
{142}{}{你怎知这些事呢？}
{143}{}{在那油台上面还有什么事发生呢？}
{144}{}{谢谢，再见。}
{145}{}{消息传得很快的。}
{146}{}{我知道了。在那油台上还有什么事发生呢？}
{147}{}{我知道了，再见。}
{148}{}{不知道。我是一个那瓦罗的人员，不是在油台上工作的。我们一向都经过无线电与他们联络，并没有真正到那边过。}
{149}{}{我知道了，我要怎样控制这个东西呢？}
{150}{}{谢谢，再见。}
{151}{}{你敢与船长还有他的朋友乱来，真是犯了一个大错误了．．}
{152}{}{你怎样操作？只要你准备好所有的东西，按下按钮，电脑就会自动操作了。它将会自动的航向油台，而他们不会发现的。}
{153}{}{你也要将导航系统修好，我想你应该可以在一个避难所之中找到零件的。}
{154}{}{很高兴再见到你，你需要什么？}
# Begin Seraph's Code
{155}{}{，而我认为，你的朋友应该都在那边。}
{156}{}{。}
# End Seraph's Code

#added by killap
{200}{}{What old sub?}
{210}{}{There's an old Chinese submarine marooned out there in the bay. Damn thing gives me the creeps, lurking out there under the water like a rusty ghost. I doubt it's still active, but if it was, its automated weapons systems could blow this tanker to hell before you even got close to that oil rig.}
{211}{}{Why don't you think the sub's still active?}
{220}{}{Well, for one, she's been sitting there rotting in the ocean since the great war. Plus, if she were active, she would've fired on this rig back when the Enclave first docked it here. Course, I wouldn't put it past the Shi to go there and start tinkering with it, so you never know. Might be worth checking into before you set sail.}
{221}{}{How would I go about checking into it?}
{230}{}{If anyone knows what's going on with that sub, it'd be the Shi. The sub's what brought 'em here in the first place - I wouldn't be surprised if they worship the thing. The Shi Emperor would know everything, of course, but good luck with that. You'd be better off asking Lao Chou, over at the Flying Dragon 8 - he's been known to dole out information from time to time. Hell, maybe you could even get one of the dock workers to talk.}
