#{100}{}{You see a powerful computer.} //This is for the computer object itself
#{101}{}{You see the Emperor Computer.}
#{102}{}{You see a large, humming, fully functional computer that has "Emperor v8.8" stamped into its lower casing.}
{100}{}{你看到一部电脑。}
{101}{}{你看到皇帝电脑。}
{102}{}{你看到一部电脑，上面有一个触摸式荧幕。上面写着“皇帝ｖ８．８电脑终端机”。}
{103}{}{你好，请键入你的秘码。}
{104}{}{::流口水::}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{::侵入电脑::}
{109}{}{离线。}
{110}{}{身份已确认。}
{111}{}{你想要执行什么功能？}
{112}{}{检查。}
{113}{}{资料。}
{114}{}{预测。}
{115}{}{无。}
{116}{}{请与系统工程师联络，再见。}
{117}{}{::侵入电脑::}
{118}{}{::离开::}
{119}{}{入侵者警报被启动了，系统关机中。再见。}
{120}{}{[完成]}
{121}{}{检查那一样功能？}
{122}{}{网路检查。}
{123}{}{格式化磁碟。}
{124}{}{检查硬碟结构。}
{125}{}{回去。}
{126}{}{你想要查询那一样的资料？}
{127}{}{生物。}
{128}{}{化学。}
{129}{}{物理。}
{130}{}{历史。}
{131}{}{回去。}
{132}{}{住在王宫的子民们有危险了，有５０％的机会有暗杀者混在他们之中。}
{133}{}{危险降临的王宫了。有７５％机会居民们会受伤。}
{134}{}{哈伯教的太空船发射会有９５％的失败率。原因：没有燃料，机身没有封闭完成，引导不良。}
{135}{}{获选者执行他的任务有１５％的成功率。}
{136}{}{资料显示英克雷军比他人想像中的要强大；不要接近他们。}
{137}{}{在本游戏中潜艇再次出现的机率：０％。}
{138}{}{如果外人不帮忙，油轮船员自行将生物清除的机率：０％。}
{139}{}{波斯当油轮无法承受航行。}
{140}{}{无法处理，需要更多资料。}
{141}{}{[更多]}
{142}{}{回去。}
{143}{}{生物站：运作中}
{144}{}{生物站：没有运作}
{145}{}{化学站：运作中}
{146}{}{化学站：没有运作}
{147}{}{物理站：运作中}
{148}{}{物理站：没有运作}
{149}{}{关起生物站。}
{150}{}{关起化学站。}
{151}{}{关起物理站。}
{152}{}{连接生物站。}
{153}{}{连接化学站。}
{154}{}{连接物理站。}
{155}{}{开动生物站。}
{156}{}{开动化学站。}
{157}{}{开动物理站。}
{158}{}{回去。}
{159}{}{格式化磁碟：所有的资料都会消失，要继续吗？}
{160}{}{是的。}
{161}{}{不。}
{162}{}{本系统的磁碟有９２％结构可以运作。资料可靠度１００％。预测处理器有电力问题－需要６天才能修覆。预测功能只有１５％运作度。}
{163}{}{回去。}
{164}{}{你想要格式化吗？这是一个无法反悔的动作。}
{165}{}{是的。}
{166}{}{不。}
{167}{}{格式化中．．格式化中．．格式化完成。机器人需要完全安装，关机。关机中．．完成。}
{168}{}{[完成]}
{169}{}{选择资料：－植物学程式－基因程式－ＸＥＮＯ程式}
{170}{}{植物学程式。}
{171}{}{基因程式。}
{172}{}{ＸＥＮＯ程式}
{173}{}{回去。}
{174}{}{(在二十分钟后，你看到：商博士的抗放射植物研究并不是相当的成功，所创造出来的植物有着相当不良的反效果。}
{175}{}{基因程式。}
{176}{}{ＸＥＮＯ程式}
{177}{}{回去。}
{178}{}{(在二十分钟后，你看到：在进行ＦＥＶ病毒研究之后，他发现创造变种士兵的可能性相当的高。}
{179}{}{植物学程式。}
{180}{}{ＸＥＮＯ程式}
{181}{}{回去。}
{182}{}{“我们原本想要进行实验的实验品都不见了，一定是被哈伯教偷走了”。在能够找到新的实验品之前，所有的实验都暂停。}
{183}{}{植物学程式。}
{184}{}{基因程式。}
{185}{}{回去。}
{186}{}{化学资料库：燃料－聚合体}
{187}{}{燃料}
{188}{}{聚合体}
{189}{}{回去。}
{190}{}{(在看过复杂的化学公式之后，你发现始族发明了一种可以从植物取出的燃料。)}
{191}{}{(你看到许多的公式，你一点都看不懂。)}
{192}{}{送燃料到波斯当油轮。}
{193}{}{送燃料到哈伯教。}
{194}{}{回去。}
{195}{}{你发现始族正在设计一种聚合体的装甲。}
{196}{}{回去。}
{197}{}{燃料送达。储存槽状况：空。关闭程式。}
{198}{}{[完成]}
{199}{}{燃料送达。储存槽状况：空。关闭程式。}
{200}{}{[完成]}
{201}{}{物理资料库：创新－学说}
{202}{}{创新}
{203}{}{学说}
{204}{}{回去}
{205}{}{由于目前得到的飞鸟设计图，我们设计飞行器的可能性增加了不少。}
{206}{}{::拷贝设计图:: 回去。}
{207}{}{回去。}
{208}{}{“我们还在设计飞行的机器。不过目前都还没有成功，如果我们可以读取战前的设计的话．．”－王博士}
{209}{}{回去。}
{210}{}{(你发现始族正在设计核能发电的科技，还有想办法创造战前的科技。}
{211}{}{回去。}
{212}{}{站开启完成。}
{213}{}{回去。}
{214}{}{电脑终端机并没有那种界面。}
{215}{}{电脑终端机看起来没有作用。}

{216}{}{系统遭到侵入。命令攻击！}
{217}{}{攻击入侵者！}
{218}{}{攻击！}
{219}{}{有反叛者！}

{220}{}{地面寻找。}
{221}{}{你想要寻找什么？}
{222}{}{我的同胞。}
{223}{}{有９７％的可能你的同胞正在英克雷军的基地。}


#RP 1.3

#History
{230}{}{[The screen flashes for a second before switching to a monochromatic display filled with Chinese symbols.
 After a few moments, the screen clears and displays a list of contents. Most of the files are ancient and corrupted,
 but there are several that seem to be still intact.]}
{231}{}{People's Liberation Army Navy                                       Emperor v. 4.01 Access Terminal
                                    Please make a selection:}
{232}{}{Submarine status}
{233}{}{Chinese Intelligence Network}
{234}{}{Comlinks}
{235}{}{Personnel logs}
{236}{}{::back::}

#sub status
{240}{}{Name: Shi-Huang-Ti                                                     Class: Type 088 Nuclear-powered Ballistic
 Missile Submarine   Armament: Eight JL-3 nuclear ballistic missiles
                  Launched: 8th August 2068                                         Commissioned: 18th April 2069
                                       Captain: Admiral Class AAAA Ye Li
                                Crew: 15 officers, 28 petty officers, 27 enlisted, 16 civilian technicians}
{241}{}{Read on.}

{250}{}{Service:                                                               2069 - 2071: Chinese territorial
 waters patrol              2071 - 2077: Combat patrol in the Alaskan and Pacific theatres of operations
                                            October 2077: Combat mission in the Californian theatre of operations.
 Mission outline R.}
{251}{}{Read on.}

{260}{}{Current status:
                                                     Submarine damaged beyond repair. Mainframe removed from vessel and
 relocated. Ship refitted as stationary defensive structure two miles NNE of San Francisco harbor.}
{261}{}{What was that about combat patrols?}
{262}{}{Read more about Mission Outline R.}
{263}{}{Stationary defensive structure sounded interesting.}
{264}{}{::back::}

#combat patrols...
{270}{}{Upon request made by the Alaskan Frontline commander, General Jingwei, the Shi-Huang-Ti was transferred to the
 Alaskan/Pacific theatre of operations to intercept American convoys in open waters. Under the command of Rear Admiral
 Ye Li, she has sunk 9 freighters and 4 warships, damaging 18 more craft and putting a significant strain on enemy
 supply lines.}
{271}{}{Read on.}

{275}{}{Admiral Ye Li has also been credited by the People's Liberation Army Navy as leading to the sinking of USS
 Ebon Atoll by an American submarine, USS Interference.}
{276}{}{::back::}

#defense struct
{280}{}{2220, May : Poseidon Marine Vessel Valdez arrives in port, manned by a crew equipped with unknown-type powered
 infantry armor. The ship is disabled and infested with mutants.
                                                                  2220, June: Following consults with the Emperor, Chiang Lee
 dictates that the Shi-Huang-Ti be reactivated and transformed into a defensive installation against further naval threats.
                                                           2220, July: The submarine is reactivated. Emergency power
 had to be provided to power it up.                                  2231, May: The emergency generator dies. Ken Lee orders
 an ElectroBox generator to be wired into the power system to keep powering the submarine.
                                     2238, August: A Neptune Waveskimmer motorboat is restored and transferred to the
 submarine maintenance crew.}
{281}{}{Hmm, let's see if I can find something more on that maintenance crew...}
{282}{}{::back::}

#find more on maintenance crew...
{290}{}{[Bingo! After a few minutes of fiddling with commands, you manage to pull up a small text file concerning the
 generator on the submarine. It seems that regular trips are needed to refuel and maintain the generator. The file also
 lists the current maintenance crew roster.]}
{291}{}{Submarine maintenance crew (2241 onwards): Tsing Tao, Hun Kwai, Shin Fai, Lo Chang, Wu Fei}
{292}{}{::add myself to maintenance crew roster::}
{293}{}{::back::}

#add self
{300}{}{[With a few quick keystrokes, you become a part of the submarine maintenance crew. A list of passwords for
 the motor boat guard is now accessible.]}
{301}{}{::download password list to PIP-Boy::}

#download list...
{310}{}{[You plug the PIP-Boy into one of the access ports. After a moment, you have an up-to-date list of passwords
 for the next year. Talk about security.]}
{311}{}{::back::}

#done
{320}{}{You're a fully fledged Shi submarine technician now.}

#intel network
#initial message

{325}{}{Error. Command Code Chart required. Please insert the correct chart.}

{330}{}{[Thanks to the command code chart you retrieved from the sub, you are able to access restricted files on the
 Emperor's drives]}
{331}{}{Command code recognized. Security restrictions lifted. Chinese Intelligence Network initialized..
...
...
Warning! Uplink to CIN central Beijing server unavailable. Retrieving archived data.
 [It seems most of the archives are corrupted. However, the mainframe manages to retrieve several intact files]}
{332}{}{Intelligence report 2069-11-5}
{333}{}{Intelligence report 2072-4-18}
{334}{}{Intelligence report 2073-12-4}
{335}{}{Intelligence report 2074-9-17}
{336}{}{Intelligence report 2075-10-17}
{337}{}{Intelligence report 2076-8-12}
{338}{}{Intelligence report 2077-10-12}
{339}{}{Intelligence report 2077-10-23}
{340}{}{}
{341}{}{::more::}
{342}{}{::back::}

#2069-11-5
{345}{}{From: Counterintelligence Division
                                  Rioting in Tibet and neighboring provinces continues, threatening the construction
 of the Eastern Dragon satcom complex. President Xin orders military intervention against the populace. Following
 significant insurgent casualties, the province is restored to Chinese control and the remaining insurgents are resettled.}
{346}{}{::back::}

#2072-4-18
{350}{}{From: Biochemical Warfare Division
                          Outbreak of epidemic in the Soviet Union threatens northern protectorates of the PRC. BioChem
 WD advises quarantine andisolation of endangered territories. Potential resettlement location for insurgents, terrorists
 and undesirables and harvesting area for new strains of biological weapons. Plan submitted to Party for approval.}
{351}{}{::back::}

#2073-12-4
{360}{}{From: Alaskan Front Commander, General Jingwei
                Strain #23-110 deployed against American troops, demoralizing and weakening their operational
 strength. Requesting additional troops and Battlemaster armor for final push against the entrenched American forces at
 the borders of Alaska.}
{361}{}{::back::}

#2074-9-17
{370}{}{From: Central Command
                                           American units deployed to mainland after evading our blockade of Japan.
 Alaskan forces are to continue operations. Military forces in annexed territories are to augment the defense of home front.
 Command authorizes the use of biological and chemical weapons on home soil - the foreign devils must be exterminated!}
{371}{}{::back::}

#2075-10-17
{380}{}{From: Red Dragon
                                                     Insurgency operations and terror strikes highly effective in
 demoralizing the American population. Support for military operations overseas wanes as riots and protests are incited
 across the American soil. Recommend strikes against designated research and military targets across the United States,
 priority: Raven Rock, West Tek, Mariposa, Boulder, Institute.}
{381}{}{::back::}

#2076-8-12
{390}{}{From: Central Command
                                              American military superiority now clear - T-51b power armor units deployed
 to mainland. The PLA has no appropriate counter and is losing ground daily. Chairman Cheng demands that Beijing stays in
 Chinese hands - fortification is underway. Command orders intensification of guerilla operations behind enemy lines.
 Operatives in all American Commonwealth are to prepare for staging insurgencies. Weapon and equipment shipments dispatched.
 Priority target: Washington, DC, Columbia Commonwealth}
{391}{}{::back::}

#2077-10-12
{400}{}{From: Party Chairman Cheng
                                         With the Alaskan Front's collapse and increasingly strong American presence on
 Chinese soil defeat is imminent. According to resolution 636860 of the Communist Party of China, I am hereby ordering all
 loyal military forces to commence nuclear operations against the Americans, mission outline R. Priority targets are
 contained within operational directives. May our souls return to this Earth.}
{401}{}{::back::}

#2077-10-23
{410}{}{From: Central Command                                            All forces in position. Transmitting final confirmation
 codes. Operation Youmíng is go.}
{411}{}{::back::}

#comm links
{420}{}{Scanning communication outlets...                                    PLA CentCom...		offline
                                                CIN Beijing...		offline
                                                   SSC Naval Yard...	offline
                                              SCA Eastern Dragon..	offline
                                        Warning: No connection to external serves could be made.}
{421}{}{That's disappointing...}

#Personnel logs
{430}{}{Scanning local drives...}
{431}{}{[CONTINUE]}

{440}{}{One accessible file found. [It seems most of the archives are corrupted. However, the mainframe manages to
 retrieve an intact file.]}
{441}{}{Personal log: Li Ye, Admiral, Captain}

{450}{}{2077-10-12: We are losing this war. I just received confirmation that the Party has finally decided to go
 through with plan R. Madness! How will nuclear war give us victory? Nobody wins if we unleash this kind of power. But
 I am a soldier and I will follow my orders through to the end.}
{451}{}{Read on.}
{452}{}{::back::}

{460}{}{2077-10-19: The crew is becoming restless. Wong, excited, told the officers about plan R and they were ecstatic.
 I cannot blame them, even though I disagree: Wong lost his sons in Anchorage while Da Chiang's brother was captured off
 the coast of Maryland.}
{461}{}{Read on.}
{462}{}{::back::}

{470}{}{2077-10-21: We have completed final preparations for launch. All that is left is inputting the confirmation codes.
 It has been an honor to serve with these men.}
{471}{}{Read on.}
{472}{}{::back::}

{480}{}{2077-10-23: We have received confirmation codes and will be in position in fifteen minutes. This is probably my
 last entry in this log, so let me state that I do not condone this kind of atrocity. War is fought between soldiers, not
 bombs and civilians. If anyone survives, I hope they will forgive us.}
{481}{}{Read on.}
{482}{}{::back::}

{490}{}{2077-10-29: Damn those maniacs! I thought we were the only group ordered to engage the Los Angeles sector, but I
 was wrong. They launched our most powerful ICBM at it. I cannot fathom why it wasn't sent at Washington, but that's moot.
 We are currently drifting in the ocean. The Emperor is dead, navigation is busted and it seems this is going to be our
 grave.}
{491}{}{Read on.}
{492}{}{::back::}

{500}{}{2077-11-04: We've been adrift for several days now. Jing managed to restore some of the power to our onboard
 systems, so we should have enough oxygen to last several weeks. I am more concerned about food and water - our supplies
 are low and there's not enough of them to go around. The crew is getting restless.}
{501}{}{Read on.}
{502}{}{::back::}

{510}{}{2077-11-08: The Emperor is back on line, but barely. We still have no navigation and the crew is on the verge of
 mutiny - I had to stop two sailors from beating up Jing. The situation is dire. Unless we surface in the next few days,
 I fear we will kill each other.}
{511}{}{Read on.}
{512}{}{::back::}

{520}{}{2077-11-12: Finally! We ran aground in the San Francisco bay. The sailors were rejoicing until we cut open the
 hatches. The city is a wreck, ravaged by firestorms and fallout. I sent out shore parties to find a suitable camp site.
 So far, none have reported such a location. }
{521}{}{Read on.}
{522}{}{::back::}

{530}{}{2077-11-16: Lao's team found an inhabitable neighborhood. The denizens have abandoned it, after the air raid
 alarm it seems, but it has suffered little damage. The most ironic thing? It's San Francisco's Chinatown, still surrounded
 by American checkpoints and fortified barracks. If only they knew...}
{531}{}{Read on.}
{532}{}{::back::}

{540}{}{2077-11-24: We made contact with Red Dragon. The north America Black Ghost command has been trudging westwards
 ever since the 23rd, after they lost contact with CentCom. They're none too happy about being stuck on enemy soil, but
 we must make do.}
{541}{}{Read on.}
{542}{}{::back::}

{550}{}{2077-12-06: The Shi-Huang-Ti away camp is set up and functioning. Ghosts are running scavenging operations in
 the surrounding areas and rounding up any supplies they come across. I gave them strict orders not to engage American
 survivors without provocation - we cannot antagonize potential allies.}
{551}{}{Read on.}
{552}{}{::back::}

{560}{}{2077-12-14: An oddity - a cult by the name of Church of Hubology has somehow survived the devastation in a
 reinforced bunker near what remains of the Golden Gate bridge. They are harmless fanatics, but useful. Their resources,
 manpower and knowledge of the surrounding area will aid us in establishing our new home.}
{561}{}{Read on.}
{562}{}{::back::}

{570}{}{2077-12-27: The basic necessities are covered. We are currently making plans to strip the submarine of electronics
 and other useful equipment - there's no point in maintaining it, since the propulsion system is beyond repair and we can
 use everything we can on site. Jing drafted plans for a reinforced structure - a 'Steel Palace' of sorts.}
{571}{}{Read on.}
{572}{}{::back::}

{580}{}{2077-12-31: This is going to be my last entry in this log. I am no longer an Admiral of the People's Liberation
 Army Navy. I have a responsibility to my men and will lead them into the future. As of 2078, we are in full secession
 from China. Chairman Cheng, eat your heart out. This is Ye Li, leader of the Shi-Huang-Ti people, signing off.}
{581}{}{::back::}

#Mission R
{590}{}{Mission Outline R:                                                    Emergency nuclear warfare contingency plan
 for the People's Liberation Army in case of imminent defeat by a foreign power, accepted by the Communist Party of China
 on 11th November 2073.}
{591}{}{Read on.}

{600}{}{The plan includes a series of coordinated nuclear strikes against strategic targets across America, using strategic
 aircraft, nuclear missile submarines, missile delivery systems, low yield infantry nuclear weapons and other nuclear
 devices. The objective is to cripple American retaliatory capability and military capability.}
{601}{}{Read on.}

{610}{}{The Shi-Huang-Ti is tasked with destroying eight targets on Californian soil, including the West Tek Research
 Facility, corporate headquarters in Los Angeles and major population centers.}
{611}{}{Read on.}

{620}{}{In case of mutiny, betrayal or defection, the Captain is authorized to order the Emperor to take control of the
 vessel and carry out the mission.}
{621}{}{::back::}
{622}{}{::logoff::}
