{100}{}{你见到了一个迷失的灵魂。}
{101}{}{你看见Nessa，那个迷失的灵魂.}
{102}{}{你看见了一个漂亮姑娘的灵魂，寒冷的月光凝望着她。}
{103}{}{我被出卖了。背叛与孤独。}
{104}{}{他怎么可以这样对我？}
{105}{}{血……如此多的血……}

{110}{}{他说他爱我。我们本可以开始崭新的生活。他怎么能这样做？}
{111}{}{谁对你这样做的？你能听见我说话么？}

{120}{}{这一切都是谎言。他根本就不爱我。啊，他拿起了刀！那真疼！他眼神是那么的冷酷，那么的……}
{121}{}{如果你能听到我说的，告诉我谁在伤害你。这是谁做的？}
{122}{}{那对我——真是够了。我要离开这里。}

{130}{}{他就这么准备离开了，留下我孤独的死去。事情怎么会变成这样？}
{131}{}{求你了，告诉我他的名字。给我些有用信息。}

{140}{}{事情怎么会是这样。你说你想和我一起组建一个家庭。啊，那真冷……不！这不是真的！你绝对不会对我做这样的事情的Thorg！我爱你！Nessa将永远爱你……}
{141}{}{谢谢你，Nessa。这就是我想要知道的。}

{150}{}{黑暗中如此孤独……如此孤独。}
{151}{}{[完成]}

{160}{}{血流不止……痛苦为何无法结束？}
{161}{}{别担心，Nessa，我将会很快让你回归平静。}

#dumb dialogue
{300}{}{Uh... You talkin' to me, glow-lady?}

{310}{}{Where dah knife man at? I don' see no knife man. Wat you talkin' 'bout? Why yu glow like dat enywey? Yu dicted to gamma gulp?}

{320}{}{Lissen glow-lady, der is NO KNIFE MAN! He not walk no-place cuz ders no one but yu 'n me!}

{330}{}{I tink yu pretty, glow-lady, but yu too crazy to be gud fit fer me. Sumtime yu not even makin no sense! Yu need help, but I dun' no how tuh give. So, uh... I go now, kay? Bu-bye!}
