{100}{}{你看见了个矮胖的修女。}
{101}{}{你看见了伊莱恩。}
{102}{}{你仍旧看见她。}

{200}{}{祝福你!}
{201}{}{你好，你叫什么名字？}
{202}{}{关于这你能告诉我些什么？}
{203}{}{再见。}

{300}{}{如果你想知道更多关于我们的工作，和我们的领导者谈谈吧。他在三楼。}
{301}{}{明白了。再问几个问题……}

{400}{}{例如？}
{401}{}{你叫什么名字？}
{402}{}{不要在意，回见。}
{403}{}{关于这你能告诉我些什么？}

{500}{}{叫我伊莱恩。}
{501}{}{明白了。再问几个问题……}

#{600}{}{Hey! Before you go, perhaps you could do me a favor. I'm supposed to bring this machine part to Max in the basement copy room. But you see, my left knee has been acting up lately, and it's a real pain for me to go up and down all those stairs. Would it trouble you too much to bring him this part for me?}
{600}{}{嘿！在你走之前，也许你可以帮我个忙。我应该把这个机器部件给地下室的麦克斯。但你瞧，最近我的左膝不太听话，如果跑上跑下非疼死我不可。你能帮我这个忙吗？}

#{601}{}{Sure.}
{601}{}{当然。}
# {602}{}{Sorry, I don't have time for this. Bye.}
{602}{}{抱歉，我没有时间。再见。}
# {603}{}{Do I look like your personal delivery service? Do it yourself, you fat lazy bitch. Bye.}  #new in RP 1.3
{603}{}{我看起来像你的私人快递员吗？自己做吧，你个又肥又懒的婊子。拜。}  #new in RP 1.3

# {604}{}{Thanks! Here's the part. The copying room is in the basement. Just use the stairs directly behind Brother Matthew in the chapel area.}
{604}{}{谢谢！拿好了。影印室就在地下室里。礼拜区马修兄弟后边的楼梯可以下去。}
# {605}{}{Not a problem. [You take the part.] I'll bring it down to Max right away.}
{605}{}{没问题。[你接了过来。]我会立刻交给麦克斯的。}

#dumb dialgoue
# {700}{}{Me }
{700}{}{我 }
# {701}{}{. Who you?}
{701}{}{。谁你？}

# {710}{}{Hehe. That pretty name.}
{710}{}{呵呵。漂亮的名字。}
# {711}{}{Bye!}
{711}{}{拜！}

# {720}{}{You're a special little guy aren't you? Could you do me a BIG favor and be my special helper today?}
{720}{}{你是个特别的小家伙，对不对？今天你能不能做我的特别救星，帮我个大大的忙？}
# {721}{}{You're a special little gal aren't you? Could you do me a BIG favor and be my special helper today?}
{721}{}{你是个特别的小姑娘，对不对？今天你能不能做我的特别救星，帮我个大大的忙？}
# {722}{}{Me special. Me help.}
{722}{}{我特别。我帮忙。}
# {723}{}{Me no wanna help.}
{723}{}{我不要帮忙。}

# {730}{}{Really? Great! Please give this machine part to Max in the copying room. He can be found in the BASEMENT. Okay?}
{730}{}{真的？太棒了！请把这个机器零件交给影印室的麦克斯。就在地下室里，明白？}
# {731}{}{I no let you down!}
{731}{}{我，不让你失望。}

# {740}{}{You keep on truckin' now.}
{740}{}{你继续忙忙吧。}