#You see a grave marker.
{100}{}{你看见了一个墓碑。}
#The grave marker reads: 
{101}{}{墓碑上写着：}
#"Here lies Brother Gregory. A man who knew no limits."
{102}{}{"长眠于此的是格雷戈里修士。一个无人不知的人。"}
#"Aunt Patty. Good riddance indeed."
{103}{}{"帕蒂姑妈。可喜的解脱"}
#Here lies Per Joner. Died one rock too short.
{104}{}{"长眠于此的是乔恩。是被石头砸死的。"}
#Here lies Father Michael. Founder, Father, Fighter.
{105}{}{"长眠于此的是麦克尔。创始人，父亲，战士。"}
#An Atheist. All dressed up and no place to go.
{106}{}{"老钱，德克斯翻译者长眠于此。"}
#"Here lies Johnny Yeast. Pardon me for not rising."
{107}{}{"乔尼·酵母躺在这里，请原谅我没有站起来。"}
#"Mary Jane. Loving wife and mother."
{108}{}{"karlock.星辰，他让一切能运行了，值得一提的是他挖坑的本事无人能敌"}
#"'Checkmate!' was the call to dear old Jon, On the chessboard of life, He was just a pawn.
{109}{}{"国王" 是亲爱的老乔恩的称号，在棋盘上的一生，他只是一个小卒。}
#"Sir John Strange, here lies an honest lawyer, and that is Strange."
{110}{}{"ipisgfx，因自不量力汉化什么F2_Restoration_Project，结果落得个长眠于此！"}
#Tears cannot restore her -- therefore I weep.
{111}{}{"Delete1204，这家伙竟然敢搞什么RP2.33的汉化，我们把他埋得很深"}
#Every day in every way, I am getting better and better.
{112}{}{"校对者b13，可喜的解脱。"}

#There are no markings on this grave marker.
{250}{}{"这个墓碑上没有字"}
#The grave marker is too cracked and broken to be read.
{251}{}{"这个墓碑已经严重破碎了，看不清上面的字了"}
#The name on the grave marker reads John Doe.
{252}{}{这个墓碑的名字是某约翰。}
#The name and date on this headstone have been worn off by the weather.
{253}{}{这个墓碑上的名字日期已经被风化了，你隐约看到“no v a ra in”。}