{100}{}{你看见一个商人。}
{102}{}{你看见这个商人在试着修理这个抽水泵。}
{103}{}{只差一点我就能让这玩意动起来。}
{104}{}{看上去修起来非常困难。}
{105}{}{这是什么狗屎！}
{106}{}{真是个烦人的东西。}
{107}{}{你能伸手帮个忙吗？}
{108}{}{也许你对这个运气会更好一些。}
{109}{}{嗨，谢谢你修好的抽水泵。}
{110}{}{你应该向修士长通报一下抽水泵现在修好了。}
{200}{}{谢谢帮我们做这个。}


{300}{}{我现在很忙，你找我什么事。你是有什么需要，还是说你只是个想浪费我时间的混球？}
{301}{}{实际上是，修士长叫我来的。他说这个抽水泵有一点问题。}
{302}{}{嗯哈，“有一点问题”只是保守说法。这已经完全坏了。已经没法再起动了。}
{303}{}{好吧，介意我查看一下吗？我答应过修士长看看我能做点什么。}
{304}{}{当然，我的客人。你也不可能再把它弄的更糟了。}
{305}{}{我无意打扰，不过看上去有些故障？}
{306}{}{阿比的主抽水泵坏了。最糟的是这样下去再过几天农作物会慢慢死去的。}
{307}{}{我有个工程学学位，介意我看看吗？}
{308}{}{好吧，我对机械不是非常在行，不过或许我能找出问题所在。}
{309}{}{没问题，没人会阻止你。}
{310}{}{噢，对不起，再见。}
{311}{}{我会知道我能做什么了。}

#added in 1.3
#{312}{}{I thought I might be able to help, but if you want to be an asshole about it, then you're welcome to figure it out on your own.}
{312}{}{我想我也许能帮上忙，但如果你想仍旧是这种态度。那我欢迎你自己来解决。}

#{313}{}{I told the Abbot I'd be willing to help, but if you want to be an asshole about it, then you're welcome to figure it out on your own.}
{313}{}{我告诉院长我愿意帮忙，但如果你想仍旧是这种态度。那我欢迎你自己来解决。}

#{320}{}{[He squints at you for a moment, then slowly lets out his breath in a sigh.] Sorry friend, this thing's being a real bitch, and it's gotten me all worked up. I didn't mean to snap at ya. }
{320}{}{[他愣了好一会，然后叹了口气。] 对不起，朋友，这东西真烦人，它把我整个工作都打乱了，我不是故意要骂你的。}

#{321}{}{Well, what seems to be the problem then？}
{321}{}{那么，问题出在哪里呢？}

#{322}{}{Whatever, bye.}
{322}{}{再见。}

#{330}{}{Come back and talk to me in the morning.}
{330}{}{早上再回来和我谈谈。}

#end added

{400}{}{噢，又是你，一切顺利吗？}
{401}{}{不，事情我还在办。搞定后我会回来的。}
{402}{}{实际上是，我查看了一下看上去是发动机坏了。原因发电机太旧，线圈已经烧掉了。找个新的发电机再重新连上电线就行了。}

{500}{}{嗯……主发动机挂了？好吧，我找一些新连接器来就能工作了。不过没有新的发动机。我想地下掩体城会有那玩意。去那找哈利，告诉他戴夫叫你来的。这玩意很贵，不过他会给你折扣的。}
{501}{}{我现在就去那，马上回来。}

#added in 1.3
#{502}{}{Whoa, hold on a second. I was happy to help you figure out the problem, but who said I'm willing to trek across the wastes to go buy you an expensive motor？ If you want my help, it's going to cost you.}
{502}{}{等一下。我很乐意帮你解决这个问题，但谁说我愿意长途跋涉，去买一个昂贵的零件？如果你需要我的帮助，你就得付出代价。}

#{503}{}{How 'bout *you* tell Harry that when you go fetch it your damn self? I'm not your fucking errand boy. Bye.}
{503}{}{你怎么跟哈利说，当你去把它找回来的时候？我不是你的差事。再见。}

#{510}{}{Alright, I wouldn't expect someone to do work for free. The part will cost you bout 500 and I think 100 more for your trouble is reasonable. Here's 600.}
{510}{}{好吧，我不希望有人免费工作。零件应该需要花掉你大约$500，我想再给你$100应该足够作为麻烦你的合理费用，这是$600。}


#{511}{}{That's better. I'll be back with the part.}
{511}{}{这不错，我马上就回来。}

#end added

{600}{}{一切顺利吗？这机器可不会修好自己。}
{601}{}{正在做呢。我找到就会回来的。}
{602}{}{是的，东西在这。}

{700}{}{太好了，要我装上去还是你愿意效劳？}
{701}{}{我想我能操作它，让开一点。}
{702}{}{实际上，我想我已经做的够多了。你自己装吧。}

{800}{}{很好，交换一下。}
{801}{}{你请吧。}

{900}{}{做这事。}
{901}{}{抽水泵被修好了。}

#if head monk gives you the quest
{910}{}{[擦着额头的汗]是的，需要什么？}
{911}{}{修士长说你需要一些帮助。似乎出了什么问题？}
{912}{}{别介意。再见。}
#already looked at water pump
#{913}{}{I took a look at the water pump and it seems the motor is completely busted. The connections are shot, so we're going to have to get our hands on a new motor, as well as some wires to reconnect everything since the old wires are fried.}
{913}{}{我已经看过了，问题的原因是水泵的发电机太旧，线圈已经烧掉了。找个新的发电机再重新连上电线就行了。}
