{100}{}{你看见修道院的墓地管理员。}
{101}{}{你看见塞缪尔修士，墓地管理员。}
{102}{}{他看上去喝高了，一副昏昏欲睡的。}

{200}{}{*摇摇晃晃* 什么，[打着酒嗝~]我的名字是塞缪尔，什么风把你带到这来了[打着酒嗝~]？}
{201}{}{*摇摇晃晃* 嗨，又见面了。}
{202}{}{我是到处走走，你是这个墓地的管理员吗？}
{203}{}{你认识塔里神父吗？}
{204}{}{塔里神父，你说？[他开始敲打他的头试着想起什么]对...我 *摇摇晃晃*记得塔里。 那伙计做了什么？从他被这踢出去很多年我都没见过他了。那个小子是一个古怪的人，他和我很象[他醉醺醺的笑了笑]。}
{205}{}{他现在住在新里诺，在那里做。。。嗯~~类似宣讲福音的事。知道吗，你们俩有很多相似之处。}
{206}{}{在新里诺？哈 [他靠在铲子上，拿出一个小瓶大口喝了几口] 我记他说他会*摇摇晃晃*朝那去的。我很高兴他在那很安全。我一直*摇摇晃晃*都很喜欢那伙计。如果你再见到他告诉他塞缪尔仍然活的好着呢。}
{207}{}{我会的。我还有一些别的问题。}
{208}{}{我会的。保重，塞缪尔}
{209}{}{别介意。对不起打扰你。}
{210}{}{实际上我只是来替他问声好的。我也会帮你向他问好的。我还有一些别的问题。}
{211}{}{实际上我只是来替他问声好的。我也会帮你向他问好的。保重，塞缪尔。}

{300}{}{你想知道些什么？*打嗝*}

{301}{}{你是这个墓地的管理员吗？}
{302}{}{关于阿比你能告诉我些什么？}
{303}{}{我能帮你什么事吗？}

#are you the keeper here?
#{400}{}{Yes, *hickup* I tend to these 'ere graves. Nobody else wants to *hickup* do it, so Ol' Sammy got th' job. It'snot as bad as one might think. It's got its?perks, if you know what I mean. [He grins sloppily and wiggles his bushyeyebrows at you.]}
{400}{}{是的，我比较喜欢看守这些“坟墓”，没人喜欢这个工作，所以，塞缪尔得到了工作。说实在的，这里其实这并不像人们想象的那么糟糕。它有额外的好处，如果你知道我的意思。[他咧嘴一笑，朝你挑了挑眉毛。]}
#new in RP 1.3
#{401}{}{No. I don't know what you mean, and I never want to. Bye.}
{401}{}{不。我不知道你的意思，也不想知道。再见。}
#{402}{}{No. I don't know what you mean. But I think I'd rather ask you something else. }
{402}{}{不。我不明白你的意思。但是我想我还是问你点别的吧。}
#{403}{}{No. I don't know what you mean, but I'm morbidly curious...}
{403}{}{不。我不明白你的意思，但我很好奇...}
#{404}{}{Hell yeah I do. Nothing turns me on like a rotten cadaver.}
{404}{}{是的，我懂的，没有什么比腐烂的尸体更让我兴奋了。}
#{410}{}{Why, I get to be outdoors, and no one's 'round to tell Ol' Sammy when he's had enough. I *know* when I've'ad enough... when 'ere's none left！ [He cackles, which quickly turns into a hideous cough. After coughing up a lungor two, he smiles at you.]}
{410}{}{为什么我更喜欢呆在教堂外面而不是里面呢，因为我很自在，周围没人说老塞缪尔喝多了。什么时候喝够了我说了算，那就是酒瓶空了的时候！[他举起酒瓶，咯咯地笑起来，很快就变成了可怕的咳嗽。他咳了足足有一刻钟之后对你笑了。]}

#{411}{}{Oh, of *course* that's what you meant. [Sigh of relief.] Let me ask you something else, though.}
{411}{}{哦，当然，我明白你的意思[你松了一口气]不过，让我问你另外一件事。}
#{420}{}{[His eyes go wide with shock and he seems to instantly sober.] That's not what I meant, you...you MONSTER！ FIEND！Get away from me！ }
{420}{}{[他因震惊而睁大了眼睛，他似乎立刻清醒了] 我说的不是这个意思，你...你这个怪物！恶魔！远离我！}
#{421}{}{Whatever, you drunk old fuck. You don't know what you're missing.}
{421}{}{无论如何，你喝太多了，你不知道自己错过了些什么。}

#{430}{}{Foul demon！ Be gone！}
{430}{}{肮脏的恶魔！滚开！}

#Tell me about abbey
#{500}{}{The Abbey, well, this place *hickup* has been my 'ome fer most of my life. Everone 'ere *hickup* is nice, andanyone's welcome, long as they *hickup* don't cause trouble. I, myself, don't spend too much time in th'mona-*hickup*-monastery, but I know our 'puters have all kinds of info that's been collected over th' years. Maybesome of it *hickup* might be of some use to you.}
{500}{}{修道院，嗯，这个地方是我一生中最喜欢的地方。每个人都很好，任何人都欢迎，只要他们不惹麻烦。我，我自己，不想花太多时间在修道院，但我知道我们有各种各样的信息，这些信息已经收集了很多年了。可能对你有些用处。}

#{501}{}{You don't spend much time in the church? You are a monk, aren't you?}
{501}{}{你不想待在修道院？但你是个修士，不是吗？}
#{502}{}{[He grins, revealing a gap filled set of rotten teeth.] Well, *hickup* let's just say that th' other monks don'ttake *hickup* too kindly to my, uh, drinking habits.}
{502}{}{[他咧嘴一笑，露出了一嘴烂牙。] 哦，那这么说吧，其他的修士对我爱喝酒的习惯都不太友好。}
#{503}{}{Makes sense I guess. I got some more questions.}
{503}{}{有道理，我还有一些问题。}
#{504}{}{I guess so. See you around Sammy.}
{504}{}{我想是这样。再见了，塞缪尔。}
#{505}{}{I see. Look I must be going.}
{505}{}{我明白了。我得走了。}

#Need any help
#{600}{}{Hmm... *hickup* lemme...lemme tink a minute. Yeah, I might got somethin, if yer up to it.}
{600}{}{嗯…让我...让我想一分钟。是的，事实上我有一些麻烦，如果你愿意的话。}

#{601}{}{Uh, nevermind Sam. I must be going now.}
{601}{}{嗯，无所谓塞缪尔。我现在得走了。}
#{602}{}{Sure Sam, what do you need?}
{602}{}{塞缪尔，你需要什么？}
#{603}{}{Well, th' past coupla days I've *hickup* noticed some of these graves are bein dug up. Now, whoever's doin thisdon't appear to be gettin that far, but it's a *hickup* a pain fer me to fill 'em back up.}
{603}{}{嗯，在过去的一段时间里，我发现有些坟墓被挖出来了。现在，可是我一直都找不到原因，看起来干这事的人没有得到想要的东西，但要我把这些墓穴再填平真是要命了。。}
#{604}{}{Hmm, well did you try and figure out who has been doing this?}
{604}{}{嗯，那你有没有试着去找出是谁干的？}
#{605}{}{Sure *hickup* I tried. One night I stayed around till midnight or so and no one showed up. I must've fallen asleepsoon afterwards. Too much drinking I s'pose. [He grins, pulls out his flask and takes a hefty swig.] So, what do you*hickup* say? You wanna help out?}
{605}{}{我当然试过了，有天晚上我一直呆到半夜，但一直没事发生。我后来一定是睡着了，那天我喝得太多了。[他咧嘴一笑，拿出他的酒瓶，喝了一大口。]那么，你想说什么？你想帮忙吗？}
#{606}{}{Alright, I'll see what I can do. Do you know anything else that might help me?}
{606}{}{好吧，我看看我能做什么。你还有什么线索吗？}

#{607}{}{Well, now that you mention it, I do *hickup* 'member Mr. Peterson sayin something about hearing some noises cominfrom his field. He might know something about this. He and that pretty little wife a his live right over there.[He points to the building south of the graveyard.]}
{607}{}{哦，听你这么一说我想起来了。我听彼得森先生说他的房子附近有一些声音。他可能会知道些事情，他和他漂亮的小妻子就住在那里。[他指着墓地南边的建筑。]}
#{608}{}{I'll see what I can do.}
{608}{}{我看看我能做些什么。}
#{609}{}{I think I'll pass. I must be going.}
{609}{}{我想还是算了。我得走了。}

#{700}{}{I took care of the grave digging situation. You shouldn't have any more problems out here.}
{700}{}{我把盗墓的事情解决，你这里不会再有问题了。}
#{701}{}{Well, that's *hickup* good news. Glad I won't be falling into any more open *hickup* graves. Thanks fer th' help.}
{701}{}{这真是个好消息，很高兴我不会再掉到被掘开的坟墓里去了。谢谢你帮助。}
#{702}{}{Glad to help. I got some questions though.}
{702}{}{很高兴能帮上忙。我还有一些问题。}
#{703}{}{Well, take care then.}
{703}{}{那么，多保重了。}
#{704}{}{I don't think open graves are the real reason you're falling down Samuel, but you take it easy now.}
{704}{}{我不认为那些被挖开的墓穴是你掉下去的真正原因，塞缪尔。不过现在你不用担心了。}

#{1000}{}{*Whistle*}
{1000}{}{*吹口哨*}
#{1001}{}{*Cough* *Cough*}
{1001}{}{*咳嗽* *咳嗽*}
#{1002}{}{*Clears throat*}
{1002}{}{*清了清喉咙*}
#{1003}{}{*Cough*}
{1003}{}{*咳嗽*}
#{1004}{}{*Sigh*}
{1004}{}{*叹气*}
#{1005}{}{*Hickup*}
{1005}{}{*打嗝*}

#{2000}{}{It's been a *hickup* long day. Come back in th' morning.}
{2000}{}{这是漫长的一天 *打嗝*。明天早上再来吧。}