{100}{}{你看见一个电脑操作员。}
{101}{}{你看见保罗修士。}
{102}{}{这个修士看上去是一个电脑操作员。}

{200}{}{嗨！}
{201}{}{你好。}
{202}{}{现在，今天我备份了这些文件了吗...}
{203}{}{抱歉，我没时间。}

{300}{}{是的？}
{301}{}{你这个家伙在这有很多电脑嘛。}
{302}{}{关于阿比你能告诉我什么？}
{303}{}{和我说说你们的领导者。}
{304}{}{你知道伊甸园创造器吗？}
{305}{}{你知道哪能找到13号避难所吗？}
{306}{}{再见。}
{307}{}{我很需要知道一些特别的消息。}
{308}{}{好的，比如什么？}

{400}{}{是的，我们有。在我看来很多。每天都要备份所有的文件那真是烦人。太多资料要保存，但是这是必需的。}
{401}{}{我可以想像。我还有一些别的问题。}
{402}{}{我们是一个独立的团体。长久以来，我们都欢迎任何人表现自我。}
{403}{}{好的。}
{404}{}{他是一个好的领导者。只是在托马斯修士死了之后他有一些暴躁。}
{405}{}{什么样的怪物？}
{406}{}{我没见过，但是我认为是一只巨大的辐射蝎。}
{407}{}{为什么你认为是一只巨大的辐射蝎？}
{408}{}{因为我听见过洞穴传来的声音，听起来就像辐射蝎发出的。}
{409}{}{对。}
{410}{}{实际上我们做了。看看那里的电脑。用这个通行卡解开文件。[他给你一张通行卡]}
{411}{}{噢，非常感谢！}
{412}{}{我不知道13号避难所在那里。但在南边有一个地下掩体市，它里面有一个避难所。也许那有你需要的讯息。}
{413}{}{谢谢。}
{414}{}{我身边的电脑里有一些相关的信息。用他你需要一把通行卡。我们通常不会给任何人的，所以得先和我们的领导者谈谈获得许可。}
{415}{}{好的，谢谢。}

{420}{}{你真的读了很多书，包括非技术方面的和技术方面的，贯穿你的一生，对吧？有什么你特别感兴趣的科目的吗？}

#new in RP 1.3
#新增部分new in RP 1.3
#{421}{}{Hmm, let's see. Did you know a notch in a tree will remain the same distance from the ground as the tree grows?}
{421}{}{嗯，让我们看看。你知道树上的一个缺口会随着树的生长而与地面保持距离吗？}
#{4210}{}{Uh, no, I can't say I knew that. That's...interesting.}
{4210}{}{嗯，不，我还真不知道原来会这样。这真有趣的。}
#{4211}{}{And did you know a cucumber is 96% water?}
{4211}{}{那么你知道黄瓜是96%水吗？ }
#{4212}{}{Wow, 96%, huh? Fascinating. But, um, what's a cucumber?}
{4212}{}{哇，96%，嗯？真让人意想不到。但是，什么是黄瓜？}
#{4213}{}{其实我也没见过，但我在书上看到过有关它们的信息。[他看起来有点紧张，并压低他的声音。]我知道我们不应该去研究这些书的，但每当我抄录植物学的书的时候，我就忍不住会被它吸引进去了。植物的世界实在太迷人了。也许，如果你在旅途中偶然发现一些植物学信息，你可以把它带给我吗？我会非常感激你的，当然，这件事必须是我们之间的秘密。 }
{4213}{}{其实我也没见过，但我在书上看到过。[他看起来有点紧张，并压低他的声音。]我知道我们不应该去研究这些书的，但每当我抄录植物学的书的时候，我就忍不住会被它吸引。如果你在旅途中发现一些植物学信息，可以把它带给我吗？}
#{422}{}{Sure. If I come across anything like that, I'll be sure to let you know.}
{422}{}{当然.如果我遇到那样的信息，我一定会让你知道。}
#{4220}{}{I don't think I want to contribute to your plant obsession. Sorry.}
{4220}{}{你对植物着迷是你的事，我对植物可没什么兴趣。对不起。 }

#{4221}{}{Oh, well then. Fine, forget I asked.}
{4221}{}{呃，忘了我说过的话吧。}
#{4222}{}{Let me ask you something else.}
{4222}{}{让我问你一些别的事情。 }


#end
#{423}{}{Right...Well, I have some other questions.}
{423}{}{对，我还有其他问题。}

#{424}{}{would you? I'd appreciate that.}
{424}{}{你愿意吗？我会感激你的。 }

#{425}{}{No problem. I have some other questions.}
{425}{}{没问题。我有一些其他的问题。}
#{426}{}{Any time. Well, see you around.}
{426}{}{好的，回头见。}

#{430}{}{I found some information about Botany that might interest you.}
{430}{}{我找到了一些你可能感兴趣的植物学知识。 }

#{431}{}{Really?! That's great. Please, do tell immediately.}
{431}{}{真的？太好了。是什么呢。 }

#{432}{}{Fascinating! I shall take this holodisk and add it to the computer database immediately. I appreciate you
 taking the time to find this for me. Thank you for collecting this for me.}
{432}{}{这太令人着迷了！我要把这此立即添加到计算机数据库里去。感谢你，谢谢你为我收集到这些珍贵的资料。}


#{433}{}{Well you see...Understanding habitat destruction and species extinction is dependent on an accurate and complete catalog of plant systematics and taxonomy. And then this means that...}
{433}{}{你看...理解栖息地的破坏和物种灭绝是依赖于植物系统分类的准确和完整的目录。然后这意味着... }

#{434}{}{Any time. I have some other questions though.}
{434}{}{不用谢，我有一些其他的问题。}

#{435}{}{No problem. See you around.}
{435}{}{回头见。}

#{436}{}{Fascinating! I appreciate you taking the time to find this for me. Please go and upload this information to our computers.}
{436}{}{我感谢你花时间给我找这个。请把这些信息上传到我们的电脑。}

#{437}{}{No problem, I'll do that now. See you around.}
{437}{}{没问题，我现在就去做。一会见。 }

#{500}{}{Stop that, moron!}
{500}{}{停止，白痴！}

#{550}{}{That computer near me should have some information about it. You now have access, so take a look for yourself.}
{550}{}{我旁边的那台电脑应该有一些信息。你可以查一查。 }

#{600}{}{The Abbot gave me permission to access the computers here.}
{600}{}{院长允许我访问这里的电脑。 }

#{601}{}{Ah yes, I heard about what you did. Thanks for taking care of that situation. Here is the access key. [He hands you the key.] Enjoy!}
{601}{}{是的，我已经听说你为我们所做的事情了。真是太感谢了。这里是通行证。(他把钥匙递给你)好好享受吧！}

#{602}{}{Thanks. See you around.}
{602}{}{再见，回头见。}

#{650}{}{Greetings traveler! I am Brother Paul and I am in charge of the collection of information for the Abbey. What can I do for you?}
{650}{}{你好旅行者！我是保罗修士，我负责修道院的信息收集工作。我能为你做点什么？ }

#{651}{}{Nice to meet you, Paul. I have some questions.}
{651}{}{保罗，很高兴遇见你。我有一些问题。 }
#{652}{}{Nothing. See you around.}
{652}{}{没什么事，回头见。}