#ipisgfx译
{100}{}{你打开柜台找到一些文件。}
{101}{}{搜索这个柜台。}
{102}{}{[离开]}
#{103}{}{As you search through the records in the dresser, you notice a thin leather briefcase stuffed carefully far in the back.}
{103}{}{经过从头到尾搜索，你注意到一个塞满的皮制公文包在后面不远处。}
{104}{}{拉出公文包}
#{105}{}{Ignore and continue perusing.}
{105}{}{忽略然后细读。}
#{106}{}{30 minutes pass and you find nothing of importance. All that you have found out is that Chad has records documenting every moment of his life. He's a pretty boring guy actually. Just as you are about to close the drawers, you hear a cough from the front door and a handle turning...}
{106}{}{30分钟后你发现没什么价值。你找到的是Chad一生的记录文件。他是一个相当烦人的家伙。当你关上抽屉时，你听见从门传来咯一声...}
{107}{}{拉出公文包}