#ipisgfx译
{100}{}{你看见一个多功能电脑。}
{101}{}{你看见一个航空交通控制终端。}

#{102}{}{Welcome to air traffic control. This terminal controls satellite alignment for the movement of Vertibirds.Please enter a command.}
{102}{}{欢迎使用航空交通控制终端。这个终端控制飞鸟的导航卫星。请输出命令。}
{103}{}{[离线]}
#{104}{}{Align satellite to receive Enclave coordinates.}
{104}{}{连接导航卫星目标英克雷基地。}
#{105}{}{Satellite realigning. One moment please...}
{105}{}{连接导航卫星中...稍等片刻... }
{106}{}{[更多]}
#{107}{}{Realignment successful. Docking rig ready to receive incoming aircrafts.}
{107}{}{连接成功。开始加载程序...}
{108}{}{[离线]}