#ipisgfx译
{100}{}{你看见一架大型飞机。}
{101}{}{你看见一架飞鸟。}

#{200}{}{[You climb into the aircraft and access the pilot terminal.] Welcome to PoseidoNet. This terminal is limited to transmission between Enclave Vertibird squad and docking rig. Command?}
{200}{}{[你爬入飞机起动导航终端] 欢迎使用波塞冬网络。此终端仅限英克雷飞鸟小队和石油钻塔之间的连线。命令？}
#{201}{}{Status.}
{201}{}{情况}
{202}{}{[离线]}
#{203}{}{This aircraft has only enough fuel for a complete round trip flight from the Navarro outpost, to the docking rig, and back again.All procedures are fully automated and thus no intervention by crew members is needed. Current fuel status is: Full.}
{203}{}{这架飞机的燃料只够从那瓦罗到石油钻塔的一个来回的飞行。所有程序完全自动化，不需要为人干涉。当前燃料情况：满。}
#{204}{}{Fly to Oil Rig.}
{204}{}{飞向石油钻塔。}
{205}{}{[离线]}
#{206}{}{Error. Yellow Reactor Keycard not inserted. All pilots are issued this card upon clearance for takeoff.Automated flight cannot occur without the presence of this clearance card.}
{206}{}{错误。黄色通行卡没有插入。无通行卡自动飞行无法起动。}
{207}{}{插入通行卡}
#{208}{}{Shit. Looks like I will have to find this card.}
{208}{}{操，看上去我得先找到这个通行卡。}
#{209}{}{Keycard accepted. Aircraft is now activated.}
{209}{}{通行卡确认能过。飞鸟激活。}
#{210}{}{Run pre-flight diagnostics.}
{210}{}{执行飞行前诊断}
{211}{}{[离线]}

#{212}{}{Beginning system diagnostics...35% complete...75% complete...100% complete. All systems appear operational. Checking for response from docking rig...}
{212}{}{开始系统诊断...35%完成...75%完成...100%完成. 所有系统运行正常。石油钻塔应答校验...}
{213}{}{[更多]}
#{214}{}{No signal returned from docking rig. Reason: Satellites not aligned for automated docking with Oil Rig. Please make sure docking rig is aware of the presence of incoming aircrafts.}
{214}{}{没有信号从石油钻塔返回。原因：导航卫星没有和石油钻塔连接。请确定飞鸟降落被允许。}
#{215}{}{Hmm...Looks like I will have to find a way to align the satellites.}
{215}{}{嗯...看上去我还得连接导航卫星的方法。}
{216}{}{#￥%？}

#{220}{}{Aircraft currently activated. Command?}
{220}{}{飞鸟处于激活状态。命令？}
{221}{}{执行飞行前诊断}
{222}{}{[离线]}

#{230}{}{Test signal received. Retrieving docking coordinates...complete. Aircraft ready for takeoff.}
{230}{}{接收信号测试。同步中...完成。飞鸟可以起飞。}
{231}{}{出发}
{232}{}{[离线]}

#{240}{}{Aircraft is locked in on target. Flight time is approximately 6 hours. Enjoy your flight.}
{240}{}{这次飞行时间大约6小时。祝你飞行愉快。}
{241}{}{现在，到了关键时刻。是时候结束一切了。我的部落正有麻烦，我的脚一阵阵剧痛，我记不清有多久没有洗个好澡，也记不清有多久没有吃顿饱饭，我活下去就是为了这一刻。已经没办法回头了，是时候让世界瞧瞧了。}
{242}{}{ 承受的这一切，现在要偿还给英克雷了！}
#{243}{}{Hehe...Fly birdie, fly! }
{243}{}{呵呵...飞吧飞鸟，飞吧！}
#{244}{}{ save day now.}
{244}{}{ 反败为胜的时候到了。}

#beat enclave...
{300}{}{[你爬入飞机起动导航终端] 欢迎使用波塞冬网络。此终端仅限英克雷飞鸟小队和石油钻塔之间的连线。命令？}
{301}{}{情况}
{302}{}{[离线]}
{303}{}{这架飞机的燃料只够从那瓦罗到石油钻塔的一个来回的飞行。所有程序完全自动化，不需要为人干涉。当前燃料情况：空。}
{304}{}{[离线]}
