{100}{}{你看见一个流浪者。}
{101}{}{你看见一个又脏又臭的男人。}
{102}{}{你看见一个又脏又臭的女人。}

#{103}{}{嗨伙计，我们先来的。你想干嘛？}
#{104}{}{我觉得丹恩城的孩子们需要一个地方生活，我觉得这栋建筑很适合做这个。因此我来看看。}
#{105}{}{等等，什么？你不是认真的吧……}
#{106}{}{我是认真的。我们需要一栋大建筑来开办孤儿院，这正好很合适。唯一的问题是你和你的朋友住在这。}
#{107}{}{等等……你是在驱逐我吗？那一点也不酷。混蛋……开打吧！}
#{108}{}{听着，你有两个选择要么是平静的离开这，要么把你们的尸体打包扔出去。}
#{109}{}{[这个人看看了你] 不伙计，没人能让我们离开这。我们会为我们的地盘而战的。}
#{110}{}{[这个人强忍住] 好的，不需要为这么生气。不过我们能去哪？出去我们没什么任何地方可住院。}
#{111}{}{我不知道。那不是我的问题。}
#{112}{}{这样啊，你们有兴趣在孤儿院工作吗？整理一下你们自己，如果你们愿意可以做这的清洁工，你们还可以得到免费食物和一些钱。}
#{113}{}{不伙计，我改变主意了。我们不离开。我们就在这，开打吧。}
#{114}{}{那听起来不错！我会告诉我的朋友这事的。你可以相信我们。不用担心，我们会保证这些孩子安全的。}
#{115}{}{别介意。}


#{103}{}{What do you want?}
{103}{}{有什么事吗}

#{104}{}{I want you and your friends out of this building. It's come to my attention that Mom intends to turn this place
 into an orphanage to get all those homeless children off the streets. And she can't do that with you squatting here.}
{104}{}{我想让你和你的朋友离开这栋大楼。妈妈桑打算把这个地方变成孤儿院，让那些无家可归的孩子们离开街头。而你们现在占着这里，她不能这样做。 }

#{105}{}{[He snickers uneasily and glances at his fellow squatters for support.] Mom knows the deal. We're not going anywhere
 until she coughs up the money. So unless you brought us a million coins, fuck off.}
{105}{}{[他笑着说，旁边他的同伴给予他支持的目光。 ]妈妈桑知道价格。我们不会去任何地方，除非她把钱给我们。或者你给我们带来一百万个瓶盖，现在给我滚。 }


#{106}{}{Look, Mom doesn't have that kind of money, and even if she did, she'd never pay you, so just forget it. Why not show
 some decency and go squat someplace else? Those homeless kids need this place a hell of a lot more than you do.}
{106}{}{这么说吧，妈妈桑没有那样的钱，即使她有，她也不会付你钱。所以为什么不表现出一些体面，考虑一下其他地方呢？那些无家可归的孩子比你更需要这个地方。}

#{107}{}{Who're you to say who deserves what? We *like* it here. You can't make us leave.}
{107}{}{我们,更需要,这个地方，我们*喜欢*这里。你不能让我们离开。 }


#{108}{}{Listen, you have two choices: You can either walk out of here on your own two feet, or *I* can remove you -- by dragging
 you out, one corpse at a time.}
{108}{}{听着，你有两个选择：你可以靠自己的双脚走出来，或者我把*你们的尸体*打包拖出去。 }


#{109}{}{[He exchanges a look with his fellow squatters, then looks back at you and shakes his head.] You can't intimidate us.
 No one's kicking us out of here. We'll fight you for our turf.}
{109}{}{[他与同伴交流一下的人，然后回头看着你摇头。]你不能恐吓我们。没有人把我们从这里踢出去。我们将为我们的地盘而战。 }


#{110}{}{[He exchanges a look with his fellow squatters, then looks back at you and nods.] OK, you made your point. It's not like
 we hate kids or anything, hell, most of us were homeless kids ourselves. We were just trying to make some money, you know? The
 only jobs around here involve peddling drugs or pain, and we're not into that. [He sighs.] We'll leave, but where do you suggest
 we go? This place is our home.}
{110}{}{[他与同伴交流一下的人，然后回头看着你点头。]好吧，其实我们在这里，并不是因为我们讨厌孩子或者想要任何东西。我们其实也是无家可归的人。我们只是想赚点钱，你知道吗？而这里唯一的工作是贩卖毒品或者陪人睡觉，我们不想做这些事。他叹气着说：“你要我们走了，但其实我们能去哪儿？”这个地方是我们的家。}

#{111}{}{I don't know. That's not my problem.}
{111}{}{我不知道。这不是我的问题。}

#{112}{}{I may regret saying this, but if you're serious about wanting jobs, I'm sure Mom could use some help fixing this place up. She's a real nice lady,
 so maybe if you apologize, she'd give you a fair chance to prove you're more than a bunch of lazy opportunists. I'll talk to her about it. But if you try to
 fuck her over, I'll hunt you down and make you pay.}
{112}{}{我可能会后悔这么说，但如果你说的是实话，我相信妈妈桑可以帮助到你们。她是一个真正的好人，如果你道歉的话，她会给你一个公平的机会来证明你们不是一群懒惰的机会主义者，我会安排这件事。但如果你试图欺骗她，我会抓到你，并让你付出代价。 }

#{113}{}{Screw this, I changed my mind. We ain't leaving. We're staying right here and fighting.}
{113}{}{杂种！我改变了我的想法。我们不会离开。我们就在这里战斗。}

#{114}{}{[He exchanges a look with the other squatters and ponders your words.] You know what? That doesn't sound too bad. In fact, that could work out great,
 if you really think Mom will go for it. While you go talk to her, we'll get started on cleaning this place up. Oh, and thanks for being so cool about things.}
{114}{}{[他看起来与其他人交流和在思考你的话。]你是认真的吗？这听起来不太糟糕。事实上，如果你真的能让妈妈桑给予我们一个工作机会的话，那真的不错。你去和她谈谈的时候，我们会开始打扫这个地方了，谢谢你。}

#{115}{}{Nevermind.}
{115}{}{不要}

#new for RP 1.3
#{116}{}{She's not going to pay you. But I'm here to offer you a new deal: You and your friends walk away from here now, and you get to keep your lives.}
{116}{}{她不会付钱给你的。但我在这里给你一个建议：你和你的朋友离开这里，另外保住你的命。}

#{117}{}{Alright, well, I gave it a shot. Bye.}
{117}{}{好吧，我试过了。再见。}


#{120}{}{This is a great idea. We'll get things ready.}
{120}{}{这是一个伟大的想法。我们会把事情做好。}


#{200}{}{Huh?}
{200}{}{啊?}

#{201}{}{This is our turf.}
{201}{}{这是我们的地盘。}

#{202}{}{You squatting here too?}
{202}{}{你也要留在这里吗？}

#{203}{}{Got anything to eat?}
{203}{}{有什么吃的吗?}

#{300}{}{You see a man in work clothes.}
{300}{}{你看到一个穿工作服的人。}

#{301}{}{You see a woman in work clothes.}
{301}{}{你看到一个穿工作服的女人。}

#{310}{}{Hey, thanks for helping to set this up for us. We'll work hard.}
{310}{}{嘿，谢谢你，我们会努力工作。}

#{311}{}{You better. Make sure the children stay out of trouble too.}
{311}{}{干得不错，记得保护孩子也远离麻烦。}
#{312}{}{We'll do our best.}
{312}{}{我们将尽我们最大的努力。}

#{313}{}{Bye.}
{313}{}{再见.}

#third way to finish quest -added after initial creation, but before official release
#{350}{}{Anywhere but here. The Den's a big place, I'm sure you can find somewhere else to crash. Come on, do you really want the children to live on the streets?}
{350}{}{任何地方，但不是这里。丹恩是个大地方，我相信你能找到别的地方。难道你希望孩子们住在街上吗？}


#{351}{}{Nah, you're right, that ain't cool for the children. Alright, we'll pack our things and move out. This place had a leaky roof anyway.}
{351}{}{好吧，我们将收拾我们的东西搬出去。但我要说这个地方没你想的那么好，你看，屋顶都在漏水。}

#{352}{}{Thanks. This will mean a lot to them. Take care.}
{352}{}{谢谢。}

#{353}{}{Nah, that ain't our problem. If Mom thinks it's that important to get those kids off the streets, then she should stop being stingy with her cash and share the
 wealth. Yeah, I've changed my mind, we're staying until she pays up. Now this conversation's over, so you better leave if you know what's good for you.}
{353}{}{不，这不是我们的问题。如果妈妈桑认为让孩子们离开街道是很重要的，那她应该停止吝啬她的现金。是的，我改变主意了，我们会一直呆在这里，直到她把钱付清。现在对话结束了，而你最好马上离开。}


#{360}{}{Alright. No need for this to get out of control. I'll leave you alone.}
{360}{}{好吧。没有必要对这个失控。我会离开。}

#{361}{}{Time to clean this place up then. [Attack]}
{361}{}{是时候清理这个地方了。（攻击）}


#{400}{}{Thanks again!}
{400}{}{再次感谢!}

#{401}{}{We'll work hard.}
{401}{}{我们将努力工作。}

#{402}{}{Thanks for being so cool about things.}
{402}{}{谢谢你}

#{403}{}{We won't let you down.}
{403}{}{我们不会让你失望。}


#{500}{}{We'll collect our things and be out of here soon.}
{500}{}{我们会收拾我们的东西，离开这里。}

#{600}{}{You've cleared out all the squatters.}
{600}{}{你已经清除了所有的人。}