#ipisgfx译
#You see a middle aged man.
{100}{}{你看见一个中年男子。}
#He is unshaven and reaks of alcohol.
{101}{}{他满脸胡须而且一身酒味。}
#*hickup* Do I know you?
{102}{}{*摇摇晃晃*我认识你吗？}
#It`s 11 O'clock. Do you know where your children are?
{103}{}{11点了。你知道你的孩子在哪吗？}
#[Looks at you sleepily] What? *hickup* It's 11 already?
{104}{}{[他困倦的看着你] 什么？ *摇摇晃晃* 都11点了？}
#Actually no it isn't, I just wanted to say that. But seriously, do you know where your children are?
{105}{}{实际上我只是想说那个。认真的说，你知道你的孩子在哪吗？}
#Actually yeah it is, but that's not important right now. Seriously though, do you know where your children are?
{106}{}{是这样的，不过这不重要。认真的想想，你知道你的孩在哪吗？}
#*hickup* I have children? *hickup* Oh yeah, I do. He..or is it she..*hickup* should be around here somewhere.
{107}{}{*摇摇晃晃* 我有孩子？ *摇摇晃晃* 喔对，我有。 他或是她……*摇摇晃晃* 应该就在附近什么地方吧。}
#Wow, you're such a drunk. Well, good thing I am working on a way to get your child out of here.
{108}{}{噢，你喝醉了。那好吧，好事是我正在想办法让你的孩子离开这。}
#[Ignores what you just said.] Yeah that's great. *hickup* Now let me get back to this drink.
{109}{}{[不理采你刚说了什么] 太棒了。 *摇摇晃晃* 让我再来一杯。}
#You are a hero to all fathers out there. Keep it up!
{110}{}{继续吧！}
{111}{}{zzzZZZZzzz……}
{112}{}{zZZZZzzZZzzz……}
#*mumbles*
{113}{}{*含糊的说着什么*}
#Can't you see I'm drinking here? *hickup*
{114}{}{你没看见我在喝酒吗？*摇摇晃晃*}
#Don't bother me. *hickup*
{115}{}{别烦我。*摇摇晃晃*}

#Actually it is a little before 11 O'clock, but that's not important right now. Seriously though, do you know where your children are?
{116}{}{实际上是在11点以前，但是现在不重要了。说真的，你知道你的孩子在哪儿吗?}
#Actually it is a little past 11 O'clock, but that's not important right now. Seriously though, do you know where your children are?
{117}{}{实际上是在11点以前，但是现在不重要了。说真的，你知道你的孩子在哪儿吗?}
