#{100}{}{You see a small boy。}
#{101}{}{You see Little Bobby。}
#{102}{}{He is wearing dirty clothing and has bruises on his neck and face。}
#{103}{}{He is wearing new clothing and has a smile on his face。}
#{104}{}{Hi mister！ My name's Bobby and I live here with my Dad。}
#{105}{}{Hi miss！ My name's Bobby and I live here with my Dad。}
#{106}{}{I see。 Well tha-}

#ipisgfx译
{100}{}{你看见一个小男孩。}
{101}{}{你看见利特尔-约翰。}
{102}{}{他穿着一身脏乱的衣服而且脸和脖子上都有瘀伤。}
{103}{}{他穿上了新衣服而且脸上充满笑容。}
{104}{}{您好，先生！我叫约翰，我和爸爸一起住在这。}
{105}{}{您好，女士！我叫约翰，我和爸爸一起住在这。}
{106}{}{您好，你看上去不是很好，是发生了什么吗。}



#{107}{}{Are you here 'cause my dad owes you money？ I don't know if he's here or not。 But if I knew where he was，
 I'd tell you， 'cause maybe you'd beat him up so bad he wouldn't ever come home again。}
#{108}{}{This sounds horrible， Bobby。 Your father has no right to treat you that way -- no parent does。}
#{109}{}{Hah！ I'd beat my son too if he didn't listen to me。 Your father sounds like a good man。}
#{110}{}{[His eyes light up。] You aren't like the others that come through here。 I like you。 [He sighs heavily。]
 I wish my dad was more like you。 Sometimes I think about running away。 Some of my friends don't have homes， and they say
 it's not so bad。 As long as they bring Mr。 Flick enough things， they get to eat once a day。 But Mr。 Flick doesn't sound very
 nice either -- actually， he sounds a lot like my dad。}
#{111}{}{You're a meanie！ Go away。 I don't like you。}

{107}{}{你来这儿是因为我爸爸欠你钱吗？我不知道他是否在这里。但如果我知道他在哪里，我会告诉你的，因为也许你把他打一顿，他就再也不会回家了。 }
{108}{}{这听起来真可怕。没有任何父母会这样对待自己的孩子的。}
{109}{}{嘿，我儿子如果不听我的我一定会收拾他的。你老爸做的没错。}
{110}{}{[他眼前一亮] 你不像这镇子上的人。[他重重地叹了口气] 我希望我的爸爸更像你。有时我想逃离这里。我的一些朋友没有家，他们说没有那么糟糕。只要他们偷了足够多的东西，他们就能够一天吃一次饭。但是，富力克先生听起来也不是很好-实际上，他听起来很像我的爸爸。  }
{111}{}{你是个坏人！走开。我不喜欢你}



#{112}{}{There's gotta be something that can be done about this。 Can you think of any adults in this town that'd be willing to
 look after you -- or any of these homeless kids？}
#{113}{}{[Bobby shrugs。] Maybe Mom？ I don't mean *my* mom -- my mom's dead -- but there's a lady that people call Mom。 I dunno why。
 Maybe 'cause she's really nice？ She's got a diner on the other side of town。 [He points to the Northeast。] My homeless friends go
 there and she sneaks them free food。 I wish Dad would take me there， 'cause she knows how to make rat taste really yummy！}
#{114}{}{Hmm， I *am* feeling a bit hungry。 Perhaps I'll go pay Mom a visit。 You take care of yourself， Bobby。}
#{115}{}{You're such a little brat。 I better leave now before I kick the shit outta you。 Bye。}
#{116}{}{Guess what， Bobby？ I spoke with Mom， and she's going to be opening up a nice big new home where you and all your
 homeless friends are welcome to go live together。 It's going to be in the big building that's right across the street from here。
 She said she'll have it all set up in a couple days。}
 

{112}{}{我想我关于你目前的情况我必须要做些事。你能想到这个镇上的任何成年人愿意照顾你吗？ }
{113}{}{[约翰耸了耸肩] 嗯，唯一会真正担心我们的人是妈妈桑，她在城东的一家餐馆。[他指向东北]我那些流浪的朋友会偷偷地去那里，她经常免费给他们一些食物。我希望爸爸会带我去那里，因为她知道如何把老鼠肉的煮得好吃！ }
{114}{}{嗯，我感觉有点饿了。我会去找她谈一下。你先照顾好自己，约翰。}
{115}{}{你这小子。我最好现在离开，不然我就他妈的踢你。再见。 }
{116}{}{你猜怎么了，约翰？我和妈妈桑谈过了，她有一个漂亮的大房子，欢迎你和你所有的无家可归的朋友一起生活。这个大房子就在街的对面。她说她会在几天内把一切都安排好。}
 
 
 
#{117}{}{[A huge smile lights up the boy's face。] Really？ That's great！ [He hugs you。] I can't wait to live there with all my
 friends！ I'm so excited！ Thanks again mister， you're the best！}
#{118}{}{[A huge smile lights up the boy's face。] Really？ That's great！ [He hugs you。] I can't wait to live there with all my
 friends！ I'm so excited！ Thanks again miss， you're the best！}
#{119}{}{You're welcome kid。 See you around。}
#{120}{}{Hi again！ Did you talk to the Mom lady？}
#{121}{}{Don't worry Bobby， I'm working on it。}


{117}{}{[一个巨大的笑容点亮了男孩的脸] 真的？那太好了！[他拥抱你]我迫不及待地想和我所有的朋友住在那里！我很兴奋！再次感谢你，先生，你是最好的！ }
{118}{}{[一个巨大的笑容点亮了男孩的脸] 真的？那太好了！[他拥抱你]我迫不及待地想和我所有的朋友住在那里！我很兴奋！再次感谢你，女士，你是最好的！ }
{119}{}{你是个好孩子。回头见。 }
{120}{}{嗨！你和妈妈桑提过了吗？ }
{121}{}{别担心，约翰，我正在办这件事。 }


#{122}{}{You help Bobby find a better life。}
#{123}{}{Hi again！ Thanks for everything。 I love this new place。 Mom is such a great lady！}
#{124}{}{I love this new place。 Mom is such a great lady！}

{122}{}{你帮助约翰找到一个更好的生活。}
{123}{}{嗨！感谢您所做的一切。我喜欢这个新的地方。妈妈桑真是一位伟大的女士！ }
{124}{}{我喜欢这个新的地方。妈妈桑真是一位伟大的女士！}

#{125}{}{I'm so excited！ Time to pack my stuff。}
#{126}{}{I wonder if dad will notice I am gone。}
#{127}{}{This is going to be so much better。}
{125}{}{我很开心！我现在马上收拾我的东西。 }
{126}{}{我不知道爸爸会不会注意到我走了。}
{127}{}{这里是如此的好。}


#{200}{}{I don't like you。 Go away！}
{200}{}{我不喜欢你，走开！}



#{210}{}{It sounds like you're not too fond of your dad。 Mind if I ask why？}
#{211}{}{You little brat， what gives you the right to talk about your dad like that？}
#{220}{}{Cause my dad's not very nice。 He leaves me home alone all the time， and when he *is* home， he's always drunk or
 he says he's flying on jet， which is a lie 'cause I never see him fly anywhere。 Sometimes， he brings a
 girlfriend home -- he's got lots of girlfriends -- and he makes me go outside for awhile， even if its the middle of the night
 and it's cold or raining。}
#{221}{}{That's-}
#{230}{}{Oh！ And sometimes he tells me to take things from people in secret。 He says it's a game and that he gives it back later，
 but I don't' believe him。 But if I don't do it， then he gets real mad and his eyes get all scary looking， and he hurts me。
 See？ [He lifts up his shirt sleeve， revealing a nasty bruise on his arm。]}
 
 

{210}{}{听起来你不太喜欢你爸爸。介意我问为什么吗？ }
{211}{}{你这小鬼，你有什么权利来谈论你的爸爸？ }
{220}{}{因为我爸爸很不好。他总是独自离开我，当他回家的时候，他总是喝得醉醺醺的。有时他会说他在喷气飞机上飞行，但我从来没有看到他飞到任何地方。有时，他会带女朋友回家--他很多女朋友中的一个--然后他就会让我出去一会儿，那怕是在深夜、冬天或下雨天。 }
{221}{}{[继续]}
{230}{}{哦！有时他会要我从这里的旅客身上偷东西，他说这只是一个游戏，但我不相信他。但如果我不这样做，那么他就会疯了一样的打我，就像这样，看到了吗？ [他举起袖子，露出胳膊上的一块块的瘀青]}


