#{100}{}{You see MIBoba Fe88。}
#{101}{}{You see a tough, ruthless bounty hunter。}
#{200}{}{You see Hivan Zolo。}
#{201}{}{A scruffy lookin', but handsome rogue。}
#{300}{}{You see Contie-bacca。}
#{301}{}{He looks like a walking carpet。}

{100}{}{你看到MIBoba Fe88[詹戈·费特]。}
{101}{}{你看到一个无情的赏金猎人}
{200}{}{你看到Hivan Zolo[汉·索罗]。}
{201}{}{一个看起来很邋遢，但相貌却很英俊的游侠。}
{300}{}{你看到Contie-bacca[楚巴卡]。}
{301}{}{他看起来像一块行走的地毯。}

#{400}{}{You see Darek Vader。}
#{401}{}{This guy looks hard as hell and appears to be more machine than man。}
#{500}{}{You see Jotisz the Hutt。}
#{501}{}{This guy is big, fat and green。}
#{600}{}{You see R2Qwerty。}
#{601}{}{A feisty little robot。 He flashes and beeps。}
#{700}{}{You see Chris3ParksO。}
#{701}{}{A shiny gold humanoid robot。 He looks surprised。}

{400}{}{你看到Darek Vader[达斯·维德]。}
{401}{}{这个家伙看起来很可怕，而且看起来比人更像机器。}
{500}{}{你看到Jotisz the Hutt[赫特人贾巴]。}
{501}{}{这个家伙又大又肥又绿。}
{600}{}{你看到R2Qwerty[R2D2]。}
{601}{}{一个精力充沛的小机器人。他闪烁，哔哔声。}
{700}{}{你看到Chris3ParksO[3PO]。}
{701}{}{一个闪亮的金色人形机器人，他看上去很让人惊讶。}

#{800}{}{You see Yosan12。}
#{801}{}{A little green guy。 He looks OLD。}
#{900}{}{You see Obi-Wan-Killap。}
#{901}{}{He seems like a kindly old man with something slightly bear-like about him。}
#{1000}{}{You see Empress Timeslip。}
#{1001}{}{You see a mean-looking cloaked figure with a stoop。}
#{1100}{}{You see Luke Skynet。}
#{1101}{}{A hooded figure who looks quietly confident。}

{800}{}{你看到Yosan12[尤达大师]。}
{801}{}{一个小绿人，他看上去很老。}
{900}{}{你看到Obi-Wan-Killap[欧比·旺·肯诺比]。}
{901}{}{他看起来像一个和蔼的老人，但你隐约觉得他很强大。}
{1000}{}{你看到Empress Timeslip[皇帝帕尔帕廷]。}
{1001}{}{你看见斗篷笼罩着他自负而刻薄的脸。}
{1100}{}{你看到Luke Skynet[卢克天行者]。}
{1101}{}{一个戴着兜帽的人，他看起来很自信。}

#{1200}{}{You see Mon-Morticia。}
#{1201}{}{A very diplomatic looking lady。}
#{1300}{}{You see Kanhef。}
#{1301}{}{Now HE looks like a great guy。}
#{1400}{}{You see HawkEyE。}
#{1401}{}{A glittering gem of hatred。}
#{1500}{}{You see Adam Dravean。}
#{1501}{}{He nods in your direction。}

{1200}{}{你看到Mon-Morticia。}
{1201}{}{一个穿着正式的女士。}
{1300}{}{你看到Kanhef。}
{1301}{}{现在他看起来像个强大的家伙。}
{1400}{}{你看到HawkEyE。}
{1401}{}{一个闪闪发光的仇恨的宝石。}
{1500}{}{你看到Adam Dravean。}
{1501}{}{他朝你点头。}

#{1600}{}{You see Mr。 Wolna。}
#{1601}{}{This guy is seriously enthusiastic……}
#{1700}{}{You see encinodude。}
#{1701}{}{He looks like a good guy。}
#{1800}{}{You see Minigun Jim。}
#{1801}{}{He is wearing a Red Dwarf T-shirt under his armor。}
#{1900}{}{You see Bofast。}
#{1901}{}{He stands up straight as he sees you looking at him。}

{1600}{}{你看到Mr.Wolna。}
{1601}{}{这个家伙真的非常热情……}
{1700}{}{你看到encinodude。}
{1701}{}{他看起来是个好人。}
{1800}{}{你看到Minigun Jim。}
{1801}{}{他在他的铠甲下面穿着一件红色的T恤。}
{1900}{}{你看到Bofast。}
{1901}{}{当你看着他时，他站直了。}

#{2000}{}{You see Pixote。}
#{2001}{}{You see a noble repair bot。}
#{2100}{}{You see Mash。}
#{2101}{}{He nods at you。}
#{2200}{}{You see Mikael Grizzly。}
#{2201}{}{This animal is extremely furry。}
#{2300}{}{You see x'il。}
#{2301}{}{He looks at you with admiration。}
#{2400}{}{You see a pile of rocks。}
#{2401}{}{There is a plaque on the rocks。}
#{2500}{}{You see a large mass of goo。}
#{2501}{}{This mass of goo seems to spell out something: "Dedicated to all those whose names have been forgotten, but yet helped make everything possible。"}  
{2000}{}{你看到Pixote。}
{2001}{}{你看到一个高雅的修理机器人。}
{2100}{}{你看到Mash。}
{2101}{}{他向你点头。}
{2200}{}{你看到Mikael Grizzly。}
{2201}{}{这动物真是全身长满了毛发。}
{2300}{}{你看到x'il。}
{2301}{}{他钦佩的看着你。}
{2400}{}{你看到一堆石头。}
{2401}{}{在岩石上有一块牌子。}
{2500}{}{你看到一堆粘液。}
{2501}{}{这堆粘液似乎在说同一句话：“献给那些不知名，却提供了帮助，使这一切成为可能的人。"} 

#MIB88
#{110}{}{You see a tough, ruthless bounty hunter。 He doesn't look like he talks much。 He helped with the new scripts and ideas。 And with killing people。}
{110}{}{你看到一个严肃的，无情的赏金猎人。他看起来并不多话，他协助提供了新的脚本和想法，另外他还杀了不少人。}

#Polish Translator - Ivan Zaharath
#if energy weapons > 100
#{210}{}{Kid, I've flown from one side of this galaxy to the other, and I've seen a lot of strange stuff, but I've never seen *anything* to make me believe that there's one all-powerful Force controlling everything。 'Cause no mystical energy field controls *my* destiny。 It's all a lot of simple tricks and nonsense。 Hokey religions and ancient weapons are no match for a good blaster at your side。 I can tell when a guy is handy with a gun, so take this。 Trust me: it'll come in handy when you've got a price on your head。 [He hands you a blaster。]}
#{211}{}{My real name is Ivan Zaharath。}
#{212}{}{I translated the RP into Polski for the benefit of the great and powerful Republic of Poland …… I mean Rebel Alliance。}
#{213}{}{Laugh it up, fuzzball。}
#{214}{}{Hokey religions and ancient weapons are no match for a good blaster at your side, kid。}
#{215}{}{Who're you callin' 'scruffy lookin'！？}

{210}{}{小子，我什么地方都去过。也见过不少奇怪的东西，但是我却永远不能相信有一种力量能控制一切。没有任何奇怪的力量能够控制我的命运，这只是些小把戏用来唬人的而已。那些虚伪的宗教和古老的武器并不怎么适合你，比起一把爆能枪来说不算什么。我知道一个人什么时候需要枪，所以带上它。相信我：关键时刻这玩意能救你命。[他给了你一把大家伙，爆能枪]}
{211}{}{我真名叫做Ivan Zaharath。}
{212}{}{我将RP的文本翻译成了波兰语，让它能够给强大、伟大的波兰共和国带来好处……我说的是反抗军同盟。}
{213}{}{瞧瞧吧，绒球。}
{214}{}{那些虚伪的宗教和古老的武器，根本比不上一把爆能枪。}
{215}{}{嘿嘿，你在叫谁脏鬼！？}

#Continuum
{310}{}{Roow rooo arrrrr rooow。}
{311}{}{Rrrrrrrrrrrrr ……。 squeak！}
{312}{}{Nowrrrrragh。}
{313}{}{Yawrrrk！}
{314}{}{Roow rooo Nowrrrrragh！}

#When player clicks on Contie-bacca, Chris3ParksO translates:
#{315}{}{He says he's Continuum, and he made new & unique graphics。}
#{316}{}{He says he made them using 3D modeling。 He's quite clever you know。 For a human。}
#{317}{}{He says he's not speaking Czech-speak, though it does sound a bit like baby-talk。}
#{318}{}{He says it's not a crossbow, it's a blaster。 And no you can't have it。}
#{319}{}{He says you should thank him for bringing the sub back into the game。}

{315}{}{他说他在这次制作里面是贯穿始终的，他创造很多全新独特的图片。}
{316}{}{他说是他很聪明的，他是用3D模型制作这些东西的。}
{317}{}{他说他不会说捷克语，因为听起来有点像婴儿说话。}
{318}{}{他说这不是一个十字弓，它是一个电浆枪。不，他不能给你这个。}
{319}{}{他说你应该感谢他把潜艇带进了游戏。}


#Darek
#{410}{}{I'm Darek。 I helped answer a million noob questions for Obi-Wan-Killap。}
#{411}{}{Join me！ Together we can rule the galaxy！}
#{412}{}{Did you know that the great Obi-Wan-Killap asked ME for help？}
#{413}{}{Don't tell Obi-Wan-Killap, but I think he might be losing his mind。}
#{414}{}{I helped squash several nasty bugs。 You can thank me later。}

{410}{}{我是Darek。 我为Obi-Wan-Killap解决了一千万个愚蠢到极点的问题。}
{411}{}{加入我！我们一起可以统治银河系！ }
{412}{}{你敢相信强大的Obi-Wan-Killap竟然需要我的帮助？}
{413}{}{不要告诉Obi-Wan-Killap，不然他很可能要疯掉。}
{414}{}{我帮助粉碎了成吨的漏洞，别急着谢我。}


#Jotisz
#{510}{}{I'm Jotisz the Hutt。 I may look like a big fat green slug, but I actually helped create those nice new armored threads your buddy Sulik is wearing。 Those were created by Yosan12 and me。 I know！ And with these stubby hands！}
#{511}{}{I'm Jotisz the Hutt。 I may look like a big fat green slug, but I actually helped create those nice new armored threads your buddy……hey where is Sulik？ You should go get him and see how he looks。 His threads were created by Yosan12 and me。 I know！ And with these stubby hands！}
#{512}{}{*whistles* I'm a big fat green slug……}
#{513}{}{In case you didn't notice, I'm suspiciously easy to strangle。}
#{514}{}{Now, where did I put Leia……？}

{510}{}{我是赫特人Jotisz，我可能看起来像个大胖子，但实际上我帮你创造了你的朋友史克力穿的那些漂亮的新护甲，
这些是由Yosan12和我一起创造的！}
{511}{}{我是赫特人Jotisz。我可能看起来像一个绿色的大鼻涕虫，但实际上我帮助创造了史克力穿的那些漂亮的新护甲}
{512}{}{[吹口哨]我是一个巨大的绿色鼻涕虫……}
{513}{}{注意别踩到我。}
{514}{}{现在,我把莱娅在哪里放在那里了？}

#Wild Qwerty
{610}{}{Beep beep！}
{611}{}{Rrrrrr beep Rrrrwow！}
#{612}{}{*flashes and jiggles excitedly*}
#{613}{}{Crossbows！ Tactics！ Crossbows！}
{612}{}{*兴奋地晃动*}
{613}{}{战斗！ 战斗！ 战斗！}

#Chris Parks
#{710}{}{Hi, I'm Chris3ParksO, human-cyborg relations。 I am well versed in over 3 million programming languages。}
#{711}{}{I helped lay the groundwork for the Umbra Tribe and the EPA。}
#{712}{}{This is R2QWERTY: my faithful sidekick。 He created new critters and graphics。}

{710}{}{你好，我是Chris3ParksO，人机关系专家。我精通300多万种编程语言。}
{711}{}{我为暗影部落和EPA打下了坚实的基础。}
{712}{}{这是我忠实的助手：R2QWERTY。他创造了新的生物和图形。}

#Josan12
#{810}{}{Yosan12 am I。 Created the NPC armor mod I did。 Lift Xwing from swamp did I too。 Talk in strange very also way do I。 Difficult to understand, hmmm？ Hagh Hah ha！ Also, created the new Sniper, Wakizashi and lightsaber animations I did。 }
#{811}{}{Remember: anger, fear, hatred: of the dark side are they。}
#{812}{}{When gone am I, a little fuzzy glowing ghost will I become。}
#{813}{}{Once, a puppet with wisdom and character was I。 Now, a hollow, CGI character for the kids I have become。}
#{814}{}{Stupid JarJar Binks is。}

{810}{}{Yosan12是我。创造了NPC护甲我，我也用奇怪的方式说话。很难理解，对吧？哈哈哈！另外我创建新的狙击动作,光剑动作我。}
{811}{}{记住:愤怒，恐惧，仇恨，黑暗的另一面就是他们。}
{812}{}{当我离开的时候，我会变成一个模糊的发光的幽灵。}
{813}{}{曾经我是一个有智慧和性格的角色。现在，我变成了一个只有几句对话的配角。}
{814}{}{愚蠢的JarJar Binks。}

##Killap
#{910}{}{Greetings }
#{911}{}{。 I see you've been doing quite well for yourself。 I'm Obi-Wan-Killap: I make Fallout work like it should have from the very beginning。}
#{912}{}{Wow。 Well, thank you for that, Mr。 Killap。 How did you do it？}
#{913}{}{What the Hell is Fallout？}
#{914}{}{Ok。 And who, pray tell, are these other people？}
#
#{920}{}{I am a Programming Master, skilled in the way of 原码力。 It is an energy field created by all digital things。 It surrounds us and penetrates us。 It binds the galaxy together。 You, me - the tree - the rock。 Pixilated beings are we……。not this crude matter *pokes you*。 I have learned to use this power through years of staring at a computer screen。}
#{930}{}{Fallout is the world you are in。 I created it, or at least, made it work like it was supposed to。 You see, not long ago, this world was in chaos。 Travelers that came here were often killed by the huge number of bugs that roamed the wasteland corrupting saved games indiscriminately。 The gods of this world had been careless。 But then I came, and, using the power of 原码力, my friends and I cleaned up the wasteland。 You could say I am the savior。 I am seen by many as a hero: The Bear Dude。}
#{940}{}{These are my companions。 They helped me improve this world: MIBoba Fe88, Hivan Zolo, Contie-bacca, Darek Vader, Jotisz the Hutt, R2Qwerty, Chris3ParksO, Yosan12, Empress Timeslip, Luke Skynet, Mon-Morticia, Kanhef, HawkEyE, Adam Dravean, Mr。 Wolna, encinodude, Minigun Jim, Bofast, Pixote, Mash, Mikael Grizzly, x'il, Per, and the Masses。 They all helped in the great project to restore this world from the bug infestation。 The only good bug is a dead bug。} 
##response to 920
#{921}{}{Wow。 Our shaman always said there was more to this world than what I can see, hear, touch, taste and feel。 Can you teach me to use the power of 原码力？}
#{922}{}{I think I've heard enough religious mumbo-jumbo to keep me stocked for another nuclear winter。 Frankly, I prefer a plasma pistol at my side。}
#{923}{}{Oh great, another kookie religious nutbag。 I'm outta here。}
#
##response to 930
#{931}{}{I see。 Well, actually, I was under the impression I was the hero of this story。 I run around looting shit and killing people - you know - heroically。 Oh, and I talk to them sometimes, but that part can get tiresome。 I just click through it to get to the fun bit。}
#{932}{}{Great work, Mr。 Killap。 I really appreciate all your time and hard work spent cleaning up the wasteland。 If what you say is true, then you should know that I, too, am a hero。 In fact, I've squashed quite a few bugs myself。}
#
#{935}{}{And we are grateful that you have destroyed the Enclave。 You are the true hero here。}
#{936}{}{Whatever gets you through the day。}
#
##response to 935-936
#{937}{}{So, how exactly did you clean up this world？}
#{938}{}{Who, pray tell, are these other people？}
#
##response to 940
#{941}{}{Hmm。 those names somehow sound familiar…… Well, I think I'll go talk to them。}
#
##response to 921
##player > level 15
#{950}{}{Indeed I can。 You must learn to use your feelings: let go of your conscious mind。 Turn off the monitor。 Close your eyes, and FEEL 原码力 flowing through the mouse …… [Follow his instructions。]}
#{951}{}{You lack the experience to start training。 Return to me when you've at least learned some basic Programming, young padawan。}
#
#{960}{}{As you wish, young }
#{961}{}{。 But before you go on your way, remember this: Many of the truths we cling to depend greatly on our own point of view。 Now go, and may 原码力 be with you。}
##player has high karma
#{962}{}{。 Your actions on your quest have proved you good, kind and honest。 Take this to aid you in your struggle against the Dark Side: it is your ancestor's light saber。 This is the weapon of a Java Knight。 Not as clumsy or random as a blaster; an elegant weapon for a more civilized age。 And though you may be tempted to use it to arbitrarily cut people in half for entertainment, you should use it only in service of good。 Good luck, and may 原码力 be with you, my friend。}
#{963}{}{What？！ My ancestor, The Vault Dweller, had one of these？！ I don't remember finding this in Fallout 1！ *run off to check*}
#{964}{}{Thank you, Mr。 Bear Dude。 For everything。 May 原码力 be with you too。}

{910}{}{你好 }
{911}{}{ 。你已经完成了你应当做的。我是Obi-Wan-Killap：是我让Fallout变得看起来像它原本应当的样子。}
{912}{}{哇，好的，谢谢你，Killap先生。你是怎么做的？}
{913}{}{什么是Fallout？}
{914}{}{好的，谁告诉我下，这些人是谁？}

{920}{}{我是一个编程大师，遵循原码力之路。它是由所有数字化而创造的一个能量场，它包围着我们，穿透我们，它让银河紧密地联系在一起。你、我-树-岩石，像素化的生物就是我们……不是这个粗俗的东西*捅你*。我通过紧盯着屏幕很多年来学习这种能力。}
{930}{}{Fallout是你所处的世界。我创造了它，或者说让它按照本来设计的那样运转。不久之前，你看到这个世界处于混乱状态。来到这里的旅者常常被这里大量的漏洞杀死。 但后来我来了，利用原码力的力量，我朋友们与我清理了废土，你可以说我是救世主。我被许多人视为英雄：The Bear Dude。}
{940}{}{这些是我的同伴，他们帮助我改善这个世界：MIBoba Fe88，Hivan Zolo，Contie-bacca，Darek Vader，Hutt Jotisz，R2Qwerty，Chris3ParksO，Yosan12，Empress Timeslip，Luke Skynet，Mon-Morticia，Kanhef，HawkEyE，Adam Dravean，Mr.Wolna，encinodude，Minigun Jim，Bofast，Pixote，Mash，Mikael Grizzly，x'il，Per和Masses。他们都帮助这个伟大的项目，从漏洞中拯救了这个世界。没有漏洞允许留下。} 
#response to 920
{921}{}{哇，我们的萨满告诉我，世界上有超越五官能感知的事物存在，你能教我使用原码力的力量吗？}
{922}{}{我想我已经听到足够多的神棍言论，让我为另一个核冬季储备。坦率地说，我就喜欢等离子手枪不离身。}
{923}{}{大大的好，又是的一个神棍的八嘎。我的这里的离开。}

#response to 930
{931}{}{我明白了，实际上，我的印象是，我是这个故事的英雄，四处奔走，杀人越货，就跟你认为的英雄一样，噢，我有时会和他们谈话，但那部分会让人厌烦。 我只需点击它即可获得有趣的一点。}
{932}{}{干得漂亮Killap先生，我非常感谢你在清理废土所花的时间和精力，如果你说的是真的，那么你应该知道我也是一个英雄，事实上，我也亲手干掉了一大票人渣。}

{935}{}{我们很感激你摧毁了英克雷，你是这里真正的英雄。}
{936}{}{无所谓了，就是过日子吧。}

#response to 935-936
{937}{}{那么，你到底是怎样清理这个世界的？}
{938}{}{谁，请告诉我，这些人是谁？}

#response to 940
{941}{}{嗯，这些名字听起来很熟悉…………我想我会和他们谈谈。}

#response to 921
#player > level 15
{950}{}{事实上，我可以，你必须学会使用你的感官：放开你的意识，关闭显示器，闭上你的眼睛，并感受原码力流过鼠标……[按照他的指示]。}
{951}{}{你缺乏接受训练的经验。当你至少学会了一些基本的编程，年轻的徒弟，回到我身边。}

{960}{}{如你所愿，年轻的 }
{961}{}{。但在你走之前，请记住这一点：我们坚持的许多事实都很大程度上取决于我们自己的观点，现在去吧，愿原码力与你同在。}
#player has high karma
{962}{}{。你的任务已经证明你是善良，善良和诚实的，并且帮助你对抗黑暗面：这是你祖先的光剑，这是Java骑士的武器，不像笨拙或不稳定的爆能枪; 这是一个更文明的时代的优雅武器，尽管你可能会试图用它来将人们劈开取乐，但是你应该明白它服务于正义，祝你好运，愿原码力与你同在，我的朋友。}
{963}{}{什么？！我的祖先，避难所居民，有这些之一？！我不记得在Fallout 1中能找到这个！*跑去检查*}
{964}{}{谢谢你，Mr. Bear Dude。谢谢你做的一切。愿原码力与你同在。}

#Timeslip
#{1010}{}{I'm Empress Timeslip。 I'm a Programming Master, skilled in the way of 原码力。 It was I who allowed Obi-Wan-Killap's spies to steal my engine fixes to greatly improve the stability of this world, and correct FOOLISH AND STUPID MISTAKES left by the original ones。}
#{1011}{}{Indeed, my master。 Tell me about yourself oh great one。}
#{1012}{}{Wow。 You're creepy。 And your face looks awful。}
#{1013}{}{That's nice。 Gotta go。}
#
##response to 1011
#{1020}{}{I can change that which is hardcoded into 原码力 with the merest thought, and determine the fate of entire universes！ An entire legion of my best bug fixes await you in the rest of your adventure。 I'm master of the Dark side of 原码力。}
##response to 1012
#{1021}{}{Silence！ Years of working in the dark may have distorted my looks, but in this mind are the powers of a God！ Using 原码力 I create weather, mastered entire worlds and tweak that which cannot be tweaked！ It was I who allowed the Evil Beth to rule the RPG world with my mods。 Everything that has transpired has done so according to MY desires。}
#
##Response to 1020/1030
#{1022}{}{Sauce？ What kind of sauce？ Are you saying cooking is the key to controlling the universe？ Whatever you say, chef。}
#{1023}{}{Yeah yeah。 Jeeze, whatever you say。 I think I will leave now。}
#{1024}{}{Uh, ok。 that's great。 Well, I need to go……erm ……water my plants……}
#
##Response to 1022-1024
#{1030}{}{Ignorant fool。 Your overconfidence is your weakness, and my faith in your friends is …… er …… mine。 *looks confused* Be gone from my sight！}
#{1040}{}{Wait！ You will leave IF and WHEN I decide。 In case you haven't noticed, you have been exceedingly evil in your quest。 Your hate has made you powerful and your character has developed according to my desires。 Anger, fear, hatred …… of the dark side are they。 Now you will become my apprentice and fulfill your place AT MY SIDE！}
#
#{1041}{}{As you wish, my master。 I'm at your bidding。}
#{1042}{}{Not interested。 Bye。}
#
#{1045}{}{Go forth and wreak havoc my child。}
#{1046}{}{Begone！}

{1010}{}{我是Empress Timeslip，我是一名编程大师，精通原码力之路，我允许Obi-Wan-Killap的窃取我的引擎修复，大大提高这个世界的稳定性，纠正哪些原本开发者留下的愚蠢和无知的错误。}
{1011}{}{的确如此，大师，请为我展示您的伟大。}
{1012}{}{哇，你真令人毛骨悚然，你的脸看起来真恶心。}
{1013}{}{好吧，我得要走了。}

#response to 1011
{1020}{}{我可以用最简单的思想来改变那个被编入源码的东西，并确定整个宇宙的命运！我的精锐漏洞修复大军正等待着，你之后的旅行。我掌控着原码力的黑暗面。}
#response to 1012
{1021}{}{住口！在黑暗中工作多年可能会扭曲我的外表，但从这个层面来说即是神的力量！使用原码力我创造了天气，掌握了整个世界并调整了无法调整的东西！这是我允许Evil Beth用我的mod来统治RPG世界。所发生的一切亦是我的意志。}

#Response to 1020/1030
{1022}{}{酱？什么样的酱？你说烹饪是控制宇宙的关键吗？得了吧，伙夫。[英文里酱和Source读音相近]}
{1023}{}{好，好，不管你说什么，我该走了。}
{1024}{}{呃，好吧，那很好，我需要去……呃……给我的植物浇水……}

#Response to 1022-1024
{1030}{}{无知的傻瓜，你的过度自信是你的弱点，我对你朋友的信仰是……呃……我的。*看起来很困惑*从我的眼前消失！}
{1040}{}{等等！我在想你为何以及何时要离开。或许你没有注意到，你所追求的邪恶让你变得强大，你的角色已经根据我的愿望发展了。愤怒、恐惧与憎恨，它们就是黑暗面，现在你将成为我的徒弟，并在我的身边实现你的价值！}

{1041}{}{如你所愿，师傅，我将照做。}
{1042}{}{不感兴趣，再见。}

{1045}{}{让灾难与浩劫肆虐吧，我的孩子。}
{1046}{}{滚开！}

#response to 1041
{1050}{}{Eeeeeeexcellent。 Then take this Java weapon。 Use it。 Kill indiscriminately。 USE YOUR AGRRESSIVE FEELINGS, CHILD！ [He hands you a red lightsaber。]}
{1051}{}{So……。 basically carry on as I've been doing。 No problem。 Bye！}
{1052}{}{I will not fail you, my master。}
{1053}{}{Kill everything？ you mean …… even the children？}

{1060}{}{ESPECIALLY the children。}

#Skynet
#{1110}{}{I'm Luke Skynet: I'm here to rescue you。}
#
#{1111}{}{Rescue me？}
#{1112}{}{Do I look like a princess？ What do you mean 'rescue'？}
#{1113}{}{Right。 I think you're the one that needs rescuing, pal……from your own movie career。 Bye。}
#
#{1120}{}{Yes, I'm here to rescue you。 I created the basis to what you see at the Abbey, and there you will find salvation。 There you will find the light！}
#{1121}{}{I've actually already been there。 I 'rescued' a lot stuff from getting lost in all those drawers and containers。}
#{1122}{}{Amen brother。 Thank you for aiding in the creation of that place of peace and solace。 And just when I needed to rest my radiated feet and seek spiritual rejuvenation。}
#{1123}{}{I remember that place。 No qualified shaman though, and no herb-superb。 I don't know who's idea of a spiritual center that is, but it's not mine。}
#{1124}{}{Oh？ And where is this place that can rescue me？}
#{1125}{}{Cuck-oo！ Bye bye now！}
#
#{1130}{}{You should return there again。 It is a safe haven in these harsh Wastes。}
#{1131}{}{I'm on my way, Mr。 Skynet。 Thanks for everything。 Goodbye。}
#{1132}{}{Well, I think YOU should go there Skybrain, and stay there。 I'm outta here。 Freak。}
#
#{1135}{}{Here。 [He shows you on your PipBoy]。 You should go there now。}
#
#{1138}{}{The Abbey is a place of solitude。}
#{1139}{}{Be careful out there。}

{1110}{}{我是Luke Skynet：我是来救你的。}

{1111}{}{拯救我？}
{1112}{}{我看起来像个公主吗？你说的“拯救”是什么意思？}
{1113}{}{是的，我认为你是需要拯救的人，朋友……从你自己的电影生涯。再见。}

{1120}{}{是的，我是来拯救你的。我完成了修道院的基本设置，你在那里会找到救赎。在那里你会找到光明！}
{1121}{}{实际上我已经去过那里了，我从很多抽屉和容器中“救”出了很多东西。}
{1122}{}{感谢上帝，当我需要休息下受到辐射的脚，寻求精神慰藉之时。你帮助了那个小镇，那个由我创造的小镇。}
{1123}{}{我记得那个地方。虽然没有合格的巫医，也没有优质草药。我不知道谁的想法才是精神的中心，不过绝对不是我的。}
{1124}{}{哈？这个地方能救我？}
{1125}{}{Cuck-oo！再见！}

#{1130}{}{You should return there again。 It is a safe haven in these harsh Wastes。}
#{1131}{}{I'm on my way, Mr。 Skynet。 Thanks for everything。 Goodbye。}
#{1132}{}{Well, I think YOU should go there Skybrain, and stay there。 I'm outta here。 Freak。}
#
#{1135}{}{Here。 [He shows you on your PipBoy]。 You should go there now。}
#
#{1138}{}{The Abbey is a place of solitude。}
#{1139}{}{Be careful out there。}

{1130}{}{你应该再回到那里，那真是没用垃圾的避风港。}
{1131}{}{我会去的，Skynet先生。谢谢你。再见。}
{1132}{}{嗯，我想象你这样的进水脑子才会呆在那里呢。我走了。奇葩。}

{1135}{}{在这里。[他在你的pipboy中指出了位置]。你应该现在就去。}

{1138}{}{修道院是一个独一无二的地方。}
{1139}{}{一路小心。}

#Morticia
#{1210}{}{I helped with writing a walkthrough to aid all the noobs on their new adventures in this improved world。}
#{1211}{}{Shit！ I'm on the wrong side！ I never was quite sure who's side I was supposed to be on。}
#{1212}{}{Does my bum look big in this？}
#{1213}{}{Empress Timeslip has made a critical error and the time for our attack has come。 *wink*}

{1210}{}{我协助完成了攻略来帮助新手，让他们能融入这新世界的冒险。}
{1211}{}{妈的！我站错队了！我根本无法确定应该站在哪一边。}
{1212}{}{我的屁股看起来大吗？}
{1213}{}{皇帝Timeslip已经犯了一个严重的错误，我们的反攻的时机已经到来。*眨眼*}

#Kanhef
#{1310}{}{I'm basically the NMA helpdesk。}
#{1311}{}{I'm not with these weirdoes。}
#{1312}{}{Damn。 Why is the no。 23 always late？}
#{1313}{}{In case you didn't know, I'm just an all-round useful guy。}

{1310}{}{我基本上是 NMA 服务台。}
{1311}{}{我跟这些怪人不同。}
{1312}{}{妈的。为什么不同。23号总是迟到？}
{1313}{}{怕你不知道, 我是个上知天文下知地理的人。}

#French Translator - HawkEyE
#{1410}{}{Bonjour。 Je suis Hawk-Eye。 J'ai translate le version Francais。 }
#{1411}{}{I'm Hawk-EyE。 I headed the translation of the French version。 Vive la France！！}
#{1412}{}{I like to eat ……。 little fishies so sweeeet！}
#{1413}{}{Nobody here but us chickens。}

{1410}{}{你好，我是Hawk-Eye。 我负责法语版本的翻译！ }
{1411}{}{我是Hawk-EyE，我负责翻译法语版本，法兰西万岁! ！！}
{1412}{}{我喜欢吃小甜鱼！！}
{1413}{}{除了那些美国弱鸡，这里没其它人。}

#German Translator and other misc artwork - Mr.Wolna
#{1510}{}{I'm Mr。 Wolna。 I headed the translation of the German version。}
#{1511}{}{[plz bitch-slap me！！]}
#{1512}{}{Good work, guys！ Keep it up！}
#{1513}{}{Look！ A golden Eagle！}
#{1514}{}{Ich komme aus Deutschland！}

{1510}{}{我是Mr.Wolna，我负责德语版的翻译。}
{1511}{}{[plz bitch-slap me！！]}
{1512}{}{干得好，伙计们！坚持下去！}
{1513}{}{看！ 一只金鹰！}
{1514}{}{我是德国人！}

#Dravean - Dex, RP dialogue rewrite, etc
#{1610}{}{[He removes his helmet and casts aside his crimson cloak, revealing a ruggedly handsome man with a shaved head and a leather jacket。 He seems to exude charisma and awesomeness。] Hey stranger, the name's Adam。 How's it going？}
#{1611}{}{Pretty good。 It's been a rocky road, but I've finally come to the end。}
#{1612}{}{I don't have time for this。 Bye。}

{1610}{}{[他摘下头盔，解开他的深红色的斗篷，一个粗犷英俊的一个光头皮夹克男展现出来，他似乎散发出的魅力和帅气。] 嘿，陌生人，我的名字叫亚当，最近怎么样？}
{1611}{}{很好，这真不容易，但我最总还是坚持下来了。}
{1612}{}{我没有时间做这个，再见。}

#{1620}{}{That's good to hear。 [He looks around, then furrows his brow。] Where's Dex？ I spent a lot of time writing that dude's dialogue, and you're not even using him？ [He sighs heavily and shakes his head。]}
#{1621}{}{Dex？ Wrote his dialogue？ What are you talking about？}

{1620}{}{听起来不错。[他环顾四周，然后皱起眉头。]德克斯在哪里？我花了很多时间写那个家伙的对话，而你甚至没有使用他？[他重重地叹了口气，摇了摇头。]}
{1621}{}{德克斯？写了他的对话？你在说什么？}

#{1630}{}{That's good to hear。 Excuse me a moment。 [He walks over to Dex, gives him a high five, then returns to you。] I'm glad to see you and my man Dex have stuck together。 You know I spent a lot of time writing that dude's dialogue。}
#{1631}{}{How do you know Dex？ And you "wrote his dialogue"？ What are you talking about？}

{1630}{}{听起来不错。抱歉。[他走到德克斯面前，和他击掌，然后又回到你身边。]我很高兴看到你和我的伙计德克斯在一起，你知道我花了很多时间写那个家伙的对话。}
{1631}{}{你是怎么认识德克斯的？你写了他的对话吗？你在说什么？}

#{1640}{}{Look, don't worry about it。 But if you ever decide to embark on another epic quest, make sure to stop by the EPA。 There's a shitload of things to do there and if you play your cards right, you might find yourself a new companion。 [He looks you over and grins。] Yeah, you're just Dex's type, so you'll be friends for sure。}
#{1641}{}{Thanks。 I'll keep that in mind。}

{1640}{}{好吧，别在意这些。但是如果你决定走上另一个史诗级任务，确保游历下EPA。那真有一大堆的事情要做，你如果选择了正确的方式，可能会发现自己的新的伙伴。[他看起来对你呢嘴一笑。]是的，看来你是德克斯喜欢的类型，你们当然会成为朋友。}
{1641}{}{谢谢，我会留意的。}

#{1650}{}{Look, don't worry about it。 But if you ever decide to embark on another epic quest, make sure to stop by the EPA。 There's a shitload of things to do there and if you play your cards right, you might find yourself a new companion。 [He looks you over。] You'll probably have to change your attitude if you want to make friends with Dex。 He likes his companions to be a bit more …… morally impaired。}
#{1651}{}{Thanks。 I'll keep that in mind。}

{1650}{}{好吧，别在意这些。但是如果你决定走上另一个史诗级任务，确保游历下EPA。那真有一大堆的事情要做，你如果选择了正确的方式，可能会发现自己的新的伙伴。[他打量了你。]你如果想和德克斯做朋友，也许你需要改变下态度。他并不太喜欢一个彻底的……好人。}
{1651}{}{谢谢，我会留意的。}

#{1660}{}{[He nods and looks off into the distance。] You know, Dex wasn't my only contribution。 I also helped the Bear Dude in sprucing this world up by serving as adviser, tester, and guardian of canon and original intent。 But mostly, I was tasked with bringing all the new wasteland speech up to par。 It's been a hell of a long road, but if you ask me, this thing turned out pretty fuckin' sweet。 [He looks back at you and grins。]}
#{1661}{}{Whatever。 I'm tired of listening to this。 Bye。}
#{1662}{}{That's quite noble of you。 You've done a remarkable job。 Take care of yourself。 Bye。}

{1660}{}{[他点头，又看着远方。]你知道，德克斯不是我唯一的贡献。我还在The Bear Dud美化这个世界时作为顾问和测试员，保护事情的初衷和原本的意图。但最重要的是，我把所有废土上的语言调整得更标准。这是一个很长的路，但如果你问我，这件事竟然还蛮有趣的。[他回头看着你笑。]}
{1661}{}{好吧，我听够了。再见。}
{1662}{}{你真是太高尚了。你干得很出色。照顾好自己。再见。}

#{1670}{}{*Looks over at your party members* Lookin' good, Dex。}
#{1671}{}{Keep your eye on Dex, alright？ I don't want him getting into trouble。 After all, he's my creation。}
#{1672}{}{You're welcome for cleaning up the dialogue of the wastes。}
#{1673}{}{Hey, where's Dex？ Did I mention I'm his creator？}

{1670}{}{*你的小队成员*看起来不错，德克斯。}
{1671}{}{看好德克斯，好吗？我不想让他陷入麻烦。毕竟，他是我的创造物。}
{1672}{}{感谢你整理了废土人物的对话。}
{1673}{}{嘿，德克斯在哪里？我提到过我是他的创造者吗？}

#encinodude - Kitsune
#{1710}{}{*Looks over at your party members* Lookin' good Kitsune。}
#{1711}{}{You keep an eye on Kitsune, you hear。 I don't want her getting into trouble。 She's my creation, you know。}
#{1712}{}{I helped out with the sub, you know。}
#{1713}{}{Hey, where's Kitsune？ I wrote her dialogue you know。}
#{1714}{}{I helped out with the sub, you know。}

{1710}{}{[仔细查看你的队伍成员]}
{1711}{}{我创造了灵狐。另外我提醒你要看好灵狐，我不想让她陷入麻烦。}
{1712}{}{RP里潜水艇的部分我也有参与制作哦。}
{1713}{}{嘿, 灵狐在那里？ 我曾经参加过她的对话创作，你知道吗？}
{1714}{}{三番市的潜水艇我也有参与制作哦。}

#Minigun Jim - Cat Jules
#{1810}{}{*Looks over at your party members* Lookin' good Cat。}
#{1811}{}{You keep an eye on Cat, you hear。 I don't want him getting into trouble。 He's my creation, you know。}
#{1812}{}{Hey, where's Cat？ I wrote his dialogue you know。}

{1810}{}{[仔细查看你的队伍成员，看样子他在找一只好"猫"]}
{1811}{}{你要看紧你的"猫"。知道吗，尽管是我创造了他，但我总是觉得他很可能会惹点什么麻烦。}
{1812}{}{嘿，你的"猫"在哪里？他的对话是我写的，你知道吗。}

#Bofast
#{1910}{}{Good going bringing a peaceful end to the Raiders attacking Vault City。 I helped make that possible。}
#{1911}{}{You didn't have to kill all those Raiders attacking Vault City。 There is a peaceful solution now, thanks to me。}

{1910}{}{我为那些攻击地下掩体市的歹徒做了一个好的结局。}
{1911}{}{现在你不用把那些攻击地下掩体市的歹徒都干掉了，现在会有和平解决问题的办法。这都是我做的！}

#Pixote
#{2010}{}{[The robot nods as you approach。] Hello there。 Are you enjoying your time in this world？}
#{2011}{}{Yes I am。 Thanks for asking。}
#{2012}{}{Not really。 Things could be better。}
#{2013}{}{I'm not in the mood to chat。 Bye。}
#
#{2020}{}{That's great to hear！ I hope all the hard work I have done to make each location appear as unique and detailed as possible is in some way responsible for your happiness。 It took a lot of work to tidy things up, but the overall atmosphere and appearance is top notch now。 Don't you agree？}
#{2021}{}{Oh, definitely。 Everything looks amazing。 You're quite talented！}
#{2022}{}{Meh, it's alright。}
#{2023}{}{That's nice。 Bye。}
#
#{2030}{}{I'm sorry to hear that。 Perhaps you haven't taken a good look at the world around you。 I have done much to make each location appear as unique and detailed as possible。 Maybe if you look at the details, this will lift your spirits。 It took a lot of work to tidy things up, but the overall atmosphere and appearance is top notch now。 Don't you agree？}
#{2031}{}{Now that you mention it, I did notice things look a lot nicer now。}
#{2032}{}{Didn't really notice。}
#{2033}{}{That's nice。 Bye。}
#
#{2040}{}{[The robot rocks back and forth with glee。] I'm glad you like it。 Well, I must be going now。 I've got more goodies to unleash upon this world。}
#{2041}{}{Alright。 Take care。}
#
#{2050}{}{[The robot's head lowers in sadness。] Well, my work isn't for everyone I suppose。 Now, if you'll excuse me, I must be going。 I've got more goodies to unleash upon this world。}
#{2051}{}{Whatever。 Bye。}
#
#{2060}{}{I so enjoy creating new things。}
#{2061}{}{So many new details now。 So beautiful。}

{2010}{}{[机器人点头并走向你]你好，你在这世界玩得愉快么？}
{2011}{}{是的，谢谢你的问候。}
{2012}{}{一般般吧，或许能更好。}
{2013}{}{我没注意，再见。}

{2020}{}{真是太好了！我所做的一切努力，即是希望使每个地点看起来尽可能的丰满并独具特色，更希望你能高兴。}
{2021}{}{哦，那当然。一切看起来都很棒。你真是个天才！}
{2022}{}{哦，好吧。}
{2023}{}{挺不错的，再见。}

{2030}{}{听到这个消息我很难过。也许你没有仔细的观察这个世界。我已经做了许多工作让每个地点看起来尽可能的丰满并独具特色。如果你仔细观察会为之一振。这需要做大量的工作，处理各种各样的东西，但整体氛围和外观是一致的，不是吗？}
{2031}{}{嗯好的，我会更加留意这些的。}
{2032}{}{还真没有注意到。}
{2033}{}{还行吧，再见。}

{2040}{}{[机器人手舞足蹈]我很高兴你喜欢它。好吧，我现在必须得走了。这世界上还有很多值得展现的好东西。}
{2041}{}{好的，保重。}

{2050}{}{[机器人垂头丧气]嗯，我想我做的事情不是所有人都能理解吧，不过现在，如果你不介意的话，我必须走了。这世界上还有很多值得展现的好东西。}
{2051}{}{无所谓了，再见。}

{2060}{}{我超喜欢创造新事物。}
{2061}{}{这么多新的细节，太漂亮了。}

#Mash
#{2110}{}{Greetings！ Glad you've made it this far。 I hope you are enjoying the expanded visible size of this world。 Not enough of this world could be shown at any one time。 I changed all this though。 Empress Timeslip and I are masters of 原码力。 He and I have brought this old world into a new era。}
#{2111}{}{Wow, thanks for that。 Everything is a lot better。 Sometimes a bit too small, but I can easily adjust that。}
#{2112}{}{I don't have time for this。 Bye。}
#
#{2120}{}{I'm glad you are enjoying my hard work。 I also made it possible to change appearances。 No longer are you stuck with a specific race or hair type。 Yosan12, x'il, and others made the physical appearances themselves, but I, with the help of Empress Timeslip, dug deep into 原码力 to make it all possible。 I see that you have taken advantage of this new ability。 Outstanding！}
#{2121}{}{Oh, I love my new looks。 Thanks for that！}
#{2122}{}{Right。 Goodbye。}
#
#{2130}{}{I'm glad you are enjoying my hard work。 I also made it possible to change appearances。 No longer are you stuck with a specific race or hair type。 Yosan12, x'il, and others made the physical appearances themselves, but I, with the help of Empress Timeslip, dug deep into 原码力 to make it all possible。 I see that you have not taken advantage of this feature。 Just know that it is there and available。 A great place to test it out is at the EPA。 Oh, what fun！}
#{2131}{}{I'll keep that in mind。 Thanks。}
#{2132}{}{Right。 Goodbye。}
#
#{2140}{}{Most excellent。 Well, you take care。}
#{2141}{}{Goodbye。}
#{2142}{}{See you around。} 
#{2150}{}{原码力 is tricky, but I can handle it。}
#{2151}{}{Enjoy the expanded visibility of this world！}
#{2152}{}{Enjoy the new you！}

{2110}{}{您好！很高兴你已经走了这么远，希望你享受了原码力开放世界的乐趣。尽管没人能够一次性看完整个世界。我也尽力去改变，皇帝Timeslip和我是主要的编写者。我们把这个旧世界带入了一个新时代。}
{2111}{}{哇，谢谢你。一切都好多了。有时候有点不适，但我也可以轻松适应。}
{2112}{}{我没有时间闲聊，再见。}

{2120}{}{我很高兴你喜欢我的工作，它让你可以改变外貌和种族。Yosan12，x'il和其他人也创造了他们独特的外观。但我在皇帝Timeslip的帮助下，追根溯源找到了最初的设计，并让它们能够重现眼前。我想你已经该已经见识过了吧！}
{2121}{}{哦，我喜欢我的新模样。谢谢你！}
{2122}{}{好的，再见。}

{2130}{}{我很高兴你喜欢我的工作，它让你可以改变外貌和种族。Yosan12，x'il和其他人也创造了他们独特的外观。但我在皇帝Timeslip的帮助下，追根溯源找到了最初的设计，并让它们能够重现眼前。我们为了测试它有多厉害，于是就有了EPA。嘿，那里很有趣吧！}
{2131}{}{我会记住的，谢谢。}
{2132}{}{好的，再见。}

{2140}{}{好的棒极了，一路小心。}
{2141}{}{再见。}
{2142}{}{下次见。} 
{2150}{}{尽管原码力诡异，但是我能处理它。}
{2151}{}{享受原码力开放世界的乐趣吧。}
{2152}{}{享受全新的自己！}

#Grizzly
#{2210}{}{Hello there。 I helped bring the submarine back into this world。}
#{2211}{}{You like how furry I am？ I know I do。}
#{2212}{}{Hope you enjoyed the sub。}

{2210}{}{你好，我帮你把潜艇带回了这个世界。}
{2211}{}{你喜欢我毛茸茸的吗？我很喜欢。}
{2212}{}{希望你喜欢潜水艇。}

#x'il
#{2310}{}{I helped a lot with critter appearances。 Hope you have enjoyed it！}
#{2311}{}{Nice hair, man。 I helped make that possible。}
{2310}{}{我帮助制作了很多生物体，希望你喜欢他们。}
{2311}{}{漂亮的新发型，兄弟，我帮你实现了。}

#Per
#{2410}{}{There is a plaque on the pile of rocks。 It reads: "Dedicated to Per Jorner。 Master of the walkthroughs, King of the lizards, and Accumulator of all rocks。}
{2410}{}{在岩堆上的牌子上写道："向Per Jorner致敬，演练的大师，蜥蜴的国王，所有岩石的收藏者"。}

#Masses
{2510}{}{}

#{5000}{}{Combat is not allowed here。}
{5000}{}{战斗在这里是不允许的。}

