#{100}{}{You see a traveler.}
#{101}{}{Hail! Fellow traveler.}
#{102}{}{I'm in need of directions. Can you help me out?}
#{103}{}{Where are you headed?}
#{104}{}{What do you do?}
#{105}{}{Ug.}
#{106}{}{Well……I don't know. I'm pretty new to this area and I've only been to the following areas.}
#{107}{}{New Reno.}
#{108}{}{Vault City.}
#{109}{}{Redding.}
#{110}{}{The Den.}
#{111}{}{San Francisco.}
#{112}{}{New California Republic.}
#{113}{}{An abandoned mine.}
#{114}{}{An old, abandoned facility.}
#{115}{}{No, I've been there already. Thanks anyway.}

{100}{}{你看到一个旅行者。}
{101}{}{你好，你也在旅行吗？}
{102}{}{我需要方向。你能帮我吗？}
{103}{}{你要去哪里？}
{104}{}{你是怎么做到的？}
{105}{}{呃.}
{106}{}{嗯……我对这一带也不是很熟，我只去过以下几个地方。}
{107}{}{[新里诺]}
{108}{}{[地下掩体市]}
{109}{}{[瑞丁]}
{110}{}{[丹恩]}
{111}{}{[三番市]}
{112}{}{[新加州共和国]}
{113}{}{[废矿场]}
{114}{}{[旧设施]}
{115}{}{不，我已经去过那里了。谢谢。}





#{116}{}{New Reno -- now that's a great place to go. Sex, drugs and gambling. What more can one ask for? Here, let me show you where it is.}
#{117}{}{Thanks. Bye.}
#{118}{}{Vault City -- now that's a city of morons. Grow an extra finger and they treat you like some kind of freak. Never been inside, but I know where it is.}
#{119}{}{Thanks. Bye.}
#{120}{}{Redding……I don't know much about it, other than it's an old mining town. It's located up north, right smack dab in the middle of some of meanest mountains you've ever seen.}
#{121}{}{Thanks. Bye.}
#{122}{}{I'd stay away from the Den if I were you. It's a magnet for lowlifes of the area. I'll show you where it is, but I don't recommend you go there.}
#{123}{}{Thanks. Bye.}
#{124}{}{San Francisco. Um……all I can say is that the people there are……strange. It's located on the coast.}
#{125}{}{Thanks. Bye.}
#{126}{}{The New California Republic……now there's a nice place. I'd like to settle down and live there some day. Clean, nice people, and very well maintained. It's located right here on your map.}
#{127}{}{Thanks. Bye.}
#{128}{}{Yeah, a while back I came across an abandoned mining camp. Thought I'd rest there a day or two, but then wolves started showing up and I thought it best if I left. A shame, too; it looks like the miners left in a hurry. They left a lot of stuff behind. I'm not planning to go back, so I guess it's all right if I show you where it is.}
#{129}{}{Thanks. Bye.}


{116}{}{新里诺 -- 那是一个很棒的地方。性、毒品和赌博。一个人还能要求什么？来，让我告诉你它在哪儿。}
{117}{}{谢谢，再见。}
{118}{}{地下掩体市 -- 那是一个白痴之城，你手指长得长一点，他们都有可能把你当成怪物。我从未进过里面，但我知道它在哪里。}
{119}{}{谢谢，再见。}
{120}{}{地下掩体市 -- 我不太了解它，除了知道它是一个古老的采矿小镇。它位于北部，正好在你见过的一些最恶劣的山脉中间。}
{121}{}{谢谢，再见。}
{122}{}{丹恩 -- 如果我是你，我就远离丹恩。那里是各种下三滥的吸铁石。我会告诉你它在哪里，但我不建议你去那里。}
{123}{}{谢谢，再见。}
{124}{}{三番市 -- 嗯……我只能说那里的人很奇怪。它位于海岸上。}
{125}{}{谢谢，再见。}
{126}{}{新加州共和国 -- 现在是个好地方。我希望有一天能住在那里。干净，善良的人，而且维护得很好。现在我把它标在你的地图上。}
{127}{}{谢谢，再见。}
{128}{}{废矿场 -- 我曾经遇到了一个废弃的采矿营地。我想在那里休息一两天，但是后来狼来了，我想最好还是离开。那里看起来矿工们匆忙离开了。他们留下了很多东西，我不打算回去。现在我把它标在你的地图上。}
{129}{}{谢谢，再见。}



#{130}{}{Yeah, a while back I came across an old facility that looked like it'd been abandoned since the Great War. Looked pretty important too, so I bet it's chock full of pre-war goods. I would've scavenged the place myself, but it's grounds were covered with some real pissed off man-eating plants. I'm not planning on going back, so I guess it's all right if I show you where it is.}
#{131}{}{Thanks. Bye.}

{130}{}{旧设施 -- 我偶然发现了一个旧的设施，它看起来就像一个被遗弃的地方，而且看起来也很重要。所以我打赌它里面塞满了各种战前的神奇宝贝。但它的院子里到处都是吃人的植物，我把它标在你的地图上吧。}
{131}{}{Thanks. Bye.}


#{132}{}{Oh……it doesn't really matter. I just decided to travel one day and well, here I am.}
#{133}{}{Maybe you can help me. I need some directions.}
#{134}{}{What do you do?}
#{135}{}{Nice talking to you.}
#{136}{}{I do odd jobs here and there to get me by. But mostly I just travel.}
#{137}{}{Maybe you can help me. I need some directions.}
#{138}{}{Where you headed?}
#{139}{}{Nice talking to you.}
#{140}{}{I really should be going now. It was nice talking to you.}
#{141}{}{Maybe we'll meet again.}
#{142}{}{I want to make the next town by nightfall. I'd better go.}
#{143}{}{I'd better be going.}
#{144}{}{Ambush!}
#{145}{}{Can't trust anyone these days.}
#{146}{}{You have broken the code of the traveler.}
#{147}{}{Time to go.}
#{148}{}{I've overstayed my welcome.}
#{149}{}{I must depart.}

{132}{}{哦……它并不重要。我决定去旅行一下，然后我就出发了。}
{133}{}{也许你可以帮助我。我需要一些方向。}
{134}{}{你会怎么做? }
{135}{}{很高兴和你聊天。}
{136}{}{我会在附近的城市做零工赚取我的旅费，但大多数时候我只是旅行。}
{137}{}{也许你可以帮助我。我需要一些方向。}
{138}{}{你去哪？}
{139}{}{很高兴和你聊天。}
{140}{}{我现在真的该走了，很高兴和你谈话。}
{141}{}{也许我们会再见面。}
{142}{}{我想在夜幕降临前到达下一个城镇，我先走了。}
{143}{}{我最好走吧。}
{144}{}{伏击!}
{145}{}{现在不能相信任何人。}
{146}{}{你已经破坏了旅行者的代码。}
{147}{}{旅行时间。}
{148}{}{我无任欢迎。}
{149}{}{我必须离开。}

#{150}{}{Thanks. I need directions to some other places.}
{150}{}{谢谢。我需要去其他地方的路。}