# Message file for epac9.ssl 
# Number of nodes: 18

#{100}{}{You see a large computer.}
#{101}{}{You see Mr. Chemmie!}
#{102}{}{A large crafting computer for drugs.}

{100}{}{你看到一台大型计算机。}
{101}{}{你看到"点石成金"先生！}
{102}{}{你看到一台用于制造药品的大型计算机。}


# Node  0  [Node001]
#{200}{}{Hello user! I'm the pharmacist of the future, Mr. Chemmie! How can I help you?!}
#{201}{}{What do you do?}

{200}{}{尊敬的用户，您好！我是未来的药剂师，"点石成金"先生！我能为你做什么吗？}
{201}{}{你能做什么？}


# Node  1  [Node002]
#{210}{}{I make drugs! All kinds of drugs! When life gets you down, Mr. Chemmie is here to pick you up! How does Mr. Chemmie work?! It's simple! All you need is some scientific know-how and the right ingredients, then leave the rest up to me! Go on! Give me a try! And kids, remember to ask Mommy or Daddy for permission before playing with Mr. Chemmie!}
#{211}{}{Alright, I'll give this a try.}
#{212}{}{Maybe later.}

#{210}{}{我会制造药物！各种各样的药物！孩子，当你感到沮丧的时候，请想起"点石成金"先生！当你对生活感觉失望的时候，请想起点石成金"先生！"点石成金"先生是怎么工作的？很简单！你所需要的是一些科学知识和正确的材料，然后把剩下的交给我！去吧！给我一个配方试试！孩子们，记得在和"点石成金"先生玩之前先征得妈妈或爸爸的同意！}
#{211}{}{好，我来试试。}
#{212}{}{我以后再回来吧。}

# Node  2  [Node003]
{220}{}{好吧！让我们把材料混合起来！您希望制作什么？}
{221}{}{治疗针}
{222}{}{超级治疗针}
{223}{}{毒药}
{224}{}{解毒剂}
{225}{}{急救箱}
{226}{}{医生手提袋}
{227}{}{壮大灵 }
{228}{}{曼他特}
{229}{}{疯狂药}
{380}{}{放射线X}
{381}{}{放射药}
{382}{}{[让人惊喜的东西]}
{383}{}{没有什么想要的}


# Node  3  [Node004]
#{230}{}{Great choice! To make a Stimpak, please feed me: one Broc Flower, one Xander Root and one Empty Hypodermic needle! Yum-yum!}
#{231}{}{Make a stimpak.}
#{232}{}{I don't have those right now.}
#{233}{}{Return to the menu.}

{230}{}{做一个治疗针？一个很好的选择！请给我：布拉克花，山德根，空针筒！ }
{231}{}{制作一个治疗针。}
{232}{}{我现在没有这些东西。}
{233}{}{[返回]}

# Node  4  [Node005]
#{240}{}{Great choice! To make a Super Stimpak, please feed me: one ordinary Stimpak, one piece of Fruit and one Nuka Cola! Yum-yum!}
#{241}{}{Make a Super Stimpak.}

{240}{}{做一个超级治疗针？一个很好的选择！请给我：一个治疗针，一个水果和一个核子可乐！}
{241}{}{制作一个超级治疗针。}

# Node  5  [Node006]
#{250}{}{Great choice! To make Psycho, please feed me: one box of Mentats, one Buffout, one piece of Fruit and one Stimpak! Yum-yum!}
#{251}{}{Make a Psycho.}

{250}{}{做一个疯狂药？真是令人兴奋的选择！请给我：一盒曼他特，一盒壮大灵，一个水果，一个治疗针 ! }
{251}{}{制作一个疯狂药。}

# Node  6  [Node007]
#{260}{}{Great choice! To make some Mentats, please feed me: one First Aid Kit, one piece of Fruit, and one bottle of Booze! Yum-yum!}
#{262}{}{Make some Mentats.}
#{263}{}{Exit}

{260}{}{做一个曼他特？真是令人兴奋的选择！请给我：一个急救箱，一个水果，一瓶酒！}
{262}{}{制作一个曼他特。}
{263}{}{[退出]}


# Node  7  [Node008]
#{270}{}{Great choice! To make a Doctor's Bag, please feed me: one Stimpak, one First Aid Kit, one Empty Hypodermic needle and one Poison Antidote! Yum-yum!}
#{272}{}{Make a Doctor's Bag.}

{270}{}{做一个医生手提袋？一个很好的选择！请给我：一个治疗针，一个空针筒，一个解毒剂，一个急救箱！}
{272}{}{制作一个医生手提袋。}

# Node  8  [Node009]
#{280}{}{Great choice! To make a First Aid Kit, please feed me: one Stimpak, one Empty Hypodermic needle, one Poison Antidote and one Rad Away! Yum-yum!}
#{282}{}{Make a First Aid Kit.}

{280}{}{做一个急救箱？一个很好的选择！请给我：一个治疗针，一个空针筒，一个解毒剂，一个放射药！}
{282}{}{制作一个急救箱。}

# Node  9  [Node010]
#{290}{}{Great choice! To make Poison, please feed me: one Empty Hypodermic needle, one Scorpion Tail and one Nuka Cola! Yum-yum!}
#{292}{}{Make some poison.}

{290}{}{做一个毒药？真是令人兴奋的选择！你到底想要毒死谁呢，孩子。请给我：一个毒蝎尾，一瓶核子可乐，一个空针筒！}
{292}{}{制作一个毒药。}

# Node  10  [Node011]
#{300}{}{Great choice! To make Buffout, please feed me: one First Aid Kit, one bottle of Beer and one Nuka Cola! Yum-yum!}
#{302}{}{Make Buffout.}

{300}{}{做一个壮大灵？ 真是令人兴奋的选择！请给我：一个急救箱，一瓶啤酒，一瓶核子可乐！}
{302}{}{制作一个壮大灵。}


# Node  11  [Node012]
#{310}{}{Great choice! To make Rad-X, please feed me: one First Aid Kit and one Nuka Cola! Yum-yum!}
#{312}{}{Make a Rad-X.}

{310}{}{做一个放射线X？一个很好的选择！请给我：一个急救箱，一瓶核子可乐！}
{312}{}{制作放射线X。}

# Node  12  [Node013]
#{320}{}{Great choice! To make Rad Away, please feed me: one Nuka Cola, one Empty Hypodermic needle and one Stimpak! Yum-yum!}
#{322}{}{Make a Rad Away.}

{320}{}{做一个放射药？一个很好的选择！请给我：核子可乐，空针筒，治疗针！}
{322}{}{制作放射药。}


# Node  13  [Node014]
#{330}{}{Great choice! To make a Poison Antidote, please feed me: one Scorpion Tail and one bottle of Booze! Yum-yum!}
#{331}{}{Make Poison Antidote.}

{330}{}{做一个解毒药？一个很好的选择！请给我：一个毒蝎尾，一瓶酒！}
{331}{}{制作解毒药。}


# Node  14  [Node015]
#{340}{}{Oh boy! A special request! What kind of special drug would you like Mr. Chemmie to create for you today?!}
#{341}{}{Marijuana.}
#{342}{}{Doctor's Chemicals.}

#{343}{}{My friend Cassidy has a problem with his heart. Can you make something to help him?}
#{344}{}{Environmental Rejection Syndrome Inhibitors.}

{340}{}{哦，一个特殊的请求！孩子，你想要什么特殊的药吗？}
{341}{}{大麻}
{342}{}{心脏病药}

{343}{}{我的朋友盖西迪的心脏有问题，你能帮他做点什么吗？}
{344}{}{ERSI[环境拒绝综合症抑制剂]}



# Node  15  [Node016]
#{350}{}{This is your lucky day! I have enough chemicals in my storage tanks to make these! Would you like Mr. Chemmie to make them for you?!}
#{351}{}{Create.}
#{352}{}{Return to Main Menu.}

{350}{}{今天是你的幸运日！我的储存罐里有足够的化学物质来制造这些！你想让"点石成金"先生帮你做吗？}
{351}{}{制造}
{352}{}{返回}

# Node  16  [Node017]
#{360}{}{Uh-oh! Sorry, but I no longer have the chemicals needed to create these!}

{360}{}{哦！抱歉，但是我已经没有足够的化学原料来制造这些了！}

# Node  17  [Node018]
#{370}{}{Selection created! That was fun! Please collect the item from the machine! Thank you for using Mr. Chemmie! Let's make drugs again sometime!}

{370}{}{你选择了制造！这一定会很有趣！请从取药台上拿走你的药品！谢谢你使用了"点石成金"先生！让我们改天再嗑药吧！}

{371}{}{[更多选择]}

#{375}{}{Mr. Chemmie loves to help! I can create a substance called nitroglycerin, which will control an irregular heartbeat and prevent heart attacks!}

{375}{}{"点石成金"先生喜欢帮人！我可以制造一种叫做硝化甘油的物质，它可以控制不规则的心跳，防止心脏病发作！}

#{390}{}{This is your lucky day! I have just enough chemicals in my storage tanks to make one batch of ERSIs! Would you like Mr. Chemmie to make them for you?!}
#{391}{}{Create.}
#{392}{}{Exit.}

{390}{}{今天是你的幸运日！我的储罐里有足够多的化学物质，可以制作ERSI[环境拒绝综合症抑制剂]！你想让"点石成金"先生帮你做吗？}
{391}{}{制造}
{392}{}{返回}
