# Message file for epac5.ssl 
# Number of nodes: 5

#{100}{}{You see a Hologram.}
#{101}{}{You see the Director of Operations.}
#{102}{}{Hologram 12001. He directs operations within the EPA.}

{100}{}{你看到一个全息图像。}
{101}{}{你看到一个运管主管。}
{102}{}{全息图像12001，他负责EPA的运营和对外发布工作。}


# Node  0  [Node001]
#{200}{}{[This weasely looking hologram regards you with a nervous smile.] Hello, welcome to the EPA. You may have noticed that we're experiencing some mild issues, but we'll cross that bridge once we come to it.}
#{201}{}{Uh, OK. Who are you?}

{200}{}{这个图像脸上带着微笑，但表情却有点狡猾]你好，欢迎来到EPA，你可能已经注意到我们这里有一些轻微的问题，但既然我们来到了这里，我们一定会跨过这个难关。}
{201}{}{嗯，好的。你是谁？}


# Node  1  [Node002]
#{210}{}{I'm the Director of Operations for the EPA.}
#{211}{}{Oh, right. [You scratch your head] What does that actually mean?}

{210}{}{我是EPA的运营主任。}
{211}{}{哦，对吧。运营，[你挠头]那到底是什么意思？}



# Node  2  [Node003]
#{220}{}{[He chuckles uneasily.] Why, I coordinate things. Get the ball rolling. Now it's in your court. I like to bring out the best in people. Here at the EPA, that's what it's all about. Honestly. Integrity. Thank you, we value your opinion.}
#{221}{}{What the hell are you talking about?}

{220}{}{[他露出演员般的笑容]我负责协调一切，让球可以滚起来。我喜欢把每个人的优点发挥出来，在EPA，这是我们最重视的原则。谢谢你，我们重视你的意见。}
{221}{}{你他妈到底在说什么?}

# Node  3  [Node004]
#{230}{}{I assure you that we are working diligently to resolve all issues. We've had a bit of downsizing, but things are looking up. I feel confident that all quotas will be achieved in due time.}
#{231}{}{What quotas? You're not making any sense. Do you actually do anything here? Can you help me, or not?}

{230}{}{我向你保证，我们正在努力解决所有的问题。我们已经缩减了规模，情况正在好转。我相信所有的配额都将在适当的时候达到。}
{231}{}{配额？你在说些什么，你到底在这里做什么的？你能帮我吗？}

# Node  4  [Node005]
#{240}{}{That all depends on your outlook. My hands are tied on this matter, but I'd be delighted to assist you if you could.}
#{241}{}{Forget it. Bye.}
#{242}{}{I'm sorry I couldn't be of further assistance.}
#{243}{}{Thank you for your time.}

{240}{}{这完全取决于你的观点。我对这件事无能为力，如果可以的话，我很乐意帮助你。}
{241}{}{忘记这件事吧，再见。}
{242}{}{我很抱歉，我不能提供进一步的信息。}
{243}{}{谢谢你的访问。}

#{244}{}{I don't want to comment.}
#{245}{}{No comment.}
#{246}{}{I would, but I'm currently authoratally challenged.}
#{247}{}{We'll tackle that issue once we come to it.}
#{248}{}{This meeting is for discussion, not for action.}
#{249}{}{I'm confident the EPA is on track for success.}
#{250}{}{That issue's relevancy is in question.}
#{251}{}{Let's not be hasty, lest we act too quick.}
#{252}{}{That sounds adequate.}
#{253}{}{I understand your concern.}

{244}{}{我不想评论。}
{245}{}{无可奉告。}
{246}{}{我愿意，但是我现在受到了权威的挑战。}
{247}{}{我们会处理这个问题。}
{248}{}{这个项目将在会议讨论。}
{249}{}{我相信EPA会取得成功。}
{250}{}{在那个问题上是存在争议的。}
{251}{}{我们并不是行动迟缓，我们是努力避免行动中可能的错误。}
{252}{}{你的意见很好。}
{253}{}{我理解你们的担忧。}
