#{100}{}{You see a tribal.}
#{101}{}{You see a captive tribal of the Doctor.}
#{102}{}{A sad-looking prisoner, belonging to the Doctor.}
#{103}{}{HELP!}
#{104}{}{HELP US!}
#{105}{}{Please free us!!}
#{106}{}{We can't take any more!!}
#{107}{}{Thank you, friend!}


{100}{}{你看见一个部落人。}
{101}{}{你看到一个被医生俘虏的部落人。}
{102}{}{一个被医生俘虏的部落人，他看起来很虚弱。}
{103}{}{救命！}
{104}{}{帮帮我们！}
{105}{}{请给我们自由！！}
{106}{}{我们不能再吃了！}
{107}{}{感谢你，朋友！}