# Message file for epac8.ssl 
# Number of nodes: 13

#{100}{}{You see a worn-looking Hologram.}
#{101}{}{You see the Director of Ground Maintenance.}
#{102}{}{Hologram 10031. He is in charge of all the ground maintenance at the EPA.}

{100}{}{你看到一个看起来很丑的全息图。}
{101}{}{你见到地面维护主任。}
{102}{}{全息图像10031，他负责环境保护局的所有地面维护工作。}

# Node  0  [Node001]
#{200}{}{Hello there. Mind if I ask how you managed to get in here? The elevators to the surface broke down a long time ago.}
#{201}{}{Let's see... I used a rope to climb down an elevator shaft to the utility level... Then I crawled through a fan duct and found myself in a robot maintenance area...}

{200}{}{您好，介意我问一下你是怎么进来的吗？到地面的电梯坏了一段不短的时间了。}
{201}{}{怎么说好呢……我用绳子爬下电梯井……然后我爬过一个油腻腻的风扇管道，发现自己在一个机器人维修区……然后……}


# Node  1  [Node002]
#{210}{}{I'm surprised you made it past all those damn plants without being eaten. I'm Hologram 10031, the Director of Ground Maintenance here at the EPA. [He sighs heavily.] I know, I know, the grounds look terrible. No need to tell me.}
#{211}{}{If you're not happy with the way the grounds look, why don't you do something about it?}
#{212}{}{No kidding. The grounds are littered with radioactive goo, corpses, mutant carnivorous plants... Seriously, you must be the worst groundskeeper ever.}

{210}{}{我很惊讶，你竟然没被那些该死的植物吃掉。我是全息图像10031，环境保护局地面维护主任[他重重的叹了口气。我知道这里看起来很糟糕]}
{211}{}{如果你不满意这里，你为什么不做点什么呢？}
{212}{}{这真不是开玩笑的，满地都是放射性物质、尸体、还有一箩筐的变异食肉植物……说真的，你一定是史上最差的园丁。}


# Node  2  [Node003]
#{220}{}{If I could do something about it, trust me, I would. I've got no physical body, and the damn robots won't respond to a word I say. I've been operating at 100% inefficiency for the last few decades -- how pathetic is that? The other Holograms won't let me forget it either. The only one more useless than me is the Director of Operations.}
#{221}{}{Maybe I could help somehow?}
#{222}{}{That's really a shame. I have to be going now. Goodbye.}

{220}{}{如果我能做点什么，相信我，我肯定会去做的。我没有身体，也没有权限，该死的机器人不会回应我说的话。在过去的几十年里，我一直在以100%的低效率工作……这是多么可悲的事？其他的全息图也不会管这些事情，唯一比我更没用的是运营总监。}
{221}{}{也许我可以帮助你?}
{222}{}{那真是太遗憾了，我得走了，再见。}

# Node  3  [Node004]
#{230}{}{Hey, if you're really willing to help, that'd be great. I'll ensure you get something for your troubles.}
#{231}{}{Consider it done. What can I help you with?}
#{232}{}{No, I haven't the time right now.}

{230}{}{嘿，如果你真的愿意帮忙的话，那就太好了。我保证你会为你的麻烦得到回报的。}
{231}{}{我能帮你什么呢？}
{232}{}{不，我现在还没有时间。}

# Node  4  [Node005]
#{240}{}{Those mutated spore plants have spread beyond the confines of the green house and have taken root all over the EPA's grounds. If you could get rid of all those bastards for me, that'd be a big step in the right direction.}
#{241}{}{Sure, I could kill all the spore plants for you. I'll be back once it's done.}
#{242}{}{That's easy enough. I already killed them all.}

{240}{}{那些突变的孢子植物已经扩散到地面建筑的范围之外，并在EPA周边的泥地上生根发芽了，这会危害周边的安全。如果你能帮我干掉那些该死的孢子植物，那将是朝着正确方向迈出的一大步。}
{241}{}{当然，我可以为你杀死所有的孢子植物。一旦完成，我就回来。}
{242}{}{这太简单了，我已经把那些孢子植物都干掉了。}

# Node  5  [Node006]
#{250}{}{Hello again. What can I do for you? *Sigh*}
#{251}{}{You're looking rather glum. What's wrong?}

{250}{}{你好，我能为您做些什么？[叹气]}
{251}{}{你看起来很忧郁，怎么了?}


# Node  6  [Node007]
#{260}{}{Hello again. Have you reconsidered helping me? As I mentioned before, I'll make it worthwhile for you.}
#{261}{}{Yeah, why not. I have nothing better to do.}
#{262}{}{No, I'm still too busy at the moment. I'll come back some other time.}

{260}{}{你好，你有重新考虑过我的提议吗？正如我之前提到的，我会给你报酬的。}
{261}{}{嗯，为什么不呢，现在我也其它事做。}
{262}{}{不，我现在还是太忙了。我改天再来吧。}


# Node  7  [Node008]
#{270}{}{Have you completed the task for me?}
#{271}{}{Yep, I've killed all the plants. The grounds still look like hell, but at least they're a little safer.}
#{272}{}{No, not yet. I'll have to get back to you.}

{270}{}{你已经完成了我的任务吗？}
{271}{}{是的，我杀死了所有的植物。地面仍然看起来像地狱，但至少它们更安全一些。}
{272}{}{不，还没有，我稍后再回来。}

# Node  8  [Node009]
#{280}{}{Oh, thank you so much. For that, I hereby hire you as my assistant groundskeeper. [He points to a key on the floor by his feet.] I managed to coax one of the half working robots into bringing that for you. You now have authorization to access the storage shed. Thanks again.}
#{281}{}{[You pick up the key and pocket it.] No problem. See ya.}

{280}{}{太感谢你了，作为报酬，我特聘请你为我的助理场地管理员，[他指着地板上的一把钥匙]，我设法说服了一台的工作机器人把它带来，您用它可以打开地面的存储库，再次感谢。}
{281}{}{[你拿起钥匙，把它装在口袋里]再见。}

# Node  9  [Node010]
#{290}{}{You look rather messy. Is everything all right?}
#{291}{}{Yeah, I'm fine. I had some trouble with some mutated plants on the way down here but I took care of them.}

{290}{}{你看起来不是很好，一切都还好吗? }
{291}{}{嗯，我很好。我在来这儿的路上遇到了一些突变的植物，但我已经"照顾"好它们了。}

# Node  10  [Node011]
#{300}{}{You have? Wonderful! For that, I hereby hire you as my assistant groundskeeper. [He points to a key on the floor by his feet.] I managed to coax one of the half working robots into bringing the keys to me awhile ago -- just in case. Take 'em. You now have authorization to access the storage shed. Thanks again.}
#{301}{}{Oh no. It's all I could do. Don't worry about it.}
#{302}{}{Hey thanks! Goodbye.}

{300}{}{太感谢你了，我特聘请你为我的助理场地管理员，[他指着地板上的一把钥匙]，我设法说服了一台的工作机器人把它带来，您用它可以打开地面的存储库，再次感谢。}
{301}{}{哦，这是我能做的，别担心。}
{302}{}{谢谢！再见。}

# Node  11  [Node012]
#{310}{}{Hey, you've done me a good turn so you'll take the key and anything you want or need. It's my way of saying thank you for what you've done.}
#{311}{}{Oh, all right then. Say who are you anyway? Why is it so important to you that I've killed all of these plants?}

{310}{}{Hey, you've done me a good turn so you'll take the key and anything you want or need. It's my way of saying thank you for what you've done.}
{311}{}{Oh, all right then. Say who are you anyway? Why is it so important to you that I've killed all of these plants?}

# Node  12  [Node013]
{320}{}{你帮了我一个大忙，所以你可以拿走钥匙和任何你想要或需要的东西，这是我对你表示感谢的方式。}
{321}{}{哦，那好吧。你到底是谁？为什么我杀了所有这些植物对你这么重要？}


#{330}{}{Keep up the good work, assistant.}
#{331}{}{I'm now operating at 1% efficiency!}
#{332}{}{You wipe out the mutant plants that have grown rampant over the EPA's grounds.}
#{333}{}{The whole place has been taken over by these mutant plants.}
#{334}{}{They're everywhere.}
#{335}{}{And then there's the mantises...}
#{336}{}{The greenhouse is in shambles.}
#{337}{}{If only the robots would respond to commands.}
#{338}{}{I know, I'm a complete failure.}
#{339}{}{I thoroughly apologize for the state of the grounds.}
#{340}{}{If I could do something about it, I would.}
#{341}{}{Maybe 10001 is right. Maybe we should just destroy it all.}

{330}{}{好好干！助理。}
{331}{}{我现在的工作效率是1%!}
{332}{}{你消灭在EPA土地上蔓延的变种植物。}
{333}{}{整个地区都被这些突变植物接管了。}
{334}{}{它们到处都是。}
{335}{}{然后是螳螂……}
{336}{}{这个温室一团糟。}
{337}{}{如果只有机器人会对命令作出反应。}
{338}{}{我知道，我是一个彻底的失败者。}
{339}{}{我为我刚刚的状态道歉。}
{340}{}{如果我能做些什么，我会的。}
{341}{}{也许全息图10001是对的，也许我们应该摧毁一切。}

