#{100}{}{You see Sergeant Cat Jules.}
#{101}{}{You see a good-looking black man with rather pronounced canines. He moves with a constant swagger and has a smug expression on his face.}
#Cat Jules

{100}{}{你看见朱利斯中士，也是一只猫。}
{101}{}{你看到一个看起来挺英俊的黑人，他的犬齿非常明显。}


#{200}{}{[As you approach the cryogenic chamber, you see a slender, naked black man sprawled on the floor. His muscular body is still shaking from the icy, cold water. He looks up at you as you approach.]}
#{201}{}{Who are you?}

{200}{}{[当你走近冰冷的休眠仓时，你看到一个身材苗条、赤身裸体的黑人趴在地板上。由于低温，他那肌肉发达的身体一直在颤抖，他抬头看着你。]}
{201}{}{你是谁？}

#{210}{}{[Standing up and shaking himself dry like a wet animal, the man looks at you and smirks, revealing some oddly sharp front teeth.] Who am *I*? Who are *you*? You look like a heavily armed hobo!}
#{211}{}{[Standing up and shaking himself dry like a wet animal, the man looks at you grinning widely, revealing some oddly sharp front teeth.] Who am *I*. Why, I'm only Sgt. Jules, the best-looking soldier on this base, gorgeous!}
#{212}{}{I'm }
#{213}{}{. But, what's your name?}
#{214}{}{Don't you get cocky with me. What's with this place anyway?}
#{215}{}{I see. Well, Sgt. Jules, what's going on around here anyway?}
#{216}{}{How come you're alive? The Doctor said he was the only survivor.}

{210}{}{[他努力地站起来，湿辘辘的身体就像掉进水里的动物一样。突然，他对着你笑了，露出了一嘴锋利的牙齿]我是*谁*？为什么不让我先问问你是谁呢？你看起来就像一个全副武装的垃圾佬！}
{211}{}{[他站起来，湿辘辘的身体浑身发抖。突然，他对你笑了，露出了一嘴锋利的牙齿] 我是*谁？我是朱利斯中士，这个基地里最完美的士兵！}
{212}{}{我是 }
{213}{}{。 你的名字是？}
{214}{}{注意一下你的态度，这个地方是怎么回事？}
{215}{}{我明白了。朱利斯中士，这里到底是怎么回事？}
{216}{}{你是怎么活下来的，医生说他是这里唯一的幸存者。}


#{220}{}{The name's Sgt. Jules, but you can call me Cat. I'm the fastest and best-looking soldier on this base.}
#{221}{}{Right, whatever you say. So, what's with this place?}

{220}{}{我的名字朱利斯，军阶是中士，你也可以叫我做"猫"，我是这里最好的士兵，最强壮，最敏捷，最帅。}
{221}{}{好吧，这个地方是怎么回事？}



#{230}{}{You mean Doctor C? Why would he forget about me? Hell, he helped shape this work of *ART* [He gestures at his body].}
#{231}{}{Right, whatever you say. So, what's with this place?}
#{232}{}{I think we are talking about two different people...So, what's going on around here anyway?}

{230}{}{你说C医生？为什么他没有提起我？他可是打造了这件艺术品的人[他指了指自己的身体]。}
{231}{}{好吧，别在意刚刚的对话了，这个地方是怎么回事？}
{232}{}{我想我们谈论的是两个不同的人...那么，这里到底发生了什么？}



#{240}{}{This is some government facility as far as I know. They do all kinds of top secret research. But...[He looks around the room.] it's awfully quiet. Where is everybody?}
#{241}{}{Well, this is probably going to come as a shock to you, but you've been frozen for over a century. The world's not the same anymore. They dropped the bombs and the Earth went silent. Society is still trying to rebuild itself from the ashes.} 
#{250}{}{[Sgt. Jules looks at you with a raised eyebrow.] You ain't kidding, are you? Well, they actually followed through with it then. Damn. Guess I'm lucky to have been pulled from the military and brought here.}
#{251}{}{You were in the army?}

{240}{}{这是一个政府机构，在这里有着各种各样的绝密研究，我知道的就是这么多。[他停了一下，环视了一下房间]这里太安静了，这是怎么回事，人都到哪里去了？ }
{241}{}{呃，我说的话可能会让你感到震惊。你已经被冻在这个冰箱里一个多世纪了，外面的世界已经和你认识的完全不一样了。天上下了炸弹雨，蘑菇云升起后之后地球就沉默了。现在这个时间，人们正从废墟里爬出来，努力地重建文明。} 
{250}{}{[朱利斯睁大了眼睛看着你] 你不是在开玩笑吧？尽管我在过来之前就有听说过两个国家对丢炸弹这件事，但这竟然真的发生了，该死的。我想我应该很庆幸被从军队里拖到这里来。}
{251}{}{你在军队里？}


#{260}{}{Yep. I was the energy weapons expert. Pretty nimble on my feet too. I was only in the army for about a year before I was reassigned here. It's a shame I'll never see any of my friends again. I would have liked to have exchanged some goodbyes.}
#{261}{}{I'm sorry.}
#{262}{}{I'm sorry for your losses, but you have to move on. Wallowing in your own misery won't get you anywhere.}

{260}{}{没错，我是能源武器专家，我跑得也很快。但在我被调到这里之前，我只在部队待了一年左右。我再也见不到我的朋友了，这真的太糟糕了，我本来还想交换一些临别礼物的。}
{261}{}{我很抱歉。}
{262}{}{对你身上发生的事我深表同情，但事情已经发生了。振作点吧，沮丧不会让你得到任何好处。}


#{270}{}{Yeah, ain't we all. What am I gonna to do now though?}
#{271}{}{I guess you're right. What am I going to do now though?}
#{272}{}{Well, I could use a companion. Want to join me?}
#{273}{}{Well, I really must be going. Best of luck to you out there.}

{270}{}{你说得对，起码我还在这里，不是么。对于眼前你有什么建议？}
{271}{}{我觉得你是对的，对于眼前你有什么建议？}
{272}{}{嗯，我这里刚好缺少一只猫，想要加入吗？}
{273}{}{嗯，就谈到这里吧，我必须要走了。}


#{280}{}{Hey, why not! I'll show you this Cat still got what it takes.}
#{281}{}{Sounds good. Let's go.}
#{282}{}{Whatever you say.}

{280}{}{嘿，为什么不呢！我来告诉你这只猫有多大的本事吧。}
{281}{}{听起来不错，我们走吧。}
{282}{}{那就这样吧。}


#{2900}{}{I need to put on some clothing first. [Looking around, Cat spots a locker, opens it and looks inside.] These really aren't my style, but I guess they'll do. [He quickly puts the clothing on.] Alright, I'm good to go.}
#{2901}{}{[END]}

{2900}{}{[他环视四周，很快，猫找到一个了储物柜，他熟练地打开了锁]这衣服品味真差，但就先穿这个吧[他很快就把衣服穿上了。]好了，我们走吧。}
{2901}{}{[结束]}

#{290}{}{Don't you worry about this ol' cat. I'll find my place in this world. Now step aside and let the Cat do his thing.}
#{291}{}{[END]}

{290}{}{你不担心这只猫吗？算了，我会在这个世界上找到我的位置的。现在走开，让猫去做他的事。}
{291}{}{[再见]}



#past
#{300}{}{So, how did you end up in that cryo chamber? And what happened to your teeth?}
#{301}{}{I used to be the guard for one of the genetics labs. They were messing with human and feline DNA. Trying to make something with the best of both worlds, I suppose. And that's where yours truly comes in. [Cat flashes you his toothy grin.] They wanted a volunteer for one of their projects. It was for scouts and the like, supposed to make you more agile and flexible. I liked the sound of that *leers*. Anyway, they gave me this shot, put me under, and the next thing I knew, I had these teeth, and I felt... sharper? Kind of predatory.}
#{302}{}{Go on.}
#{303}{}{Well, apparently the experiment wasn't going as planned and whatever they put inside me wasn't sitting well with my system. I don't know what they meant by that, since I felt better than ever. They decided to throw me in the cryo freezer until they figured out what to do with me.}
#{304}{}{And then I thawed you out. Seems like you owe me one.}
#{305}{}{Yeah, you saved me. In return, maybe I can save your sense of style, monkey.}
#{306}{}{Monkey? Must be the cat DNA talking. That's all I need to know for now.}

{300}{}{你为什么会在休眠仓里的？还有，你的牙齿是怎么回事？}
{301}{}{我曾经是一个遗传学实验室的守卫，在那里科学家们尝试把人类和猫科动物的DNA混合。[他向你笑了笑]刚好他们想为实验室的项目找一个志愿者。然后就像你现在看到的这样了，他们曾经给我一张旧照片，上面是我原来的样子。但实际上，我更喜欢现在这个样子，[他上下碰撞他的尖牙齿，发出咯咯咯的声音]，这声音真是好极了。}
{302}{}{[继续]}
{303}{}{但很显然的是，这个实验没有得到科学家们预期中的结果，他们觉得这个结果出了偏差--尽管我觉得比以前好多了。然后他们决定把我扔进休眠仓，直到他们弄明白我发生了什么事。}
{304}{}{然后就是我把你从冰箱里解冻了，你欠我一个人情。}
{305}{}{是的，你救了我。作为回报，也许猫可以记住你的样子，猴子。}
{306}{}{猴子？好吧，这一定是猫的DNA在作祟。我要知道的就是这些。}



#teach
#{310}{}{Since you were in the army, you think you might be able to teach me anything?}
#{311}{}{I might be able to teach you a thing or two about energy weapons and other big weapons. Now you have to remember...}
#{312}{}{[Continue.]}
#{313}{}{There you go. That should help you melt those mutants who get in your way.}
#{314}{}{Thanks.}

{310}{}{既然你曾经在军队里，你有什么能教我的吗？}
{311}{}{我也许可以教你一些关于小型武器、大型武器，还有猫最喜欢的能源武器的事情。现在你必须记住...}
{312}{}{[继续]}
{313}{}{好了，这应该能帮到你融化那些挡在你前面的畸形怪物的。}
{314}{}{谢谢。}

#party was full when first tried to recruit
#{390}{}{You ready to take me with you?}
#{391}{}{Let's go.}
#{392}{}{No, not yet.}

{390}{}{你准备好带猫走了吗？}
{391}{}{走吧，好猫咪。}
{392}{}{不，以后再说。}


#in party
#{400}{}{Need something?}
#{401}{}{How can the Cat be of service?}
#{402}{}{Yes?}

{400}{}{需要什么？}
{401}{}{需要猫为你做什么？}
{402}{}{是？}

#skills
#{410}{}{What do you need to know?}
#{411}{}{Well, I was trained to use the usual military stuff. Rifles, pistols, SMGs and the like. I prefer laser weapons and the like better though. Those have style! But if you give me some brass knuckles or one of those power fists, I'll pounce on any flat-footed goons before they know what hit them!}

{410}{}{你需要知道些什么？}
{411}{}{嗯，我精通常规的军事装备，步枪，手枪，SMG都可以。不过我更喜欢激光武器，它们biu起来更有范儿！当然，我的近战格斗也很不错，如果你给我一个拳指虎之类的闪亮玩意，我也能把敌人打得满地找牙。}

#distance
#{421}{}{What's wrong with it?}
#{422}{}{Alright. I have your back.}
#{423}{}{Fine by me.}
#{424}{}{I work better solo anyway.}

{421}{}{怎么了？}
{422}{}{好的。猫会跟在你后面。}
{423}{}{猫会自由活动的。}
{424}{}{猫单干就行。}


#wait
#{430}{}{I don't have much patience, so hurry back.}
#{431}{}{I'm not a fan of waiting. Don't take too long.}

{430}{}{猫一向都没有太多的耐心，所以赶快回来吧。}
{431}{}{猫不喜欢等待，不要离开太长时间。}

#come back
#{440}{}{We moving out?}
#{441}{}{It is about time you got back.}

{440}{}{我们能走了？}
{441}{}{欢迎你，好猫咪。}

#lets go
#{450}{}{It's good to be on the move again. My legs need to keep moving.}
#{451}{}{It's about time we did something together again.}

{450}{}{猫的腿需要好好活动一下。}
{451}{}{是时候让我们一起干点事情了。}

#remove armor
#{460}{}{Sure, it looks like crap anyway. Got anything in blue?}

{460}{}{好的，反正这个看起来太难看了，有蓝色款的吗？}

#unwield weapon
#{470}{}{Ok, but this is *my* shiny thing. And if you try and take it off me, I may have to shoot you.}
{470}{}{好吧，但这些闪闪亮的东西是我的，如果你试着把它从我身上拿走，猫可能要杀了你。}


#hurt
#{480}{}{I'm feeling top notch.}
#{481}{}{Just a few scratches, nothing to worry about.}
#{482}{}{I've seen worse in the army.}
#{483}{}{Call a medic. I'm going down fast.}
#{484}{}{I'm bleeding out of everything now...}

{480}{}{这个感觉真好。}
{481}{}{不过多了几处擦伤，没有好担心的。}
{482}{}{我在军队里见过更糟的情况。}
{483}{}{打电话叫急救车，我要医生！越多越好！}
{484}{}{我现在正在流血...}

#ch <= 1
#{490}{}{Jesus, your ugly. You ought to get yourself checked out. I'm outta here.}
#{491}{}{Baby, you got real ugly. I'm outta here.}

{490}{}{上帝，你太难看了，你应该去找个医生好好检查一下，我先走了。}
{491}{}{宝贝，你可不符合一只猫的审美，我先走了。}

#party full
#{500}{}{Don't get me wrong, it is good to stick together, but you are taking this a little too far. Come back when you got less people.}
#{501}{}{Don't get me wrong, it is good to stick together, but you are taking this a little too far. Come back when you got less people. Now while you are making room, I'm going to find some clothing to wear. [Looking around, Cat Jules spots a locker, opens it and looks inside.] These really are not my style, but I guess they will do. [He quickly puts the clothing on.] Alright, let me know when you are ready.}

{500}{}{不要误会我的意思，团在一起是很暖和，但是你太过分了。当你队伍人少点的时候再来。}
{501}{}{不要误会我的意思，团在一起是很暖和，但是你太过分了，[他环视四周，很快，猫找到一个了储物柜，他熟练地打开了锁]这衣服品味真差，但就先穿这个吧[他很快就把衣服穿上了]如果你队伍人少点的时候再回来吧。}

#poisoned
#{510}{}{Did I eat bad fish or something? I feel poisoned.}
{510}{}{我吃了坏掉的鱼了吗，猫感觉头晕。}


#radiated
#{520}{}{I feel like I am melting away here. Must be radiation poisoning.}
{520}{}{这里热得猫都要融化了。}


#broken limb
#{530}{}{How do you expect me to perform at my best with this broken limb?}
{530}{}{你要指望一只猫用断了的爪子挠人吗？}

#blind
#{540}{}{Who turned out the lights? I think something's wrong with my eyes.}
{540}{}{有人开了灯吗？猫看不见了。}


#generic floats
#{600}{}{Some might say I'm a pretty shallow guy, but a shallow guy with a great ass.}
#{601}{}{In the army it was always, "Cat do this. Cat do that." What am I, a dog?}
#{602}{}{[singing] 'Cause you make me tongue tied, tongue tied... [singing]}

{600}{}{有些人可能会说我是一个很肤浅的人，但我想说，只不过是他们太浅薄而以。}
{601}{}{在军队里总是：“猫会这样做”，“猫去做那个”，“猫应该这样做的”。我是什么，狗吗？}
{602}{}{*唱歌*因为你使我舌头打结，舌头打结...*唱*}



#location floats
#New Reno
#{700}{}{LADIES! Ladies, one at a TIME, please!}
{700}{}{小猫咪们，请一个个来！}


#Military Base
#{710}{}{I've got a nose for trouble, and it's going off like a nuke attack siren!}
{710}{}{猫闻到了麻烦。}

#Redding
#{720}{}{GOLD mining? This where they dig up the shiny things?}
{720}{}{金矿吗？这里看起来更像生产闪亮猫玩具的地方。}
#EPA
#{730}{}{I thought we were leaving this place for good?}
{730}{}{猫不喜欢这里。}


#NPC floats
#Myron
#{800}{}{I've had enough of smart-ass lunatics! Can we leave this greasy little idiot?}
{800}{}{猫受够这个愚蠢的疯子了！我们能离开这个油腻的小白痴吗？}

#Sulik
#{810}{}{What's with the bone, Neanderthal?}
{810}{}{这个骨头是什么？一个诗人吗？}

#Lenny
#{820}{}{Least I didn't end up like YOU, Lenny!}
{820}{}{幸好我没变成你这样，廉尼！}
#Marcus
{830}{}{幸好我没变成你这样，大家伙！}



#Don't apply ERSI to specimen == horrible flaming death for specimen
#{5000}{}{[The man stands up and shakes himself dry like a wet animal. As he looks at you, his eyes suddenly get really wide and he starts gasping for air.}
#{5001}{}{[END]}
#{5002}{}{Holy shit!}

{5000}{}{[这个男人站起来，他浑身发抖，大口的吸着气试着对抗低温。过了好一会，他望向你的方向，突然...]}
{5001}{}{[结束]}
{5002}{}{操！}

