#{100}{}{You see Dex.你看到德克斯}
#{101}{}{You see a handsome, impeccably groomed man. Beneath an impressive shock of grease-slicked hair, his eyes sparkle with intensity... or perhaps insanity.你看到一个帅气的男人，衣着完美无缺。在茂密发亮的头发之下，他的双眼闪烁着一丝紧张...或者可能是一丝疯狂。}

{100}{}{你看到德克斯}
{101}{}{你看到一个帅气的男人，衣着完美无缺。在柔顺发亮的头发之下，他的双眼闪烁着一丝紧张...也可能是一丝疯狂。}


#good/neutral male intro
#{200}{}{[Aem against his chest. He sits there for several moments, staring blankly ahead as his body quakes and his teeth chatter. Gradually, he seems to calm down.][当你接近冷冻室时，你看到一个迷人的裸体男子蜷缩在地板上。他弯着双腿，把膝盖抱在胸口。他坐了一会儿，双目无神地看着前方，而身体在战栗，嘴里在嘟囔。慢慢地，他看起来冷静下来了。]}
#{201}{}{Uh, hello?呃，你好？}

{200}{}{[当你接近冷冻仓时，你看到一个迷人的裸体男子蜷缩在地板上。他蜷曲着双腿，把膝盖抱在胸口。他坐了一会儿，双目无神地看着前方，身体和嘴巴因为寒冷不停地颤抖着。慢慢地，他看起来平静下来了。]}
{201}{}{呃，你还好吗？}

#{210}{}{[He snaps his head towards you and leaps to his feet. He watches you intently, then glances around like a cornered animal. When his eyes return to you, they soften, and he relaxes as his memories come flooding back to him. He quickly alters his composure, projecting cool confidence, despite his nakedness.] I don't recognize you, bud. You don't mind if I get dressed do you?[他突然把头转向你，猛地站起来，仔细地观察着你，然后四处张望，就像一只被逼到角落的动物。他的眼睛转回到你身上，慢慢柔和和放松，他的记忆涌入了他的大脑。他突然变得冷静，释放出冷静的自信，即使他还裸体着。]我不认识你，伙计。你不介意我穿上衣服，对吧？}
#{211}{}{I guess there's no harm-我认为这没有坏处。}
#{212}{}{Well, I-好。我——}

{210}{}{[他突然把头转向你，猛地站起来，仔细地观察着你，然后四处张望，就像一只被逼到角落的动物。过了好一会，他的眼睛转回到你身上，慢慢地他放松下来，他的记忆涌入了他的大脑。他突然变得冷静下来，他的表情变得非常自信，即使他还是赤身裸体着。]我不认识你，伙计。你不介意我穿上衣服，对吧？}
{211}{}{我认为这没有坏处。}
{212}{}{当然。}


#{220}{}{Of course you don't mind. Thanks, pal. [He steps past you and opens a nearby locker. He casually dresses himself in a finely tailored suit, then pockets the locker's contents. Utilizing a pocket comb, he begins to sculpt and style his slicked dark hair with the quick precision of a seasoned pro.] So, where's the doc? 当然你不介意。谢了，朋友。[他走到你后面打开了一个锁箱。他非常习惯地穿起了一套精细裁剪的套装，口袋里装入了锁箱里的东西。用一把随身的梳子，他开始用一种流行的款式，仔细地雕刻和装饰他的闪亮黑发]所以，医生在哪里？}
#{221}{}{The doc? Oh, he's probably around here somewhere. In fact, I think he's on his way now, so I'll just mosey on out of here and let you two catch up. Bye!医生？哦，他可能在附近。实际上，我认为他已经上路了，我就是在附近闲逛的，你自己去追他吧。拜！}
#{222}{}{This may come as a shock to you, but you've been frozen for a very long time. Whoever "the doc" was, he's certainly long dead by now. If he was your friend, then I'm sorry.这对你可能很震惊，但是你已经被冷冻了很久了。不管这个“医生”是谁，他绝对早就死了。如果他是你朋友，我很抱歉。}
#{223}{}{I don't mean to blow your mind, but you've been on ice for a *real* long time. I'm pretty sure your friend, "the doc", is long dead by now.我不是故意要刺激你的，但是你已经被冻在冰里“很”久“很”久了。我很确定你的朋友，这个“医生”，早就死了。}
#{224}{}{Listen up, pretty boy. I didn't unthaw your psychotic ass so I could answer your questions and watch you groom yourself. I'm only letting you live long enough to tell me whatever useful information you might have. So start talking. The more you can tell me, the longer you get to live.听着，靓仔。我解冻你的疯屁股并不是要回答你问题和看你刷毛的。告诉我任何有用的信息，我就让你活着。现在谈话开始。你可以告诉我的越多，你就可以活得越久。} 
#{230}{}{[His cool demeanor vanishes and his eyes flare with rage.] You think you can intimidate ME? Do you have the first FUCKING CLUE who you're talking to? Come here and I'll show you what I'm capable of![他冷静的态度消失了，眼里冒出愤怒的火焰]你认为你可以威胁老子？你晓不晓得你在跟那个说话？过来，老子给你点颜色看看！}
#{231}{}{[Done.][结束]}

{220}{}{感谢你的不介意，朋友。[他走到你后面，打开了一个锁箱，然后非常习惯地穿起了一套精细裁剪的套装，接着他开始把锁箱里的东西也逐一放到身上。做完这一切之后，他拿出一把随身的梳子，然后开始用一种近乎苛刻的态度仔细地雕刻和装饰他的闪亮黑发。过了好一会，他回过头来。] 所以，医生在哪里？}
{221}{}{医生？哦，他应该在附近。我认为他可能在外面，实际上我就是在附近闲逛的，你自己去追他吧。拜！}
{222}{}{说事实的话可能会令你很震惊。你已经被冷冻了很久了，不管这个“医生”是谁，他绝对早就死了。如果他是你朋友，我很抱歉。}
{223}{}{我不是故意要刺激你的，但是你已经被冻在冰里“很久很久”了。我很确定你的朋友，这个“医生”，早就死了。}
{224}{}{听着，我解冻你这个混球并不是要回答你问题和看你刷毛的。告诉我有用的信息，我就让你活着。你可以告诉我的越多，你就可以活得越久。现在开始把你知道的吐出来。} 
{230}{}{[他冷静的态度消失了，眼里冒出愤怒的火焰]你认为你可以威胁老子？你知道你在跟谁说话吗？过来，老子给你点颜色看看！}
{231}{}{[结束]}

#{240}{}{[Dex grins at you, revealing a set of perfect teeth-a product of pre-war dentistry that look strange to you in all their pearly white symmetry.] The doc, my friend? [He cocks an eyebrow.] You don't know who I am, do you?[德克斯对你笑着，露出一幅完美的牙齿——这是战前牙科学的产物，在你看来很奇怪，它们都是珍珠般的白色]医生，我的朋友？[他抖了抖眉毛]你不认识我，对吧？]}

{240}{}{[德克斯对你笑着，露出一幅完美的牙齿——在你看来很奇怪，它们都是珍珠般的白色，也许这是战前牙科学的产物吧]医生，我的朋友？[他抖了抖眉毛]你不认识我，对吧？]}

#{241}{}{Uh, not exactly. I've been sort of wandering around this strange facility, tinkering with stuff, and I just so happened to unthaw you. Why were you frozen in there, anyway?呃，不一定。我就是在这个奇怪的设施附近闲逛，东摸西抠，偶然把你解冻了。呃，你为什么被冻在那里？}
#{242}{}{Well, according to that computer, you're Dex, a narcissistic, sociopathic killer from before the great silence. I only unthawed you so I could put you down like the sick dog you are.嗯，根据那台电脑的说法，你是德克斯，一个来自大寂静之前的自恋反社会杀手，我把你解冻，就是为了能够像宰掉一条死狗那样宰掉你。}
#{243}{}{Uh, not exactly. I'm sure you're a perfectly normal guy that was kept frozen for perfectly normal, non-evil reasons. Hell, what do I know? I've been sort of wandering around this strange facility, tinkering with stuff, and I just so happened to unthaw you.呃，不一定。我确信你是个极其普通的人，因为一些非常普通的一点都不邪恶的理由被冻起来的。该死，我知道什么？我就是在这个奇怪的设施附近闲逛，东摸西抠，偶然把你解冻了。}

{241}{}{我相信我不认识你。我就是在这个奇怪的设施里闲逛，偶然把你解冻了。嗯，你为什么会被冻在那里的？}
{242}{}{我相信我不认识你。但根据那台电脑的说法，你是德克斯，一个来自大寂静之前的自恋反社会杀手，我把你解冻，就是为了能够像宰掉一条死狗那样宰掉你。}
{243}{}{我相信我不认识你。但我确信你是个极其普通的人，因为一些非常普通而且一点都不邪恶的理由被冻起来的。该死，我知道什么？我就是在这个奇怪的设施里闲逛，偶然把你解冻了而以。}


#{250}{}{[Dex takes another look around the room and whistles.] This place has really gone to shit. How long did you say it's been?[德克斯又看了看房间，然后悄声说道]这个地方就是一沱屎。你刚刚说有多久了？}
#{251}{}{It's been over a hundred and fifty years since the Great Silence brought an end to the Old Ones... *your* people.自从大寂静给“你的”旧世界画上句号，已经150年了...}

{250}{}{[德克斯又看了看房间，然后小声说道]这个地方就像是一沱屎。你刚刚说有多久了？}
{251}{}{自从大寂静给“你的世界”画上句号，已经150年了...}

#{260}{}{Great Silence? The Old Ones? How about you spare me this cryptic bullshit and just tell me what happened?大寂静？旧世界？你干嘛停住这些废话，直接告诉我发生啥了？}
#{261}{}{The Great Silence is what my people call the end of your world. When the great fires rained down from the sky and scorched the land. You'll find the world is nothing like the one you knew.大寂静就是我们这些人称呼你的世界终点的词。当业火从天而降，席卷大地，你就发现这儿世界和你所熟悉的完全不一样了}

{260}{}{大寂静？旧世界？你别跟我胡扯了，直接告诉我发生了什么事。}
{261}{}{大寂静，嗯，它的意思，直接点说就是属于你那个年代的世界已经终结了。当火焰像雨点一样从天而降之后，这个世界已经变了样了。}


#{270}{}{No shit, so they actually dropped the bombs, huh? I guess the vault project wasn't just a big waste of the tax-payers' money, after all.放屁，就是说他们真的丢了炸弹，嗯？避难所计划到最后并不是完全浪费纳税人的钱嘛。}
#{271}{}{Wait. You know of the holy vaults?等等。你听说过神圣避难所？}

{270}{}{放屁！等等，你是说他们真的丢了炸弹，嗯？看来避难所计划到最后并不是完全浪费纳税人的钱啊。}
{271}{}{等等。你听说过神圣避难所？}

#{280}{}{Know of them? Hell, I used to live right by the Chicago vault. I even watched 'em finish building the thing. Then of course they started doing those damn drills... [He stops and regards you with amusement.] You're really eating this up, aren't you?听说过？妈的，我过去就住在芝加哥避难所边上。我甚至看着他们完成这个东西。然后他们当然就开始做这个...[他停下来，戏谑地看着你]你要吃完这个了，是吧？}
#{281}{}{TELL ME MORE OF THE VAULTS!告诉我更多避难所的事！}
#{282}{}{Well, you see, I've been chosen by my people to try and find a Vault. There, I hope to retrieve a G.E.C.K. and use its power to save my village from destruction. Anything you can tell me of the Vaults could help me in my quest.呃，你知道，我被我的族人选出来找寻避难所。在那里我希望能回收一个GECK，然后用它的力量来拯救我的村子，避免毁灭。你告诉我的任何东西对我的任务都有用。}
#{283}{}{Well, you see, I had been chosen by my people to try and find a Vault. After risking my life in countless adventures, I finally discovered the Holy 13. However, I'm curious what else you might know of these places.呃，你知道，我被我的族人选出来找寻避难所。在数不清的冒险之后，我最终发现了神圣的13号避难所。但是，我也很好奇，对这些地方你还知道些什么。}


{280}{}{听说过？我可不单单是听说过。妈的，我过去就住在芝加哥避难所边上。我甚至看着他们完成这个东西。然后他们当然就开始做那些该死的训练...[他停下来，狡黠地看着你]你要找这个东西，对吧？}
{281}{}{告诉我更多避难所的事！}
{282}{}{这么说吧，我被我的族人选出来找寻避难所。在那里我希望能回收一个伊甸园创造器，然后用它的力量拯救我的村子。所以你告诉我的任何东西对我的任务都很有用。}
{283}{}{这么说吧，我被我的族人选出来找寻避难所。在数不清的冒险之后，我最终发现了神圣的13号避难所。但是，我也很好奇，对这些地方你还知道些什么。}

#{290}{}{I'll tell you what, bud. You need help finding these Vaults, and I need someone to show me the ropes, so to speak, in this crazy world of yours. So what do you say... partner?我会告诉你的。你需要有人帮忙找到这些避难所，我需要有人给我系上安全绳，在你这个疯狂的世界。所以，你觉得如何，伙伴？}
#{291}{}{Hmm, your knowledge of the old ones could prove quite useful to me... But, well, honestly, I, uh, read about you in that computer over there, and I'm not sure you're the type of guy I'd want to travel with.嗯，你对旧世界的只是会对我很有用...但是，说实话，呃，我在那台电脑里读过你的信息。我认为你不是我想一起旅行的人。}
#{292}{}{I don't really have the time to "show you the ropes". I'm sure you'll do just fine on your own, "bud".我没时间给你“系上安全绳”。我确信你自己也能行，“伙计”。}
#{293}{}{I say you've got a deal... partner.就这么说定了...伙伴。}
#{294}{}{I don't think I'm too eager to go gallivanting around the wasteland with a psychotic murderer. So you're on your own, "bud". Don't worry, I'm sure you'll be just fine. [Snicker.]我觉得我一点都不想跟一个疯狂杀手在废土上闲逛。现在你靠你自己了，“伙计”。别担心，我觉得你会很好的。}

{290}{}{我会告诉你的。这么说吧，老兄。你需要有人帮忙找到这些避难所，而我需要在你这个疯狂的世界里面有个人给我系上安全带。所以，我们一起合作，你觉得如何，“拍档”？}
{291}{}{嗯，你对旧世界的了解应该会对我很有用...。但是，在那台电脑里我读过你的信息。我认为你不是我想一起旅行的人。}
{292}{}{我不认为我能给你“系上安全绳”。我确信你自己也能行，“伙计”。}
{293}{}{就这么说定了...“拍档”。}
{294}{}{我不认为我会渴望和一个精神病杀人犯在荒地上闲逛。所以你只能靠自己了，别担心，我相信你会没事的。[窃笑]}


#{300}{}{Whoa, stop right there. Let me guess, you read I was some kind of crazy murderer, right? Well bud, I've got two words for you: Bull. Shit. Don't you buy a word of it.欧，停步，别动。我猜一下，你读到我是个疯狂杀手，对吧？好吧，伙计，我有两个字给你：狗，屎。你一个字都不要信。}
#{301}{}{But that doesn't make any sense, why would they lie about you?这完全没道理。他们骗我干嘛？}
#{302}{}{The only bullshit around here is what's spewing out of your mouth, and I think it's time I shut you up for good.这里唯一的狗屎就是你刚刚喷的。我觉得最好现在就让你永远闭嘴。}

{300}{}{欧欧欧，伙计，慢着慢着慢着，听我解释。我猜一下，你在电脑里读到我是个疯狂杀手，对吧？好吧，伙计，我有两个字给你：“狗”，“屎”。那些电脑里面你一个字都不要信。}
{301}{}{这并不合理，录入这些资料的人骗我干嘛？}
{302}{}{这里唯一的狗屎就是你刚刚喷的。我觉得最好现在就让你永远闭嘴。}



#{310}{}{Hey, I know it doesn't seem to make a lot of sense, but have you looked around this place? There's not much sense to be made around here. Who knows what goes on in the fucked up minds of these scientists. 嗨，我知道这看起来没啥道理，但是你看过这周围吗？这里更没有多少道理。我睡到这些他妈的科学家脑子里在发什么疯？}
#{311}{}{Hmm... you've got a point, there. I'm not saying I believe you... but I guess I can at least hear you out.嗯...你说得对。我不是说我相信你，但是我觉得我可以听听你说的。}
#{312}{}{Yeah, no kidding. Go on...对，不开玩笑，继续。}

{310}{}{嘿，伙计，我知道这听起来没什么道理，但是你看过这周围吗？这里的东西有多少道理？谁知道这些科学家脑子里到底在想些什么？}
{311}{}{嗯...你说得对。我不是说我相信你，但是我觉得我可以听听你说的。}
{312}{}{对，不开玩笑，继续。}


#{320}{}{Alright, you see, it's all part of their "experiments". These crazy fucking doctors were doing some kind of tests on the "nature of human evil" or some crap. They wer e injecting me with the memories of a maniac in order to see how it would affect the personality of a normal person. At least, that's the best I could figure it.好的，你看，这就是他们的“实验”。这些疯狂博士在测试一些“人性本恶”或者其他什么狗屎。他们给我注射了一个疯子的记忆，来测试这种记忆如何影响普通人的人性。至少，最多能指出这些。}
#{321}{}{Well... if that's true, then that's terrible. But what made them choose you as a test subject in the first place?好吧...如果是这样，就太早了。但是，他们为什么选你昨晚测试样本？}
{322}{}{Wow man, that really sucks. Anyway, that's all the in past now. Those asshole scientists are long dead and won't be able to mess with you anymore. Come along with me and we'll get out of this place.喂，这件事情真倒霉啊。不管怎样，都是过去了。这些狗屁科学家早就死了，再也不能搞你了。跟我来，我们一起出去。} 
#{330}{}{Heh, you see that's the funny thing. *I* actually came to *them*. Answered an ad they put out saying they'd pay big bucks for healthy test subjects. I needed the money, and, well, it turned out to be the worst mistake of my life. I can't even begin to tell you the horrors they subjected me to. [His eyes shimmer with tears as he reflects. He sighs deeply and wipes the tears away.] Anyway, thanks to you, bud, I'm finally free of that nightmare.嗨，你看到那个搞笑玩意儿了嘛？“我”就是为“他们”来的。我打了他们登出来的广告电话，广告说他们会给健康的测试对象付一大笔钱。我要这笔钱，嗯。很明显我这辈子最严重的错误。我甚至不能给你说他们给我注射的恐怖。[他眼角反射着泪光。他长叹一口气，抹去泪水]无论如何，谢谢你，老兄。我最终从这个噩梦中自由了。}
#{331}{}{Huh. Well, I'm glad I could help... I think.呃，好嘛，我很高兴能帮忙...}
#{332}{}{Actually, asshole, your nightmare's just begun, because I'm not buying a word of this.实际上，老屁眼，你的噩梦才刚刚开始，因为我一个字都不信。}


{320}{}{好吧，你看，这都是他们“实验”的一部分。这些科学狂人在做一些关于“人性本恶”的测试或者一些其它什么类似的垃圾实验。他们把一个疯子的记忆注入我的大脑，目的是想看看它会如何影响一个正常人的性格。至少，这是我能想到的最好的了。}
{321}{}{嗯...如果这是真的，那就太糟糕了。但究竟是什么原因让他们选择你作为测试样本呢?}
{322}{}{哇，伙计，那真是糟透了。不管怎样，这件事情过去了。那些混蛋科学家早就死了，再也不能对你做什么了。跟我来，我们离开这个地方。} 
{330}{}{实际上是“我”主动找“他们”的。我打了他们登出来的广告电话，广告说他们会给健康的测试对象付一大笔钱。我要这笔钱，嗯。但很明显这是我这辈子最严重的错误。我甚至不能告诉你他们让我遭受的恐怖。[他眼角反射着泪光。他长叹一口气，抹去泪水]无论如何，谢谢你，老兄。我最终从这个噩梦中自由了。}
{331}{}{呃，好嘛，我很高兴能帮忙...}
{332}{}{实际上，混球，你的噩梦才刚刚开始，因为我一个字都不信。}


#{340}{}{So how 'bout it, pal? Can we partner up? Not only will you get to feel cooler by hanging out me, but I can handle myself in a fight. Hell, I'd be alright with going solo, but I've got no clue what kind of crazy shit is lurking out there now. For all I know, the first tree I piss on could open up its mouth and bite my cock off.老伙计，那这样如何？我们组队吧？不只是你离开我会更冷，我在打斗中也可以照顾我自己。妈的。我本来单干很不错的，但是我不知道这个世界都会潜伏着些什么。我怀疑我尿尿的第一棵树就想张开嘴咬掉我老二。}
#{341}{}{Alright, you can travel with me, but I'm gonna keep a close eye on you. The second you even think about stepping out of line, I'll put you down.好吧，你可以跟我走，但我会注意你的。你只要敢越界，我就干掉你。}
#{342}{}{Sure, I suppose we could partner up. Welcome to the team, Dex.没问题，我认为我们可以组队。欢迎加入，德克斯}
#{343}{}{That was a damn good story, and you're not a bad actor, which makes you all the more dangerous. I think I'll do the wastelands a favor and remove you before you can do anymore harm.真他妈是个好故事，你演得很好，这让你看起来更危险了。我觉得我要在你为害废土之前先除掉你。}

{340}{}{所以，老兄，就这样如何？我们组队吧？和我在一起不仅会让你感觉更酷，我还非常擅长战斗。见鬼，我可以一个人单干，但是我不知道这个世界都会潜伏着些什么。我怀疑离开这里之后尿尿的第一棵树就想张开嘴咬掉我老二。}
{341}{}{好吧，你可以跟我走，但我会注意你的。你只要敢越界，我就干掉你。}
{342}{}{没问题，我认为我们可以组队。欢迎加入，德克斯}
{343}{}{真他妈是个好故事，你演得很好，这让你看起来更危险了。我认为还是在你成为废土下一只害虫之前先除掉你比较好。}



#dialogue added 12/28/08
#did not read bio
#{350}{}{[Dex's grin falters and his eyes become unfocused. After a moment, he begins speaking without meeting your eyes.] I was one of their sick experiments. They did... terrible things to me. [He shakes his head, then looks at you with a renewed grin.] I'd rather not talk about it, you know? The name's Dex, by the way.[德克斯笑容僵住了，眼睛失神。一会儿之后，他开始自言自语.]我曾经是他们该死实验的一员。他们对我...做了疯狂的事情。[他开始摇头，又再次笑着看着你]我不想说这件事。顺便一说，我叫德克斯。}
#{351}{}{Sorry to hear that, Dex. Anyway, that's all in the past now. The real, *real* distant past.抱歉，德克斯。无论如何，都已经过去了。在非常，非常，遥远的过去。}
#{352}{}{Look, Dex, I might be able to help you, but I'd like to know who I'm dealing with. What exactly did they do to you?看，德克斯，我可能可以帮你，但是我想先知道，我在和谁打交道。他们到底对你做了什么？}

{350}{}{[德克斯笑容僵住了，眼睛失神。一会儿之后，他开始自言自语。]我曾经是他们的实验品。他们对我...做了疯狂的事情。[他开始摇头，过了好一会，他对你微微一笑]我，我不想谈这件事，你知道吗？顺便说一下，我叫德克斯。}
{351}{}{抱歉，德克斯。无论你曾经经历过什么，这都已经过去了。而且已经过去很久很久了。}
{352}{}{德克斯，我可能会帮你，但是我想先知道，我在和谁打交道。他们到底对你做了什么？}


#{360}{}{[Dex takes another look around the room and whistles.] No kidding. This place has really gone to shit. How long did you say it's been?[德克斯又看了看房间，低声说]不开玩笑。这个地方已经成了一沱屎了。你说它有多久了？}

{360}{}{[德克斯又看了看房间，低声说]不开玩笑。这个地方烂得就和沱屎一样。你刚刚说已经过了很久了？}

#{370}{}{Alright, you really need to know? Fine. Basically, these crazy fucking doctors were doing some kind of tests on the "nature of human evil" or some crap. They injected me with the memories of a maniac in order to see how it would affect the personality of a decent, law abiding fella like me. At least, that's the best I could figure it.呃，你真想听？好吧。简单而言，他妈的疯狂医生在类似“人性本恶”一类的玩意儿上做了一些测试。他们给我注入了疯子的记忆，就想看看这玩意儿怎么影响一个正直的人的人性。}
#{371}{}{I see. So, how *did* it affect you? 嗯。那么，这玩意儿怎么“影响”你了？}
#{372}{}{I don't know, it gave me some nightmares, alright? Look, I've been frozen for who knows how long, and I'm not in the mood for a fucking interrogation. You're almost as bad as the Doc... Did you say he's dead? How long was I out for anyway? This place looks like shit.我不知道。他让我做了噩梦。你瞧，我被冻起来不知道有多久，我他妈也没心情被他妈的审问。你和医生一样坏...你说他死了？我被冻多久了？这个地方就像沱屎。}

{370}{}{呃，你真的想听？好吧。简单地说，这些他妈的疯狂医生在做一项关于“人性本恶”的测试或者一些类似的实验。他们给我灌输了一个疯子的记忆，目的是想知道这对一个像我这样正派、守法的人会有什么影响。至少，这是我能想到的他们对我做过最好的事了。}
{371}{}{我明白了。那么，这对你有什么影响呢？}
{372}{}{我不知道，灌注记忆之后，我做了好长一段时间的噩梦。你瞧，我被冻起来不知道有多久了，我也没心情接受他妈的审问。我觉得你就和医生一样坏...你说他死了？我被冻多久了？这个地方看起来糟透了。}



#good/neutral female intro
#{400}{}{[As you approach the cryogenic chamber, you see an attractive naked man sprawled on the floor. He draws his knees up and hugs them against his chest. He sits there for several moments, staring blankly ahead as his body quakes and his teeth chatter. Gradually, he seems to calm down.][你进入了冷冻室，你交到一具迷人裸男趴在地板上。他蜷缩着膝盖，把膝盖抱在胸前。他在那里坐了好一会儿，双眼无神，直视前方，身体和牙齿都在发抖。慢慢地，他冷静下来了。}
#{401}{}{Uh, hello?呃，嗨？}

{400}{}{[你打开了冷冻室，你看到一个长得很英俊的裸男趴在地板上。他蜷缩着膝盖，把膝盖抱在胸前。他在那里坐了好一会儿，双眼无神，直视前方，身体和牙齿都在发抖。慢慢地，他冷静下来了。}
{401}{}{呃，你还好吗？}



#{410}{}{[He snaps his head towards you and leaps to his feet. He watches you intently, then glances around like a cornered animal. When his eyes return to you, they soften, and he relaxes as his memories come flooding back to him. He quickly alters his composure, projecting cool confidence, despite his nakedness.] Hey doll, I know I'm quite the sight to behold, but it's a tad chilly in here. You mind if I get dressed?[他突然把头转向你，站起来。他专心地看着你，然后像一只在绝境里的动物一样环视四周。当他再次看向你，他的眼睛变得柔和了，他放松了，记忆潮水般涌了出来。他突然冷静了下来，释放出冷静的自信，即使还是裸着的。]嗨，美人，我知道我现在很好看，但是这里有点太冷了。你能让我穿上衣服吗？}
#{411}{}{I guess there's no harm-我觉得这没害处-}
#{412}{}{Well, I- 好吧，我-}

{410}{}{[他突然把头转向你，猛地站起来，仔细地观察着你，然后四处张望，就像一只被逼到角落的动物。他的眼睛转回到你身上，慢慢地他放松下来，他的记忆涌入了他的大脑。他突然变得冷静下来，他的表情变得非常自信，即使他还是赤身裸体着。]嗨，美人，我知道我现在很好看，但是这里有点太冷了。你能让我穿上衣服吗？}
{411}{}{我觉得这没害处-}
{412}{}{好吧，我-}


#{420}{}{Of course you don't mind. Thanks, babe. [He steps past you, gently slapping your rump, and opens a nearby locker. He casually dresses himself in a finely tailored suit, then pockets the locker's contents. Utilizing a pocket comb, he begins to sculpt and style his slicked dark hair with the quick precision of a seasoned pro.] I don't think I've seen you around, doll, and I doubt I'd forget a face like yours. Name's Dex, but I'm sure you know that. Mind if I ask yours?你当然不介意。谢了，美人。[他走过你，轻轻地拍了拍你的屁股，打开了最近的一个锁柜。他非常习惯地穿上一套修身的外套，然后把锁柜里的东西打包了。他用一把梳子，开始熟练而又快速地梳理他光滑的黑发。}
#{421}{}{I'm 我是 }
#{422}{}{. But you should know I've got a strict rule of not dating any strange men I unthaw. Since you've been on ice for the past century and a half, I'll assume your hand spasmed and accidentally slapped my ass. But if it happens again, I'll rip your cock off. Got it?但你应该知道，我对和我姐懂得陌生男人约会有一个严格的规则。既然你已经被冻了一个半世纪，我就假设你的手是因为痉挛而无意间摸我的屁股的。但是，如果再来一次，我就会切掉你的卵蛋。明白？}
#{423}{}{My name's 我叫做}
#{424}{}{. It's nice to meet you, Dex. I can't imagine what it must be like to wake up after being frozen for over a hundred and fifty years.认识你很不错，德克斯。我很难想象被冰冻了一般五十年后苏醒的感觉。}
#{425}{}{Yeah, I DO mind, you fucking creep. I only unthawed you so I could put you down like the sick dog you are.是的，我就是介意，你个他妈的怪胎。我解冻你只是因为可以像对一条死狗一样干趴下你。}
#{426}{}{Forget about names. How 'bout you take those clothes back off and show me what pre-war men are made of.不要管名字。你为什么不脱下这些衣服，让我看看战前的男人是怎么样的？}

{420}{}{你当然不会介意了，美人，谢了。[他走向你，轻轻地拍了拍你的屁股，然后打开了旁边的一个锁柜。然后非常习惯地穿起了一套精细裁剪的套装，接着他开始把锁箱里的东西也逐一放到身上。做完这一切之后，他拿出一把随身的梳子，然后开始用一种近乎苛刻的态度仔细地雕刻和装饰他的闪亮黑发。}
{421}{}{我是 }
{422}{}{。另外你应该知道，我对挑选男人有一套很严格的规则，而你很显然在这之外。但既然你已经被冻了一个半世纪，我就先假设你的手是因为痉挛而无意间碰到我的臀部。如果再来一次，我就会切掉你的卵蛋。明白？}
{423}{}{我的名字是 }
{424}{}{。认识你很不错，德克斯。我很难想象被冰冻了150年后苏醒的感觉。}
{425}{}{抱歉，我很介意。你这该死的混蛋，我解冻你只是为把你干得像死狗一样趴下来。}
{426}{}{名字？不要管这个了。你为什么不脱下这些衣服，让我看看战前的男人是怎么样的？}





#{430}{}{[Grins and begins to undress.] You're my kind of gal. Prepare yourself to experience Dex, the Duke of Sex.[笑着开始脱衣服]你是我喜欢的类型。开始准备体验性爱公爵德克斯吧}
#{431}{}{[Continue.][继续]}

{430}{}{[笑着开始脱衣服]你是我喜欢的类型。准备好体验“性爱公爵”德克斯吧。}
{431}{}{[继续]}



#{440}{}{[After an intense love making session on the floor of the chamber, the two of you collapse in exhaustion. Dex holds a small object near your mouth.] Scream for her, baby. [Just as you realize it's a severed human ear, you feel a blade pierce your chest. You scream as the blade is pulled out and plunged back in...][在房间地板上一场激烈的性爱之后，你们俩都累得精疲力尽。德克斯把一个小东西放在你嘴边。]尖叫吧，宝贝。[就在你意识到这是个这是一只掉下来的人耳时，你感觉到一把刀插进了你胸口。你激烈尖叫，刀拔出来又插了回去。}
#{441}{}{[End.][结束]}

{440}{}{[在房间地板上一场激烈的性爱之后，你们俩都累得精疲力尽。德克斯把一个小东西放在你嘴边。]尖叫吧，宝贝。[就在你意识到这是个这是一只人的耳朵时，你感觉到一把刀插进了你胸口。你激烈尖叫，刀拔出来又插了回去，不停重复。]}
{441}{}{[结束]}

#{450}{}{Whoa, whoa, whoa. Back up a second, sweetheart. Did you just say a hundred and fifty years? [He shakes his head in  disbelief.] That is un-fucking-believable. [He checks out his reflection.] But you gotta admit, I'm looking damn good for my age. [He grins at you, revealing a set of perfect teeth-a product of pre-war dentistry that looks strange to you in all  their pearly white symmetry.]嗷嗷嗷。退回几秒钟，甜心。你刚刚说150年？[他摇摇头，不相信]这他妈的不可能。[他检查了他的反映]但你必须承认，就我这个年纪来说，我他妈的长得真不赖。[他对着你笑，露出一口白牙——这种一口对称白牙的战前牙医科技对你来说很神奇。]}

{450}{}{喔喔喔，不要这么激动，甜心。你刚刚说150年？[他摇摇头，不相信]这他妈的不可能。[他对着镜子仔细看了一下自己]但你必须承认，就我这个年纪来说，我他妈的长得真不赖。[他对着你笑，露出一口白牙——这是战前牙科技术的产物，在你看来，它有着珍珠般的白色匀称，看上去很奇怪，对你来说和其它人完全不同。]}


#read the bio
#{451}{}{Sure, some girls might find you attractive, but I'm finding it hard to look past the fact that you're a cold-blooded murderous psycho.好吧，有些姑娘可能会认为你很不错，但我认为我不会忽视这个事实，你是个冷血的杀人疯子。}
#{452}{}{Yes, you're very attractive, but honestly, I'm a bit nervous to talk to you after what I read about you being a murderous psycho.是的，你很迷人，但说实话，我读了你的记录，你是个杀人疯子。和你说话我有点紧张，}
#{453}{}{Alright, this is sickening. Let's see how great you look after I put a couple holes in your face.好吧，这很恶心。我们来看看，我给你脸上加两个洞之后，你有多好看。}

{451}{}{好吧，有些姑娘可能会认为和坏小子约会很不错，但我认为我不会忽视这个事实，你是个冷血的杀人疯子。}
{452}{}{是的，你长得还不错。但说实话，我读了你的记录，你是个杀人疯子。和你说话时我会提醒自己这件事。}
{453}{}{好吧，这很恶心。我们来看看，我认为给你脸上加两个洞之后，你会好看得多。}



#did not read the bio
#{454}{}{Not bad for an ice man. Why were you frozen in there, anyway? 对个冰人来说并不赖。你为什么被冻起来了？}
#{455}{}{Eh, you're not my type. Anyway, why were you frozen in there?呃，你不是我的菜。另外，你为什么被冻起来了？}
#{456}{}{Alright, this is sickening. Let's see how great you look after I put a couple holes in your face.好吧，这很恶心。我们来看看，我给你脸上加两个洞之后，你有多好看}

{454}{}{以一根冰棍的标准来看，还不赖。你为什么被冻起来了？}
{455}{}{呃，你不是我的菜。另外，你为什么被冻起来了？}
{456}{}{好吧，这很恶心。我们来看看，我认为给你脸上加两个洞之后，你会好看得多。}



#{460}{}{OK, where are you getting this crap about me being a "murderous psycho"?好吧，你从哪里搞到这个说我是“杀人疯子”的狗屁玩意儿的？}
#{461}{}{Don't try to bullshit me. I read about you on that computer.别想忽悠我。我在那台电脑里读到过你。}
#{462}{}{That computer over there had some kind of bio on you, and it had some pretty terrible things in it.那台电脑有一些你的记录，记载了一些相当可怕的东西。}
#{463}{}{I can sense it. You give off this vibe.我能感觉得到。你散发出这种气氛。}
#{464}{}{Don't try to bullshit me. I know people like you.别想忽悠我。我知道你这种人。}

{460}{}{什么？你从哪里听说我是“杀人疯子”的这种狗屁玩意儿的？}
{461}{}{不要打算骗我，旁边的那台电脑里面写得很清楚。}
{462}{}{那台电脑有一些你的记录，记载了不少相当可怕的东西。}
{463}{}{我能感觉得到，你并不是什么好人。}
{464}{}{不要打算骗我，你并不是什么好人。}



#{470}{}{Ah, now it makes sense. Look, don't worry about that, it's not what you think. I'll explain everything in a second. But first of all, would you mind telling me what the hell's happened since they put me on ice? I mean, this place has gone to shit, and you look like you've walked out of some kind of sci-fi adventure tale.哈，现在说得过去了。瞧，别担心这件事儿。这和你想的不一样。给我几秒钟让我来解释。但是首先，你不介意告诉我，他们把我放到冰块里面之后到底发生了什么事情吧？我是说，这个地方就是一沱屎，而且你看起来就像从某些科幻冒险传说里出来的一样。}
#{471}{}{It's been over a hundred and fifty years since the great silence brought an end to the Old Ones... *your* people.自从大寂静给老一代人，*你”那一代人，画上句点之后，已经150年了。}

{470}{}{啊，现在说得通了。听着，别担心，这不是你想的那样。我马上解释，但首先，你能告诉我自从他们把我放在冰上后发生了什么吗？我是说，这个地方烂透了，你看起来就像科幻故事里走出来一样。}
{471}{}{自从“大寂静”给*你*那一代人画上句点之后，已经150年了。}

#{475}{}{Great Silence? The Old Ones? How about you spare me this cryptic bullshit and just tell me what happened?大寂静？老一代人？不如你给我解释一下这狗屁玩意儿再告诉我发生什么事情了？}
#{476}{}{The Great Silence is what my people call the end of your world. When the great fires rained down from the sky and scorched the land. You'll find the world is nothing like the one you knew. 大寂静就是我这一代人对你的世界的终结的称呼。业火从天而降，炙烤大地。你会发现，世界跟你所知的再无相同之处。}

{475}{}{大寂静？*我*那一代人？你别跟我胡扯了，告诉我发生了什么事。}
{476}{}{大寂静，直接点说就是属于你那个年代的世界已经终结了。当火焰像雨点一样从天而降之后，这个世界已经变了样了。}


#{480}{}{No shit, so they actually dropped the bombs, huh? I guess the vault project wasn't just a big waste of the tax-payers' money, after all.妈的，就是说他们真的丢炸弹了，嗯？我猜避难所计划最终还是一个浪费纳税人金钱的大垃圾。}
#{481}{}{Wait. You know of the holy vaults?等等，你知道神圣的避难所？}


{480}{}{妈的，他们真的丢了炸弹！？看来避难所项目最终并没有浪费纳税人的钱啊。}
{481}{}{等等，你知道神圣的避难所？}

#{490}{}{Know of them? Hell, I used to live right by the Chicago vault. I even watched 'em finish building the thing. Then of course they started doing those damn drills... [He stops and regards you with amusement.] You're really eating this up, aren't you, babe?知道？老天，我曾经住在芝加哥避难所边上。我甚至看着他们完成这玩意儿的修建。然后他们就开始挖这个...[他停下来，饶有兴致地看着你]你很在意这个，对吧，美女？}
#{491}{}{TELL ME MORE OF THE VAULTS! 告诉我更多的事情！}
#{492}{}{Well, you see, I've been chosen by my people to try and find a Vault. There, I hope to retrieve a G.E.C.K. and use its power to save my village from destruction. Anything you can tell me of the Vaults could help me in my quest.好吧，你知道，我被我的人民选来找到避难所。我希望从那里回收伊甸园创造器并用它的能量来避免我的村子毁灭。你告诉我的任何事情，对我的任务都很有用。}
#{493}{}{Well, you see, I had been chosen by my people to try and find a Vault. I risked my life on several occasions to find this Holy Vault and I finally was successful in finding it. I am curious what else you might know of these places.好吧，你知道，我被我的人民选来找到避难所。我冒着生命危险，最终发现这个神圣的避难所。我很好奇，关于这些地方你还知道些什么。} 
#{500}{}{I'll tell you what, babe. You need help finding these Vaults, and I need someone to show me the ropes, so to speak, in this crazy world of yours. So what do you say... partner?美人，我会告诉你的。你需要帮忙找到这些避难所，我也需要有人牵线搭桥。说吧，在你这个疯狂的世界里。所以，你觉得如何...伙伴？}
#{501}{}{I say you've got a deal... partner.我说，成交...伙伴。}
#{502}{}{Well, your knowledge of the old ones could prove quite useful to me... but, you know, there's that whole psychotic murderer thing...好，你对老东西的知识可能对我很有用...但是，你要知道，还有个疯狂杀手的事情...}
#{503}{}{I don't think I'm too eager to go gallivanting around the wasteland with a psychotic murderer. So you're on your own, "babe". Don't worry, I'm sure you'll be just fine. [snicker.]我认为我并不想和个疯狂杀手在废土上寻欢作乐。你靠你自己吧，“美人”。别担心，我认为你能行的。[讽刺]}

{490}{}{知道？老天，我曾经住在芝加哥避难所边上。我甚至看着他们完成那玩意儿的修建。然后他们当然开始做那些该死的训练...[他停下来，饶有兴致地看着你]你很在意这个，对吧，美女？}
{491}{}{告诉我更多的事情！}
{492}{}{好吧，我的人民选中我寻找一个避难所。我希望从那里回收伊甸园创造器，并用它拯救我的村子。你告诉我的任何关于避难所的事情，对我的任务都很有用。}
{493}{}{美人，我会告诉你的。你需要帮忙找到这些避难所，而在你这个疯狂的世界里，我也需要有个人牵线搭桥。所以，你觉得如何？“拍档”？}
{501}{}{成交...“拍档”。}
{502}{}{好，你对旧世界的知识可能对我很有用...但是，但我会留意关于那个“疯狂杀手”的事情...}
{503}{}{我认为我并不想和一个疯狂杀手在废土上寻欢作乐。你靠你自己吧，“美人”。别担心，我认为你能行的。[讽刺]}


#{510}{}{Hey, like I told you, I can explain. Everything you read about me was complete bullshit. Don't you buy a word of it.嗨，就像我告诉你的，我可以解释。你读到关于我的事情都是狗屎。一个字都不要信。}
#{511}{}{Hey, like I told you, I can explain. These evil vibes you are getting from me are the result of the scientists who experimented on me.嗨，就像我告诉你的，我可以解释。你从我身上感受到的邪恶气氛都是疯狂科学家对我做实验的结果}
#{512}{}{But that doesn't make any sense. What was done to you?这不能说明什么。他们对你做了什么？}
#{513}{}{Bullshit. I think it's time I shut you up for good.狗屎。我想我最好让你闭嘴。}
#{514}{}{But that doesn't make any sense, why would they lie about you?这不能说明什么。他们为什么要对你的事情撒谎？}
#{515}{}{The only bullshit around here is what's spewing out of your mouth and I think it's time I shut you up for good.这里唯一的狗屎就是从你嘴里喷出来的。我觉得现在最好让你闭嘴。}

{510}{}{嗨，就像我告诉你的，我可以解释。你在电脑上读到关于我的事情都是狗屎。一个字都不要信。}
{511}{}{嗨，就像我告诉你的，我可以解释。你从我身上感受到的邪恶气息都是那些疯子科学家对我做实验的结果。}
{512}{}{这不能说明什么。他们对你做了什么？}
{513}{}{混球，我想我最好让你闭嘴。}
{514}{}{这不能说明什么。他们为什么要对你的事情撒谎？}
{515}{}{这里唯一的狗屎就是从你嘴里喷出来的。我觉得现在最好让你闭嘴。}



#{520}{}{Hey, I know it doesn't seem to make a lot of sense, but have you looked around this place? There's not much sense to be made around here. Who knows what goes on in the fucked up minds of these scientists.嗨，我知道这说明不了什么，但你看过这个地方吗？这附近都是完全没有道理。谁知道这帮科学家里有什么狗屎？}
#{521}{}{Hmm... you've got a point there. I'm not saying I believe you... but I suppose I can at least hear you out.呃...你说到点子上了。我并不是说我相信你...但是我觉得至少可以听你说完。}
#{522}{}{Yeah, no kidding. Go on...好，不开玩笑。继续...}

{520}{}{嗨，我知道这说明不了什么，但你看看这个地方。这个地方有那一点是合乎道理的？天知道那帮科学家脑子装的是什么狗屎。}
{521}{}{呃...你说到点子上了。我并不是说我相信你...但是我觉得至少可以听你说完。}
{522}{}{好，不开玩笑。继续...}



#{530}{}{Alright, you see, it's all part of their "experiments". These crazy fucking doctors were doing some kind of tests on the "nature of human evil" or some crap. They were injecting me with the memories of a maniac, in order to see how it would effect the personality of a normal person. At least, that's the best I could figure it.好，你瞧，这全是他们“实验”的一部分。这些狗杂种医生在做一些诸如关于“人性本恶”的测试。他们给我注入了一个疯子的记忆，试图看看这怎么影响一个普通人的人性。至少，这是我做知道的。}
#{531}{}{Well... if that's true, then that's terrible. But what made them choose you as a test subject in the first place?嗯...如果是这样，那还真不好。但他们为什么要选你作为测试对象？}
#{532}{}{Awe, you poor thing. Well, that's all the in past now. Those terrible men are long dead and won't be able to hurt you anymore. Come along with me and we'll get out of this place.哈，你个可怜虫。好吧，这些都已经过去了。这些疯子早就死了，再也不能伤害你了。跟我走，我们出去。}

{530}{}{好，你看，这全是他们“实验”的一部分。这些狗杂种医生在做一些诸如关于“人性本恶”的测试。他们给我注入了一个疯子的记忆，试图看看这怎么影响一个普通人的人性。至少，这是我知道他们做过对我最乐观的事情了。}
{531}{}{嗯...如果是这样，那还真不好。但他们为什么要选你作为测试对象？}
{532}{}{哈，你这个可怜的家伙。好吧，这些都已经过去了。这些疯子早就死了，再也不能伤害你了。跟我走，我们出去。}



#{540}{}{Heh, you see that's the funny thing. *I* actually came to *them*. Answered an add they put out saying they'd pay big bucks for healthy test subjects. I needed the money, and, well, it turned out to be the worst mistake of my life. I can't even begin to tell you the horrors they subjected me to. [His eyes shimmer with tears as he reflects. He sighs deeply and wipes the tears away.] Anyway, thanks to you, 嗨，你看这是个搞笑事情。“我”就是为“他们”来的。他们的广告说，给健康的测试对象付一大笔钱，而且，正好是我这辈子最大的错误。我甚至无法告诉你他们对我所做的恐怖。[他的研究闪烁着泪花，他深叹一口气，擦掉眼泪。]无论如何，谢谢你。}
#{541}{}{, I'm finally free of that nightmare.我最终从噩梦中自由了。}
#{542}{}{Huh. Well, I'm glad I could help... I think.嗯，很高兴我能帮忙。}
#{543}{}{Actually, asshole, your nightmare's just begun, because I'm not buying a word of this.事实上，大屁眼，你的噩梦才刚刚开始，因为我一个字都不信。}

{540}{}{你看，现实总是这么讽刺，实际上是“我”主动找“他们”的。我打了他们登出来的广告电话，广告说他们会给健康的测试对象付一大笔钱。我很需要这笔钱。但很明显这是我这辈子最严重的错误，我甚至不能告诉你他们让我遭受的恐怖。[他眼角反射着泪光。他长叹一口气，抹去泪水]无论如何，谢谢你，宝贝。}
{541}{}{。我最终从噩梦中自由了。}
{542}{}{嗯，很高兴我能帮上忙...}
{543}{}{事实上，混球，你的噩梦才刚刚开始，因为我一个字都不信。}



#{550}{}{So how 'bout it, babe? Can we partner up? Not only do I bring my striking good looks to the table, but I can handle myself in a fight. Hell, I'd be alright with going solo, but I've got no clue what kind of crazy shit is lurking out there now. For all I know, the first tree I piss on could open up its mouth and bite my cock off.这怎么样，美人？我们能组队吗？不仅仅我闪亮发光的英俊外表，战斗力我也能照顾好自己。天哪，我单干其实更好，但我不知道外面有什么疯狂玩意儿。就我所知，我尿尿的第一棵树就张开嘴差点咬掉了我的蛋蛋。}
#{551}{}{Alright, you can travel with me, but I'm gonna keep a close eye on you. The second you even think about stepping out of line, I'll put you down. 好，你可以跟我走。我会紧盯着你的。一旦你想要越线，我就干掉你。}
#{552}{}{Sure, I suppose we could partner up. Welcome to the team, Dex.很好，我想你可以跟我组队。欢迎加入，德克斯。}
#{553}{}{That was a damn good story, and you're not a bad actor, which makes you all the more dangerous. I think I'll do the wastelands a favor and remove you before you can do anymore harm.这个故事不错，你也不是个差演员，这让我觉得更危险。我觉得我该给废土一个人情，现在就把你除掉，免得你造成更多伤害。}

{550}{}{你看我这个提议怎么样，美人？我们组队吧，我可不光只是英俊得发亮而以，战斗我也很擅长。天哪，我单干其实很不错的，但是我不知道这个世界都会潜伏着些什么。我怀疑我尿尿的第一棵树就想张开嘴咬掉我老二。}
{551}{}{好，你可以跟我走。我会紧盯着你的。一旦你想要越线，我就干掉你。}
{552}{}{很好，我想你可以跟我组队。欢迎加入，德克斯。}
{553}{}{这个故事不错，你也不是个差演员，这让我觉得更危险。我觉得我该给废土一个人情，现在就把你除掉，免得你造成更多伤害。}




#did not read the bio
#{554}{}{I say you've got a deal... partner. 我说，成交...伙伴。}
#{555}{}{Well, your knowledge of the old ones could prove quite useful to me... I suppose you've got a deal.好，你对老东西的只是可能对我很有用...我想，我们成交。}
#{556}{}{I don't really have the time to "show you the ropes". I'm sure you'll do just fine on your own, "babe".我没时间来给你“牵线搭桥”。我觉得你可以照顾好自己。} 

{554}{}{我想，好吧，成交...“拍档”。}
{555}{}{好，你对旧世界的信息可能对我很有用...我想，我们成交。}
{556}{}{我没有多余时间来“告诉你诀窍”，我觉得你可以照顾好自己。“甜心”} 


#dialogue added 12/28/08
#Non-evil female, did not read the bio
#{560}{}{[Dex's grin falters and his eyes become unfocused. After a moment, he begins speaking without meeting your eyes.] I was one of their sick experiments. They did... terrible things to me. [He shakes his head, then looks at you with a renewed grin.] Anyway, I'd much rather talk about you, babe.[德克斯笑得前仰后合，双目无神。一会儿之后，他开始说话，却不看着你。]我是他们恶心实验的一部分。他们...对我做了很坏的事情。[他摇着头，一会儿又笑着看着你。]无论如何，我更想谈谈你，美人}
#{561}{}{Oh, well, let's see... I was born and raised in the village of Arroyo. My mother is the village elder, and we're direct descendants of the legendary vault dwel—哦，嗯，我看看...在阿罗由，我生于斯长于斯。我母亲是村子长老，我们都是传奇的避难所遗民的直系后代。}
#{562}{}{Look, Dex, I might be able to help you, but I'd like to know who I'm dealing with. What exactly did they do to you?瞧，德克斯，我可能可以帮你。但我想先知道我在和谁打交道。他们到底对你做了什么？}

{560}{}{[德克斯露齿而笑，眼睛漫无目的地看着空气。过了一会儿之后，他开始说话，但眼睛却不看着你。]我是他们那些恶心实验的一部分，他们...对我做了很坏的事情。[他摇着头，过了好一会，又微笑看着你。]无论如何，我更想谈谈你，美人}
{561}{}{嗯，我出生在阿罗由，我的母亲是村子长老，我们都是传奇的避难所住民的直系后代。}
{562}{}{瞧，德克斯，我可能可以帮你。但我想先知道我在和谁打交道。他们到底对你做了什么？}


#{570}{}{Wow, that's real interesting, babe, and I can't wait to hear more about you. Honest. But first of all, how 'bout you fill me in on what the hell happened since they put me on ice. I mean, this place has gone to shit, and you look like you've walked out of some kind of sci-fi adventure tale.哇，这真有趣，宝贝，老实说我等不及听多一些你的事情了。但是首先，干嘛不先说说他们把我放到冰块里之后发生了什么？我是说，这个地方就是一沱屎，而且你看起来像是从某些科幻冒险传说中走出来的。}

{570}{}{哇，这真有趣，宝贝，老实说我等不及想多听一些你的事情了。但是首先，能说一下他们把我放到冰块里之后发生了什么吗？我是说，这个地方就是一沱屎，而你看起来像是从某些科幻故事中走出来一样。}



#{580}{}{Alright, you really need to know? Fine. Basically, these crazy fucking doctors were doing some kind of tests on the "nature of human evil" or some crap. They injected me with the memories of a maniac in order to see how it would affect the personality of a decent, law abiding fella like me. At least, that's the best I could figure it.好，你真想知道？好吧。基本上来说，这些该死的医生对我做了一些诸如“人性本恶”的测试。他们给我注入了一个疯子的记忆，试图看看他怎么影响一个遵纪守法好公民的人性。至少，我就知道这些。}
#{581}{}{I see. So, how *did* it affect you?我知道了。这到底“怎么”影响你？}
#{582}{}{I don't know, it gave me some nightmares, alright? Look honey, I've been through a lot and I'm not in the mood for a fucking interrogation right now. I answered your questions, now how 'bout you you fill me on what the hell happened since they put me on ice. I mean, this place has gone to shit, and you look like you've walked out of some kind of sci-fi adventure tale.我不知道。这让我做噩梦，知道么？宝贝，你看，我已经经历这么多，不想再他妈的被审问了。我回答了你的问题，现在说说他们把我放到冰块里之后发生了什么。我是说，这个地方就是一沱屎，而且你看起来像是从某些科幻冒险传说中走出来的。}

{580}{}{你真想知道？好吧。简单的说，这些该死的医生对我做了一些诸如“人性本恶”之类的测试。他们给我注入了一个疯子的记忆，试图看看他怎么影响一个遵纪守法好公民的人性。至少，我就知道这些。}
{581}{}{我知道了。这到底“怎么”影响你？}
{582}{}{我不知道。这让我做噩梦，知道么？宝贝，你看，我已经经历这么多，不想再他妈的被审问了。我回答了你的问题，现在说说他们把我放到冰块里之后发生了什么。我是说，这个地方就是一沱屎，而且你看起来像是从某些科幻冒险传说中走出来的。}



#evil male intro
#{600}{}{[As you approach the cryogenic chamber, you see an attractive naked man sprawled on the floor. He draws his knees up and hugs them against his chest. He sits there for several moments, staring blankly ahead as his body quakes and his teeth chatter. Gradually, he seems to calm down.][你进入了冷冻室，你交到一具迷人裸男趴在地板上。他蜷缩着膝盖，把膝盖抱在胸前。他在那里坐了好一会儿，双眼无神，直视前方，身体和牙齿都在发抖。慢慢地，他冷静下来了。]}
#{601}{}{Uh, hey...嗨...}

{600}{}{[你打开了冷冻仓，你看到一个迷人裸男趴在地板上。他蜷缩着膝盖，把膝盖抱在胸前。他在那里坐了好一会儿，双眼无神，直视前方，身体和牙齿都在发抖。慢慢地，他冷静下来了。]}
{601}{}{...你还能动吗...}


#{610}{}{[He snaps his head towards you and leaps to his feet. He watches you intently, then glances around like a cornered animal. When his eyes return to you, they soften, and he relaxes as his memories come flooding back to him. He quickly alters his composure, projecting cool confidence, despite his nakedness.] I don't recognize you, bud. You don't mind if I get dressed do you?他突然把头转向你，站起来。他专心地看着你，然后像一只在绝境里的动物一样环视四周。当他再次看向你，他的眼睛变得柔和了，他放松了，记忆潮水般涌了出来。他突然冷静了下来，释放出冷静的自信，即使还是裸着的。]嗨，老兄，我知道我现在很好看，但是这里有点太冷了。你能让我穿上衣服吗？}
#{611}{}{I guess there's no harm-我觉得无妨}
#{612}{}{Well, I-好的，我}

{610}{}{他突然把头转向你，站起来。他专心地看着你，然后像一只在绝境里的动物一样环视四周。当他再次看向你，他的眼睛变得柔和了，他放松了，记忆潮水般涌了出来。他突然冷静了下来，他的表情变得非常自信，即使他还是赤身裸体着的。]嗨，老兄，这里有点太冷了。你介意让我先穿上衣服吗？}
{611}{}{我觉得无妨-}
{612}{}{好的，我-}

#{620}{}{Of course you don't mind. Thanks, pal. [He steps past you and opens a nearby locker. He casually dresses himself in a finely tailored suit, then pockets the locker's contents. Utilizing a pocket comb, he begins to sculpt and style his slicked dark hair with the quick precision of a seasoned pro.] So, where's the doc? 当然你不介意。谢了，朋友。[他走到你后面打开了一个锁箱。他非常习惯地穿起了一套精细裁剪的套装，口袋里装入了锁箱里的东西。用一把随身的梳子，他开始用一种流行的款式，仔细地雕刻和装饰他的闪亮黑发]所以，医生在哪里？}
#{621}{}{Beats me. Wherever he is, he's long dead by now. You see, you've been doing that popsicle impression for a REAL long time.你难倒我了。不管他在哪里，他早就死了。你瞧，你当冰棍已经很久很久了。}
#{622}{}{Listen up, pretty boy. I didn't unthaw your psychotic ass so I could answer your questions and watch you groom yourself. I'm only letting you live long enough to tell me whatever useful information you might have. So start talking. The more you can tell me, the longer you get to live.听着，小靓仔。我给你解冻并不是要回答你问题看你打扮自己的。我让你活这么久，只想你告诉我你可能有用的信息。开始说说吧。你说得越多，我让你活得越久。}

{620}{}{谢谢你的不介意，朋友。[他走到你后面，打开了一个锁箱。他非常习惯地穿起了一套精细裁剪的套装，口袋里装入了锁箱里的东西。接着他拿出一把随身的梳子，开始用一种近乎苛刻的态度，仔细地雕刻和装饰他的闪亮黑发]所以，医生在哪里？}
{621}{}{你难倒我了。不管他在哪里，他早就死了。你瞧，你被冻在这里已经很久了。}
{622}{}{听着，崽子。我给你解冻并不是要回答你问题和看你打扮自己的。我让你活这么久，是要你告诉我可能有用的信息。开始说吧，你说得越多，我让你活得越久。}


#{630}{}{Is that so? [He regards you curiously.] You don't exactly look like you belong here, bud, yet you've decided to release me and I'd like to know why. I assume you know who I am?是么？[他好奇地看着你]你看起来完全不属于这里。但是，你决定释放我，我想知道为什么。我估计你知道我是谁吧？}
#{631}{}{Yeah, you're Dex, right? If what I read about you is true, then you're one evil son of a bitch. I like that.是的，你是德克斯，对吧？如果你的资料没错的话，你就是个他妈的邪恶的狗杂种。}
#{632}{}{Well, according to that computer, you're Dex, a narcissistic, sociopathic killer from before the great silence. I only unthawed you so I could put you down like the sick dog you are.嗯，那台电脑说，你是德克斯，一个自恋狂，大寂静之前的反社会杀手。我放你出来只为了能把你揍得像条死狗。}
#{633}{}{No idea, but you are giving off these evil vibes and I approve.不知道，但是我猜你很邪恶。}

{630}{}{是么？[他好奇地看着你]你看起来完全不属于这里。但是，你决定释放我，我想知道为什么。我估计你知道我是谁吧？}
{631}{}{是的，你叫德克斯，对吧？如果你的资料没错的话，你就是个他妈邪恶的反社会杂种。}
{632}{}{嗯，那台电脑上面写得很清楚，你叫德克斯，一个自恋狂，大寂静之前的反社会杀手。我放你出来只为了能把你揍得像条死狗。}
{633}{}{不知道，但是我不认为你是个好人。}


#{640}{}{[His cool demeanor vanishes and his eyes flare with rage.] You think you can intimidate ME? Do you have the first FUCKING CLUE who you're talking to? Come here and I'll show you what I'm capable of![他冷静的态度消失了，眼里闪过一丝怒火]你觉得你可以威胁我？你他妈知道你在跟谁说话？过来，我让你看看我是谁。}
#{641}{}{[Done.]结束} 
#{650}{}{[Dex grins at you, revealing a set of perfect teeth-a product of pre-war dentistry that look strange to you in all their pearly white symmetry.] I knew there was something I liked about you. You've got good taste. I don't suppose you're also a fan of The King?[德克斯咧着嘴笑着看着你。牙齿很好——战前高科技的产物。这种珍珠般发白的对称感让你很陌生。]我知道你有些东西我很喜欢。你的品味不错。我不认为你也是皇帝的爱好者吧？}
#{651}{}{Uh... [Blank stare.]呃...[目光无神]}
#{652}{}{Oh yeah, I love that... uh, what'd you call it, The King? Yeah, huge fan.是的，我喜欢那个...你说的那个...皇帝？没错，我是大粉丝！}

{640}{}{[他冷静的态度消失了，眼里闪过一丝怒火]你觉得你可以威胁我？你他妈知道你在跟谁说话？过来，我让你看看我是谁。}
{641}{}{[结束]} 
{650}{}{[德克斯咧开嘴笑着看着你，他的牙齿很好——这应该是战前高科技的产物。那种珍珠般发白的对称牙齿让你很陌生。]我知道你有些东西我很喜欢。你的品味不错。我不认为你也是皇帝的爱好者吧？}
{651}{}{呃...[目光无神]}
{652}{}{是的，我喜欢那个...你说的那个...皇帝？没错，我是大粉丝！}


#{660}{}{Nevermind, bud. [Dex takes another look around the room and whistles.] This place has really gone to shit. How long did you say it's been?别介意，兄弟。[德克斯又看了看周围，吹了声口哨]这个地方就是一沱屎。你说这有多久了？}
#{661}{}{It's been over a hundred and fifty years since the great silence brought an end to the Old Ones... *your* people.自从大寂静给老一代人，*你”那一代人，画上句点之后，已经150年了。}

{660}{}{别介意，兄弟。[德克斯又看了看周围，吹了声口哨]这个地方就是一沱屎。你说这有多久了？}
{661}{}{自从大寂静给*你*那一代人画上句点之后，已经150年了。}


#{665}{}{Great Silence? The Old Ones? How about you spare me this cryptic bullshit and just tell me what happened?}
#{666}{}{The Great Silence is what my people call the end of your world. When the great fires rained down from the sky and scorched the land. You'll find the world is nothing like the one you knew.}

{665}{}{大寂静？*我*那一代人？别和我讲这些让人听不懂的废话，告诉我发生了什么事。}
{666}{}{大寂静，没错，就是大寂静。我们把它称之为你们世界的尽头。当大火像雨点一样从天而降，把地面烤得焦酥发脆。你会发现外面的世界已经不像你所知道的那样了。}


#{670}{}{No shit, so they actually dropped the bombs, huh? I guess the vault project wasn't just a big waste of the tax-payers' money, after all.}
#{671}{}{Wait. You know of the vaults?} 
#{680}{}{Know of them? Hell, I killed my first hooker not far from where they were building the Chicago Vault. Those were the days... [He stops and regards you with amusement.] You're really eating this up, aren't you?}
{670}{}{不是吧，所以他们真的投了炸弹？我想避难所项目并不是在浪费纳税人的钱。}
{671}{}{你知道神圣的避难所？} 
{680}{}{知道？我可不仅仅是知道，我杀的第一个妓女就在他们建芝加哥避难所的不远处。那些日子...[他停下来狡黠地看着你]你需要这方面的信息，对吧？}




#{681}{}{TELL ME MORE OF THE VAULTS!}
#{682}{}{Well, I'm supposed to be trying to find a Vault for my tribe. Once I do, I'm expected to find a G.E.C.K. so we can use its power to save my dying village. Anything you can tell me about the Vaults could make my job a hell of a lot easier.}
#{683}{}{Well, you see, I had been chosen by my people to try and find a Vault. I risked my life on several occasions to find that damn Holy Vault and I finally was successful in finding it. I am curious what else you might know of these places.} 
#{690}{}{I'll tell you what, bud. You need help finding these Vaults, and I need someone to show me the ropes, so to speak, in this crazy world of yours. So what do you say... partner?}
#{691}{}{Hell, no need to try and convince me. I'd be happy to have you along just to see your handiwork first hand.}
#{692}{}{I don't know, Dex. Let's just say I let you come along with me, and we make it back to the remote safety of a settlement. Once there, how do I know you won't try and slit my throat the first chance you get?}

{681}{}{告诉我你知道的事情！}
{682}{}{我需要为我的部落找一个避难所。在里面我很可能可以找到伊甸园创造器，我需要用它的力量来拯救我垂死的村子。你告诉我的任何关于避所难的事情，都能让我的工作轻松很多。}
{683}{}{嗯，我被我的人民选中去寻找一个避难所。在冒了不少危险之后，我终于成功地找到了它。我很好奇你对这些地方还知道些什么。} 
{690}{}{我会把我知道的都告诉你的。这么说吧，你需要有人帮助你找到这些避难所，而我需要有人告诉我，怎么在这个疯狂的世界里活下去。那你觉得如何...“拍档”？}
{691}{}{见鬼，没必要试着说服我。我很高兴你能和我一起，让我看看你第一个作品。}
{692}{}{我不知道，德克斯。假设我让你和我一起走，我们也回到了安全的地方。但到了那里，我怎么知道你不会一有机会就试图割开我的喉咙？}



#{700}{}{I can tell you're no saint, so I could ask you the same thing. But to answer your question, I wouldn't kill you because that'd fuck me over. I'll be honest, }
#{701}{}{, I don't give a fuck about anyone, or anything, except for myself. If the world is as fucked up as you say it is, then sticking with you is the best shot I've got. It's as simple as that.}
#{702}{}{Fair enough. Let's go.}
#{703}{}{I'm just fucking with you Dex. I never actually had any intention of bringing you with me. I just thought I'd have a bit of fun with you before caving your skull in.} 
#evil female intro
#{800}{}{[As you approach the cryogenic chamber, you see an attractive naked man sprawled on the floor. He draws his knees up and hugs them against his chest. He sits there for several moments, staring blankly ahead as his body quakes and his teeth chatter. Gradually, he seems to calm down.]}
#{801}{}{Uh, hey...}


{700}{}{我看得出来，你也不是什么好人，所以我也可以问你同样的问题。现在我们回过头谈你刚刚的问题，我不会杀你，因为我并不把想事情搞砸。老实说, }
{701}{}{我不在乎任何人或任何事，除了我自己。如果这个世界像你说的那么糟糕，那么跟着你就是我最好的机会，就这么简单。}
{702}{}{很好，我们走吧。}
{703}{}{我只是在跟你开玩笑，德克斯。我从没想过带你一起走。我只是想在把你的头盖骨掀开之前和你玩一会儿。} 


#evil female intro
#{800}{}{[你打开了冷冻仓，你看到一个迷人裸男趴在地板上。他蜷缩着膝盖，把膝盖抱在胸前。他在那里坐了好一会儿，双眼无神，直视前方，身体和牙齿都在发抖。慢慢地，他冷静下来了。]}
#{801}{}{Uh, hey...}

{800}{}{[As you approach the cryogenic chamber, you see an attractive naked man sprawled on the floor. He draws his knees up and hugs them against his chest. He sits there for several moments, staring blankly ahead as his body quakes and his teeth chatter. Gradually, he seems to calm down.]}
{801}{}{呃，你还好吗...}


#{810}{}{[He snaps his head towards you and leaps to his feet. He watches you intently, then glances around like a cornered animal. When his eyes return to you, they soften, and he relaxes as his memories come flooding back to him. He quickly alters his composure, projecting cool confidence, despite his nakedness.] Hey doll, I know I'm quite the sight to behold, but it's a tad chilly in here. You mind if I get dressed?}
#{811}{}{I guess there's no harm-}
#{812}{}{Well, I-}

{810}{}{他突然把头转向你，站起来。他专心地看着你，然后像一只在绝境里的动物一样环视四周。当他再次看向你，他的眼睛变得柔和下来，记忆潮水般涌了出来。他突然冷静了下来，释放出冷静的自信，即使他还是赤裸着的。]嗨，美人，我知道我现在很好看，但是这里有点太冷了。你能让我穿上衣服吗？}
{811}{}{我觉得无妨-}
{812}{}{好的，我-}



#{820}{}{Of course you don't mind. Thanks, babe. [He steps past you, gently slapping your rump, and opens a nearby locker. He casually dresses himself in a finely tailored suit, then pockets the locker's contents. Utilizing a pocket comb, he begins to sculpt and style his slicked dark hair with the quick precision of a seasoned pro.] I don't think I've seen you around, doll, and I doubt I'd forget a face like yours. Name's, Dex, but I'm sure you know that. Mind if I ask yours?}
#{821}{}{I'm }
#{822}{}{. But you should know I've got a strict rule of not dating any strange men I unthaw. Since you've been on ice for the past century and a half, I'll assume your hand spasmed and accidentally slapped my ass. But if it happens again, I'll rip your cock off. Got it?}
#{823}{}{My name's }
#{824}{}{. It's nice to meet you, Dex. I can't imagine what it must be like to wake up after being frozen for over a hundred
and fifty years.}
#{825}{}{Yeah, I DO mind, you fucking creep. I only unthawed you so I could put you down like the sick dog you are.}
#{826}{}{Forget about names. How 'bout you take those clothes back off and show me what pre-war men are made of.}

{820}{}{谢谢你的不介意，美人。[他走过你，轻轻地拍了拍你的屁股，打开了最近的一个锁柜。他非常习惯地穿上一套修身的外套，然后把锁柜里的东西打包了。接着他用一把梳子，开始熟练而又快速地梳理他光滑的黑发。}
{821}{}{我的名字是 }
{822}{}{。另外你应该知道，我对挑选男人有一套很严格的规则，而你很显然在这之外。但既然你已经被冻了一个半世纪，我就先假设你的手是因为痉挛而无意间碰到我的臀部。如果再来一次，我就会切掉你的卵蛋。明白？}
{823}{}{我的名字是 }
{824}{}{。认识你很不错，德克斯。我很难想象被冰冻了150年后苏醒的感觉。}
{825}{}{抱歉，我很介意。你这该死的混蛋，我解冻你只是为把你干得像死狗一样趴下来。}
{826}{}{名字？不要管这个了。你为什么不脱下这些衣服，让我看看战前的男人是怎么样的？}




#{830}{}{[Grins and begins to undress.] You're my kind of gal. Prepare yourself to experience Dex, the Duke of Sex.}
#{831}{}{[After an intense love making session on the floor of the chamber, the two of you collapse in exhaustion. You notice Dex slyly going for a hidden knife. You quickly clutch his genitals.]}
#{832}{}{Touch that knife, and I'll turn you into the Dickless Duke. Besides, why ruin a good thing? The two of us could have so much fun together.}
#{833}{}{I... think I'm in love. [Dex has joined your party.]}


{830}{}{[笑着开始脱衣服] 你是我喜欢的类型，准备好见识一下“性爱公爵”德克斯了吗？}
{831}{}{[在房间的地板上进行了一场激烈的性爱后，你们两个精疲力竭地倒下了。你注意到德克斯狡猾地去找一把藏起来的刀。你很快抓住了他的老二。]}
{832}{}{如果你敢摸一下那把刀，我就让你变成一个没有老二的公爵。再说，为什么要毁掉一件好事呢？我们两个可以在一起玩得很开心。}
{833}{}{我...我想我恋爱了。 [德克斯加入了你的队伍。]}


#{840}{}{Whoa, whoa, whoa. Back up a second, sweetheart. Did you just say a hundred and fifty years? [He shakes his head in disbelief.] That is un-fucking-believable. [He checks out his reflection.] But you gotta admit, I'm looking damn good for my age. [He grins at you, revealing a set of perfect teeth-a product of pre-war dentistry that look strange to you in all their pearly white symmetry.]}
#{841}{}{Sure, some girls might think you're an attractive guy, but I'm sure they're a bit put off by that whole murderous psycho thing you've got going on.}
#{842}{}{Alright, this is sickening. Let's see how great you look after I put a couple holes in your face.}
#{843}{}{Sure, some girls might think you're an attractive guy, but I'm sure they're a bit put off by the murderous psycho vibes you're giving off.}

{840}{}{哇，哇，哇。等一下，甜心。你是说一百五十年前吗？他难以置信地摇了摇头。那真他妈的不可思议。[他看了看镜子里的自己]但你得承认，就我的年龄而言，我看起来棒极了。[他朝你咧嘴一笑，露出了一副完美的牙齿——应该是战前牙科的产品，在你看来，它有着珍珠般的匀称白色，看起来很奇怪。]}
{841}{}{当然，有些女孩可能会觉得你很有魅力，但我肯定她们很快会对你身上那种杀人不眨眼的精神状态感到恐惧。}
{842}{}{好吧，这真不错。让我在你脸上打几个洞，看看你看起来有多棒。}
{843}{}{当然，有些女孩可能会觉得你很有魅力，但我肯定她们会对你散发出来的残忍气息感到恐惧。}


#did not read the bio
#{844}{}{Not bad for an ice man. Why were you frozen in there, anyway?}
#{845}{}{Eh, you're not my type. Anyway, why were you frozen in there?}
#{846}{}{Alright, this is sickening. Let's see how great you look after I put a couple holes in your face.}

{844}{}{以一块冰鲜肉的标准来说还不错。你为什么被冻在里面？}
{845}{}{你不是我喜欢的类型。不管怎样，你为什么被困在里面？}
{846}{}{好吧，这真不错。让我在你脸上打几个洞，看看你有多棒。}


#{850}{}{Well they usually don't see that side of me until it's too late. But anyways... [Dex takes another look around the room and whistles.] This place has really gone to shit. So what have I missed out on?}
#{851}{}{It's been over a hundred and fifty years since the great silence brought an end to the Old Ones... *your* people.}

{850}{}{她们通常不会看到我的那一面，直到为时已晚。但无论如何...德克斯又环视了一下房间，吹起了口哨。这个地方看起来就像一沱屎，我错过了什么吗？}
{851}{}{自从“大寂静”结束了*你*那一代人之后，已经有150多年了。}



#{855}{}{Great Silence? The Old Ones? How about you spare me this cryptic bullshit and just tell me what happened?}
#{856}{}{The Great Silence is what my people call the end of your world. When the great fires rained down from the sky and scorched the land. You'll find the world is nothing like the one you knew.}


{855}{}{大寂静！？你别开玩笑了，到底发生了什么？}
{856}{}{大寂静就是你们所说的世界末日。天空下起了火焰雨，土地被烤得和曲奇饼一样酥脆，如果到了外面，你会发现这个世界与你所认识的完全不同。}


#{860}{}{No shit, so they actually dropped the bombs, huh? I guess the vault project wasn't just a big waste of the tax-payers' money, after all.}
#{861}{}{Wait. You know of the vaults?}

{860}{}{不是吧，所以他们真的投了炸弹？看来避难所项目并不是在浪费纳税人的钱了。}
{861}{}{你知道神圣的避难所？}


#{870}{}{Know of them? Hell, I killed my first hooker not far from where they were building the Chicago Vault. Those were the days... [He stops and regards you with amusement.] You're really eating this up, aren't you?}
#{871}{}{TELL ME MORE OF THE VAULTS!}
#{872}{}{Well, I'm supposed to be trying to find a Vault for my tribe. Once I do, I'm expected to find a G.E.C.K. so we can use its power to save my dying village. Anything you can tell me about the Vaults could make my job a hell of a lot  easier.}
#{873}{}{Well, you see, I had been chosen by my people to try and find a Vault. I risked my life on several occasions to find that damn Holy Vault and I finally was successful in finding it. I am curious what else you might know of these  places.} 
#{880}{}{I'll tell you what, babe. You need help finding these Vaults, and I need someone to show me the ropes, so to speak, in this crazy world of yours. So what do you say... partner?}
#{881}{}{Hell, no need to try and convince me. I'd be happy to have you along just to see your handiwork first hand.}
#{882}{}{I don't know, Dex. Let's just say I let you come along with me, and we make it back to the remote safety of a settlement. Once there, how do I know you won't try and slit my throat the first chance you get?}

{870}{}{知道？我可不仅仅是知道，我杀的第一个妓女就在他们建芝加哥避难所的不远处。那些日子...[他停下来狡黠地看着你]你需要这方面的信息，对吧？}
{871}{}{告诉我你知道的事情！}
{872}{}{我需要为我的部落找一个避难所。在里面我很可能可以找到伊甸园创造器，我需要用它的力量来拯救我垂死的村子。你告诉我的任何关于避所难的事情，都能让我的工作轻松很多。}
{873}{}{嗯，我被我的人民选中去寻找一个避难所。在冒了不少危险之后，我终于成功地找到了它。我很好奇你对这些地方还知道些什么。} 
{880}{}{这么说吧，你需要有人帮助你找到这些避难所，而我需要有人告诉我，在这个疯狂的世界里活下去的“诀窍”。那你觉得如何...“拍档”？}
{881}{}{见鬼，没必要试着说服我。我很高兴你能和我一起，让我看看你第一个作品。}
{882}{}{我不知道，德克斯。假设我让你和我一起走，我们也确实能回到了安全的地方。但到了那里，我怎么知道你不会一有机会就试图割开我的喉咙呢？}


#did not read bio
#{883}{}{I say you've got a deal... partner.}
#{884}{}{Well, your knowledge of the old ones could prove quite useful to me... I suppose you've got a deal.}
#{885}{}{I don't really have the time to "show you the ropes". I'm sure you'll do just fine on your own, "babe".}

{883}{}{我想这笔交易可以接受...“拍档”。}
{884}{}{嗯，你对旧世界的知识可能对我很有用...成交。}
{885}{}{我真的没有时间告诉你“诀窍”。我相信你自己会做得很好的。“宝贝”}


#{890}{}{I can tell you're no saint either, so I could ask you the same thing. But to answer your question, I wouldn't kill you because that'd fuck me over. I'll be honest, }
#{891}{}{, I don't give a fuck about anyone, or anything, except for myself. If the world is as fucked up as you say it is, then sticking with you is the best shot I've got. It's as simple as that.}
#{892}{}{Fair enough. Lets go.}
#{893}{}{I'm just fucking with you Dex. I never had any intention of bringing you with me. I just thought I'd have a bit of fun with you before caving your skull in.}

{890}{}{我看得出来，你也不是什么好人，所以我也可以问你同样的问题。我们回过头谈你刚刚的问题，我不会杀你，因为我并不把想事情搞砸。老实说，}
{891}{}{，我不在乎任何人或任何事，除了我自己。如果这个世界像你说的那么糟糕，那么跟着你就是我最好的机会。就这么简单。}
{892}{}{很好，我们走吧。}
{893}{}{我只是在跟你开玩笑，德克斯。我从没想过带你一起走。我只是想在把你的头打飞之前和你玩一会儿。}

#{900}{}{We'll get to that in a second. But first of all, how 'bout you fill me in on what the hell happened since they put me on ice. I mean, this place has gone to shit, and you look like you've walked out of some kind of sci-fi adventure tale.}

{900}{}{我会告诉你想要知道的，但现在能先说说他们把我放到冰块里之后发生了什么。我是说，这个地方就是一沱屎，而且你看起来像是从某些科幻冒险传说中走出来的。}





#in party

#male
#{1000}{}{What's the word?}
#{1001}{}{[Dex cocks an eyebrow at you.] Something up?}
#{1002}{}{Speak to me.}
#{1003}{}{[Dex smiles.] What's up, pal?}
#{1004}{}{You need something?}
#{1005}{}{What can Dex do for ya?}

{1000}{}{这叫啥来着？}
{1001}{}{[德克斯朝你眉毛一扬。] 有什么事情？}
{1002}{}{和我谈谈。}
{1003}{}{[德克斯笑着] 有什么事？“拍档”。}
{1004}{}{你需要什么？}
{1005}{}{德克斯能为你做什么？}

#female
#{1010}{}{What's the word?}
#{1011}{}{[Dex cocks an eyebrow at you.] Something up, babe?}
#{1012}{}{Speak to me baby.}
#{1013}{}{[Dex smiles.] What's up, doll?}
#{1014}{}{You need something? Anything? [Dex grins.]}
#{1015}{}{What can Dex do for ya baby?}

{1010}{}{这叫啥来着？}
{1011}{}{[德克斯朝你眉毛一扬] 有什么事情？宝贝。}
{1012}{}{和我谈谈，宝贝。}
{1013}{}{[德克斯笑着] 怎么了，宝贝？}
{1014}{}{你需要什么？ [德克斯猥琐的看着你。]}
{1015}{}{德克斯能为你做什么？宝贝。}


#waiting
#{1100}{}{We ready to roll?}
#{1101}{}{We takin' off, or what?}
#{1102}{}{You ready yet? I'm itchin' to move.}
#{1103}{}{So, you realized you're better off with me, huh?}
#{1104}{}{We going now? I'm not in the habit of waiting around for others.}
#{1105}{}{Come on. I was frozen for over a hundred and fifty years. I'm eager to move.}
#{1106}{}{I'm getting impatient over here.}


{1100}{}{准备好了吗？}
{1101}{}{我们能出发了吗，或者干点其它什么事情？}
{1102}{}{你准备好了吗？我实在等得不耐烦了。}
{1103}{}{你意识到和我在一起是更赞的选择了，是吧？}
{1104}{}{我们现在就出发吗？我没有等别人的习惯。}
{1105}{}{来吧，我被冻在鲱鱼罐头里一百五十年了，我很想搬家。}
{1106}{}{我有点不耐烦了。}

#party was initially full, waiting...
#{1110}{}{You ready to take me with you?}
#{1111}{}{Let's go.}
#{1112}{}{No, not yet.}

{1110}{}{准备好一起了吗？“拍档”。}
{1111}{}{走吧}
{1112}{}{下次吧。}


#questions...
#{1200}{}{So, what can you tell me about the Vaults?}
#{1201}{}{So, now do you remember anything you can tell me about the Vaults?}
#{1202}{}{Is there anything useful you can tell me about the time before the Great Silence?}

{1200}{}{那么，关于避难所你能告诉我什么？}
{1201}{}{那么，现在您还记得关于避难所的任何事情吗？}
{1202}{}{关于大寂静之前的事情，你能告诉我一些有用的信息吗？}


#{1210}{}{Well, lets see... Huh. You know what? My mind's still a little foggy about some things. You'll have to ask me later.}
#{1211}{}{Hmm. Alright.}

#{1220}{}{The vaults... the vaults... Nope, not yet.}
#{1221}{}{Hmm. Alright.}

#{1230}{}{Yes, actually, I remember... Wait, never mind, I forgot.}
#{1231}{}{Hmm. Alright.}

{1210}{}{嗯，让我想一想...嗯。你知道吗？看来冰冻对我有些后遗症，我对一些事情还有些糊涂。你以后再问我如何？}
{1211}{}{好吧。}

{1220}{}{避难所...避难所...没错，避难所，但目前我还没想到有关这方面的信息。}
{1221}{}{好吧。}

{1230}{}{没错，避难所，呃，等等...我刚刚想起来些什么了，我又忘了。}
{1231}{}{好吧。}




#{1240}{}{Well, I used to live by the Chicago Vault. Does that help?}
#{1241}{}{Do you know if it had a G.E.C.K.?}
#{1242}{}{I'm sure it did. I'm pretty sure they all did.}
#{1243}{}{Alright, now we're on to something. Can you tell me where this Vault is located?}
#{1244}{}{No problem. It's about 2,000 miles in that direction. [Dex points eastward.]}
#{1245}{}{Oh. Well then. Never mind.}


{1240}{}{嗯，好吧，我曾经住在芝加哥金库附近。这对你有帮助吗？}
{1241}{}{你知道它里面是否有一个伊甸园创造器吗？}
{1242}{}{我敢肯定它里面有这个。}
{1243}{}{太好了，让我们开始做点什么。你能告诉我这个避难所在哪里吗？}
{1244}{}{没问题。往那个方向大约2000英里。[德克斯指向东方]}
{1245}{}{哦。那么，好的，不要紧。}



#{1250}{}{There was one man, greater than any other, that we called, "The King". He was a handsome man with impeccable style, amazing hair, and a voice of gold. With a simple thrust of his pelvis he could impregnate every woman in sight. He was worshiped as a God by the people of the world. He was my father.}
#{1251}{}{Interesting...}

{1250}{}{曾经有一个男人，我们称为“国王”。他是一个英俊的男人，有着无可挑剔的风格，闪亮的头发和黄金般的嗓音。只要轻轻推一下骨盆，他就能使眼前的每个女人都怀孕。他被世人奉为神明。他是我的父亲。}
{1251}{}{这真有趣...}


#{1260}{}{There were immortals that lived secretly among us. They had to battle each other to the death with swords until only one remained to claim "The Prize".}
#{1261}{}{Wait. If they were immortal, how could they kill each other?}
#{1262}{}{They could only be killed by decapitation. When one immortal decapitated another, a quickening would be released, giving the slain immortal's powers to the victor.}
#{1263}{}{What exactly do you mean by "powers"?}
#{1264}{}{Uh, fighting powers? Mechanic powers? I don't know, it was kind of vague.}
#{1265}{}{Interesting...}

{1260}{}{有一些神灵在我们中间秘密地生活着。他们不得不用剑决斗至死，直到只剩下一个人来领奖。}
{1261}{}{等等。如果神是不死的，他们怎么能自相残杀呢？}
{1262}{}{他们只能被斩首处死。当一个不死之身砍下另一个神的头颅时，就会释放一个生命，把被杀死的不死之身的力量交给胜利者。}
{1263}{}{你说的“力量”是什么意思？}
{1264}{}{呃，战斗能力？机械能力？我不知道，这部分记忆有点模糊。}
{1265}{}{这真有趣...}


#{1270}{}{There were these giant lizards, some bigger than buildings, that people would ride around on. We called them dinosaurs, and they were known as man's best friend.}
#{1271}{}{Wow, did you have one?}
#{1272}{}{Of course. I rode a T-rex, the most badass giant lizard of them all. Only mine was even more badass because it had wings. Basically, it was a dragon.}
#{1273}{}{Interesting...}

{1270}{}{这里曾经有一些巨大的蜥蜴，有些比建筑物还大，人们可以骑着它们到处走。我们称它们为恐龙，它们被认为是人类最好的朋友。}
{1271}{}{哇，你有一只吗？}
{1272}{}{当然。我骑的是雷克萨斯霸王龙，恐龙中最凶猛的巨型蜥蜴。实际上我的恐龙是最厉害的，因为它有翅膀。基本上，它应该算是一条龙。}
{1273}{}{这真有趣...}



#{1280}{}{In the year 2011, The Awaking took place, and long dormant magical creatures, like Orcs, Elves, Trolls, and Dwarves returned to the world, along with magic. Magic and technology then clashed in a dark world of corporate warfare, waged in the shadows of the sprawling metropolises.}
#{1281}{}{Wow, what happened to the magical creatures?}
#{1282}{}{I guess they got taken out when the bombs fell. Except it looks like you've still got some Dwarves, Trolls, and Zombies around.}
#{1283}{}{Interesting...}

{1280}{}{在2011年，大觉醒发生了，很多休眠了很久的魔法生物，例如兽人，精灵，巨魔和矮人一起回到了世界。随后，魔法和技术在一个充斥着现代气息的黑暗世界中发生了冲突，这些战争是大都市的阴影中发生的。}
{1281}{}{哇，这些神奇的生物后来怎么了？}
{1282}{}{我猜他们在炸弹落下时被干掉的。当然我估计有些幸存者，你看，你的周围还有一些矮人、巨魔和僵尸。}
{1283}{}{这真有趣...}



#{1290}{}{There was this gigantic green lizard called Godzilla. Godzilla would alternate between terrorizing Japan, and saving its ass against giant space invaders. There was another violent gigantic lizard called the Tarrasque. I think they were cousins or something.}
#{1291}{}{Wow, what happened to them?}
#{1292}{}{Godzilla got taken out by Ferris Bueller. As for the Tarrasque, we had a giant robot battle him. The robot, piloted by yours truly, punched the Tarrasque so hard that be broke apart into thousands of little Tarrasques that scattered all over California.}
#{1293}{}{Interesting...}

{1290}{}{这里曾经有一种巨大的绿色蜥蜴，叫做哥斯拉。哥斯拉既要恐吓日本，又要保护自己的屁股不受太空入侵者的伤害。还有另一种凶猛的巨型蜥蜴，叫做塔拉斯克，我想他们是表亲吧。}
{1291}{}{哇，它们后来怎么了？}
{1292}{}{哥斯拉被奥特曼带走了。至于塔拉斯克，我们有一个巨大的机器人和他战斗。机器人，由和你一样真实的驾驶员驾驶，他猛烈地击打塔拉斯克，以至于它分裂成几万个分散在加利福尼亚各地的小塔拉斯克。}
{1293}{}{这真有趣...}


#{1300}{}{The earth was full of hot women, and I held the world record for the amount of sexual partners I had.}
#{1301}{}{I see. You know, Dex, some of these things you're telling me are a bit... out there. I get this strange feeling that it might not all be true.}
#{1302}{}{Hey, were YOU alive back then? No, you weren't. So who's the pre-war expert here? So trust me, it's all true. But hey, if you're not going to believe me, then I'm done telling you stories for now.}
#{1303}{}{Huh. That's too bad, because they've been so helpful so far.}

{1300}{}{地球上曾经到处都是热辣的女人，我一直保持着性伴侣数量的世界纪录。}
{1301}{}{我明白了。德克斯，你告诉我的一些事情有点...。我有一种奇怪的感觉，那就是这一切可能都不是真的。}
{1302}{}{嘿，你有活在那个时代吗？不，你并没有，对吧。那么谁是战前知识的专家呢？相信我，这都是真的。如果你不相信我的话，那我现在就不给你讲故事了。}
{1303}{}{嗯，那太糟糕了。我想到目前为止，你说的事情一直很有帮助。}


#distance
#{1400}{}{Just tell me where you want me.}
#{1401}{}{Just tell me where you want me, babe.}
#{1402}{}{No problem. I wouldn't want to make you nervous. [Dex grins.]}
#{1403}{}{Sure. If you think you need to keep an eye on me, I'm fine with that.}
#{1404}{}{Sure. I understand it's hard to concentrate when I'm too close. [Dex grins.]}
#{1405}{}{[Dex cocks his eyebrow at you and winks.]}
#{1406}{}{No problem.}

{1400}{}{告诉我，你要我去哪里。}
{1401}{}{告诉我，你要我去哪里，宝贝。}
{1402}{}{没问题。我不想让你太紧张。[德克斯笑着]}
{1403}{}{没错，如果你认为你需要关注我，我可以接受。}
{1404}{}{你确定？我担心当我离得太近的时候，你很难集中注意力。[德克斯笑着]}
{1405}{}{[德克斯翘起眉毛朝你眨眼。]}
{1406}{}{没问题。}


#put weapon away
#{1500}{}{Why? You don't trust me with weapons? [He laughs.] Sure thing, if it'll put your mind at ease.}

{1500}{}{为什么？你不相信我懂得拿武器？[他笑着说]实战示范？当然可以，只要你放心。}

#remove armor
#{1600}{}{Uh, sure. But just so we're on the same page here, you know I'm into chicks... right?}
#{1601}{}{All-right. [Dex strips off his armor and begins stripping off his clothes. He stops when he sees you glaring at him.] You're sending me mixed signals here, doll. Dex doesn't like to be toyed with. Just the armor it is.}

{1600}{}{嗯，当然。但我们一起站在这里，你知道我只喜欢妓女...对吧？}
{1601}{}{好的。[德克斯脱下他的盔甲，然后开始脱衣服。当他看到你怒视他时，他停下来] 你给我的信号很复杂，宝贝儿。德克斯不喜欢被人耍，看来你说的只是盔甲而已。}


#weapons you can use
#{1700}{}{Well, I can do wondrous things with knives. It's like an art. There's something very special about the way a blade slices into flesh, you know what I mean?}
#{1701}{}{Uh... yeah, sure. Anything else you can use? Feel free to be less creepy about it this time.}
#{1702}{}{Well, my Uncle was one of them military hard-asses. He trained me with pistols and SMGs, and I even got to toy around with some energy weapon prototypes they were working on. He thought I'd follow in his footsteps and be a puppet for Uncle Sam, but I, uh... Let's just say I went down a different path.}
#{1703}{}{That sounds alright. Anything else?}
#{1704}{}{I've been known to beat some ass with good 'ol fisticuffs. When I was a teen, I tried my hand at Karate for awhile, but they kept feeding me all this shit about being more disciplined, so I told 'em to fuck off. Anything else you need to know?}
#{1705}{}{That should cover it. Thanks.}

{1700}{}{嗯，我可以用刀子做很多奇妙的事情，就像一门艺术。你知道我的意思吗？}
{1701}{}{嗯...是的，当然。除了这个之外还有什么？这次不要再让人觉得毛骨悚然了。}
{1702}{}{我叔叔是一个硬汉军人。他用手枪和smg训练我，我甚至玩起了他们正在研发的能量武器原型。他以为我会追随他的脚步成为山姆大叔的傀儡，但我...假设我走了一条不同的道路。}
{1704}{}{大家都知道我打过几次架。当我还是个十几岁的孩子的时候，我试着练了一段时间空手道，但是他们一直在给我灌输要更有纪律性一类的东西，所以我告诉他们滚开。你还需要知道什么？}
{1705}{}{那就是我想要知道的，谢谢。}


#heal
#{1800}{}{I'm good to go.}
#{1801}{}{I've been better, but I can handle it.}
#{1802}{}{I'm not feeling very good.}
#{1803}{}{I think I hear the King calling. I can see the light...}

{1800}{}{我感觉还不错。}
{1801}{}{我觉得不太好，但我可以处理它。}
{1802}{}{我感觉不太好。}
{1803}{}{我想我听到国王在呼唤。我能看到光...}

#wait for me
#{1900}{}{No problem. But you're going to feel a lot less cool without me around. Just saying...}
#{1901}{}{Sure. I'll catch ya later.}
#{1902}{}{Sure, I'll wait. But if you don't come back, then I'm going to start looking for you, and it won't be pleasant when I find you.}
#{1903}{}{Alright, as long as you aren't just ditching me to make room for some other jerk. Because I promise you I'm better than them in every conceivable way.}
#{1904}{}{No problem.}
#{1905}{}{No problem, babe.}
#{1906}{}{Alright, as long as you aren't just ditching me to make room for some other jerk. Because I promise you I'm better than them in every conceivable way.}
#{1907}{}{Getting you too hot and bothered am I? I understand.}

{1900}{}{没问题。但如果没有我在身边，你会觉得不那么酷。当然，我只是说说...}
{1901}{}{好的，我待会儿再找你。}
{1902}{}{当然，我会等待的。但是如果你再不回来，我就要开始找你了，而且找你过程也会不太愉快。}
{1903}{}{好吧，只要你不是抛弃我为其他混蛋腾出名额。因为我向你保证，我在任何方面都比他们强。}
{1904}{}{没问题。}
{1905}{}{没问题，宝贝。}
{1906}{}{好吧，只要你不是抛弃我为其他混蛋腾出名额。因为我向你保证，我在任何方面都比他们强。}
{1907}{}{让你太热了是吗？我明白了。}



#gear
#{2000}{}{Alright, what about it?}
#{2001}{}{Look, I know I was on ice for a long time, but trust me, everything is in PERFECT working order. If you want, I'll prove it to you right here, right now. [Dex stops when he sees you glaring] Oh, I see, my *other* gear. What about it?} 

{2000}{}{好吧，关于它你有什么想说的？}
{2001}{}{听着，我知道我在冰块里呆了很长时间，但是相信我，我的一切都在完美的工作状态中。如果你愿意，我现在就给你证明。[德克斯看到你怒目而视，停住了]哦，我知道了，我的其他装备什么的呢？} 



#party full
#{2010}{}{It's a bit crowded. Let me know if things open up.}


{2010}{}{你的队伍太挤了，开除掉几个人再来找我吧。}

#ch <= 1
#{2020}{}{No way in hell I'm traveling with you. You're ugly as fuck.} 
#rejoined
#{2030}{}{Let's roll.}
#{2031}{}{About time we got goin' again.}

{2020}{}{没门，我不会和你一起旅行。你他妈的丑死了。} 
#rejoined
{2030}{}{让我们出发吧。}
{2031}{}{我们又该走了。}


#life story
#{3000}{}{So, what's your story?}
#{3001}{}{What, like my life story? Look, I know I'm pretty fascinating, but I don't want to stand around talking forever. My mouth will get all dry and there's not a whole lot of water to go around-it's just not a good situation to be in. But I suppose I could sum it up for you if you really want to know... Actually, I DO like to talk about myself so I'll leave up to you. You want the quick summary or the version with more detail?}
#{3002}{}{Just give me the quick summary.}
#{3003}{}{Lets hear the detailed version.}
#{3004}{}{Never mind, I lost interest.}

{3000}{}{告诉我一下关于你的事情？}
{3001}{}{什么，你想听我的生活故事？听着，我知道我很迷人，但我不想站在这里一直说一直说。那样我的嘴巴会变得很干，要知道这个世界里没有太多的纯净水。但如果你真的想知道的话，我可以为你总结一下...实际上，我很喜欢谈论我自己，所以您想要精简版本还是详细版本？}
{3002}{}{精简版。}
{3003}{}{详细版。}
{3004}{}{我想我还是先不要听了。}


#quick summary
#{3010}{}{Alright, basically, ever since I was a kid, I liked to kill things. I could talk about my childhood and my shitty parents and try to analyze why I like to do it, but I don't need an excuse. I do it simply because I can, and it's fun. By the time I was sixteen I spent my days as a popular high school heartthrob, and my nights as a ripper of Chicago's young working girls.}
#{3011}{}{Uh huh. Go on.}
#{3012}{}{Then one day I caught my girlfriend making the beast with two backs with another guy. I butchered them, set the place on fire, then high tailed it out of Chicago. Spent the next ten years traveling the nation, seducing girls, then cutting 'em up. Then they finally caught me, and my trail turned me into a celebrity.}
#{3013}{}{So, then what?}
#{3014}{}{So then one of my new fans, Alice, helps me escape. The two of us go on a three week cross country murder rampage before we finally go down in a shootout. Then, for some reason, The Man decides to stitch me back together and run all these tests on me. And that's how I wound up at the EPA where you found me.}
#{3015}{}{Thanks for the story.}

{3010}{}{好吧，基本上，从我小时候起，我就喜欢杀人。我可以谈论我的童年和我的糟糕的父母，并试图分析为什么我喜欢这样做。但我不需要一个借口。我这么做只是因为我能做到，而且很有趣。16岁的时候，我白天在高中时是一个受欢迎的万人迷，晚上我就变身成芝加哥年轻姑娘们的职业开膛手。}
{3011}{}{继续。}
{3012}{}{然后有一天我发现我的女朋友和另一个男人在一起了。我杀了他们，放火烧了那个地方。然后我离开了芝加哥，在接下来的十年里，我周游全国，勾引女孩，然后把她们切碎。然后，他们终于抓住了我，我的经历把我变成了一个名人。}
{3013}{}{所以，然后呢？}
{3014}{}{被抓到之后，我的一个新粉丝，爱丽丝，帮我逃走了。我们两个进行了为期三周的逃亡，我在枪战中被打中了，爱丽丝自杀。然后，出于某种原因，那些男人决定把我当成实验品，在我身上做所有这些测试。这就是你能在EPA找到我的原因。}
{3015}{}{谢谢你的故事。}


#detailed summary
#{3020}{}{Let's see... My Mom was a drug fiend and a whore, and my Dad was an ornery drunken bastard. Fortunately, my grandpa was alright for an old guy. Introduced me to The King's music. Unfortunately, he was claimed by the New Plague when I was seven. Then when I was ten, I watched from the closet as my Dad beat my Mom to death for forgetting to feed our dog, Captain Robeenie.}
#{3021}{}{This is off to a pleasant start. Go on.}
#{3022}{}{The bitch should've remembered to feed the Captain. Go on.}
#{3023}{}{So they put my Dad away and shipped me off to live with my Aunt and Uncle. You see, I was a little hell-raiser, even then, and my Uncle, being a military sort, thought he'd be able to straighten me out-turn me into a Red slaying soldier boy, just like the son he'd lost. He gave it his best shot, but I was a stubborn son-of-a-bitch.}
#{3024}{}{Uh huh. Go on.}
#{3025}{}{So anyway, we did a lot of moving around and it wasn't until I was in high school that we finally settled down in Chicago. That's when I took to sneaking out at night and knifing hookers. I'd been killing things for as long as I could remember, but gutting neighborhood critters didn't compare to the real deal, you know?}
#{3026}{}{Sure.}
#{3027}{}{So things were pretty sweet, for the most part. I mean, I fucking hated my Uncle and Aunt, but at school I was Mr. Popular. Every guy wanted to be my friend and every gal I looked at was willing to spread for me. Except for this one gal, Vicky. She actually took a bit of work. Amazing, I know, but eventually I got her to come around and become my girl.}
#{3028}{}{And all the while you were moonlighting as a serial killer?}
#{3029}{}{I don't really care about your high school sweetheart. Forget the story.}
#{3030}{}{Yeah. [Dex grins.] Those were the days. I was actually happy, you know? After we graduated, Vicky and I got our own little place together, and everything was aces. But that bitch had to go and ruin everything by sneaking around behind my back.}
#{3031}{}{How dare she.}
#{3032}{}{I caught her in the act, and I lost it. Things got real brutal. It was sloppy and there was no way I was going to be able to just cover it up. So I set the place on fire and hit the road. Did a lot of traveling, laid a lot of girls and left most of 'em dead. It wasn't a bad life, you know? It took 'em ten years, but the law finally caught up with me.}
#{3033}{}{Uh-oh. So then what?}
#{3034}{}{Then they put me on trial and it became a bit of media circus. The girls loved it because I'm a dreamboat, and everyone else loved it because it was a distraction from news about the New Plague and politics. So I thought I'd give 'em a real show.}
#{3035}{}{What'd you do?}
#{3036}{}{Well by then I'd made plenty of fans, but there was this one in particular, a real doll named Alice. She said she loved me and would do anything for me. So during my trail, she helped me make a break for it. It was a long shot, but we were lucky enough to pull it off. Then things got crazy... Are you sure you never heard about any of this?}
#{3037}{}{I'm sure, but go on.}
#{3038}{}{Never heard of it, and now I never want to. Just forget it, I'm bored.}
#{3039}{}{Well now that I was with Alice, it was kind of hard to revert back to my old ways of seducing women and slicing them open. Instead, we just starting thrill killing anyone that was convenient. It didn't matter how young or old, we were equal opportunity killers. But killing recklessly like that, we were easy to track. In three weeks they had us cornered. They gunned me down and Alice blew her own brains out.}
#{3040}{}{I see. Then what?}
#{3041}{}{So there I was, certain I was going to die, but then these G-Men stepped in and took me away. They got me back to a hundred percent, then started doing these tests on me, trying to figure out what makes me the way I am... Anyway, you can figure the rest, and my throats dry from talking. Damn, I was hoping to avoid that.}
#{3042}{}{Thanks for the story.}


{3020}{}{那就从一开始说吧...我的妈妈是一个瘾君子和妓女，我的爸爸是一个坏脾气的酒鬼私生子。幸运的是，我爷爷是一个很好的人，他把国王的音乐介绍给我。不幸的是，他在我七岁的时候被一场瘟疫夺去了生命。当我十岁的时候，我从壁橱里看到我爸爸打死了妈妈，因为我妈妈忘记喂我们的狗罗博船长。}
{3021}{}{这真不是一个愉快的开始，继续。}
{3022}{}{这只母狗应该记得喂船长才对，继续。}
{3023}{}{所以他们把我的父亲送走，让我和叔叔婶婶住在一起。你看，即使在当时我还是个小恶魔，我的叔叔，作为一个军人，仍然认为他能把我变回一个红色的士兵男孩，就像他失去的儿子一样。他尽了最大的努力，但我是个固执的混蛋，要知道我只是一个妓女的儿子啊。}
{3024}{}{继续。}
{3025}{}{总之，我们搬了很多次家，直到我上高中我们才最终在芝加哥定居下来。就在那时，我开始在晚上偷偷溜出去，用刀杀妓女。从我记事起，我就一直在杀东西，但是把附近动物的内脏挖出来和真正的杀人比起来，是完全不一样的，你知道吗？}
{3026}{}{没错。}
{3027}{}{所以大多数情况下，一切都很美好。我是说，我讨厌我的叔叔和阿姨，但在学校我是受欢迎的人。每一个男人都想成为我的朋友，我看到的每一个女孩都愿意为我播种。除了这个女孩，维姬。她实际上对我有所察觉，很神奇。但最终我让她改变了主意，让她成为了我的女朋友。}
{3028}{}{你一直都在做连环杀手的兼职吗？}
{3029}{}{我才不在乎你高中时的女朋友呢，跳过这部分的故事吧。}
{3030}{}{是的。[德克斯笑着]但那些日子，我真的很开心，你知道吗？毕业后，我和维姬有了自己的小房子，一切都是都向前好的方向发展。但那个贱人把一切都破坏了。}
{3031}{}{她后来怎么了。}
{3032}{}{我当场抓住了她，这让事情变得非常残酷，事发突然，要掩饰已经不可能。于是我放火烧了那个地方，然后上路了。我到了很多地方旅行，杀了很多女孩，生活还不错。但条子们花了十年的时间，法律最终还是追上了我。}
{3033}{}{哦，接下来的事情？}
{3034}{}{然后条子把我送上法庭，这就成了媒体的闹剧。女孩们喜欢这个故事，因为我是一个梦想家。政客也喜欢这个故事，因为它分散了人们对新的瘟疫和政治新闻的注意力，所以我想给他们一个真正的表演。}
{3035}{}{你干了什么？}
{3036}{}{那时候我已经有很多粉丝了，但是有一个特别的，一个真正的宝贝叫爱丽丝。她说她爱我，愿意为我做任何事。所以在我的旅程中，她帮我逃过一劫。这是一个不可能的机会，但是我们很幸运的成功了。你确定你从没听说过这些吗？}
{3037}{}{我确定，但请继续。}
{3038}{}{从来没听过，现在也不想听。算了吧，这个故事很无聊。}
{3039}{}{好吧，既然我和爱丽丝在一起了，就很难再回到我过去的勾引女人的生活了。相反，我们开始为了刺激杀死任何我们看上了的人。无论年轻还是年老，我们都是机会均等的杀手。但是这样鲁莽的杀戮让我们很容易被追踪。三周之内条子就把我们逼到了绝境。他们开枪打中了我，爱丽丝则朝自己脑袋开了一枪。}
{3040}{}{我明白了。然后呢？}
{3041}{}{所以我又被抓起来了，就在那里，我肯定自己会死，但是这些医生进来把我带走了。他们把我带到EPA，然后开始对我做这些测试，试图找出是什么让我变成现在这个样子...不管怎样，你可以想象剩下的，说了这么多，我喉咙都干了。妈的，其实我只是想离开那个鬼地方而以。}
{3042}{}{谢谢你的故事。}





#give bonus
#{3100}{}{Any tips you might be able to give me?}
#{3101}{}{Tips? What kind of tips?}
#{3102}{}{Well, I'm sure you've got some skill.}
#{3103}{}{Oh, I've got all *kinds* of skills. But if you're looking for advice... [He looks you over, then nods.] Alright, what the hell. I'll give you some pointers that'll have the ladies crawling at your feet. Now, the first thing you gotta do is...}
#{3104}{}{You wanna see my skills? I'll show you my skills anytime, sweetheart. But if you're looking for advice... [He looks you over, then nods.] Alright, what the hell. I'll give you some pointers that'll have the fellas eating out of your hands. Now, the first thing you gotta do is...}
#{3105}{}{There you go. Now don't be telling other people these trade secrets.}
#{3106}{}{Thanks.}


{3100}{}{有什么建议是要给我的吗？}
{3101}{}{建议？什么样的建议？}
{3102}{}{我相信你一定有些特别的技能。}
{3103}{}{哦，我有各种各样的技能。但如果你在寻求建议...他看了看你，然后点了点头。好吧，管他呢。我会给你一些建议，让女士们在你脚下爬行。现在，你要做的第一件事是...}
{3104}{}{你想看看我的技能吗？我会随时向你展示我的技能，甜心。但如果你在寻求建议...[他看了看你，然后点了点头。]好吧，管他呢。我会给你一些建议，让那些家伙们急不可耐的想要舔你的手。现在，你要做的第一件事是...}
{3105}{}{那就这样吧。现在不要告诉别人这些商业秘密。}
{3106}{}{感谢。}

#floats

#general
#{4000}{}{Man do I love the post-nuclear future.}
#{4001}{}{Come on. Let's have some violence.}
#{4002}{}{Let's find some more young ladies to, uh, admire.}
#{4003}{}{Let us seek more carnal knowledge.}
#{4004}{}{You ever just sprawl a girl out on a bed and cut her open? I tell ya, absolute beauty.}
#{4005}{}{I really need to cut something soon...}
#{4006}{}{You'd think a corpse would be terrible in bed, but you'd be surprised.}
#{4007}{}{[singing] I put an ax in my baby's head, I'm gonna end up doing time... she looked so good in red...[singing]}
#{4008}{}{[singing] 'caus I'm eviiillllll, my middle name is, miseerryyy...[singing]}
#{4009}{}{You dig my suit? This sweet baby was made in Grand Rapids, Michigan.}
#{4010}{}{So... where about the wasteland do you think they keep the hair gel?}
#{4011}{}{I know it sounds a bit gross, but don't knock deep fried ovaries 'til you've tried 'em.}
#{4012}{}{[Removes pocket comb and fixes hair.]}

{4000}{}{我爱这个核战后的时代。}
{4001}{}{来吧。让我们来点暴力吧。}
{4002}{}{让我们再找一些年轻女人吧。}
{4003}{}{让我们寻求更多的肉体知识。}
{4004}{}{你有试过把一个女孩的按倒在床上，然后把她剖开吗？我告诉你，绝对的美。}
{4005}{}{我真的需要尽快去割些东西…}
{4006}{}{你可能会认为躺在床上的尸体很可怕，但那只是你不懂欣赏。}
{4007}{}{[唱]我用斧子砍开了我的甜心的脑袋，我要记住这一个时刻...她倒在血里很好看...[唱]}
{4008}{}{[唱] 我就是这么邪恶...[唱]}
{4009}{}{你喜欢我的西装吗？}
{4010}{}{所以...你们觉得避难所科技公司在哪里？发胶在哪里？}
{4011}{}{我知道这听起来有点恶心，但在你尝试过油炸卵巢之前，千万别碰它。}
{4012}{}{[打开小梳子并打理头发。]}


#hurt
#{4020}{}{Hey! I'm fuckin' bleeding over here.}
#{4021}{}{Oh man, I'm not doing too well.}
#{4022}{}{Get me to a fucking doctor.}
#{4023}{}{You gonna just stand there and watch me bleed to death or are you going to do something about this?}

{4020}{}{嘿！我他妈的在流血。}
{4021}{}{哦，伙计，这可不太好。}
{4022}{}{给我找个该死的医生。}
{4023}{}{你就站在那里看着我流血而死？快做点什么啊！}

#radiated
#{4030}{}{I'm feeling a little weird over here...}
#{4031}{}{Hey, I'm feeling a bit radiated. If this isn't the kind that grants super powers, then I'm going to be pissed.}

{4030}{}{我觉得这里有点奇怪...}
{4031}{}{嘿，我感觉我受到辐射了。如果这不是能授予超能力的那种，那我就生气了。}



#give drug
#{4040}{}{You know, you're a bad influence.}
#{4041}{}{I try to stay away from this stuff. But if you insist...}
#{4042}{}{My body's a temple, but I guess this once won't hurt.}
#{4043}{}{If this does any permanent damage, I'm going to cut you.}

{4040}{}{你要知道，你是个坏例子。}
{4041}{}{我试图远离这个东西。但如果你坚持...}
{4042}{}{我的身体是一座神圣的庙宇，但我想就嗑一次的话不会有什么问题。}
{4043}{}{如果这造成任何永久性的伤害，我将把你切成一块块的。}



#give health drug
#{4045}{}{I feel much better now.}
#{4046}{}{Much better.}

#give health drug
{4045}{}{我现在感觉好多了。}
{4046}{}{这感觉不错。}


#push
#{4050}{}{Hey! Watch the hair.}
#{4051}{}{Hey, you don't rush perfection.}

{4050}{}{不要碰我的头发。}
{4051}{}{嘿，不要推，你不用这么急。}

#had sex
#{4060}{}{It just isn't the same when their blood's still warm, ya know?}
#{4061}{}{I hope you took notes.}
#{4062}{}{Girls have gotten pretty freaky since the end of the world... I dig that.}
#{4063}{}{...and thats why the babes used to call me "Dex, the Duke of Sex".}

{4060}{}{当她们的血还是热的时候就不一样了，你知道吗？}
{4061}{}{我希望你做了笔记。}
{4062}{}{自从世界末日之后，女孩们变得非常怪异...我操。}
{4063}{}{...这就是为什么甜心们叫我“性爱公爵”的原因。}


#poisoned
#{4070}{}{I feel nauseated. I think I'm poisoned.}
#{4071}{}{I feel like I'm gonna puke my guts out.}

#{4080}{}{I can't move this limb. I need medical attention.}
#{4081}{}{I think I lost feeling in this limb. Is that bad?}

#{4090}{}{It just got really blurry. Where'd everyone go?}
#{4091}{}{I think blood is coming out of my eyes.}


{4070}{}{我觉得恶心，我想我中毒了。}
{4071}{}{我觉得我要吐我的肠子了。}

{4080}{}{我的手不能动了，我需要医疗护理。}
{4081}{}{我的四肢失去了知觉，这很糟糕。}

{4090}{}{视线变得非常模糊，人们都哪去了？}
{4091}{}{我想血正在从我的眼睛里流出来。}



#sulik float
#{4100}{}{So, facial tattoos, huh? I guess if I was as ugly as bone-nose, here, I'd want to cover that up too.}
#{4101}{}{Yo, face-tats. You the cannibalistic sort? Maybe we could exchange recipes or something.}
#{4102}{}{I get the feeling your pal Sulik here doesn't dig me too much. You ever think about selling the guy off for some cash?}

{4100}{}{那么，面部纹身？我想如果我的鼻子长得像猪那么丑的话，我也会想把这件事掩盖起来。}
{4101}{}{哈，史力克，你的部落有吃人的习俗吗？你看，也许我们可以交换食谱之类的。}
{4102}{}{我感觉你的朋友史力克对我不怎么友善，你有没有想过卖掉那个家伙来换点钱？}


#vic float
#{4110}{}{Seriously, what's with the dumpy bald dude? You keeping him out of pity or something?}
#{4111}{}{So Vic, I hear you've got a spunky daughter. You should introduce me to her.}

{4110}{}{说真的，那个矮胖的秃头大叔是怎么回事？你是出于同情还是别的什么原因才帮他的？}
{4111}{}{那么伊克，我听说你有一个勇敢的女儿，你应该把我介绍给她。}


#Miria float
#{4120}{}{Miria, honey, we really need to spend some one-on-one time together.}
#{4121}{}{So I'm guessing we get to take turns with Miria, right?}
#{4122}{}{[Winks at Miria.]}
#{4123}{}{[Smiles at Miria.]}
#{4124}{}{Miria, you need a man who's in the same league as you. You know, one like me.}
#{4125}{}{[Brandishes knife at Miria. Grins.]}

{4120}{}{麦丽亚，亲爱的，我们真的需要在一起花一些时间做些一对一的运动。}
{4121}{}{所以我猜我们应该轮流使用麦丽亚，对吧？}
{4122}{}{[向麦丽亚眨眼。]}
{4123}{}{[向麦丽亚笑。]}
{4124}{}{麦丽亚，你需要一个和你一样漂亮的人，你知道的，就像我一样。}
{4125}{}{[在麦丽亚面前挥舞着刀，笑着。]}


#davin float
#{4130}{}{I say we put a hole in Davin's head and roll him into a ditch.}
#{4131}{}{Let's say, hypothetically, that Davin somehow gets his throat slit in his sleep tonight. No one's gonna care, right?}

{4130}{}{我说我们在达宾的头上打了个洞，把他滚进沟里。}
{4131}{}{假设地说，如果达宾今晚在睡梦中喉咙被切开了。没人会在意，对吧？}

#cassidy float
#{4140}{}{Hey Cassidy, you should really try some Psycho. I heard it can even re-grow hair.}
#{4141}{}{Why don't you hit that booze a little harder, Cassidy? It seems to have aged you so well.}
#{4142}{}{It's pathetic to see someone as old as Cassidy trying to hold on to life. If I were in his shoes, I'd kiss the barrel of a shotgun and just end it.}

{4140}{}{嘿，盖西迪，你真的应该试试心理医生。我听说她甚至可以让人重新长出头发。}
{4141}{}{盖西迪，你为什么不把酒喝得再猛一点呢？你看起来老得很好。}
{4142}{}{看到像盖西迪这样年纪的人试图抓住生命是可悲的。如果我站在他的立场上，我会亲吻枪管，然后结束它。}


#lenny float
#{4150}{}{Lets say we ditch the walking corpse.}
#{4151}{}{Alright, this whole joke about bringing Lenny along has gone on a little long now, don't you think?}
#{4152}{}{How the hell am I supposed to pick up the ladies with Lenny hanging around?}

{4150}{}{让我说，我们把那只僵尸埋了吧。}
{4151}{}{好吧，这个关于带廉尼一起旅行的玩笑已经开了很长时间了，你不觉得吗？}
{4152}{}{我怎么样才能在廉尼还在的时候去勾引那些女士呢？}

#marcus float
#{4160}{}{So, uh, Marcus, when do you revert back to the mild mannered physicist?}
#{4161}{}{Hey Marcus, don't you have some kind of town you're supposed to be running?}

{4160}{}{那么，马可世，你什么时候才能变回到温文尔雅的物理学家？}
{4161}{}{嘿，马可世，难道你没有什么你应该要去的城镇吗？}

#myron float
#{4170}{}{Hang in there Myron, I'm sure someday your balls will drop.}
#{4171}{}{The Dork-boy's kinda cramping my style.}
#{4172}{}{Myron's like one giant pimple, just waiting to be popped.}

{4170}{}{坚持下去，麦朗，我相信有一天你的蛋蛋会掉下来的。}
{4171}{}{那个傻小子有点影响到我的风格了。}
{4172}{}{麦朗就像一个大气球，等着被戳破。}


#goris float
#{4180}{}{At least Goris has the decency to cover himself.}
#{4181}{}{Good job blending in, Goris. You look just like a typical hunchbacked freak.}

{4180}{}{至少革力士有体面地掩饰自己。}
{4181}{}{干得很好，革力士，你很好地融入人群，你看起来就像一个典型的钟楼怪人。}


#town floats
#arroyo
#{4200}{}{I'm curious to see what these tribal women are like.}

{4200}{}{我真想知道这些部落女人的味道。}

#new reno
#{4210}{}{Whores... whores everywhere. I love this fucking place.}

{4210}{}{妓女...妓女无处不在。我爱死这个该死的地方了。}

#vault city
#{4220}{}{This place is just begging for some chaos.}

{4220}{}{这个地方只是在乞求混乱。}



#ncr
#{4230}{}{There's too many cops here. I say we bail.}

{4230}{}{这里的条子太多了，我可以说我是保释出来的吗？}

#broken hills
#{4240}{}{Great, more freaks. We better not stay here longer than we have to.}

{4240}{}{不错的地方，更多的怪胎。我们最好不要在这里待得太久。}

#gecko
#{4250}{}{We're wasting our time here. Zombie chicks aren't my thing. I generally don't like gals to look dead until AFTER I'm through with 'em.}

{4250}{}{我们不能在这里浪费时间。僵尸妓女不是我的菜，我不喜欢女人在我杀她们之前就好像已经死了一样。}

#modoc
#{4260}{}{Why the hell are we even wasting our time here? Seriously?}

{4260}{}{我们为什么还要在这里浪费时间？}

#modoc
#{4270}{}{I don't think I want to willingly spend any more of my time in this facility.}

{4270}{}{我不值得在这个设施里消磨时间。}

#Don't apply ERSI to specimen == horrible flaming death for specimen
#{5000}{}{[He snaps his head towards you and leaps to his feet. As he looks at you, his eyes suddenly get really wide and he starts gasping for air.}
#{5001}{}{[END]}
#{5002}{}{Holy shit!}

{5000}{}{[他把头转向你，站了起来。突然，他的瞳孔因为痛苦而放大，他急速的喘气，就像周围的空气消失了一样。}
{5001}{}{[结束]}
{5002}{}{操！}


