# Message file for epac7.ssl 
# Number of nodes: 11

#{100}{}{You see a Hologram.}
#{101}{}{You see the Director of Public Relations.}
#{102}{}{Hologram 40011. She is in charge of all the tours and press releases at the EPA.}

{100}{}{你看见一个全息图像。}
{101}{}{你看见公共关系主任。}
{102}{}{全息图像40011。她负责环境保护署的所有旅游和新闻发布。}



# Node  0  [Node001]
#{200}{}{[This attractive female hologram greets you with a friendly smile.] Hello visitor, and welcome to the EPA. How may I help you? Lunch will be served in the cafeteria at mid-day for all company employees.}
#{201}{}{What? Oh nevermind. Who are you?}
#{202}{}{I need to be going. Bye.}

{200}{}{[这个迷人的女性全息图像以友好的微笑向你问候]大家好，欢迎来到EPA，我能帮您什么忙？所有公司员工中午将在自助餐厅用餐。}
{201}{}{什么？哦，别介意。你是谁？}
{202}{}{我要走了，再见。}



# Node  1  [Node002]
#{210}{}{Me? I'm Hologram 40011, the Director of Public Relations. I organize trips, tours and other things and ensure that the place is running smoothly for the public on a day to day basis. The tour of the EPA museum will begin shortly. Please have your passes ready.}
#{211}{}{That sounds like a riveting job. Goodbye.}
#{212}{}{So maybe you could help me with something?}

{210}{}{我吗？我是全息图像40011，我是公共关系总监。我负责组织旅行和其他事情，并确保这个地方每天都在平稳地运行。EPA的参观将很快开始。请把你的通行证准备好。}
{211}{}{那听起来真是一个吸引人的工作，再见。}
{212}{}{也许你可以帮我个忙？}

# Node  2  [Node003]
#{220}{}{Of course. I'd love to help. How may I assist you? Tour pamphlets can be found in the main office and in letterboxes throughout the EPA.}
#{221}{}{There's some doors around the complex that I can't open without speaking a password. I'd really like to get through them and see more of your facility. I don't suppose you know the password?}

{220}{}{当然可以，我能为您做些什么？一般性的观光指南都可以在旅游小册子里找到，它们可以在主办公室的办公桌上或者EPA的信箱里找到。}
{221}{}{在这个复杂的地方有一些门，我没有密码就不能打开。我真的很想通过他们参观你们的设施，我想你不会不知道密码吧？}

# Node  3  [Node004]
#{230}{}{Of course I know the password, but unfortunately, I'm unable to share it with you. I understand your enthusiasm for wanting to experience all that this great facility has to offer, but there are rules we must follow for your own safety. Remember everyone, we offer guided tours of our complex at predetermined times.}
#{231}{}{Oh, you don't have to worry about my safety, I'm the Chosen One. Besides, when's the last time you had a *real* visitor? Do you really want to leave me disappointed?}
#{232}{}{Right then. Goodbye}

{230}{}{当然我知道密码的，但不幸的是我无法与你分享。我理解你的热情，你想要体验这个伟大的设施所提供的一切。但为了你的安全，有一些规则我们必须遵循。}
{231}{}{哦，你不用担心我的安全，我是获选者的。再说，你上次有个真正的访客是什么时候？你真的想让我失望吗？}
{232}{}{好吧，再见}



# Node  4  [Node005]
#{240}{}{Of course not. But, if I give you the password, then not only could I be endangering you, but I'd also be endangering the complex. Children, please do not taunt the holograms.}
#{241}{}{How could that endanger the complex? I hate to break it to you lady, but this complex has already gone to hell and back. There's nothing here but hazardous chemicals and broken robots. Honestly, I don't see how I could possibly make matters worse.}
#{242}{}{Oh forget it then.}

{240}{}{当然不是。但是，如果我给你密码，我不仅会威胁到你，而且会危及到你身边的人。另外，孩子们，请不要嘲笑全息图像。}
{241}{}{这怎么可能危及到复合体呢？我不愿意把它告诉你，女士，但是这个复杂的东西已经下地狱了。这里什么都没有，只有危险的化学物质和破碎的机器人。老实说，我不明白我怎么能让事情变得更糟。}
{242}{}{哦,那就算了。}


# Node  5  [Node006]
#{250}{}{I... I don't know. I'd be defying protocol. But... perhaps if you could assist me with something. Visitors, please note that the blue level is restricted for reasons that are very uninteresting. There's no need to be curious about it.}
#{251}{}{Sure, I could assist you. Just tell me what you need.}

{250}{}{我……我不知道。或许你是对的，我将藐视协议，但是……也许你能帮我个忙。游客们，请注意，蓝色的区域是受限制的，原因是这个区域非常无趣，没有必要对该区域感到好奇。}
{251}{}{当然，我可以帮你。告诉我你需要什么。}

# Node  6  [Node007]
#{260}{}{Ah yes, it looks much better in here now, thank you. The password is ABRE. Just speak clearly to the door and it
 will open. Now would everybody please...}
#{261}{}{YES, we've heard you already. Thanks for the code. Goodbye.}

{260}{}{啊，是的，现在这里看起来好多了，谢谢你。密码是ABRE。只要对着门说就可以了，门上面有语音识别系统，但记得发音要清晰。现在请大家……}
{261}{}{[打断]是的，我们已经听过了。谢谢你的密码，再见。}


# Node  7  [Node008]
#{270}{}{Hello again. What do you need? The EPA complex will be closed for the foreseeable future due to lack of staff.}
#{271}{}{Now that I have more time, could you tell me what you do here?}
#{272}{}{Nevermind.}

{270}{}{你好，由于缺乏工作人员，EPA将在可预见的未来永远关闭。你需要什么？}
{271}{}{你能告诉我这里是做什么的吗？}
{272}{}{没什么事。}



# Node  8  [Node009]
#{280}{}{Welcome back, visitor. There isn't a tour at the moment, but if you'd like to wait around for enough visitors to arrive, I'd be happy to arrange one.}
#{281}{}{I don't want to go on a tour, thanks. Goodbye.}
#{282}{}{I wonder if you could do something for me?}

{280}{}{欢迎你回来，访客。现在EPA没有观光计划，但是如果你带足够多的游客来，我很乐意安排一个。}
{281}{}{我目前不想去观光，谢谢拉。再见。}
{282}{}{你能帮我个忙吗？}

# Node  9  [Node010]
#{290}{}{Hello there. I'm a little busy at the moment designing a new tour program for the coming season. Could you come back later?}
#{291}{}{I would, but I'm in too much of a hurry. You see, I *really* need the password for those doors. Would you please give it to me?}

{290}{}{你好。我现在有点忙，为即将到来的季节设计一个新的观光项目，你能晚点再来吗？}
{291}{}{我会的，但是我太着急了。你看，我真的需要那些门的密码。你能把它给我吗？}

# Node  10  [Node011]
#{300}{}{Thanks again for your assistance, and please be responsible with the password I gave you. Remember, that's our little secret. Thank you for visiting the EPA, I hope you have a pleasant experience.}
#{301}{}{Thanks. Bye.}

#{302}{}{Come visit us again sometime.}
#{303}{}{Don't forget to visit the EPA souvenir stand.}

{300}{}{再次感谢您的帮助，请对我给您的密码负责。记住，这是我们的小秘密。感谢您访问EPA，希望您有愉快的经历。}
{301}{}{谢谢，再见。}

{302}{}{有时间再来看我们。}
{303}{}{别忘了参观EPA的纪念品摊位。}

#added in RP 1.3
#{310}{}{Do you think you could fix the lighting? It's improper for me to conduct tours through such a dimly lit complex.
 If you could brighten this place up for me, I'll give you the password. Please, remember to wash your hands thoroughly
 after visiting our petting zoo.}
#{311}{}{Alright. I'll see what I can do.}
#{312}{}{Nevermind. I'm not interested.}

#{320}{}{The complex is still looking rather drab. You're still going to fix the lights, aren't you? Remember visitors, all wavers must be signed before the end of the tour.}
#{321}{}{Don't worry. I'm working on it.}
#{322}{}{I'll get around to it.}

{310}{}{你是说你能修好灯对吗？对我来说，这么昏暗的灯光对在室内进行旅游是不合适的。如果你能帮我提亮这个地方，我就给你密码。另外如果你参观了我们的宠物动物园，请记得彻底洗手。}
{311}{}{好的，我会看看我能做些什么。}
{312}{}{我不感兴趣，再见。}

{320}{}{这个建筑看起来仍然很单调，你还是要把灯修好，记住访客，所有的人必须在旅行结束前登记。}
{321}{}{别担心。我正在努力。}
{322}{}{我去找它。}


#loop
#{330}{}{We'd have more visitors if the grounds were clean.}
#{331}{}{How am I supposed to conduct tours without proper lighting?}
#{332}{}{Those plants are killing all potential tourists.}
#{333}{}{All those broken down robots are *very* unsightly.}
#{334}{}{10031, you've been useless for decades.}
#{335}{}{All I'm saying, is that this place needs to be more presentable.}
#{336}{}{Destroying the complex is not the answer.}


{330}{}{我们会有更多的访客，如果这里足够干净。}
{331}{}{我怎么能在没有适当照明的情况下进行观光计划？}
{332}{}{这些植物正在杀死所有潜在的游客。}
{333}{}{那些解体了的机器人都"很"难看。}
{334}{}{10031，你已经没用了几十年了。}
{335}{}{我想说的是，这个地方需要更像样些。}
{336}{}{摧毁这个地方是不合适的。}
