#{100}{}{You see a horribly disfigured "human".}
#{101}{}{You see what appears to be an unfortunate human with grotesque animal features. It seems ravenous with hunger.}

#{200}{}{Urgh!}
#{201}{}{Hunggreee!}
#{202}{}{*snarl*}
#{203}{}{Grrr!}
#{204}{}{Want eats!}
#{205}{}{Kill! Feeeed!}
#{206}{}{*drool*}


{100}{}{你看到或许是"人"的生物。}
{101}{}{你看到一个人，但他的外表有着奇怪的动物特征，它似乎饿得要命。}

{200}{}{吼吼吼！！}
{201}{}{饿！饿！饿！}
{202}{}{*咆哮*}
{203}{}{咆哮！}
{204}{}{吃的，要吃的！}
{205}{}{杀！杀！}
{206}{}{*流口水*}