#{100}{}{You see a specimen from the Storage Tanks.}
#{101}{}{You see Kitsune.}
#{102}{}{Her eyes are different colors. One of them brown as malmbrick, the other bright green.}
#{103}{}{You see a slender, dark-haired woman who looks difficult to predict.}
#{104}{}{She has a soft face and entrancing eyes.}

{100}{}{你看见一个人像标本一样泡在休眠仓里。}
{101}{}{你看见灵狐。}
{102}{}{你看见灵狐，她的眼睛有着不同的颜色。其中一只是棕色，而另一只是亮绿色的。}
{103}{}{你看到一个苗条、黑头发的女人，她看起来神秘。}
{104}{}{她有一张线条柔和的脸，眼睛相当迷人。}

#{150}{}{It's not nice to stare.}

{150}{}{哪样盯着看是不好的。}

#{200}{}{Before you lies an open tank with icy cold water slowly being drained through a long, serpentine pipe. Inside, a woman, naked from head to toe, lies gasping and shivering. Looking around quickly, you snatch a bundle of loose clothing from a nearby locker and drape them over her for warmth.}
#{201}{}{Whoa. That had to be some trip. Are you alright?}
#{202}{}{Y-yes, the p-p-preservator r-restored my b-body t-t-temperature.}
#{203}{}{Not all of it, it looks like. }
#{204}{}{[You give it some time for her teeth to stop chattering. She recovers much quicker than you expect her to and looks up at you with sudden gravity.] Is…… it over?}

{200}{}{你看到一个敞开的水池，有一根长长的管子把冰冷的水慢慢排干。在里面，一个女人全身赤裸，躺在那里喘着粗气。你迅速地环顾了一下四周，从附近的储物柜里抽出一捆宽松的衣服，把它们披在她身上，好让她恢复体温。}
{201}{}{哇喔，那一定是一次旅行，你还好吧？}
{202}{}{[冷得打颤]是，是的，我，我，感到温暖一些了。[冷得打颤]}
{203}{}{看起来并不尽然。}
{204}{}{[你给她一些时间，好让她把体温恢复过来，看样子她恢复的速度比你想象的要快多了。突然她严肃地看着你]结……结束了？}

#{205}{}{Is what over? }
#{206}{}{You mean the War?}
#{207}{}{The War. All those nukes.}
#{208}{}{The War, yes.}
#{209}{}{That war ended long ago. Finished about as soon as it started.}
#{210}{}{[She brushes wet strands of hair from her eyes. You notice one eye is brown while the other is emerald green.] Who won?}
#{211}{}{No one.}

{205}{}{结束？你指的是什么？}
{206}{}{你是说战争？}
{207}{}{战争，核战争。}
{208}{}{是的，战争。}
{209}{}{那场战争很久以前就结束了。}
{210}{}{[她把遮着眼睛的湿头发拨开。你注意到她一只眼睛是棕色的，而另一只是翠绿色的。] 谁赢了？}
{211}{}{谁都没赢。}


#{212}{}{[She looks at you blankly. She's very easy on the eyes, especially for someone who was just thawed out of a block of ice.]}
#{213}{}{When 90% of the world is scorched to a crispy brown, I'd say it's hard to declare a clear winner. I mean, there wasn't much left worth winning.}
#{214}{}{What…… what date is it? What year? Is it still 2077?}
#{215}{}{Hell, no. [You show her the date on your Pip Boy's calendar.]}
#{216}{}{[She stares at the flickering screen, frozen in time like she never left the tank.]}

{212}{}{[她茫然地看着你。她的眼睛很好看，尤其是对一个刚从冰块里融化的人来说。]}
{213}{}{当世界上90%的人被烤得象曲奇饼一样脆的时候，我想说一个明确谁是*赢家*是件很难的事。我的意思是，也没什么值得赢的东西了。}
{214}{}{什么……现在是什么日期？哪年？还是2077年？}
{215}{}{抱歉，并不是。[你把PIPBoy上的日历上给她看。]}
{216}{}{[她盯着PIPBoy闪烁的屏幕，你看不到她的表情，但她就像一台被冻住的坦克那样一动不动。]}

#{217}{}{Are you alright?}
#{218}{}{My God. I don't believe it. I was in that thing for over a century?!}
#{219}{}{Seems like it. Hey, listen, don't look at me like that. I had nothing to do with putting you in there. Hell, my grandpa wasn't even alive back then. I just stumbled upon the location of this place and decided to check it out.}
#{220}{}{Well, will you help me up, or would like it better if I continued sitting naked at your feet?}

{217}{}{你还好吧？}
{218}{}{我的天。我……我在那个东西里呆了一个多世纪！？}
{219}{}{似乎是这样的。呃，别那样看着我。我和把你放进这个冰箱里的人毫无关系。甚至你在被冻起来的时候，我爷爷还活着。见鬼，听着，我只是偶然发现了这个地方，然后我决定进来看看。}
{220}{}{嗯，你能扶我起来吗？还是说我继续光着身子坐在你的脚边，你会更喜欢？}

#{221}{}{I was just about to. [You help her to her feet.]}
#{222}{}{Why did you wake me?}
#{223}{}{No particular reason.}
#{224}{}{I have this terrible habit of touching everything I encounter. One thing led to another.}
#{225}{}{You say you don't even work in this place?}
#{226}{}{That's what I said.}

{221}{}{我正想这样做。[你把她拉起来。]}
{222}{}{为什么你要唤醒我？}
{223}{}{没有特殊的原因，完全没有。}
{224}{}{那只是一个习惯，可怕的习惯。我喜欢翻找我能碰到的每一个地方，然后刚好我翻到这里来了。一件事导致另一件事发生，就象拉着拉链头那样。}
{225}{}{你是说，你并不是在这里工作的？}
{226}{}{哪就是我想说的。}

#{227}{}{Then if you hadn't come along, I would've been stuck in that thing even longer. Maybe forever. [She pulls one of the shirts you wrapped her in over her head.] What's it like now, the world out there? You said 90% of it was destroyed?}
#{228}{}{My world is a wasteland where every day is a struggle for survival. Most people have taken shelter in the ruined remains of the old ones. Others, like my tribe, attempt to forge a simple existence in the harsh wilderness. Truth told, it could be centuries before it even comes close to recovering.}
#{229}{}{It can't possibly be as bad as it sounds. [She doesn't sound like she's convinced of one word she just said.]}

{227}{}{如果你没有来，我可能会被困在那个东西里更久，也许是永远。[她把你裹在她头上的一件衬衫拨了下来。] 现在的世界是什么样子的？你说外面90%都毁了？}
{228}{}{现在的世界，呵，我的世界是一片荒芜，人们每天都在为生存而挣扎。大多数人都在旧世界的废墟中避难。而其他人，像我的部落，则试图在荒芜中建立一个简单的地方。我的眼睛告诉我，世界可能在需要数个世纪后才会恢复过来。}
{229}{}{这不可能，不可能像听起来那么糟糕。[她听起来不像她说的一个词。]}



#{230}{}{It's nothing like America in 2077, that's for sure.}
#{231}{}{[She pulls a pair of pants on.] So, what now?}
#{232}{}{We never did properly introduce ourselves. My name's }
#{233}{}{. What's yours?}
#{2330}{}{How 'bout you tell me your name? I'm }
#{234}{}{You can call me Kitsune.}

{230}{}{它与美国在2077年的样子完全不同，这是肯定的。}
{231}{}{[她拉了一条裤子盖在腿上。] 所以,现在该做什么？}
{232}{}{我们还没有正式介绍过我们自己。我的名字叫 }
{233}{}{。你的名字是？}
{2330}{}{告诉我你的名字好吗，我的名字是 }
{234}{}{你可以叫我灵狐。}


#{235}{}{Kitsune, what were you doing cryoed away in that tank?}
#{236}{}{I don't know for sure. They knew the War was about to happen, so they put me in a preservator like the others.}
#{237}{}{Do you have any clue what this place is?}
#{238}{}{From what I know, it's a branch of the United States Environmental Protection Agency. I was in Arizona when the War happened. I was taken here immediately.}
#{239}{}{You must have been pretty important for them to want to preserve you. Were you a Chosen One, like me?}

{235}{}{灵狐，为什么你会在那个罐子里的？}
{236}{}{我不清楚。他们知道战争就要发生了，所以他们把我在像其他人一样放在那里面。}
{237}{}{你知道这个地方的信息吗？}
{238}{}{据我所知，它是美国环境保护署的一个分支机构。战争发生时我在亚利桑那。然后我被带到这里来了。}
{239}{}{我想你一定对他们很重要，所以他们要保护你。你像我一样是被选中的吗？}


#{240}{}{Uh, not exactly. I was a homemaker, married to a councilman. Before that I wrote for several different news publications. It wasn't what you'd call a terribly exciting life.}
#{241}{}{What happened to him, your husband?}
#{242}{}{I don't know. Probably one of the billions of casualties. I doubt any of my family made it through the war. My God, even if they did, it's been so long…… everyone I ever knew is dead. [She bites her lip and her eyes start to shimmer with tears, but she quickly wipes them away and sighs, bringing herself under control.]}

{240}{}{嗯，我想不是这样。我只是一个家庭主妇，我的丈夫一个议员。在此之前，我为几家不同的新闻刊撰稿。这不是你所说的令人兴奋的生活。}
{241}{}{你的丈夫怎么了？}
{242}{}{我不知道，可能有几十亿人伤亡。我怀疑我的家人没有熬过战争。我的上帝，即使他们活下了，那也已经是很久之前的事了了……我认识的人都死了[她咬着嘴唇，眼泪开始闪烁，但她很快就把它们擦干净，叹了口气，控制住了自己。]}


#dialogue added 12/31/08
#{245}{}{Well, since you're giving me a choice…… [smirk]}
#{246}{}{[She glares at you wordlessly.]}
#{247}{}{Oh, I mean, of course I'll help you up. [You help her to her feet.]}


{245}{}{嗯，看来你给了我一个选择……[笑]}
{246}{}{[她对你怒目而视。]}
{247}{}{哦，我的意思是，我当然会帮你。[你扶她站起来。]}


#join me
#{250}{}{What are you going to do now?}
#{251}{}{I don't know. What do you do when you've been hibernating for over a century? Even bears don't sleep that long. The world out there isn't the world I knew. I don't know if I could stand to see what it's turned into.}
#{252}{}{I know it's a wasteland out there, but you've still got a whole life to live. You're wasting it down here. Come with me and maybe we can make something of it.}
#{253}{}{It doesn't look like you've got much of a choice. You can either sit down here and rot, or you could come with me. It's up to you.}

{250}{}{你现在有什么打算？}
{251}{}{我不清楚，如果你睡了一个多世纪的觉，你会怎么做？甚至熊也不会睡那么久好吗，外面的世界并不是我所熟悉的世界。我不知道我是否能看到它变成了什么样。}
{252}{}{据我所知，外面是一片荒芜，但你生命还有很久。别把它浪费在这里了。跟我来，也许我们能做点什么。}
{253}{}{事实上，你的选择我觉得并不多，你可以坐在这里腐烂，或者你可以和我一起出去，取决于你。}



#join success
#{260}{}{You know, you're right. I could go back to being frozen and sleep it off for another hundred years, but that would be the cheap way out. I need to see for myself what the world's become, and play a part in putting it back together.}
#{261}{}{Come on then. Let's go grab a brahmin steak first thing.}
#{262}{}{Don't make me regret this.}

{260}{}{我想你是对的。我可以到休眠仓里再躺上一百年，但这个做法糟透了。我需要亲眼看看这个世界变成什么样子，并在把它重新组合起来的过程中扮演一个角色。}
{261}{}{来吧，我们去吃双头牛排吧。}
{262}{}{希望这不会让我后悔。}


#join failure
#{270}{}{Forget it. It's been this way for over a hundred years. What makes you think we're going to fix it now?}
#{271}{}{I'll come back. Maybe you'll change your mind.}
#{272}{}{Maybe. But don't count on that happening. I should just go back to sleep for another century or so.}

{270}{}{忘掉它吧，这种方式已经有上百年的历史了。是什么让你认为我们现在要解决这个问题？}
{271}{}{我会回来的，也许那个时候你会改变主意。}
{272}{}{也许你是对，但别指望会发生这种事。我会回到休眠仓再睡个一百年。}



#2nd chance at join failure
#{280}{}{What if these machines stopped functioning though? You'd be dead and you'd never know whether the world that blew itself up ever put itself back together.}
#{281}{}{Then I'll watch what happens to it from wherever I am.}
#{282}{}{How do you know for sure you're gonna be taken someplace special after you sleep the big sleep? I come from a tribe that believes in the afterlife and prophecies, but from a pragmatic standpoint we're all just a bunch of organic machines that think and talk and feel because of flesh and chemical components. What if there's nothing after you die -- we shut down like computers -- and this is all you've got?}
#{283}{}{I'd rather take my chances in cryogenic suspension than wander that wasteland.}
#{284}{}{Oh yeah? You don't seem all that sure anymore.}
#{285}{}{[Kitsune ponders your words for a good long while. Finally, she lines her eyes with yours.] I can't pretend you don't have a point. Maybe…… maybe I will take my chances with you.}
#{286}{}{Let's get out of here, then. It's time we left this dump behind.}


{280}{}{如果这些机器停止运作，该怎么办？你已经死过一次了，如果再死一次，你永远不知道这个世界会不会把自己放回去。}
{281}{}{然后我会观察它从哪里发生。}
{282}{}{你怎么知道你在睡大觉后会被带到一个特别的地方？我来自一个相信来世和预言的部落，但从实用主义的角度来看，我们都只是一群有机机器，它们会思考、说话、感觉，因为它们有肉和化学成分。如果你死了，那就什么都没有了，就像电脑关机一样，这就是你想拥有的一切吗？}
{283}{}{我宁愿在休眠仓里碰运气，也不愿意在荒野上徘徊。}
{284}{}{哦？但你看起来可不是那么坚决的哦。}
{285}{}{[灵狐花了好长时间思考你的话语。最后，她的眼睛看着你。]我不能说你没有道理。也许……也许我应该和你碰碰运气。}
{286}{}{让我们离开这里吧，我们该把这堆垃圾抛在后面了。}






#NPC doesn't join and leaves for good
#{287}{}{Actually, I think I'm going to strike out on my own. I've always been the independent type, so it shouldn't be any skin off my back. A lot has changed since I've been away and I'd like to see it for myself. Thanks for unthawing me. You take care of yourself.}
#{288}{}{[Done]}

#NPC doesn't join and leaves for good
{287}{}{实际上，我想我自己就能解决事情了。我一直都是独立型的，所以我的背后也不需要任何人。自从我来到这里，很多事情都改变了，我想亲眼看看。谢谢你为我所做的。你照顾好自己，保重。}
{288}{}{[结束]}



#in party
#{300}{}{Yes?}
#{301}{}{I'm all ears.}
#{302}{}{Something you wanted?}
#{303}{}{What is it? You look like you have something to say.}
#{304}{}{What's the matter?}
#{305}{}{Is there anything you need from me?}

{300}{}{如何？}
{301}{}{我洗耳恭听。}
{302}{}{你想要什么？}
{303}{}{怎么了？你看起来好像有话要说。}
{304}{}{什么事？}
{305}{}{有什么你需要我做的吗？}


#past
#{310}{}{Kitsune, I'm pretty sure you wouldn't have been frozen in a cryo tank for no good reason. I'm interested in knowing what it was exactly you did before you were put on ice.}
#{311}{}{Why do you care? It's in the past.}
#{312}{}{We're on the road together. I want to know more about you.}
#{313}{}{[Sighs.] Well, I suppose there's no need for secrecy anymore. It's just hard to break a life-long habit. You see, I was pretty much born a spy.}
#{3130}{}{Alright. Now we're getting somewhere.}
#{314}{}{My father was Chinese, but he and his family were no friends of the Chinese government. He was born in Beijing but got the most important aspect of his education here, in the States. When he returned home and got a job as a public servant, he'd already been recruited by the Americans as an intelligence agent.}
#{315}{}{I'm not overly familiar with the politics of your time, but I think I follow what you're saying: Your dad was Chinese, but he was secretly a spy for the Americans. So did the Chinese ever suspect him?}

{310}{}{灵狐，我很确定你被冻在休眠仓里不会是没原因的。我很想知道在你被放入冰块之前你到底做了什么。}
{311}{}{为什么你想知道，那些都已经过去了。}
{312}{}{我们一路都在一起，我想知道更多关于你的事。}
{313}{}{[叹了口气] 嗯，我想再也不需要保密了。要改掉一个长期，或者应该说是终身的习惯是很困难的。你看，我天生就是个间谍。}
{3130}{}{好了，我想现在我们已经取得了一些进展。}
{314}{}{我的父亲是中国人，但他和他的家人并不是中国政府的朋友。他出生在北京，但在美国留学的时候，他找到了最重要的东西。当他回到家乡，找到一份公务员的工作时，实际上他已经被美国人招募为情报人员。}
{315}{}{我对你那个时代的政治不太熟悉，但我想我明白你的意思:你的父亲是中国人，但他是美国人的秘密间谍。中国人难道没怀疑过他吗？}

#{316}{}{My father worked at the Ministry of Agriculture for thirty-eight years.}
#{317}{}{Uh, alright, I guess that's a "no". So when did you enter the picture?}
#{318}{}{Well, one day, an aide to the official my father was working for caught him making copies of secret documents.}
#{319}{}{That couldn't have been good……}
#{320}{}{Actually, it didn't turn out so bad. You see, she thought along the same lines as my father, and within a couple of months, they were married.}
#{321}{}{Some guys have all the luck, huh?}

{316}{}{我的父亲在农业部工作了38年。}
{317}{}{呃，好吧，我想个问题的答案是“没问题”。你什么时候进的照片？}
{318}{}{嗯，有一天，我父亲的一位助手在为他工作时，发现他正在复印一些机密文件。}
{319}{}{这听起来可不太好……}
{320}{}{实际上，结果并没有那么糟糕。父亲发现，她和他的想法很接近，几个月后，他们结婚了。}
{321}{}{有些人的运气总是很好，是吧？}

#{3210}{}{Alright, now that I know your dad's life story, would you mind getting to the part about you?}
#{322}{}{They had me a year later. I was raised in China under the facade of a patriot. In school I'd write about how China was strongest when unified, and how we had to continue to strive toward social equality.  When I was older I wrote for nationalist newspapers and participated in debates supporting the ruling party.}
#{323}{}{Wow, most of that went way over my head. But if I understand correctly, you're saying you and your parents deceived the Chinese into thinking you were loyal.}
#{324}{}{Your parents took great pains to make sure your family's true loyalties stayed secret.}
#{325}{}{All warfare is based on deception. My parents loved their country. They just hated the people who ran it and thought it would be better off as a democracy. The way they saw it, they weren't betraying China - they were working against a government they didn't believe was good for it.}

{3210}{}{好的，现在我知道了你爸爸的生活故事，你能不能把你的事讲给我听？}
{322}{}{他们在一年后有了我。我是在一个爱国者的幌子下在中国长大的。在学校里，我会写中国在一党专政时才会是最强大的，以及我们如何继续努力争取社会平等。当我长大后，我为民族主义报纸撰稿，并参加了支持执政党的辩论。}
{323}{}{哇，大部分都超出了我的想象。但如果我理解正确的话，你是在说你和你的父母欺骗了中国人，让他们认为你是忠诚的。}
{324}{}{你的父母煞费苦心地保护你们家庭真正的信仰，呵呵。}
{325}{}{所有的战争都是建立在欺骗的基石之上的。我的父母热爱他们的国家。他们只是讨厌那些管理它的人，他们的看法是，他们没有背叛中国——他们是在和一个他们不信任的政府作斗争。}

#{326}{}{Go on.}
#{3260}{}{So they were traitors to their people, but for their people's own good. Got it.}
#{3261}{}{Look, I'm sick of hearing about your parents. How 'bout you get to the part about you being a spy?}
#{327}{}{I married an official who worked for the Chinese Ministry of National Defense. I chose him because he was the most willing to talk about his work when we were together. So I played the role of the dutiful wife, while secretly reporting relevant information back to my American superiors. But then things got complicated.}
#{328}{}{How so?}
#{329}{}{My father was contacted by Dr. Raynard Muldrake, an old colleague he had worked with during his time in the States. Dr. Muldrake urgently requested a private meeting, but my father was in poor health at the time and was in no condition to travel to America. Dr. Muldrake agreed to meet me in his place.}
#{330}{}{So what happened?}
#{331}{}{It turned out Muldrake was part of a top secret project at a West Tek research facility in Southern California. The project had started off innocently enough, as an attempt to find a way to make people immune to the New Plague, but it quickly evolved into something more sinister. Something called Forced Evolutionary Virus, or FEV.}
#{332}{}{Go on.}

{326}{}{[继续]}
{3260}{}{所以他们是叛徒，但是这是为了他们同胞们的利益。}
{3261}{}{我想我对你父母的事知道得够多了，所以停止谈他们吧。你是怎么成为一个间谍的？}
{327}{}{我嫁给了一个为中国国防部工作的官员。我选择他是因为他是我们在一起时最愿意谈论他的工作的人。所以我扮演了尽职的妻子的角色，同时秘密地向我的美国上司汇报相关信息。但后来，事情变得复杂了。}
{328}{}{所以如何？}
{329}{}{我父亲与雷纳德·穆瑞德雷克博士取得了联系，这是他在美国期间与他共事的一位老同事。马尔德雷克医生要求紧急召开一次私人会议，但当时我父亲身体状况不佳，没有条件去美国旅行。马尔德雷克医生同意在他的住处见我。}
{330}{}{然后发生了什么？}
{331}{}{事情是关于一个绝密项目，它是在南加州的一个叫West Tek的研究机构众多研究中的一部分。这个项目最初是很纯洁的，它试图找到一种提升人类的免疫力的方法。但很快，它演变成邪恶的东西。一种叫做“强迫进化病毒”的东西，或者我们可以叫它FEV。}
{332}{}{[继续]}



#{333}{}{It had the potential to greatly enhance a person's strength and intellect, but the FEV was dangerously unstable. Despite this, the military hoped to use it to create an army of super soldiers that could crush the Chinese.}
#{334}{}{Dr. Muldrake was against the change in the project's direction, but kept his mouth shut out of fear for his life. But when he learned that the military was testing the virus on unsuspecting, small American towns, he knew he had to take action. The world needed to know the truth.}
#{335}{}{So that's when he contacted your father……}
#{336}{}{Right. When I met him, he gave me a holodisk containing classified documentation of the FEV project. That put me in a rather difficult position: I could release the information contained in the holodisk and betray the country I'd sworn my loyalty to, or I could destroy the disk and bury the ugly truth from the people.}
#{337}{}{Holy shit. Don't tell me……}
#{338}{}{I sent copies of the holodisk to just about every major news outlet in the world. It pretty much destroyed whatever sympathy the American government still had. I might have revealed the truth to the world, but I'm afraid I also set in motion its destruction…… Things escalated quickly, and eight months later, the bombs were dropped.}
#{339}{}{How did you end up in that tank where I found you?}
#{340}{}{The American government was hunting for the person responsible for leaking the information. They finally caught up with me just before the end. They were already preparing to freeze me when the sirens first sounded. Probably to preserve me in case I had any more secrets I hadn't told them.}
#{341}{}{Did you?}
#{342}{}{It doesn't matter now. Everyone's dead……}


{333}{}{它有可能极大地增强一个人的力量和智力，但是FEV极度的危险，而且不稳定。但即使如此，军方还是希望用它来组建一支能粉碎中国人的超级士兵大军。}
{334}{}{雷纳德博士反对项目方向的改变，但逼于压力，他的嘴巴不得不闭上。直到他得知军方正在毫无戒备的美国小镇上测试病毒时，他觉得事情已经发展到不能接受的地步，他必须采取行动。世界需要知道真相。}
{335}{}{这时他想到联系你的父亲……}
{336}{}{没错，当我见到他时，他给了我一个包含FEV项目机密文件的全息磁盘。这让我陷入了一个相当困难的境地：我可以释放全息磁盘所包含的信息，背叛我发誓效忠的国家，或者我可以摧毁这个圆盘，把丑陋的真相从人民中埋葬。}
{337}{}{这真他妈的烂，你不要告诉我……}
{338}{}{我把全息磁盘的副本发送到世界上每一个主要的新闻媒体。它几乎摧毁了对美国政府的任何同情。我可能向世界揭示了真相，但我也担心我也启动了它的毁灭……事情迅速升级，8个月这后，炸弹被扔了下来。}
{339}{}{好吧，事情的开始我知道了，谈谈结束吧，你为什么会跑到那个休眠仓里的？}
{340}{}{美国政府追捕泄露情报的人。最后终于抓到了我。当警报响起的时候，他们已经准备把我冷冻起来。也许是为了保护我，也许是担心我有更多的秘密没有告诉他们。}
{341}{}{那你？}
{342}{}{现在已经不重要了。每个人都死了……}





#you caused the war
#{345}{}{Do you have any idea what the hell you brought about?}
#{346}{}{What I *may* have brought about. The world would've blown itself up sooner or later, anyhow. It was only a matter of time.}
#{347}{}{Maybe you should refrain from sharing this little tidbit of information with anyone else.}
#{348}{}{I get your drift.}

{345}{}{你知道你到底带来了什么吗？}
{346}{}{什么叫*我*带来了什么。无论如何，这个世界迟早会自己毁灭自己的，这只是时间问题。}
{347}{}{也许你应该避免与任何人分享这个小小的信息。}
{348}{}{我明白你的意思了。}



#you didn't cause the war
#{350}{}{I know what you must be thinking, but you can't blame yourself for something like that.}
#{351}{}{It's always easier not to accept responsibility.}
#{352}{}{You couldn't have known. Besides, there were other conflicts between the "powers". They would've blown each other up sooner or later. It was only a matter of time.}
#{353}{}{Humans are the worst things.}
#{354}{}{I don't consider myself that bad.}
#{355}{}{Nature's been trying to wipe us out for millennia. All these new diseases, natural disasters. We were some kind of evolutionary mistake. Maybe we came about too early or weren't suppose to come about at all. We've done more damage to this planet than any thing living or dead.}
#{356}{}{But we can atone for it. That's the special thing about us.}
#{357}{}{You've got an awfully nice way of putting it. Thanks for hearing me out. I almost feel like I can move on.}

{350}{}{我知道你在想什么，但是你不能因此责怪你自己。}
{351}{}{不接受责任总是容易的。}
{352}{}{你无法知道。除了“权力”之外，还有其他的冲突。他们迟早会打起来的，这只是时间问题。}
{353}{}{人类是毒瘤。}
{354}{}{我可不认为自己是毒瘤。}
{355}{}{几千年来，大自然一直在试图消灭我们。所有这些新的疾病，自然灾害都是为此而来。我们可能是某种进化上的错误。也许我们来得太早了，或者根本就不应该来。我们对这个星球造成的破坏比任何活着或死去的动物都要多。}
{356}{}{但是我们可以赎罪，这就是我们的特殊之处。}
{357}{}{你用一种非常好的方式来表达它。谢谢你听我的故事。我想我可以继续前进了。}


#teach me something
#{360}{}{Say, since you were a spy, I'm sure you're pretty skilled at stealth and all that. Anything you can teach me?}
#{361}{}{Yes, I've had a quite a bit of practice with sneaking, lockpicking, and stealing. Here, let me show you a few things they don't teach you in the books.}
#{362}{}{You've got it now. Remember, practice makes perfect.}
#{363}{}{Hey, thanks. I think it's about time we headed out.}

{360}{}{这么说吧，既然你是一个间谍，我相信你在潜行方面很有技巧。你能教我什么吗？}
{361}{}{是的，我曾有过一段相当多的练习那些潜行、开锁、偷东西之类的技巧。在这里，让我向你展示一些你不会在书本里学到的东西吧。}
{362}{}{你做得不错。记住，熟能生巧。}
{363}{}{嘿，谢谢。我想是我们该出发的时候了。}



#your eyes
#{370}{}{About your eyes……}
#{371}{}{What about them?}
#{372}{}{They're different colors.}
#{373}{}{What's the term for it…… heterochromia? Is that what you have?}
#{374}{}{Mine isn't a natural condition. The one on the left didn't belong to me. I lost the old one in an accident. And I've never learned to appreciate that until now.}
#{375}{}{What do you mean?}
#{376}{}{Ever since the transplant I always felt like I was seeing the past in one eye and the present in the other. More so than ever now. And that helps me carry on.}
#{377}{}{We all have our ways of coping.}

{370}{}{关于你的眼睛……}
{371}{}{它们怎么了？}
{372}{}{它们是不同颜色的。}
{373}{}{这个学术上讲叫什么？异色症吗？这是在你身上发生的事吗？}
{374}{}{这不是一个自然现象。左边的眼睛不是我的。我在一次事故中失去了原来的眼睛。直到现在我才学会欣赏它。}
{375}{}{你是什么意思？}
{376}{}{自从接受移植以来，我一直觉得我的一只眼睛看到过去，另一只眼睛看到现在。而现在这种感觉比以往任何时候都要多。这会帮助我坚持下去。}
{377}{}{自己选择的道路，我们都有自己的走法。}


#skills
#{410}{}{What do you need to know?}
#{411}{}{I have a black belt in sanshou. I can stab a man to death if the situation calls for it. Pistols, rifles and the like I'm decent with.}

{410}{}{你需要知道什么？}
{411}{}{我有一条黑带。如果情况需要，我可以把人刺死。另外如果给我手枪，步枪之类的东西，我用得也还不错。}

#distance
#{420}{}{We need to talk about the distance between us.}
#{421}{}{What's wrong with it?}
#{422}{}{Stay close to me.}
#{423}{}{Alright. I have your back.}
#{424}{}{Don't get too far away.}
#{425}{}{You need your space, got it.}
#{426}{}{Let's spread out.}
#{427}{}{Okay. We're harder targets apart.}

{420}{}{我们需要谈谈我们之间的距离。}
{421}{}{怎么了？}
{422}{}{靠近我一点。}
{423}{}{好的，我会跟着你的。}
{424}{}{不要走得太远。}
{425}{}{你需要你的空间，明白了。}
{426}{}{我们还是离远点吧。}
{427}{}{好吧。我们相信这是我们在共同努力的目标。}


#wait
#{430}{}{Don't take too long or I'm leaving without you.}
#{431}{}{I'll play solitaire or something until you come back.}
#{432}{}{I'm sure I'll find something to do while you're away.}

{430}{}{不要花太长时间，不然你别想再找到我了。}
{431}{}{我会玩纸牌或者其他东西，直到你回来。}
{432}{}{你不在的时候，我会找些其它事干的。}


#come back
#{440}{}{Whenever you need me.}
#{441}{}{Glad you're back. I held auditions but I couldn't find a good replacement for you.}
#{442}{}{Miss my company?}
#{443}{}{Feeling guilty about taking off without me?}
#{444}{}{I was beginning to think you weren't planning on coming back.}
#{445}{}{About time. In Ancient China, tardiness would get you hanged, drawn and quartered.}
#{446}{}{Hey. I was just thinking about you.}

{440}{}{只要你需要我。}
{441}{}{很高兴你回来了。我做过海选，但一直找不到合适的替代人选。}
{442}{}{我公司前台？}
{443}{}{没有了我，你会感到内疚吗?}
{444}{}{我还以为你不打算回来了。}
{445}{}{约好时间。在中国古代，迟到会使你被绞死、被五马分尸或者是凌迟处死。}
{446}{}{嘿，我只是在想你。}





#lets go
#{450}{}{You sure took your time doing whatever it is you were doing without me.}
#{451}{}{Good to be on the road again.}
#{452}{}{Where to?}
#{453}{}{So, where are we headed?}
#{454}{}{Lead the way, skipper.}


{450}{}{你肯定花时间做了你没有和我一起做的事。}
{451}{}{很高兴又上路了。}
{452}{}{去哪儿？}
{453}{}{那么，我们要去哪里？}
{454}{}{带路，队长。}





#party full
#{460}{}{You've got enough people already. You don't need an entourage.}
#{461}{}{Maybe when you've freed up some space. I don't run well with crowds.}

#{462}{}{You ready to take me with you?}
#{463}{}{Let's go.}
#{464}{}{No, not yet.}

{460}{}{你已经有足够的人了，你不需要更多的人手。}
{461}{}{当你的队伍人数少一些的时候再回来，我不习惯待在人堆里面。}

{462}{}{你准备好带我走了吗？}
{463}{}{走吧。}
{464}{}{不，还没有。}

#ch <= 1
#{470}{}{Jesus, you look like the Grim Reaper. You ought to get yourself checked out.}

{470}{}{耶稣，我的天，你看起来像死神。你应该去检查一下。}

#remove armor
#{480}{}{No problem. I'm lighter on my feet without it.}
{480}{}{没有问题。没有了它，我可以看我的脚看得更清楚。}

#hurt
#{490}{}{Never been better. Let's keep going.}
#{491}{}{I've been worse. Just a couple of scratches.}
#{492}{}{I'm not that bad off. Just some flesh wounds.}
#{493}{}{I'm not doing so great. More blood than I care to have coming out of me.}
#{494}{}{I need a medic or I'm not going to be able to help you with a damn thing.}
#{495}{}{Can't go on any longer…… leave me behind or get me to a doctor. Fast.}

{490}{}{前所未有的好，让我们继续。}
{491}{}{我想事情还能接受，不过多了几处小伤口。}
{492}{}{我想还没有那么坏。只是一些肉体上的创伤。}
{493}{}{我觉得不太好。从我身上流出的血比我想的还要多。}
{494}{}{我需要一个医生，否则我就不能帮你了。}
{495}{}{不能再继续了……把我留在后面，或者带我去看医生，快。}

#remove weapon
#{500}{}{If you insist. I can still take a man's head off with my hands.}
{500}{}{如果你坚持的话，好吧。我可以用手把一个人的头砍下来。}

#location floats

#EPA
#{1000}{}{I can't believe I spent over a hundred years in this place.}
{1000}{}{我简直不敢相信我在这个地方呆了一百多年。}

#ARROYO
#{1010}{}{Not my kind of place to be born in, no offense.}
{1010}{}{我可不想在这里出生，没有冒犯的意思。}

#TEMPLE OF TRIALS
#{1020}{}{This looks like some 15th Century emperor's burial tomb.}
{1020}{}{这看起来像是15世纪的皇帝墓地。}

#KLAMATH
#{1030}{}{This place smells like cattle dung all over.}
{1030}{}{这个地方闻起来像牛粪。}

#TOXIC CAVES
{1040}{}{我认为没有穿着合适的鞋子就进入这个地方是不明智的。}

#THE DEN
#{1050}{}{I've seen worse places, believe me. Not that I'm too fond of this one.}
{1050}{}{我看到过更糟糕的地方，相信我。不过我也不太喜欢这个地方。}

#MODOC
#{1060}{}{Rustic. I like it.}
{1060}{}{乡村，我喜欢。}

#GHOST FARM
#{1070}{}{This place looks straight out of a snuff flick.}
{1070}{}{这个地方看起来像是从鼻烟壶里冒出来的。}

#GECKO
#{1080}{}{I can taste the radiation in the air.}
{1080}{}{我能闻到在空气中的放射线。}


#VAULT CITY [OUTER]
#{1090}{}{What is this supposed to be, a labor camp?}
{1090}{}{这是什么地方？一个集中营？}

#VAULT CITY [INNER]
#{1100}{}{The ones inside have it so much better than the ones outside. The world hasn't changed all that much.}
{1100}{}{里面看起来比外面的要好得多。看来世界并没有改变那么多。}

#REDDING
#{1110}{}{Just what kind of mining town do you call this?}
{1110}{}{你把这叫做矿业城镇？}

#PRIMITIVE TRIBE
#{1120}{}{Not my kind of place to be born in, no offense.}
{1120}{}{我可不想在这里出生，没有冒犯的意思。}

#RAIDERS
#{1130}{}{Good place to hide out if the law's on your tail.}
{1130}{}{好地方，如果法律在背后追着，那你可以躲起来。}

#SIERRA ARMY DEPOT
#{1140}{}{I wonder if there're any more bunkers like this around.}
{1140}{}{我想知道是否还有像这样的碉堡。}

#NEW RENO
#{1150}{}{Biggest Little City in the World. I'll bet.}
{1150}{}{我敢打赌这是世界上最大的小城市。}

#STABLES
#{1160}{}{They can't keep just cattle here……}
{1160}{}{They can't keep just cattle here……}

#GOLGOTHA
{1170}{}{Death all over……}
{1171}{}{他们不能只在这里养牛……}

#BROKEN HILLS
#{1180}{}{We just jump ahead of nature and keep evolving, don't we? }
{1180}{}{我们只是超越自然，继续进化，不是吗？}


#SAN FRANCISCO
#{1190}{}{I haven't seen buildings this tall since the 101 got leveled.}
{1190}{}{自从101大楼被夷为平地以来，我从未见过这么高的建筑。}

#MILITARY BASE
#{1200}{}{They sure locked this place down tight.}
{1200}{}{他们肯定把这个地方关得严严实实。}

#VAULT 13
#{1210}{}{I've heard about these places……}
{1210}{}{我听说过这些地方……}

#NEW CALIFORNIA REPUBLIC
#{1220}{}{Feels nice to walk into a town that looks like it has it together.}
{1220}{}{走进一个看起来像连在一起的城镇感觉很好。}

#VAULT 15
#{1230}{}{I've heard about these places……}
{1230}{}{我听说过这些地方……}

#ABBEY
#{1240}{}{The only holy place in these unholy wastes.}
{1240}{}{在这个世界中唯一神圣的地方}


#DESERT MAP
#{1250}{}{It's hot out here.}
#{1251}{}{I'm sweating bullets.}
#{1252}{}{I'm parched.}
#{1253}{}{I'd like it better if this were a beach.}
#{1254}{}{Sulik, you know anything about rain dances?}

{1250}{}{这里太热了。}
{1251}{}{我的子弹都出汗了。}
{1252}{}{我快要干掉了。}
{1253}{}{我想如果这是海滩的话，我会更喜欢它。}
{1254}{}{史力克，你会跳求雨舞吗？}

#MOUNTAIN MAP
#{1260}{}{This is as far from civilization as it gets.}
{1260}{}{这是一个远离文明的地方。}

#SEASIDE
#{1270}{}{I doubt that water would be drinkable even if you filtered all the salt out.}
#{1271}{}{Any fish we find in these waters are bound to be mutants of some sort.}
#{1272}{}{It's cool out here.}
#{1273}{}{Hundreds bucks to anyone who dares to go skinny-dipping in those waters.}

{1270}{}{我怀疑即使你过滤掉所有的盐，水还是喝不了的。}
{1271}{}{我们在这些水里一定发现不了没变种的鱼。}
{1272}{}{这里很凉快。}
{1273}{}{有人敢在这里裸泳的话，我一定给他几百美元。}

#CAVE
#{1280}{}{I can't see a damn thing in here.}
#{1281}{}{This place smells bad and if I could see it better it'd probably look even worse.}
#{1282}{}{Careful. There's probably something ugly and smelly holed up here.}
#{1283}{}{Are those bats I hear?}
#{1284}{}{What are we going to do, spelunk?}
#{1285}{}{Better to light a candle than to curse the darkness.}

{1280}{}{我在这里什么也看不见。}
{1281}{}{这个地方闻起来很难闻，如果我能看清楚的话，估计还会更糟。}
{1282}{}{小心，这里可能有一些丑陋和难闻的东西。}
{1283}{}{我听到的那些声音是蝙蝠吗？}
{1284}{}{们要做什么，秉烛夜游？}
{1285}{}{与其诅咒黑暗，不如燃起蜡烛。}


#CITY RUINS
#{1290}{}{War…… a whole lot of good that did us.}
#{1291}{}{Dust to dust……}
#{1292}{}{I used to live someplace just like this……}

{1290}{}{战争……我们做了很多的“好事”……}
{1291}{}{尘归于尘，土归于土……}
{1292}{}{我以前就住在这样的地方里……}


#general floats

#{2001}{}{My eyes bug you that much?}
#{2002}{}{I could use a soak in a hot spring. Wonder if there're any of those left anymore.}
#{2003}{}{I'd kill to find someone to play mahjong with.}
#{2004}{}{Everyone eats and drinks. Yet only few appreciate the taste.}
#{2005}{}{This world is hell now. All thirteen levels.}
#{2006}{}{I believe in both God and the Devil. But I keep them at a distance.}
#{2007}{}{Are we living a dream, or are we someone else's dream?}
#{2008}{}{I hate what we've done to ourselves.}
#{2009}{}{I wonder how long it's going to take us to recover from the War.}
#{2010}{}{If heaven made us, then the earth'll find some use for us.}
#{2011}{}{You thirsty? I sure am.}
#{2012}{}{*yawn*}
#{2013}{}{Man proposes and God disposes.}

{2001}{}{我的眼睛对你有那么大的困扰吗？}
{2002}{}{我想我得去找个温泉泡一下，不知道还有没有剩下的温泉。}
{2003}{}{我想找个人打麻将。}
{2004}{}{每天我们都吃和喝着这样的东西。估计只有少数人能欣赏这种味道。}
{2005}{}{这个世界现在是在地狱13层左右吧。}
{2006}{}{我相信上帝和魔鬼。但是我把它们放在远处。}
{2007}{}{我们是在做一个梦，还是我们是别人的梦？}
{2008}{}{我讨厌我们对自己所做的。}
{2009}{}{我想知道我们要多久才能从战争中恢复过来。}
{2010}{}{如果上帝创造了我们，那么地球将为我们找到一些用处。}
{2011}{}{你渴吗？我确定我很渴。}
{2012}{}{*打哈欠*}
{2013}{}{谋事在人，成事在天。}



#sulik in party
#{2020}{}{Hey, Sulik. What are the spirits saying?}
{2020}{}{嘿，史力克。灵魂们在在说什么？}

#vic in party
#{2030}{}{You interested in slimming down, Vic? Ask me any time for taebo lessons.}
{2030}{}{你对减肥有兴趣吗，伊克？如果你想学跆拳道，那你任何时间都可以问我。}

#miria in party
#{2040}{}{Your wife talks too damn much about herself.}
#{2041}{}{Tell your hillbilly wife to stop coming onto me.}
{2040}{}{你的妻子话太多了。}
{2041}{}{告诉你的乡巴佬妻子不要接近我。}

#myron in party
#{2050}{}{My chest and your eyes have no business, Myron.}
#{2051}{}{How about shutting up for two minutes, Myron? Would that kill you?}
#{2052}{}{No, Myron. I wouldn't sleep with you if you built me a time machine.}
#{2053}{}{Listen, Myron. You don't keep your hands to yourself, I'll make you a eunuch.}

{2050}{}{我的胸部和你的眼睛之间没有业务，麦郎。}
{2051}{}{为什么站着不动两分钟，麦郎？你想我杀了你？}
{2052}{}{不，麦朗。如果你给我造一个时间机器，我就会和你睡了}
{2053}{}{听着，麦朗。如果你不把手放在自己身上，我让你做个太监。}


#marcus in party
#{2060}{}{Hey, Marcus. Wanna arm-wrestle?}
{2060}{}{嘿，马可世。}

#k-9 and dogmeat both in party
#{2070}{}{We've got enough dogs following us around. We don't need another one.}
{2070}{}{我们有足够的狗跟着我们，我们不需要另一只。}

#poisoned
#{2100}{}{Ugh, I feel like hell.}
#{2101}{}{I think I've been poisoned……}
{2100}{}{呃，我感觉像地狱一样。}
{2101}{}{我感觉我快要被毒死了……}

#radiated
#{2110}{}{Something doesn't feel right in me……}
#{2111}{}{I feel strange……}
#{2112}{}{My hand. It's glowing.}
#{2113}{}{I'm a fox, not a snake…… Why's my skin peeling?}
#{2114}{}{This burning inside…… What's happening to me?}

{2110}{}{有什么东西让我感觉不舒服……}
{2111}{}{我觉得奇怪……}
{2112}{}{我的手，它在发光……}
{2113}{}{我是一只狐狸，不是一条蛇…… 为什么我的皮肤脱皮了？}
{2114}{}{我感觉我的身体在燃烧…… 到底是怎么回事？}


#broken limb
#{2120}{}{Got a fracture, I think. Need to get it looked at.}
#{2121}{}{Feels like I broke something……}
{2120}{}{有骨折，我想我需要一个大夫。}
{2121}{}{我的身体里有什么碎掉了……}


#blind
#{2130}{}{I can barely see, damn it.}
#{2131}{}{I hate being blind.}

{2130}{}{我什么都看不见，该死。}
{2131}{}{我讨厌失明。}

#items used on Kitsune - Nodes 4000

#stimpack
#{3000}{}{Better.}
#{3001}{}{Appreciate it. Those are a godsend.}
#{3002}{}{I feel better already. Thanks.}
#{3003}{}{Thanks. I needed that.}
#{3004}{}{You have enough for yourself?}

{3000}{}{好。}
{3001}{}{欣赏它。这些都是天赐之物。}
{3002}{}{我感觉好很多了，谢谢。}
{3003}{}{谢谢，我需要它们。}
{3004}{}{你有留给你自己足够的份量吗？}


#booze
#{3010}{}{Strong stuff. Good thing I can hold my liquor.}
#{3011}{}{Don't know why I'm drinking this. Tastes like drain cleaner.}
#{3012}{}{Never liked booze all that much. But it numbs the pain.}
#{3013}{}{Got anything else to drink?}
#{3014}{}{Let's hope I don't wake up in a pool of my own puke.}
#{3015}{}{There go my plans to stay sober today.}

{3010}{}{这酒真够“劲”。好东西，让我拿着我自己的酒。}
{3011}{}{不知道我为什么要喝这个。这尝起来就像下水道清洁剂。}
{3012}{}{我从来都不喜欢喝这么多酒，但它麻木了痛苦。}
{3013}{}{还有什么喝的吗？}
{3014}{}{我希望不会在自己的呕吐物中醒过来。}
{3015}{}{我的计划是今天要保持清醒。}


#psycho
#{3020}{}{Shit…… Let's hope we don't ever have to face a whole gang hopped up on these.}
{3020}{}{狗屎……我真不希望看每一个人都象是一堆人。}

#buffout
#{3030}{}{Better go easy. This stuff messes with your testosterone.}
{3030}{}{更强的安非他命。这些东西会使你的睾丸激素紊乱的。}


#mentats
#{3040}{}{Hopefully this doesn't turn me into an idiot once it wears off.}
{3040}{}{但愿药效消失的时候不会把我变成傻瓜。}

#jet
{3050}{}{Habits are spiders first, threads last.}
{3051}{}{The sword is mightier than the sky.}
{3052}{}{Eye for tooth, tooth for all.}
{3053}{}{A person needs a face like a tree needs to bark.}
{3054}{}{The tree falls when the monkeys climb it.}
{3055}{}{All crows in the world are smarter than the average hawk.}
{3056}{}{A stitch of nine saves ten.}
{3057}{}{A tiger's sons are not lions.}
{3058}{}{Learn. And in learning go wrong.}
{3059}{}{The ride comes before the fall.}
{3060}{}{Fight sand with fire, magic with dust.}
{3061}{}{We must all prepare for the war of peace.}
{3062}{}{Add stripes to a snake after you finish drawing it.}
{3063}{}{The tiger may rid itself of its spots by being hard to alight.}
{3064}{}{One cannot refuse to eat just because there is a chance of growing hungry all over again.}
{3065}{}{A painting is worth a hundred years of pain.}
{3066}{}{Vicious as a tigress can be, never does she eat her own crabs.}
{3067}{}{A mermaid's fingers are short and sweet.}
{3068}{}{Kill thousands to wane one.}
{3069}{}{Keep your enemies close, and your friends right below you.}
{3070}{}{To evade the surest weakness one strikes the strongest from up front.}
{3071}{}{If your enemy is securely trained, prepare yourself for ecstasy.}
{3072}{}{Back the enemy, for him to prepare himself.}
{3073}{}{He who knows not how to fight but when, will embrace victory.}
{3074}{}{The impudent lie in wait for an enemy who cannot, and thus will win.}
{3075}{}{Invisibility possibly lies in defending the enemy at the attack of victory.}
{3076}{}{Know yourself. Know your enemy. Know your friends and family.}
{3077}{}{Opportunities multiply as we sneeze.}
{3078}{}{Impale your opponent with your ego.}
{3079}{}{Pretend weakness. Give courage to the adversary's ignorance.}
{3080}{}{Tactical strategy means a sure victory.}
{3081}{}{Cautious rulers are all generally sinful.}
{3082}{}{Break out in supreme excellence, and a nation shall quake at the benefits of prolonged warfare.}
{3083}{}{Tactics to conquer men. Strategy to evolve seeing.}
{3084}{}{There are million of ways for a cat to shed its skin.}
{3085}{}{You can't squeeze pebbles from a drop of blood.}
{3086}{}{There is no blood thicker than that of water.}
{3087}{}{There must be two suns in the sky.}
{3088}{}{Steal the flesh and mark it.}
{3089}{}{Mental is the flesh, carrying the potential that wanes.}
{3090}{}{A bird sings because its song is the answer.}
{3091}{}{Lower your voice and augment your strength.}
{3092}{}{Eat beyond your limits, walk according to the lengths you'll go to.}
{3093}{}{If a word be worth a sheik then silence be worth an emperor.}
{3094}{}{He who lives outside this plane dies with honor.}
{3095}{}{Deceive the poor. Insult the rich.}
{3096}{}{Once the heat has passed out, you forget the shady tree.}
{3097}{}{No one is closer to death as the one who listens.}
{3098}{}{Every man for all, and all for us.}
{3099}{}{All men are immortal like the Eight.}
{3100}{}{When you're dying of thirst, it's not too late to dig for water.}
{3101}{}{The taller the bamboo grows, the closer the panda comes to emerging.}
{3102}{}{Never rely on the glory of morning or the smiles of your mother-in-law.}
{3103}{}{Eyes are our sole windows.}
{3104}{}{Old age creeps up on you like a dirty old man.}
{3105}{}{Heaven is never at fault. The wicked will be paid their wages in time.}
{3106}{}{Justice is the virtuous soul that distributes itself out in the desert.}
{3107}{}{It is better that ten innocents die than one guilty man suffer.}
{3108}{}{The halls in the halls of justice are the only justice.}
{3109}{}{Lock the stable when the horse is stolen.}
{3110}{}{Haymakers under the shining sun.}
{3111}{}{Never take a gift from a horse's mouth without asking it first.}
{3112}{}{The world laughs at you. Then you weep with your comrades.}
{3113}{}{Many hands make the lights work.}
{3114}{}{A dish of carrots unsoiled, uncleaned, with vegetables.}
{3115}{}{A donkey's lips kisses a horse's mouth only when fed with extra fodder during the night.}
{3116}{}{Bring a club into a tiger's lair.}
{3117}{}{A swine casts a necklace of pearls.}
{3118}{}{Caviar Emperor.}

#Don't apply ERSI to specimen == horrible flaming death for specimen
#{5000}{}{[As the woman looks up at your face, her eyes suddenly grow wide and she starts gasping for air.}
#{5001}{}{[END]}
#{5002}{}{Holy shit!}

{5000}{}{[当女人抬头看你的脸时，她的眼睛突然睁得很大，她看上去很痛苦。]}
{5001}{}{[结束]}
{5002}{}{操！}
