# Message file for epac2.ssl 

#{100}{}{You see a Hologram.}
#{101}{}{You see the Director of Science.}
#{102}{}{Hologram 00000. He looks after the scientific aspects of the EPA.}

{100}{}{你看到一个全息图像。}
{101}{}{你看见科学主任。}
{102}{}{全息图像00000，他管理EPA的科学的事务。}


{200}{}{01001000 01100101 01101100 01110000 00100000 01101101 01100101 00100001}
#{201}{}{Uh, what?}

{201}{}{呃, 什么？}

{210}{}{01000101 01101100 01100101 01100011 01110100 01110010 01101001 01100011 01100001 01101100 00100000 01110011
 01101000 01101111 01110010 01110100 00101110}
#{211}{}{Sorry, I can't understand you. Bye.}
#{212}{}{Interesting. It seems you're only able to communicate using binary numbers. Hold on, if I write down what
 you're saying, I just might be able to figure this out.}
 
{211}{}{对不起，我听不懂你说的，再见。}
{212}{}{真有趣，似乎你是在用二进制数进行交流？让我试着把你说的代码写下来看看。}
 
 
#{220}{}{[After a couple hours, you finally believe you've correctly translated the binary numbers. It appears he's
 saying "Help me! Electrical short."}
#{221}{}{Well, that was fun to decode. See ya.}
#{222}{}{An electrical short in the tape reel, huh? Alright, let's see if we can get you fixed.}

{220}{}{[数小时后，看起来你已经正确地翻译了二进制代码]看来他是说:“帮帮我!电，短……”}
{221}{}{嗯，你说的事情真有趣，再见。}
{222}{}{磁带机短路，对吧？好，让我们看看能不能把你修好。}

{230}{}{01001000 01100101 01101100 01110000 00100000 01101101 01100101 00100001}
{231}{}{我只是来看看。再见。}
{232}{}{别担心，我正在努力把你修好。}

{240}{}{01010010 01100101 01100010 01101111 01101111 01110100 00100000 01101101 01100101 00100001}
{241}{}{好吧，我放弃了，抱歉。}
{242}{}{还不能工作吗？让我再看看你说的是什么。}

{250}{}{[你以更快的速度进行解码]:"重新引导我！"哦，原来是这个问题[你重启机器运行全息图，你看到了启动程序的载入界面，为了打发时间，你吹起了口哨]}
#{251}{}{[Continue.]}

{251}{}{[继续]}



{260}{}{感谢霍金！你做到了！我的发音程序被锁死在二进制模式下已经不知道多少年了。我很高兴能和一个志同道合的人交流，这段日子我一直在等一个会懂二进制的人，但不幸的是并没有。}
{261}{}{还有其它人吗？}

#{270}{}{They didn't have time for me, you see. Oh no, they were too *busy* indulging in their bureaucratic nonsense.
 Too busy imposing regulations upon one another and bickering like fools. And look where it got them: stuck in an endless
 loop in the conference chamber. Ha! Serves 'em right.}
#{271}{}{Stuck in a loop?}
#{272}{}{I actually fixed that problem. No more endless loops.}

{270}{}{他们没有时间陪我，哦，不，应该说他们太忙了，一直忙着在胡说八道，忙着把规章强加于人，忙着像傻瓜一样争吵。看看那群在会议室的蠢货，无限的会议，无限的循环。哈哈，是他们对的，让他们去忙吧！}
{271}{}{困在一个循环？}
{272}{}{事实上那个问题我已经解决了，没有死循环了。}


#{280}{}{What's that? Oh, yes, yes, it seems a malfunction somewhere has generated a powerful magnetic field, which is
 erasing their short term memory every couple minutes, damning them to a kind of hologram purgatory. But never mind that,
 we're better off without them. With them tied up in an endless argument, that leaves me, er, I mean, *us*, in charge of
 the facility. With my supreme intellect, and your physical body, we could make quite the duo.}
#{281}{}{First off, why don't you tell me what exactly this place is?}

{280}{}{那是什么？哦，是的，似乎终端机在某处发生了故障，产生了强大的磁场，导致每隔几分钟就抹去会议室那群蠢货的记忆，把他们弄成一种全息对话的死循环。但没关系，让他们没完没了的吵好了，没有他们我们会过得更好。我的意思是，有了我的智慧和你的肉体，我们会是一对完美的搭档。}
{281}{}{首先，你为什么不告诉我这个地方到底是什么？}

#{290}{}{Really? In my opinion, we're better off without them, but if you thought otherwise who am I to complain. With my
 supreme intellect, and your physical body, we could make quite the duo, you know.}
#{291}{}{First off, why don't you tell me what exactly this place is?}

{290}{}{真的吗？在我看来，没有他们我们会更好，我的意思是，有了我的智慧和你的肉体，我们会是一对完美的搭档。你知道的。}
{291}{}{首先，你为什么不告诉我这个地方到底是什么？}


#{300}{}{Why, it's the Environmental Protection Agency, of course. This is a federal facility originally established to
 regulate chemicals and ensure the protection of the environment, but it's become oh so much more than that! Why, you're
 standing in one of the nation's top experimental research facilities. We have so many exciting things in development. Of
 course, progress has been a bit slow lately, what with the fall of civilization and all...}
#{301}{}{That's understandable.}
#{302}{}{The apocalypse is no excuse for slacking off.}

{300}{}{这是哪里？这里是EPA，环境保护署。这是一个由联邦机构建立，规范化学品和确保环境保护的机构。但它已经变成了远远不止这些！你现在所在的是美国顶尖的实验研究机构之一，我们有许多令人兴奋的事情在发展。当然，因为世界未日的原因，最近的进展有点慢……}
{301}{}{这是可以理解的。}
{302}{}{世界末日可不是偷懒的借口。}


#{310}{}{Yes, if only I had an able bodied assistant, I could finally make some more progress on my research...}
#{311}{}{What kind of help do you need?}

{310}{}{当然，如果我有一个能干的助手，我意思真正是能动手的助手，我就能在我的研究上取得一些进步……}
{311}{}{你需要什么样的帮助？}


#{320}{}{Well, that depends. I don't suppose you'd feel comfortable wielding a large experimental gun, would you?}
#{321}{}{Hell yeah I would!}
#{322}{}{Sure.}
#{323}{}{I think I'll pass.}

{320}{}{嗯，你看我不太可能舒服地拿着一把实验枪吧，对吗？}
{321}{}{嗯，但我可以!}
{322}{}{确定。}
{323}{}{我想我还是不参与了。}

#{330}{}{Oh, I see. That's too bad. Oh well, no hard feelings. I'll just wait until the next flesh and blood person comes
 wandering into this facility. It's bound to happen again within a century or two. Goodbye.}
 
#{340}{}{Hello again. I don't suppose you've reconsidered my offer of helping me to test an experimental weapon?}
#{341}{}{Nope. Sorry.}
#{342}{}{Alright. Sure.}

{330}{}{哦，我明白了。那太糟了，看来我要等到下一个血肉之躯游荡到此了，它肯定会在一两个世纪内再次发生的，再见。}
 
{340}{}{您好，你要不要重新考虑一下帮助我测试实验武器的提议？}
{341}{}{不，对不起。}
{342}{}{好吧，我帮你。}


#{350}{}{Excellent! You're the perfect candidate. You see, in an effort to help the military become more "environmentally
 friendly", I developed a new weapon that requires no ammo, as it runs completely on *light*. I call it, the
 *Solar Scorcher*. However, it's yet to be tested under direct sunlight, which is, of course, where you come in.}
#{351}{}{So you just want me to go outside and shoot this thing? That's it?}
#{352}{}{Yeah, yeah, just give me the gun already.}

{350}{}{太棒了!你是完美的助手候选人，你看，为了让军队变得更加环保。我发明了一种新的武器，它不需要弹药，因为它完全使用*太阳能*运行。我叫它*太阳能发射器 *。但是，这件发明还没有真正在户外进行测试过。}
{351}{}{所以你是想让我到外面找个东西，然后用这把枪射上一通？对吧？}
{352}{}{好的，把枪给我。}

#{360}{}{Essentially, yes. Of course, I need to know how well it fares in a combat situation, so I'd appreciate it if you
 could find some threatening life forms out there, which you could then spectacularly dispatch with my Solar Scorcher.}
#{361}{}{Go outside and kill something, got it. So, where is this Solar Scorcher?}

{360}{}{从本质上来说是的。作为发明者，我需要知道在实战中它的效果如何，你需要在地面找到一些真正能威胁到生命的东西，然后用我的发明来进行实战测试。如果你愿意帮忙的话我会很感激的。}
{361}{}{到外面，找个能把人杀掉的东西，用这把枪干掉它/他/她，然后回来，对吧。那么，太阳能发射器在哪里呢？}

#{370}{}{Not so hasty, my friend. I don't want you to simply shoot the weapon outside aimlessly. I need to know how well
 it fares in a combat situation, so I'd appreciate it if you could find some threatening life forms out there, which you
 could then spectacularly dispatch with my Solar Scorcher.}
#{371}{}{Go outside and kill something, got it. So, where is this Solar Scorcher?}

{370}{}{不要这么匆忙，我的朋友。我不希望你只是漫无目的地射击。我需要知道这个发明在实战中的性能，你需要在地面找到一些真正能威胁到生命的东西，然后你可以用我的发明来进行实战测试。}
{371}{}{到外面，找个能把人杀掉的东西，用这把枪干掉它/他/她，然后回来，对吧。那么，太阳能发射器在哪里呢？}

#{380}{}{Oh, yes, it's in that locker on the wall over there, next to my projector. The passcode is 03141879.}
#{381}{}{Alright, I'll try it out and let you know how it goes.}

{380}{}{对，就是这样。枪在那里墙上的那个柜子里，在我的投影机旁边，密码是03141879。}
{381}{}{好的，我会试试看。}

#{390}{}{Ah, welcome back. Have you gotten a chance to test the Solar Scorcher?}
#{391}{}{Sure did. It scorched the hell out of things.}
#{392}{}{Sure did, but the piece of shit broke on me. I had to trash it.}
#{393}{}{No, not yet.}
#{394}{}{I'll get around to it.}

{390}{}{欢迎回来，你有测试过太阳能发射器吗？}
{391}{}{当然有，它把能射中的东西都烤得象曲奇饼那样脆。}
{392}{}{当然有，但是那件狗屎砸到我了，我把它扔掉了。}
{393}{}{不,还没有。}
{394}{}{我先离开好了。}



#{400}{}{Excellent! I'm delighted to know it works as intended. Thank you for assisting me with this. Why don't you go
 ahead and keep the Solar Scorcher, I'd rather it get some use than sit around here and collect dust.}
#{401}{}{Thanks!}
#{402}{}{Good, because I didn't plan on giving it back anyway.}

{400}{}{太棒了!我很高兴地知道它是有意义的，谢谢你帮我这个忙。这个东西归你了，希望你能让它得到一些实际运用，而不是被丢在这里收集灰尘。}
{401}{}{谢谢! }
{402}{}{好，我还以为你要把它收回去了。}

#{410}{}{Oh... I see. I don't understand, that prototype withstood vigorous lab testing... [He shakes his head
 sadly.] Anyway, thanks for assisting me.}
#{411}{}{Whatever.}
#{412}{}{No problem.}

{410}{}{哦……我明白了，不，我不明白……[他摇了摇头]这真是遗憾，不管怎样，这个原型经受住了实验室测试的考验，谢谢你的帮忙。}
{411}{}{等等。}
{412}{}{没问题。}

#{420}{}{Nice to see you again. However, if you'll excuse me, I've got a plethora of projects that require my attention.}
#{421}{}{[End.]}

{420}{}{很高兴再次见到你，但我有太多的项目需要我的注意了，下次再谈吧。}
{421}{}{[结束]}

#{500}{}{You fix Hologram 00000.}
#{510}{}{You test the Solar Scorcher for the Director of Science.}

{500}{}{你修复了全息图像00000。}
{510}{}{你为科学主任测试了太阳能发射器。}
