# Message file for epac4.ssl 
# Number of nodes: 13

#{100}{}{You see a Hologram.}
#{101}{}{You see the The Director of Security.}
#{102}{}{Hologram 10001. He oversees the EPA's security.}


{100}{}{你看到一个全息图像。}
{101}{}{你看到安全主任。}
{102}{}{全息图像10001，他负责监督EPA的安全。}


# Node  0  [Node001]
#{200}{}{Halt! Do not attempt to come any closer. Identify yourself, intruder.}
#{201}{}{I'm the Chosen One of Arroyo. I'm exploring the EPA.}
#{202}{}{I'm not an intruder and now I need to be leaving.}
#{203}{}{I'm }
#{204}{}{, and I'm not trying to intrude, I'm just exploring.}

{200}{}{停止！别靠近我，入侵者。}
{201}{}{我是阿罗由的选民，我在探索EPA。}
{202}{}{我不是入侵者，现在我需要离开。}
{203}{}{我是 }
{204}{}{，我并不想打扰，我只是在探索这里。}

# Node  1  [Node002]
#{210}{}{Exploring！？Exploring...MY...EPA！？How dare you have the audacity to break in here and just casually wander around! Vollidiot! I have a half a mind to arrest you and toss your ass in the petting zoo -- give them freakshows a real feast!}
#{211}{}{No, wait! I'm not doing you any harm! Let me explain...}

{210}{}{探索！？探索！？在负责安全的本大爷眼皮子底下你竟然敢"探索"这个美利坚合众国的机密机构EPA？我现在就要把你一脚踢到下面的动物园里当饲料！}
{211}{}{不，等等！让我解释一下...}

# Node  2  [Node003]
#{220}{}{You aren't going anywhere fast, Pisskopf. Nobody saunters into MY EPA without explaining themselves. How do I know you're not a Chinese spy?}
#{221}{}{I guess you don't. But if you give me a chance to explain myself, I'm sure we can sort this whole mess out.}
#{222}{}{So what if I am? Does it even matter? Your precious EPA isn't exactly relevant anymore. It's just another decaying relic of a lost age.}

{220}{}{你什么地方都去不了，混球。没有人可以在没有准许的情况下就走进我的EPA，我怎么知道你不是中国间谍？}
{221}{}{我猜你可能不会喜欢，但是如果你给我一个解释的机会，我相信我们就不会把这里搞得一团糟。}
{222}{}{那么，如果我是呢？它甚至有关系吗？你珍贵的EPA已经不再重要了，现在这只是一个逝去时代的腐朽遗迹罢了。}



# Node  3  [Node004]
#{230}{}{Go on then, Schwachkopf, explain yourself. Make it good though, or I'll have the robots beat you and drag you down to the electric chair!}
#{231}{}{Alright. First off, I'm not a Chinese spy -- I'm what you might call a tribal. I've been chosen to embark on a perilous quest so that I might save my tribe from destruction. I only entered this complex in hope of scavenging something that could aid me in my quest.}
#{232}{}{Fuck off. Seriously, you're a *hologram*. The worst you can do is try and shout me to death, which you seem to be giving your best shot. As for those scrap heaps you call robots, I might be a little more intimidated if I saw any around here that actually work.}

{230}{}{入侵者，现在开始解释。你最好让你的解释听起来合理一点，否则我就让机器人打趴你，然后把你拉到电椅上！}
{231}{}{好吧。首先，我不是中国间谍--我来自阿罗由，我被选中从事一项危险的任务，拯救我的部落免于毁灭。我进入EPA，是希望能找到一些能帮助我的东西。}
{232}{}{滚开，在大吼大叫之前，你能先搞清楚你只是一个*全息图像*吗？你所能做的最坏的事就是试着把我喊死，在这方面我看到你已经在尽你最大的努力了。至于那些被你称为机器人的垃圾堆，如果我在这里能看到任何真正有用的东西，我可能会有点害怕。}


# Node  4  [Node005]
#{240}{}{Scavenge! You Pissnelke! How dare you discredit the name of the EPA in this way! Nobody so much as removes a piece of paper from this building without my say so! However, to have entered this far into the EPA would require some skill...perhaps I could find a use for you after all. }
#{241}{}{Huh?}
#{242}{}{No, I think I'll just scavenge some more and go. Bye!}

{240}{}{什么！没有人能从这栋楼里拿出一张纸！不过等等，进入EPA的话需要一些技巧，也许我能找到你的用处。}
{241}{}{嗯？}
{242}{}{不，我想我还去去捡更多的垃圾好了，再见！}


# Node  5  [Node006]
#{250}{}{Insolence! Such insolence from a Bles Arschloch! When I began my training, insolence was to be punished. And punished we were! Mark my words scheisskopf, that forked tongue of yours will one day be the death of you.}
#{251}{}{Maybe it will, maybe it will. And if that day were ever to come, I shall deal with it then and there. What is certain, is it will not come from you. You're a nobody. You have nothing left to rule over, which is why you cover up your sadness with anger. How long have the robots failed to respond to you?}

{250}{}{傲慢！你竟然敢这样对我说话！在我做训话的时候，傲慢是要受到惩罚的！我会惩罚你的，有一天我会把你的舌头拉出来钉在那里的墙上！}
{251}{}{如果真的有那一天，我会处理好它的。但我可以肯定的是，那和你肯定没什么关系，你只是一个*全息图像*，你什么都做不了。这就是为什么你要用愤怒来掩盖你的无力，好好想想机器人没有回应你多久了？}



# Node  6  [Node007]
#{260}{}{Well, as you may already have guessed, the robots no longer work here at the EPA. The computer consoles no longer register my verbal commands and I don't have a body to activate the console. I... I can't properly secure anything. Could you fix the robot control computer for me? I need the ability to command the robots for... well, for things.}
#{261}{}{Well why not? I'll see what I can do.}
#{262}{}{No, I don't have the time. Bye.}

{260}{}{EPA的机器人不再工作了，计算机控制台也不服从我的口头命令，我没有一个身体来激活控制台。我...我什么都做不到，你能帮我修理机器人控制电脑吗？我需要指挥机器人的能力。}
{261}{}{好，我会考虑你这件事的，我看看我能做什么。}
{262}{}{不，我没有时间。再见。}



# Node  7  [Node008]
#{270}{}{Fick dich du verdammter Arschficker! I ought to... to... [He sighs.] You're right. The robots can't understand what I say anymore. They sit there motionless like damn penners! The computers have ceased functioning and, as a hologram, I can't touch the keyboards. As I've been saying for many years now, this whole place needs leveling and rebuilding. Maybe one day I'll have the power to do just that.}
#{271}{}{Maybe I could help you somehow? I'm pretty good with computers.}

{270}{}{[他叹了口气，态度软了下来]好吧，和你猜的差不多，你是对的。机器人听不懂我在说什么。他们一动不动地坐在那里，就像那些该死的罪犯！电脑已经停止运行，作为一个全息图像，我无法触摸键盘。但正如我多年来一直说的，这个地方需要平整和重建。也许有一天我会有能力做到这一点。}
{271}{}{也许我可以帮助你？我对电脑很在行。}


# Node  8  [Node009]
#{280}{}{Thanks. If you can repair the robot control computer, I'll grant you full access to the security wing on the red level. You can take what you like from the stores. I'm afraid we have no use for them now anyway.}
#{281}{}{Thanks. I'll get back to you when I'm done.}

{280}{}{如果你能修理机器人控制计算机，我将允许你完全进入安全部门的红色水平区。你可以拿走任何你喜欢的东西，那些东西对我们已经没用了。}
{281}{}{谢谢。等我做完了再给你答复。}


# Node  9  [Node010]
#{290}{}{Lech mich! I have nothing more to say to you.}
#{291}{}{Fine.}

{290}{}{再见！我没什么可以说的了。}
{291}{}{好的。}


# Node  10  [Node011]
#{300}{}{Have you managed to complete the task yet? *Eyes gleam expectantly*}
#{301}{}{No, not yet. I'll keep working on it.}

{300}{}{你完成任务了吗？[满怀期待的眼神]}
{301}{}{不，还没有。我会继续努力的。}

# Node  11  [Node012]
#{310}{}{Are the computers back online yet?}
#{311}{}{Yes. I've repaired them for you. You can command the robots again.}

{310}{}{电脑还在线上吗？}
{311}{}{是的，我已经帮你修好了，你可以再次指挥机器人。}

# Node  12  [Node013]
#{320}{}{Excellent! Brilliant! I can crush those fools now! The EPA will be cleansed once more! Alright, now I have something for you. [Speaking to the robots] Get yer metal ass in gear and come give this civie a reward for serving this great nation!
 [A robot wheels over to you and holds out a keycard. Once you take the card, you watch it wheel back out of the room. Somehow, you get the impression that these robots would have been
 happier if you'd left them inactive.] Be on your way now. You are dismissed.}
#{321}{}{Thanks.}
#{322}{}{Dismissed? What am I, a guardsman? Later, old timer.}

{320}{}{太棒了！我现在可以粉碎那些傻瓜了！EPA将再次被净化！好了，现在我有东西给你。[对机器人说话] 抬起你的金属屁股！给我到那里拿个东西给他！动起来，去为这个伟大的国家服务！[一个轮子机器人向你走来，并拿出一个密钥卡给你。不知道为什么，你突然觉得如果这些机器人都不动的话，你会更快乐]现在走吧，你被解雇了。}
{321}{}{谢谢。}
{322}{}{解雇了？我是什么？卫兵？}

#{330}{}{Leave me alone!}
#{331}{}{I want nothing more to do with you.}
#{332}{}{MACH ES DIR SELBER!!}

{330}{}{别点我！}
{331}{}{我不想和你有任何关系。}
{332}{}{该死的共产主义者！！}


#{333}{}{I'm busy right now.}
#{334}{}{Come back later.}
#{335}{}{Can't you see I'm in conference?}
#{336}{}{We must destroy this place immediately!}
#{337}{}{That's absurd!}
#{338}{}{Never!}
#{339}{}{Only with destruction of the old can the new be reborn.}
#{340}{}{All in favor?}
#{341}{}{The robots must be reactivated!}
#{342}{}{Warmduschers! All of you!}
#{343}{}{Our weapon defenses are in dire need of ammunition!}
#{344}{}{If I was in charge, things would actually get done around here!}
#{345}{}{Halt die Schnauze!}

{333}{}{我现在很忙。}
{334}{}{稍后回来。}
{335}{}{你看不出我在开会吗？}
{336}{}{我们必须立即摧毁这个地方！}
{337}{}{这是荒谬的！}
{338}{}{决不！}
{339}{}{只有在旧的东西被破坏的情况下，新的才会重生。}
{340}{}{都在忙吗？ }
{341}{}{机器人必须被重新激活！}
{342}{}{共产主义者！你们都是！}
{343}{}{我们的武器防御系统急需弹药！}
{344}{}{如果我负责的话，这里的事情都能搞定！}
{345}{}{闭嘴！}


#{400}{}{Arrest me? You're a hologram. You can't even touch me.}
#{401}{}{I see I got a goddamn Klugschei遝r on my hands! You think I can't beat the piss out of a Warmduscher like you? Well, maybe I can't, but that's what the damn robots are for! Now I'm running out of patience real fast. You best start explaining yourself. How do I know you're not a Chinese spy?}

{400}{}{逮捕我？你只是一个*全息图像*而以，你甚至连碰我都办不到！}
{401}{}{警卫！进来！你以为我不能像你那样把有体温的人打出屎来是吗？[过了好一会，外面没有任何动静]干！警卫！警卫！[还是没有动静，他愣了一下]这些该死的机器人！听着！现在我快没有耐心了。你最好现在就开始解释，我怎么知道你不是中国间谍？}


#added in RP 2.1 - if you already repaired the computer before talking to him
#{410}{}{You the one that brought the robot control computer back online?}
#{411}{}{That's right.}
#{412}{}{Uh...maybe.}
#{413}{}{Nope. Wasn't me.}
#{420}{}{Quatsch! You're the only flesh and blood being around, so I damn well know it was you.}
#{421}{}{Alright, fine, it was me.}

{410}{}{你是把机器人控制电脑重新连网的那个人吗？}
{411}{}{没错。}
{412}{}{嗯...也许吧。}
{413}{}{不，不是我。}
{420}{}{撒谎！除了动物园你是这里唯一的有体温的人型生物体，所以我知道那是你。}
{421}{}{好，好，是我。}