# Message file for Toaster.ssl 
# Number of nodes: 7

#{100}{}{You see A dull silver toaster sitting on a desk.}
#{101}{}{You see The Brave Little Toaster.}
#{102}{}{BLT, your chirpy, if slightly annoying, breakfast companion.}

{100}{}{你看到在桌子上有一个闪着光的银色烤面包机。}
{101}{}{你看到"神勇"小面包机}
{102}{}{你看到BLT，活泼的"神勇"小面包机，你的早餐伙伴。}

# Node  0  [Node001]
#{200}{}{Howdy Doodley-Do! I'm The Brave Little Toaster, your chirpy breakfast companion. But you can just call me BLT. Say, would anybody like any toast?}
#{201}{}{No thanks, but I do want some information.}
#{202}{}{Not now, I need to be going.}

{200}{}{你好！我是"神勇"小面包机，你活泼的早餐伙伴。但是你可以叫我BLT，有人要烤面包吗？}
{201}{}{不，谢谢，但我确实想要一些信息。}
{202}{}{现在不需要，我要离开一下。}

# Node  1  [Node002]
#{210}{}{No, problem! I'm red hot in quantum mechanics, submolecular biology and TV theme tunes. Ask me anything. First though, may I ask you a question?}
#{211}{}{I guess so. What can I do for you?}

{210}{}{没有问题！我在量子力学、亚分子生物学和电视主题曲分数都是A的。你可以问我任何东西。但首先，我可以问你一个问题吗？}
{211}{}{我想是这样。我能为您做些什么？}

# Node  2  [Node003]
#{220}{}{Are you sure you won't have some toast?}
#{221}{}{NO! I don't want any toast. No muffins, no teacakes. No buns, baps, baguettes or bagels. No croissants, no crumpets, no pancakes, no potato cakes and definitely, no smegging flapjacks!!!}

{220}{}{你确定你不要来一片烤面包吗？}
{221}{}{不！我不要烤面包片，不要松饼，不要茶点饼干，不要圆面包，小面包，法式长棍面包或百吉饼，不要羊角面包，不要松脆饼，不要煎饼，不要土豆蛋糕，当然也不要烤薄饼！！！}

# Node  3  [Node004]
#{230}{}{Ah! So you're a waffle man!}
#{231}{}{Oh, I've had enough of this.}
#{232}{}{[You smack your head in frustration.] I've got to be going. I... I just have to be somewhere. Anywhere other than here.}

{230}{}{啊，所以你现在想要的是一块华夫饼！}
{231}{}{哦，我受够了。}
{232}{}{[你在沮丧中拍了拍你的头]我得走了，我必须在某个地方，任何不是这里的地方。}


# Node  4  [Node005]
#{240}{}{No, wait. I'm sorry. I'm not just a one-dimensional toast obsessed appliance. What can I do for you?}
#{241}{}{I just need some information about this place. What can you tell me about it?}

{240}{}{别，等等。我很抱歉，我并不是一个单纯的烤面包迷，我能为你做什么？}
{241}{}{我只是需要一些关于这个地方的信息。你能告诉我些什么吗？}


# Node  5  [Node006]
#{250}{}{I can tell you one thing: this is a terrible place for someone of my toast making expertise. Did you know that it's
 been well over a century since I had the pleasure of making toast for someone? You're the first toast consumer to come
 through here since the war, and, here's the real kicker: were you to actually request toast, I'm not even sure I'd be up
 for the task. You see, I'm feeling a little under the weather inside. It's rather embarrassing, really.}
#{251}{}{That's, uh, quite tragic. So, why are you here?}
#{252}{}{I see. Thanks for your time.}

{250}{}{我可以告诉你一件事：“这是一件让烤面包专业人士很尴尬的事情”。你知道吗？我已经有一个多世纪没有享受为家庭烤面包的乐趣了。战争结束后，你是第一个来这里烤面包的人。事实上，如果你真的要我烤一片面包，我甚至不确定能不能办到。你看，我觉得心里有点不舒服，这相当尴尬，真的。}
{251}{}{嗯，很悲剧。你为什么在这里？}
{252}{}{我明白了，谢谢你和我交谈。}



# Node  6  [Node007]
#{260}{}{I think he had a consignment of gas masks brought in before the accident. Some people even said that it was his errors that caused the problem in the first place.}
#{261}{}{So, why are you here?}
#{262}{}{Thanks for the information.}

{260}{}{我想他在事故发生前带了一批防毒面具。有些人甚至说，是他的错误导致了这个问题的出现。}
{261}{}{那么，你为什么在这里？}
{262}{}{谢谢你和我交谈。}

# Node  7  [Node008]
#{270}{}{Why, to make your mornings as cheerful as they can be! Say, after all this talking you wouldn't happen to have made some room
 in your stomach for some toast after all, have you?}
#{271}{}{I thought we got past this!! I'm not hungry and never will be. So, why are you REALLY here?}

{270}{}{为什么，为让你的早晨快乐起来啊！说了这么多话之后，你有感觉要为你的胃填充一点烤面包吗？}
{271}{}{我以为我们已经谈这个了！！我不饿，也永远不会饿。那么，你为什么在这里？}


# Node  7  [Node008]
#{280}{}{Alright, no need to shout. Angry is never a good way to begin your day. I was created as a breakfast companion
 but I can also be used for lunch and dinner. There isn't a time of day when some toast wouldn't hurt. If you're asking
 why I happen to be sitting here with a wire hanging from my side, well, it seems Mr. Handy doesn't always live up to his
 namesake -- the bloke started breaking down right in the middle of my annual maintenance checkup. Of course, he scuttled off
 to a maintenance bay and left me hanging.}
#{281}{}{I see. Well, thanks for your time.}

{280}{}{好啦，好啦，没必要大喊大叫，生气永远不是开始一天的好方法。我被创造成一个早餐伙伴，当然，我也可以用在午餐和晚餐上，在一天里，吃一些吐司总是一件美好的事情，不是么。如果你问为什么我会在这里，事实上每年我都需要维护检查，而负责这一件事的"快乐"先生似乎出了点问题，然后他自己跑到维修区了，把我晾着这里，陪我的就只有我屁股后面的电线和那台不会说话的大铁块了。}
{281}{}{我明白了，好的，谢谢你和我交谈。}



#{290}{}{Not a problem. Do stop by again. Maybe then you'll be hungry.}
#{291}{}{I doubt it. Bye.}

{290}{}{如果你闲下来的话，你可以再过来，或者那时你会觉得饿了。}
{291}{}{也许吧，再见。}

#{300}{}{I knew you you'd be back. They always are. So, do you want any toast now?}
#{301}{}{I knew you you'd be back. They always are. And now that I'm fully functional again, I can make toast better than ever. So, do you want any toast now?}
#{302}{}{Not right now. I need to ask you something.}
#{303}{}{Nope. I must be going.}

{300}{}{我知道你会回来的，你现在要来一块面包吗？}
{301}{}{我知道你会回来的，现在我又恢复了功能，我可以做得比以前更好，你现在要来一块面包吗？}
{302}{}{不是现在，我需要问你个问题。}
{303}{}{不。我得走了。}


#{310}{}{Sure, what would you like to know? I hope it's about toast.}
#{311}{}{What is this place?}
#{312}{}{Nevermind. Bye.}

{310}{}{当然，你想知道什么？我希望它是关于烤面包的。}
{311}{}{这是什么地方？}
{312}{}{没什么事，再见}


#{350}{}{Hey, you fixed me! I knew Mr. Handy left the job unfinished. Now I feel better than ever! Thanks.}
#{351}{}{Sure, it's what I do. See you later.}
#{352}{}{Now hold on there. If you won't let me reward you with toast, then at least allow me give you a little tip. You
 know those slot machines you find in casinos? Well, I calculated a method that can jinx the machines out of their cash.
 I have an IQ of 6000, you know. When I'm not making toast, I like to ponder these kinds of things. For helping me out,
 I'll tell you these secret codes. Just use one of the machines like you normally would and...}
#{353}{}{[MORE]}
#{354}{}{...And that's all there is to it. You'll be rich in no time, eating toast to your heart's content.}
#{355}{}{Thanks. I appreciate this. So long.}

{350}{}{嘿，你修好了我！"快乐"先生没有做完这件事，现在我感觉比以前好多了！谢谢。}
{351}{}{当然，这是我所能做的。再见。}
{352}{}{[摇晃]如果你不让我为您烤面包，那至少让我给你一些别的方法报答你。在赌场里你有看到那些老虎机吗？嗯，我计算出了一种方法，可以轻松地让老虎机吐出现金来。你知道吗，我的智商是6000，在我不烤面包这段时间里，我一直思考这件事情。让我来告诉你这些方法吧，就像这样，你平常使用一台机器...如何如何...这般这般}
{353}{}{[更多]}
{354}{}{...这就是全部，你很快就会发财的了。}
{355}{}{谢谢，我没想到...在这么长时间里...你...}

#{400}{}{You successfully repair the toaster.}
#{401}{}{You fail to repair the toaster.}
#{402}{}{The toaster is already repaired.}
#{403}{}{ successfully repairs the toaster.}
#{404}{}{ fails to repair the toaster.}

{400}{}{你成功地修理了"神勇"小面包机。}
{401}{}{你没有修理"神勇"小面包机。}
{402}{}{"神勇"小面包机已经修理好了。}
{403}{}{成功地修理了"神勇"小面包机。}
{404}{}{ 未能修理"神勇"小面包机。}