#{200}{}{If I tie some rope to this I could probably climb down there.}
#{201}{}{Some rope would definitely be useful here.}

#{300}{}{That should do it.}
#{301}{}{I already placed the rope.}
#{302}{}{You tie the rope to one of the bars of the vent and drop the rest of the rope down. You hear a thud as it hits
 the bottom.}

#{400}{}{You enter one of the EPA's ventilation systems. You can hear various insects scurrying about.}


{200}{}{如果我有一根绳子的话，或者我能顺着它爬下通风口。}
{201}{}{如果有绳子的话，在这里肯定有用。}

{300}{}{这样做应该可以了。}
{301}{}{绳子已经绑好了。}
{302}{}{你把绳子系在通风口的一根栏杆上，然后把剩下的绳子放下去。过了一会，你听到砰的一声，看来绳子已经到了底部。}

{400}{}{你进入EPA的通风系统，你可以听到各种昆虫在四处乱窜。}
