#{100}{}{You see a functional computer.}
#{101}{}{You see the EPA's botany terminal.}

{100}{}{你看见一台计算机。}
{101}{}{你看见EPA生物学电脑终端。}

#{200}{}{Welcome to the EPA's botany terminal. Please select one of the following options.}
#{201}{}{Access information database.}
#{202}{}{Access seed storage.}
#{203}{}{Log off.}

{200}{}{欢迎使用EPA生物学中央电脑。请输入命令。}
{201}{}{查找资料数据。}
{202}{}{查找种子库。}
{203}{}{[离线]}


#{210}{}{There are currently two databases available for viewing. Please make your choice below.}
#{211}{}{Access file on crop rotation.}
#{212}{}{Access file on botany.}
#{213}{}{Access file on animal and biological testing.}
#{214}{}{Back.}

{210}{}{当前有两个数据可以查看。请选择。}
{211}{}{阅读有关轮作的文件。}
{212}{}{阅读有关植物学的文件。}
{213}{}{查找有关动物和生物学实验的文件。}
{214}{}{返回。}


#{220}{}{Crop rotation avoids a decrease in soil fertility, as growing the same crop repeatedly in the same place
 eventually depletes the soil of various nutrients. A crop that leaches the soil of one kind of nutrient is followed
 during the next growing season by a dissimilar crop that returns that nutrient to the soil or draws a different ratio
 of nutrients.}
#{221}{}{[MORE]}
#{222}{}{Crop rotation is also used to control pests and diseases that can become established in the soil over time.
 Plants within the same family tend to have similar pests and pathogens. By regularly changing the planting location,
 the pest cycles can be broken or limited.}
#{223}{}{Back}

{220}{}{轮作减少了因重复在一块土壤上种植一种农作物而使土壤肥度下降到最终耗尽土壤的营养物质。一种农作物消耗了土壤的一类营养后，到下季种上另一种农作物时这类营养又会慢慢恢复，如此反复可更有效利用土壤。}
{221}{}{[更多]}
{222}{}{轮作也用于控制害虫和疾病，同类植物有相似的害虫和病原体。有规律的改变种植农作物类型，能阻止和限制害虫生长和疾病扩散。}
{223}{}{返回}


#{230}{}{Botany is the scientific study of plant life. As with other life forms in biology, plant life can be studied
 from different perspectives, from the molecular all the way up to individual plants themselves. A good understanding of
 plants is crucial to our future as it allows us to:

 -Produce food to feed an expanding population.
 -Understand fundamental life processes.
 -Produce medicine and materials to treat diseases and other ailments.
 -Understand environmental changes more clearly.

  The rest of the information appears to be various charts, graphs, and pictures of cross sections of plants.}
  
#{231}{}{Download information to a holodisk.}
#{232}{}{Back}

{230}{}{植物学是科学的学习和了解植物，是生物学中的一个学科。它从不同角度分析植物，从分子到植物本身。了解植物对于人类的未来是至关重要的，因为它允许我们：
-生产食物以养活不断增长的人口。
-了解生命的基本过程。
-生产治疗疾病和其他疾病的药品的原料。
-更清楚地了解环境变化。
其余部分是大量表格，曲线图，以及植物的横截面图片。好复杂...}
{231}{}{下载资料到磁盘。}
{232}{}{[返回]}



#{240}{}{This facility has been the site of various experiments on various animal and plant life forms. Extensive testing has been
 done on the a plant-like life form known as a spore plant and some animal-like creatures known as Centaurs, Floaters, and Radscorpions.}
#{241}{}{Read about plant experiments.}
#{242}{}{Read about Spore Plants.}
#{243}{}{Read about Centuars and Floaters.}
#{244}{}{Read about Radscorpions.}

{240}{}{这个设施是各种动物和植物生命形态的实验地点。广泛的测试包括普通的农作物、类似植物的孢子植物，而动物类如多足怪，浮游特和辐射蝎也都进行了大量的实验。}
{241}{}{阅读关于农作物的实验资料。}
{242}{}{阅读关于孢子植物的资料。}
{243}{}{阅读关于多足怪和浮游特的资料。}
{244}{}{阅读关于辐射蝎的资料。}


#{250}{}{Various experiments have been conducted to grow new plant life. Several of these attempts have been successful
 and can now be seen growing in a healthy state in the arboretum. Storage tanks currently indicate seed samples are still available for further testing.}
#{251}{}{A spore plant is a mutated form of some Venus-fly-trap-like plant. Additional testing has shown the plant is quite
 aggressive and has two forms of attacking. One is a spore which it spits at its enemies. The other form is a bite with its thorned maw.
 Great caution is suggested when handling and working with these life forms.}
#{252}{}{After extensive testing, Centaurs appear to be the by-product of the Forced Evolutionary Virus. They seem to be
 a mixture of dog, cat, brahmin, and other animals. FEV isn't the only cause of the mutation, however, as radiation also
 appears to have played a role. They seem to prefer living in a heavy radiated environment and as such they radiate everything around them.}
#{253}{}{[MORE]}

{250}{}{经过各种实验后我们培育出了一些新的农作物品种。其中一些品种很成功，现在可以在植物园里健康的生长。储藏罐显示当前还有很多种子样本。}
{251}{}{孢子植物是从某种捕蝇草类的植物变异而成了。另一些试验表明这些植物非常好斗，他们有两种攻击方式：一种是把带有自己孢子的尖刺喷射到敌人身上。另一种就是用长满荆棘的口状物咬敌人。在处理和研究这些植物时要特别谨慎！}
{252}{}{经过大量实验表明，多足怪似乎是某种动物受FEV病毒影响的副产物。他们看起来融合了狗、猫、双头牛和一些其他动物的基因。FEV并不是导至这类变异的唯一原因，辐射可能也起了很大的作用，而且多足怪似乎更愿意生活在高辐射的环境里。}
{253}{}{[更多]}

#{254}{}{The origin and etymology of Floaters are unknown but they are thought to be related to the Centaurs with which they are often found.
 They too appear to be the result of FEV. Additional testing has shown them to be completely immune to electrical damage.}
#{255}{}{Radscorpions are an extremely large version of the North American Emperor scorpion, mutated by radiation.
 Contrary to initial expectations, their poison grew more potent, not diluted. They are nocturnal and sensitive to light.
 Further testing has shown that samples of poison from their tails can be used to make antidotes.}
#{256}{}{Back}
#{257}{}{Various experiments have been conducted to grow new plant life. Several of these attempts have been successful
 and can now be seen growing in a healthy state in the arboretum. Storage tanks currently indicate there are no more seed samples available for further testing.}
 
{254}{}{浮游特的起源现在都是未知的，但是它们好像和多足怪有某种联系，因为它们通常都能在同一地方被找到。它们似乎也是FEV影响的结果，一些实验表明它们对电有免疫，电对它们造成不了什么伤害。}
{255}{}{辐射蝎就像是超大版本的北美帝王蝎，已经明确是辐射使它们变异的。但和最初预期的不同，它们的毒变得更强，而不是变弱。它们是夜行动物对光很敏感，在后期的试验中，我们发现它们的蝎毒也可以用于制造解毒剂。}
{256}{}{返回}
{257}{}{经过各种实验后我们培育出了一些新的农作物品种。其中一些品种很成功，现在可以在植物园里健康的生长。储藏罐显示当前已经没有种子样本可以用于以后的试验。}


#{260}{}{Current EPA storage containers report there are seeds remaining in Storage Tanks One and Two.}
#{261}{}{Current EPA storage containers report there are seeds remaining in Storage Tank Two.}
#{262}{}{Current EPA storage containers report there are seeds remaining in Storage Tank One.}
#{263}{}{Current EPA storage containers report there are no more seeds remaining in any of the Storage Tanks.}
#{264}{}{Access Storage Tank One.}
#{265}{}{Access Storage Tank Two.}
#{266}{}{Back}

{260}{}{当前EPA储藏罐报告显示：储藏罐1和储藏罐2里还储藏着很多种子样本。}
{261}{}{当前EPA储藏罐报告显示：储藏罐2里还储藏着很多种子样本。}
{262}{}{当前EPA储藏罐报告显示：储藏罐1里还储藏着很多种子样本。}
{263}{}{当前EPA储藏罐报告显示：所有储藏罐里都没有任何种子样本了。}
{264}{}{打开储藏罐1。}
{265}{}{打开储藏罐2。}
{266}{}{返回}

#{270}{}{Storage Tank One reports 5 remaining packets from the U.S. Food Enhancement Program. Seeds from corn plants were genetically modified
 to be immune to disease and insect infestation.}
#{271}{}{Storage Tank Two reports 2 remaining seed packets, each of similar or different families. No research has been conducted and the outcome of seed germination is unknown.}
#{273}{}{Retrieve seeds.}

{270}{}{储藏罐1显示有5包来自美国粮食增产项目的样本种子。种子大多是玉米和小麦的改良品种，可以有效免疫病虫害。}
{271}{}{储藏罐2显示有2包来自中国农业科学院最新成果“BN13号”超级杂交水稻的基因改良版种子样本，特点是超高产，免疫各种病虫害，适应各种气候。哇塞...}
{273}{}{取出种子。}

#{280}{}{Collecting seed samples...Successfully collected 5 packets of genetically modified corn seeds. Depositing packets to collection container...Success...
 Closing storage container...Success.}
#{281}{}{Collecting seed samples...Successfully collected 2 packets of unknown seeds. Depositing packets to collection container...Success...
 Closing storage container...Success.}
 
{280}{}{收集种子...成功收集到5包美国粮食增产项目的种子。种子下降到收集箱...成功...关闭收集箱...成功}
{281}{}{收集种子...成功收集到2包“BN13号”超级杂交水稻种子。种子下降到收集箱...成功...关闭收集箱...成功}

#{290}{}{Downloading Botany database to a holodisk...75% complete...Finished. Please remove the disk and return to the menu.}
#{291}{}{Back}

{290}{}{下载植物学资料到磁盘1%...15%...75%...100%...完成...，请取出磁盘返回主菜单。}
{291}{}{返回}