#{100}{}{This door is locked.}
#{101}{}{You see a locked door, preventing any further access.}
#{102}{}{You see a sturdy-looking door.}
#{103}{}{The door is now unlocked.}
#{104}{}{This door is already unlocked and open.}
#{105}{}{You fail to unlock the door.}
#{106}{}{The lock is now jammed.}
#{107}{}{The door is now locked.}
#{108}{}{You fail to lock the door.}


{100}{}{这扇门是锁着的。}
{101}{}{你看到一个锁着的门，阻止任何人的进入。}
{102}{}{你看到一扇看起来很坚固的门。}
{103}{}{门现在看起来被打开了。}
{104}{}{这扇门已经打开了。}
{105}{}{你没有打开门。}
{106}{}{这个锁现在卡住了。}
{107}{}{门现在锁上了。}
{108}{}{你没有锁上门。}
