#{100}{}{You see an old, rusty fan.}
#{101}{}{You could easily jam this fan with some piece of metal.}
#{102}{}{There is a metal pole jamming the fan.}

#{200}{}{You jam the pole into the fan. You hear scraping of metal and the fan comes to a stop. It makes a clunking
 noise as it tries to spin its now jammed blades.}

{100}{}{你看到一个生锈的风扇，它看起来好像没什么动力的样子}
{101}{}{如果有些足够硬的东西，你应该能把这个风扇卡住。}
{102}{}{有一个铁杆卡住了风扇。}

{200}{}{你把铁杆塞进风扇里，你听到沉闷的金属刮擦声，风扇停了下来。} 
 