#{100}{}{You see a peculiar machine.}
#{101}{}{The machine that controls the hologram projection for the hologram in this room.}

#{103}{}{A fault in the machine is found and quickly fixed.}
#{104}{}{This machine is already fixed.}
#{105}{}{Looks like there was interference occurring which caused the hologram's speech to become garbled.}

#{106}{}{Fixing this machine seems too complicated.}
#{107}{}{What am I looking for here?}
#{108}{}{Damn. This too hard for me. Repair just isn't my forte.}
#{109}{}{Damn, even with these tools this is too hard for me. Repair just isn't my forte.}



{100}{}{你看到一个奇怪的机器。}
{101}{}{在这个房间里，这台机器负责控制全息图的投影工作。}

{103}{}{机器的故障已经被找到且修复了。}
{104}{}{这台机器已经修好了。}
{105}{}{看起来好像有干扰，使全息图的讲话变得含糊不清。}

{106}{}{修理这台机器似乎太复杂了。}
{107}{}{我在这里找什么?}
{108}{}{该死，这对我来说太难了，修理不是我的专长。}
{109}{}{该死，即使有这些工具，这对我来说仍然是太难了，修理不是我的专长。}
