#{100}{}{Data Storage and Maintenance. Select Option.}
#{101}{}{Run Diagnostic Check.}
#{102}{}{[DONE]}
#{103}{}{Running Check... Initiating...Compiling...Thank you for being patient during this procedure...Complete. Data storage running at 84% efficiency. Wiring fault on this computer's mainframe is causing magnetic coils to run at a high power. The resulting magnetic field could cause interference with other devices if not fixed. End check.}
#{1030}{}{Running Check... Initiating...Compiling...Thank you for being patient during this procedure...Complete. Data storage running at 100% efficiency. Thank you and have a nice day. End check.}
#{104}{}{[DONE]}
#{105}{}{You see a computer}
#{106}{}{You see the EPA Data Storage Computer.}
#{107}{}{You see a computer which ensures data is properly and securely stored in the EPA.}
#{108}{}{Got it!}
#{109}{}{The magnetic coil problem has been fixed.}


{100}{}{感谢你登录数据存储和维护计算机，请选择选项。}
{101}{}{运行检查程序。}
{102}{}{[结束]}
{103}{}{运行检查...初始化编译完成...感谢您在这一过程中耐心的等待。检查结果：数据存储效率为84%。计算机主机线路故障，电磁线圈功率过高，磁场生成混乱。结论：可能会引起干扰其他设备，检查结束。}
{1030}{}{运行检查...初始化编译完成...感谢您在这一过程中耐心的等待。检查结果：数据存储服务正以100%的效率运行。感谢你，祝你今天愉快，检查结束。}
{104}{}{[结束]}
{105}{}{你看见一台计算机。}
{106}{}{你看到EPA的数据存储管理计算机。}
{107}{}{你看到一台计算机，它的作用是确保数据正确并安全地存储在EPA。}
{108}{}{搞定！}
{109}{}{电磁线圈的问题已经被解决了。}