#{100}{}{You see a peculiar machine.}
#{101}{}{You see the Hologram 00000 backup projector.}
#{102}{}{You see a machine for projecting only the Hologram of Science.}
#{103}{}{The fault in the machine has been fixed.}
#{104}{}{This machine is working fine already.}

#{105}{}{Fixing this machine seems too complicated.}
#{106}{}{What am I looking for here?}
#{107}{}{Even with your tools, you don't have the skills necessary for fixing this machine.}


{100}{}{你看到一个奇特的机器。}
{101}{}{你看到了全息图00000号备份投影仪。}
{102}{}{你看到的全息图像投影仪。}
{103}{}{机器的故障已经修好了。}
{104}{}{这台机器已经运转良好了。}

{105}{}{修理这台机器似乎太复杂了。}
{106}{}{我在这里对这台机器要做什么？？？}
{107}{}{即使你有工具，你也没有必要的技能来修理这台机器。}
