#{100}{}{You see a door.}
#{101}{}{You see an electronic door.}
#{102}{}{You see an electronic door with an override, voice activated, lock.}
#{200}{}{Confirm code:}
#{201}{}{XY104FD}
#{202}{}{BFN12}
#{203}{}{Open}
#{204}{}{Wheat}
#{205}{}{Abre}
#{206}{}{[END]}
#{300}{}{Incorrect door code. Locking door. Please contact the head of Public Relations for the override code.}
#{301}{}{[END]}
#{400}{}{Confirm override code.}
#{401}{}{[END]}
#{402}{}{This door is electronically locked.}
#{403}{}{Unlocking door. Thank you and have a pleasant day.}
#{404}{}{[END]}

#{500}{}{There is no lock to pick.}


{100}{}{你看到一扇门。}
{101}{}{你看到一个电子门。}
{102}{}{你看到一个电子门，有一个声音响起：门已经关闭并锁好。}
{200}{}{通行密码：}
{201}{}{XY104FD}
{202}{}{BFN12}
{203}{}{Open}
{204}{}{Wheat}
{205}{}{Abre}
{206}{}{[结束]}
{300}{}{密码错误，门会将锁死，请联系公共关系主管，以取得通行密码。}
{301}{}{[END]}
{400}{}{确认通行密码。}
{401}{}{[END]}
{402}{}{这门是使用电子锁的。}
{403}{}{门已经解锁，祝你愉快。}
{404}{}{[结束]}

{500}{}{没有锁可以选择。}