#{100}{}{Hello， welcome to the Environmental Protection Agency， commonly referred to as the EPA！ For your convenience，
 this terminal will provide you with descriptions of the various color coded areas that comprise our wonderful research
 facility。 Please select a level for which you would like more information。}
#{101}{}{SUB-LEVEL ORANGE}
#{102}{}{SUB-LEVEL RED}
#{103}{}{SUB-LEVEL YELLOW}
#{104}{}{SUB-LEVEL INDIGO}
#{105}{}{SUB-LEVEL VIOLET}
#{106}{}{SUB-LEVEL GREEN}
#{107}{}{SUB-LEVEL BLUE}
{100}{}{你好，欢迎来到环境保护局，通常被称为EPA！为了您的方便，这个终端将为您介绍此处出色的研究设施以及各种颜色分区的权限，请选择您希望获得更多信息的区域。}
{101}{}{SUB-LEVEL 橙。要退出请按[键盘数字8]}
{102}{}{SUB-LEVEL 红。要退出请按[键盘数字8]}
{103}{}{SUB-LEVEL 黄。要退出请按[键盘数字8]}
{104}{}{SUB-LEVEL 青。要退出请按[键盘数字8]}
{105}{}{SUB-LEVEL 紫。要退出请按[键盘数字8]}
{106}{}{SUB-LEVEL 绿。要退出请按[键盘数字8]}
{107}{}{SUB-LEVEL 蓝。要退出请按[键盘数字8]}


#{108}{}{Sub-level Orange contains the conference rooms where all the exciting decisions are made， a cafeteria where delicious food is served， and some hazardous chemicals。}
#{109}{}{Sub-level Red is home to our security department (so behave yourself！) and a small but informative museum。 Also， don't forget to purchase some snacks and stop by the public execution chamber！ [Disclaimer: Execution chamber may be unfit for children under the age of four。]}
#{110}{}{Sub-level Yellow houses the power supply rooms for our amazing new holograms， and it's also where you'll find everyone's favorite drug making appliance， Mr。 Chemmie！ [Notice: Due to limited storage space， we've moved some hazardous chemicals into this area， so watch your step！]}
#{111}{}{Sub-level Indigo is where our brilliant scientists are conducting some Top Secret Research！ Sounds exciting， doesn't it? Remember， any unauthorized visitors found on this level will be shot on sight。 So parents， don't let your children wander around unsupervised。}
#{112}{}{Sub-level Violet contains the memory core for storage of data in the EPA and other things that aren't of much interest to visitors。 Sorry！ However， it directly connects to Sub-level Yellow， which contains more interesting things， like the pharmacist of the future， Mr。 Chemmie！}
{108}{}{Sub-level 橙，包含作出所有令人兴奋决定的会议室，提供美味食物的自助餐厅和一些[不]危险的化学品。}
{109}{}{Sub-level 红，小红是我们安全部门的家[所以规矩点！]，这里包含一个小型但信息丰富的博物馆。还有，别忘了买些零食，到公共执行室去走走！[免责声明：执行室可能不适用于4岁以下儿童]}
{110}{}{Sub-level 黄，为我们令人惊叹的新产品提供动力的电源室，在这里你可以找到本地最受欢迎的糖果人，"点石成金"先生！[注意：由于储存空间有限，我们已经将一些有害的化学物质移进了这个区域，所以注意你的步骤！]}
{111}{}{SUB-LEVEL 青，我们杰出的科学家进行顶级的秘密研究的地方！听起来令人兴奋，不是吗？请记住，在这个级别的区别，任何未经授权的访客被发现将被射杀。所以，父母，不要让你的孩子在无人看管的情况下游荡。}
{112}{}{SUB-LEVEL 紫，包含了存储在EPA和其他对访客不太感兴趣的数据的处理核心。这个区域可能会有点无趣，对不起！但是，它直接连接到SUB-LEVEL 黄，这个区域包含了有趣得多的东西，例如未来的药剂师，"点石成金"先生！}


#{113}{}{Sub-level Green is an exciting level that contains an arboretum， biological weapon research， fascinating new creatures and， every child's favorite， our unique petting zoo。}
#{114}{}{Sub-Level Blue does not exist。 If someone told you otherwise， they're dirty liars and are most likely communist sympathizers。 Please report them to our security department on Sub-Level Red so they may be dealt with accordingly。 Thank you for doing your part as a proud American！}
#{115}{}{Return to main menu。}
#{116}{}{Thank you for using the location finder。}
{113}{}{SUB-LEVEL 绿，令人兴奋的区域，包含一个植物园。在这里我们进行生化武器的研究，这里有迷人的新生物，是每个孩子的最爱，我们独特的宠物乐园。}
{114}{}{SUB-LEVEL 蓝，这一层不存在，哈哈。如果你在同行中发现有可能的共产主义者。请通报我们的Sub-level 红，他们会作出处理，谢谢你做的每一件事，为了美利坚合众国！}
{115}{}{返回主菜单。}
{116}{}{感谢你使用EPA引路系统。}
{117}{}{[退出]}
{118}{}{你看到一台电脑。}
{119}{}{你看EPA的引路电脑。}
{120}{}{你看见一台可获取EPA各楼层信息的电脑。}
