#{100}{}{Force field control panel.}

#{200}{}{You successfully disable the force field.}
#{201}{}{You fail to disable the force field.}
#{202}{}{You successfully enable the force field.}
#{203}{}{You fail to enable the force field.}


#{210}{}{ disables the force field.}
#{211}{}{ fails to disable the force field.}
#{212}{}{ enables the force field.}
#{213}{}{ fails to enable the force field.}

#{300}{}{You have destroyed the computer.}

{100}{}{力场控制面板。}

{200}{}{你成功地禁用了力场。}
{201}{}{你禁用力场失败了。}
{202}{}{你成功地启用了力场。}
{203}{}{你地启用力场失败了。}


{210}{}{ 禁用力场。}
{211}{}{ 未能禁用力场。}
{212}{}{ 启用力场。}
{213}{}{ 未能启用力场。}

{300}{}{你已经破坏了计算机。}