#{100}{}{You see a modified Auto-Doc.}
#{101}{}{This Auto-Doc appears to have been modified to perform experimental appearance modifications.}

{100}{}{您看到一个被改造过的自动医生。}
{101}{}{这个自动医生似乎已经被改造过，可以执行基于身体的改造。}

#{200}{}{[The machine addresses you as you approach.] Welcome, Test Subject. Thank you for volunteering your flesh for
 science. Please, step inside me and we can begin.}
#{201}{}{Whoa, I never said I was volunteering anything. Now before I step anywhere, why don't you tell me exactly what you do?}
#{202}{}{[Shrug.] Alright. [Step into the device.]}
#{203}{}{You've got me confused with someone else. Bye.}

{200}{}{[在你靠近的时候，自动医生对你说话 "欢迎您，受试者，感谢您自愿参加科学测试，请进站到医疗平台上，我们马上可以开始了"]}
{201}{}{哇，我从没说过我要做什么志愿工作。在我走到任何地方之前，你为什么不告诉我你是要做什么？}
{202}{}{[耸耸肩]好吧。[进入设备]}
{203}{}{你把我弄糊涂了，再见。}

#{300}{}{Welcome back, Test Subject. Please, step inside me and we can begin.}
#{301}{}{Before I step anywhere, why don't you tell me exactly what you do?}
#{302}{}{Alright. [Step into the device.]}
#{303}{}{I don't think so. Bye.}

{300}{}{"欢迎您回来，受试者，感谢您自愿参加科学测试，请进站到医疗平台上，我们马上可以开始了"}
{301}{}{在我走到任何地方之前，你为什么不告诉我你是要做什么？}
{302}{}{好吧。[进入设备]}
{303}{}{我不想这么干，再见。}

#{400}{}{I'm the newest prototype of Auto-Doc technology, developed by Dr. Wood. I specialize in extreme body
 modification--the ultimate makeover. There's no need to be nervous, as my patient death rate is significantly lower
 than the previous prototype. Don't be shy, step inside me and we can begin.}
#{401}{}{You're not touching me. Bye.}
#{402}{}{I'd love to, but I really need to get going. Sorry.}
#{403}{}{Alright. [Step into the device.]}

{400}{}{我是由伍德博士最新开发的自动医生原型。我擅长对身体进行各类极端、极限的改造。没有必要紧张，因为比起之前的原型，我的病人死亡率要低得多。别害羞，站到我中间的医疗平台来，我们就可以开始了。}
{401}{}{你别碰我，再见。}
{402}{}{我很想去，但是我真的得走了，对不起。}
{403}{}{好吧。[进入设备]}

#{410}{}{Please make your selection. Due to being an early prototype, I can only offer you limited choices. Sorry.}
#{411}{}{Alter Gender.}
#{412}{}{Alter Race. (Currently only White to African American or vice versa).}
#{413}{}{Alter Hairstyle (Regular Hair).}
#{414}{}{Alter Hairstyle (Long Hair).}
#{415}{}{Alter Hairstyle (Bald).}
#{416}{}{Alter Hairstyle (Blond Hair).}
#{417}{}{On second thought, I don't really have time for this right now. Bye.}

#妈了个b的，英文自己少了一行418，操
{410}{}{请进行您的选择，由于我是仍然是一台原型机，我只能给你有限的选择，抱歉。}
{411}{}{改变性别}
{412}{}{改变肤色[目前的原型机只能为你改造为白种人或者黑种人]}
{413}{}{改变发型[普通头发]}
{414}{}{改变发型[长发]}
{415}{}{改变发型[秃]}
{416}{}{改变发型[迷人的金发]}
{417}{}{改变发型[热情的红发]}
{418}{}{我想现在我真的没有时间做这个。再见。}



#gender
#{500}{}{This procedure will take four weeks for you to recover and has a 50% chance of death. Do you wish to begin now?}
#{501}{}{Let's do it.}
#{502}{}{Yes. Finally, I can be the person I've always been on the inside.}
#{503}{}{Eh, maybe later. Bye.}
#{504}{}{Let me choose another procedure.}
#{505}{}{Hell no! I'm outta here!}

{500}{}{手术后需要四周时间进行恢复，有50%的死亡几率。你想现在就开始吗？}
{501}{}{开始吧。}
{502}{}{是的。我相信我会是活下来的那个人。}
{503}{}{嗯，过几天再说吧，再见。}
{504}{}{让我选择其它程序。}
{505}{}{不！让我离开这里！}


#race
#{510}{}{Excellent choice. This procedure will take two weeks for you to recover and has a 25% chance of death. Do you wish to begin now?}
#{511}{}{Let's do it.}
#{512}{}{Yes. Finally, I can be the person I've always been on the inside.}
#{513}{}{Eh, maybe later. Bye.}
#{514}{}{Let me choose another procedure.}
#{515}{}{Hell no! I'm outta here!}

{510}{}{明智的选择，手术后需要两周时间进行恢复，有25%的死亡几率。你想现在就开始吗？}
{511}{}{开始吧。}
{512}{}{是的，我相信我会是活下来的那个人。}
{513}{}{嗯，过几天再说吧，再见。}
{514}{}{让我选择其它程序。}
{515}{}{不！让我离开这里！}

#hair style
#{520}{}{Excellent choice. This procedure will take one day for you to recover and has a 1% chance of death. Do you wish to begin now?}
#{521}{}{Let's do it.}
#{522}{}{Yes. Finally, I can be the person I've always been on the inside.}
#{523}{}{Eh, maybe later. Bye.}
#{524}{}{Let me choose another procedure.}
#{525}{}{Hell no! I'm outta here!}

{520}{}{明智的选择，手术后需要一天时间进行恢复，只有1%的死亡几率。你想现在就开始吗？}
{521}{}{开始吧。}
{522}{}{是的，我相信我会是活下来的那个人。}
{523}{}{嗯，过几天再说吧，再见。}
{524}{}{我选择其它程序。}
{525}{}{不！让我离开这里！}

#{600}{}{Congratulations! The experiment was a success. Thank you, and enjoy the new you.}
#{601}{}{[Exit.]}

{600}{}{恭喜你！手术成功了，请享受全新的你。}
{601}{}{[退出]}

#{650}{}{I'm sorry, this particular procedure is not currently available for females.}
{650}{}{很抱歉，这个特殊的程序目前还不能用于女性。}


#{700}{}{I'm sorry, but something went terribly wrong with the procedure. We apologize for this inconvenience, but thank
 you for volunteering for the sake of science.}
#{701}{}{Oh, shit...}

{700}{}{我很抱歉，但是程序出了点"小"问题。很抱歉给您带来不便，感谢你为科学献身。}
{701}{}{Oh, shit...}