#{100}{}{You see a terminal.}
#{101}{}{You see a forcefield control unit.}
#{200}{}{Forcefield control terminal. Enter command:}
#{201}{}{Disable forcefield.}
#{202}{}{Exit.}
#{203}{}{You fiddle with the interface to no avail. You feel sure you could crack it with higher skills.}
#{204}{}{[After several minutes of tinkering, a countdown of 5 seconds is displayed along with a message.] Releasing specimens...}



{100}{}{你看到一个终端机。}
{101}{}{你看到力场控制终端机。}
{200}{}{力场控制终端，请输入命令：}
{201}{}{[禁用力场]}
{202}{}{[离开]}
{203}{}{你摆弄这个接口没用，你需要用更高的科学水平才攻克难关。}
{204}{}{[经过你几分钟的操作之后，终端屏幕上出现了一个5秒的倒计时，并显示一个消息] 释放标本...}