#{100}{}{You see a computer.}
#{101}{}{You see the EPA's museum computer.}

{100}{}{你看到一台计算机。}
{101}{}{你看到EPA的博物馆终端。}

#{200}{}{Welcome to the EPA's museum! This terminal will project a movie using exciting new holographic technology!
 The movie is an entertaining and informational look at the scary, but possible, reality of a post-nuclear world.}
#{201}{}{[Play movie.]}
#{202}{}{[Logoff.]}

{200}{}{欢迎来到EPA的博物馆！这个终端将使用令人兴奋的新全息技术播放电影！你看到的这部电影将让我们看到可能的未来，并用娱乐和信息的角度看待核战后世界。}
{201}{}{[播放影片]}
{202}{}{[退出]}



#{210}{}{[The terminal projects a hologram of a tall bespectacled man in a lab coat. He waves and gives you a friendly smile.]
 Hello, I'm Dr. Caleb, and I'll be hosting this holographic video on a post-holocaust America.}
#{211}{}{[MORE]}

{210}{}{[终端投影出一份全息图像] 一个高大、戴眼镜的人，穿着实验室的外套，他挥了挥手，给你一个友好的微笑。您好，我是迦勒博士，我将主持一个关于核战后美国的全息视频。}
{211}{}{[继续]}

#{220}{}{[A living room materializes around Dr. Caleb, where a family appears to be relaxing for the evening. Dr. Caleb
 pats the head of the family dog, then smiles at you.] Meet the Johnsons. They're your average American family. Dad smokes
 his pipe, Mom reads her cook book, and little Billy and Susie catch some boob-tube before bedtime. They think everything
 will be just fine. They ignore the warning sirens, thinking that it's just another drill. Oh, but what's this?}
#{221}{}{[MORE]}

{220}{}{[一个客厅的全息影像在你的周围出现] 这是约翰逊一家，他们是普通的美国家庭。一个普通晚上，爸爸在抽他的烟斗，妈妈读她的烹饪书，小比利和苏茜在睡觉前抓了一大把糖果，他们认为一切都很好[迦勒博士拍了拍全息图里宠物狗的头，然后对你微笑]。但是，他们忽略了警报，认为这只是一个演习。哦，但这是什么？}
{221}{}{[继续]}


#{230}{}{[Through the back window, you see a large bomb crash to the earth, creating a massive mushroom cloud explosion,
 followed by a blinding light. Once the light fades away, you see Dr. Caleb is now standing in the burnt ruins of the
 living room, with the family replaced by skeletons.] Uh-oh! It looks like the commies dropped the big one, and the
 Johnsons weren't quite as safe as they thought. Now, what can we learn from the Johnson family's mistake?}
#{231}{}{[MORE]}

{230}{}{[在客厅后面的窗户里，你看到一个巨大的炸弹坠落下来，扬起巨大的蘑菇云，接着是耀眼的闪光。闪光消失后，你看到迦勒博士正站在燃烧的废墟中，原本客厅中的人已经变成了骷髅] 喔！看起来共产党员们丢下了那个大家伙，约翰逊一家并不像他们想的那样安全。现在，我们能从约翰逊一家的错误中学到什么呢？}
{231}{}{[继续]}

#{240}{}{That's right! In the event of a nuclear war, you want your family to be safe within the shelter of a Vault-Tec
 brand vault. Vault-Tec have constructed 122 public vaults around our great nation, so there's bound to be one near you.
 As you can imagine, space is very limited, so reserve your space today, or else *your* family might end up like the
 Johnsons here. [Dr. Caleb pats the head of the skeletal dog. The skull detaches from the body and hits the floor,
 shattering. A Mr. Handy robot hovers over and sweeps up the skull fragments.]}
#{241}{}{[MORE]}

{240}{}{没错！在发生核战争的情况下，您会希望你的家人能在一个坚固的地下掩体安全度过。避难所科技[Vault-Tec]在我们伟大的国家建造了122个公共避难所，所以肯定会有一个在你附近。空间是非常有限的，所以今天就开始预订你的空间，*否则*你的家可能会变成这样。[迦勒博士拍了一下宠物狗已经成了骷髅的头，头在地板上撞得粉碎。一个"巧手管家"机器人移动了过来，打算把头骨碎片扫起来]}
{241}{}{[继续]}

#{250}{}{It looks like Mr. Handy's going to have his work cut out for him if he plans to clean up *this* mess. [Dr. Caleb
 laughs as the image fades away and is replaced by text.] Thank you for watching. This educational video was brought to
 you by the fine folks at Vault-Tec. Vault-Tec, America's Final Word in Homes.}
#{251}{}{[Logoff.]}

{250}{}{看起来"快乐先生"非常尽职于它的工作。 [当图像消失并被文本代替时，迦勒博士笑着说] 感谢您的收看，避难所--美国家庭的最终代名词。}
{251}{}{[退出]}