#{100}{}{Sorry my non two-legged friends. You're going to have to wait up here for me.}
#{101}{}{Sorry my non two-legged friend. You're going to have to wait up here for me.}
#{102}{}{You see a broken elevator shaft.}
#{103}{}{This elevator is broken. With some effort, you could probably make your way to the bottom.}



{100}{}{抱歉，我不是两条腿的朋友，你得在这儿等我。}
{101}{}{抱歉，我不是两条腿的朋友，你得在这儿等我}
{102}{}{你看到一个坏了的电梯井。}
{103}{}{这个电梯坏了，如果有条绳子的话，或许你能顺着它爬到下面去。}