#{100}{}{Electric Chair Computer Station: Select an option.}
#{101}{}{Empower Electric Chair.}
#{102}{}{Disempower Electric Chair.}
#{103}{}{Chair empowered. Please encourage person to move as close to chair as possible from either side. Thank you.}
#{104}{}{Chair disempowered.}
#{105}{}{Exit.}
#{106}{}{You see a computer whirring to itself.}
#{107}{}{You see the Electric Chair Computer.}
#{108}{}{You see a computer controlling the electric chair.}


{100}{}{感谢您使用电椅控制终端，设备检测开始...设备正常，请选择一个选项。}
{101}{}{电椅通电。}
{102}{}{电椅离电。}
{103}{}{椅子已通电，请鼓励受试者尽可能靠近椅子，感谢您的支持。}
{104}{}{电椅离电。}
{105}{}{[退出]}
{106}{}{你看见一台计算机。}
{107}{}{你看到电椅控制终端。}
{108}{}{你看到一台计算机，它负责控制电椅的开关。}
