#{100}{}{Welcome to the EPA Robot Control Computer. What do you wish to do?}
#{101}{}{Command Robots.}
#{102}{}{Run diagnostic check.}
#{103}{}{Leave.}
#{104}{}{!ERROR! !ERROR! PROBLEM ENCOUNTERED TERMINATING SEQUENCE!}
#{105}{}{Return to Main Menu}
#{106}{}{Diagnostic Check...circuit board error....section four...loose wiring.}
#{107}{}{Done}
#{108}{}{It's too difficult to repair this.}
#{109}{}{The fault in the computer is repaired and the machine is brought back online.}
#{110}{}{Welcome to the EPA Robot Control Computer. You no longer have security authorization to use these files. Terminating sequence.}
#{111}{}{DONE}
#{112}{}{BEEP!}
#{113}{}{BOOP!}
#{114}{}{Bzzzt..}
#{115}{}{You already repaired it.}


{100}{}{欢迎来到EPA机器人控制计算机。你想做什么?}
{101}{}{指挥机器人。}
{102}{}{运行诊断检查。}
{103}{}{[离开]}
{104}{}{错误！错误！终止序列！}
{105}{}{返回主菜单}
{106}{}{诊断检查……电路板错误……第四部分……电线松散。}
{107}{}{结束}
{108}{}{这太困难了。}
{109}{}{电脑上的故障被修复了，机器又重新回到了网上。}
{110}{}{欢迎来到EPA机器人控制计算机，您不具有使用这些文件的安全授权，终止序列。}
{111}{}{结束}
{112}{}{BEEP!}
{113}{}{BOOP!}
{114}{}{Bzzzt..}
{115}{}{你已经修好它。}