#{100}{}{You see a vigilant Shi guard.}
#{101}{}{This scowling man appears to be guarding the motorboat. He seems to be taking his job very seriously.}

{100}{}{你看到一个警惕的始族守卫。}
{101}{}{这个人似乎在保护旁边的船，看起来他对这份工作很认真。}

#{200}{}{[He eyes you suspiciously.] Help you with something?}
#{201}{}{Nope. I'm all set. Bye.}
#{202}{}{I was just wondering what you're doing.}
#{203}{}{Say, that's a nice boat you got there. Does that thing still work?}
#{204}{}{Me ride metal fishy-fish?}

{200}{}{[他的眼睛盯着你] 你有什么事吗？}
{201}{}{没什么事，我只是路过。}
{202}{}{我只是想知道你在这里是做什么的。}
{203}{}{你旁边那条船真不错，它还能动吗？}
{204}{}{我能骑铁鱼鱼吗？}


#{210}{}{None of your business, outsider. Piss off.}
#{211}{}{Poor choice of words, asshole. They're gonna be your last.}
#{212}{}{I can take a hint. No need to be a dick about it. Bye.}
#{213}{}{Whatever you say, buddy.}

{210}{}{不关你的事，外人，走开。}
{211}{}{糟糕的对话选择，这会是你说的最后一句话，混蛋。}
{212}{}{我可以给你一个提示。没有必要成为一个混蛋。再见。}
{213}{}{无论你说什么，老兄。}


#{220}{}{[He looks at you as if you're dumbest creature he could possibly imagine. Slowly, he shakes his head.] You no ride metal fishy-fish. You go. You go, or I shoot. Understand?}
#{221}{}{Okie, bu-bye!}
#{222}{}{You meanie-man. Me smash meanie-man!}

{220}{}{[他看着你好像你是他能想象的最愚蠢的生物。过了一会，他摇了摇头]不，你不能骑铁鱼鱼，离开，不然我开枪。}
{221}{}{好，再见！}
{222}{}{你是一个吝啬鬼，我打吝啬鬼！}


#{230}{}{[The guard grips his weapon and glares at you wordlessly.]}
#{231}{}{Can I borrow your boat for a minute?}
#{232}{}{I was just checking to see if you're still an asshole. Yep, looks like you are. Bye.}
#{233}{}{Sorry, I thought you were, uh, someone else. Bye.}
#{234}{}{I hope you know how to use that thing, 'cause I plan on taking that fucking boat, one way or another.}

{230}{}{[卫兵握紧他的武器，恶狠狠地瞪着你。]}
{231}{}{我能借用一下你的船吗？}
{232}{}{我只是想看看你是否仍然是个混蛋。看来我没错，再见。}
{233}{}{对不起，我还以为你是别人呢。再见。}
{234}{}{我希望你知道如何使用那件东西，因为我要把那艘该死的船开走。}


#{240}{}{[He looks at you as if you're dumbest creature he could possibly imagine. Slowly, he shakes his head.] No. Now go away. Ask me another question, and I'll hurt you.}
#{241}{}{Alright, I'm going. Bye.}
#{242}{}{Is that a fact?}

{240}{}{[他看着你好像你是他能想象的最愚蠢的生物。过了一会，他摇了摇头]不，不行，离开这里，不然我开枪。}
{241}{}{好吧，我离开，再见。}
{242}{}{你认真的吗？}


#{250}{}{Get away from there!}
#{251}{}{Touch that again and I'll kill you.}
#{252}{}{I warned you!}

{250}{}{离开哪里!}
{251}{}{再碰一次我就宰了你！}
{252}{}{我警告你！}