#{100}{}{You see an anxious Shi guard.}
#{101}{}{The guard's eyes shift nervously about the gloom.}

#{200}{}{This place is sacred. Incredibly eerie, but sacred.}
#{201}{}{Let's get this over with.}
#{202}{}{I can feel the spirits of my ancestors among us.}
#{203}{}{Go do your tech thing so can return to the mainland.}
#{204}{}{Did you hear that? I swear I heard something.}
#{205}{}{Why do I always get assigned to this? }


{100}{}{你看到一个焦虑的始族守卫。}
{101}{}{卫兵的眼睛在紧张地注视着黑暗。}

{200}{}{这个地方是神圣的，非常诡异，但是神圣的。}
{201}{}{让我们把这件事了结吧。}
{202}{}{我能感觉到我祖先的灵魂在我们之中。}
{203}{}{去做你的科技产品吧，这样就可以回到陆地上了。}
{204}{}{你听到了吗？我发誓我听到了什么。}
{205}{}{为什么我总是被分配到这个工作？}
