#{100}{}{You see a dockworker. He looks up at you as you approach.}
#{101}{}{You see a melancholy dockworker. His sorrow-filled eyes glance up at you as you approach.}

{100}{}{你看到一个码头工人。当你走近时，他抬头看着你。}
{101}{}{你看到一个忧郁的码头工人。当你走近时，他那双充满悲伤的眼睛望着你。}


#{200}{}{[Mumbles to himself.] Oh, what atrocities did poor Meng do in a past life to deserve such
 misfortune? Now the lao wai comes to me, and what good could possibly come of it? None, of course. None at all……}
#{201}{}{Why do you not leave poor Meng in peace? [Mumbles to himself.] Not that I've ever known peace. Or, if I did,
 then it's long forgotten, like a distant dream……}
#{202}{}{Uh, I seem to have caught you at a bad time. Bye.}
#{203}{}{What's your problem, Mumbles?}
#{204}{}{I noticed you seem to be upset about something. I was just wondering if I could help.}

{200}{}{[喃喃而语]噢，可怜的孟在过去的生活中有过这样的暴行，太不幸了。现在老外来找我了，有什么好处呢？当然没有……根本没有……}
{201}{}{为什么你不让可怜的孟平静下来？[喃喃而语]。我从来没有听说过平和。如果我曾经有过，然后，它就像一个遥远的梦，被遗忘很久了……}
{202}{}{呃，我似乎在一个不愉快的时候找到了你，再见。}
{203}{}{为什么你总是对自己说话？}
{204}{}{我注意到你似乎对某事感到不安，我在想我是否能帮上忙。}

#{210}{}{My problem? [He laughs bitterly.] Loa wai, you do not wish to know my problem. To hear of sorrows such as mine
 is to forget the sound of a child's laughter, and the warm embrace of a lover. No, trust me, you do not wish to glimpse my personal Hell.}
#{211}{}{I've witnessed a lot of terrible things in my time. I'm sure that whatever your problem is, I can handle it.}
#{212}{}{You think *your* problems are bad? I bet they don't *compare* to things I've been through.}
#{213}{}{I'm sorry things have been rough for you, but it might help to talk about it. If you're willing to talk, then I'm willing to listen.}
#{214}{}{All right Mr. Melodrama, I'm gonna leave now before you make me depressed. Bye.}

{210}{}{我的问题吗？[他苦笑]老外，你不会希望知道我的问题的。我忘记了孩子的笑声，爱人温暖的拥抱。相信我，你不希望看到我的私人地狱的。}
{211}{}{我在这个时代目睹了许多可怕的事情。我相信不管你的问题是什么，我都能应付。}
{212}{}{你认为*你的经历*很不好吗？我敢打赌比起我身上发上的事，你的经历一点都不可怕。}
{213}{}{我很抱歉，现在对你来说可能很艰难，但是谈论它可能会有帮助。如果你愿意说话，那么我愿意倾听。}
{214}{}{在你让我沮丧之前，再见。}


#{220}{}{Fine. You want to know my problem. I'll tell you. Two years ago, my brother, who looks very similar to me, had
 an affair with a local gang leader's girlfriend. The gang leader found out about it and my brother fled town. The gang
 caught me instead, and, thinking I was my brother, they severed my penis as punishment. Now I piss through a tube.}
#{221}{}{Oh, well?}

{220}{}{好。你想知道我的问题。那我告诉你。我的哥哥和我长得很像，两年前他和当地黑帮头目的女友有染。后来团伙头目发现了这件事，我的兄弟逃离了小镇。但那伙人却把我当成了我的兄弟，把我的阴茎割下来作为惩罚，现在我只能插根管子来尿尿了。}
{221}{}{[继续]}


#{230}{}{Oh no! I'm not done yet. Then my beautiful girlfriend left me, because I was no longer a "real man" and could not
 satisfy her. She then married my next door neighbor, who also happens to be my boss. Now, all day at work, he orders me
 around and mocks me with my co-workers. And every night I must try to fall asleep to the sound of him making love to the
 girl I should have married.}
#{231}{}{Hahaha! Holy shit, you're a loser. Why don't you do yourself a favor and just end it?}
#{232}{}{I, uh, wow, I'm not sure what to say. That's a terrible story.}
#{233}{}{I'm sorry that happened to you, Meng. Life can be cruel, but it can always get better. If I were you, I'd move
 somewhere else and find a different job. Otherwise you'll never be able to move on.}
 
{230}{}{哦！不！还没完。然后我美丽的女友离开了我，因为我不再是一个“真正的男人”，也不能满足她。然后她嫁给了我隔壁的邻居老王，也是我的老板。现在他命令我整天工作。每天晚上我都睡不着，因为他们每天晚上都做爱……而我本应该结婚的。}
{231}{}{哈哈哈!天啊，你是个失败者。你为什么不帮自己一个忙，就这样结束了？}
{232}{}{我，呃，哇，我不知道该说什么。这是一个可怕的故事。}
{233}{}{我很同情发生在你身上的一切，孟。生活可能是残酷的，但它总能变得更好。如果我是你，我会搬家。在别的地方找一份不同的工作，否则你将永远无法站起来。}
 
 

#{240}{}{Yes. Yes, this is what I should have done long ago. It is the only way to retain what little honor I have left.
 Thank you, lao wai. [He takes out a knife and slits his throat. You watch as he quickly bleeds to death.]}
#{241}{}{[DONE]}

{240}{}{是的，是的，这是我很久以前就应该做的。这是保留我仅有的一点荣誉的唯一方法。谢谢你，老外。[他拿出一把刀，撕开了他的喉咙，你看着他迅速流血而死]}
{241}{}{[结束]}

#{250}{}{Yes. This I warned you about. Now, let me be. I have nothing else to say to you.}
#{251}{}{[DONE]}

{250}{}{是的,这是我警告过你的。现在让我单独呆着，我没有别的话对你说。}
{251}{}{[结束]}


#{260}{}{Perhaps you are right. All my life, I've known nothing but the Shi. But there is nothing left here for me but sorrow.
 Yes, I think I shall venture out into the world and forge a new destiny. Even if the wastes offer me nothing but a swift
 death, that is preferable to remaining here. Thank you, lao wai.}
#{261}{}{Good luck, Meng. I hope your fortunes improve.}
#{262}{}{Before you start packing, I was wondering if you could answer a question or two for me?}

{260}{}{也许你是对的，在我的一生中，我只知道始族。但是这里除了悲伤，没有什么可以留给我。是的，我想我将冒险进入这个世界，创造一个新的命运。即使荒野只给我一个迅速死亡的机会。谢谢你。老外。}
{261}{}{祝你好运，孟。祝你好运。}
{262}{}{在你开始收拾行李之前，我想知道你能不能给我回答一两个问题？}




#{270}{}{Why not? I'm severing all ties to the Shi. Their secrets now mean nothing to me. Ask what you will.}
#{271}{}{What can you tell me about that guarded motorboat over there? }
#{272}{}{Never mind. Good luck on your new life, Meng.}

{270}{}{为什么不呢？我要断绝与始族的一切联系。他们的秘密对我来说毫无意义，你想问什么。}
{271}{}{你能告诉我关于那艘有警卫的汽艇的情况吗？}
{272}{}{没什么事，祝你的新生活好运。}

#{280}{}{The Shi use that motorboat to access our sleeping guardian, the sub.}
#{281}{}{What can you tell me about the sub?}

{280}{}{始族用汽艇来接近潜艇"始皇帝"，"始皇帝"是我们沉睡着的守护者。}
{281}{}{你能告诉我关于潜艇的事吗?}


#{290}{}{The Shi-Huang-Ti is the submarine that brought our ancestors to this place from a far away land. In the aftermath
 of the Great War it lost power and ran aground in the San Francisco bay. Captain Ye Li and his crew then made their way
 to this city and established what would become the Shi society.}
#{291}{}{You referred to it as a "sleeping guardian." What do you mean by that?}

{290}{}{"始皇帝"是把我们的祖先从遥远彼岸带到这个地方的潜水艇。后来在这场大战中，它失去了力量，在旧金山湾搁浅。于是李烨船长和他的船员们走了出来，后来建立了城市，建立了"始族"。}
{291}{}{你把它称为"沉睡着的守护者"。你这话是什么意思?}

#{300}{}{Like a hibernating dragon whose snores can still produce deadly fire -- the sub is immobile, but not helpless.
 The Shi have been working on it in secret, making clandestine trips to the sub under cover of night. Its weapons have
 been reactivated and will surly destroy any non-Chinese vessels that dare to sail through this bay.}
#{301}{}{So, let's say, *hypothetically*, if that big tanker that's docked here where to try and set sail……}

{300}{}{就像一头沉睡的龙，它的鼾声仍能产生致命的火焰。虽然潜艇不能动的，但始族一直在修复它，它的武器系统已经被重新激活了。如果有任何非中国船只敢闯进来，那就会被"始皇帝"炸上天。}
{301}{}{那么，假设，假设，如果旁边这艘大油轮试着启航……}


#{310}{}{Then…… BOOM!}
#{311}{}{Gotcha. I don't suppose you know how I could disarm it?}

{310}{}{[他白了你一眼]BOOM！上天。}
{311}{}{你知道怎样才能解除它吗？}


#{320}{}{Only the Shi's technicians would know such a thing. I've told you all I know.}
#{321}{}{Thanks, Meng. Good luck with your new life.}

{320}{}{这样的事只有始族的技术人员才知道。我已经告诉了你所知道的一切了。}
{321}{}{谢谢，孟。祝你新生活好运}


#{330}{}{Now it is time to begin anew……}
{330}{}{现在是重新开始的时候了……}

#{350}{}{Leave me be, lao wai.}
{350}{}{离开我，老外。}

#{400}{}{You convince Meng to move on with his life.}
{400}{}{你说服孟继续他的生活。}
