#looks/descriptions
#{100}{}{You see a guard in loose clothing, wearing a look of wary boredom.}
#{101}{}{You see a dock guard. He's unusually well armed.}
#{102}{}{You see the motorboat guard.}

{100}{}{你看到一个穿着宽松衣服的警卫，脸上带着警惕的神情。}
{101}{}{你看到一个码头警卫，他带着武器。}
{102}{}{你看到了汽艇警卫。}


#touched motor boat without permission


#{150}{}{Hey! Step away from that!}
#{151}{}{Don't even think about that. This is your last warning.}
#{152}{}{I warned you, lao wai, now die!}

{150}{}{离开那里！}
{151}{}{不要再想那件事，这是最后的警告。}
{152}{}{我警告过你，“老外”，现在准备受死！}

#Main dialogue

#Greeting
#{200}{}{What do you want, lao wai?}
#{201}{}{It's you again. What is it that you want, lao wai?}
#{202}{}{What are you guarding?}
#{203}{}{I need to use the motorboat.}
#{204}{}{Nothing. Bye.}

{200}{}{嘿，“老外”，你想要什么？}
{201}{}{又回来了，你想要什么？“老外”。}
{202}{}{你在这里是干什么的？}
{203}{}{我要使用这台汽艇。}
{204}{}{没什么事，再见。}


#what are you guarding?
#{210}{}{Everything. Don't try anything funny.}
#{211}{}{Can't you be any more specific?}

{210}{}{和你没什么关系，不要在这里晃悠。}
{211}{}{你不能放轻松点吗？}

#be more specific
#{220}{}{No. Now back away, outsider.}
#{221}{}{Alright. Bye.}
#{222}{}{Nobody tells me what to do. You're fucking dead!}

{220}{}{不能，现在离开这里，陌生人。}
{221}{}{好吧，再见}
{222}{}{没有人能告诉我该做什么，受死吧！}

#I need to use the motor boat
#{230}{}{And I need you to fuck right off. You're not permitted to use the motorboat, hell, you're a lao wai, not a Shi.}
#{231}{}{Listen, I'm in a desperate situation. If you don't let me use that motorboat, then my entire tribe could die.
 Right now, they're in the clutches of those Enclave bastards and they're counting on me to save them. But in order to
 do that, I'm going to need to use that motorboat. If you won't let me use it, I'll have to take it by force and one of
 us will end up dead. Please, don't let it come to that.}
#{232}{}{Actually, I'm an honorary member of the Shi. I was hired for the submarine maintenance team due to my expertise in...subology. Here's my password...}
#{233}{}{I don't think you realize who you're insulting. Time to die, asshole.}
#{234}{}{Alright, I'm going... Sheesh, some people...}

{230}{}{你需要回去被一打变种人干你的后门，你不能使用这艘汽艇，你是一个“老外”，不是一个始族人。}
{231}{}{现在我在绝望的边缘，我的部族被一台会飞的机器带走了，我不知道他们会发生什么，他们都等着我去救他们。在这里，我求你让我使用这艘船，否则我只能被逼使用武力，这样我们当中的一个肯定会死在这里，求求你了，我不想发生这种事情。}
{232}{}{实际上，我是始族的荣誉会员，由于我在电子学方面的专业知识，我受雇于潜艇维护小组，这是我的密码...}
{233}{}{你在说什么？It's A Good Day To Die!}
{234}{}{好的，好的，我现在就走。}


#Listen, I might not be Shi...
#{240}{}{[He stares at you for a long moment, then sighs.] Look, no one gets on this boat without giving the proper password. You know, like the one you just gave me. [Mumbles.] Ken Lee's going to have my head for this...}
#{241}{}{Thank you, friend. And don't worry, I won't speak a word of this anyone.}

{240}{}{他盯着你看了很长时间，然后叹了口气]从来没有人能在没有密码的情况下上船，不过你好像已经把密码给我了。[喃喃而语]李健肯定会为这件事责怪我的...}
{241}{}{谢谢你，朋友。别担心，我不会告诉任何人的。}

#I won't speak a word of this anyone
#{250}{}{I hope not, for both our sakes... Let me know when you're ready to use the boat. You can't bring anyone with you, as it'll draw too much attention. You'll have to go at this alone.}
#{251}{}{I'd like to use it right now.}
#{252}{}{Not right now.}

{250}{}{我希望这件事只有我们两个人知道，当你准备好使用这艘船的时候，请告诉我。你得一个人去，不能带任何人，因为这会引起太多的注意。}
{251}{}{我马上就去。}
{252}{}{我一会再回来。}


#I'm a member of the Shi...
{260}{}{[警卫听口令，点了点头]我想你真的是个技术员，但始族一般很少雇佣外人。现在恐怕你来得有点太早了，维护技术团队要直到午夜才会离开港口。如果你愿意的话，你可以在这里等其他的人。}
{261}{}{现在我没什么其它事，我在这里等吧。}
{262}{}{我一会再过来。}

#Use motor boat now
#{270}{}{Just use the mooring post and slide down the rope to the boat. Don't take too long out there, though, I don't want to get into any trouble.}
#{271}{}{Got it. Bye.}
#{272}{}{Easy enough. Goodbye.}

{270}{}{顺着绳子滑到船上，然后解开固定船的绳子，别花太长时间，我可不想惹麻烦。}
{271}{}{再见。}
{272}{}{感谢你，再见。}

#Player wasn't initially ready to go with the tech team
#{280}{}{Ready to join the tech team?}
#{281}{}{Yes, I'm ready to go.}
#{282}{}{No, not yet.}

#{290}{}{Can't you see I'm busy here?}

{280}{}{你准备好启程了吗？}
{281}{}{是的，我已经准备好了。}
{282}{}{不，还没有。}

{290}{}{你没看见我在忙吗？}


#dumb dialogue
#{300}{}{Me ride metal fishy-fish?}
#{310}{}{[He looks at you as if you're dumbest creature he could possibly imagine. Slowly, he shakes his head.] You no ride
 metal fishy-fish. You go. You go, or I shoot. Understand?}
#{311}{}{Okie, bu-bye!}
#{312}{}{You meanie-man. Me smash meanie-man!}

#{500}{}{You talk your way into gaining access to the motor boat.}

{300}{}{我能骑这个铁鱼鱼吗？}
{310}{}{[他看着你，仿佛你是他能想象到的最愚蠢的生物]过了好一会，他摇了摇头，你不能骑铁鱼鱼。离开，否则我开枪，明白吗？}
{311}{}{好的，再见！}
{312}{}{你是小气鬼，我要干掉小气鬼！}

{500}{}{你用你的方式进入了汽艇。}


