#{100}{}{You see a crazed-looking Shi scientist.}
#{101}{}{You see Dr. Sheng.}

{100}{}{你看到了申博士，和大部分游戏里的科学狂人一样，他秃头，穿着白色技术服}
{101}{}{你看到了申博士，他眼睛闪着狂热的光芒}


#{200}{}{[You see a Shi scientist with a wispy beard and a crazed look in his eyes. His hair and clothes are disheveled and he appears to have not slept in days.] Ah！ Yes！ Yes, I was expecting you. They told me you were coming. [He looks you up and down.] Yes, you are perfect.}
#{201}{}{I won't argue with that, but what the hell is going on here？}
#{202}{}{You must be Dr. Sheng. Dr. Wong told me your location. The Shi thought you might be dead.}
#{203}{}{First of all, what are these creatures？}
#{204}{}{Perfect for what, exactly？}
#{205}{}{Who told you I was coming？}

{200}{}{[你看到一个有胡子的始族人，他的头发和衣服都凌乱不堪，眼睛闪着疯狂的眼神，他似乎几天没睡觉了]啊！我正等着你呢，它们告诉我你要来。[他上下打量你]是的，你真是太完美了，太合适了。}
{201}{}{这到底是怎么回事？}
{202}{}{你一定是申博士，王博士告诉了我你的位置，始族认为你可能已经死了。}
{203}{}{首先，这些生物是什么？}
{204}{}{合适什么？}
{205}{}{谁告诉你我要来？}


#{210}{}{Science！ What else？ I am Dr. Sheng and these creatures are my creations. Beautiful, are they not？}
#{211}{}{Uh, yeah …… But, what are they？}
#{212}{}{Actually, I find them rather repulsive. Vomit inducing, really. And that smell, both sweet and fetid, like syrup made from corpse juice. What are these things？}

{210}{}{当然是科学！除此之外还能有什么？我是申博士，这些生物是我的创造物，它们很美丽，不是吗？}
{211}{}{呃……是的……但是，他们是什么？}
{212}{}{实际上，我觉得它们相当令人厌恶，这些东西就象又甜又臭的呕吐物，或者是用死尸做成的糖浆人。这些是什么东西？ }



#{220}{}{Ha！ Dr. Wong wishes I were dead. Oh no, I am doing better than ever. And things will only improve if you are willing to assist me.}
#{221}{}{Assist you with what？}
#{222}{}{Hold on. Before I agree to help you with anything, tell me what these creatures are.}

{220}{}{哈！王博士当然会希望我死了。但是，我并没有，我比以前做得更好了。相信我，只要你愿意帮助我，事情会变得更好。}
{221}{}{帮助你什么？}
{222}{}{等等，在我答应帮你做任何事之前，先告诉我这些生物是什么。}


#{230}{}{They are the future！ A new race of sentient plant life forms, created by me. I have finally achieved success in synthesizing my new plant life with fresh human cadavers！ As you can see, this endows the plants with, sensory, ambulatory, and vocal capabilities which they would otherwise lack. It also grants a human-like appearance which will allow them to more easily assimilate into our culture.}
#{231}{}{So where are you getting these 'fresh human cadavers'？ }
#{232}{}{Assimilate into our culture？ Good luck with that. The ghouls and mutants can hardly manage that and they are梠r were梐t one point human. These things are abominations.}
#{233}{}{Actually, I've met a spore plant that could talk without being infused with a human body.}
#{234}{}{That's incredible. As a fellow student of science, I must know how this was made possible.}

{230}{}{他们是未来！我创造了一种有知觉的植物生命形态。我终于成功地用新鲜的人类尸体合成了我的新植物！正如你所看到的，我赋予了植物感觉、走动和发声能力，我还赋予了他们类人的外表，这将使他们更容易融入我们的文化。}
{231}{}{那么，你在哪里得到这些"新鲜的尸体"？}
{232}{}{融入我们的文化吗？祝你成功，食尸鬼和变种人和我们同源都很难做到这一点，而这些东西看起来比他们可怕多了。}
{233}{}{老实说，我遇到过一棵孢子植物，它可以说话，而且不需要新鲜的人体就能做到。}
{234}{}{这是如此的激动人心，作为一名科学专业的学生，我真想知道这是如何实现的。}

#{240}{}{Perfect for the task at hand. You see, not all of my experimental creatures have been as successful as the specimens you see here. Most tend to end up being mindless, violent brutes. I keep these failures locked within a pen in my lab, but they recently got loose. I managed to get out and lock the door before any could escape into the wild, but now I am unable to return to my lab.}
#{241}{}{So what do you want me to do about it？}

{240}{}{很适合完成我手头的工作。你看，不是所有的实验生物都像你在这里看到的那样成功。相当一部分成为了没有头脑的、暴力的畜生。我把这些失败品锁在实验室的一个角落里，但最近他们把笼子挣坏了。我设法逃了出去，并在它在能逃到野外之前锁上了门，但代价是现在我不能回到我的实验室了。}
{241}{}{那么你想让我做些什么呢？}


#{250}{}{My creations, of course. They are ever vigilant of the wastes. There is much out there to be wary of, as I'm sure you would agree. When they told me of your approach, I instructed them to bring you to me, as I believe you may be able to assist me.}
#{251}{}{Assist you with what？}
#{252}{}{Before I agree to assist you with anything, tell me what these creatures are.}

{250}{}{我的作品，他们对这附近是时刻保持警惕的。我相信你会同意废土上有很多值得警惕的地方。他们发现你来到后，我指示他们把你带到我这里来，因为我相信你可以帮助我。}
{251}{}{帮助你什么？}
{252}{}{在我同意帮助你做任何事之前，先告诉我这些生物是什么。}


#{260}{}{Oh, mostly from raiders who foolishly decide to attack us here. But enough about that. I must know if you are willing to assist me.}
#{261}{}{Assist you with what？}

{260}{}{大部分是那些愚蠢闯进这里的袭击者，我想知道你是否愿意帮助我。}
{261}{}{帮助你什么？}


#here
#{270}{}{You see, not all of my experimental creatures have been as successful as the specimens you see here. Most tend to end up being mindless, violent brutes. I keep these failures locked within a pen in my lab, but they recently got loose. I managed to get out and lock the door before any could escape into the wild, but now I am unable to return to my lab.}
#{271}{}{So what do you want me to do about it？}

{270}{}{你看，不是所有的实验生物都像你在这里看到的标本一样成功。大多数实验体成为没有了头脑的、只会使用暴力的畜生。我把这些失败品锁在实验室的一个角落里，但最近他们把笼子挣坏了。我设法逃了出去，并在它在能逃到野外之前锁上了门，但代价是现在我不能回到我的实验室了。}
{271}{}{那么你想让我做些什么呢？}


#{280}{}{How you feel about my work is of no concern to me. Now I shall be blunt. I have a task which you seem qualified for. Upon its completion, you will be rewarded. Are you interested？}
#{281}{}{I'm listening.}
#{282}{}{I want nothing to do with you or your disgusting creations.}

{280}{}{我不关心你对我工作的感觉。我们直接点吧，我有一项你似乎能胜任的任务。如果完成，你就会得到报酬，你感兴趣吗？}
{281}{}{我在听。}
{282}{}{我不想和你或你的恶心的创造物做任何事。}


#{290}{}{Excellent！ Give them to me, and you shall be rewarded.}
#{291}{}{Sure, it's not like I have much use for them. Here you go.}
#{292}{}{Nah. I've grown rather fond of the little guys. I think I'll hold on to them. Maybe start a garden or something.}
#{293}{}{I don't have them on me but I'll go see if I can find them.}
#{294}{}{I don't have them on me, and even if I did I wouldn't hand them over to you. I want nothing to do with you or your veggie-zombies.}

{290}{}{太棒了！把它们给我，你就会得到奖赏。}
{291}{}{当然，我不太喜欢它们，给你。}
{292}{}{不，我越来越喜欢这些小家伙了。我想我会留着它们，也许将来可以开个花园什么的。}
{293}{}{我还没找到，但是我会去看看我是否能找到他们。}
{294}{}{我还没找到，即使我找到了，我也不会把它们交给你。我不想和你或者你的素食僵尸有任何瓜葛。}


#{300}{}{The facility is known as the EPA. I've marked it on your mapping device. Please, go there and try to find some seeds. And not just any plain old seeds ？they must be unique.}
#{301}{}{Ah, it seems you already know the location of the EPA. Please, go there and try to find some seeds. And not just any plain old seeds ？they must be unique.}
#{302}{}{I'll be back.}
#{303}{}{Eh, on second thought, I'm not interested in working for you anymore. We're done here.}

{300}{}{这个地方被称为EPA，我在你的地图上做了标记。请到那里去找一些种子，请注意我要的不是普通的种子，我要的是独特的种子。}
{301}{}{啊，看来你已经知道EPA的位置了。请到那里去找一些种子，请注意我要的不是普通的种子，我要的是独特的种子。}
{302}{}{我会回来。}
{303}{}{嗯，再想想，我对为你工作不感兴趣了。这件事我们就到止为止吧。}


#{310}{}{[His eyes flare with rage] Kill him, my children！ His body shall make a fine host for your newest sibling！}
#{311}{}{[His eyes flare with rage] Kill her, my children！ Her body shall make a fine host for your newest sibling！}
#{312}{}{[DONE]}

{310}{}{[他的眼睛闪耀着愤怒和疯狂]杀了他，我的孩子们！主人会用他的身体会为你们做一个最新款式的兄弟姐妹！}
{311}{}{[他的眼睛闪耀着愤怒和疯狂]杀了他，我的孩子们！主人会用他的身体会为你们做一个最新款式的兄弟姐妹！}
{312}{}{[结束]}


#{320}{}{Excellent！ Now I shall prepare your reward. Make yourself comfortable. This may take a little while.}
#{321}{}{[CONTINUE]}
#{322}{}{Keep your reward. I don't have time to wait around.}

{320}{}{太棒了！现在我要准备你的奖赏，这可能需要一点时间，在这里等一会，尽量让自己舒适些。}
{321}{}{[继续]}
{322}{}{留着你的奖赏吧，我现在要走了。}

#{330}{}{Yes, bring the seeds to me and you may claim your reward.}
#{331}{}{I'll be back.}

{330}{}{把种子带给我，你会得到报酬。}
{331}{}{我会回来。}

#{340}{}{Simply giving you the location of the facility is a reward in itself, as it is bound to be full of useful supplies. You may of course keep anything else you find. I am only interested in unique seed samples. Once you have brought them to me, I will give you a gift to present to the Shi.}
#{341}{}{Alright, I'll do it. I'll be back.}
#{342}{}{You call that a reward？ I can explore ruins on my own time. I'm not interested.}

{340}{}{告诉你设施的位置本身就是一种奖励，因为它里面肯定有各种有用的东西。我只对独特的种子样品感兴趣，除此之外你可以保留任何你在里面发现的东西。如果你给我带来种子，我会付给你报酬。}
{341}{}{好了，解决这件事后，我就回来。}
{342}{}{你把哪个叫做报酬？我自己就能搜索哪里，你的事我不感兴趣。}


#{350}{}{[Looks at you expectantly.]}
#{351}{}{Here are the seeds you wanted.}
#{352}{}{I'll come back when I have the seeds.}

{350}{}{[用期待的眼光看着你]}
{351}{}{这是你想要的种子。}
{352}{}{我有了种子就会回来的。}


#{360}{}{Then it seems I have no further use for you. [He motions to the plant creatures.] Kill him, my children！ His body shall make a fine host for your newest sibling！}
#{361}{}{Then it seems I have no further use for you. [He motions to the plant creatures.] Kill her, my children！ Her body shall make a fine host for your newest sibling！}
#{362}{}{[DONE]}

{360}{}{那似乎你对我没什么用处了。[他向植物生物示意]，杀了他！主人会用他的身体会为你们做一个最新款式的兄弟姐妹！}
{361}{}{那似乎你对我没什么用处了。[他向植物生物示意]，杀了他！主人会用他的身体会为你们做一个最新款式的兄弟姐妹！}
{362}{}{[结束]}


#{370}{}{[The Doctor departs. After about an hour, he returns and hands you a single plant seed.] This plant sample is my gift to the Shi. It will change everything. I am giving you the honor of presenting it to Doctor Wong.}
#{371}{}{What's so special about this plant sample？}
#{372}{}{That's it？ I went and got those damn seeds for you and this is what I get for my trouble？ Yet another seed？ Fuck you and your creepy plant zombies. I think I'll do the world a favor and put an end to this morbid operation of yours.}

{370}{}{[申博士离开了，大约一个小时后，他回来给你一颗植物种子]这个植物样品是我送给始族的礼物，它将改变一切，请把它交给王博士。}
{371}{}{这个植物样本有什么特别的？}
{372}{}{又是种子？去你妈该死的种子和植物僵尸，我想我要帮世界一个忙，结束你这个病态的行为。}

#{380}{}{The Shi have been attempting to create plant life that is resistant to radiation. I was the head of that project, but during my research I made a discovery that led me down a different path. I created a plant sentience serum, but after a few …… unfortunate incidences, the Shi wanted to shut the project down. So I left to continue my work unimpeded.}
#{381}{}{Okay. So how does this plant sample figure into this？}
#{382}{}{Go on……}

{380}{}{始族一直试图创造可以抵抗辐射的植物，我是那个项目的负责人。但在我的研究过程中，我碰到了一个让我走上不同道路的发现，我创造了一种植物血清，它可以赋予植物知觉。但不久之后，始族强行中止了这个项目，所以我选择离开，继续我的工作。}
{381}{}{那么这个植物样本是怎样的呢？}
{382}{}{[继续]}


#{390}{}{Ironically, just as my focus was shifting to my new sentient plant creations, I happened to make a major breakthrough in radiation-resistant plant research. I kept this breakthrough a secret, as I did not want to draw attention away from my more significant discovery. When the others failed to see the importance of my sentient plants, I decided to keep my secret out of spite. That is, until now. With the plant sample I have given you, even a narrow-minded fool like Dr. Wong could achieve the goal of radiation-resistant plant life.}
#{391}{}{So why the change of heart？}
#{392}{}{Okay. I'll deliver it to Dr. Wong.}
#{393}{}{I'll bring this to Dr. Wrong. But if he doesn't give me a proper reward for it, then you'll be seeing me again.}
#{394}{}{You can keep the sample. I'm sure Dr. Wong and the other Shi scientists can figure it out without your help. I'm done doing you favors.}

{390}{}{讽刺的是，当我集中注意力到我的全新领域时，我碰巧在抗辐射植物研究方面也取得了重大突破。我把这个突破当成了一个秘密，因为我不想把注意力从更重要的发现上移开。但当时，身边的人都看不清我新领域的前景，我决定不把这项突破公布出去。这么说吧，只要有我给你的植物样本，即使是像王博士这样心胸狭窄的傻瓜，也能达成创造抗辐射植物的目标。}
{391}{}{为什么你的想法会发生变化的？}
{392}{}{好，我会将它交给王博士。}
{393}{}{我会把它给王博士的，但如果他不给我适当的报酬，你就会再见到我了。}
{394}{}{样品你可以自己留着了，我相信王博士和其他的始族科学家不需要你的帮助，我们到此为止。}



#{400}{}{I have had no change of heart. In addition to being radiation resistant, the plant sample is infused with my sentience serum. Like a proud father, I merely wish to see my creation flourish. Deliver it for me, and you shall be granted a true reward.}
#{401}{}{Okay. I'll deliver it to Dr. Wong.}
#{402}{}{Nah. Keep your sample. I'm done helping you.}
#{403}{}{Dr. Wong seems like a sly guy. You really think he'll trust a plant sample from you？}

{400}{}{我并没有改变想法，除了抗辐射基因外，这个植物样品还注入了我的植物知觉血清。就所有骄傲的父亲一样，我希望看到我的创造蓬勃发展。按我说的办，完成后你会得到报酬的。}
{401}{}{好吧，我将交给王博士。}
{402}{}{不，样品你留着吧，我们到此为止。}
{403}{}{王博士看起来是个狡猾的家伙，你真的认为他会信任你的植物样本吗？}


#was 270
#{410}{}{It has come to my attention that there is an old US government facility where one might obtain unique plant seeds untouched by radiation. This facility is too far away for me to personally venture to, but I believe it would be a simple task for an experienced wastelander such as you.}
#{411}{}{Oh, you're talking about these weird seeds from the EPA. Been there, got them.}
#{412}{}{I'm always up for exploring some old ruins. Give me the location and I'll go see what I can find.}
#{413}{}{And what do I get out of it？}

{410}{}{我注意到有一个旧的美国政府设施，在那里可以得到独特的植物种子。这个设施对我来说太遥远了，我个人不敢冒险。但是我相信，对于像你这样有经验的旅行者来说，这是一个简单的任务。}
{411}{}{哦，你说的是EPA里这些奇怪的种子？它们就在这里。}
{412}{}{我总是在寻找一些古老的遗迹。把位置给我，我去看看我能找到什么。}
{413}{}{那我能从里面得到什么？}



#{420}{}{Yes, Dr. Wong is a bit of an obstacle. If he were removed from the picture, things would go much more smoothly. Give Dr. Wong the sample. Even if he distrusts me, his curiosity will get the better of him and he'll accept it. Once the sample has been stored away, find a way to eliminate Dr. Wong without alerting the other Shi. Perhaps an overdose of some sort. Do this, and I'll see that your reward is tripled.}
#{421}{}{I'll see what I can do.}
#{422}{}{If you want Wong dead, you'll need to give me something up front.}
#{423}{}{You know, this is all getting a bit complicated. I think I'd rather just massacre you and then go massacre the Shi.}
#{424}{}{There's no way I'm killing Dr. Wong for you. I'm done here.}

{420}{}{王博士的确是一个障碍，如果把他从照片上删除，事情就会顺利得多。你把样本给王博士就可以了，即使他不信任我，他的好奇心也会让他把这些种子接下来的。当种子被存储起来之后，你就在不惊动旁人的情况下把王博士干掉，如果你能完成这件事，我会给你3倍的奖励。}
{421}{}{我看看我能做什么。}
{422}{}{如果你想要王博士死，你需要给我一些行之有效的东西。}
{423}{}{你知道，这一切都变得有点复杂了。我想我宁愿杀了你，然后再去屠杀始族。}
{424}{}{我不会杀王博士，我们到此为止。}



#{430}{}{Very well. This poison may come in handy. I extracted it from one of my creations. It is extremely deadly. [He gives you a syringe.]}
#{431}{}{I'll see what I can do.}

{430}{}{很好，这种毒药可以派上用场。这是我的一个作品中提取出来的，它是非常致命的[他给你一个注射器]}
{431}{}{我看看我能做什么。}

#{440}{}{[Looks at you expectantly.]}
#{441}{}{I'm still working on things. I'll get back to you.}
#{442}{}{I delivered the sample to the Shi.}
#{443}{}{The Shi have the sample and Dr. Wong is dead.}
#{444}{}{Your method of revenge wasn't direct enough for my tastes, so I just killed everyone for you.}
#{445}{}{Dr. Wong is dead.}
#{446}{}{I delivered the sample to the Shi and told Dr. Wong about your intentions. He destroyed the sample immediately.}

{440}{}{[用期待的眼光看着你]}
{441}{}{事情我还在办，迟些给你答复。}
{442}{}{我已经把样品给了始族。}
{443}{}{样品已经给了始族，王博士也死了。}
{444}{}{你报复的方法不合我的口味，所以我杀了所有人。}
{445}{}{王博士已经死了。}
{446}{}{我把样品交给了始族，也告诉王博士你的意图，他立即销毁了样品。}


#{450}{}{Impossible！ A spore plant cannot be capable of speech regardless of its intelligence. Either you are making some sort of jest or you were under a drug-induced hallucination. By the looks of you, I'd guess it was the latter. But enough about that nonsense. I must know if you are willing to assist me.}
#{451}{}{Yeah, I suppose it *does* sound rather silly. Anyway, what did you want me to assist you with？}
#{452}{}{Don't change the subject was telling the truth！ I swear on the Vault Dweller, his name was Seymour and he could talk. He wanted me to re-plant him in a better location. I'm not making this up and I wasn't hallucinating.}

{450}{}{不可能的！一个孢子植物无论其智力如何，都不可能说话。你要么是在开玩笑，要么是毒吸多了。看你的样子我认为多半是后者，现在废话就此打住吧。我想知道你是否愿意帮助我。}
{451}{}{是的，我想这听起来有点傻，但这是真的。你要我帮你做什么？}
{452}{}{不要改变话题，我说的是真话！我发誓，他的名字是西摩，他可以说话。他想让我把他安置在一个更好的地方。我不是在瞎编，我也没有产生幻觉。}



#{460}{}{Enough！ I do not have time for this foolishness. Will you assist me, or not？}
#{461}{}{Assist you with what？}
#{462}{}{No！ I'm not going to assist you, asshole！ Seymour was real！ SEYMOUR WAS REAL！}

{460}{}{够了！我不想再谈这个，你愿意帮助我吗？}
{461}{}{帮助你什么？}
{462}{}{不！我不会帮你的，你这个混蛋！西莫是真实存在的！西莫是真的！}


#{470}{}{[He grins, obviously eager to show off his genius.] I've always been fascinated by plants. They are so remarkably different from animals, and yet surprisingly similar. When you look at an animal, you know it can think, that it's aware of its surroundings, experiences pain and fear. That it has reason. Obviously the extent of this ability varies, but the point is that an animal possesses this.}
#{471}{}{Go on.}

{470}{}{[他呢嘴笑着，显然急于炫耀他的天才]我一直对植物着迷，它们与动物非常不同，但却惊人地相似。当你看一种动物，你很清楚地知道它能思考，动物可以感知到周围环境，会有痛苦和恐惧。每种动物在这方面的程度可能各不相同，但关键是动物拥有这些能力。}
{471}{}{[继续]}


#{480}{}{When you look at a plant though, do you also think this？ If you kick a plant, does it fight back？ Does it respond to you in anyway？ Does talking to a plant affect its growth？ Some cultures before the Great War tested such theories. A people known as the Germans conducted experiments which lead them to believe that plants are capable of emotions and that one could promote healthy growth with talk, attention, and affection.}
#{481}{}{But plants lack a nervous system, and without one what you're suggesting just isn't possible.}
#{482}{}{I think all forms of life perceive in some way or another.}
#{483}{}{Those spore plants I've encountered sure fight back. So yeah, I'd say plants feel something.}

{480}{}{当你看着植物的时候，你是否也有这么想过？如果你踢一棵植物，它会反击吗？它对你的行为会有什么反应？和植物对话会影响它的生长吗？在大战争之前的一些科学家对这种理论进行了实验。一个被称为德国人的民族曾经做了实验，其结果让人相信植物是有情感的，而且可以通过谈话、注意和情感来促进其成长。}
{481}{}{但是植物并没有动物那样的神经系统，没有这个系统，你所说的东西都不会存在的啊。}
{482}{}{我认为所有形式的生命都可以用某种方式感知到外界。}
{483}{}{那些我遇到的孢子植物都会咬人，如果被打它们也会反击。所以，我会说我认为植物是有感知能力的。}


#{490}{}{And you would not be alone in thinking that. I too was skeptical at first. But you see, in the twentieth century, the United States government conducted similar experiments with a focus on communication. Sure, all forms of life have some means of self-damage detection, otherwise known as pain, but do they communicate this pain in some way？ And what was the conclusion of these experiments？ The idea of biocommunicationhat plants are sentient.}
#{491}{}{Are you suggesting that plants are almost like humans？}


{490}{}{并不是只有你这么想，起初我也持怀疑态度。但在20世纪，美国政府进行过类似的实验，其测试的重点是交流。所有形式的生命都有一些自我伤害的检测手段，也就是所谓的痛苦，但是他们能在某种程度上表达了这种痛苦吗？这些实验的结论非常有趣，当我们把电极接到植物上面时，如果我们伤害植物，电极会接收到电流。而且植物之间可能也存在着某种通迅。}
{491}{}{你是说植物就像人一样吗？}



#{500}{}{And you would not be alone in thinking that. In the twentieth century, the United States government conducted similar experiments with a focus on communication. Sure, all forms of life have some means of self-damage detection, otherwise known as pain, but do they communicate this pain in some way？ And what was the conclusion of these experiments？ The idea of biocommunicationhat plants are sentient.}
#{501}{}{Are you suggesting that plants are almost like humans？}

{500}{}{并不是只有你这么想，起初我也持怀疑态度。但在20世纪，美国政府进行过类似的实验，其测试的重点是交流。所有形式的生命都有一些自我伤害的检测手段，也就是所谓的痛苦，但是他们能在某种程度上表达了这种痛苦吗？这些实验的结论非常有趣，当我们把电极接到植物上面时，如果我们伤害植物，电极会接收到电流。而且植物之间可能也存在着某种通迅。}
{501}{}{你是说植物就像人一样吗？}


#{510}{}{I'm suggesting that they COULD be like humans. And as you can see, I was right. They just required a little help.}
#{511}{}{A little help？}

{510}{}{我的意思是他们可能像人类一样。正如你所见，我是对的，事实上只要我们给一点助力，它们就能更进一步。}
{511}{}{一点助力？}


#{520}{}{Gene-splicing！ Through the magic of science, I was able to develop a botany sentience serum. But giving the plants human-like intelligence was only half of the equation. In order to fully utilize such intelligence, I knew they would require a human-like body and senses.}
#{521}{}{Ah, which is where the 'fresh human cadavers' come in. You must tell me how you were able to get the plant life to interface with and take control of a human nervous system. And a dead one, at that. I wouldn't believe it were possible if I hadn't seen it firsthand.}

{520}{}{基因剪接！通过科学的魔力，我开发出一种植物的知觉血清。这个研究是划时代的，但是单纯的植物形态只能让这种血清发挥一半的能力，为了充分发挥血清的潜力，我知道它们需要一个像人一样的身体和感官。}
{521}{}{啊，这就是"新鲜的人类尸体"的切入点。你必须告诉我，你是如何让植物的生命与人类神经系统相联系的，要知道两者仍然是完全不同的生命类型。如果不是亲眼目睹你的研究成果，我就不会相信这是可能的。}



#{530}{}{Very well, I cannot promise you will fully comprehend what I am about to say, but I will do my best to explain it to you. [With the zeal of a preacher raving about his god to a rapt listener, he spends two hours detailing the process of his experiments, obviously taking great pride in his accomplishments.]}
#{531}{}{[MORE]}

{530}{}{我不能保证你会完全理解我要说的话，但我会尽力向你解释。[申博士就象一位热心牧师一样，他花了两个小时向你详细描述他的研究，显然他为自己的成就感到非常自豪]}
{531}{}{[更多]}


#{540}{}{And so now you understand, I hope？}
#{541}{}{Yes, I do. It seemed totally impossible, but the way you've explained it makes complete sense. And the thing about the sponges, absolute genius！ Morbid, but genius. But there was one thing you didn't explain. Where exactly are you getting these 'fresh human cadavers'？}

{540}{}{现在你明白了吧，我希望你能听得懂。}
{541}{}{这太神奇了，这似乎是完全不可能的，但你解释的方式却是完全合理的。你是一位绝对的天才！病态，但绝对是天才！有一件事你没有解释，你到底在哪里搞到这些新鲜的尸体？}



#{550}{}{Now hold on there a minute. Dr. Wong will be a bit of an obstacle here. If he were removed from the picture, things would go much more smoothly. Give Dr. Wong the sample. Even if he distrusts me, his curiosity will getter the better of him and he'll accept it. Once the sample has been stored away, find a way to eliminate Dr. Wong without alerting the other Shi. Perhaps an overdose of some sort. Do this, and I'll see that your reward is tripled.}
#{551}{}{I'll see what I can do.}
#{552}{}{If you want Wong dead, you'll need to give me something up front.}
#{553}{}{You know, this is all getting a bit complicated. I think I'd rather just massacre you and then go massacre the Shi.}
#{554}{}{There's no way I'm killing Dr. Wong for you. I'm done here.}

{550}{}{王博士的确是一个障碍，如果把他从照片上删除，事情就会顺利得多。你把样本给王博士就可以了，即使他不信任我，他的好奇心也会让他把这些种子接下来的。当种子被存储起来之后，你就在不惊动旁人的情况下把王博士干掉，如果你能完成这件事，我会给你3倍的奖励。}
{551}{}{我看看我能做什么。}
{552}{}{如果你想要王博士死，你需要给我一些行之有效的东西。}
{553}{}{你知道，这一切都变得有点复杂了。我想我宁愿杀了你，然后再去屠杀始族。}
{554}{}{我不会杀王博士，我们到此为止。}


#{560}{}{Excellent. And what of Dr. Wong？}
#{561}{}{He is still alive. I'll return once he's out of the picture.}
#{562}{}{I'm not going to kill Dr. Sheng for you. I gave them the plant sample, and now I'm done helping you.}

{560}{}{你好，王博士怎么样了？}
{561}{}{他还活着，我解决了这件事之后再回来。}
{562}{}{我不会为了你杀了王博士。我给了他们植物样本，现在我们到此为止。}


#from 240
#{570}{}{I need them put down, and you look more than capable of the task.}
#{571}{}{Why don't you send these, uh, more successful ones in there to take care of them？}
#{572}{}{Sounds fun. I'll do it.}
#{573}{}{What's in it for me？}
#{574}{}{I'm not interested in cleaning up your messes.}

{570}{}{我需要让它们"离开"我的实验室，你看起来有能力完成任务。}
{571}{}{为什么你不让你的作品去做这件事呢？}
{572}{}{听起来有趣。我会做这件事。}
{573}{}{我有什么好处？}
{574}{}{我对你的事情不感兴趣。}



#{580}{}{They will not attack their own. They understand why I must now dispose of their less-fortunate brethren, but they will not carry out the task themselves. That left me in a rather delicate situation. Which is why I was so pleased to learn of your approach. So, will you assist me？}
#{581}{}{All right. I'll do it.}
#{582}{}{What's in it for me？}
#{583}{}{I'm not interested in cleaning up your messes.}

{580}{}{它们不会攻击自己的同类。它们明白为什么我必须抛弃它们那些不那么幸运的兄弟，但它们就是不执行任务。这使我陷入了一种相当微妙的境地。这就是为什么我很高兴你来到这里的原因，那么，你愿意帮我吗？}
{581}{}{好吧。我会做它。}
{582}{}{我有什么好处？}
{583}{}{我对你的事情不感兴趣。}



#{590}{}{The laboratory is right up there to the north. The sentry will let you through. Be careful. These creatures are incredibly strong, so try not to let them get too close. Oh, and beware of the poisonous spore they shoot out. But do not worry. I have an antidote, should you get poisoned.}
#{591}{}{Okay. I'll be back.}
#{592}{}{So they're incredibly strong and have poisonous projectiles？ On second thought, I'm going to have to pass.}

{590}{}{实验室这里的北面，门口有一个我的哨兵，它会让你通过的。你要小心一点，我的作品非常强壮，所以尽量不要让它们太靠近。哦，还要当心它们喷出的有毒孢子。但不要担心，我有解药。}
{591}{}{好吧。我马上就回来。}
{592}{}{所以它们非常强壮，而且还会朝我扔带毒的孢子？再想想，我还是不去了。}



#{600}{}{I shall give you money, of course. Also, I have information that I believe would be of great interest to you. So, will you assist me？}
#{601}{}{All right. I'll do it.}
#{602}{}{I'm not interested in cleaning up your messes.}

{600}{}{我当然会给你钱。而且，我有一些你会很感兴趣的信息。那么，你愿意帮我吗？}
{601}{}{好吧。我会做它。}
{602}{}{我对你的事情不感兴趣。}


#{610}{}{[Looks at you expectantly.]}
#{611}{}{I'll come back after I've taken out the creatures in the lab.}
#{612}{}{All the creatures in the lab are dead.}
#{613}{}{All the creatures in the lab are dead, but I've been poisoned. You said something about an antidote？}

{610}{}{[用期待的眼光看着你]}
{611}{}{我把实验室里的生物都清理后再回来。}
{612}{}{所有在实验室里的生物都死了。}
{613}{}{所有在实验室里的生物都死了，但我中毒了，你有解药吗？}


#{620}{}{Yes, I shall administer it at once. Here.}
#{621}{}{Ah. I feel better already.}

{620}{}{当然，我马上为你注射。}
{621}{}{啊，我感觉好多了。}


#{630}{}{It is a pity to lose those specimens, but a necessary evil to reclaim my laboratory. You have done well. Here is your monetary reward. [He hands you $1000.] The second half of your reward is information ？and a second task to go with it.}
#{631}{}{It is a pity to lose those specimens, but a necessary evil to reclaim my laboratory. You have done well. Your reward is information ？and a second task to go with it.}
#{632}{}{Let's hear it.}
#{633}{}{Forget it. Keep your information. I'm done working for you.}

{630}{}{丢失了这些标本真是让人可惜，但收回我的实验室是一件很有必要的事。你做得很好。你奖励的前半部分是信息，后半部分是这个[他给你$1000]。}
{631}{}{丢失了这些标本真是让人可惜，但收回我的实验室是一件很有必要的事。你做得很好，还有第二项任务。}
{632}{}{我在听。}
{633}{}{就这样吧，我们到此为止。}


#{640}{}{Exellent. And the Shi have the sample I gave you？}
#{641}{}{Oh, uh …… No, actually. I forgot to give it to him first.}

{640}{}{你把样品给始族了吗？}
{641}{}{哦，还没有，实际上，这件事我忘记了。}

#{700}{}{You clear out Dr. Sheng's lab.}
#{710}{}{You deliver plant seeds to Dr. Sheng.}

{700}{}{你把申博士的实验室清理干净了。}
{710}{}{你把植物的种子送到申博士那里了。}

{800}{}{*gasp* Ahhh……}
