{100}{}{你看到一个很矮的始族人。}
{101}{}{你看到王宜慈博士。}
{102}{}{你看到一个很矮的始族人。}
{103}{}{我可以帮你什么吗？}
{104}{}{嗯嗯？}
{105}{}{你谁？}
{106}{}{我听说你有某个人的脾脏。}
{107}{}{你是谁？}
{108}{}{你在这里是干什么的？}
{109}{}{不，谢谢。就这样。}
{110}{}{我一定要承认，我不会说你的语言。你应该要与李健谈谈，他会说各种不同的语言。}
{111}{}{啊！}
{112}{}{我是王博士，我是这里的主管科学家。}
{113}{}{更多的问题。}
{114}{}{谢谢，再见。}
{115}{}{我是负责监督这里科学实验的人。我也是负责这里电脑网络的人。}
{116}{}{你在计划着什么？}
{117}{}{要如何才能够进入电脑网络呢？}
{118}{}{我还有一些问题。}
{119}{}{我知道了，再见。}
{120}{}{啊，但如果我告诉你我的计划，那每一个人都会知道。那些计划是秘密的。}
{121}{}{好，好。我还有其它的问题。}
{122}{}{谢谢。再见。}
{123}{}{如果我用一把枪指着你逼你跟我说呢？}
{124}{}{如果你是说如何侵入电脑的话，你猜我会不会找人把你杀了呢？}
{125}{}{你不会真的把我杀掉了吧？}
{126}{}{也就是说你对我进入电脑不反对？}
{127}{}{我还有一些问题。}
{128}{}{你当然会。再见。}
{129}{}{那我就要把那种行为视为是一种威胁。}
{130}{}{让我们试试看吧。}
{131}{}{我只是开玩笑的。我还有一些问题。}
{132}{}{[他笑着] 我们一定要保护自己的。}
{133}{}{嗯，对。对于我进入电脑，你会反对吗？}
{134}{}{对。我还有一些其它的问题。}
{135}{}{再见。}
{136}{}{如果你有办法说服我的守卫让你进去的话...}
{137}{}{如果我用一把枪指着你呢？}
{138}{}{很好。我还有更多的问题。}
{139}{}{嗯。我知道了，再见。}
{140}{}{嗯，对！}
{141}{}{你还有吗？很好，基特需要它。}
{142}{}{那是一个人的脾脏啊，你这个疯子！}
{143}{}{你知道那种酒是要配肝，而不是脾脏的，对不对？}
{144}{}{你知道那是一个人的脾脏，对不对。}
{145}{}{谁是基德啊？现在那是我的脾脏了，我要把它配点豆子和葡萄酒，作为晚餐吃了。}
{146}{}{基德是那个脾脏原来的主人。他喝醉了并且把它不小心卖给了朱流。}
{147}{}{他需要那个脾脏才能够活下去，你知道吗？那是从他的身体里活生生取出来的。}
{148}{}{那我看我把你杀了之后再把它取回去好了。}
{149}{}{卖了就是卖了。他不能拿回去了。抱歉，基德只好没有脾脏了。}
{150}{}{[更多]}
{151}{}{那是一个人的脾脏？朱流并没有跟我说呀！}
{152}{}{不过由于你那样的不客气，我决定拿它来做实验。}
{153}{}{告诉你的朋友叫他在明天之前来，我会很高兴的还他的。我希望你能够及时的把它装回去。}
{154}{}{很好。}
{155}{}{哈哈！我也看过那部电影。等一下...你在说什么？你是说...？}
{156}{}{是的，那是一个人的脾脏。}
{157}{}{事实上，你这个人态度很不好，因此我不跟你说话了。再见。}
{158}{}{[完成]}
{159}{}{啊！卫兵！有个“老外”入侵者在这里！}
{160}{}{你有什么设计图要给我吗？}
{161}{}{李健叫我马上将这些东西给你。}
{162}{}{是的，我应该到那里拿？}
{163}{}{不，还没有。}
{164}{}{去与李健谈，他会告诉你，你未来会发生什么事的。谢谢你，利用这些资料，我们应该能够确保我们的实验成功。再见。}
{165}{}{我还有一些问题。}
{166}{}{再见。}

#added by killap - expansion pack

#bio specimen begin
#{200}{}{I found this corpse stashed over at the Hubologists' base. I believe it might be your missing Xeno Project specimen.}
#{201}{}{Yes, it is indeed! My predecessor had much invested in this subject and was quite distressed when it went missing. Although he is now gone, we still may have some use for this specimen. Thank you for retrieving this.}
#{202}{}{No problem. See you later.}
#{203}{}{Hold on there. No one said I did this for free.}
#{204}{}{Correct. Nor did anyone ask you to retrieve the subject. You did that and brought it here of your own volition. Now the stolen subject has been returned to its rightful owners, and we thank you for it.}

{200}{}{我发现这具尸体藏在哈伯教的基地，我想可能是你丢失的Xeno项目标本。}
{201}{}{是的，这的确是！我的前任在这个问题上投入了大量的资金，虽然他现在已经不在了，但当这个标本失踪的时候，我感到很痛苦。这个标本对我们仍有一些用处，谢谢您！}
{202}{}{没问题，再见。}
{203}{}{等等，没有人说这个东西是免费的。}
{204}{}{没错，但也没有人要求你找到这个，既然你这样做了，还把它带到这里来。现在被偷的东西已经归还给它的合法主人，我们感谢你。}


#{205}{}{That's nice, but I found it, so if you want it back, then it's going to cost you.}
#{206}{}{I don't have time for this...Guards!}
#{207}{}{[The man looks like he is about to yell, then calms down.] Fine. Here is $500. More than enough for something that always belonged to us. Now leave, I'm a busy man.}
#{208}{}{Pleasure doing business with you. Bye.}
#{209}{}{Oh, shit!}
#{210}{}{Let's dance!}


{205}{}{很好，但这是我找到的，所以如果你想要它回来，你就需要给我报酬。}
{206}{}{我没有时间和你在这里废话...警卫！}
{207}{}{[这个男人看起来就要大喊大叫了，然后平静下来]好，这里是$500。为了让我们拥有属于自己的东西，现在走吧，我很忙。}
{208}{}{和你做生意很愉快，再见。}
{209}{}{喔，狗屎！}
{210}{}{让我开始跳舞吧！}


#{211}{}{You recover the missing Xeno Program specimen.}
#{220}{}{So where is it then? Are you trying to play games with me?}
#{221}{}{Sorry, I like to try and hoard as many items as I can. It's kinda my thing.}
#{230}{}{I don't have time for this. Come back when you have the specimen.}


{211}{}{关于你要找的Xeno程序标本。}
{220}{}{那么，它在哪里？你想和我玩游戏吗？}
{221}{}{对不起，我现在有点事情，一会再回来。}
{230}{}{我没有时间理你，当你有标本的时候再来。}



#{240}{}{[He sniffs the air.] What is that smell? Like rotten meat. [He looks at you and raises an eyebrow.]}
#{241}{}{Oh, you must be smelling this body I found. I'm not really sure why I'm carrying it around, to be honest.}
#{242}{}{Huh-huh! [You pull out the decomposing corpse] Stinky body! U want?}

{240}{}{[他吸着鼻子] 那是什么味道？像死尸[他看着你，皱起了眉毛]}
{241}{}{哦，你闻到的一定是我找到的这具尸体。老实说，我也不太清楚为什么要随身带着它。}
{242}{}{[你把腐烂的尸体拉出来]一个惊喜！一具腐烂的尸体！你想要这个？}


#{250}{}{Wait a second, that's the subject from the Xeno Project! My predecessor had much invested in this subject and was quite distressed when it went missing. Although he is now gone, we still may have some use for this subject. Thank you.}
#{251}{}{No, I do not want— Wait a second, that's the subject from the Xeno Project! My predecessor had much invested in . . . [He notices your blank stare.] Ahem. I mean, thank you for the body. Good job. Don't bring any more though. This is enough. Bye now!}
#{252}{}{Bye Bye!}
#{253}{}{Me hoard tings. Me hide it.}

{250}{}{等等，这是Xeno项目的标本！我的前任在这个问题上投入了大量的资金，虽然他现在已经不在了，但当这个标本失踪的时候，我感到很痛苦。这个标本对我们仍有一些用处，谢谢您！}
{251}{}{不，我不要，等等，这是Xeno项目的主题！我的前任在这个问题上投入了大量的资金[他注视着你眼睛]，嗯，我的意思是，谢谢你把它带回来，再见！}
{252}{}{再见！ }
{253}{}{不，这东西是我的。}

#bio specimen end

#dr sheng begin
#{300}{}{So what's the deal with this Dr. Sheng?}

{300}{}{关于申博士，你能告诉我些什么？}

#{310}{}{How do you know about Dr. Sheng? Eh, I suppose it doesn't matter. Dr. Sheng Ming was a brilliant, but rather unpleasant man who served as my predecessor. He is no longer of any great relevance here.}
#{311}{}{Well if he's not relevant to you, then why should *I* care? Let me ask you something else.}
#{312}{}{So what happened to him?}

{310}{}{你怎么知道申博士的事的？这和你没关系，申明博士是一位才华横溢但相当令人不愉快的人。他是我的前任，他在这里已不再重要了。}
{311}{}{嗯，如果你不愿意说，那*我*为什么要关心你呢？让我问你一些别的问题。}
{312}{}{他发生了什么事？}

#{320}{}{What happened? I'd say he lost his mind. During his experiments he stumbled upon something which I admit was rather remarkable, but it was also extremely dangerous and in no way related to the goals of the Shi. But that did not matter to Dr. Sheng. He became obsessed with his creation and since his experiments were deemed too dangerous to continue here, he decided to take them elsewhere. He left on sabbatical and never returned. That is when I stepped up to fill his position.}
#{321}{}{What kind of experiments was Dr. Sheng performing? And what exactly was his big discovery?}
#{322}{}{So where is Dr. Sheng now?}

{320}{}{发生了什么事？我得说他疯了。在他的实验中，他偶然发现了一些我承认是相当了不起的东西，但它也极其危险，而且与始族的目标毫无关系。但这对申博士来说并不重要，他开始沉迷于自己的创作，因为他的实验被认为太危险，不能继续在这里进行下去，所以他决定把它们带到别处。前段时间他在休假时彻底失踪了，再也没有回来。在这个时候，我挺身而出，填补了他的职位。}
{321}{}{申博士在实验里发现了什么？}
{322}{}{那么，申博士现在在哪里？}


#{330}{}{As a man of science, I respect your inquisitive nature. However, I'm afraid I am not willing to share the secrets of the Shi with you, stranger.}
#{331}{}{So where is Dr. Sheng now?}
#{332}{}{Fine, you keep your fancy secrets. I have secrets of my own, you know. Better secrets than you could ever possibly imagine.}

{330}{}{作为一个科学家，我尊重你的好奇心。但是，恐怕我不愿意和你分享这个秘密，陌生人。}
{331}{}{那么，申博士现在在哪里？}
{332}{}{很好，你保留着你的秘密，我也有自己的秘密，比你想象中更好的秘密。}


#{340}{}{[He smiles politely.] I'm sure you do. Now if you will excuse me, I have plenty of work that needs doing. Good day.}
#{341}{}{[DONE]}

{340}{}{[他礼貌地微笑]我肯定你会的。希望你能谅解我，我还有很多工作要做，这是美好的一天。}
{341}{}{[完成]}


#{350}{}{Dr. Sheng was escorted a day or so to the south. He took up residence in some abandoned home, if I'm not mistaken. He was only supposed to be gone for a month, but it's been much longer and we have yet to hear from him. If I were to guess, I would say he was either destroyed by his own creations, or else fell victim to the numerous hazards of the wasteland.}
#{351}{}{One of your lead scientists could be dead, and you don't care? You're not even going to go look into it?}
#{352}{}{I think I'd like follow up on this Dr. Sheng guy. Could you give me his last known location?}
#{353}{}{Well, that's that. Let me ask you something else.}

{350}{}{申博士最后被护送到南方，离这里一天左右的路程，如果我没记错的话，他在一些被遗弃的房子里住了下来。他的假期本应该是一个月，但时间已经很长了，我们也没有再收到他的信息。如果我没猜错的话，我打赌他要么被自己的创造物摧毁了，要么已经死在废土上的各种危险中。}
{351}{}{你们当中的一个科学家可能已经死了，你不关心吗？你甚至不打算去看他？}
{352}{}{我想我想要跟踪这个申博士。你能告诉我他最后的位置吗？}
{353}{}{嗯，就是这样。让我问你一些别的问题。}



#{360}{}{You'll have to excuse me for seeming so callous about the matter. The truth is, Dr. Sheng was not very popular around here and I do not believe any of us miss him in the slightest.}
#{361}{}{I think I'd like follow up on this Dr. Sheng guy. Could you give me his last known location?}
#{362}{}{I see. Let me ask you something else.}

{360}{}{你必须原谅我对这件事在表面上如此麻木不仁。事实上，申博士在这里不是很受欢迎，我相信我们中的任何一个人都不会对他有丝毫的思念。}
{361}{}{我想找到这个申博士，你能告诉我他最后的位置吗？}
{362}{}{我明白了，让我问你一些别的问题。}

#{370}{}{I suppose I could... I must admit I am somewhat curious to learn of his fate. Here, I'll mark Dr. Sheng's last known location on your mapping device. But I must warn you that it could prove to be highly dangerous. Of course, it is always dangerous out there in the wastes. Anyway, if you find something of interest, do let me know.}
#{371}{}{Thanks, I'll do that. Bye.}
#{372}{}{Let me ask you something else.}

{370}{}{我想我可以...我必须承认，在科学研究的角度，我有点想知道他的命运。我会在你的地图设备上标记申博士最后的位置。但我必须警告你，你接近那里可能是非常危险的。当然，在废土中什么地方都是很危险的，但不管怎样，如果你有什么发现，一定要告诉我。}
{371}{}{谢谢，我会的，再见。}
{372}{}{让我问你一些别的事情。}


#{380}{}{Dr. Sheng is still alive and he's created some kind of plant that takes root in and controls human corpses.}

{380}{}{申博士他还活着，他创造了一种植物，可以扎根并控制人类的尸体。}

#{390}{}{So he has achieved some success with his Xeno Project. How fascinating ... and disturbing. We put an end to his sentient plant experiments here after we lost one our techs. When he left to continue his research, I assumed he'd fall victim to his own creations. Has he managed to assume some form of control over them?}
#{391}{}{Yeah, some of them seem to be subservient. They even refer to him as 'master.'}

{390}{}{所以他的Xeno项目取得了一些成功，多么的迷人...和让人不安。在我们失去了一个技术人员之后，我们结束了他在这里的植物实验。当他离开去继续他的研究时，我认为他会成为他自己创作的牺牲品...他有没有想办法对这些东西进行某种形式的控制？}
{391}{}{在我看来应该是有的，他们甚至称他为"主人"。}


#{400}{}{Hmm... If he were to somehow establish an army of those plant-creatures, that would not bode well for the Shi. I was hoping it wouldn't come to this, but it seems we have no choice but to ensure that Dr. Sheng and his experiments are eliminated. Since he trusts you enough to allow you get close to him, you are the best candidate. Is that something you'd be willing to do? You would be compensated, of course.}
#{401}{}{It'd be a pleasure. The guy and his whole operation creeps me out.}
#{402}{}{What kind of compensation are we talking here?}
#{403}{}{Not interested. Dr. Sheng's your problem—you guys can deal with him.}

{400}{}{如果他以某种方式建立一个植物军队，这可能会意味着历史重演...。我本来希望不会出现这种情况，但似乎我们别无选择，只能确保申博士和他的实验被淘汰。既然他信任你，让你接近他，你就是最好的人选。你愿意做这件事吗？当然，这是有报酬的。}
{401}{}{好，那个家伙和他的糖浆人都使我毛骨悚然，我会去干这件事。}
{402}{}{会是什么样的报酬呢？}
{403}{}{我不感兴趣，申博士是你们自己的问题。}

#{410}{}{The Shi will be most grateful for this service. Once Dr. Sheng and all of his creations have been eliminated, report back to me to receive your reward.}
#{411}{}{[DONE]}

{410}{}{如果申博士和他所有的创造物都被消灭，始族会非常感激你的。届时你向我回报，就会有相应的报酬。}
{411}{}{[结束]}

#{420}{}{I'll leave that up to you. We could grant you weapons, supplies, or money. You may decide once the task is complete.}
#{421}{}{All right. I'll do it.}
#{422}{}{Not interested. Dr. Sheng's your problem—you guys can deal with him.}
#{423}{}{All right. I'll do it. But before I go, Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.}

{420}{}{我们可以给你武器、补给、或者金钱。一旦任务完成，你可以决定要什么。}
{421}{}{好吧，我干这件事。}
{422}{}{我不感兴趣，申博士是你们自己的问题。}
{423}{}{好吧，我会这样做的。但是在我走之前，申博士让我把这个植物样品交给你，他说这应该能帮助你达到制造防辐射植物生命的目标。}


#{430}{}{Fair enough. We will handle the problem ourselves, but it will have to wait, as we don't have the resources to expend at the moment. Hopefully it won't be too late once we are able to act. In the meantime, if you should change your mind, please let me know.}
#{431}{}{Don't count on it. Bye.}
#{432}{}{I'll think about it. Bye.}
#{433}{}{We'll see. Let me ask you something else.}

{430}{}{好，我们会自己处理这个问题，但现在因为人手问题，我们没法马上去做这件事，希望采取行动的时候不会太迟。另外，如果你改变主意，我们可以再谈这件事。}
{431}{}{不用指望了，再见。}
{432}{}{我会考虑的，再见。}
{433}{}{我会考虑的，让我问你一些别的问题。}

#{440}{}{I don't suppose you have changed your mind? Will you help us eliminate Dr. Sheng and his creations?}
#{441}{}{Nope, I actually wanted to ask you about something else.}
#{442}{}{Alright, I'll take him out for you.}
#{443}{}{I'll do it, but for a price. You were talking about compensation before?}

{440}{}{你改变了主意了吗？你能帮我们消灭申博士和他的创造物吗？}
{441}{}{不，我实际上想问你一些别的事情。}
{442}{}{好吧，我带他出去找你}
{443}{}{我会做这件事，但不是免费的，报酬是什么？}




#{450}{}{Our scouts have reported that Dr. Sheng and his experiments have been destroyed. Such a waste of a brilliant mind... Anyway, you may claim your reward. Are you interested in weapons, supplies, or cash?}
#{451}{}{Our scouts have reported that Dr. Sheng and his experiments have been destroyed. Such a waste of a brilliant mind... Anyway, we never asked you to get so involved, but we are grateful. For your troubles, you may claim a reward. Are you interested in weapons, supplies, or cash?}
#{452}{}{I'll take weapons.}
#{453}{}{I could always use more supplies.}
#{454}{}{Just give me money.}
#{455}{}{Keep your reward. I only did it because it was the right thing to do.}

{450}{}{我们的侦察兵报告说，申博士和他的实验已经被摧毁了。这样一个杰出的头脑...不管怎样，你可以得到你的报酬，你对武器、用品或现金感兴趣吗？}
{451}{}{我们的侦察兵报告说，申博士和他的实验已经被摧毁了。这样一个杰出的头脑...不管怎样，我们非常感激。为了补偿你在这件事上的麻烦，你可以得到你的报酬，你对武器、用品或现金感兴趣吗？}
{452}{}{[武器]}
{453}{}{[补用品]}
{454}{}{[钱]}
{455}{}{不需要，我之所以这么做，是因为这是正确的做法。}


#{460}{}{Here you go. [He hands various high powered weapons]}
#{461}{}{[DONE]}

#{470}{}{Here you go. [He hands you various supplies]}
#{471}{}{[DONE]}

#{480}{}{Here you go. [He hands you $5,000]}
#{481}{}{[DONE]}

#{490}{}{The Shi appreciates your assistance. Now, I have much work to do. Good day.}
#{491}{}{[DONE]}

{460}{}{这个给你[他拿出了一堆武器]}
{461}{}{[结束]}

{470}{}{这个给你[他拿出了一堆补给品]}
{471}{}{[结束]}

{480}{}{这个给你[他拿出了$5,000]}
{481}{}{[结束]}

{490}{}{始族感谢你的帮助。现在，我有很多工作要做。}
{491}{}{[结束]}



#{500}{}{Before I go, Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.}
#{501}{}{Dr. Sheng wanted me to deliver this plant sample to you. He said it should help you achieve the goal of creating radiation-resistant plant life.}
#{502}{}{Dr. Sheng wanted me to give you this plant sample as a gift, but I thought I should warn you that it's infused with his sentience serum. I don't know what it's supposed to do, but I'm pretty sure it won't be good for the Shi.}

{500}{}{在我走之前，申博士让我把这个植物样品给你。他说，它应该能帮助你达到制造防辐射植物生命的目标。}
{501}{}{博士，申博士希望我把这个样品给你。他说，它应该能帮助你达到制造防辐射植物生命的目标。}
{502}{}{博士，申博士希望我给你这个植物样品作为礼物，但我想警告这应该不是什么好礼物。我不知道它会发生什么，但我很确定它不会对始族有好处。}



#{510}{}{Interesting. [He takes the sample and stores it away.] My team and I will examine it later. I can't say I trust any gift from Dr. Sheng, but I suppose there is an off chance that it'll prove useful. We shall see. Now if there is nothing else, I should be getting back to work.}
#{511}{}{Interesting. [He takes the sample and stores it away.] My team and I will examine it later. I can't say I trust any gift from Dr. Sheng, but I suppose there is an off chance that it'll prove useful. We shall see. But I thought you were going to eliminate Dr. Sheng, not be his courier? In any case, I should be getting back to work.}
#{512}{}{Actually, I would like to ask you something else.}
#{513}{}{Goodbye.}
#{514}{}{Actually, I went through quite a bit of trouble to get that sample for you. I think it's worth a reward.}

{510}{}{[他拿走了样品，把它储存起来]这很有趣，我的团队和我将在以后研究它。我不能说我相信申博士的任何礼物，但我想这可能对我们有帮助。如果没有别的事，我就该回去工作了。}
{511}{}{[他拿走了样品，把它储存起来]这很有趣，我的团队和我将在以后研究它。我不能说我相信申博士的任何礼物，但我想这可能对我们有帮助。但我认为你应该把申博士和他的创造物消灭掉，而不是当他的邮差，不是吗？}
{512}{}{实际上，我想问你一些别的事情。}
{513}{}{再见。}
{514}{}{实际上，我费了好大的劲才为你弄到那个样品，我认为应该值得一份报酬。}



#{520}{}{Do you, now? The Shi did not solicit this plant sample from you, but if you feel your deeds have earned some compensation, I suppose we could spare this. [He hands you a super stimpak.] Now I really should be getting back to work.}
#{521}{}{Actually, I would like to ask you something else.}
#{522}{}{Thanks. Bye.}
#{523}{}{Really? You call this a reward? I'm gonna knock you around until something more valuable falls out.}

{520}{}{你认为？始族没有向你征求这个样品，但如果你认为你做的事已经值得给一份报酬，我想我们可以省下这笔钱[他递给你一个超级棒]，现在我要回去工作了。}
{521}{}{实际上，我想问你一些别的事情。}
{522}{}{谢谢，再见。}
{523}{}{你把这叫做奖励？我要把你打翻，直到有更值钱的东西暴出来。}


#{530}{}{[Takes the seed.] Thank you, I will dispose of this immediately. [He sighs.] I knew Dr. Sheng had lost it, but I didn't think he'd go so far as to try and destroy his own people. He must be dealt with immediately.}
#{531}{}{I agree. He's quite the madman.}

{530}{}{[他拿起样品]。谢谢，我会马上处理掉的，[他叹了口气]我们已经失去申博士了，但我从来没想过他会尝试摧毁他自己的同胞，他必须被处理掉。}
{531}{}{我同意。他是疯子。}

#{540}{}{*clutches heart* Wahh.}
#{541}{}{Urgh.}
#{542}{}{Dr. Wong!}

{540}{}{*心脏彭彭跳* Wahh.}
{541}{}{Urgh.}
{542}{}{王博士！}

#{600}{}{You eliminate Dr. Sheng for the Shi.}
#{601}{}{You deliver the plant sample to Dr. Wong.}
#{602}{}{You assassinate Dr. Wong.}

{600}{}{你消灭了申博士。}
{601}{}{你把植物样本交给王博士。}
{602}{}{你暗杀了王博士。}

#dr sheng end
#end added
