{100}{}{你看到一个店老板。}
{101}{}{你看到了朱流，一个店老板。}
{102}{}{你看到一个穿着整齐的男人。}
{103}{}{你好！欢迎来到我的商店，飞龙888。}
{104}{}{我可以帮你什么吗？}
{105}{}{嗯嗯！}
{106}{}{东西！}
{107}{}{你好吗？}
{108}{}{我正在寻找一些器材。}
{109}{}{我正在寻找一些讯息。}
{110}{}{再见。}
{111}{}{你要买什么东西吗？}
{112}{}{*点头*}
{113}{}{*摇头*}
{114}{}{这是我们有的东西。}
{115}{}{[结束]}
{116}{}{我恐怕那就是我能够帮你的了。再见。}
{117}{}{[完成]}
{118}{}{我是朱流，是这里的负责人，而这里是飞龙888，一间商店，也是一个“消息交流”的地方。}
{119}{}{什么样的消息？}
{120}{}{我知道了。我想要一些器材。}
{121}{}{在这个镇里发生的事很少有我不知道的。当然，你知道你想要问什么，对不对？你想要知道什么？}
{122}{}{我正想要升级我的器材。}
{123}{}{我在那里可以找到飞鸟设计图？}
{124}{}{我想要找一些燃料。}
{125}{}{我知道我需要一个FOB才能够使用油轮的电脑。}
{126}{}{我需要一些油轮的导航晶片。}
{127}{}{我正在找一个脾脏。}
{128}{}{我听说一些会飞的机器把整村的人都带到这附近来了。}
{129}{}{没事，再见。}
{130}{}{去与克拉克特谈吧，他就在哈伯教的营里。他是他们的主要科学家。}
{131}{}{谢谢，我需要再问一些事。}
{132}{}{谢谢。再见。}
{133}{}{到北方去看看，在那瓦罗。在那里的加油站附近有一个秘密的基地。}
{134}{}{谢谢，我需要再问一些事。}
{135}{}{谢谢，再见。}
{136}{}{你有试着到旧的避难所去找找看吗？我听说那里面有许多的资料以及科技。}
{137}{}{谢谢，我需要再问一些事。}
{138}{}{谢谢。再见。}
{139}{}{一个脾脏？哈哈！是，基德在一场赌局中输了自己的脾脏。我把它卖给了王博士。他好像对那很有兴趣。}
{140}{}{王博士？我在那里可以找到他？}
{141}{}{你怎样让脾脏不见的呢？}
{142}{}{谢谢，我需要再问一些事。}
{143}{}{谢谢。再见。}
{144}{}{王博士是钢铁王宫的科学家，到那里去找他吧。}
{145}{}{你怎样让脾脏不见的呢？}
{146}{}{谢谢，我需要再问一些事。}
{147}{}{谢谢。再见。}
{148}{}{他喝醉了。非常的醉。他整个晚上都提到他的脾脏，最后他把它拿去赌了。}
{149}{}{你把他的脾脏拿走了？}
{150}{}{我知道了，我还有一些问题要问。}
{151}{}{是的。}
{152}{}{我知道了，我还有一些问题要问。}
{153}{}{你有病，不是吗？}
{154}{}{再见。}
{155}{}{你是一个不知羞耻的人。我不要你在我的店里。下次再来吧。}
{156}{}{随便你。}
{157}{}{你说的机器不在这里，他们从北方飞过来，经过我们的头顶，然后朝海的方向飞去了。}
{158}{}{飞到海上？我要怎才能够到那里去？}
{159}{}{骗鬼吧，跟我说真话，不然我就把你杀了。}
{160}{}{嗯..我们没有一艘船可以航行那么远的。除了..}
{161}{}{除了..？}
{162}{}{谢谢你的“帮助”。我会去问别人的意见的。}
{163}{}{..除非你能够开动那艘旧油轮。那是一艘老船，但是却能够航行长距离。}
{164}{}{谢谢，我需要再问一些事。}
{165}{}{谢谢。再见。}
{166}{}{有人说哈伯教取得了大量的燃料。去跟他们谈吧。}
{167}{}{谢谢，我需要再问一些事。}
{168}{}{谢谢。再见。}
{169}{}{你应该去问问始族的科学家，也许他们能够帮你吧。}
{170}{}{谢谢，我需要再问一些事。}
{171}{}{谢谢。再见。}
{172}{}{你是我们的敌人。死吧！}
{173}{}{你将AHS-9杀了，对我们帮助很大。我希望我能够帮你。}
{174}{}{你是谁？}
{175}{}{我正在寻找一些器材。}
{176}{}{我正在寻找一些讯息。}
{177}{}{再见。}
{178}{}{你已经将它们给了哈伯教徒，不是吗？}
{179}{}{嗯..我可以问你一些事吗？}
{180}{}{嗯..再见。}


#RP 1.3
#{200}{}{What else can you tell me about the tanker?}

#{210}{}{Even if you could get the NavCom working and the tanker fueled up, you'll still need considerable good fortune if you really want the ship to sail again.}
#{211}{}{What do you mean by 'considerable good fortune?'}

#{220}{}{I mean, the hunk of junk is older than most ghouls. It would be a miracle if it didn't sink on you. That is all I meant.}
#{221}{}{I have a feeling that there's something you're not telling me about the tanker.}

#{230}{}{Perhaps there is. [smiles] Perhaps the wasteland has made you paranoid.}
#{231}{}{Listen, I need to find my tribe. Those bastards who took them are dangerous and need to be stopped.}
#{232}{}{Come on. What's so special about the tanker? We're just two people talking.}
#{233}{}{You sure? I'll make it worth your while.} #female
#{234}{}{I don't have time for these mind games. Goodbye.}


{200}{}{关于港口那艘油轮，你能告诉我什么？}

{210}{}{即使你能让油轮的电脑工作，并给它加满油，但如果你真的想让船再次航行，你仍然需要相当可观的好运才行。}
{211}{}{你说的"相当可观的好运"是什么意思?}

{220}{}{我的意思是，这艘"豪华游轮"的年纪比大多数食尸鬼还要老。如果它不沉在你身上，那真是一个奇迹。}
{221}{}{我有一种感觉，你没有告诉我关于这艘油轮全部的事。}

{230}{}{[微笑]也许有，也许没有，也许只是荒野让你变得偏执罢了。}
{231}{}{听着，我需要找到我的部落，那些绑走了他们的杂种是危险的，我要制止他们。}
{232}{}{这艘油轮到底有什么特别之处？现在说话的只有我们两个人了。}
{233}{}{你确定吗？我会让它"值"你一段时间。} #female
{234}{}{我没有时间玩这些脑力游戏，再见。}



#SPEECH >90%  Listen……
#{240}{}{Bah. They are nothing. However, it's not the tanker that's special. It's just a big rusty tanker like you said. Our submarine, on the other hand……}
#{241}{}{Submarine?}

{240}{}{这不过是一艘生锈的普通大油轮罢了，但另一方面，我们的潜艇……}
{241}{}{潜艇?}


#SPEECH <90%  Come on……
#{250}{}{Let's talk, then. But there's nothing special about the tanker. I give you my word.}
#{251}{}{What if I paid you to tell me?}

{250}{}{这艘油轮并没有什么特别之处，我向你保证。}
{251}{}{如果我愿意付你钱呢？}

#{260}{}{Hmm…… Business has been slow lately. I could use more customers. Or a donation from a very generous one. Say, $2000?}
#{261}{}{Here you go. But your information better be worth it.}
#{262}{}{$1500 and that's my final offer.}
#{263}{}{I don't think so. That's too much.}

{260}{}{近来生意清淡，更多的顾客我总是欢迎的，这个信息需要$2000。}
{261}{}{钱在这儿，你的信息最好是值得的。}
{262}{}{$1500，这是我最后的报价。}
{263}{}{我不这么认为，这个价太高了。}


#{270}{}{[Lao Chou pockets the $2000.] It's not the tanker that's special. It's just a big rusty tanker like you said. Our submarine, on the other hand……}
#{271}{}{Submarine?}

{270}{}{[朱流用你看不见的速度把钱装进口袋]这不过是一艘生锈的大油轮。另一方面，我们的潜艇……}
{271}{}{潜艇?}


#{280}{}{We have nothing further to discuss, then.}
#{281}{}{You sure? My lovely wife Miria will certainly make it worth your while.}
#{282}{}{Goodbye.}

{280}{}{我觉得我们没必要继续在这件事上谈下去。}
{281}{}{你确定吗？我可爱的妻子麦丽雅可能会让你觉得值得的。}
{282}{}{再见。}


#{285}{}{You drive a hard bargain. Fine, $1500.}
#{286}{}{Here you go. But your information better be worth it.}
#{287}{}{[Lao Chou pockets the $1500.] It's not the tanker that's special. It's just a big rusty tanker like you said. Our submarine, on the other hand……}
#{288}{}{Submarine?}

{285}{}{你很会讨价还价，好，就$1500。}
{286}{}{钱在这儿，但是你说的话最好值这个价。}
{287}{}{[朱流用你看不见的速度把钱装进口袋]这不过是一艘生锈的大油轮。另一方面，我们的潜艇……}
{288}{}{潜艇?}


#SPEECH <90% BUT PC IS FEMALE AND CH >=7 OR SEX APPEAL
#{290}{}{Well if you put it that way, I have been cooped up in this dusty shop for a long time. It has been a quite a while since I enjoyed the company of a charming woman like yourself.}
#{291}{}{[CONTINUE]}

{290}{}{嗯，如果你这样说的话，我每天都被关在这个尘土飞扬的商店里。离上一个象你这样迷人的女人来这里，已经有好长一段时间了。}
{291}{}{[继续]}


#{300}{}{[Hours past with no end in sight. You begin to suspect that Lao Chou may not be completely human. You black out, eventually.]}
#{301}{}{hhh…… What happened?}

{300}{}{[数小时过去了，看不到尽头，你开始怀疑朱流是不是一个人类。到后来你眼睛一黑，晕过去了]}
{301}{}{……发生了什么事？}


#{310}{}{You fainted as I moved us into the triple-lotus position, and I had to finish pleasuring myself with the grinning-panda kata. But a deal's a deal. It's not the tanker that's special -- it's just a big rusty tanker like you said. Our submarine, on the other hand……}
#{311}{}{Submarine?} 

{310}{}{你在我们做一个经典姿势的时候晕过去了，我只好用那只掉光毛的熊猫娃娃来解决问题。但交易就是交易，这么说吧，港口的不过是一搜生锈的普通油轮罢了。另一方面，我们的潜艇……}
{311}{}{潜艇？} 

#IF SPEECH <90% BUT PC IS FEMALE AND CH <7
#{330}{}{I…… don't think so.}
#{331}{}{Don't try and fight it now. You want me and you know it.}

#{340}{}{No, actually. You are not my type.}
#{341}{}{Oh, I see. You're not into women.}

#{350}{}{I am. I just do not find you very attractive. Perhaps if I were drunk.}
#{351}{}{You're obviously blind. Whatever. It's your loss.}

{330}{}{不……我不这么想。}
{331}{}{不要对抗你自己，你想要我，你知道的。}

{340}{}{实际上没有，你不是我喜欢的类型。}
{341}{}{哦，我明白了，你喜欢的不是女人。}

{350}{}{我只是觉得你不太吸引人。}
{351}{}{你显然是眼睛瞎了，这是你的损失。}


#IF SPEECH <90% BUT PC W/ MIRIA
#{360}{}{What are you proposing? Ahh…… well, I have been cooped up in this shop for a long time. I will reveal all I know in exchange for a sample of your lady friend's charms.}
#{361}{}{Miria, honey…… I guess you'll have to, erm, pump this guy for information.}
#{362}{}{I was joking, old man. Like I'd let you make time with my wife…… I'm leaving.}

{360}{}{你的建议，好像还不错……我在这家店已经关了很长时间了。为了换取你那位女士朋友的魅力，我会把我所知道的一切都告诉你。}
{361}{}{麦丽雅，亲爱的……我猜你得帮这个家伙一个小忙。}
{362}{}{我是在开玩笑，老头子。我和我妻子现在要离开了。}


#{370}{}{[You wait outside and hear faint moans from inside the Flying Dragon 8. An hour passes, and then another. You bang on the door, shouting, "Hurry up in there!" Finally, the moans become a primal scream.]}
#{371}{}{[Bang on the door] Hey, what are you two doing in there!?}

{370}{}{[你在外面等着，你听到店里面有微弱的呻吟声。一个小时过去了，另一个小时过去了，你砰地一拳砸在门上，大喊:"快点！"。最后，呻吟声变成了原始的尖叫。}
{371}{}{[把门踹开]嘿，你们俩在里面干什么？}


#{380}{}{A smiling Lao Chou emerges from his bedroom, still pulling on his pants. A few moments later Miria stumbles out behind him, looking dazed and confused but deeply satisfied] Your wife is a great deal more experienced than she looks.}
#{381}{}{I, erm, know. Now pull your damn pants up and tell me what's so special about the tanker.}

{380}{}{[朱流拉着他的裤子，微笑着从他的卧室里出来]。几分钟后，麦丽雅在他身后跌跌绊绊地走了出来了，看上去有点恍惚。朱流很满意地说:"你的妻子比她看起来更有经验。"}
{381}{}{嗯，我知道。现在把你的裤子拉起来，告诉我这艘油轮有什么特别之处。}


#{390}{}{There's nothing special about the tanker. It's just a big rusty tanker like you said. Our submarine, on the other hand……}
#{391}{}{Submarine?}

{390}{}{这么说吧，港口的不过是一搜生锈的普通油轮罢了。另一方面，我们的潜艇……}
{391}{}{潜艇？}

#Submarine?
#{400}{}{The Shi-Huang-Ti. My great grandfather, Ye Li, was its captain. He unleashed her nuclear fires like a horrible dragon upon California's coast.}
#{401}{}{No shit.}

{400}{}{是的，它的名字叫"始皇帝"， 我的外曾祖父李烨曾经是他的船长。"始皇帝"就像加利福尼亚海岸上一条可怕的巨龙一样，向这里发射了核导弹。}
{401}{}{干！}


#{410}{}{Ironically, a malfunctioning missile from our own ancestral nation went off course and exploded over the ocean near the submarine's location. The blast knocked out the Shi-Huang-Ti's systems, leaving Captain Ye Li and his crew stranded at sea.}
#{411}{}{That's karma for you.}

{410}{}{但讽刺的是，来自我们祖国的一枚故障的导弹偏离了航线，在靠近潜艇位置的海面上爆炸了。爆炸摧毁了"始皇帝"的系统，外曾祖父和他的船员被困在海上。}
{411}{}{这是报应。}


#{420}{}{But there was salvation. After weeks of drifting, the sub finally came to rest out in the shallow waters of the San Francisco bay. This city became our new home. We eventually restored the Shi-Huang-Ti; its targeting systems, its weapons. It has enough firepower to blow any potential invaders out of the water. So even if you got that old tanker running, it wouldn't get far, as the submarine will destroy any non-Chinese vessel that sails through the bay.}
#{421}{}{That sounds like a problem alright. So how would I get to the submarine?}

{420}{}{幸运的是，经过几周的漂流，潜艇终于在旧金山湾的浅水中搁浅了，这个城市成了我们的新家。在这里，我们最终修复了"始皇帝"，就和以前一样，它拥有足够的武器能将任何打算入侵这里的船变成珊瑚礁。所以即使你有了那艘旧的油轮，它也不会走得太远，因为潜艇的系统会扫描并摧毁任何驶进海湾的非中国船只。}
{421}{}{这听起来是个问题，好吧。这艘潜艇在那里？}

#{430}{}{You swim. Or take the motorboat at the docks. It is guarded, though, by one of our best soldiers, and he will not let an outsider like you past him.}
#{431}{}{You have any idea how I can get past him then, without shooting him in the face?}

{430}{}{你可以游泳，或者乘码头那艘生锈的汽艇过去。不过，我们一个士兵把守着它，他不会让像你这样的外人离开他视线范围的。}
{431}{}{有什么办法能让我能从他身边离开，又不用向他头上开枪吗？}


#{440}{}{He's under strict orders to guard it 24/7. He will not let anyone without the right password through.}
#{441}{}{I don't suppose you know it?}

{440}{}{他接到的命令是每天24小时，每周7天守着那里，他不会让任何没有正确密码的人通过的。}
{441}{}{你认为，我会觉得你不知道密码吗?}

#{450}{}{That depends. I don't suppose you have $10000 to ensure the continued prosperity of my shop?}
#{451}{}{Here's your $10000.}
#{452}{}{That's outrageous for a simple password. I'll only go as high as $5000.}
#{453}{}{No deal.}

{450}{}{知道与不知道视情况而定。我不觉得你有$10000来保证我商店的持续繁荣。}
{451}{}{这里是$10000。}
{452}{}{对于一个简单的密码来说，这太离谱了，$5000。}
{453}{}{我还是回头再来。}


#here's the $5000
#{460}{}{Ah, much appreciated. The password is XY8QIV2SHI. Others may be watching me after this, so don't forget the password. If ever we discuss it again, I'll need even more money for bribes.}
#{461}{}{Thank you. Goodbye.}

{460}{}{感谢您的惠顾，密码是XY8QIV2SHI，货品出门概不退换，如果你忘记了密码，那就请再次购买。出门之后别忘了给五星好评。}
{461}{}{再见。}

#pass barter check
#{470}{}{You are a crafty one, I'll give you that. Fine. I accept your offer. The password is XY8QIV2SHI. Don't forget it, or you'll have buy it from me again.}
#{471}{}{Thank you. Goodbye.}

{470}{}{密码是XY8QIV2SHI，货品出门概不退换，如果你忘记了密码，那就请再次购买。出门之后别忘了给五星好评。}
{471}{}{再见。}

#fail barter check
#{480}{}{Don't insult me with your meager offers. $10000. Take it or leave it.}
#{481}{}{Fine. Here's your $10000.}
#{482}{}{No deal.}

{480}{}{$10000，Yes OR No。}
{481}{}{好，这里是$10000。}
{482}{}{我还是回头再来。}


#No deal.
#{490}{}{Your loss then. I don't believe we have anything else to discuss. Goodbye.}
#{491}{}{Bye.}

{490}{}{这是你的损失，我们这件事就聊到这吧，再见。}
{491}{}{再见}
