#{100}{}{You see a humanoid covered in plant-growth. It drips green sludge.}
#{101}{}{You see one of Dr. Sheng's foul creations.}
#{102}{}{You see one of Dr. Sheng's foul creations. It looks like this one didn't turn out so well.}

{100}{}{你看到一个人形生物，它身上覆盖着各种藤蔓和苔藓，而且它还滴着绿色的污泥。}
{101}{}{你看到申博士的一个邪恶的创造物。}
{102}{}{你看到申博士的一个邪恶的创造物，看起来这个研究结果真的不是很好，至少以你的角度看真的不怎么好。}

#{200}{}{去与主人说话，人类。}
#{201}{}{Your body would make a fine host...}
#{202}{}{The master said you are off limits... for now.}

{200}{}{去和主人说话，人类。}
{201}{}{你的身体很适合发芽。}
{202}{}{主人说不能打你的身体。}


#{300}{}{[A half-dozen strange humanoid creatures slowly shamble toward you. Their cadaverous vine and moss-covered bodies make repulsive squelching sounds with each awkward step. The lead creature addresses you in a harsh rasp.] Master wants to speak with you. Come with us, human, and do not resist ... or we'll make a host of you.}
#{301}{}{[Shrug] This should be interesting. Lead the way.}
#{302}{}{I'm not going anywhere with you, plant ... creature ... things.}
#{303}{}{I don't have time for this shit.}
#{304}{}{Hold on. Who's your master? And what, exactly, are you?}

{300}{}{[有六个奇怪的人形生物慢慢地向你蹒跚而行，它们身上覆盖着各种藤蔓和苔藓，每一步都发出令人厌恶的咯吱咯吱的声音。领头的生物用一个粗糙的声音对你说]主人想和你说话。跟着我们一起来，人类，不要抗拒，不然我们会打你。}
{301}{}{[耸肩]这应该是有趣的，带路。}
{302}{}{我不会和你一起去任何地方，你们这些绿色畸形。}
{303}{}{我没有时间。}
{304}{}{你的主人是谁？你到底是什么？}


#{310}{}{You have no choice, human. Either come and speak to Master, or we shall resort to violence.}
#{311}{}{Then let's dance.}
#{312}{}{All right. I'll meet this master of yours.}

{310}{}{你没有选择，人类。要么和主人说话，要么我们打你。}
{311}{}{我们就在这里开始暴力好了。}
{312}{}{好吧，我来见见你的主人。}


#{320}{}{Master will answer all questions. Now, come.}
#{321}{}{I don't think so.}
#{322}{}{All right. I'll meet this master of yours.}

{320}{}{主人会说，你的问题，现在，来。}
{321}{}{我不这么认为}
{322}{}{好吧。我来见见你的主人。}

{400}{}{Uuuhhhhh...}
{401}{}{Grrraaah!}
{402}{}{Hheesssss...}
{403}{}{Ohhh...}

#{410}{}{The master says no one may enter.}
#{420}{}{The master says you may enter, human.}

{410}{}{主人说没有人可以进入。}
{420}{}{主人说你可以进来，人类。}

#{500}{}{You spray the creature and it gives off a heavy groan. Segments of the plant-growth covering it fall limp to the floor.}
#{501}{}{You spray the creature；it gives off a heavy groan and oozes into a puddle before your eyes.}

{500}{}{你向这个生物喷药，它发出一声沉闷的低吼，身上的一些植物部分松脱下来，掉到了地板上。}
{501}{}{你向这个生物喷药，它发出一声沉闷的低吼，身上的一些部分掉在地面上，成了一摊绿色的烂泥。}
