#Torpedo Console Techie

#{100}{}{You see a person in funny pajamas. He seems preoccupied.}
#{101}{}{You see a Shi submarine technician.}

#{150}{}{Uh, what are you doing, sneaking around like that?}
#{151}{}{Are you some kind of spy?}

{100}{}{你看到一个穿着技术服的人，他看起来心事重重。}
{101}{}{你看见一名始族潜艇技师。}

{150}{}{你偷偷摸摸地想做什么？}
{151}{}{你是间谍吗?}

#{200}{}{This is filthy, look at all that rust!}
#{201}{}{I can't fathom why we need to keep this running.}
#{202}{}{Those torpedoes are an accident waiting to happen.}

{200}{}{看看那些生锈的废物！}
{201}{}{我无法理解为什么我们需要保持这里的运作。}
{202}{}{这些鱼雷就是一堆在等着发生的事故。}



#{300}{}{I don't recall ever seeing you around here, what are you doing in the torpedo room? And who are you anyway?}
#{301}{}{You again? What are you still doing in the torpedo room? And who are you anyway?}
#{302}{}{I'm a last-minute addition to your tech team. Sorry for not informing you earlier. Oh, and I'm here to do some
 maintenance on the torpedoes. They look horrible, an accident waiting to happen!}
#{303}{}{I was added to your roster just recently. I was asked to work with the targeting systems of the torpedoes,
 since they've been acting up recently. I think it might be due to certain uncorrectable flaws in the design of the
 Sungsam motherboards.}
#{304}{}{I'm a repairman, freshly added to your roster. I'm supposed to be doing periodic maintenance on the torpedoes,
 since they look like hell! Look at all that rust! And the propellers look like they're about to fall off!}
#{305}{}{Sorry, wrong room.}

{300}{}{我记得曾在这里见过你，你在鱼雷室做什么？你到底是谁？}
{301}{}{你又回来了？你在鱼雷室做什么？你到底是谁？}
{302}{}{我最近加入技术团队的，很抱歉没有提前通知你。哦，安排我来这儿是要做什么来着？对，维修鱼雷！他们看起来很可怕，一场事故正在等着发生!}
{303}{}{我是最近才加到技术团队花名册上的，我被要求修正鱼雷的制导系统。报告上说这个系统近来工作都不正常，我认为这可能是由于某些不可逆转的设计缺陷造成的。}
{304}{}{我是一个修理工，我刚刚加入你的花名册，我的工作是定期维护鱼雷，没错，就是定期维护鱼雷。看看那些锈！看看那些螺旋桨马上要掉下来的样子！}
{305}{}{抱歉,错误的房间。}





#{310}{}{Oh, good to finally have a qualified mechanic on board. I've been meaning to fix these, but I just can't get over
 my fear of those torps. Did you know that they carry enough explosives to turn this entire vessel into finely ground scrap?}
#{311}{}{I'll exercise caution, I promise.}

{310}{}{哦，很好，终于有了一个合格的机械师了。我一直想解决这些问题，但请你做事小心点，这里的炸药足够把我们和整艘船一起炸上天。}
{311}{}{我会小心的，我保证。}


#{320}{}{They finally sent me a mechanic, after all those weeks of begging……}

{320}{}{在几个星期的乞讨之后，他们最后给我一个修理工……}

#{330}{}{Uh, you don't look like a mechanic. Frankly, I don't think you can tell a spanner from a screwdriver from the
 looks of it, so why don't you go back and help the rest of the guys, instead of loitering in the torpedo room? I don't
 want you to blow us up accidentally.}
#{331}{}{Fine, I'll go.}

{330}{}{呃，你看起来不像个机械师。坦白地说，我认为你甚至连螺丝刀和扳手都分不清，你为什么不回去帮助其他的？我不希望你把我们炸上天。}
{331}{}{好的，我去。}


#{340}{}{That's all fine and good, but, uh, why are you looking for the console in the torpedo room? It's in the room behind
 you. I need a mechanic, not another technician, so unless you are also a talented repairman, I need you to leave.}
#{341}{}{Actually, yes, I'm also a repairman, with quite a bit of experience in dealing with ancient technology. I believe
 I can handle those torpedoes. I'll get the propellers working properly and make sure they don't turn us into finely ground
 scrap.}
#{342}{}{Fine, I'll go.}

{340}{}{这一切都很好。但是你为什么要在鱼雷室找制导控制台呢？它在后面的房间里。我需要一个机械师，而不是另一个技术员，所以除非你也是一个有才能的机械师，否则请你离开。}
{341}{}{实际上，是的，我也是一个机械师，在处理古老的技术方面有相当多的经验。我相信我能应付那些鱼雷，我会让鱼雷推进器正常工作，也保证它不会把我们变成浮在海上的碎片。}
{342}{}{好的，我去。}


#{350}{}{Oh, specialists in both fields are not common in the wastelands. I guess I can trust you, so go ahead and fix those
 torpedoes so that I can finally feel a little safer.}
#{351}{}{Alright.}

{350}{}{哦，同时在这两个领域的专家在废土上并不多见。我想我可以信任你，你去解决这些问题吧，这样我会可以感觉安全点。}
{351}{}{好的。}



{360}{}{我现在很忙}
{361}{}{抱歉, 我现在很忙}

#{370}{}{Don't touch that!}
#{371}{}{What did I tell you?!}
#{372}{}{I warned you!}

{370}{}{别碰!}
{371}{}{我说你说过!}
{372}{}{警告你!}

#{375}{}{What the hell are you doing! Guards!}

{375}{}{你在干什么!守卫!}

#{380}{}{Stop wasting time and get to work.}

{380}{}{别浪费时间，开始工作}
