#Targeting Console Techie

#{100}{}{You see a person in funny pajamas. He seems preoccupied.}
#{101}{}{You see a Shi submarine technician.}

{100}{}{你看到一个穿着技术服的人，他看起来心事重重。}
{101}{}{你看见一名始族潜艇技师。}

#{150}{}{Uh, what are you doing, sneaking around like that?}
#{151}{}{Are you some kind of spy?}

{150}{}{Uh, what are you doing, sneaking around like that?}
{151}{}{Are you some kind of spy?}

{150}{}{你偷偷摸摸地想做什么？}
{151}{}{你是间谍吗?}

#{200}{}{This'd be easier if my Chinese was better……}
#{201}{}{I/O error!? How can a guidance system get an I/O error!?}
#{202}{}{001100010010011110100001101101110011? Where's my error code chart……}
#{203}{}{I wish the IFF database still worked. That'd make things a whole lot easier.}

{200}{}{如果我的中文水平更好一点就好了……}
{201}{}{ I/O错误！？导航系统也能产生I/O错误！？干！}
{202}{}{001100010010011110100001101101110011？我的错误代码图在哪里……}
{203}{}{我希望IFF数据库仍然有效，那会让事情简单得多。}


#{300}{}{What do you want, lao wai? Can't you see I'm trying to reconfigure the targeting systems here?}
#{301}{}{Actually, that's what I'm here for. I've got new specifications for those systems, checked by the Emperor, uh,
 personally. Can you input them? You seem to be the most knowledgeable about this subsystem.}
#{302}{}{That's why I'm here, I can help you with configuring the systems. It seems the connection between the marine
 navigation subsystem and the IFF transponder finally died, so you have to do a workaround. Mind if I help?}
#{303}{}{Sorry to bother you.}

{300}{}{你想要什么？老外，你看不出来我正在重新配置目标系统吗？}
{301}{}{实际上，这就是我在这里的目的，皇帝要求我过来为鱼雷制导系统输入新的定位数据，你能帮我输入吗？你似乎是最了解这个系统的人。}
{302}{}{这就是我在这里的原因，我可以帮助你配置系统。这艘潜艇可能使用的是海军陆战队的内部加密系统，所以你不能单纯使用IFF数据库里的资料，你需要做一个变通。介意我帮助吗? }
{303}{}{抱歉打扰你。}




#{310}{}{Oh, I've been waiting for these new specifications for ages! You should've been here a week ago, though, when I was working on what's left of the battle database. Now I have to bust it open again…… Oh well, life of a tech, I guess.}
#{311}{}{Have fun. I'll see what else needs fixing.}

{310}{}{哦，我已经等了好久了！你应该在一周前就来到这里，这个系统让我深感困扰。}
{311}{}{很高兴可以帮到你，我看看还有什么需要修复的。}


#{320}{}{I hardly know you! For all I know lao wai, you could be some kind of a foreign spy, wanting to disable this submarine, so that your plan to travel over the seas to strange places can be completed without the torpedoes sinking your boat! I'm sure that Ken Lee wouldn't let a stranger board the Shi-Huang-Ti with bad intentions, so sorry, but I can't accept these coordinates unless I get them from our leader in person.}
#{321}{}{Well, can I at least help you with configuring the submarine? I have some experience with ancient computer systems, enough to understand how a 200 year old vacuum lamp system can refuse to obey its master.}
#{322}{}{Alright, sorry to bother you.}

{320}{}{我从来都没有见过你！你很可能是一名外国间谍，想要关闭这艘潜艇的鱼雷制导系统，这样你就可以在没有鱼雷击沉你的船的情况下，在海上航行到陌生的地方。我不能接受这些坐标，除非是我亲自从我们的领导那里得到的。}
{321}{}{嗯，我至少能帮你配置潜艇吗？我对古代计算机系统有一些经验，足以了解一个200岁的真空管系统为什么会拒绝服从它的主人。}
{322}{}{好，抱歉打扰你。}


#{330}{}{I guess I can use your help, here, you try it. [The Shi tech lets you take the input. After a few moments of familiarizing yourself with the UI, you start working. A few minutes later you've not only managed to reconfigure the targeting parameters, so that the sub doesn't sink the tanker, but also remove a fault in the system, preventing the techs from accessing the subsystem easily.]}
#{331}{}{Okay, there you go. I've fixed the system. It shouldn't give you any trouble now. Hopefully it'll help you in your work.}

{330}{}{我想我可以接受你的帮助[始族技术员给你让出一个位置，允许你操作。你很快就熟悉了操作界面，几分钟后，您不仅成功地重新配置了目标参数，而且还可以修改了系统的安保配置，防止技术人员可以在短时间内重新把参数恢复回来]}
{331}{}{现在这样就可以了，现在它应该不会再拒绝你的要求，希望这对你的工作有帮助。}


#{340}{}{Thank you for your help, it's hard to find a good computer tech these days.}

{340}{}{谢谢你的帮助，最近很难找到一个好的计算机技术员。}

#{350}{}{Sorry, but no. You might break something and we'll lose the subsystem for good and I am *not* going to set the torpedo target acquisition modules by hand. So, unless you have something *important* for me, please let me get back to my work.}
#{351}{}{Actually, I do. I have new targeting parameters for the torpedoes, checked with the Emperor, uh, himself. You're the resident computer wizard, so I think I can trust you with this.}
#{352}{}{Sorry to bother you.}

{350}{}{不行，你可能会破坏一些东西，搞不好我们会永远失去这个系统，我*不*打算手动设置鱼雷目标捕获模块。所以，除非你对我有重要的意义，否则请让我回到工作上。}
{351}{}{事实上,我做的。我有新的鱼雷的目标参数，和皇帝联系，呃，他自己。你是常驻计算机向导，所以我想我可以信任你。}
{352}{}{抱歉打扰你。}

#{360}{}{No, I don't need any help or any new data. I'm here to work and you are preventing me from working, so go away or I'll have you *taken* away!}
#{361}{}{Sorry to bother you.}

{360}{}{不，我不需要任何帮助或任何新数据。我在这里工作，而你在阻止我工作。请你离开，不然我叫警卫就把你带走！}
{361}{}{抱歉打扰你。}

#{370}{}{Hey, I'm busy here.}
#{371}{}{Sorry, I'm working.}

{370}{}{嘿，我这里很忙。}
{371}{}{抱歉，我现在很忙。}

#{400}{}{You tricked the technician into disabling the submarine.}
{400}{}{你欺骗了技术人员，使潜艇武器系统失效了。}