#Power Console Techie

#{100}{}{You see a person in funny pajamas. He seems preoccupied.}
#{101}{}{You see a Shi submarine technician.}

#{150}{}{Uh, what are you doing, sneaking around like that?}
#{151}{}{Are you some kind of spy?}

#{200}{}{I hate working with this junk.}
#{201}{}{Let's recalibrate this…… there.}
#{202}{}{All those loose cables and no insulation in sight……}
#{203}{}{I hope I don't get electrocuted when recharging the generator.}

#{300}{}{Hey, I'm busy here.}
#{301}{}{Sorry, I'm working.}
#{302}{}{These cables won't fix themselves, find someone else to pester.}

{100}{}{你看到一个穿着技术服的人，他看起来心事重重。}
{101}{}{你看见一名始族潜艇技师。}

{150}{}{你偷偷摸摸地想做什么？}
{151}{}{你是间谍吗?}

{200}{}{我讨厌这个垃圾。}
{201}{}{我们需要调整……这里。}
{202}{}{检查那些松散的电缆有没有短路……}
{203}{}{我希望在检查发电机的时候不会触电。}

{300}{}{嘿，我这里很忙。}
{301}{}{对不起，我很忙。}
{302}{}{这些电缆不会修理自己，去烦其它人。}
