#{100}{}{You see an old console.}
#{101}{}{It appears that this console manages the torpedo launching and loading system. Like everything else on the sub,
 it's rusted through and just barely working.}

#{200}{}{This subsystem, if disabled, should prevent the tubes from being reloaded with spare torpedoes. Disabling
 shouldn't be too hard - the metal is literally falling apart and you can clearly see the vacuum tubes.}

#{210}{}{Just like you thought - the metal gives way easily and the console is soon dismantled. This sub won't be able
 to reload its tubes anytime soon.}
#{211}{}{You fail to disable the system.}

{100}{}{你看到一个旧的控制台。}
{101}{}{这个控制台管理鱼雷发射和装载，它和船上的其它东西一样锈迹斑斑。}

{200}{}{如果禁用这个控制台，应该可以让鱼雷不能发射出去。在松脱的面板缝隙里你可以清楚地看到真空管，这件事应该不太难办到。}

{210}{}{就像你想的一样，控制台上面的金属已经太旧了，你很轻松地掰开了控制台的面板……你迅速的动手……现在好了，在短时间内重新加装这些真空管应该是不太可能的。}
{211}{}{你未能禁用该系统。}


{212}{}{*beep*}
{213}{}{*beeboop*}
