#{100}{}{You see an old console.}
#{101}{}{Looks like this is the old torpedo target control console. Most of the monitors are busted or missing, with
 only a single one just barely operational. Random bits of data appear on the flickering screen from time to time.}

#{200}{}{The operating system seems to be corrupted, as it doesn't respond to your commands like it should. You could
 figure the system out with a more scientific approach.}

#{210}{}{With a few advanced commands, the system is subverted and starts behaving properly. A few keystrokes later, the
 torpedo guidance systems are disabled and rigged to explode a few moments after leaving the tubes. Science!}
#{211}{}{You fiddle with the system for a few minutes, but it's just too far gone for you to salvage. Looks like
 you need to find another way to disable the torpedoes.}
 
{100}{}{你看到一个旧的控制台。}
{101}{}{这个控制台管理鱼雷的目标制导，它上面大部分的监测仪器都已经损坏了，闪烁屏幕上不时闪出乱码，看来要操作它必须要有专业的技能才可以。}

{200}{}{操作系统似乎已经损坏了，它没有响应你的命令，你或者可以用更科学的方法解决这个问题。}

{210}{}{你输入了一些高级命令后，系统开始正常工作了。你先将鱼雷制导系统禁用，然后将鱼雷设置成在发射后的几分钟内爆炸，感恩科学! }
{211}{}{你摆弄这个系统好几分钟，但看起来你需要找到另一种方法来禁用鱼雷。}
 
 
{212}{}{*beep*}
{213}{}{*beeboop*}

