#{100}{}{You see a guard in loose clothing, wearing a look of wary boredom.}
#{101}{}{He doesn't look like he wants to be here right now.}

#{150}{}{Uh, what are you doing, sneaking around like that?}
#{151}{}{Are you some kind of spy?}

#{200}{}{This thing still gives me the creeps.}
#{201}{}{Stop wasting my time, lao wai.}



{100}{}{你看到一个穿着宽松夹克的警卫，脸上带着警惕的神情。}
{101}{}{你看到一个穿着宽松夹克的警卫，他看起来并不想呆在这里。}

{150}{}{你偷偷摸摸的想做什么？}
{151}{}{你是间谍吗？}

{200}{}{每次来到这个地方都我毛骨悚然。}
{201}{}{停止浪费我的时间，“老外”。}