#{100}{}{This hatch looks odd - unlike the rest of the vessel, it's relatively rust free and has an intricate,
 complicated lock.}
 
#{200}{}{You struggle with the hatch, but eventually you manage to rip it open. Pieces of the broken lock litter the
 tower and crunch under your boots.}
#{201}{}{You try your best, but the hatch just won't budge. Maybe explosives will help.}
#{202}{}{Looks like the hatch can be opened if you apply enough force. Marcus might help with that.}

{100}{}{这个舱口看起来很奇怪，不像船上其它的位置，它上面没什么锈迹，而且看起来上面有一把很复杂的锁。}
 
{200}{}{你与舱口搏斗，脚下的铁板因为你的力量咯吱作响，最终你赢了，锁的碎片散落一地。}
{201}{}{你尽了最大的努力，但是舱门纹丝不动的，或者你需要来包炸药才能解决问题。}
{202}{}{看来如果你足够强壮，那就可以打开舱门，马可世或许能帮上忙。}



#{210}{}{Hey Marcus, can you help me open this hatch?}
#{211}{}{Sure, just give me some room.}
#{212}{}{*hrrrgnnnr*}
#{213}{}{The supermutant struggles to pull the hatch up. For a moment, it looks as if he was about to bust a gut, but
 just then, he rips it open, littering the tower with pieces of the broken lock.}
 
{210}{}{嘿，马可世，你能帮我打开这个舱口吗?}
{211}{}{当然，让开一点，给我腾出个地方来。}
{212}{}{*hrrrgnnnr*}
{213}{}{超级变种人脸涨得通红，头上冒出了青筋，你感觉马可世头都快要爆炸了。舱门和变种的人搏斗持续了好一会，就在你认为要失败的时候，嘭的一声，舱门被巨大的力量强行拉开了。}
 

#{220}{}{You fiddle with the lock for a while and open it. Lockpicking's definitely more than just a hobby for you.}
#{221}{}{You fiddle with the lock, but ultimately give up. There's got to be another way to open the lock.}

{220}{}{你摆弄这把锁好一会儿，最终你还是把它打开了。对你来说，开锁绝不仅仅是一种业余爱好。}
{221}{}{你摆弄那把锁，但最终还是放弃了。必须有另一种方法来打开锁。}

#{230}{}{The explosion rips open the hatch and the lock, apart from deafening you.}
{230}{}{爆炸的气浪差点把你掀到水中，也直接把舱门和锁炸到上帝那里去了。}


#{240}{}{You fiddle with the lock for a while and relock it. Lockpicking's definitely more than just a hobby for you.}
#{241}{}{You fiddle with the lock, but ultimately give up. There's got to be another way to relock this.}

{240}{}{你把锁拨弄一下，再把它重新锁上。对你来说，开锁绝不仅仅是一种业余爱好。}
{241}{}{你摆弄那把锁，但最终还是放弃了。必须有另一种方法来重新锁定这个。}
