#{100}{}{You see an old console.}
#{101}{}{The power console is almost completely ruined. Wires stick out in all directions, held together by duct tape
 and the status monitor seems to be busted. This contraption just barely holds together.}

#{200}{}{You examine the console and the loose cables. Looks like someone with a little skill in repair [or a crowbar]
 could completely disable the power subsystem.}
 
#{210}{}{The console surrenders quickly and the emergency generator dies. Without power, the submarine poses no threat.}
#{211}{}{You fail to disable the power generator.}

{100}{}{你看到一个旧的控制台。}
{101}{}{这个控制台负责潜艇的电力管理，它看起来损坏得很严重，状态监视器已经不再显示，面板被掀开，电线从各个方向伸出再重新用胶带固定。不客气地说，这个曾经很精密的装置现在被各种胶带绑得像木乃伊一样。}

{200}{}{你检查控制台上面松垮垮的电缆，看来只要一个二流的维修工或者一把撬棍就可以禁用电力系统了。} 
{210}{}{经过你高超的"修理"，控制台很快就投降了，应急发电机也失灵了。如果没有动力，潜艇就不会构成威胁}
{211}{}{你关闭发电机失败了。}



{212}{}{*beep*}
{213}{}{*beeboop*}
