#{100}{}{You see torpedos.}
#{101}{}{These dangerous-looking weapons are filled to the brim with explosives. The casings are corroded and it
 seems the propellers will fall off any second now.}

#{200}{}{Despite the looks, this torpedo is still a potent weapon. The loose propeller is actually an integral part of
 its navigating system, giving it unprecedented maneuverability. Looks like you need to break out the tools to disable it.}
#{210}{}{Thanks to two centuries of decay, the rusted propulsion system is easy to disassemble. Moments later, it's put
 back together, this time completely immobilized.}
#{211}{}{The rusted-through propulsion system is too much of a challenge. The nuts are stuck and you can't quite figure
 out how to detach the propeller without cutting yourself.}
 
#{220}{}{You have planted explosives near several high-explosive torpedoes. It might be a good idea to get the hell
 out of here.}

{100}{}{你看到鱼雷。}
{101}{}{这些危险的武器外壳已经被腐蚀了，上面锈迹斑斑的螺旋桨好像随时就要掉下来的样子。}

{200}{}{尽管看起来这些鱼雷已经旧得不行了，但仍然是一个有力的武器。看起来马上要散架的螺旋桨实际上质量好得很，真不愧是中国制造。看起来你找些工具才能把它拆开。}
{210}{}{由于两个世纪的腐烂，鱼雷的面板很容易就被拆开了，你破坏了推进系统，然后把面板重新盖上。}
{211}{}{这个生锈的推进系统是一个很大的挑战。你完全不能想象如何在不割伤自己的情况下拆卸螺旋桨。}
 
{220}{}{也许尘归尘土归土是一个好的主意，你在几枚鱼雷附近放下了炸药，现在赶快离开这里。}
 