#{100}{}{You see a powerful computer.} //This is for the computer object itself
#{101}{}{You see the Emperor Computer.}
#{102}{}{You see a large, humming, fully functional computer that has "Emperor v8.8" stamped into its lower casing.}
{100}{}{你看到一部电脑。}
{101}{}{你看到皇帝。}
{102}{}{你看到一部电脑，上面有一个触摸式荧幕。上面写着“皇帝v8.8电脑终端机”。}
{103}{}{你好，请键入你的密码。}
{104}{}{*流口水*}
{105}{}{CSPDMSHR-Shih-huang-ti-X9372}
{106}{}{KSLJKJ:Ken-Lee-97313}
{107}{}{TIUASPO-Lo-Shi-S12908}
{108}{}{*侵入电脑*}
{109}{}{[离线]}
{110}{}{身份已确认。}
{111}{}{你想要执行什么功能？}
{112}{}{检查。}
{113}{}{资料。}
{114}{}{预测。}
{115}{}{无。}
{116}{}{请与系统工程师联络，再见。}
{117}{}{*侵入电脑*}
{118}{}{*离开*}
{119}{}{入侵者警报被启动了，系统关机中。再见。}
{120}{}{[完成]}
{121}{}{检查那一样功能？}
{122}{}{网络检查。}
{123}{}{格式化磁碟。}
{124}{}{检查硬碟结构。}
{125}{}{[返回]}
{126}{}{你想要查询那一样的资料？}
{127}{}{生物。}
{128}{}{化学。}
{129}{}{物理。}
{130}{}{历史。}
{131}{}{[返回]}
{132}{}{住在王宫的子民们有危险了，有50%的机会有暗杀者混在他们之中。}
{133}{}{危险降临王宫了。有75%机会居民们会受伤。}
{134}{}{哈伯教的太空船发射会有95%的失败率。原因：没有燃料，机身没有封闭完成，引导不良。}
{135}{}{获选者执行他的任务有15%的成功率。}
{136}{}{资料显示英克雷军比他人想像中的要强大；不要接近他们。}
{137}{}{在本游戏中潜艇再次出现的机率：0%。}
{138}{}{如果外人不帮忙，油轮船员自行将生物清除的机率：0%。}
{139}{}{波塞冬油轮无法航行。}
{140}{}{无法处理，需要更多资料。}
{141}{}{[更多]}
{142}{}{[返回]}
{143}{}{生物站：运作中}
{144}{}{生物站：没有运作}
{145}{}{化学站：运作中}
{146}{}{化学站：没有运作}
{147}{}{物理站：运作中}
{148}{}{物理站：没有运作}
{149}{}{关起生物站。}
{150}{}{关起化学站。}
{151}{}{关起物理站。}
{152}{}{连接生物站。}
{153}{}{连接化学站。}
{154}{}{连接物理站。}
{155}{}{开动生物站。}
{156}{}{开动化学站。}
{157}{}{开动物理站。}
{158}{}{[返回]}
{159}{}{格式化磁碟：所有的资料都会消失，要继续吗？}
{160}{}{是的。}
{161}{}{不。}
{162}{}{本系统的磁碟有92%结构可以运作。资料可靠度100%。预测处理器有电力问题-需要6天才能修复。预测功能只有15%运作度。}
{163}{}{[返回]}
{164}{}{你想要格式化吗？这是一个无法逆转的行为。}
{165}{}{是的。}
{166}{}{不。}
{167}{}{格式化中..格式化中..格式化完成。机器人需要完全安装，关机。关机中..完成。}
{168}{}{[完成]}
{169}{}{选择资料：-植物学程序-基因程序-XENO程序}
{170}{}{植物学程序。}
{171}{}{基因程序。}
{172}{}{XENO程序}
{173}{}{[返回]}
{174}{}{[在二十分钟后，你看到：申博士的抗放射植物研究并不是相当的成功，所创造出来的植物有着相当不良的反效果。}
{175}{}{基因程序。}
{176}{}{XENO程序}
{177}{}{[返回]}
{178}{}{[在二十分钟后，你看到：在进行FEV病毒研究之后，他发现创造变种士兵的可能性相当的高。}
{179}{}{植物学程序。}
{180}{}{XENO程序}
{181}{}{[返回]}
{182}{}{“我们原本想要进行实验的实验品都不见了，一定是被哈伯教偷走了”。在能够找到新的实验品之前，所有的实验都暂停。}
{183}{}{植物学程序。}
{184}{}{基因程序。}
{185}{}{[返回]}
{186}{}{化学资料库：燃料|聚合物|……}
{187}{}{[燃料]}
{188}{}{[聚合物]}
{189}{}{[返回]}
{190}{}{[在看过复杂的化学公式之后，你发现始族发明了一种可以从植物取出的燃料。]}
{191}{}{[你看到许多的公式，你一点都看不懂。]}
{192}{}{送燃料到波塞冬油轮。}
{193}{}{送燃料到哈伯教。}
{194}{}{[返回]}
{195}{}{你发现始族正在设计一种新型聚合物的护甲。}
{196}{}{[返回]}
{197}{}{燃料送达。储存槽状况：空。关闭程序。}
{198}{}{[完成]}
{199}{}{燃料送达。储存槽状况：空。关闭程序。}
{200}{}{[完成]}
{201}{}{物理资料库：创新-学说}
{202}{}{创新}
{203}{}{学说}
{204}{}{回去}
{205}{}{由于目前得到的飞鸟设计图，我们设计飞行器的可能性增加了不少。}
{206}{}{*拷贝设计图* [返回]}
{207}{}{[返回]}
{208}{}{“我们还在设计可以飞行的机器。不过目前都还没有成功，如果我们可以得到战争前的设计图纸的话..”-王博士}
{209}{}{[返回]}
{210}{}{[你发现始族正在设计核能发电的科技，而且在想办法重现战前的科技。}
{211}{}{[返回]}
{212}{}{站开启完成。}
{213}{}{[返回]}
{214}{}{电脑终端机并没有出现界面。}
{215}{}{电脑终端机看起来没有作用。}

{216}{}{系统遭到侵入。命令攻击！}
{217}{}{攻击入侵者！}
{218}{}{攻击！}
{219}{}{有反叛者！}

{220}{}{地面寻找。}
{221}{}{你想要寻找什么？}
{222}{}{我的同胞。}
{223}{}{有97%的可能你的同胞正在英克雷军的基地。}


#RP 1.3

#History
#{230}{}{[The screen flashes for a second before switching to a monochromatic display filled with Chinese symbols.
 After a few moments, the screen clears and displays a list of contents. Most of the files are ancient and corrupted,
 but there are several that seem to be still intact.]}
#{231}{}{People's Liberation Army Navy                                       Emperor v. 4.01 Access Terminal
                                    Please make a selection:}
#{232}{}{Submarine status}
#{233}{}{Chinese Intelligence Network}
#{234}{}{Comlinks}
#{235}{}{Personnel logs}
#{236}{}{[返回]}

{230}{}{[屏幕闪烁片刻，然后切换到充满中国字的单色界面。几分钟后，屏幕清空并显示内容列表。大多数文件都是古老或者损坏的，但是有几个似乎仍然完好无损]}
{231}{}{人民解放军海军皇帝v8.8访问终端。请选择:}
{232}{}{[潜艇位置]}
{233}{}{[中国情报网络]}
{234}{}{[Comlinks]}
{235}{}{[人员日志]}
{236}{}{[返回]}


#sub status
#{240}{}{Name: Shi-Huang-Ti                                                     Class: Type 088 Nuclear-powered Ballistic
 Missile Submarine   Armament: Eight JL-3 nuclear ballistic missiles
                  Launched: 8th August 2068                                         Commissioned: 18th April 2069
                                       Captain: Admiral Class AAAA Ye Li
                                Crew: 15 officers, 28 petty officers, 27 enlisted, 16 civilian technicians}
#{241}{}{Read on.}

{240}{}{
舰名：始皇帝；
类型: 088型核动力潜艇；
导弹潜艇武器:8枚JL-3型核导弹；
发行日期:2068年8月8日:2069年4月18日；
船长配置:海军上将AAAA级，李烨；
船员配置:15名军官，28名士官，27名士兵，16名文职技术人员；
}
{241}{}{[继续]}




#{250}{}{Service:                                                               2069 - 2071: Chinese territorial
 waters patrol              2071 - 2077: Combat patrol in the Alaskan and Pacific theatres of operations
                                            October 2077: Combat mission in the Californian theatre of operations.
 Mission outline R.}
#{251}{}{Read on.}

{250}{}{
任务：
中国领土水域巡逻：2069 - 2071；
阿拉斯加和太平洋战区的战斗巡逻：2071 - 2077；
加利福尼亚的战区作战任务：2077年10月；
R任务大纲。}
{251}{}{[继续]}



#{260}{}{Current status:
                                                     Submarine damaged beyond repair. Mainframe removed from vessel and
 relocated. Ship refitted as stationary defensive structure two miles NNE of San Francisco harbor.}
#{261}{}{What was that about combat patrols?}
#{262}{}{Read more about Mission Outline R.}
#{263}{}{Stationary defensive structure sounded interesting.}
#{264}{}{*back*}

{260}{}{
目前状况:潜艇损坏无法修复，动力部分已从舰中取出，主体改装为固定防御结构；
位置：旧金山港两英里。}
{261}{}{[阅读关于战斗巡逻]}
{262}{}{[阅读关于任务大纲R]}
{263}{}{[阅读固定防御结构]}
{264}{}{[返回]}



#combat patrols……
#{270}{}{Upon request made by the Alaskan Frontline commander, General Jingwei, the Shi-Huang-Ti was transferred to the
 Alaskan/Pacific theatre of operations to intercept American convoys in open waters. Under the command of Rear Admiral
 Ye Li, she has sunk 9 freighters and 4 warships, damaging 18 more craft and putting a significant strain on enemy
 supply lines.}
#{271}{}{Read on.}

{270}{}{在阿拉斯加前线指挥官精卫将军的要求下，"始皇帝"被编入阿拉斯加/太平洋战区，任务是在开阔水域拦截美国护航队。在海军少将李烨的指挥下，"始皇帝"击沉了9艘货船和4艘军舰，破坏了18艘船只，给敌人补给线造成了巨大的压力。}
{271}{}{[继续]}


#{275}{}{Admiral Ye Li has also been credited by the People's Liberation Army Navy as leading to the sinking of USS
 Ebon Atoll by an American submarine, USS Interference.}
#{276}{}{*back*}

{275}{}{Admiral Ye Li has also been credited by the People's Liberation Army Navy as leading to the sinking of USS
 Ebon Atoll by an American submarine, USS Interference.}
{276}{}{[返回]}


#defense struct
#{280}{}{2220, May : Poseidon Marine Vessel Valdez arrives in port, manned by a crew equipped with unknown-type powered
 infantry armor. The ship is disabled and infested with mutants.
                                                                  2220, June: Following consults with the Emperor, Chiang Lee
 dictates that the Shi-Huang-Ti be reactivated and transformed into a defensive installation against further naval threats.
                                                           2220, July: The submarine is reactivated. Emergency power
 had to be provided to power it up.                                  2231, May: The emergency generator dies. Ken Lee orders
 an ElectroBox generator to be wired into the power system to keep powering the submarine.
                                     2238, August: A Neptune Waveskimmer motorboat is restored and transferred to the
 submarine maintenance crew.}
#{281}{}{Hmm, let's see if I can find something more on that maintenance crew……}
#{282}{}{*back*}


{280}{}{
2220年5月：观测到一艘海军舰艇瓦尔迪兹[Valdez]停靠到波塞冬钻油平台[Poseidon]，这艘船残损严重，船员配备了未知类型的步兵护甲，上面到处都是变种人。
2220年6月：在与皇帝商量之后，最高指挥官李蒋决定重新启用"始皇帝"，并将其转变为防御设施，以防止进一步的海上威胁。
2220年7月：潜艇后备紧急电力系统修复，"始皇帝"重新激活。                                 
2231年5月：潜艇后备紧急电力系统损毁，李健命令将一台发电机连接到电力系统中，以继续为潜艇提供动力。
2238年8月：一艘海王星汽艇被修复，并移交给潜艇维修人员。}
{281}{}{嗯，让我们看看在维修人员身上能否能找到更多的东西……}
{282}{}{[返回]}

#find more on maintenance crew……
#{290}{}{[Bingo! After a few minutes of fiddling with commands, you manage to pull up a small text file concerning the
 generator on the submarine. It seems that regular trips are needed to refuel and maintain the generator. The file also
 lists the current maintenance crew roster.]}
#{291}{}{Submarine maintenance crew [2241 onwards]: Tsing Tao, Hun Kwai, Shin Fai, Lo Chang, Wu Fei}
#{292}{}{*add myself to maintenance crew roster*}
#{293}{}{*back*}

{290}{}{[Bingo！在摆弄了几分钟之后，您找到一个文本文件。根据上面的记录，潜艇上的发电机需要定期补充燃料和维护，该文件还列出当前维护人员名册。]}
{291}{}{潜艇维修组编号2241:陶、胡坤、新辉、罗昌、吴飞}
{292}{}{*增加自己到维修人员名册*}
{293}{}{[返回]}


#add self
#{300}{}{[With a few quick keystrokes, you become a part of the submarine maintenance crew. A list of passwords for
 the motor boat guard is now accessible.]}
#{301}{}{*download password list to PIP-Boy*}

{300}{}{[没花多少时间，你就把自己加入到潜艇维修人员列表中，这里还有汽艇的密码表，现在应该可以通过港口的守卫盘问了]}
{301}{}{*下载密码列表到PIP-Boy*}


#download list……
#{310}{}{[You plug the PIP-Boy into one of the access ports. After a moment, you have an up-to-date list of passwords
 for the next year. Talk about security.]}
#{311}{}{*back*}

{310}{}{[你把PIP-Boy插入到一个插口中，开始下载密码列表]}
{311}{}{[返回]}

#done
#{320}{}{You're a fully fledged Shi submarine technician now.}

{320}{}{你现在是一个始族的潜艇技师了。}

#intel network
#initial message

#{325}{}{Error. Command Code Chart required. Please insert the correct chart.}
{325}{}{错误，命令代码所需的图表缺少，请插入正确的图表。}



#{330}{}{[Thanks to the command code chart you retrieved from the sub, you are able to access restricted files on the
 Emperor's drives]}
#{331}{}{Command code recognized. Security restrictions lifted. Chinese Intelligence Network initialized..
……
……
Warning! Uplink to CIN central Beijing server unavailable. Retrieving archived data.
 [It seems most of the archives are corrupted. However, the mainframe manages to retrieve several intact files]}
 
{330}{}{[感谢您从sub中检索到的命令代码图，您可以访问皇帝的驱动器中受限制的文件]}
{331}{}{命令代码识别……安全限制解除……中国的情报网络初始化. …….警告!Uplink to CIN中央服务器不可用，检索已存档数据。[似乎大多数档案都已损坏。但是计算机仍然设法检索到几个完整的文件]}


#{332}{}{Intelligence report 2069-11-5}
#{333}{}{Intelligence report 2072-4-18}
#{334}{}{Intelligence report 2073-12-4}
#{335}{}{Intelligence report 2074-9-17}
#{336}{}{Intelligence report 2075-10-17}
#{337}{}{Intelligence report 2076-8-12}
#{338}{}{Intelligence report 2077-10-12}
#{339}{}{Intelligence report 2077-10-23}
{332}{}{情报报告 2069-11-5}
{333}{}{情报报告 2072-4-18}
{334}{}{情报报告 2073-12-4}
{335}{}{情报报告 2074-9-17}
{336}{}{情报报告 2075-10-17}
{337}{}{情报报告 2076-8-12}
{338}{}{情报报告 2077-10-12}
{339}{}{情报报告 2077-10-23}

{340}{}{}
#{341}{}{*more*}
#{342}{}{*back*}

{341}{}{[更多]}
{342}{}{[返回]}

#2069-11-5
#{345}{}{From: Counterintelligence Division
                                  Rioting in Tibet and neighboring provinces continues, threatening the construction
 of the Eastern Dragon satcom complex. President Xin orders military intervention against the populace. Following
 significant insurgent casualties, the province is restored to Chinese control and the remaining insurgents are resettled.}
#{346}{}{[返回]}
{345}{}{[发送部门: 反间谍部门]西藏和邻近省份的骚乱仍在继续，威胁着周边建设。新总统下令对民众进行军事干预，击毙大量叛乱人员，剩下的叛乱分子被控制，中国恢复了对该省的控制。}
{346}{}{[返回]}

#2072-4-18
#{350}{}{From: Biochemical Warfare Division
                          Outbreak of epidemic in the Soviet Union threatens northern protectorates of the PRC. BioChem
 WD advises quarantine andisolation of endangered territories. Potential resettlement location for insurgents, terrorists
 and undesirables and harvesting area for new strains of biological weapons. Plan submitted to Party for approval.}
{350}{}{[发送部门: 生化研究部]在苏联爆发的流行病威胁着中国北方。生化研究部建议封锁该区域，并对潜在的叛乱分子安置地点使用新的生物武器。该计划已提交给上级，等待批复。}
{351}{}{[返回]}

#2073-12-4
#{360}{}{From: Alaskan Front Commander, General Jingwei
                Strain #23-110 deployed against American troops, demoralizing and weakening their operational
 strength. Requesting additional troops and Battlemaster armor for final push against the entrenched American forces at
 the borders of Alaska.}
{360}{}{[发送部门: 前线统率]阿拉斯加边境战况激烈，为并取得最终胜利，已经将额外的部队和战斗人员的护甲派往此地。 }
{361}{}{[返回]}

#2074-9-17
#{370}{}{From: Central Command
                                           American units deployed to mainland after evading our blockade of Japan.
 Alaskan forces are to continue operations. Military forces in annexed territories are to augment the defense of home front.
 Command authorizes the use of biological and chemical weapons on home soil - the foreign devils must be exterminated!}
{370}{}{[发送部门: 中央司令部]美国部队在避开日本封锁线后部署到大陆，阿拉斯加军队将继续作战。对于已经登陆的美国军队，命令授权在本土使用生物和化学武器，星条恶魔必须被消灭！}
 
{371}{}{[返回]}

#2075-10-17
#{380}{}{From: Red Dragon
                                                     Insurgency operations and terror strikes highly effective in
 demoralizing the American population. Support for military operations overseas wanes as riots and protests are incited
 across the American soil. Recommend strikes against designated research and military targets across the United States,
 priority: Raven Rock, West Tek, Mariposa, Boulder, Institute.}
{380}{}{[发送部门: 红龙]煽动行动和恐怖袭击非常有效，美国本土因为暴乱和抗议，其对海外军事行动的支持大大减弱。建议对美国境内指定的研究和军事目标进行打击，优先：玛丽萨博军事基地[Mariposa]，黑鸦岭[Raven Rock]，博尔德[Boulder]，西部科技[West Tek]，研究所[Institute]。} 
{381}{}{[返回]}

#2076-8-12
#{390}{}{From: Central Command
                                              American military superiority now clear - T-51b power armor units deployed
 to mainland. The PLA has no appropriate counter and is losing ground daily. Chairman Cheng demands that Beijing stays in
 Chinese hands - fortification is underway. Command orders intensification of guerilla operations behind enemy lines.
 Operatives in all American Commonwealth are to prepare for staging insurgencies. Weapon and equipment shipments dispatched.
 Priority target: Washington, DC, Columbia Commonwealth}
 
{390}{}{[发送部门: 中央司令部]美国向前线部署了T-51b护甲部队，我方解放军缺乏有效反击手段，每天都在节节败退。程主席要求北京政府继续留在中国，中国政府正在加强对中国的控制。命令剩余部队在敌人后方加强游击战，向所有美国联邦的特工人员发送武器和设备，随时准备发动武装叛乱。
优先目标:华盛顿哥伦比亚联邦。} 
{391}{}{[返回]}

#2077-10-12
#{400}{}{From: Party Chairman Cheng
                                         With the Alaskan Front's collapse and increasingly strong American presence on
 Chinese soil defeat is imminent. According to resolution 636860 of the Communist Party of China, I am hereby ordering all
 loyal military forces to commence nuclear operations against the Americans, mission outline R. Priority targets are
 contained within operational directives. May our souls return to this Earth.}
{400}{}{[发送部门: 程主席]随着阿拉斯加前线的崩溃，在越来越强大的美国部队面前，中国失守的面积越来越大。根据中国共产党的第636860号决议，我在此发出全面指令，
所有忠诚的军事力量开始向美国进行核作战，R任务启动，我们的灵魂属于这片大地。} 
{401}{}{[返回]}

#2077-10-23
#{410}{}{From: Central Command                                            All forces in position. Transmitting final confirmation
 codes. Operation Youmíng is go.}
{410}{}{[发送部门: 中央司令部]所有部队部署完毕，发送最终行动确认码。}
 
{411}{}{[返回]}

#comm links
#{420}{}{Scanning communication outlets……                                    PLA CentCom……		offline
                                                CIN Beijing……		offline
                                                   SSC Naval Yard……	offline
                                              SCA Eastern Dragon..	offline
                                        Warning: No connection to external serves could be made.}
#{421}{}{That's disappointing……}

{420}{}{
扫描通信媒体……
中国人民解放军中央司令部……离线；
CIN北京……离线；
SSC海军指挥部……离线；
SCA东方龙……离线；
警告:无法连接到外部服务。}
{421}{}{真令人失望啊……}


#Personnel logs
#{430}{}{Scanning local drives……}
#{431}{}{[CONTINUE]}

{430}{}{扫描本地驱动器……}
{431}{}{[继续]}


#{440}{}{One accessible file found. [It seems most of the archives are corrupted. However, the mainframe manages to
 retrieve an intact file.]}
#{441}{}{Personal log: Li Ye, Admiral, Captain}

{440}{}{[看来大部分档案都被损坏了。但计算机仍然设法检索出一个完整的文件]}
{441}{}{[个人日志：李烨，海军上将]}


#{450}{}{2077-10-12: We are losing this war. I just received confirmation that the Party has finally decided to go
 through with plan R. Madness! How will nuclear war give us victory? Nobody wins if we unleash this kind of power. But
 I am a soldier and I will follow my orders through to the end.}
#{451}{}{Read on.}
{450}{}{2077-10-12: 我们正在输掉这场战争。我刚刚收到确认，上层终于决定要通过R计划，这简直是疯子的行为，核战争怎么可能给我们带来胜利？如果我们释放这种力量，没有人会赢。但我是一名战士，我会服从我的命令直到最后。}
{451}{}{[继续]}
{452}{}{[返回]}

#{460}{}{2077-10-19: The crew is becoming restless. Wong, excited, told the officers about plan R and they were ecstatic.
 I cannot blame them, even though I disagree: Wong lost his sons in Anchorage while Da Chiang's brother was captured off
 the coast of Maryland.}
#{461}{}{Read on.}
{460}{}{2077-10-19: 船员们变得焦躁不安，王飞很兴奋地告诉大家关于R计划的事，他们欣喜若狂。尽管我不能持相同的观点，但我不能责怪他们：王飞在安克雷奇失去了他的儿子，而大江的兄弟在马里兰被俘虏了。}
{461}{}{[继续]}
{462}{}{[返回]}

#{470}{}{2077-10-21: We have completed final preparations for launch. All that is left is inputting the confirmation codes.
 It has been an honor to serve with these men.}
#{471}{}{Read on.}
{470}{}{2077-10-21: 我们已经完成了发射的最后准备工作，剩下的就是输入确认码，和这些人一起服役是我的荣幸。}
{471}{}{Read on.}
{472}{}{[返回]}

#{480}{}{2077-10-23: We have received confirmation codes and will be in position in fifteen minutes. This is probably my
 last entry in this log, so let me state that I do not condone this kind of atrocity. War is fought between soldiers, not
 bombs and civilians. If anyone survives, I hope they will forgive us.}
#{481}{}{Read on.}
{480}{}{2077-10-23: 已经收到了确认码，15分钟后就可以到达作战目的地。这可能是我的在这个日志中最后一个记录，但我绝不认同这种暴行！战争是士兵之间的战斗，而不是炸弹和平民之间！如果有人幸存下来，我希望他们能原谅我们。}
{481}{}{[继续]}
{482}{}{[返回]}

#{490}{}{2077-10-29: Damn those maniacs! I thought we were the only group ordered to engage the Los Angeles sector, but I
 was wrong. They launched our most powerful ICBM at it. I cannot fathom why it wasn't sent at Washington, but that's moot.
 We are currently drifting in the ocean. The Emperor is dead, navigation is busted and it seems this is going to be our
 grave.}
#{491}{}{Read on.}
{490}{}{2077-10-29: 这群该死的那些疯子！我以为我们是唯一被要求参与攻击洛杉矶的部门，但他们竟然向这里发射了最强大的洲际弹道导弹，而且就砸在我们旁边！我无法理解为什么它瞄准的不是华盛顿。但这一切现在都毫无意义，我们目前正在海洋中漂流，动力系统坏了，"皇帝"停止了工作，导航也一样，看来这艘潜艇就是我们的坟墓。}
{491}{}{[继续]}
{492}{}{[返回]}

#{500}{}{2077-11-04: We've been adrift for several days now. Jing managed to restore some of the power to our onboard
 systems, so we should have enough oxygen to last several weeks. I am more concerned about food and water - our supplies
 are low and there's not enough of them to go around. The crew is getting restless.}
#{501}{}{Read on.}
{500}{}{2077-11-04: 我们已经漂流了好几天了，大江设法恢复了船上的一些电力，所以我们又有了足够的氧气可以持续几个星期。我更担心的是食物和水--已经没有多少补给了，船员们开始变得焦躁不安。}
{501}{}{[继续]}
{502}{}{[返回]}

#{510}{}{2077-11-08: The Emperor is back on line, but barely. We still have no navigation and the crew is on the verge of
 mutiny - I had to stop two sailors from beating up Jing. The situation is dire. Unless we surface in the next few days,
 I fear we will kill each other.}
#{511}{}{Read on.}
{510}{}{2077-11-08: 奇迹一样，"皇帝"又开始运作了，但这对我们现在的状况毫无帮助，没有动力，我们仍然只能在海里漂。船员已经到了兵变的临界点，形势非常严峻的，我甚至在写这份日志前不得不阻止了一场可能的械斗。除非在接下来的几天里有好消息，否则我们可能会自相残杀。}
{511}{}{[继续]}
{512}{}{[返回]}

#{520}{}{2077-11-12: Finally! We ran aground in the San Francisco bay. The sailors were rejoicing until we cut open the
 hatches. The city is a wreck, ravaged by firestorms and fallout. I sent out shore parties to find a suitable camp site.
 So far, none have reported such a location. }
#{521}{}{Read on.}
{520}{}{2077-11-12: 好消息！我们在旧金山湾搁浅了，大家都很高兴--直到我把舱门打开。我们看到的是一片废墟，上面满是被破坏的废墟，盖氏计数器格格作响。我派人去岸上找一个合适的营地，但到目前为止，还没有人回来。}
{521}{}{[继续]}
{522}{}{[返回]}

#{530}{}{2077-11-16: Lao's team found an inhabitable neighborhood. The denizens have abandoned it, after the air raid
 alarm it seems, but it has suffered little damage. The most ironic thing? It's San Francisco's Chinatown, still surrounded
 by American checkpoints and fortified barracks. If only they knew……}
#{531}{}{Read on.}
{530}{}{2077-11-16: 劳的小队发现了一个适宜居住的社区，在袭击过后这个社区几乎没有受到波及，但里面一个人都没有，原住民们走的时候似乎有点惊慌，大部物资都还留在里面。最讽刺是，这里是旧金山的唐人街。}
{531}{}{[继续]}
{532}{}{[返回]}

#{540}{}{2077-11-24: We made contact with Red Dragon. The north America Black Ghost command has been trudging westwards
 ever since the 23rd, after they lost contact with CentCom. They're none too happy about being stuck on enemy soil, but
 we must make do.}
#{541}{}{Read on.}
{540}{}{2077-11-24: 我们联系上了红龙，潜入北美的黑幽灵部队一直在向西移动。自从11月23日后他们就失去了与中央司令部的联系，他们不喜欢被困在敌人的土地上，但是我们别无选择。}
{541}{}{[继续]}
{542}{}{[返回]}

#{550}{}{2077-12-06: The Shi-Huang-Ti away camp is set up and functioning. Ghosts are running scavenging operations in
 the surrounding areas and rounding up any supplies they come across. I gave them strict orders not to engage American
 survivors without provocation - we cannot antagonize potential allies.}
#{551}{}{Read on.}
{550}{}{2077-12-06: "始皇帝"附近的营地开始建设和运作，幽魂部队正在对周围的区域进行清理工作，并运回他们遇到的任何补给。我命令他们不要射杀美国人，我们不能对抗潜在的盟友--那些没有挑衅行为的幸存者。}
{551}{}{[继续]}
{552}{}{[返回]}

#{560}{}{2077-12-14: An oddity - a cult by the name of Church of Hubology has somehow survived the devastation in a
 reinforced bunker near what remains of the Golden Gate bridge. They are harmless fanatics, but useful. Their resources,
 manpower and knowledge of the surrounding area will aid us in establishing our new home.}
#{561}{}{Read on.}
{560}{}{2077-12-14: 一件很奇怪的事，一个自称哈伯的教会来到这附近，并在在金门大桥附近开始加固掩体和建造设施。他们是邪教，但却是无害的狂热分子，他们的资源、人力和周围地区的知识将帮助我们建立我们的新家。}
{561}{}{[继续]}
{562}{}{[返回]}

#{570}{}{2077-12-27: The basic necessities are covered. We are currently making plans to strip the submarine of electronics
 and other useful equipment - there's no point in maintaining it, since the propulsion system is beyond repair and we can
 use everything we can on site. Jing drafted plans for a reinforced structure - a 'Steel Palace' of sorts.}
#{571}{}{Read on.}
{570}{}{2077-12-27: 基本生活设施都已经覆盖，我们目前正在计划剥离潜艇的电子设备和其他有用的设备——维护它们现在毫无意义，因为推进系统已经无法修复。我们的工程师使用现在能找到的一切，起草了一个加固结构的项目"铁宫殿"。}
{571}{}{[继续]}
{572}{}{[返回]}

#{580}{}{2077-12-31: This is going to be my last entry in this log. I am no longer an Admiral of the People's Liberation
 Army Navy. I have a responsibility to my men and will lead them into the future. As of 2078, we are in full secession
 from China. Chairman Cheng, eat your heart out. This is Ye Li, leader of the Shi-Huang-Ti people, signing off.}
{580}{}{2077-12-31: 这将是我在这个日志中的最后一个记录，我不再是人民解放军的军官、海军上将。我来自中国，我将对我人民负有责任，并将带领他们走向未来。明天，我们将完全脱离中国政府。我是李烨，"始"的领导人。程主席，在地狱啃你自己的黑心吧！} 
{581}{}{[返回]}

#Mission R
#{590}{}{Mission Outline R:                                                    Emergency nuclear warfare contingency plan
 for the People's Liberation Army in case of imminent defeat by a foreign power, accepted by the Communist Party of China
 on 11th November 2073.}
#{591}{}{Read on.}
{590}{}{R任务：应急核战争应急计划；起拟日期2073年11月11日；任务实施环境：如中国人民解放军被外国势力打败，实行该计划。}
{591}{}{[继续]}


#{600}{}{The plan includes a series of coordinated nuclear strikes against strategic targets across America, using strategic
 aircraft, nuclear missile submarines, missile delivery systems, low yield infantry nuclear weapons and other nuclear
 devices. The objective is to cripple American retaliatory capability and military capability.}
#{601}{}{Read on.}
{600}{}{该计划包括一系列针对美国战略目标的核打击行动，包括飞机、核导弹潜艇、导弹运载系统、步兵式核武器和其他核设施。目标是削弱美国的报复能力和军事能力。}
{601}{}{[继续]}


#{610}{}{The Shi-Huang-Ti is tasked with destroying eight targets on Californian soil, including the West Tek Research
 Facility, corporate headquarters in Los Angeles and major population centers.}
#{611}{}{Read on.}
{610}{}{计划中，"始皇帝"的任务是摧毁加州上的8个目标，其中包括西部科技[West Tek]的研究所、位于洛杉矶的公司总部，以及主要的人口中心。}
{611}{}{[继续]}


#{620}{}{In case of mutiny, betrayal or defection, the Captain is authorized to order the Emperor to take control of the
 vessel and carry out the mission.}
{620}{}{在遇到叛变时，船长有权命令"皇帝"自动控制执行任务。}
{621}{}{[返回]}
#{622}{}{*logoff*}
{622}{}{[退出]}