#{100}{}{You descend down a rusted ladder inside the submarine. The interior is dark, lit only by the dull light of the
 few working monitors. The air is bad, filled with the stench of rust and decay. You feel surrounded and uneasy.}
#{101}{}{You descend down a rusted ladder inside the submarine. The interior is dark, lit only by the dull light of the
 few working monitors. The air is bad, filled with the stench of rust and decay. You feel almost like at home.}

{100}{}{你从潜艇一个生锈的梯子上下来，里面非常的黑，在昏暗的灯光照射下你看到一些监控台在工作，空气很糟，充满了锈迹和腐烂的味道。你感到被包围和不安。}
{101}{}{你从潜艇一个生锈的梯子上下来，里面非常的黑，在昏暗的灯光照射下你看到一些监控台在工作，空气很糟，充满了锈迹和腐烂的味道。你感到像回到家一样。}
