#{100}{}{You stumble and cut yourself on an exposed piece of metal.}
#{101}{}{Some old wires smack you across the face.}
#{102}{}{Your foot falls through the rusted grating. You break free, but hurt your leg in the process.}
#{103}{}{The stench of rust and decay is overbearing. You have trouble breathing freely and hit an exposed rebar. Ouch.}


{100}{}{你在一块突起的金属上绊了一跤，割伤了自己。}
{101}{}{不少旧的电线垂下来打到你的脸。}
{102}{}{你穿过生锈的铁栅栏，不小心绊了一跤，你爬了起来，但却伤了腿。}
{103}{}{锈和腐烂的恶臭不停的进入你的肺里，你感到呼吸困难，并且接触到暴露的金属，这真糟糕。}