#{100}{}{Halt, mutant wastelander! We are searching the area for an enemy of the Enclave. Identify yourself immediately.}
#{101}{}{Who are you calling a mutant, asshole? You want an enemy? You've got one -- right here.}
#{102}{}{Look, I'm just a simple traveler. I've never even heard of the Enclave. This person you're looking for must be pretty dangerous, because you guys look like you mean business.}

{100}{}{停下，变种人！我们正在这个地区寻找敌人，报上名来。}
{101}{}{你说谁是变种人，混蛋？你想要一个敌人对吧？这里就有一个！}
{102}{}{你好，我只是一个简单的旅行者。我从来没听说过那瓦罗。我想你要找的这个人一定很危险，因为你看起来像个诚实的生意人。}


#{103}{}{That's enough for me. Kill him.}
#{104}{}{Oh, this will be fun!}

{103}{}{这就够了，杀了这个家伙。}
{104}{}{哦，这会很有趣的！}

#{105}{}{Oh yeah, they're dangerous alright, and we suspect them to be fleeing Gecko. For all we know, you're the one we're looking for.}
#{106}{}{Well I'm sure glad I'm not, because you don't look like anyone I'd want to mess with. But listen, if there's a dangerous person on the loose around here, I should really be getting back to my family so I can warn them.}
#{107}{}{All right, I give up. Let's party!}

{105}{}{哦，是的，他们很危险，我们怀疑他们在逃离蜥蜴城。另外据我们所知，你就是我们要找的人。}
{106}{}{我必须要说，我不是。因为你看起来不像我想惹的人。另外，如果这里有一个危险的人，我想我应该赶快回家，这样我就可以警告家人们了。}
{107}{}{好吧，我觉得没什么好说的了。让舞会开始吧！ }



#{108}{}{You're not going anywhere just yet. Have you ever been to Gecko?}
#{109}{}{Yeah, of course I have. Lovely place. I mean, the locals are hideous and it kinda smells and there's all that radiation and stuff, but it sure is fun to mess around on the computers. Ha! You should have been there when I was messing with this one jackass—you know, he looked a lot like you fellas.}
#{110}{}{Gecko? Hell no, this is as close as I get. Don't you know that place is full of them ugly-ass ghouls? Why do you ask?}

{108}{}{你还不能去任何地方，你去过蜥蜴城吗？}
{109}{}{是的，我当然去过哪里。那真是个可爱的地方。我的意思是，当地人都很可怕，而且有点难闻，还有辐射什么的，但是在电脑上乱搞确实很有趣。哈！但你应该把我和这个混蛋捣混了，要知道，他的外表看起来很像你们。}
{110}{}{蜥蜴城？不，我从来没去过那里。难道你不知道那个地方到处都是僵尸吗？你为什么问这个？}



#{111}{}{OK, I believe you. Fan out, men. Search the area. We gotta find this person.}
#{112}{}{No. I don't believe you. This is our man, boys!}
#{113}{}{No. I don't believe you. This is our woman, boys!}

{111}{}{好吧，我相信你。现在离开这里，继续搜索，我们得找到这个人。}
{112}{}{不，我不相信你。这就是我们要找的男人，小子们！}
{113}{}{不，我不相信你。这就是我们要找的女人，小子们！}


#{114}{}{Whoa! Whoa! Just hold on a second. Why don't you believe me? What am I supposed to have done?}

{114}{}{嘿！嘿！冷静一下，等一下。你为什么不相信我？我要该怎么做才能证明？}


#{115}{}{Somebody hacked into the Enclave computer network from the Poseidon Oil Reactor. We're trying to track him down.}
#{116}{}{Hacked into it！？Well, that couldn't have been me. I'm just a tribal. Hell, I don't even know how to use a -- what did you call it? Kom-pu-tor?}

{115}{}{有人利用波塞冬石油平台的网络入侵那瓦罗的计算机，我们正在追踪他。}
{116}{}{入侵电脑？！那不可能是我。我只是一个土人，我根本不知道怎么用那些高科技的东西，你们叫它什么来着？颠~脑？？ }

#added by killap - RP 1.3
#{200}{}{Gecko? Hell no, this is as close as I get. Don't you know that place is full of them ugly-ass ghouls? It's bad enough that I have to watch over my Uncle Lenny, here. Why do you ask?}
#{201}{}{Urgh?}
#{202}{}{Me kill baddies!}

{200}{}{蜥蜴城？不，我从来没去过那里。难道你不知道那个地方到处都是僵尸吗？我一直在这里照看我廉尼叔叔，这已经够糟的了。你为什么问这个？}
{201}{}{啊？}
{202}{}{我杀，杀坏人！}
