#{100}{}{You enter a series of tunnels beneath Trapper Town. The smell of rat droppings is quite strong.}
{100}{}{你进入了城镇下面的隧道，里面很臭，到处是老鼠粪便的味道。}
#{101}{}{The explosion causes the damaged supports to break and an avalanche of rocks comes down from above. As this occurs, you hear what seems to be a loud crack echo throughout the cavern. As you look around you see that the other weak supports are beginning to give way.}
{101}{}{爆炸破坏了支撑物导致了岩石从上面崩塌下来。因为这个，你听见木材断裂的辟啪声贯穿了整个洞穴。你看了看周围，发现身边很多不牢固的支撑柱也要垮了。}
#{103}{}{You have trapped Keeng Ra'at! With no means out, starvation is all that is left for him to enjoy.}
{103}{}{你堵住了鼠王。他无路可走了，他的余生只能享受饥饿了。}
#{104}{}{在我被压碎之前我最好找出去去的方法。I better get out of the way of these supports before I get crushed to death or trapped.}
{104}{}{在我被压碎之前我最好找到出去的方法。}
#{105}{}{Another support beam gives way and an avalanche of rocks comes tumbling down.}
{105}{}{横梁开始倒塌，很多岩石开始落下来。}