{100}{}{你看到一个电脑终端机。}
{101}{}{你看到语音界面终端机。}
{102}{}{你看到一个标准的电脑终端机，它被改造接受语音命令。}
{103}{}{你检查电脑终端机，但是你找不到坏掉的地方。你要怎么办？}
{104}{}{用特别的方法敲它一下。}
{105}{}{踢一下特别的地方。}
{106}{}{执行自我检查程序。}
{107}{}{把它打开看看里面。}
{108}{}{不要理它。}
{109}{}{你看着那台电脑，试着决定要打那一个地方。在你狠狠的敲它一下之后，荧幕闪了几下，除此之外，就没有其它的效果了。你要怎么办？}
{110}{}{踢一下特别的地方。}
{111}{}{执行自我检查程序。}
{112}{}{把它打开看看里面。}
{113}{}{不要理它。}
{114}{}{这一种有名的修理方法现在有了两个结果。第一，荧幕闪了几下。第二，被你踢到的地方解体掉到地上了。你要怎么办？}
{115}{}{执行自我检查程序。}
{116}{}{那东西裂开了，干脆看看里面有什么吧。}
{117}{}{不要理它。}
{118}{}{你确定这系统一定会有一些自我检查的程试。不过键盘输入的功能好像被关起来了。这一个系统只接受语音命令。你要怎么办？}
{119}{}{只剩下看看里面了。}
{120}{}{不要理他。}
{121}{}{在看到许多的电线以及电路板之后，你发现系统是被人特意破坏的。其中的一块电路板，也就是语音辨识电路，被人破坏到不能修理的地步，而一定要换一片。你只要找到一片新的就可以更换了。}
{122}{}{完成。}
{123}{}{完成。}
{124}{}{你将那电路板装进了终端机里面。这一个系统被修好了。}
{125}{}{在这个系统可以运作之前，你得要安装一片新的语音辨认电路板。}
{126}{}{完成。}
{127}{}{这一个系统现在可以正常运作了。}

{128}{}{读取安全影片，执行实体显像放影..}

{129}{}{你是最后一个了，甘德。你的种族将会全部被消灭。}
{130}{}{告诉你的总统，他会付出代价的。}
{131}{}{随你说吧，你只不过是一个会说话的动物而已。}
{132}{}{是吧，但是我们却是你们研究出来的成品。你给了我们生命！}
{133}{}{那现在我给你死亡！}
{134}{}{把他的身体拿走。博士想要一个样品。}
{135}{}{他们的血将会像尼罗河一样的流！}

#added by killap - RP
#{200}{}{Welcome, Vault Dweller. For your convenience, this Vault-Tec terminal has been modified to respond to vocal commands. Please vocalize your command now.}
{200}{}{欢迎您,避难所居民。为了您的方便，这个Vault-Tec终端已经被修改以响应语音命令。现在请发出你的命令。}
#{201}{}{Oh, you've got me confused with someone else. You see, I'm not the Vault Dweller, I'm the Chosen One. }
{201}{}{哦，你把我弄糊涂了。我不是这里的居民，我是获选者。}
#{202}{}{Run diagnostics.}
{202}{}{运行诊断。}
#{203}{}{Switch to keyboard input mode.}
{203}{}{切换到键盘输入模式。}
#{204}{}{Access security footage.}
{204}{}{访问安全录像。}
#{205}{}{[注销]}
{205}{}{[注销]}
{206}{}{Urk?}


#{210}{}{[A light blinks on the terminal as it makes various clicking and whirling sounds. After several seconds, text
 appears on the monitor.] Sorry, I did not understand your command. Please repeat your command, making sure to speak
 directly into the microphone in a clear and precise manner. Vault-Tec apologizes for any inconvenience. Thank you.}
{210}{}{[一盏灯在终端上闪烁，它旋转闪烁着并发出咔哒声。几秒钟后,文本出现在监视器上。] 对不起，我听不懂你的命令。请重复你的命令，请对准麦克风，用清晰、准确的普通话进行命令。Vault-Tec为任何不便道歉。感谢！}
#{211}{}{Run diagnostics.}
{211}{}{运行诊断。}
#{212}{}{Switch to keyboard input mode.}
{212}{}{切换到键盘输入模式。}
#{213}{}{Access security footage.}
{213}{}{访问安全录像。.}
#{214}{}{[注销]}
{214}{}{[注销]}

#{220}{}{Please wait while I initiate diagnostic checks..Vault-Tec appreciates your patience……Thank you for waiting……Diagnostic
 checks complete. All systems are working properly. After all, you're using Vault-Tec. }
{220}{}{请稍候，现在开始做诊断检查。Vault-Tec感谢您的耐心，诊断检查完成。所有系统都运行正常。毕竟，你使用的是Vault-Tec产品。}
#{221}{}{Back.}
{221}{}{返回}
#{222}{}{[注销]}
{222}{}{[注销]}

#{230}{}{Switching to manual interface mode……manual interface mode initiated. For the convenience of others, this
 terminal will automatically revert to vocal interface mode once you have logged off. Please input command.}
{230}{}{正在切换到手动界面模式,手动接口模式启动完毕。为了别人的方便，当您注销后，终端将自动恢复到语音界面模式。请输入命令。}
#{231}{}{Search database for anything of interest.}
{231}{}{搜索数据库}
#{232}{}{[注销]}
{232}{}{[注销]}

#{240}{}{After a bit of searching, you discover three files that might be worth a look: Vault Dweller's Survival Guide
 [Abridged Version], Vault 13 Timeline, and Overseer Logs.}
{240}{}{经过一番搜索之后，你发现了三个值得一看的文件:避难所居民的生存指南[精简版]，13号避难所历史记录，和监督日志。}
#{241}{}{Access Vault Dweller's Survival Guide [Abridged Version]. }
{241}{}{存取避难所居民的生存指南[精简版]。}
#{242}{}{Access Vault 13 Timeline. }
{242}{}{访问13号避难所历史记录。}
#{243}{}{Access Overseer Logs.}
{243}{}{监督访问日志。}
#{244}{}{[注销]}
{244}{}{[注销]}


#Vault Dweller's Survival Guide [Abridged Version]
#{250}{}{Welcome to Vault-13, the latest in a series of public defense works from Vault-Tec, your contractor of choice
 when it comes to the best in nuclear shelters. Vault-Tec, America's Final Word in Homes.}
{250}{}{欢迎来到13号避难所，这是由你的承包商Vault-Tec的一系列公共防御工程中最新的一个。是至今为止最好的避难所，美国家庭的最终代名词。}
#{251}{}{[更多]}
{251}{}{[更多]}
{252}{}{The Vault series of survival shelters are designed from the ground up to provide the best chance for a good life
 following nuclear armageddon. It is the duty of every American citizen to learn and use the skills necessary for a comfortable Vault life. The best place to start is with a description of your new home.}
{252}{}{避难所系列产品的是设计目的是在世界核末日后提供庇护，并在重返地面之前提供最好的生活。每个美国公民都有义务学习避难所生活所必需的技能，以便在最适合开始的地方重建你舒适的新家。}
#{253}{}{[更多]}
{253}{}{[更多]}

#{254}{}{IMPORTANT VAULT 13 STATISTICS
                                    Starting construction date: August 2063
                        Ending construction date: March 2069
                             Starting Budget: $400,000,000,000
                                Final Budget, with interest: $645,000,000,000
                   Total number of occupants: 1,000 [at capacity]
                 Total duration: 10 years [at capacity]
                            Number of living quarters: 100 [hot bunking required if at maximum capacity]}
{254}{}{重要的13号避难所统计数据：
建造日期:2063年8月。
结束施工日期:2069年3月。
预算:4000亿美元。
最终预算，含利息:6450亿美元。
住户总数:1,000[以容量计]
总持续时间:10年[满负荷]
宿舍数量:100[按最大容量计算]}							
							

#{2541}{}{Door thickness: 4 yards, steel
                                       Earth coverage: 3,200,000 tons of soil, at 200 feet
           Computer control system: Think machine
                          Primary power supply: Geo-thermal
                                Secondary power supply: General Atomics Nuclear Power backup systems
                                                         Power requirements: 3.98mkw/day
                                 Stores: Complete construction equipment, hydro-agricultural farms, water purification system from underground river,
 defensive weaponry to equip 10 men, communication, social and entertainment files [for total duration]}
{2541}{}{避难所门厚:4码，材质:钢。
避难所防护层:覆盖3200万吨泥土，厚度200英尺。
计算机控制系统:思考型机器头脑。
主要电源:地热电力系统。
次要电源:通用型原子动力后备电力系统。
电力要求:3.98 mkw /天。
设施:完备的工程器械、水培室、依靠地下暗河提供水源的水处理设施，防御武器装备10人，通讯系统，社会和娱乐设施[配备额外的伊甸创造工具箱]}
      
#{255}{}{[更多]}
{255}{}{[更多]}

#{256}{}{To help Vault Dwellers record information [and information is extremely valuable, in fact, it might be the most
 valuable weapon we have against the end of civilization, so pay attention!] Vault-Tec has selected the RobCo Industries RobCo Pip-Boy 2000 as the Personal Information Processor of choice for its Vault Dwellers.}
{256}{}{为帮助避难所居民记录信息[避难所记录数据是非常有价值的，事实上，在文明终结后的世界，它可能是最重要的部分，所以务必要注意!]。Vault- tec选择了RobCo Industries RobCo Pip-Boy 2000作为其避难所居民的个人信息处理器。}
#{257}{}{[更多]}
{257}{}{[更多]}

#{258}{}{The RobCo Pip-Boy 2000 is a handy device that you wear on your wrist. It's small, especially by today's standards, and it will store a goodly amount of information for you. And using modern super-deluxe
 graphics to boot! Please refer to your Pip-Boy manual for 更多 information.}
{258}{}{RobCo Pip-Boy 2000是一个你在手腕上佩戴的方便设备。它很小，并且使用简单易用的图形化界面!它将为您存储大量的信息。更多信息请参考您的Pip-Boy手册。}
#{259}{}{[更多]}
{259}{}{[更多]}

#{260}{}{The key to a successful reintroduction of civilization following a massive scale nuclear war is people. Here at Vault-Tec, we are working to ensure to your fellow man [and woman] is up to the task of bringing America back from the dead.}
{260}{}{在大规模的核战争之后，成功重建文明的关键是人才。Vault-Tec公司将确保你和你的同胞能够完成把美国从死亡线上拉回来的任务。}
#{261}{}{[更多]}
{261}{}{[更多]}

#{262}{}{We believe that a positive attitude is one of the best tools at our disposal. Should you encounter any fellow Vault Dwellers displaying a less than positive attitude, you are encouraged to report them to your Vault's Overseer. Remember, once the doors are sealed, the Overseer's word is law.}
{262}{}{我们相信，积极的态度是我们处理异常状况最好的工具之一。如果你在避难所中遇到散播消极情绪的人，请报告给你的避难所监督者。记住，当避难所大门关闭后，监督者的话就是法律。}
#{263}{}{[更多]}
{263}{}{[更多]}

#{264}{}{Vault-13 comes prepared with the latest in survival equipment. The items in your storage containers will last 1,000 people over 10 years in comfortable and modern surroundings. When it is time to leave the Vault, and return to rebuild America, your friends at Vault-Tec have provided you with everything that you will need.}
{264}{}{13号避难所配备了最新的生存设施。在避难所中的1000位成员将会在舒适和现代的环境中度过10年，以躲避地面上恶劣且未知的一切。当你离开避难所返回地面重建美国之时，Vault-tec将准备好你所需的一切。}
#{265}{}{[更多]}
{265}{}{[更多]}

#{266}{}{Thank you for taking the time to read The Vault Dweller's Survival Guide [Abridged Version]. We at Vault-Tec feel confident that you'll love your new underground dwelling.}
{266}{}{感谢您花时间阅读避难所居民的生存指南[精简版]。Vault-Tec非常之有信心，你将会喜欢你的避难所生活。}
#{267}{}{Access Vault 13 Timeline. }
{267}{}{访问13号避难所历史记录。 }
#{268}{}{Access Overseer Logs.}
{268}{}{访问监督日志。}
#{269}{}{[注销]}
{269}{}{[注销]}

#Vault 13 Timeline
#{270}{}{As you read over the beginning of the timeline, you find it interesting that no reason is given for why the Vault didn't open 10 years after the Great War, as it was originally designed to. }
{270}{}{你从避难所历史记录的未尾开始阅读，你发现让人感到困惑的是，在第一次世界大战之后的10年这个避难所的大门并没有被打开，这与它最初的设计目标不符。但对这件事，你在历史记录找不到任何的解释。}
{271}{}{[更多]}

#{272}{}{Browsing ahead, you don't find much of interest until the year 2161, when the Vault's only working water chip breaks down. You feel a surge of pride as you read about your grandfather being selected for the important task of leaving the Vault and scouring the wasteland for a replacement water chip. However, it feels a little odd seeing your tribe's most revered legend told in a simple bullet point format.}
{272}{}{[再往前看，你发现更多你感兴趣的东西]2161年，13号避难所唯一的净水晶片损坏，你的祖父被挑选出来离开这座活人墓在废土上寻找替代的净水晶片。[读到这里你感到一阵骄傲]但是，你看到你的部落最受人尊敬的传奇人物，在这份历史记录里竟然只有轻描淡写的记录，你感到很奇怪。}
{273}{}{[更多]}

#{274}{}{Continuing down the timeline, you read of your grandfather's success and subsequent exile, and how several other vault dwellers chose to join him rather than remain in the relative safety of the Vault. You also discover that the Overseer was eventually tried and executed by the remaining vault dwellers.}
{274}{}{顺着这条记录往下看，你看到了你祖父的成功和随后的被流放，以及几位支持者选择加入他而不是留在相对安全的避难所。你还发现，监督者最终被剩下的避难所居民审判和处决。}
{275}{}{[更多]}

#{276}{}{The final entry in the timeline is dated May of 2242. It seems that, for the first time, Vault 13 was sent an "all clear" signal from an unknown source. After some debate, the vault dwellers decided to open the Vault doors and see what awaited them on the surface world. There is no record of what happened to them after that.}
{276}{}{历史记录上的最后一项日期为2242年5月。似乎第一次，13号避难所从一个未知的来源收到了一个“污染清除”的信号。经过一番讨论后，避难所的居民决定打开避难所的门，看看在地面上等待着他们的是什么。在那之后就再也没有新的记录了。}
#{277}{}{Access Vault Dweller's Survival Guide [Abridged Version]. }
{277}{}{存取避难所居民生存指南[精简版]。}
#{278}{}{Access Overseer Logs.}
{278}{}{访问监督日志。}
{279}{}{[注销]}

# Overseer Logs
#{280}{}{Authorization required. Please enter password. }
{280}{}{授权要求。请输入密码。}
{281}{}{[返回]}
#{282}{}{[Guess password]}
{282}{}{[猜密码]}
#{283}{}{[Attempt to hack into it.]}
{283}{}{[试图入侵它]}
{284}{}{[注销]}

#Guess Password
#{290}{}{Incorrect. Please enter password.}
{290}{}{你输入的密码不正确的。请重新输入密码。}
#{291}{}{[BACK]}
{291}{}{[返回]}
#{292}{}{[Guess password]}
{292}{}{[猜密码]}
#{293}{}{[Attempt to hack into it.]}
{293}{}{[试图入侵它]}
{294}{}{[注销]}

#After 3 Incorrect Guesses
#{300}{}{Incorrect. You are now locked out of these files. Vault-Tec apologizes for any inconvenience.}
{300}{}{你输入的密码不正确的。你的账号已经被锁定。Vault-Tec对为此造成的任何不便致歉。}
#{301}{}{[BACK]}
{301}{}{[返回]}
#{302}{}{[Attempt to hack into it.]}
{302}{}{[试图入侵它]}
{303}{}{[注销]}

#{310}{}{[You try everything you can think of, but you're unable to gain access. With a sigh of defeat, you return to the main menu.]}
{310}{}{[你尝试了所有你能想到的办法，但你无法获得访问。你叹了口气，回到主菜单。]}
#{311}{}{Run diagnostics.}
{311}{}{运行诊断。}
#{312}{}{Switch to keyboard input mode.}
{312}{}{切换到键盘输入模式。}
#{313}{}{Access security footage.}
{313}{}{访问安全录像。}
{314}{}{[注销]}

#{320}{}{Password correct. All entries but one have been removed from the system. Final entry in the Overseer's Logs is still accessible.}
{320}{}{密码正确。所有的记录均已经从系统中删除，在监督者的日志中最后的记录仍然是可访问的。}
#{321}{}{[After several long minutes of working your technical magic, you manage to hack your way into the Overseer's Logs. However, it seems that every entry except for the final one has been deleted.]}
{321}{}{[几分钟之后，你设法侵入了监督者的日志]然而，似乎除了最后一个记录之外，所有记录都被删除了。}
#{322}{}{Alright, let's see what this Overseer had to say. [Read Log.] }
{322}{}{好了，让我们看看这个监督者说了些什么。[读取日志]}
#{323}{}{Eh, whatever. [Logoff.]}
{323}{}{呃，等等。[注销]}

#{330}{}{This is it. Consider these my final words, as I doubt I'll live to write another entry. Oh no, the people of the Vault have spoken, and they've made it quite clear that they want my head. I knew this day would come, ever since HE managed to rile them up by doing the impossible. Sure, he saved all our lives, but he also ruined everything.}
{330}{}{这很可能是我写的最后一句话，我怀疑我能不能活到写下一篇记录。哦，应该不会有下一篇了，避难所的人们已经很清楚地表达了，他们想要的是我的命。自从“他”使他们摆脱不可能，我便知道这一天终将会到来。他救了我们的命，但他也毁了一切。}
{331}{}{[更多]}
#{332}{}{Let it be known that I took little joy in exiling our "great hero", but I had no choice in the matter. His adventures in the outside world had changed him too much. He was too great a threat to the project. Had I let him remain among us, he might have uncovered the true nature of the Vaults and jeopardized the experiment. Even if he didn't, he'd at least inspire others to venture outside, which would be just as bad.}
{332}{}{事实上，我也为拯救我们的“伟大的英雄”而欢欣鼓舞。但在这件事上我没有选择，他在外面世界的冒险经历已经改变他太多了，他对这个项目的威胁太大了。如果我让他继续留在我们中间，他可能会知道并向人们揭示避难所的本质，并危及整个实验。即使他没有这样做，他至少也会鼓励其他人去外面冒险，这也同样糟糕。}
{333}{}{[更多]}
#{334}{}{He simply had to go. There was no other option. But even that wasn't enough. No, I'm afraid the damage had already been done. I allowed his most stubborn supporters to follow him into exile, and then tried to reassert my control over those who remained. But it was no use -- I'd already been vilified. So be it. The only thing I'm guilty of is an entire lifetime of carrying out the demands of our Great Nation.}
{334}{}{我必须让他离开，没有别的选择，但这还不够。恐怕我担心的事情已经在逐渐蔓延了。我让他最顽固的支持者跟着他离开，然后试图控制局面，向那些留下来的人重新灌输“外界很危险”的信息。但是我知道这不会有很大的效果，我的公信力已经受到质疑了。我这辈子唯一的罪过就是一生都在履行我们伟大国家的要求。}
{335}{}{[更多]}
#{336}{}{My only regret is that Vault 13 is not likely to complete the social experiment. Once I've been disposed of, I feel certain the others will leave the Vault. Not right away, of course -- I've instilled too much fear in them of the outside world. But eventually, they're bound to overcome that fear. I have very little faith that Vault 13 will remained closed until 2277, as the experiment dictates.}
{336}{}{我唯一的遗憾是13号避难所恐怕不太可能完成“社会保存计划”了。一旦我被处决了，我相信剩下的人都会离开避难所。当然，他们应该不会马上就离开，因为我给他们灌输了很多关于外部世界的恐惧。但最终他们一定会克服这种恐惧，13号避难所应该不会坚持封闭到实验所规定的2277年了。}
{337}{}{[更多]}
#{338}{}{I'm afraid I have failed my duty as Overseer. I can only hope that the rest of the public Vaults involved in the Societal Preservation Program have been more successful. To my superiors, who I'm certain will one day read this: forgive me. And may God bless America.}
{338}{}{我恐怕已经无法履行我的职责了。我只能希望其余参与“社会保存计划”的避难所可以取得成功，希望这份记录会在将来被我的同撩看到。请原谅我，愿上帝保佑美国。}
#{339}{}{Search for any other files that contain information on "Societal Preservation Program".}
{339}{}{搜索任何包含“社会保存计划”信息的文件。}
{340}{}{[注销]}

#{350}{}{After hours of scouring through the computer's archives, you're unable to find anything else that mentions the Societal Preservation Program. As you give up your search, you vow never again to waste so much time staring at a computer monitor.}
{350}{}{经过数小时的搜索，你无法找到任何提及“社会保存计划”的东西。你揉了揉发酸的眼睛，放弃了搜索，你发誓再也不会浪费这么多时间盯着电脑显示器。}
{351}{}{[注销]}

#{360}{}{After hours of scouring through the computer's archives, you're able to locate a few hidden documents concerning the Societal Preservation Program. As you read over them, you uncover a rather disturbing truth about the Vaults: they were never intended to save the population of the United States.}
{360}{}{经过数小时的搜索，你找到一些有关社会保存计划的隐藏文件。当你读到他们的时候，你发现了一个相当令人不安的事实:"避难所从来不拯救任何人"}
{361}{}{[更多]}
#{362}{}{Incredibly, all 122 of Vault-Tec's public Vaults were part of a grand social experiment orchestrated by the US government. Only 17 of those Vaults, dubbed "control Vaults", were designed to function correctly [it seems Vault 8 was one of the lucky few]. The rest were meant to have various critical flaws, so that the government could study the pre-selected occupants, and see how they react to the stresses of their situations, and how well they're able to re-colonize once their Vaults open.}
{362}{}{你搜索到的信息简直令人难以置信，在全部122个避难所中，所有的公共避难所都是由美国政府精心策划的大型社会实验的一部分。只有17个被称为“控制端”的避难所被设计成正确的功能[似乎8号避难所是少数幸运儿之一]。其余的则故意在建造时留下各种各样的缺陷，这样政府就可以研究这些预先选定的住户，看看他们如何应对他们所面临的压力，以及一旦他们的避难所打开，他们又能如何重新开始地面生活。而最终这些避难所成功与否，实验者都不关心，美国政府关心的是“如果地球被毁了，之后我们到另一个星球该如何定居”，避难所实验只是这个计划的其中一环。}
{363}{}{[更多]}
#{364}{}{It seems Vault 13's role in the experiment was to remain closed for 200 years to test the effects of prolonged isolation. Apparently, the breaking down of the water chip was un-intended, and forced the Overseer to improvise by selecting your grandfather to go out and fetch a new chip. After some more digging around, you manage to find descriptions of some of other Vault experiments.}
{364}{}{在这个实验中，13号避难所的作用似乎并不是封闭10年，而是保持封闭200年，以测试长期隔离的效果。显然，净水水晶片是意料之外的事情，这迫使监督者通过选择你的祖先去拿一个新的芯片来临时凑合。在进行了更多的挖掘之后，你可以找到一些关于其他避难所实验的描述。}
{365}{}{[更多]}
#{366}{}{Vault 12's door was designed never to close, so that the assholes behind this experiment could "study the effects of radiation on the selected population". If you recall the legend correctly, Vault 12 was located under the ghoul filled city of Necropolis, where the Vault Dweller finally found the water chip. It seems quite likely that the ghouls were the result of this experiment.}
{366}{}{12号避难所的门从来没有关闭过，所以这个实验背后的混蛋可以“研究辐射对所选人群的影响”。你回想起祖父的传奇，12号避难所就坐落在一个充满僵尸的城市里，被流放者终于找到了净水晶片。食尸鬼似乎很可能就是这次实验的结果。}
{367}{}{[更多]}
#{368}{}{Vault 15, another key location in the Vault Dweller's quest, was to be populated by people with "radically diverse ideologies" that would be sealed in the Vault together for 50 years. Vault 27 was to be purposely overcrowded with 2,000 people -- double the maximum capacity. That couldn't have been pretty. Vault 29 was to be populated only by those under the age of sixteen, with their parents "purposely redirected to other Vaults".}
{368}{}{15号避难所是“避难所文化融合探索”的实验地点，它的居民是文化与意识形态之间存在着极端剧烈的冲突的人，他们将在一起被封存50年，以观察在数十个乃至数百个不同文化之间的融合或者冲突。27号避难所容纳的人口数被故意超过其能容纳的限度，足足有2000人，是最大容量的两倍。避难所29号的居民均不超过15岁,他们的父母都被有意的安排到了其他的避难所，避难所用一部ZAX超级电脑代替人工控制，电脑依靠机器人助手来治疗和抚养儿童，给予他们基础教育，待孩子成年后逐步将他们释入一个可控环境。观察他们回到地面后，是否能够重建社会。}
{369}{}{[更多]}
#{370}{}{Vault 34's experiment involved an armory overstocked with weapons and ammo, and, of course, not provided with a lock. How pleasant. Vault 36 suffered from food extruders that were designed to produce only "a thin, watery gruel", while Vault 42 was outfitted only with dim lighting—no light bulbs of over 40 watts were provided.}
{370}{}{34号避难所内储存了大量的武器,但在这个避难所中并没有一把锁。36号避难所的食品生产机被设计成只能生产一种“极其稀薄”的流质食品。而42号避难所只配备了昏暗的照明——这个避难所里没有超过40瓦的灯泡。}
{371}{}{[更多]}
#{372}{}{Vault 53's equipment was designed to break down every few months. While repairable, the constant breakdowns were meant to test the stress of the inhabitants. You wonder how many expert mechanics and technicians that Vault produced. Vault 55 would have all its entertainment tapes removed, while Vault 56 would have all its entertainment tapes removed, with the exception of one featuring a particularly bad comic actor.}
{372}{}{53号避难所绝大部分设备被设计为每几个月就瘫痪一次.但都是可修复的，这种瘫痪旨在用来给避难所居民不定期地增加压力。56号避难所里除了一个非常蹩脚的喜剧演员主演的影片之外，没有一点娱乐媒介。社会学家们认为这个避难所将会先于55号避难所崩溃。}
{373}{}{[更多]}
#{374}{}{Vault 68 was to be occupied by 999 males and only one female. You can only imagine the horrors that took place there……Vault 69, on the other hand, was to be occupied by 999 females and only one male……interesting. Vault 70's jumpsuit extruders were designed to fail after 6 months. And finally, Vault 106 was designed so that 10 days after being sealed, it would begin "releasing psychoactive drugs into the air filtration system".}
{374}{}{第68号避难所内1000个居民中只有一个女性，而69号避难所则恰好相对，只有1个男性，余下的都是女性[你很难相象这到底是幸福还是恐怖]。70号避难所的衣物制造机在避难所关闭6个月后失效,而在这个避难所里绝大多数的居民都是摩门教徒。最后，106号避难所关闭10天后开始向空气中注入致幻毒气。}
{375}{}{[注销]}

#{500}{}{You learn about the Vault Experiments and the roles of the various Vaults.}
{500}{}{你了解了Vault实验和各种避难所的作用。}
#{510}{}{You learn about the history of Vault 13 and the Overseer's role in the Vault Experiments.}
{510}{}{你了解了13号避难所的历史和监督者在避难所实验中的角色。}

#{520}{}{I'm sorry, I did not understand that.}
{520}{}{对不起，我不明白。}
{521}{}{[注销]}
