{100}{}{你看到一个很老，但是看起来很亲切的人。}
{101}{}{那是朱伯利医生。}
{102}{}{那是一个有着雪白胡子的老人，一脸的轻蔑表情。}
{103}{}{我是朱伯利医生。那里有不对劲吗，年轻人？}
{104}{}{那里有不对劲吗，年轻人？}
{105}{}{我受伤了。}
{106}{}{我需要一个医生。}
{107}{}{你难道不能吃一些药或者是怎么样的，不要来烦我好吗？}
{108}{}{哼，你根本就没有在流血嘛。}
{109}{}{我不知道，我不觉得我能够救你的腿，也许得要把它截了。}
{110}{}{你在开玩笑吧。}
{111}{}{哈哈。}
{112}{}{就是那样，小子。}
{113}{}{又是你。}
{114}{}{谢谢，医生。也许你能帮我解答一些问题。}
{115}{}{再见。}
{116}{}{那会花掉你$50。}
{117}{}{赶快帮我治疗吧。}
{118}{}{我不要待在这里。}
{119}{}{你让我觉得好多了。}
{120}{}{我要走了。}
{121}{}{不，不是开玩笑。我最好在坏死之前把那条腿切下来。}
{122}{}{我不能，不会，也不可能让你把我任何地方截掉，懂吗？}
{123}{}{我受够了，我要走了。}
{124}{}{好吧，那个地方如果烂掉，可不要怪我啊。}
{125}{}{我这里又不是慈济医院。你得掏钱我才能帮你治疗。}
{126}{}{我可以帮你做什么吗？}
{127}{}{说吧。}
{128}{}{第13号避难所？}
{129}{}{你知道在哪，可以让我找到第13号避难所吗？}
{130}{}{我听闻卫斯丁先生身体不太好，那是真的吗？我很担心他会出事，毕竟他还欠我一些钱呢。}
{131}{}{有一个叫咸牛的人说你从他那里偷走了一张地图，这是怎么回事？}
{132}{}{我正在找工作，知道哪有工作吗？}
{133}{}{医生，关于那群对抗那些邪恶的奴隶贩子的人，你有什么知道的吗？}
{134}{}{不用担心，如果他不再残害自己的身体，不抵触我的治疗方案和药物，他也许比我们活得都长。}
{135}{}{那真是好消息。我还想知道一些事情。}
{136}{}{谢谢，医生。}
{137}{}{那个老醉鬼！？我唯一从他手上得到用来代替现金的，就只有那幅画着一个人像的油画，听说那个人叫“猫王”。}
{138}{}{“猫王”的油画？我可以看看它吗？}
{139}{}{并不是张地图，哈？那好吧，我们谈点别的吧。}
{140}{}{我得要走了。}
#{141}{}{I ain't heard that mentioned since old Saltbeef was brought in here. Sunstroke. Burned with fever for three days, all the time ranting how he'd found Vault 13, his mother lode.}
{141}{}{在咸牛来这里之后，我就再没有听过有人提到那个地方了。那个时候他中了暑，那三天里他发着高烧，迷迷糊糊地一直在喊他是怎么找到13号避难所，那个他出生的山洞的。。}
{142}{}{出生的山洞？}
{143}{}{那它到底在那里？}
{144}{}{避难所在那？}
{145}{}{不知道，咸牛声称有到那里的地图，但是从来都没人见过。}
{146}{}{咸牛？}
{147}{}{告诉我更多的。}
{148}{}{很好，那是我找到的最有用的线索了。}
{149}{}{咸牛是个老铀矿探矿者，或者更确切的说，他是个醉鬼。这段时间他就住在卫斯丁的双头牛牧场。}
{150}{}{还有别的问题……}
{151}{}{谢谢你告诉我这些事。}
#CMH changing per Fergus.. Now you have to pay 1000 or steal the painting off of him.
{152}{}{嘿，正好我想拿它卖些钱。只要$}
{153}{}{也许下次吧，我还有些问题……}
{154}{}{也许下次吧，我要走了。}
{155}{}{咸牛是老铀矿的探矿者。这段时间他就住在卫斯丁。}
{156}{}{还有别的问题……}
{157}{}{谢谢你告诉我这些事。}
{158}{}{你最好去与坦蒂总统谈谈。我听说她正在找一些特别的人。}
{159}{}{还有别的问题……}
{160}{}{谢谢。}
{161}{}{我想，那是一个对抗奴隶贩卖和其他犯罪行为的组织吧。他们在市东的修车厂那里有个落脚点，有可能你能在那里修车子。}
{162}{}{还有别的问题……}
{163}{}{谢谢。}
{164}{}{嘿，住手，混蛋！}
{165}{}{当心！别暴露了自己。}
{166}{}{把它放回去！你一不小心就会伤到自己的。}
{167}{}{这些药是给卫斯丁先生。把它们放回去。}
{168}{}{离开那里。小心一点，我们可不想让卫斯丁先生药出问题。}
{169}{}{小心点！我才刚刚量好了卫斯丁先生的药量。}

{170}{}{我是朱伯利医生，有什么不对吗，小姐？}
{171}{}{有什么不对吗，小姐？}
{172}{}{你在那里啊，小姐。}
{173}{}{你不用担心，小姐。如果他不再残害自己的身体，不介意我的治疗方案和药物，他也许比我们活得都长。}
{174}{}{当然，这里是$}
{175}{}{谢谢，我一直都想要从咸牛的身上拿钱回来，但是那混帐身上从来都没半毛钱。}
{176}{}{。}

#RP content - killap
#{200}{}{Whoa there, }
#{201}{}{son! }
#{202}{}{missy! }
#{203}{}{You can't be messing with that stuff! I just measured out Mr. Westin's dose and we wouldn't want him getting the wrong meds now. What in blazes do you think you're doing?}
#{204}{}{I was just trying to get a look at those pills you have on the shelf there.}
#{205}{}{Oh, don't mind me. I was just window shopping.}
#{206}{}{Sorry. I've just always had this irresistible compulsion to dig around in other people's stuff that I've never been able to shake.}
#{207}{}{Honestly? Not expecting you to be that observant. I guess I'm going to have to improvise.}

{200}{}{离开那儿, }
{201}{}{小子! }
{202}{}{女孩! }
{203}{}{你不能在那儿，你会把东西弄乱的！我才刚刚量好了卫斯丁先生的药量，我们不希望他现在拿错药。你脑子抽了么，你到底想什么？}
{204}{}{我只是想看看你架子上的那些药片。}
{205}{}{哦，别介意，我就是看看而已。}
{206}{}{抱歉。我总是有种不可抗拒的冲动，想要在别人的东西里挖来挖去，我一直都无法摆脱这种事。}
{207}{}{你是认真的？没想到你会这么细心，我想我得“改变一下计划”了。}



#{210}{}{Were you, now? (Doc Jubilee regards you coolly.) I'd guess you were a mite young to be suffering from a bum ticker.}
#{211}{}{And you'd be right. I'm asking for my friend Cassidy. Older fella. He's got a bad heart, and traveling the wastes is getting kind of rough on him.}
#{212}{}{And I'd wish you were right. I got it from my pa. Or so they tell me.}
#{213}{}{Oh, nothing like that. I'm just overbearingly inquisitive, I guess.}

#{210}{}{你有什么事？[朱伯利医生对你很冷淡] 我想你这小鬼肯定是遇到麻烦了。}
{210}{}{这次是你？[朱伯利医生对你很冷淡]我觉得你这种没心没肺的小孩并不会得心脏病。}
{211}{}{你还真猜对了。我的朋友盖西迪，他是一个老小伙了，所以他的心脏不太好，在废土的旅行对他来说有点困难。}
{212}{}{我想你猜对了。我从我老爹那弄来药片。就这样，他们就告诉我了。}
{213}{}{哦，没什么。也许，就是感到好奇吧。}


#{220}{}{Well, you can't. This is a private practice, not a drugstore. You might want to try Duppo's, a tetch north of here.}
#{221}{}{Sounds like just what I'm looking for. Bye.}
#{222}{}{I'll check 'em out. In the meantime, though, do you mind if I ask you a few things?}
#{223}{}{No, I think I came to the right place. I can see you're doing good work here. I thought I might offer a donation.}

{220}{}{嗯，你不能。这是私人诊所，不是药店。你应该去杜普的店里去看看，就在北边不远。}
{221}{}{看上去就像我正要找的，谢谢。}
{222}{}{我回去看看的。在此之前能让我问你些事情么?}
{223}{}{不，我想我来对地方了，我看得出来你在这里干得很好。我想我应该提供点捐款。}


#{230}{}{(The doctor blinks. He blinks again.) You should probably talk to somebody about that. Unfortunately, I ain't the right kind of doctor. All's you need to know about that shelf is that if you mix up or taint any of those prescriptions, some poor fella's liable to end up in a world of hurt, if they're still in this world at all. Best keep your hands to yourself.}
#{231}{}{Will do, doc. But, uh, say-- I've got a buddy who could really use some of those heart pills you've got there. Think you'd be willing to sell me some?}

{230}{}{[医生眨了眨眼睛]你应该换个人谈谈，我不是负责那个专科的医生。另外请你明白一件事，如果你搞混或者污染了处方里的东西，一些可怜的家伙就会在这个世界上受到伤害，所以管好你的手。}
{231}{}{好的，医生。但，呃，我朋友真的很需要心脏病药。你愿意卖给我一些吗？}

#{240}{}{Awww, }
#{241}{}{son, }
#{242}{}{miss, }
#{243}{}{I wish I could help you, but I'm not taking on any new patients right now. Council's got me on retainer. Can't sell you no pills, neither-- Councilman Westin's people are supposed to pick those ones up in }
#{244}{}{ days, }
#{245}{}{ day, }
#{246}{}{and just ain't no way I'm going to have time to mix up another batch before then.}
#{247}{}{I understand, doc. Maybe I'll find a decent pharmacist somewhere else. If it's not too much to ask, though, is there any advice you could give me on the subject? You don't find medicine like that too often.}
#{248}{}{Those are the breaks, I guess. Anyway, I should be alright. I've picked up *tons* about cardamomagy from old comic books. Cut the hard chems back to twice a day, TOPS, make sure to get your exercise in short, strenuous bursts so your heart doesn't have time to act up, all kinds of good stuff.}


{240}{}{哦哦哦, }
{241}{}{小子, }
{242}{}{女孩, }
{243}{}{我也希望能帮你，但事实上我现在没法接纳新病人了。议会让我退休。我手上没药卖给你了，除了威斯丁议员嘱咐的人在}
{244}{}{ 天后来取的药, }
{245}{}{ 天后来取的药, }
{246}{}{而且这段时间里也不够我再做一批药了。}
{247}{}{我理解，医生。也许我会在别的地方找到一个好药剂师，你能给我一些建议吗？在废土上这种药并不常见。}
#{248}{}{我想，就是得好好休息吧，应该没事的。我已在旧漫画里经看过*成吨的*的蠢蛋。每天不计其数的嗑药，猛烈的而急促的运动。明显这样会让心脏没法做好它该做的事情。}
{248}{}{好，我想我应该没什么要问的了。我已经在旧漫画里经看过*成吨*关于心脏病方面的资料。例如多嗑点药，保证你的运动足够的剧烈而且短促，这样你的心脏就没有时间去做别的事了，恩，没错。}

#{250}{}{I feel for you, friend, but I'm afraid those pills are for Councilman Westin, and I ain't taking on any new patients right now so I wouldn't be able to write you up a script. Now please, don't go messing around on that shelf anymore. Those prescriptions get mixed up, someone could wind up in a pretty bad way.}

{250}{}{抱歉了，朋友，但是那些药丸确实是给议员威斯丁的，我没办法接纳新病人了，也没办法给你开方子。现在别再弄那个架子了。如果你把这些处方搞混，有人可能会遭殃的。}


#{260}{}{Let's be clear here, }
#{261}{}{mister. }
#{262}{}{missy. }
#{263}{}{What exactly do you mean by "donation?"}
#{264}{}{A charitable contribution, in furtherance of your service to the public, say…… $150? You can count it out in the back room. Should only take a minute, right?}
#{265}{}{Uh, actually, I think I'd better check with my accountant before I do anything rash. See you later, doc.}

{260}{}{我们在这里搞清楚, }
{261}{}{小子。}
{262}{}{女孩。}
{263}{}{你所说的“捐款”到底是什么意思?}
{264}{}{为了促进你对公众的服务做的一个慈善的捐赠，$150如何？你可以在后面的房间清点一下。}
{265}{}{呃，实际上，我想在做任何鲁莽的事之前，我最好先和我的会计核对一下。再见，医生。}


#{270}{}{No can do, I'm afraid. Those are for Councilman Westin. His people are due by to pick them up in }
#{271}{}{ days, }
#{272}{}{ day, }
#{273}{}{and I'm not going to have the time to mix up another batch before then. I'm sure you can find a pharmacist with a lighter workload.}
#{274}{}{I see. Well, thanks anyway.}

{270}{}{我恐怕不行，这些药是给议员威斯丁的，他的人在 }
{271}{}{ 天后会来取药, }
{272}{}{ 天后会来取药, }
{273}{}{而且我在那之前没空再做一批新药。我相信你能找到一个有闲余时间的药剂师。}
{274}{}{我明白了，好，谢谢。}



#{280}{}{(Doc Jubilee gapes at you for a moment.) Aw, you're puttin' me on, right? You've gotta be puttin' me on. (glances at you again, shakes head, blows out cheeks) Hooo, boy. Either way, I wouldn't be no kind of doctor if I let you walk out of here without a few pointers, at least.}
#{281}{}{Let's see…… for starters, you should prob'ly stop doing…… well, near to just about everything oughta cover it. No drinking, no smoking, no red meat, NO chems. Try to get a half-hour a day of MILD exercise. And take it easy. Life ain't a race, 'least not the kind where you want to be first to finish. Truth told, no one ever listens to this stuff, but at least I'll be able to rest easier tonight.}
#{282}{}{More important, you need to find you a half-decent chemist and tell 'em you need set up with a regular supply of Triproxinil. Tri-prox-i-nil. Wasteland stock ain't gonna be as fancy as what I got on the shelf there, but chemically, it's all the same once you get down to brass tacks. 30 milligrams, twice a day.}
#{283}{}{Now, you gotta be sure to drink plenty of water while you're on this stuff. And for criminy sakes, you stay *as far as you can* from those pecker pills like they got up in New Reno, understand? They don't play nice together. Fella takes one while he's on the other, his John Thomas ain't nearly the only part of him going stiff that day, if you follow.}
#{284}{}{(To yourself) Hmm, that could work. Yeah. Maybe something in the way of a PDE-5 inhibitor compound……}
#{285}{}{Oh-- And if you *do* go through one of them Reno hucksters, they might go tellin' you that this stuff'll proof your heart against just about any pusher's poison you'd care to try. I ain't gonna lie to you-- there's prob'ly some truth to that. Still don't make bein' a junkie any more glamorous. You're grown and out of britches, so I ain't gonna lecture, but there it is.}
#{286}{}{Thanks a million, doc. You have no idea what a help you've been. Take care.}
#{287}{}{Tri-prox-i-nil, no bo-ner-pill. Heh heh. I'll keep that in mind. See you around, doc.}


{280}{}{[朱庇特医生盯着你好一会]你在讽刺我是吗？你就是在讽刺我。[再次瞥了你一眼，摇了摇头]好吧，小子，如果我让你离开这里，但又不给你几句能称之为医嘱的话，我就不会是一个医生了。}
{281}{}{首先，你应该停止做……其实我说的所有东西都必须要做，不喝酒，不抽烟，不吃红肉，不吃巧克力。试着每天做半小时的轻度锻炼，记得是轻度运动，活着不是赛跑，至少不是你想要先完成的那种。事实证明，没人照着我说的做了，但说完这些也许能让我睡个好觉。}
{282}{}{另外，你还得去找个二流的药剂师，让他定期供应的Triproxinil。当然废土里的货肯定不如我架子上的哪些，但毕竟是同样的化合物，吞下后效果也基本上差不多。每次30毫克，每天两次。}
{283}{}{另外要注意饮水，还有，不要磕药。远离新里诺那些象啄木鸟那样嗑药的飞行员。如果有人把Triproxinil和那些兴奋剂一起嗨，那他硬的可能就不只是他的小弟弟了。}
{284}{}{[对你说]恩，那应该有效果。是的，可能是一种PDE-5抑制剂化合物就可以……}
{285}{}{哦，对了，你如果真碰上了新里诺那帮飞机师，他们可能会说这些东西能证明你的心脏有多强大，我不打算骗你，他们说的可能有一定是对的。但是别认为瘾君子有啥魅力。你已经长大了，不再是小鬼，所以我不说教了。}
{286}{}{一百万个感谢，医生。感激不尽，无以言表。保重。}
{287}{}{Tri-prox-i-nil，不是bo-ner-pill，哈哈。我会记住的。再见，医生。}



#{290}{}{You think you're dealing with some shifty bartertown sawbones, }
#{291}{}{son, }
#{292}{}{girlie, }
#{293}{}{is that it? Don't. I am a trained and accredited NCR medical professional, and that's worth a lot more than that pocketful o' chump change.}
#{294}{}{My apologies. Obviously, a practitioner of your caliber rates a donation of no less than $250.}
#{295}{}{(hang head) Look, I'm really sorry. I'm not proud of myself, and I would normally never have tried anything like that, but I'll be honest with you: I was desperate for those pills.}
#{296}{}{Sorry for the trouble. I think I'd better just go before I dig myself a bigger hole.}

{290}{}{你觉得是在和地摊上的小贩耍滑头吗？}
{291}{}{小子，}
{292}{}{女孩，}
{293}{}{我可是个受过培训的，驻扎在NCR的医药专业人士，你这点破钱根本不足挂齿。}
{294}{}{我很抱歉低估了你，显然一个称职的医生应当获得$250的捐款。}
{295}{}{[摇头]听着，我真的很抱歉。我并没有看不起你的意思。一般情况下我也不会这么做，但现在我只能恳求你，我真的非常需要那些药片。}
{296}{}{对不起，给你添麻烦了。我想我还是离开吧，然后给自己挖一个坑。}


#{300}{}{(Doc Jubilee begins to turn red.) I don't think you heard me the first time,}
#{301}{}{ boy, }
#{302}{}{ woman, }
#{303}{}{so listen close: I am a doctor of the NCR. It's a solemn duty, and it came with a solemn oath. You ask me one more time to piss on that oath, the ONLY part of it that's going out the window is "first, do no harm." You got me?}
#{304}{}{Alright, screw it. If you're as great as you seem to think you are, maybe you'll be able to sew yourself back together after this.}
#{305}{}{Whoa, now. Didn't mean to step on any toes, doc. I'll just leave you be for awhile.}

{300}{}{[朱庇特医生脸气的发红]我想你是没听清开始我给你说的话，}
{301}{}{小子，}
{302}{}{女孩，}
{303}{}{听好了：我是NCR的医生。这是一项庄严的职责，也是誓言。你在一次又一次地触犯我的底线，你知道吗？}
{304}{}{好吧，去你的。如果你真那么自视伟大，}
{305}{}{哇，好吧。我无意冒犯你，医生。我还是走吧。}


#{310}{}{Say, doc, I was wondering about those heart pills you've got up there on the shelf.}
#{311}{}{Are you sure you can't reconsider selling me some of those pills?}

{310}{}{医生，关于你在架子上放的那些心脏药。}
{311}{}{你确定你不能重新考虑卖给我一些这些药片吗?}


#{320}{}{Sorry, Councilman Westin's people are due by to pick those up in }
#{321}{}{ days, }
#{322}{}{ day, }
#{323}{}{and I'm just too busy to mix up another batch in time.}

{320}{}{这些药是给议员威斯丁的，他的人在  }
{321}{}{ 天后会来取药, }
{322}{}{ 天后会来取药, }
{323}{}{而且我不会有时间在那之前再做一批新药。}

#{324}{}{(Mutters to himself) Where the hell did I put those pills for Mr. Westin. His heart aint gonna last long without 'em. (He looks up) Oh, sorry. What can I do for you today?}
#{325}{}{I couldn't help overhearing what you said about heart pills. I was actually going to ask you about such medicine.}
#{330}{}{(Mutters to himself) I can't believe Mr. Westin's dead. Couldn't have been my fault, I measured out those pills preciesly. (He looks up) Oh, sorry. What can I do for you today?}

{324}{}{[喃喃自语]我给威斯丁先生配了药，没有它们，他的心脏坚持不了多久的……[他抬起头]哦，抱歉。今天我能为您做些什么吗？}
{325}{}{我无意中听到你说关于心脏药片的事，我想了解一下那种药。}
{330}{}{[喃喃自语]我真不敢相信威斯丁先生死了。我精确地测过剂量，不可能错的啊…….[他抬起头]哦，抱歉。今天我能为您做些什么吗？}