{100}{}{你看到一个耳朵上面夹着一支笔的老人。}
{101}{}{那是沃尔斯，奴隶所的老板。}
{102}{}{他大概只剩下三颗牙齿了。他的衣服上都沾满了蓝色的墨水。在他的额头上有着已经褪色的奴隶贩子刺青。}
{103}{}{你想要什么？}
{104}{}{兄弟，欢迎来到沃尔斯的地方。我可以帮你吗？}
{105}{}{你开始让我感到厌烦了。}
{106}{}{这个地方是我的地方，无论新加州共和国的人跟你说什么，我这里所作的生意都是诚实的。由于新加州共和国不允许奴隶制度，因此他们不喜欢我们。}
{107}{}{你是谁啊？这里是奴隶所，我可是有执照的喔。}
{108}{}{}
{109}{}{只是想要问几个问题而已。}
{110}{}{我正在找工作。}
{111}{}{嗯？}
{112}{}{我要走了。}
{113}{}{这个地方是干什么的？}
{114}{}{没事，走错地方了。}
{115}{}{喔，兄弟们，把这个虚伪的家伙给我轰出去！}
{116}{}{操！}
{117}{}{怎么样？}
{118}{}{我正在找第13号避难所。}
{119}{}{你有一个伊甸园创造器吗？}
{120}{}{有关本镇，你可以告诉我些什么事？}
{121}{}{你这个奴役他们的混帐！我为什么不应该把你给杀了？}
{122}{}{我听说一些叫做新加州游骑兵的人。他们有找你的麻烦吗？}
{123}{}{你介意我到处看看吗？}
{124}{}{工作？嗯...我也许有一些工作吧。你有没有听说过新加州游骑兵？}
{125}{}{有。}
{126}{}{没。}
{127}{}{操你妈的，兄弟们，把这沱屎给我弄出去。}
{128}{}{来啊！}
{129}{}{第13号避难所！那个地方是一个传说而已啊。}
{130}{}{再一个问题...}
{131}{}{谢谢你什么都没有帮我。}
{132}{}{一个什么？无论那是什么，我都没有。}
{133}{}{再一个问题...}
{134}{}{谢谢你什么都没有帮我。}
{135}{}{新加州共和国-就是一大堆的官僚还有商人的地方嘛。他们不喜欢奴隶制，不过那对我也没有影响。}
{136}{}{再一个问题...}
{137}{}{谢谢，我要走了。}
{138}{}{有人跟你乱说，是不是？我与大家都没有瓜葛，尤其是游骑兵。我这里是合法的生意，因此我不会有什么麻烦的。}
{139}{}{再一个问题...}
{140}{}{随便你说吧，我要走了。}
{141}{}{是啊，我对那些游骑兵的看法也是一样。你正在找工作吗？}
{142}{}{是的。}
{143}{}{不。}
{144}{}{不行，这里不是博物馆！}
{145}{}{再一个问题...}
{146}{}{我要走了。}
{147}{}{你应该要知道有些人认为他们是一个麻烦。如果有一张地图能够指出他们岗哨的所在，我就愿意出$500购买它。}
{148}{}{当然。}
{149}{}{我不这样认为。}
{150}{}{那让我告诉你，这一些游骑兵的目标就是运用武力除掉奴隶制。}
{151}{}{他们一向都是秘密的行动，特别是在北方一带。}
{152}{}{天啊，我还要慢慢的跟你解释吗？他们专门对付奴隶制度，专门把奴隶所谓“解救”到新加州共和国里面。你有兴趣了吗？}
{153}{}{没有可是，你到底要不要那个工作？}
{154}{}{可是？}
{155}{}{那你要我做什么呢？}
{156}{}{好。当你帮我拿到地图时，我会在这里的。}
{157}{}{我到那里可以找到一张地图呢？}
{158}{}{好，不过我还有一些问题。}
{159}{}{我这就去，等会见。}
{160}{}{我他妈的怎么会知道！？如果我知道，我早就拿到了，对不对？}
{161}{}{再让我问几个问题。}
{162}{}{好吧，我会回来的。}
{163}{}{你回来了，你拿到地图了吗？}
{164}{}{拿到了。}
{165}{}{还没有。}
{166}{}{我还在等你完成你的第一个任务！}
{167}{}{喔，对，我忘了。}
{168}{}{你完成了你的工作，谢谢。}
{169}{}{在问一个问题。}
{170}{}{没问题，再见。}
{171}{}{做得好。}
{172}{}{很高兴能与你共事。}
{173}{}{不要一天到晚在这里出现，你这个笨蛋！有人会怀疑的！}
{174}{}{好，我懂了。}
{175}{}{什么？卫兵！我们有入侵者！}
{176}{}{你敢进去，我就把你的头打烂，懂吗？}

#added by killap
#{177}{}{It's late and we're closed. Come back in the morning.}
{177}{}{时间太晚了，我们关门了，明天早上再来。}

#added by killap - expansion
#{200}{}{Good work. One more thing though. You're a slaver, right? How 'bout you lend a hand and wipe out those safe houses for me. I could pay you for the job - say $1,000.}
#{201}{}{Good work. One more thing though. You look like a mean sonuvabith. How 'bout you wipe out those safe houses for me. There's a reward for it - say $1,000.}
#{202}{}{Sure.}
#{203}{}{Not interested.}
#{204}{}{Excellent. Here, let me mark these coordinates on your map thingy. Report back when you're done.}
#{205}{}{Your loss. Now you best make yourself scarce, in case those Rangers ever wise up.}
#{206}{}{Alright. Bye.}
#{207}{}{Actually, do you think you could send some of your men along with me? It'd make things go a hell of a lot faster, and further guarantee success.}

{200}{}{你是个奴隶贩子，对吧？我这里有份好工作，帮我把游骑兵那些安全屋全部清除掉，我会付你这份工作的薪水，$1,000，如何？}
{201}{}{嗨，伙计，你看上去心都烂透了，我这里有份好工作，帮我把游骑兵那些安全屋全部清除掉，我会付你这份工作的薪水，$1,000，如何？}
{202}{}{好的。}
{203}{}{不感兴趣。}
{204}{}{好，我在地图上标出这些坐标，完成后回来找我。}
{205}{}{这是你的损失，现在你最好躲起来，不然让那些游骑兵找到你，你就有大麻烦了。}
{206}{}{好吧。再见。}
{207}{}{实际上，你能派你的人和我一起去吗？我们一起上会让事情做得更好，也更容易成功。}


#{210}{}{You're back. Did you wipe out the Rangers' safe houses?}
#{211}{}{Hell yeah I did. Piece of cake.}
#{212}{}{Not yet. I'm still working on it.}

{210}{}{你回来了，事情办妥了吗？}
{211}{}{我已经搞定了，轻而易举。}
{212}{}{还没有，我还在努力。}

#{215}{}{Really? Hot damn. This is the best news I've heard yet. This will be quite a blow to the Rangers. Good work. Here's your pay. Now you best make yourself scarce, the Rangers in town are sure to be looking for you.}
#{216}{}{Let em look -- I'm not afraid. Thanks for the money.}
#{217}{}{I better get out of town then. See you later.}
#{218}{}{It seems everything I do manages to piss someone off. I'm used to it now. Bye.}

{215}{}{真的吗？这真是我听到操他妈最好的消息了。这对游骑兵一定是个不小的打击。这是你的报酬，现在你最好少露面，城里的游骑兵一定会来找你的。}
{216}{}{让他们来好了，谢谢你的钱，它们闻起来味道真不错。}
{217}{}{我想我最好离开这个城市，再见。}
{218}{}{看来我做的每件事都会惹某些人生气，我早已经习惯了，再见。}

#{220}{}{Hell no. I'm not rounding up any guys for this. If you feel you can't handle it, then leave.}
#{221}{}{I never said I couldn't handle it. I just thought your men would like to join in on the fun. But whatever, I'll handle it on my own, no problem. I'll report back when I'm done.}
#{222}{}{Fine, you can count me out, asshole. I'm not gonna be your dog. Bye.}
#{223}{}{You calling me chicken? No one calls me that and lives!}

{220}{}{没有任何人，我不会为这件事给你提供人手，如果你觉得自己应付不了，那就离开。}
{221}{}{我从来没有说过我应付不了，我自己来处理这件事。我做完后会回来报告的，没问题。}
{222}{}{好的，你不用算我那一份了。混球，我不会成为你的狗的，再见。}
{223}{}{你叫我混球？没有人这么叫我之后能活下来的。}



#{225}{}{Well, alright. I think I can round up some boys to aid you in this. They'll meet you on the way. You ready to start now?}
#{226}{}{Give me some time. I'll be back when I am ready.}
#{227}{}{I was born ready. Let's rumble.}
#{228}{}{I'm ready. Let's go.}
#{229}{}{I think I'll pass on all this. I've lost interest. Bye.}

{225}{}{嗯，好的。我想我可以找几个男孩来帮你，他们会在路上接应你的，那你现在准备好了吗？}
{226}{}{给我一些时间，我准备好了就回来。}
{227}{}{我生下来就准备好了，让我们赶紧去轰上他妈的几炮。}
{228}{}{准备好了，我们走吧。}
{229}{}{我想我改变主意了，我对这件事已经失去了兴趣。再见。}



#{230}{}{You ready for the raid, or are you here to waste more of my time?}
#{231}{}{I need more time.}
#{232}{}{I'm ready. Let's go.}

{230}{}{你准备好办事了没，还是你要在这里浪费我更多的时间？}
{231}{}{我还需要些时间。}
{232}{}{我已经准备好了，走吧。}



#{240}{}{You wipe out the Rangers' safe houses. This deals quite a blow to the Rangers in their fight against slavery.}
{240}{}{你摧毁了游骑兵的安全屋。这对游骑兵们反对奴隶制的斗争是一个不小的打击。}


#{241}{}{I'm looking to buy some slaves.}
{241}{}{我想买一些牲口，我是指奴隶。}


#{250}{}{Well that's fuckin nice. We don't sell here. Metzger up north in the Den can help you with that.}
#{251}{}{I've been there and his stock wasn't up to my standards.}
#{252}{}{Seeing how I killed Metzger, I don't know how that's going to be useful to me. I think I'll kill you instead.}

{250}{}{嗯，那真是太好了。但我们在这里不方便卖，我们的老大麦塔则在丹恩的东边，他可以帮你。}
{251}{}{我去过那里，他那边的货远远没有达到我要求的标准。}
{252}{}{麦塔则？他已经被我做掉了，我不知道能去丹恩什么地方找奴隶，或者我应该把你也做掉。}

#{260}{}{Well aren't you a picky fuck. You do realize that his stock isn't limited to just the Den, right? He's got his own holding pen where slaves are dropped off.}
#{261}{}{Interesting. How would I get to this other location?}

{260}{}{嗯，看来你是个操蛋的挑剔货。你得要知道一件事，老大的生意不仅仅局限于丹恩，他还有其它的库存，奴隶们只是在这边做个中转。}
{261}{}{这真有趣，我怎样才能到达另一个地点？}

#{270}{}{What, do you think you can get whatever the fuck you want for free? $1,000. Take it or leave it.}
#{271}{}{What, do you think you can get whatever the fuck you want for free? Plus, you ooze virtuousness. I don't like that. $2,000. Take it or leave it.}
#{272}{}{Alright, here.}
#{273}{}{Nevermind.}
#{274}{}{I'll do whatever I want. And I think I'll kill you now.}
#{275}{}{I'll come back when I have more money.}

{270}{}{这里可没有能白嫖的婊子，你要的东西可不能免费，$1,000，要么接受，要么放弃。}
{271}{}{这里可没有能白嫖的婊子，你要的东西可不能免费。另外你看起来实在不怎么坏，$2,000，要么接受，要么放弃。}
{272}{}{好，钱在这里。}
{273}{}{无所谓。}
{274}{}{我想做什么就做什么，我想我现在就应该杀了你。}
{275}{}{我有更多的钱再回来。}


#{280}{}{[He points on your map the location of the slaver camp.] It's around there. Now what else are you going to waste my time with?}
#{281}{}{I've got what I need. Bye.}

{280}{}{[他在你的地图上指出奴隶营区的位置。] 营区就在那儿，现在你还打算用什么来浪费我的时间呢？}
{281}{}{这就是我需要的东西，再见。}

