{100}{}{你看到一个耳朵上面放着一支笔的老人。}
{101}{}{那是沃尔斯，奴隶所的老板。}
{102}{}{他大概止剩下三颗牙齿了。他的衣服上都沾满了蓝色的墨水。在他的额头上有着已褪色的奴隶贩子刺青。}
{103}{}{你要什么？}
{104}{}{兄弟，欢迎来到沃尔斯的地方。我可以帮你吗？}
{105}{}{你开始让我感到厌烦了。}
{106}{}{这个地方是我的地方，无论新加州共和国的人跟你说什么，我这里所作的生意都是诚实的。由于新加州共和国不准奴隶制度，因此他们不喜欢我们。}
{107}{}{你是谁啊？这里是奴隶所，我可是有执照的喔。}
{108}{}{}
{109}{}{只是想要问几个问题而已。}
{110}{}{我正在找工作。}
{111}{}{嗯？}
{112}{}{我要走了。}
{113}{}{这个地方是干什么的？}
{114}{}{没事，走错地方了。}
{115}{}{喔，兄弟们，把这虚伪的家伙给我轰出去！}
{116}{}{操！}
{117}{}{怎样？}
{118}{}{我正在找第１３号避难所。}
{119}{}{你有一个伊甸园创造器吗？}
{120}{}{有关本镇，你可以告诉我些什么事？}
{121}{}{你这个奴役他们的混帐！我为什么不应该把你给杀了？}
{122}{}{我听说一些叫做新加州巡警的人。他们有找你的麻烦吗？}
{123}{}{你介意我到处看看吗？}
{124}{}{工作？嗯．．我也许有一些工作吧。你有没有听过新加州巡警？}
{125}{}{有。}
{126}{}{没。}
{127}{}{干你娘。兄弟们，把这团屎给我弄出去。}
{128}{}{来啊！}
{129}{}{第１３号避难所！那个地方是一个传说而已啊。}
{130}{}{再一个问题．．}
{131}{}{谢谢你什么都没有帮我。}
{132}{}{一个什么？无论那是什么，我都没有。}
{133}{}{再一个问题．．}
{134}{}{谢谢你什么都没有帮我。}
{135}{}{新加州共和国－就是一大堆的官辽还有商人的地方嘛。他们不喜欢奴隶制，不过那对我也没有影响。}
{136}{}{再一个问题．．}
{137}{}{谢谢，我要走了。}
{138}{}{有人跟你乱说，是不是？我与大家都没有瓜葛，尤其是巡警。我这里是合法的生意，因此我不会有什么麻烦的。}
{139}{}{再一个问题．．}
{140}{}{随便你说吧，我要走了。}
{141}{}{是啊，我对那些巡警的看法也是一样。你正在找工作吗？}
{142}{}{是的。}
{143}{}{不。}
{144}{}{不行，这里不是博物馆！}
{145}{}{再一个问题．．}
{146}{}{我要走了。}
{147}{}{你应该要知道有些人认为他们是一个麻烦。如果我们有一张地图能够指出他们岗哨的所在，我就愿意出$500购买它。}
{148}{}{当然。}
{149}{}{我不这样认为。}
{150}{}{那让我告诉你。这一些巡警的目标就是运用武力除掉奴隶制。}
{151}{}{他们一向都是秘密的行动，特别是在北方一带。}
{152}{}{天啊，我还要慢慢的跟你解释吗？他们专门对付奴隶制度，专门把所有的奴隶都护送到新加州共和国里面。你有兴趣了吗？}
{153}{}{没有可是，你到底要不要那个工作？}
{154}{}{可是？}
{155}{}{那你要我做什么呢？}
{156}{}{好。当你帮我拿到地图时，我会在这里的。}
{157}{}{我到那里可以找到一张地图呢？}
{158}{}{好，不过我还有一些问题。}
{159}{}{我这就去，等会见。}
{160}{}{我他妈的怎会知道！？如果我知道，我早就拿到了，对不对？}
{161}{}{再让我问几个问题。}
{162}{}{好吧，我会回来的。}
{163}{}{你回来了，你拿到地图了吗？}
{164}{}{拿到了。}
{165}{}{还没有。}
{166}{}{我还在等你完成你的第一个任务！}
{167}{}{喔，对，我忘了。}
{168}{}{你完成了你的工作，谢谢。}
{169}{}{在问一个问题。}
{170}{}{没问题，再见。}
{171}{}{做得好。}
{172}{}{很高兴能与你共事。}
{173}{}{不要一天到晚在这里出现，你这笨蛋！有人会感到可疑的！}
{174}{}{好，我懂了。}
{175}{}{什么？卫兵！我们有入侵者！}
{176}{}{你敢进去，我就把你的头打烂，懂吗？}

#added by killap
{177}{}{It's late and we're closed. Come back in the morning.}

#added by killap - expansion
{200}{}{Good work. One more thing though. You're a slaver, right? How 'bout you lend a hand and wipe out those safe houses for me. I could pay you for the job - say $1000.}
{201}{}{Good work. One more thing though. You look like a mean sonuvabith. How 'bout you wipe out those safe houses for me. There's a reward for it - say $1000.}
{202}{}{Sure.}
{203}{}{Not interested.}
{204}{}{Excellent. Here, let me mark these coordinates on your map thingy. Report back when you're done.}
{205}{}{Your loss. Now you best make yourself scarce, in case those Rangers ever wise up.}
{206}{}{Alright. Bye.}
{207}{}{Actually, do you think you could send some of your men along with me? It'd make things go a hell of a lot faster, and further guarantee success.}

{210}{}{You're back. Did you wipe out the Rangers' safe houses?}
{211}{}{Hell yeah I did. Piece of cake.}
{212}{}{Not yet. I'm still working on it.}

{215}{}{Really? Hot damn. This is the best news I've heard yet. This will be quite a blow to the Rangers. Good work. Here's your pay. Now you best make yourself scarce, the Rangers in town are sure to be looking for you.}
{216}{}{Let em look -- I'm not afraid. Thanks for the money.}
{217}{}{I better get out of town then. See you later.}
{218}{}{It seems everything I do manages to piss someone off. I'm used to it now. Bye.}

{220}{}{Hell no. I'm not rounding up any guys for this. If you feel you can't handle it, then leave.}
{221}{}{I never said I couldn't handle it. I just thought your men would like to join in on the fun. But whatever, I'll handle it on my own, no problem. I'll report back when I'm done.}
{222}{}{Fine, you can count me out, asshole. I'm not gonna be your dog. Bye.}
{223}{}{You calling me chicken? No one calls me that and lives!}

{225}{}{Well, alright. I think I can round up some boys to aid you in this. They'll meet you on the way. You ready to start now?}
{226}{}{Give me some time. I'll be back when I am ready.}
{227}{}{I was born ready. Let's rumble.}
{228}{}{I'm ready. Let's go.}
{229}{}{I think I'll pass on all this. I've lost interest. Bye.}

{230}{}{You ready for the raid, or are you here to waste more of my time?}
{231}{}{I need more time.}
{232}{}{I'm ready. Let's go.}

{240}{}{You wipe out the Rangers' safe houses. This deals quite a blow to the Rangers in their fight against slavery.}

{241}{}{I'm looking to buy some slaves.}

{250}{}{Well that's fuckin nice. We don't sell here. Metzger up north in the Den can help you with that.}
{251}{}{I've been there and his stock wasn't up to my standards.}
{252}{}{Seeing how I killed Metzger, I don't know how that's going to be useful to me. I think I'll kill you instead.}

{260}{}{Well aren't you a picky fuck. You do realize that his stock isn't limited to just the Den, right? He's got his own holding pen where slaves are dropped off.}
{261}{}{Interesting. How would I get to this other location?}

{270}{}{What, do you think you can get whatever the fuck you want for free? $1000. Take it or leave it.}
{271}{}{What, do you think you can get whatever the fuck you want for free? Plus, you ooze virtuousness. I don't like that. $2000. Take it or leave it.}
{272}{}{Alright, here.}
{273}{}{Nevermind.}
{274}{}{I'll do whatever I want. And I think I'll kill you now.}
{275}{}{I'll come back when I have more money.}

{280}{}{[He points on your map the location of the slaver camp.] It's around there. Now what else are you going to waste my time with?}
{281}{}{I've got what I need. Bye.}
