#{100}{}{You see a motor boat.}

#{200}{}{You sneak onto the motor boat when the guard isn't looking and hide yourself from view. At around midnight
 you hear voices nearby and you feel the motor boat begin to move.}
#{201}{}{After telling your party members to stay put, you sneak onto the motor boat when the guard isn't looking and hide
 yourself from view. At around midnight you hear voices nearby and you feel the motor boat begin to move.}

#{210}{}{Maybe I should disarm this thing before I go.}
#{220}{}{It's too risky to use that again.}
#{221}{}{I wouldn't know where to go.}


{100}{}{你看到一个汽艇。}

{200}{}{趁警卫不注意的时候，你偷偷地溜到摩托艇上，把自己隐藏起来。午夜时分，你听到附近有声音，你感到摩托艇开始移动。}
{201}{}{在告诉你的小队成员呆在原地后，趁警卫不注意的时候，你偷偷地溜到摩托艇上，把自己隐藏起来。午夜时分，你听到附近有声音，你感到摩托艇开始移动……}

{210}{}{也许在我走之前，我应该把这东西放下。}
{220}{}{太危险了，不能在这里用它。}
{221}{}{我不知道该去哪里。}