#{100}{}{After about a quarter of an hour, the rickety motorboat arrives at a rusty conning tower sticking out of the
 water, off the coast of San Francisco. The shallow waters are murky, but you can see the outline of the massive submarine quite clearly.}
#{101}{}{The Shi tech crew quickly disembarks and disappears into the sub.}
#{102}{}{As you get away from the submarine, a massive explosion rips through the air, sending gallons of water in all
 directions. You look back and notice that where a conning tower once stood, there is absolutely nothing now.}

 
{100}{}{在大约一刻钟后，那艘摇摇晃晃的汽艇来到旧金山附近的一个浅水区，你看到你周围的水都是铁锈的颜色。当船停下来的时候，你看到眼前有一个潜艇指挥塔，你可以清楚地看到下面那艘巨大的潜艇的轮廓。}
{101}{}{始族的技术团队打开舱盖，迅速地进入了潜艇内部。}
{102}{}{当你从潜艇上离开后不久，你听到了巨大的爆炸声。顺着爆炸的方向你回头一看，曾经是指挥塔的地方现在什么东西都没有了。}
