#{100}{}{You see a warrior.}
#{101}{}{You see Serin.}
#{102}{}{He looks badly injured and has a broken leg.}
#{103}{}{You see Serin. He looks badly injured and has a broken leg.}
#{104}{}{You see Serin. His leg is bandaged and he is hobbling.}
#{105}{}{You see Serin. He looks better and he is in a deep sleep.}
#{106}{}{You see Serin. He looks like he has recovered nicely.}
{100}{}{你看到一个战士。}
{101}{}{你看到塞林。}
{102}{}{他看起来受了重伤，腿也断了。}
{103}{}{你看到塞林。他看起来受的伤不轻，腿也断了。}
{104}{}{你看到塞林。他的腿上缠着绷带，正在蹒跚学步。}
{105}{}{你看到塞林。他看起来好多了，而且睡得很沉。}
{106}{}{你看到塞林。他看起来恢复得很好。}


#{200}{}{*ugh* Die fiend！！ You won't be ta-}
#{201}{}{Calm down. You're safe now. The gecko is dead.}
{200}{}{*啊*滚开！恶魔！ ！}
{201}{}{冷静下来，你现在是安全的，蜥蜴已经死了。}


#{202}{}{What！？ Oh， praise the spirits， fren. I feared I be done for.}
#{203}{}{What happened here?}
#{204}{}{Jerem and I be going out for weekly hunt. Took cave passage to field where many geckos roam. Hunt went bad. Had to run. Too many geckos with spirits of fury. We entered cave. Started yelling for help. [He pauses for a moment and winces in pain as he tries to rub his leg.]}
#{205}{}{Please go on.}
#{206}{}{Passage was already on brink of doom. Water seeping in from stream overhead. A deadly pass， but it be a great shortcut to fields. Not no more. See， we be yelling like fools and the ceiling come crashing down on us.}
{202}{}{什么！？噢，赞美神灵。我以为我死定了！。}
{203}{}{发生了什么？}
{204}{}{杰米和我去日常的狩猎。穿过这个洞穴后我们来到一小片原野，却没想到有一大群蜥蜴在那里，这群蜥蜴数量多到不是可以“打猎”的数量，这完全出乎了我们的意料。在发现了我们之后，这群蜥蜴开始追着我们不放，我们拼了命一样想跑回营地里[疼痛使他停住他揉了揉受伤的腿]}
{205}{}{[继续]}
{206}{}{但不幸的是，这个山洞已经快要崩塌了，在我们跑过的时候，水从头顶的岩石中渗出，岩石泥土不停砸到我们头上。}




#{207}{}{[Continue]}
#{208}{}{Poor Jerem. I saw big rock crush him like bug. The big rocks missed me， but the Gecko's bite didn't. Just when I thinking I be safe， a gecko come from nowhere and take big bite outta leg. Took me right to the ground. Had no spear， thought the Gecko be dining on me for sure. But the spirits had other plans. Brought a final big 'o rock down on the geckos head. Crushed it flat. But crushed my leg， too.}
#{209}{}{[Continue]}
#{210}{}{So I be stuck on ground， without spear. Suddenly， I be hearing something come at me from the dark. It got closer， and I saw it be one big angry gecko. The falling rocks only be making it more pissed. That's when you came in， fren. Truly， I be in your debt.} 
#{211}{}{Wow， that's quite the story. It seems you're very lucky to be alive. How's your leg?}
#{212}{}{Not good， fren. It seems rock be stronger than my leg bone. I doubt I be getting up and walking out soon.}
#{213}{}{Don't worry， I'm a skilled doctor. Let me have a look at your leg and I'll see what I can do.}
#{214}{}{Don't worry， I shouldn't have a problem carrying you out of here. Then we can have the shaman take a look at your leg.}
#{215}{}{We should probably get a professional to come here and look at it. I'll quickly go try to find some help. The cave seems to be empty now， so you should be safe here until I return.}
#{216}{}{Hmm... I don't think I'm quite strong enough carry you out of here， but I bet Sulik could do it. [to Sulik] Let's carry this guy out of here.}
#{217}{}{Hmm... I don't think I'm quite strong enough carry you out of here， but I bet Marcus could do it. [to Marcus] Let's carry this guy out of here.}
#{218}{}{[You examine the warrior's leg. It's badly ripped up and the bone is showing in some parts. You skillfully snap the bone back in place， stop the bleeding， splint the leg， and set to work on healing it.]}
#{219}{}{[After about 15 minutes of agonizing work， the leg is in much better shape. It looks as if this man will be able to walk again.]}
#{220}{}{Alright， that should about do it. You'll need a couple days of rest for it to fully heal. Don't put too much pressure on it during this time and you should be fine.}
#{221}{}{Holy spirits posses you， fren！ I thank you. Now I be hobbling my way to the shaman. Get some good herb to ease the pain. Be seeing you back at the village， fren.}
#{222}{}{[Done]}
{207}{}{[继续]}
{208}{}{杰米不走运，我看见一块大石头像虫子一样把他压扁了。就在我认为自己安全的时候，不知道在那里冒出来一只金蜥蜴，咬住了我的腿，要把我拖到地上。我手上没有矛，我心里想这次死定了，但谢天谢地，一块大石头砸在了那只蜥蜴的头上。唉，但我的脚也没那么幸运。同样被落下的岩石压住了。}
{209}{}{[继续]}
{210}{}{所以我就被那块石头压在地上了，手边也没有武器。突然，我听到有什么东西从黑暗中传来。它靠近了，我看到它是一只愤怒的蜥蜴，刚刚掉落的岩石让它更生气了。就在我认为全完了的时候，你来到了。} 
{211}{}{哇，这是一个很好的故事。看起来你还活着很幸运。你的腿如何？}
{212}{}{很不好，朋友。看起来石头比我的腿骨结实得多了。我怀疑我是不是这辈子都要在床上了。}
{213}{}{别担心，我是个熟练的医生。让我看看你的腿，看看能做什么}
{214}{}{别担心，我会把你带出去的。然后我们可以让萨满看看你的腿。}
{215}{}{我们应该找个专业人士来这里看看。我马上去找帮手，这个洞现在看起来很安全，没有落石，也没有蜥蜴，等我回来。}
{216}{}{嗯... 我把你带出去有点困难。不过史力克应该没问题。 [叫史力克] 让我们把这家伙带出去吧。}
{217}{}{嗯... 我把你带出去有点困难。不过马可世应该没问题。[叫马可世] 让我们把这家伙带出去吧。}
{218}{}{[你检查战士的腿。它严重变形，某些部位骨头都露出来]你熟练地把骨头重新放回原位，止血，用夹板固定住腿，然后开始治疗。}
{219}{}{[15分钟痛苦的工作后，腿的形状看起来好多了]看来伤愈之后走路应该是没问题的。}
{220}{}{看起来应该没有问题了。你需要休息一段时间才能完全康复，放心，你应该没事的。}
{221}{}{神圣的灵魂祝福您！我感谢你。我会回到村子让萨满找些好的草药来缓解疼痛，在村子里见。}
{222}{}{[完成]}



#{300}{}{I thank you， fren. Be seeing you back at the village.}
{300}{}{我谢谢你，朋友。真高兴在村子里见到你。}
#{400}{}{Thanks much， fren. Truly， you are blessed by the spirits.}
{400}{}{谢谢，朋友，神圣的灵魂祝福您。}

{500}{}{zzzZZzzz...}
{501}{}{...zzZZZZzz...zzz...}

{600}{}{你治愈了塞林的腿。}

# PC has beaten the Enclave
#{1000}{}{很高兴看到你，英雄。}
#{1001}{}{I never forget what you done for me， hero.}
{1000}{}{我永远不会忘记你为我所做的一切，英雄。}
#{1001}{}{I never forget what you done for me， hero.}
{1001}{}{看来我帮不上些什么，我最好走了。}
#{700}{}{He needs more help than I can offer. I better get going.}

{700}{}{他需要的帮助比我所能提供的要多，我最好走了。}