#{100}{}{You see an old man with a crazy gleam in his eye.}
#{101}{}{You see Old Joe, the local idiot savant.}
#{102}{}{Hello. Haven't seen you in a while.}
#{103}{}{Do I know you?}
#{104}{}{Ah, yeah. It's been a while. What have you been doing?}
#{105}{}{Well, it has been a while. What have you been up to?}

{100}{}{你看到一个老人，他的眼光闪闪发亮。}
{101}{}{你看到老乔，本地的白痴学者。}
{102}{}{你好，很久不见了。}
{103}{}{我认识你吗？}
{104}{}{啊，是的。这段时间，你在做什么？}
{105}{}{嗯，已经好长一段时间了，你最近在忙些什么？}

#{106}{}{This and that. Where do you know me from?}
#{107}{}{Look, old man, I don't know who the hell you are.}
#{108}{}{Sure has. Well, I've been around；finally ended up here in this god-forsaken place. Not like the good old days. No sir.}
#{109}{}{Yeah, the good old days. Remember that time we...}
#{110}{}{It hasn't been the same lately, that's for sure. Now... what did we do together?}

{106}{}{这个...这个...你从哪儿认识我的？}
{107}{}{听着，老头，我不知道你到底是谁。}
{108}{}{的确是的。我走遍各方，最后停留在这个凄凉的地方，一点也不像以前美好的时光。}
{109}{}{是的，过去的好时光。记得那时候我们...}
{110}{}{和以前不一样了，这是肯定的。但我们一起做了什么？}

#{111}{}{Don't remember me, do you? Well, you do seem to be a bit young.}
#{112}{}{What are you trying to tell me?}
#{113}{}{You look so familiar, though. Ah, must be my old eyes. Well, good day to you.}
#{114}{}{Uh, yeah... goodbye.}
#{115}{}{Yeah, we sure gave the Master hell, didn't we? Shit fell apart after you left, though. Had to move around and change my name. Where'd you end up?}

{111}{}{你不记得我了，是吗？嗯，你看起来确实有点年轻。}
{112}{}{你想告诉我什么？}
{113}{}{你看起来很面熟，一定是我的老眼睛骗了我。好吧，祝你好运。}
{114}{}{嗯，是的...再见。}
{115}{}{是的，我们把教主踢进了地狱，那真是一记好球，对吧？那之后你离开了，而我到处乱逛还改了名字。你去哪了？}


#{116}{}{I've been living up in a small village.}
#{117}{}{Well, you better be careful around here. Things ain't as clear as they once were. You best watch your back.}
#{118}{}{Okay, thanks.}
#{119}{}{Yeah, I looked for your Vault for a while, but never found it. So you got any good stories for your old friend Ian?}
#{120}{}{Ian?}
#{121}{}{Yeah, Ian. Don't you remember me? It's been a bunch of years. You'd think someone wouldn't forget his best buddy. Well... except for the shooting in the back thing. Sorry about that again.}

{116}{}{我一直住在一个小村庄。}
{117}{}{好吧，你在这附近要小心一点，这里不像以前那么安全了。}
{118}{}{好，谢谢。}
{119}{}{我曾经去找你过的避难所，但是都找不到。有什么有趣的故事可以讲给你的老朋友伊恩听吗？}
{120}{}{伊恩？}
{121}{}{对啊，伊恩。你不记得我了？ 有很多年了吧。你觉得有人会忘记他最好的伙伴吗？嗯... 除非后面出了什么事。}

#{122}{}{I am sorry, but you must think I am the Vault Dweller. My village was founded by the one who came from the Vault.}
#{123}{}{Well, that makes a bit more sense. Well, it's good to hear my friend did well. Well, old Ian's got some advice for you. You be careful out there. This place ain't as peachy as it seems. }
#{124}{}{What's going on here?}
#{125}{}{Well, the Vault Citizens think very highly of their bloodline and don't care much for people like me and you. You take this. It'll protect you if things get a little out of control. You probably shouldn't be seen talking with this crazy old man. Best get on your way.}
#{126}{}{Thanks for your help. Bye.}
#{127}{}{Let an old man rest.}
#{128}{}{So familiar...}
#{129}{}{Leave me be now.}
#{130}{}{You better get going.}
#{131}{}{They'll get suspicious if we talk anymore.}
#{132}{}{Go on, get. Make my old friend proud.}


{122}{}{对不起，你一定是把我误认成为避难所住民了。我的村子是由他创立的，我是他的后代。}
{123}{}{噢，很高兴听到我的朋友情况不错。好吧。老伊恩给你一些忠告，这里并不是表面上看的那么漂亮，其实这里的治安不太好，小心一点。}
{124}{}{这里怎么了？}
{125}{}{好吧，地下掩体市的公民认为他们血统很高贵，所以看不起像你我这样的人。拿着这把枪吧，它会保护你的。你可能不应该和我这样的疯老头子说话，保重。}
{126}{}{谢谢，保重。}
{127}{}{让老人休息一下。}
{128}{}{真眼熟...}
{129}{}{不要理我了。}
{130}{}{你最好快走吧。}
{131}{}{如果我们继续谈话的话，他们会怀疑我们的。}
{132}{}{去吧，让我为老朋友感到骄傲吧！}


#{133}{}{Thanks. One more thing though. I'm trying to help this little village that's north-east of here. A guy there named Connar told me to seek you out and speak with you.}
#{134}{}{Connar, huh? He's a good guy. I've been keeping my eye on things for him. So what exactly does Connar want, now?}
#{135}{}{He's trying to get his hands on some weapons. He thinks if they had some firepower, they'd be able to keep the Vault City patrols at bay.}
#{136}{}{Ah, so that's his new plan, eh? Well, head over to Happy Harry's general store. Tell Harry Connar sent you, and he should be able to fix you up -- I believe he's got some guns stashed away for just such an occasion. But if you ask me, I'm not sure this is the best way to handle things.}
#{137}{}{I'm off to speak with Harry then. Take care ol' friend.}
#{138}{}{Why, what do you mean?}
#{139}{}{Connar and his people have that strong fighting spirit, but it won't be enough in this case. Vault City have nearly unlimited resources, and eventually, they'll win out. Sometimes, it's best to talk things out and try to reason with people. That's a lesson I learned from my old friend, the Vault Dweller. Senior Council Member McClure has shown to be a reasonable man. Perhaps some agreement can be made with him?}

{133}{}{谢谢你，有一件事。在东北的小村庄需要帮助，有个叫康尔的人让我来找你。}
{134}{}{康尔？他是一个好人。我一直在关注他的事情。那么康尔到底想要什么呢？}
{135}{}{他正在设法弄到一些武器，他认为如果他和他的人能弄到一些武器，就能让掩体市巡逻队吃点苦头。}
{136}{}{啊，那是他的新计划吗？好吧，去快乐哈利杂货店吧。告诉哈利是康尔让你来的，他应该能帮你解决。但我不认为这是处理问题的最好方法。}
{137}{}{我现在去找哈利，保重，老朋友。}
{138}{}{为什么，你是什么意思？}
{139}{}{好吧，康尔和他的人民也许能抵抗一段时间，但地下掩体市和外面是通商的，他们拥有无限的资源，康尔是不可能赢的。有时候，最好是大家坐下来，把事情说清楚，这是我从老朋友，避难所住民那里学到的。掩体市的议会议员麦卡路是一个聪明的人，也许你更应该找他协商一下这件事。}




#{140}{}{Hmm...I may have to consider this. Thanks for everything, bye.}
#{141}{}{Perhaps I'll go speak with him then. However, I was curious about the mole rats that are guarding the village.}
#{142}{}{Yeah, what about them?}
#{143}{}{Any idea where they're from or who's controlling them?}
#{144}{}{That, I'm not sure about. A bunch of ghouls came by with them. They were carrying strange amulets and talking about some "Renewal". That's pretty much all I know. You might wanna check out Gecko though. That place is bustling with ghouls. Speaking of big rats, did I ever tell you about the time the Vault Dweller and I went to Vault 15?}
#{145}{}{No, but I'm well versed in the tale, as it's become a sacred legend in my tribe. Anyway, maybe I'll go see what I can find in Gecko. Take care, Ian.}
#{146}{}{Uh, thanks for the tip. I think you are the man I need to see though. Connar sent me to ask you for some things.}
#{147}{}{Wait a minute! Connar told me you have some information.}
#{148}{}{No, but I'm well versed in the tale, as it's become a sacred legend in my tribe. Anyway, maybe I'll go see what I can find in Gecko. Take care.}

{140}{}{嗯...我会考虑这个的。谢谢。再见。}
{141}{}{我会和他谈谈的。但我对地鼠保护村庄这件事很好奇。}
{142}{}{是的，它们怎么了？}
{143}{}{比如它们从哪来的还有谁控制着它们？}
{144}{}{我也不是很清楚，一些僵尸和它们一起来的。他们带着护身符，还说着“重生”什么，我就知道这些了。你应该去蜥蜴城看看，那里到处是僵尸，我听说那里的废车场里总有些声音，也许你能在那找到一些答案。我有没有和你提过我和避难所居民找到了15号避难所？}
{145}{}{没有，但是我很熟悉这个故事，因为它已经成为我部落里的一个神圣的传说。或者我会去蜥蜴城看看，保重，伊恩。}
{146}{}{呃，谢谢你的提示。我想你是我需要见的人，康尔让我问你一些事情。}
{147}{}{等等！康尔告诉我你有一些信息。}
{148}{}{没有，但是我很熟悉这个故事，因为它已经成为我部落里的一个神圣的传说。或者我会去蜥蜴城看看，保重。}



#{150}{}{He was interested in getting some weaponry to fight off the Vault City patrols, but I convinced him that there's a better solution.}
#{151}{}{Ah, so that's his new plan, eh? Yeah, Connar's a good man, but he doesn't always think things all the way through. Sometimes, it's best to talk things out and try to reason with people. That's a lesson I learned from my old friend, the Vault Dweller.}

{150}{}{他很想弄点武器来打败地下掩体市的巡逻队。但我认为这不是个好的解决办法。}
{151}{}{哈，所以这就是新计划？没错，康尔的确是一个好人，但他从不全面的分析事情。有时候，最好是大家坐下来，把事情说清楚，这是我从老朋友，避难所住民那里学到的。}


#{152}{}{Well, any idea who on the council I might be able to talk to?}
#{153}{}{I think Senior Council Member McClure might be the man to talk to. What do you think?}
#{154}{}{Senior Council Member McClure is a smart man here in Vault City. Perhaps some agreement can be made with him?}

{152}{}{那么，我应该和议会里的哪个人谈谈？}
{153}{}{我认为是议会议员麦卡路。你认为呢？}
{154}{}{议会议员麦卡路是掩体市的一个聪明人。也许能和他协商一下这件事。}


#{155}{}{Alright. I'll try to speak with him. Bye.}
#{156}{}{Perhaps I'll go speak with him then. However, I was curious about the mole rats that are guarding the village.}

{155}{}{好了，我试着和他谈谈。再见。}
{156}{}{我会考虑和他谈谈。然而，我对看守村庄的地鼠很好奇。}



#{157}{}{He'd be your best bet. He is the only one on the council that has a reasonable soul left.}
#{158}{}{Alright. I'll try to speak with him. Bye.}
#{159}{}{I will go speak with him then. I was curious about the molerats that are guarding the village though.}

{157}{}{他将是这件事最好的解决办法，他是理事会中唯一一个有理智的人...}
{158}{}{好，我试着和他谈谈。再见。}
{159}{}{我会和他谈谈，我对地鼠保护村庄这件事很好奇。}


#added by killap - new in RP 1.3
#{200}{}{Hey, if you really are the same Ian that journeyed with my ancestor, then I've got a question for you.}
#{201}{}{Alright, let's hear it.}
#{202}{}{How the hell are you still alive? You must be over a hundred years old. Not to mention the Vault Dweller's memoirs, which say you were burnt to death in Necropolis by a Super Mutant with a flame thrower.}

{200}{}{嘿，如果你真的是和我的祖先一起旅行的那个伊恩，那么我有个问题要问你。}
{201}{}{你想听什么}
{202}{}{你怎么还活着？你一定有一百多岁了，而且根据部落里的传说，你应该在大墓地被一个超级变种人用“喷火大炮”烧死了。}


#{203}{}{[He barks gruff laughter for awhile；finally, he settles down and wipes a couple tears from his eyes.] Oh, that's rich. Burnt to death by a flame thrower, ha! You see, I told the Vault Dweller to make up some story about how I died, 'cause I didn't want any of our old enemies trying to hunt me down -- that's why I changed my name. I told him to have me going down in a blaze of glory, and it looks like he took that literally. Ha, that's classic.}
#{204}{}{Heh, I guess that solves that. I was curious about the molerats that are guarding the village though.}
#{205}{}{That still doesn't explain how you're still alive and well after all these years.}

{203}{}{[他笑了好一阵，最后他平静下来，擦了擦眼泪]哈！对，被“喷火大炮”烧死了。事实上在我们分别的时候，我让避难所住民编造一些关于我死掉的消息，因为我不想让我们的老敌人来追捕我。这就是为什么我改了名字。我告诉他，故事里一定要让我在火焰中英勇地倒下。看起来他真的是这样做了，哈哈哈。}
{204}{}{原来如此，不过，我还是很好奇那些守卫着村子的地鼠。}
{205}{}{但这个仍然不能解释你是怎么活了这么多年的啊。}

#{206}{}{Hey, I'm just as confused as you are. Who knows? Maybe it's got something to do with all that radiation I was exposed to back in the old days. Hell, when we went to the Glow, I remember the Vault Dweller was popping Rad-X like candy, but did he offer any to ol' Ian? Of course not. I think he was still upset over a little friendly fire mishap. Heh heh. [Sigh.] Those were some good times.}
#{207}{}{I'm sure they were. Thanks for the story Joe, er, Ian. Take care.}
#{208}{}{I'm sure they were. Thanks for the story Joe, er, Ian. I was curious about the molerats that are guarding the village though.}

{206}{}{嘿，我和你一样糊涂，天知道是为什么。也许这和我以前接触到的辐射有关。见鬼，当我们走到闪光之地的时候，我记得那个避难所住民像吃糖果那样磕抗辐射药，但是他给了伊恩吗？没有。我还以为他是不是因为什么事生我气了，呵呵呵。[叹气，那是一些美好的时光]}
{207}{}{谢谢你的故事，乔，呃，伊恩，保重。}
{208}{}{谢谢你的故事，乔，呃，伊恩。不过，我很好奇那些守卫着村子的地鼠。}


#{300}{}{Wait a minute! Are you the contact in Vault City that Connar was talking about?}
{300}{}{等等！你是康尔说的地下掩体市的联系人吗？}
