#{100}{}{You see the caravan master.}
#{101}{}{You see Mr. Baron, the master of this caravan.}

{100}{}{你看到商队的主人。}
{101}{}{你见到巴伦先生，这个商队的主人。}

#{200}{}{Hello Traveler, name's Robert Baron, master of this here caravan. Are you looking to make a trade?}
#{201}{}{Sure. Let's see what you've got.}
#{202}{}{Actually, I wanted to speak with you on behalf of a nearby village.}
#{203}{}{Nope. I'll be on my way now.}
#{204}{}{Robert Baron, huh? Ever think about going by Bobby Baron? That's got a nice bounce to it, don't you think?}

{200}{}{你好，旅行者，我的名字是罗伯特.巴伦，是这个商队的主人，你想做交易吗？}
{201}{}{确定。让我们看看你有什么。}
{202}{}{实际上，我想代表附近的村庄和你谈一谈。}
{203}{}{不，我有其它事情要做。}
{204}{}{罗伯特.巴伦，恩？你有没有想过改叫鲍比·巴伦？这是一个很好的名字，你不觉得吗？}



#{210}{}{I think your mom might've bounced you on your head a couple times. Now, do you want to trade, or not? I'm a busy man.}
{210}{}{我想你出生的时候头撞到地板上可能不止一次。现在，你想不想交易？我很忙。}


#{220}{}{Alright. Anything else?}
#{221}{}{Yes actually, I wanted to speak with you on behalf of a nearby village.}
#{222}{}{Nope. I'll be on my way now.}

{220}{}{好了。还有别的事吗？}
{221}{}{是的，实际上，我想代表附近的村庄和你谈一谈。}
{222}{}{不，我有其它事情要做。}


#{230}{}{[He furrows his brow.] Village? Not sure what your--oh! Are you talking about that rat infested little shit-hole down the way?}
#{231}{}{Uh, maybe.}
#{232}{}{Yes, I am.}
#{233}{}{It's not a shit-hole. They're a struggling community that's making some real progress.}

{230}{}{[他额头上的皱纹折了起来]村庄吗？这附近那里来的村庄...哦！你是在说那个满是老鼠屎的难民营吗？}
{231}{}{呃，也许。}
{232}{}{是的。}
{233}{}{不是难民营拉，他们是一个很努力求生存的社区，而且现在他们也开始有一些进展了。}


#{240}{}{Look, I already met with them, and I'm going to tell you the same thing I told them. They're simply too small for me to bother with. Besides, that place is fetid as all hell.}
#{241}{}{Alright. I gave it a shot. Bye.}
#{242}{}{Oh, come on, it's not that far out of your way. You pretty much pass right by it.}
#{243}{}{Is there *any* way I could get you to change your mind?}

{240}{}{听着，我已经见过他们了。那个地方实在太小了，我懒得管，再说，那个地方臭气熏天。}
{241}{}{好吧，我们已经谈过了，再见。}
{242}{}{别这样，那里离你的固定路线其实不远，你顺道过去一下就可以了。}
{243}{}{有什么可以让你改变你的想法吗？}



#{250}{}{Now what? If you're not going to trade, then stop wasting my fucking time.}
#{251}{}{Let's trade.}
#{252}{}{Sorry, I'll go now.}
#{253}{}{I think I'll waste *you* asshole.}
#{254}{}{Is there *any* way I could get you to change your mind about trading with the village?}

{250}{}{如果你不打算交易，那就别再浪费我的时间了。}
{251}{}{让我们交易吧}
{252}{}{抱歉，我现在就走。}
{253}{}{我想我现在要把你*浪费*掉，混球。}
{254}{}{有什么可以让你改变你的想法吗？}


#{260}{}{So what if I do? I don't care if it's only a *minute* out of my way, it's just not worth the hassle.}
#{261}{}{Alright. I see it's useless to reason with you. Bye.}
#{262}{}{Is there *any* way I could get you to change your mind?}
#{263}{}{That's too bad, because a smart merchant would jump on this opportunity. But hey, if you're not interested, I suppose I'll have to go elsewhere...}

{260}{}{为什么我要做呢？ 我不在乎是不是只*花几分钟*时间，是因为那个地方不值得这么麻烦。}
{261}{}{好吧，我看跟你讲道理是没有用的，再见。}
{262}{}{有什么方法可以让你改变你的想法吗？}
{263}{}{那太糟糕了，因为聪明的商人总会懂得抓住机会的。如果你不感兴趣的话，我想我去找别人谈好了。}


#{270}{}{Now just hold on a moment. I didn't say for certain that I wasn't interested. What's this opportunity you speak of?}
#{271}{}{You see, that village might not be much to look at now, but I've got some insider information that all but guarantees that place is going to be the new hot spot. Trust me, it's going to be booming in the coming years. So if I were you, I'd want to build up relations now, before they get too big and you miss your chance.}

{270}{}{等一下，我并没有说我不感兴趣。你说的这个机会是什么？}
{271}{}{你看，那个村庄现在确实不怎么样，但我有一些内部消息，几乎可以保证那个地方将成为新的热点。相信我，在未来的几年里，它将会蓬勃发展。所以，如果我是你，我现在就会和他们建立关系，如果村子扩展到让其它商队注意上了，那你就没什么机会了。}

#{280}{}{Haha! You expect me to believe that shit-hole is going to turn into something worthwhile? I think I'm about done wasting my time with you.}
#{281}{}{Alright. I see it's useless to reason with you. Bye.}
#{282}{}{Is there *any* way I could get you to change your mind?}

{280}{}{哈哈！你竟然想让我相信哪几个小帐篷会变成有价值的东西？我想我们现在是在浪费生命。}
{281}{}{好的，我看跟你讲道理是没有用的，再见。}
{282}{}{有什么可以让你改变你的想法吗？}


#{290}{}{You're not kidding, are you? Hmm, I suppose it couldn't hurt to take a little detour over there now and then. Hell, it's hardly even out of my way. Thanks for the tip, friend.}
#{291}{}{No problem. See ya.}
#{292}{}{Yep. Bye.}

{290}{}{你不是在开玩笑吧？嗯，我想偶尔在那里绕一圈是不会有坏处的。谢谢你的建议，朋友。}
{291}{}{再见，保重。}
{292}{}{再见。}


#{300}{}{[He seems to consider your question.] Perhaps . . . exactly what are we talking here?}
#{301}{}{You make that village a regular stop on your route, and in return, I'll pay you $500.}
#{302}{}{You make that village a regular stop on your route, and in return, I'll do my part to ensure nothing "unfortunate" happens to your caravan.}
#{303}{}{You make that village a regular stop on your route, and in return, I'll show you a good time you'll never forget.}
#{304}{}{You make that village a regular stop on your route, and in return, my wife here will show you a good time you'll never forget.}
#{305}{}{Actually, never mind. Bye.}

{300}{}{[他似乎在考虑你的问题]你的要求是什么？}
{301}{}{你把那个村庄加到你的经商路线上，作为回报，我将付给你$500。}
{302}{}{你把那个村庄加到你的经商路线上，作为回报，我将尽我所能确保你的车队不会发生"不幸"。}
{303}{}{你把那个村庄加到你的经商路线上，作为回报。作为回报，我将向你展示你永远不会忘记的美好时光。}
{304}{}{你把那个村庄加到你的经商路线上，作为回报，作为回报，我的妻子将在这里向你展示你永远不会忘记的美好时光。}
{305}{}{村子和我没什么关系，再见。}


#{310}{}{Now you're speaking my language! Alright, it's a deal. [He greedily snatches the money from you and shakes your hand.]}
#{311}{}{Pleasure doing business with you. Bye.}
#{312}{}{Bye.}

{310}{}{我看我们现在语言一致了！好的，一言为定。 [他贪婪地从你手里抢过钱，握了握你的手]}
{311}{}{记得遵守承诺，再见。}
{312}{}{再见。}

#{320}{}{$500? Not worth it. Make it $1,000 and you've got a deal}
#{321}{}{I don't have that much. Bye.}
#{322}{}{Alright, fine. $1,000 it is.}
#{323}{}{No deal. Goodbye.}

{320}{}{$500？这个路线对我来讲价值太小了，你要办到这件事的话，得花$1,000。}
{321}{}{我没有那么多，再见。}
{322}{}{好，这里是$1,000。}
{323}{}{下次再说吧，再见。}


#{330}{}{Now you're speaking my language! You've got yourself a deal. [He greedily snatches the money from you and shakes your hand.]}
#{331}{}{Pleasure doing business with you. Bye.}
#{332}{}{Bye.}

{330}{}{我看我们现在语言一致了！好的，一言为定。 [他贪婪地从你手里抢过钱，握了握你的手]}
{331}{}{记得遵守承诺，再见。}
{332}{}{再见。}


#{340}{}{Are you threatening me? No one threatens me and lives! [to his caravan guards] Kill this stupid fuck!}
#{341}{}{Bring it on!}

{340}{}{你在威胁我吗？没有人可以威胁我和我的生命！[对他的商队卫兵]杀了这该死的混蛋！}
{341}{}{放马过来！}


#{350}{}{Look, I don't want any trouble. If you want me to swing by and trade with that village, fine, no big deal. Hell, it's hardly even out of my way. No problem.}
#{351}{}{I'm glad we have an understanding. I'll be watching you. Bye.}
#{352}{}{You better hope there's not a problem. Cause if there is, I'll solve it. Bye.}
#{353}{}{[Glare at him intently for a moment, then slowly walk away.]}

{350}{}{听着，我不想惹麻烦。如果你想让我和那个村子做生意，好吧，没什么大不了的。}
{351}{}{我很高兴你能理解我们的难处，再见。}
{352}{}{你最好别给我出什么事，不然我会找你"聊聊"的，再见。}
{353}{}{[对他盯着看了一会儿，然后慢慢地走开]}


#{360}{}{Ugh! God no! I'd rather fuck a brahmin. Now get out of here and stop wasting my time.}
#{361}{}{Fuck you, asshole! [Attack.]}
#{362}{}{Fine, but you could've just said no. No need to be a jerk about it.}
#{363}{}{You don't know what you're missing.}
#{364}{}{[Bury your ugly face in your hands and run away crying.]}

{360}{}{我宁愿去干一头双头牛，现在离开这里，别再浪费我的时间。}
{361}{}{去你妈的，混蛋！[攻击]}
{362}{}{很好，但是你可以直接说不，不需要做一个混蛋。}
{363}{}{你不知道你错过了什么。}
{364}{}{[把你的脸埋在你的手里，哭着跑掉]}


#{370}{}{Eh, sorry girl. I'm just not in the mood right now. You got anything else to offer?}
#{371}{}{You make that village a regular stop on your route, and in return, I'll pay you $500.}
#{372}{}{You make that village a regular stop on your route, and in return, I'll do my part to ensure nothing "unfortunate" happens to your caravan.}
#{373}{}{Nope. Bye.}

{370}{}{嗯，抱歉，女孩。我只是没心情，你还有什么事吗？}
{371}{}{你把那个村庄加到你的经商路线上，作为回报，我将付给你$500。}
{372}{}{你把那个村庄加到你的经商路线上，作为回报，作为回报，我将尽我所能确保你的车队不会发生"不幸"。}
{373}{}{没什么事，再见。}

#{380}{}{[He looks you up and down, then grins.] I think you've got yourself a deal. Do you take it in the backdoor?}
#{381}{}{Baby, I take it any way you want to give it.}
#{382}{}{You'll just have to find out, won't you?}
#{383}{}{Ugh! Hell no! Now let's hurry up and get this over with before I puke.}

{380}{}{[他上下打量你，然后邪恶的笑了] 我想我们能达成协议了，你的后门准备好了吗？宝贝。}
{381}{}{宝贝，我能以任何你想要的方式去做。}
{382}{}{你得自己找到答案，你知道的。}
{383}{}{啊！现在让我们抓紧时间，在我吐出来之前把这件事做完吧。}


#{390}{}{[The merchant grins at you as he refastens his belt.] Holy shit, you sure know how to drive a good bargain. If you ever need to talk a merchant into doing something else, you make sure and look me up. Now, I should really be going. It was a pleasure doing business with you.}
#{391}{}{[Shudder.] Once was enough. Bye.}
#{392}{}{Anytime. Bye.}
#{393}{}{Bye.}

{390}{}{[商人笑着把皮带重新扣上]天啊，你真懂得怎么讨价还价。如果你下次需要说服一个商人去做别的事情，你一定要去找我。现在，我真的要走了。和你做生意是一件愉快的事。}
{391}{}{[不寒而栗]一次就已经足够了。再见}
{392}{}{好的，再见。}
{393}{}{再见。}



#{400}{}{[He looks Miria up and down, then grins.] I think you've got yourself a deal. [He shakes your hand, then puts his arm around Miria and walks her to someplace more private.]}
#{401}{}{[Tap your foot while you wait.]}
#{402}{}{[Whistle while you wait.]}
#{403}{}{[Check your weapons while you wait.]}
#{404}{}{[Stand there silently and make awkward eye contact with the caravan guards while you listen to the sounds of your wife being defiled by the merchant master.]}

{400}{}{[他把麦丽雅上上下下打量了一番，然后邪恶的笑了]我想我们已经达成了协议[他握了握你的手，然后搂着麦丽雅到一个远点的地方]。}
{401}{}{[等待的时候，拍拍你的鞋子]}
{402}{}{[吹口哨等待]}
{403}{}{[检查你的武器，安心等待]}
{404}{}{[站在那里，安静地站在那里，与商队守卫进行眼神交流。你听到妻子和商人的声音]}



#{410}{}{[An hour later, you see Robert Baron and Miria, now sweaty and disheveled from their sexual romp, walking back towards you. You notice Miria is walking with a slight limp. The merchant grins at you as he refastens his belt.] Holy shit, you sure know how to drive a good bargain. If you ever need to talk a merchant into doing something else, you make sure and look me up. Now, I should really be going. It was a pleasure doing business with you.}
#{411}{}{Whatever. Bye.}
#{412}{}{Anytime. Bye.}
#{413}{}{Bye.}

{410}{}{[一小时后，你看到罗伯特·巴伦和麦丽雅汗流浃背地走过来了。你发现麦丽雅走路有点跛，商人在扣上皮带时对你狡黠一笑]天啊，你真懂得讨价还价。如果下次你需要说服一个商人去做别的事情，你一定要去找我。现在我真的要走了，和你做生意是一件愉快的事。}
{411}{}{无论如何，再见。}
{412}{}{任何时候，再见。}
{413}{}{再见。}



#{500}{}{You convince the merchant to add the village to his trade route.}
#{510}{}{You kill the merchant, thus ensuring that the village won't be able to trade.}

{500}{}{你说服商人把村子加到他的贸易路线上。}
{510}{}{你杀了商人，村子不再能外界交易了。}

