#{100}{}{You see a young woman.}
#{101}{}{You see Ann, Connar's wife.}
#{102}{}{She appears to be busily cooking.}

#{200}{}{Why hello there, I'm Connar's wife, Ann. You must be the one who helped us out. I can't tell you how much we appreciate all you've done. It's hard to believe that we can finally live in peace without fear of Vault City's goons coming to take us from our homes.}
#{201}{}{Glad to be of assistance. You seem to be quite busy here. Need some help with anything?}
#{202}{}{No problem. See you around.}

#ipisgfx译
{100}{}{你看见一个年轻的女人。}
{101}{}{你看见安。康尔的妻子。}
{102}{}{她正在忙着做饭呢。}

{200}{}{你好！我叫安。我是康尔的妻子。那么，你一定就是帮助我们的那个人。我们很感激你所做的一切，现在我们能生活的很安宁，不像原来那样担惊受怕了。}
{201}{}{很乐意帮助你们。你看上去很忙。需要帮忙吗？}
{202}{}{没什么，再见。}

#{300}{}{Actually, I *could* use some help. Now that we're becoming more organized, we're starting to see our numbers grow. The problem is, I'm not sure we'll have enough food to go around. My husband has attempted to get the caravans to stop here, but they don't' think we're worth their time. I don't suppose you could get them to reconsider?}
#{301}{}{Sorry lady, but I think I've done enough here. I need to move on now. Bye.}
#{302}{}{Can't you people ever deal with your own fucking problems? Bye.}
#{303}{}{Sure. I'll see what I can do. Who do I talk to about this?}

{300}{}{实际上，我需要一点帮助。现在我们的社区在慢慢扩展，人口也在增长。但现在的问题是，我们食物并不充足。我丈夫曾试图让商队把这里作为一条路线，但商队不认为我们值得花时间。我想你不能让他们重新考虑一下吧？}
{301}{}{对不起女士，但我认为我在这里做得够多了。我得走了。再见。}
{302}{}{难道你们就不能解决自己的问题吗？ }
{303}{}{我看看我能做些什么，我该跟谁谈这个？}

#{310}{}{One of the caravan masters, Mr. Baron, will be passing by here shortly. The caravan trail isn't far from this village. If you could go out there and meet with him, we'd all appreciate it greatly.}
#{311}{}{Alright, I'll give it a shot. Show me where he is.}
#{312}{}{Alright, but I'm not ready yet. I'll let you know when I am.}
#{313}{}{On second thought, you're going to have to handle this on your own. Sorry.}

{310}{}{巴伦先生，他是商队的一位主人，不久就会从这里经过。商队小道离这个村子不远。如果你能出去见见他，我们都会非常感激的。}
{311}{}{好吧，我试试看。告诉我他在哪里。}
{312}{}{好的，但是我现在还要办些事，我准备好了再回来。}
{313}{}{你必须自己处理这件事，抱歉。}

#{320}{}{Are you ready to go meet the caravan master yet?}
#{321}{}{Not yet. Bye.}
#{322}{}{Alright. I'm ready.}

{320}{}{你准备好去会见商队的主人了吗？}
{321}{}{还没有。再见。}
{322}{}{好了。我准备好了。}


#{330}{}{Oh, it's you! Thank you for speaking with Mr. Baron. He had just come by to make trade arrangements with my husband. You've done so much to help us, we're forever in your debt!}
#{331}{}{It's the least I could do. Take care.}
#{332}{}{You think I do all this for free? Let's talk money.}

{330}{}{哦，是你！感谢你和巴伦先生谈判，他刚刚过来，和我丈夫做贸易安排。我们永远感谢你为我们做的事情！}
{331}{}{这是我能做的事，保重。}
{332}{}{你认为我是免费做这些的吗？让我们谈谈报酬。}


#{340}{}{[Ann looks a bit flustered.] Well, yes...alright fine. I had a little something stored away for an emergency, but I suppose you can have it. And to think I saw you as a good person.}
#{341}{}{Looks are in the eyes of the beholder, lady. Good day.}
#{342}{}{Sorry, money makes the world go round. Bye.}

{340}{}{[安看起来有点慌乱]嗯，是的...好的，我有一些东西是打算用来应急的，但我想你可以拿去，你是个好人。}
{341}{}{旁观者清，女士，美好的一天。}
{342}{}{对不起，金钱使世界运转。再见。}


#{350}{}{Oh, it's you! I heard what you did to Mr. Baron. I never did care for him, but you didn't have to kill him. We'll stifle as a community without proper trade.}
#{351}{}{Sorry, mistakes happen. Bye.}
#{352}{}{Not my problem. Bye.}
#{353}{}{You don't need to worry about any damn merchants. Because I plan on killing the whole lot of you.}

{350}{}{哦，是你！我听说了你对巴伦先生做了什么。我从不关心他，但你不用杀他。但如果没有适当的贸易，我们这里也生存不下来的。}
{351}{}{抱歉，这是一个意外，再见。}
{352}{}{这不是我的问题，再见。}
{353}{}{你不需要担心任何该死的商人，因为我打算把你们都杀了。}


#{400}{}{Did Vault City send you?}
#{401}{}{We have the right to live here, you know.}
#{402}{}{I have nothing more to say to you.}
#{403}{}{Thanks again for everything!}
#{404}{}{Thanks so much!}
#{405}{}{Finally we are safe.}
#{406}{}{Thanks for everything! Be sure to stop by again once we expand the place. I'll finally have a working kitchen to cook in.}

{400}{}{地下掩体市叫你来的吗？}
{401}{}{请你明白，我们有权住在这里。}
{402}{}{我没有什么要对你说的。}
{403}{}{感谢你做的一切！}
{404}{}{非常感谢！}
{405}{}{我们终于安全了！}
{406}{}{感谢你所做的一切！我们的社区一直在扩展，过段日子你一定要再来一次，我想我终于能有一个真正的厨房了。}


#{410}{}{Hello again.}
#{411}{}{You seem to be quite busy here. Need some help with anything?}
#{412}{}{Nevermind. Bye.}

{410}{}{你好。}
{411}{}{你看上去很忙。需要帮忙吗？}
{412}{}{没什么，再见。}


#{420}{}{How did it go?}
#{421}{}{How did what go? Oh, the merchant. Actually, I lost interest with him and wandered off.}

{420}{}{事情怎么样了？}
{421}{}{什么怎么样啊？哦，商人。实际上，我对这件事没有兴趣了，再见。}


#{430}{}{What！？You realize this was our last chance to make arragements with him. We look like fools now standing him up. You've doomed us.}
#{431}{}{Sorry, mistakes happen. Bye.}
#{432}{}{Not my problem. Bye.}
#{433}{}{You don't need to worry about any damn merchants. Because I plan on killing the whole lot of you.}

{430}{}{什么！？你是我们最后的希望，我们每天像傻瓜一样盼着商人会过来。}
{431}{}{抱歉，再见。}
{432}{}{这不是我的问题，再见。}
{433}{}{你不需要担心任何该死的商人，因为我打算把你们都杀了。}

#{500}{}{You convinced the merchant to add the village to his trade route.}
#{510}{}{You killed the merchant, thus ensuring that the village won't be able to trade.}
#{511}{}{You fail to convince the merchant to add the village to his trade route.}

{500}{}{你说服商人把村子加到他的贸易路线上。}
{510}{}{你杀死了商人，村庄再不能和外界交易了。}
{511}{}{你没能说服商人把村子加到他的贸易路线上。}

