#ipisgfx译
#{100}{}{You entered a small village. You see a lot of molerats around. They are not attacking you for some reason.}
{100}{}{你进入了一个小村庄。你看见周围有许多地鼠。它们好像不想攻击你。}
{101}{}{这个村庄看上去什么都没有。空气中充满了地鼠尸体的臭味。}
{102}{}{这个村庄比起你上次来现在大有改观。}
#{103}{}{Even more has changed since you were last here. It seems the protection of the molerats has been replaced with a wall.}
{103}{}{比起你上次来，这里变了很多。原先到处是地鼠，而现在架起了围墙。}
{104}{}{嗨！人们都去哪了？}