#{100}{}{You see a very hyperactive little boy.}
#{101}{}{You see Little Todd.}

{100}{}{你看到一个非常活跃的小男孩。}
{101}{}{你看到小托德。}

#random floats
#{200}{}{BOOM!!! I love 'splosions!}
#{201}{}{Bam-bam! I shoot mutants!}
#{202}{}{I wish I saw more 'splosions!}
#{203}{}{Everything should explode!}

{200}{}{BOOM!!!我爱'splosions！}
{201}{}{Bam-bam! 我射击变种人！}
{202}{}{我希望能看到更多的'splosions！}
{203}{}{炸掉所有东西！}


#dialogue
#{300}{}{Can you blow something up, Mister?}
#{301}{}{When I grow up, I'm gonna rule the world!}
#{302}{}{I don't like it here, I wanna move to the east coast!}
#{303}{}{My clothes are magic!}
#{304}{}{Grownups talk too much!}
#{305}{}{The Brotherhood of Steel are the knights of the wasteland!}
#{306}{}{All mutants are evil!}
#{307}{}{I bet my teddy bear could kill you!}
#{308}{}{My dad went missing again!}
#{309}{}{Sometimes I drink from toilets!}
#{310}{}{What's cont-i-newy-t mean?}
#{311}{}{Can you blow something up, Misses?}

{300}{}{你能炸飞什么东西吗？先生。}
{301}{}{当我长大了，我要统治世界！}
{302}{}{我不喜欢这里，我想搬到东海岸去！}
{303}{}{我的衣服有魔法! }
{304}{}{大人们太喜欢说话了! }
{305}{}{"钢铁兄弟会是荒原上的骑士!"}
{306}{}{所有变种人都是邪恶的！}
{307}{}{我打赌我的玩具熊会杀了你！}
{308}{}{我爸爸又失踪了！}
{309}{}{有时我从厕所里喝水！}
{310}{}{cont-i-newy-t是什么意思？}
{311}{}{你能“吹”起些什么东西吗？小妞。[原文*Can you blow something up, Misses?*，取双意]}
