#ipisgfx译
#{100}{}{As you leave the outskirts of the city you skillfully notice a group of armed men being stealthily led through the bushes by a strong looking tribal. The tribal glances in your direction and spots you looking at him. He gives a signal and the group of men he is leading duck down and dissapear.}
{100}{}{当你离开市郊时，你注意到一个强壮的土人带着一群武装人员正悄悄地穿过矮树丛。这个土人扫视了一下你所在的方向发现你正在看着他。他给那群人发了个信号，带领他们急忙蹲下躲藏了起来。}
{101}{}{[跟着他们保持安全距离]}
{102}{}{[不管他们，离开]}