#{103}{}{This bot seems uninterested in talking to you.}
#{104}{}{This bot seems to be deactivated.}
#{105}{}{Intruder Alert! Intruder Alert!}
##{106}{}{Destroy Target!}
#{107}{}{Security System Malfunctioning!}
#{108}{}{System Error!}

#{150}{}{You seem to have disabled the robot.}
#{151}{}{You seem to have repaired the robot completely.}

{103}{}{这个机器人似乎没有兴趣和你说话。}
{104}{}{这个机器人似乎已经坏了。}
{105}{}{入侵警报！侵警报！}
{106}{}{摧毁目标！}
{107}{}{安全系统故障！}
{108}{}{系统错误！}

{150}{}{你似乎已经使机器人失灵了。}
{151}{}{你似乎已经完全修复了这个机器人。}
