#{100}{}{You smoke a Commie.}
#{101}{}{You smoke another Commie.}
#{102}{}{Inside your helmet there's a warning: "DANGER! - No smoking!!" You think you better do as it says.}
#{103}{}{You've smoked 'em all.}
#{104}{}{You need a lighter first.}

{100}{}{你点了根烟。}
{101}{}{你又点了根烟。}
{102}{}{在你的头盔里面有一个警告：“危险！禁止吸烟！！”你认为你最好照它说的做。}
{103}{}{你吸烟。}
{104}{}{你需要一个打火机。}



#{200}{}{You smoke a joint.}
#{201}{}{You smoke another joint.}
#{203}{}{You're all outa weed.}

{200}{}{你抽了一口大麻。}
{201}{}{你又抽了一口大麻。}
{203}{}{你抽了所有的大麻。}

#{210}{}{Whoa. That is some herb SUPERB.}
#{211}{}{Okay, I'm just gonna lie down here for a while.}
#{212}{}{You begin to feel VERY light headed.}
#{213}{}{I am feeling really strange right now...}
#{214}{}{...this must be how Hakunin feels in his garden.}
#{215}{}{That was crazy. I feel better now though.}
#{216}{}{Oh shit...}
#{217}{}{You pass out.}
#{218}{}{You wake up feeling dazed and confused.}

{210}{}{哇，那他妈真是一种好草药。}
{211}{}{好的，我要在这里躺一会儿。}
{212}{}{你开始感到头晕了。}
{213}{}{我现在感觉很奇怪...}
{214}{}{...这一定就是哈库林在他的花园里的感觉。}
{215}{}{那真是疯狂，我现在感觉好多了。}
{216}{}{啊，狗屎...}
{217}{}{你晕倒了。}
{218}{}{你醒来的时候感到昏昏沉沉的。}


#{250}{}{Smoking is a disgusting habit for a woman to have.}
{250}{}{吸烟是女人的一个令人讨厌的习惯。}
