#You see a grave marker.
{100}{}{你看见了一个墓碑。}
#The grave marker reads: 
{101}{}{墓碑上写着： }
#"Here lies Brother Gregory. A man who knew no limits."
{102}{}{"长眠于此的是格雷戈里兄弟。一个无人不知的人"}
#"Aunt Patty. Good riddance indeed."
{103}{}{"Patty姑妈。可喜的解脱"}
#Here lies Per Joner. Died one rock too short.
{104}{}{"长眠于此的是乔恩。是被石头砸死的。"}
#Here lies Father Michael. Founder, Father, Fighter.
{105}{}{"长眠于此的是麦克尔。创始人，父亲，战士。"}
#An Atheist. All dressed up and no place to go.
{106}{}{"一个无神论者。·#￥%……￥%……"}
#"Here lies Johnny Yeast. Pardon me for not rising."
{107}{}{"长眠于此的是乔尼。原谅我没#￥%……——"}
#"Mary Jane. Loving wife and mother."
{108}{}{"玛丽 简。亲爱的妻子和母亲。"}
#"'Checkmate!' was the call to dear old Jon, On the chessboard of life, He was just a pawn.
{109}{}{"国王!' 是亲爱的老乔恩的称号，在棋盘上的一生，他只是一个小卒。}
#"Sir John Strange, here lies an honest lawyer, and that is Strange."
{110}{}{"ipisgfx，因自不量力汉化什么F2_Restoration_Project，结果落得个长眠于此！"}
#Tears cannot restore her -- therefore I weep.
{111}{}{"眼泪不能让她复活 -- 因此我伤心。"}
#Every day in every way, I am getting better and better.
{112}{}{"每时每刻，我都在变的更好。安心去吧！"}

#There are no markings on this grave marker.
{250}{}{这个墓碑没有任何碑文。}
#The grave marker is too cracked and broken to be read.
{251}{}{这个墓碑破损太大，无法读了。}
#The name on the grave marker reads John Doe.
{252}{}{这个墓碑的名字是某约翰。}
#The name and date on this headstone have been worn off by the weather.
{253}{}{这个墓碑上的名字日期已经被风化了。}