#You see Hank.
{100}{}{你看见翰克。}
#You see a greasy monk.
{101}{}{你看见一个肥胖的修道士。}
{102}{}{He is messing with a still.}

#Hey, buddy. Do you have a lighter on you?
{200}{}{嗨，哥们。你有打火机吗？}
#Yep. [Hand your lighter to him.]
{201}{}{有。 [伸手帮他点火]}
#This is perfect. Thanks!
{202}{}{真是棒极了。谢了！}
#Out of curiosity, what exactly are you doing here?
{203}{}{出于好奇，你来这干嘛？}
#Sure. Since you brought me a lighter, here's one on the house.
{204}{}{当然，鉴于你借火给我，今天我请客。}
#[Drink it.]
{205}{}{[喝酒]}
#I changed my mind I don't want any alcohol. Bye.
{206}{}{我改变想法了，我不想要酒了。再见。}
#You feel warm and relaxed after you gulp down the liquor.
{207}{}{(一杯下去，你感觉很暖和很放松。)}
#Gimme another, Hank.
{208}{}{给我再来一杯，翰克。}
#I'll go now, bye.
{209}{}{我得走了。再见。}
#(Suddenly you feel like shit, then your vision begins to blur. You fall on the ground...)
{210}{}{(突然你感觉很糟糕，视线变得模糊。你跌在了地板上...)}
{211}{}{[完成]}
#No, Sorry.
{212}{}{不，报歉。}
#Hi, again.
{213}{}{嗨，又见面了。}
#Hi and bye.
{214}{}{嗨一会见。}
#This one won't be free. It will cost you $20.
{215}{}{这不是免费的，得花$20。}
#Sure. Here's the money.
{216}{}{没问题，这是钱。}
#Nah, I've had enough. Maybe next time.
{217}{}{不，够了。也许下次吧。}
#(He pockets the money.) Alright then, here's the drink.
{218}{}{(他收起钱。) 酒在这。}

#Any luck finding a lighter?
{220}{}{你找到打火机了？}

#{250}{}{I would like to buy some of the alcohol you make here.}
{250}{}{我想买点带酒精的东西如果你这有的话。}
#{251}{}{Just looking around. Take care.}
{251}{}{随便逛逛。别介意。}
#{252}{}{Sure. $20 a bottle.}
{252}{}{当然. $20 一瓶。}
#{253}{}{[Hold on to it.]}
{253}{}{[继椟]}


#{300}{}{Where did I put my lighter.}
{300}{}{我把打火机放哪去了。}
#{301}{}{I need a lighter.}
{301}{}{我需要个打火机。}
#{302}{}{COULD SOMEONE BRING ME A LIGHTER.}
{302}{}{谁能借个打火机给我。}
#{303}{}{Uh, Hi there.}
{303}{}{嗯, 嗨你好。}
#{304}{}{Sorry, I can't chat with you now.}
{304}{}{对不起，我现在不能和你聊天。}

#{400}{}{Ooh, look at all those pretty stars!}
{400}{}{呵，看看这些漂亮的星星！}

#{500}{}{Hello. Need something?}
{500}{}{哈罗，需要点什么？}
{501}{}{Hey, thanks again for the lighter. It's better than my old one.}
{501}{}{嗨, 再次谢谢你的打火机。比我以前那个好多了。}

#{600}{}{We brew our own alcohol here at the monastery. Some of the most powerful stuff you'll taste in the Wastes.}
{600}{}{我们在这修道院酿造我们的酒。 在这酒里你能尝到一些最劲的东西。}
#{601}{}{Mind if I try some?}
{601}{}{介意我试一点吗？}
#{602}{}{Sounds interesting. I must be going.}
{602}{}{听起来很有趣，不过我得走了。}

#{700}{}{That's too bad. I lost mine recently and I cannot seem to find it. If you ever get your hands on one, I would be glad to take it off your hands.}
{700}{}{那太糟了。我的丢了找不到去哪了。如果你正好有多的，我很乐意要一个。}
#{701}{}{Sure. If I come across one I will let you know. Bye.}
{701}{}{当然，如果我多着我会告诉你的。再见。}
#{702}{}{Sorry. I'm a bit of a collector and keep all that I find. Bye.}
{702}{}{对不起，我是个收藏家，我会收藏所有找到的。再见。}
