#{100}{}{You see Jack, the medic of Abbey.}ipisgfx译
{100}{}{你看见杰克，阿比的医生。}
#{101}{}{He has a red cross on his shoulder.}
{101}{}{他肩上有一个红色的十字。}

#{200}{}{If you are injured, talk to me.}
{200}{}{如果你受伤了，告诉我。}

#{300}{}{How can I help you?}
{300}{}{我能帮你什么吗？}
#{301}{}{I'm injured, can you help me?}
{301}{}{我受伤了，你能帮我吗？}
#{302}{}{[Drool.]}
{302}{}{[说昏话.]}
#{303}{}{So, what do you do here at the Abbey?}
{303}{}{那么，你在阿比做些什么？}
{304}{}{再见。}

#{400}{}{It is done!}
{400}{}{搞定了！}
{401}{}{谢谢。}
#{402}{}{Stop that!}
{402}{}{别那样！}
{403}{}{[继续]}
{404}{}{[离开]}
{405}{}{停下！停下！停下！}
{406}{}{[继续]}
{407}{}{[停止]}
#{408}{}{(suddenly, jack starts to melt) I'M MELTING, I'M MELTING, OH WHAT A WORLD...}
{408}{}{(突然，杰克开始熔化) 我在熔化，我在熔化，天哪，这是个什么世界...}
#{409}{}{What the fu...}
{409}{}{这是什－－..什—什么....}

#{500}{}{Hey, don't steal my medical supplies!}
{500}{}{嗨，别偷我的医疗补给品！}
#{501}{}{You gain 200 experience points for making Jack melt. Are you happy now, bastard!}
{501}{}{你获得了200点经验，因为你使杰克熔化了。你现在高兴了？混蛋！}

#{600}{}{I am the doctor here. I have been here about 15 years now.}
{600}{}{我是这的医生。我来这有15年了。}
#{601}{}{I see. You must have a great knowledge in medicine then.}
{601}{}{我明白了。你在医学方面一定很有知识。.}
#{602}{}{Where did you get all your medical equipment?}
{602}{}{你在哪获得你的医学设备的？}
#{603}{}{Interesting. I think I will be leaving now.}
{603}{}{有意思。我想我该走了。}
#{604}{}{Yes, although I do learn something new every week. It's funny...even when you think you know everything you need to know, you always come across something new.}
{604}{}{是的, 尽管我每周都在学习新的知识。但有趣的是当你觉得学会了所有的知识的时候，你总是变得想知道更多的。}
#{605}{}{Yeah, that is so true.}
{605}{}{是，说的太对了。}

#{700}{}{Some of these meds I received from my father. Other meds were already in the Abbey.}
{700}{}{一些是从我父亲那得的。其他的都是在阿比的。}
{701}{}{有意思。再见。}
#{702}{}{Could you give me some of your meds. You seem to already have more than you are ever going to need.}
{702}{}{你能给我一些你的医学设备吗？看上去你好像不需要这么多。}
#{703}{}{Why do you need these meds?}
{703}{}{你为什么需要这些医学设备？}
#{704}{}{I don't have any particular reason...}
{704}{}{我也没什么具体的理由...}
#{705}{}{I'm on my holy quest to find a Garden Of Eden Creation Kit. You see, my village needs it to survive. Those meds could help me on my journey.}
{705}{}{我在执行寻找伊甸园制造器的神圣任务，我的村子需要用它来拯救。这些医学设备在我的旅程中会有很大帮助。}
#{706}{}{(He thinks about what you have just said) You're right. I'll give you some medical supplies, you're surely gonna need them. Here (he hands them to you) and good luck, wanderer.}
{706}{}{(他想了一下你刚才所说的。) 你是对的。我会给你一些医学设备的，你的确需要它们。 拿去(他递给你) 还有祝你好运，流浪者。}
#{707}{}{Thanks, Jack. These meds will sure come in handy, bye.}
{707}{}{谢谢，杰克。这些东西一定会很有用的。再见。}

#{708}{}{In that case, I don't have ANY reason to give you any medical supplies.}
{708}{}{如果是那样的话，我没有理由给你任何医疗补给品。}
#{709}{}{Fine, GOODBYE.}
{709}{}{很好，再见~~~~}

#{800}{}{I can't talk right now.}
{800}{}{我现在不能说话。}
#{801}{}{Sorry, I'm in the middle of some medical research now.}
{801}{}{对不起，我现在正在某种医学的研究中。}
#{802}{}{Hello again.}
{802}{}{又见面了。}