#ipisgfx译
{100}{}{你看见一个中年修士。}
{101}{}{你看见修士马太。}
#{102}{}{He is standing at a podium preaching to the citizens of Abbey.}
{102}{}{他正站在讲台上为阿比的市民讲道。}

#{200}{}{Good people of Abbey. Take a moment to listen, for I have much to say.}
{200}{}{阿比善良的人们。给我片刻，我有一些话要说。}
#{201}{}{These great many books we have here have much to tell.}
{201}{}{我们在这里有很多书，我们在这里要讲述。}
#{202}{}{From science to philosophy, Asimov to zebras,}zebras-斑马。。？
{202}{}{从科学到哲学，从Asimov到Zebras。}
#{203}{}{The wisdom of saints, and madmen's ravings.}
{203}{}{圣人的至理名言，和疯子的胡言乱语。}
{204}{}{因那所作所为已然记录，因那所选所择已然显露；}
#{205}{}{So our world might become a better place to be.}
{205}{}{也许我们的世界，会变成更好的世界。}
#{206}{}{Yes, within these pages the greatest tragedies and comedies of all time are sealed.}
{206}{}{书中的喜怒哀乐，人们依然不知。}
#{207}{}{So that, for your sake, they could be later revealed.}
{207}{}{所以为了你们，我将稍后明示。}
{208}{}{因为从错误中得到知识，从失败中学会升级。}
{209}{}{于是在成功与放弃之间，我们掌握清晰的对比。}
{210}{}{这些事迹被写下，成功，或是失败。}

{211}{}{这些共鸣在回荡，现在，或是将来。}
{212}{}{看，人们不见自身，不见行事的光芒；}
{213}{}{但，书籍目睹一切，目睹他们的灭亡。}
{214}{}{不论多小，故事总能被读到， }
{215}{}{不论几代，传说总能被听到。}
{216}{}{因为前辈的作为已被记录，一次又一次地重复；}

{217}{}{于是年轻人的奋斗与罪孽，一次又一次地重复。}
{218}{}{若有一天，你能与书为伍； }
{219}{}{不论去向哪里，你都不会孤独。}
{220}{}{你的孩子，终将被书左右；}
{221}{}{结局如何？毁灭或是拯救？}
{222}{}{你的所作所为已被写下，属于你自己的传奇。}
{223}{}{喜剧还是悲剧，全在你自己的心底。}

#{224}{}{Now, please take a moment and reflect on what I have said.}
{224}{}{现在，请用一点时间来细想一下我说的这些。}

#{300}{}{Greetings friend. I don't think I have seen you around here before. My name is Brother Matthew and I help spread
 the word about the importance of books and the knowledge contained within them.}
#{300}{}{祝福你朋友，我想我以前没见过你吧。我叫马太修士，我向世界传播书中的价值和其中的知识。}
#{301}{}{It's good to meet you Matt. My name is }
{301}{}{很高兴见到你马太。我的名字是}
#{302}{}{ and I am on a quest for the holy GECK.}
{302}{}{ 我正在寻找神圣的伊甸园创造器。}
#{303}{}{Sorry, I must be going.}
{303}{}{对不起，我得走了。}

#{400}{}{A GECK, huh? I do remember reading something about that during one of my reading sessions. Go to the second floor
 and ask for access to one of our computers. I am sure you will find something useful there. And while you are at it, take
 a moment to peruse through our library. Not all our books have been copied over to the computers yet and a great many books
 are still found in their original format.}
{400}{}{伊甸园创造器？我记得读过一些相关的资料。去二楼查寻下我们的电脑。我相信你会找到一些有用的资料的。你到那细读一下我们的图书馆里的书。不是所有书都拷贝到电脑里的，很多伟大的书都是原版。}
#{401}{}{I think I just might. I have some questions though.}
{401}{}{我想我会的。我还有一些问题。}
#{402}{}{Thank. I shall go do that now.}
{402}{}{谢谢，我现在就去。}

#{500}{}{I am at your service. What would you like to know?}
{500}{}{你想知道什么？}
#{501}{}{What can you tell me about this place?}
{501}{}{你能说说这个地方吗？}
#{502}{}{You seem to be very poetic in your preaching. Any reason for this?}
{502}{}{你在演讲时看上去很有诗意。为此有什么理由吗？}
#{503}{}{Nevermind. Take care.}
{503}{}{没什么，别介意。}

#{600}{}{Well, Abbey is home to anyone so long they don't cause trouble. We are an independent community and rarely get visitors. The majority of those you see here came as one group a long time ago. I was part of this group and a young boy at the time. We came across this old monastery we are standing in and we thought it would make a peaceful home. We found numerous books scattered around and we decided to make it our mission to preserve the knowledge contained inside so that future generations could also enjoy them.}
{600}{}{好的，阿比一直以来都是任何不想找麻烦的人的家。我们是一个独立的团体，很少有访客来此。我们经过这个修道院时停留下来了，觉得这会是一个安宁的家。我们发现许多书分散在这，于是决定以保护这些知识让未来的一代人也享受到它们。}
{601}{}{继续。}
#{602}{}{Over the years a few other individuals have wandered their way in here and decided to settle down. It has been quite peaceful here and we hope it stays that way.}
{602}{}{近年来少部分其他的个体在这迷路，最终他们决定安居于此。这里很平静我们希望一直这样下去。}
#{603}{}{Very interesting. Another question.}
{603}{}{很有趣，问下别的问题。}
{604}{}{很有趣，我得走了。}

#{700}{}{[The man chuckles at your question] No, no particular reason. I have just read much poetry throughout my life
 and I enjoy applying it to my teachings. It helps leave a greater impact on those listening.}
{700}{}{[因为你的问题他吃吃的笑] 不，不，没什么特别的理由。只是因为在我的一生里我读了很多诗，我很享受把它应用到我的演讲里，这有助于他们聆听。}
#{701}{}{Fair enough. Another question.}
{701}{}{非常好。另一个问题。}

{800}{}{很高兴再次见到你。}
{801}{}{我能为你做点什么？}
{802}{}{我有一些问题。}
{803}{}{没什么，再见。}
