#ipisgfx译
{100}{}{你看见一个商人。}
{102}{}{你看见这个商人在试着修理这个抽水泵。}
{103}{}{我只是没有某种东西继续工作。}
{104}{}{看上去修起来非常困难。}
{105}{}{这是什么狗屎！}
{106}{}{真是顽固的婊子对吧？}
{107}{}{你能伸手帮个忙吗？}
{108}{}{也行你对这个运气会更好一些。}
{109}{}{嗨，谢谢你修好的抽水泵。}
{110}{}{你应该向修士长通报一下抽水泵现在修好了。}
{200}{}{谢谢帮我们做这个。}


{300}{}{啊，这是什么狗屎－#￥%……—我现在很忙。你有什么需要还是你只是想浪费我的时间？}
#{301}{}{Actually yes, the Head Monk sent me. He said the water pump is having some trouble.}
{301}{}{实际上是，修士长叫我来的。他说这个抽水泵有一点问题。}
#{302}{}{Heh, "having trouble" is an understatement. This ol' thing is totally busted. There's no way
 it is going to run again.}
{302}{}{嗯哈，“有一点问题”只是保守说法。这已经完全坏了。已经没法再起动了。}
#{303}{}{Well, mind if I take a look? I did promise the Head Monk I would see what I could do.}
{303}{}{好吧，介意我查看一下吗？我答应过修士长看看我能做点什么。}
#{304}{}{Sure, be my guest. Not like you could break it any more.}
{304}{}{当然，我的客人。你也不可能再把它弄的更糟了。}
#{305}{}{I don't mean to bother, but what seems to be the trouble here?}
{305}{}{我无意打扰，不过看上去有些故障？}
#{306}{}{The main water pump for Abbey is busted. The damn thing was breathing its last the past few days and now its finally gone out.}
{306}{}{阿比的主抽水泵坏了。最糟的是这样下去再过几天农作物会慢慢死去的。}
#{307}{}{I'm a bit of a techie, mind if I take a look?}
{307}{}{我有个工程学学位，介意我看看吗？}
#{308}{}{Well, I'm not that great with machines, but perhaps I can see if something can be done.}
{308}{}{好吧，我对机械不是非常在行，不过或许我能找出问题所在。}
#{309}{}{Sure, no one's stopping you.}
{309}{}{没问题，没人会阻止你。}
{310}{}{噢，对不起，再见。}
#{311}{}{I'll see what I can do then.}
{311}{}{我会知道我能做什么了。}

#{400}{}{Oh, it's you again. Any luck?}
{400}{}{噢，又是你，一切顺利吗？}
#{401}{}{No, not yet. I'll get back to you if I do.}
{401}{}{不，还在进行。找到后我会回来的。}
#{402}{}{Actually yes. I looked inside and it seems the motor is completely busted. The connections are shot so we are going to have to get our hands on a new motor as well as some wires to reconnect everything since the old wires are fried.}
{402}{}{实际上是，我查看了一下看上去是发动机坏了。原因是旧连接器烧了，导致发电机也坏了。找个新的发电机再重新连上电线就行了。}

#{500}{}{Hmm...the connectors are shot on the main motor, eh? Well, I got some wires here with me that will work, but not that specific motor. I am sure Vault City has the part though.  Go there and speak with Harry in the main courtyard. Tell him Dave sent you. Damn motor is expensive, but he should give you a good deal.}
{500}{}{嗯...主发动机挂了？好吧，我找一些新连接器来就能工作了。不过没有新的发动机。我想地下掩体城会有那玩样。去那找哈利，告诉他戴夫叫你来的。这玩样很贵，不过他会给你折扣的。}
#{501}{}{I'll head there now. Be back soon.}
{501}{}{我现在就去那，马上回来。}

#{600}{}{Any luck on that part? This machine won't fix itself.}
{600}{}{一切顺利吗？这机器可不会自己修好。}
#{601}{}{No not yet. I'll be back when I get it.}
{601}{}{正在做呢。我找到就会回来的。}
#{602}{}{Yep, got the part right here.}
{602}{}{是的，东西在这。}

#{700}{}{Excellent. Want me to install the damn thing or do you want the pleasure?}
{700}{}{太好了，要我装上去还是你愿意效劳？}
#{701}{}{I think I can handle it. Step aside.}
{701}{}{我想我能操作它。让开一点。}
#{702}{}{Actually, I think I have done enough this job. Go ahead and install it yourself.}
{702}{}{实际上，我想我已经做的够多了。你自己装吧。}

#{800}{}{Alright fine, hand it over.}
{800}{}{很好，交换一下。}
{801}{}{你请吧。}

#{900}{}{That should do it.}
{900}{}{做这事。}
#{901}{}{The water pump has been repaired.}
{901}{}{抽水泵被修好了。}

#if head monk gives you the quest
#{910}{}{(Wipes the sweat from his forehead.) Yeah, need something?}
{910}{}{(擦着额头的汗)是的，需要什么？}
#{911}{}{The Head Monk said you might need some assistance. What seems to be the trouble?}
{911}{}{修士长说你需要一些帮助。似乎出了什么问题？}
#{912}{}{Nevermind. Goodbye.}
{912}{}{别介意。再见。}