#ipisgfx译
{100}{}{你看见一个年青人，看上去很强壮。}
{101}{}{你看见彼得斯先生。}

#{200}{}{Hello, friend. Haven't seen you around here before. First time to Abbey?}
{200}{}{你好，朋友。以前没见过你。你一次来阿比？}
{201}{}{很高兴再次见到你。我能为你做点什么？}
{202}{}{是，你能介绍一下这个地方吗？}
{203}{}{我正在找神圣的伊甸园创造器。关于这个你知道什么吗？}
#{204}{}{Brother Samuel said you might know something about who is disturbing the graves. He said you heard some noises coming from your crops.}
{204}{}{塞缪尔修士说你可能知道一些关于谁在墓地捣乱的事。他说你听到一些噪声在你的田里。}
{205}{}{别介意，我得走了。}

#{300}{}{Well, Abbey is a very safe place to be, unlike some other places you might find yourself. I myself only came here a few years ago with my wife on a caravan. We liked it here so much we decided to stay. We started growing some crops to make money and we have been here ever since.}
{300}{}{好的，阿比是一个很安宁的地方，不象其他地方你能找到自我。我和我的妻子和一个商队到这只有几年。 我们很喜欢这最终决定留下。 从那后我们开始种一些农作物卖钱。}
#{301}{}{You came on a caravan? Do they come often here?}
{301}{}{你自一个商队？你经常到这？}
#{302}{}{Not really. Abbey is only on a minor trade route and even that doesn't mean a caravan will always stop by.Everyone here at Abbey still gets by despite this. If you want to learn more about when the caravans stop by, ask Bill over at the general store. He would know more about this. You can find his place southeast of here.}
{302}{}{不是的。。阿比是一个二流的商业线路使得商队不会经常停在这。如果你想获悉理多关于商队的事。问问那边商店的比尔。他可能知道更多的事。你可以在南边找到他。}
#{303}{}{That sounds great and all, but I really must be going.}
{303}{}{那听上去不错。不过我真的要走了。}
{304}{}{很有趣，我想知道点别的事。}
{305}{}{别介意。我得走了。}

{400}{}{你还要知道什么？}
{401}{}{关于阿比你能告诉我什么？}
{402}{}{你知道关于伊甸园创造器的事吗？}

{500}{}{伊甸园创造器？嗯....我记得在大教堂的档案室读过一点有关的资料。我不记得上面怎么说的了。如果我是你我就去查查那些文件。也许你能找到一些有用的信息。}
{501}{}{谢谢，我就去看看。我还有一些问题。}
{502}{}{谢谢你的消息。我现在就去查查。}

#{600}{}{Brother Samuel sent you here? What's that drunkard up to now?}
{600}{}{塞缪尔修士叫你来的？什么他现在酒醒了？}
#{601}{}{Tending to the graves as usual I suppose. So about what you heard...}
{601}{}{所以你听说了什么...}
#{602}{}{(John sits down in his chair and pours himself a shot of whiskey.) Well, it all began a couple days ago.I was home here with the wife when we heard some rustling out in the field. I grabbed my lantern and rushed outside to see if I could find the source of the noise. As soon as I made it to the fields though, the noises had stopped.}
{602}{}{(约翰坐到了椅子上喝了几口酒) 好吧，一切始于几天前，我和我的妻子在家，当我们听到一些沙沙声后我就准备到田间查看一下。我拿着提灯匆忙出去看是什么发出这种声音。当我到了田里时声音就没了。}
{603}{}{继续。}
#{604}{}{Look, I really must be going.}
{604}{}{听着。我真必需走了。}
#{605}{}{Well the next night we didn't hear a thing. The night after that though we heard rustling coming from the field again. This time I crept to the window and looked out rather than rushing outside. This time I saw a dim light,like from an old lantern or something, moving among the crops. After a couple minutes the light moved toward the cemetery.}
{605}{}{然后第二晚我们就没听见任何声音了。又一晚我们又听见那个沙沙声。这次我小心的到窗口看外面。这次我看见一个暗光。好像是一个老旧的提灯发出的，在农田间移动。几分钟后这个暗光移向了墓地。}
#{606}{}{I decided it would be best if I just stayed inside and check on things in the morning. The next day I went to check on the crops and I saw that some of them had been eaten and fresh footprints were all around. Now, I don't mind feeding the poor, but I don't take too kindly to thieves. After my crops had gone missing, I asked Brother Samuel if anything had happened in the graveyard. It was then that he told me that someone had begun to dig up some of the graves. Apparently whoever is doing this isn't strong enough to dig in one night. It's probably some old beggar hoping to dig up some treasure. If you ever find out who is doing this, please tell 'em them to stop by. There's no need for thievery here in Abbey and I would be happy to help this person in anyway I can.}
{606}{}{第二天我去田里查看，发现很多农作物被吃了，周围还有很多新的脚印。我不介意给穷人吃。不过我对小偷没什么好感。之后我的农作物又开始少了。我问塞缪尔修士墓地发生了什么。他说有人盗墓，而且不是一次了。如果查出是哪些人做的，请你告诉他们停住吧。我很乐意帮肋这些人如果我能帮到他们的话。}
#{607}{}{I'll try and catch this individual. Maybe I'll wait around midnight and see if I can find anything out. Well,thanks for the information. Take care.}
{607}{}{我会试着找出这些人的。也许我夜晚在那周围等着就能找到一些东西了。好的，谢谢这些消息。保重。}
{608}{}{我会看看我能做点什么。走之前我还有一些问题。}
{609}{}{这故事真是有一点长。再见。}