#ipisgfx译
{100}{}{你看见一个抽水泵。}
{101}{}{你看见一个相当老的抽水泵而且看上去坏了。}
{102}{}{这个抽水泵又正常工作了。}
{103}{}{除了你的手你还需要更多东西来修理这个机器。或许一些工具能帮你把这个部件装上。}
{104}{}{你修好了这个抽水泵。}
{105}{}{你修理抽水泵没有成功。}
{106}{}{你找到了抽水泵出什么什么问题。}

{200}{}{你打了这个机器查看了里面。你看见很多生锈的齿轮和发动机。其中一个发动机上有裂缝。}
{201}{}{收工。}
{202}{}{再研究一下。}
#{203}{}{Upon closer inspection you see that the crack is not the cause of the trouble, but rather　the connection for where the wires go. The connectors seem to have burned out over the years of use. It's going to　take a whole new motor as well as a new set of wires to get this machine working again.}
{203}{}{靠近观察后你发现那个裂缝不是导致问题的原因。更确切的是那些连接器导致的。这些连接器经过多年已经烧焦了。是时候换个新的发动机和换上新的连接器让机器再次工作了。}
{204}{}{退出。}


