#ipsigfx译
{100}{}{你看见一个墓地管理员。}
{101}{}{你看见塞缪尔修士，墓地管理员。}
{102}{}{他看上去喝高了，且昏昏欲睡的。}

#{200}{}{*hickup* Why, 'ello there my name's Samuel. What, uh, *hickup* brings you here?}
{200}{}{*摇摇晃晃* 什么，（唲~）我的名字是塞缪尔，什么（唲~）风把你带到这来了？}
{201}{}{*摇摇晃晃*嗨又见面了。}
#{202}{}{I'm just looking around. Do you tend to this graveyard?}
{202}{}{我是到处走走。你在管理这个墓地。}
#{203}{}{Do you know a Father Tully?}
{203}{}{你认识塔里神父吗？}
#{204}{}{Father Tully, you say? (He appears to be racking his brain trying to remember)Yeah...I *hickup* remember Tully. How is that fella doin anyway? I haven't seen him since he was kicked out of here many years ago. Boy he was a hoot. Him and me together, *hickup* what a combo.}
{204}{}{塔里神父，你说？ (他开始敲打他的头试着想起什么)对...我 *摇摇晃晃*记得塔里。 那伙计做了什么？从他被这踢出去很多年我都没见过他了。小子他是一个古怪的人。他和我一类的。*摇摇晃晃*多么好的一个团队。}
#{205}{}{He lives in New Reno now. You know, you both seem a lot a like.}
{205}{}{他现在住在新里诺。你知道的。你俩真的很象。}
#{206}{}{New Reno, huh? (He leans on his shovel, pulls out a small flask and takes a big swig) I remember him sayin he would *hickup* be headin that way. I'm  glad he made it there safely. I always *hickup* liked that fella.If you see him again tell him Ol' Sammy is still alve an' kickin.}
{206}{}{新里诺, 哼？ (他靠着他的铲子，拿出一个小瓶大口喝了几口) 我记他说他会*摇摇晃晃*朝那去的。我很高兴他在那很安全。我一直*摇摇晃晃*都很喜欢那伙计。如果你再见到他告诉他塞缪尔仍然活的好着呢。}
{207}{}{我会的。我还有一些别的问题。}
{208}{}{我会的。保重塞缪尔}
{209}{}{别介意。对不起打扰你。}
{210}{}{实际上我只是来替他问声好的。我也会帮你向他问好的。我还有一些别的问题。}
{211}{}{实际上我只是来替他问声好的。我也会帮你向他问好的。保重塞缪尔。}

#{300}{}{What do you *hickup* want to know?}
{300}{}{你他知道什么？*摇摇晃晃*}

{301}{}{你是管理员？}
{302}{}{关于阿比你能告诉我什么？}
{303}{}{我能帮你什么事吗？}

#are you the keeper here?
#{400}{}{Yes, *hickup* I tend to these here graves. Nobody else wants to *hickup* do it, so Ol' Sammy got th' job.It's not as bad as one might think.}
{400}{}{是的，*摇摇晃晃* 我管理这些墓地。没人想干这个，所以塞缪尔接了这个工作。也不是想象的这么差。}
{401}{}{明白了，我还有一些别的问题。}
{402}{}{明白了。好的再见了。}

#Tell me about abbey
#{500}{}{Abbey, well this place *hickup* has been my home fer most of my life. Everyone here *hickup* is very nice to
 each other and anyone is welcome as long as they *hickup* don't cause any trouble. I myself, don't spend
 too much time in th' monastery *hickup* but I know that our computers have all kinds of information that has been collected
 over th' years. Maybe some of it *hickup* might be of some use to you.}
{500}{}{阿比，好吧，*摇摇晃晃*这是我一生中大部分的家。所有人在这都很友善，还有只要不搞乱我们欢迎任何人。我自己不会花太多时间在修道院*摇摇晃晃*不过我知道我的电脑里有所有种类的信息，收集这些有很多年了。也许有一些对你有会很有用。}

#{501}{}{You don't spend much time in the church? You are a monk aren't you?}
{501}{}{你不会花太多时间在教堂？你是个修士，不是吗？}
#{502}{}{(He grins and you can see that several of his teeth have fallen out over the years) Well, *hickup* let's just say that th' other monks don't take *hickup* too kindly to my, uh, drinking habits.}
{502}{}{(他大笑，你能看见他的几颗牙齿已经掉了很多年了) 是的，*摇摇晃晃*让我告诉你其他的修士对我不是很友善，噢，*摇摇晃晃*是对我喝酒的习惯。}
{503}{}{我感觉出来了。我还有一些问题。}
{504}{}{我猜也是。回见塞缪尔。}
{505}{}{我知了，我得走了。}

#Need any help
#{600}{}{Hmm...well *hickup* let me think a minute. Yeah, I might got something if you are up to it.}
{600}{}{呖...好的*摇摇晃晃*让我想想。对了，我确实有些事如果你想帮忙的话。}
{601}{}{噢，别介意。我得走了。}
{602}{}{当然，塞缪尔，你需要什么?}
#{603}{}{Well, th' past coupla days I've *hickup* noticed that some of these graves here are bein dug up.Now whoever is doin this doesn't appear to be gettin that far but it is a *hickup* pain fer me
 to fill 'em back up.}
{603}{}{好的，几天前，*摇摇晃晃*我注意到有些墓地被人挖过。不知是谁干的。这对使我很痛苦。*摇摇晃晃*　每次我都要把他们给填回去。真是很烦人。}
#{604}{}{Hmm, well did you try and figure out who has been doing this?}
{604}{}{嗯，那么你有没有试着找着谁做了这事？}
#{605}{}{Sure *hickup* I tried. One night I stayed around till midnight or so and no one showed up. I must have fallen asleep soon afterwards.Too much drinking I s'pose. (He grins, pulls out his flask and takes a hefty swig.) So, what do you *hickup* say, you want to help out?}
{605}{}{当然，*摇摇晃晃*我试过了。一天晚上我在这等到了午夜，但是没什么现象发生，然后我就倒下睡着了，可能喝太多了。 (他大笑，拿出瓶子接着喝) 所以说你想帮忙找出这些人吗？}
#{606}{}{Alright, I'll see what I can do. Do you know anything else that might help me?}
{606}{}{好吧，我看我能做点什么。你还知道什么能帮我的？}
#{607}{}{Well, now that you mention it, I do *hickup* remember Mr. Peterson sayin something about hearing some noises comin from his field. He might know something about this. He and his wife can be found in that house over there. (He points to the building to the right of the graveyard.)}
{607}{}{好的，你现在提起这个。*摇摇晃晃*　我记得彼得斯先生说过听到一些声音在他的田里。他可能知道一些事。你在下面那个房子里能找到他和他的妻子。(他指着墓地右边的一个建筑)}
{608}{}{我会看看我能做点什么。}
{609}{}{我想我只是经过。我得走了。}

#{700}{}{I took care of the grave digging situation. You should not have any more problems out here.}
{700}{}{我会查看一下墓地被挖的位置，你确定那没别的问题了？}
#{701}{}{Well, that's *hickup* good news. Glad I won't be falling into any more open *hickup* graves. Thanks fer th' help.}
{701}{}{很好，*摇摇晃晃*那真是好消息。很高兴我不会再掉进任何被挖开的墓里了。谢谢帮忙。}
#{702}{}{Glad to help. I got some questions though.}
{702}{}{乐意帮你。我还有一些问题。}
{703}{}{好的，保重。}
#{704}{}{I don't think open graves are the real reason you're falling down Samuel, but you take it easy now.}
{704}{}{我不认为挖开的墓地是你摔倒的原因塞缪尔。不过你现在可以放心了。}

{1000}{}{*吹口哨*}
{1001}{}{*咳嗽* *咳嗽*}
{1002}{}{*清嗓*}
{1003}{}{*咳嗽*}
{1004}{}{*叹气*}
{1005}{}{*摇摇晃晃*}

#{2000}{}{It's been a *hickup* long day. Come back in th' morning.}
{2000}{}{真是满长的一天。*摇摇晃晃*早上再来。}