#ipisgfx译
{100}{}{你看见卢卡斯。}
{101}{}{卢卡斯是你部落的酋长。}
{102}{}{原来是你，获选者。呵！你的任务怎么样了？}
{103}{}{还不错。}
{104}{}{不是很好。}
{105}{}{啊？！}
{106}{}{我得走了。}
{107}{}{也许你需要一个战士的帮助。}
{108}{}{当然，你能帮我点什么？}
{109}{}{不了，我做的很好。}
{110}{}{回答的好，别说话，安静看我做。}
{111}{}{嗯－好的。}
{112}{}{我知道怎么用拳腿战斗。我认为这对你有些帮助。}
{113}{}{你能教我什么？}
{114}{}{风会指引你的道路，获选者。}
{115}{}{再见。}
{116}{}{呵--花一天时间我会告诉你一切的。}
{117}{}{好的，就这样吧。}
{118}{}{报歉，现在没时间做这个。}
{119}{}{你已经学会了我所能教你的全部，获选者。祝你好运！}
{120}{}{噢，好的。}
{121}{}{嗨！获选者。你的动作不够优美，要像教你那样。}
{122}{}{噢，好的。}
{123}{}{你的动作不够快，我的训练会帮助你的，获选者。}
{124}{}{噢，好的。}
{125}{}{在我教你之前你得在多练习一下，小兄弟。}
{126}{}{噢，好的。}
{127}{}{我能教你怎么踢碎岩石。那要花一天时间才能告诉你其中的诀窍。}
{128}{}{好的。}
{129}{}{我能完善你战斗中的不同。那需要一天时间。}
{130}{}{好的。}
{131}{}{你学的不错，获选者。风会指引你的道路。}
{132}{}{谢谢你的帮助。}
{133}{}{我已经把所会的都教给了你，获选者。祝你好运！}