{100}{}{你看到一个刚斯的歹徒。}
{101}{}{你看到一个刚斯的歹徒。}
{102}{}{你看到一个穿着护甲的壮丁，手上拿着武器，而且脾气看起来很不好。他一定是刚斯的一员。}
#node1
{103}{}{你．．我不认为我认识你。你操他妈的是谁？}
#responses 1
{104}{}{我的证件在这里！让我给你看。}
{105}{}{名字是嗯．．派特。我是新来的。}
#edit below by killap - was 110
{110}{}{死！}

#node 2
{106}{}{好吧，笨蛋；使出你的全力吧。}

#node 3
#made skill check
{107}{}{喔－对；抱歉，我一开始没有认出你来，继续吧。}
{108}{}{嘿，我并没有像你想的那么笨。}

#node 4
{109}{}{你还没死咧，狗屎。}

#idle talking messages
#BLOCK 1
{110}{}{天，达里安并没有付我足够的钱。}
{111}{}{有时候我会坐下，然后什么都不想。}
{112}{}{我一般的时候都不会关心别人在想什么的。}
{113}{}{不要管别人的闲事．．是安全的。}
{114}{}{下一个商队什么时候会经过呢？}
{115}{}{我需要休息一下。}

#BLOCK 2
{116}{}{可恶，那婊子可莉西踢我一脚，到现在还在痛咧。}
{117}{}{嘿，我们从来都没有得到新血。}
{118}{}{我们什么时候才能离开这一个讨厌的地方呢？}
{119}{}{我不知道你是怎么想的，但是我认为这个地方很烂。}
{120}{}{这附近都没什么可以杀的。}
{121}{}{厕所在那里？}

#BLOCK 3
{122}{}{嘿，我们从来都没有休息时间。难道这边没有劳基法吗？}
{123}{}{我们应该要跟以前一样有个政府。}
{124}{}{真不知道身为一个古代的总统会是怎样的感觉。}
{125}{}{我猜如果你是总统的话，你就可以做自己想要做的事。}
{126}{}{我想我爸会为我感到骄傲的；只可惜我把他给杀了。}
{127}{}{我恨老鼠，恨恨恨！}

#BLOCK 4
{128}{}{嘿，你身上穿的是新的护甲吗？}
{129}{}{这个避难所好臭；你不讨厌它吗？}
{130}{}{嘿，那个我们该小心的人是谁啊？}
{131}{}{我整天做的事就是站在这边。}
{132}{}{我觉得我们应该要把楼上的人都给杀了。}
{133}{}{那些老鼠到底是怎么回事？}

#BLOCK 5
{134}{}{你有没有将老鼠的一条腿活活的拔下来过？}
{135}{}{我喜欢枪，耶！枪是我的最爱！枪；我真的真的很喜欢它们！}
{136}{}{嘿，有人在听我说话吗？}
{137}{}{喔，我只是跟自己说话而已，不然我会发疯的。}
{138}{}{嘿，有人知道热狗到底是用什么肉做的呢？}
{139}{}{是狗肉、海龟肉、松鼠肉、臭鼬肉、还有马肉。}

#Lights on
{140}{}{嘿，听着－－灯亮了，怎么．．}
{141}{}{达里安说他会把那可恨的灯给修好。我想他真的修了。}
{142}{}{我不认为那发电机会自我修好，对不对？}
{143}{}{那真是奇怪；现在我可以看到了，天啊，这个地方看起来真糟！}
{144}{}{哇，这里面好亮啊。亮度控制在那里？}
