{100}{}{你看见一位流浪汉。}
{101}{}{你看见了流浪汉约翰。}
{102}{}{你看见一位穿着破旧衣服的中年人。}
{103}{}{对不起．我没有时间跟陌生人谈话。}
{104}{}{为什么不谈话？}
{105}{}{很好。}
{106}{}{好吧，再见。}
{107}{}{等一下，可以跟我谈话吗？}
{108}{}{我们是一群保守的人。我们不希望接触到外界来的人。所以请你离开这里。}
{109}{}{好。}
{110}{}{你好，再见。}
{111}{}{谢谢你的帮助，同时我很抱歉我刚刚的坏态度。}
{112}{}{去死吧，你这个屁眼。}

{113}{}{浑帐，我最讨厌这个情况了。}
{114}{}{去死吧，哈，知道我多厉害了吧。}