{100}{}{你看到一个矮子手里拿着一本书。}
{101}{}{你看到琼斯医生。}
{102}{}{你看到一个矮子手里拿着一本书，名字是“你想要成为一个医生吗？”}
{103}{}{你好，我是琼斯医生。我可以帮你吗？}
{104}{}{痛痛，治好？}
{105}{}{难过，治好？}
{106}{}{瘸了，治好？}
{107}{}{问题，好吗？}
{108}{}{抱歉，我走。}
{109}{}{受伤了，你可以帮我吗？}
{110}{}{我生病了，你可以帮我吗？}
{111}{}{我断肢了，你可以帮我吗？}
{112}{}{我想要问你一些问题。}
{113}{}{只是来说声好的。}
{114}{}{当然，让我帮你打一针这个－－这会有一点痛－－现在包扎－好了。}
{115}{}{谢谢，再见。}
{116}{}{谢谢你，我觉得好多了。}
{117}{}{当然，你需要喝这个－－全部。我知道很难喝。现在，躺下来休息吧，我早上会叫你的。}
{118}{}{我觉得舒服，再见。}
{119}{}{谢谢，我觉得好多了。}
{120}{}{我很抱歉，但是我这边没有设备可以进行手术。我劝你到一个大城市去就医。到地下掩体市去吧，它就在北方。}
{121}{}{好，再见。}
{122}{}{好，谢谢你。}
{123}{}{你想要知道什么？}
{124}{}{你帮达里安做事？}
{125}{}{你要离开就离开吗？}
{126}{}{有关达里安你知道什么？}
{127}{}{你怎会在这？}
{128}{}{你说达里安有条狗？}
{129}{}{我要走了。}
{130}{}{你是帮达里安做事的吗？}
{131}{}{你要离开随时可以离开吗？}
{132}{}{有关达里安你可以告诉我些什么？}
{133}{}{你是怎么会在这里的呢？}
{134}{}{你说达里安有条狗吗？}
{135}{}{谢谢你，我要走了。}
{136}{}{是也不是，那不是我选择的；我在这边是个犯人。达里安老了，因此他需要个固定的医生看他。刚斯的人把我困在这边看达里安，我宁可待在这帮村人治病。他们都没有医疗上的援助，因此我有很多地方可以帮助他们的。}
{137}{}{好，我需要知道更多的事。}
{138}{}{谢谢，再见。}
{139}{}{你真是一个好人啊。}
{140}{}{我知道了，我得要走了。}
{141}{}{他们是流浪汉啊！让他们死吧！}
{142}{}{不，我是被困在这边的。我连要补充药品他们都不让我离开这里。达里安会派人去帮我做我需要完成的事。}
{143}{}{我知道了，我走。}
{144}{}{我需要问更多。}
{145}{}{我想他们大概是不信任你，才不给你自由吧。}
{146}{}{好。我很抱歉，但是我要走了。}
{147}{}{我很抱歉听到那个消息。}
{148}{}{达里安是个疯子。我知道他是个叫刚斯帮派的人。他们绑架了个女孩坦蒂，并要求赎金。不过她爸爸并不吃这套，因此雇了佣兵去把她救回来。而达里安是那场大战中唯一逃出来的人。}
{149}{}{嗯．．你是说。}
{150}{}{要走了。}
{151}{}{我要走了。}
{152}{}{哇！你知道的还真不少。}
{153}{}{看来这人还不错。}
{154}{}{我是被绑架的。我原本从地下掩体市旅行到新里诺去渡假。有一天，睡醒后就被绑了起来。一星期后，我就身在这里了。}
{155}{}{嗯。}
{156}{}{谢谢，我要走了。}
{157}{}{弱肉强食。}
{158}{}{我很抱歉听到此事。}
{159}{}{很有趣，但是我要走了。}
{160}{}{是的，他有条狗。我不认为他的狗很凶。它看起来很喜欢达里安。}
{162}{}{再见。}
{163}{}{我知道了。}
{164}{}{我要走了。}
{165}{}{我不要帮助像你这样的人，走开。}
{166}{}{祝你好运，如果有需要就回来找我吧。}
{167}{}{完成。}

{168}{}{他现在很神经质，一直认为坦蒂想抓他。他对复仇相当执着，他想要坦蒂的命。}