{100}{}{你看到一个刚斯的歹徒。}
{101}{}{你看到费尔，一个刚斯的卫兵。}
{102}{}{你看到一个很壮的年青人，穿着铁装甲。他看起来有很强的火力。}
{103}{}{我应该把你杀了，但是我很好奇你会跟我说什么。}
{104}{}{我在找间谍，走到这边来。}
{105}{}{我在找失踪的女孩，你知道在那吗？}
{106}{}{我不小心闯进来的，现在就走。}
{107}{}{去你的，我杀死你。}
{108}{}{我们可以好好谈吗？}
{109}{}{我正在找一个间谍，他往这个方向来了。}
{110}{}{我在找一个失踪的女孩，有看到他吗？}
{111}{}{抱歉，我走错路了。我要走了。}
{112}{}{去你妈的，吃我的子弹吧。}
{113}{}{我想我们应该要像两个文明人一样安静的解决这个问题。}
{114}{}{嗯，那就是我。现在你找到我了，那又怎样呢？}
{115}{}{为什么你偷听丽蓓嘉说话？}
{116}{}{我现在知道不会杀错人了。谢谢！}
{117}{}{没事，我要走了。}
{118}{}{为什么你刚刚去偷听丽蓓嘉说话？}
{119}{}{我只是不想杀错人而已，谢谢，祝你一天美好！}
{120}{}{嗯。没事。我想我要走了。}
{121}{}{我真不敢相信你敢闯进这边来，然后以为可以取得答案！反正你就快死了，告诉你也无妨。我们把她的小孩关在后面房间里，并且跟她玩了好久。那婊子丽蓓嘉一直都想要找她，不过丽蓓嘉永远也找不到她的。}
{122}{}{你这变态，我要把你的心挖出来看看。}
{123}{}{跟她玩玩，什么意思？}
{124}{}{喔，是这样啊。我要走了。}
{125}{}{你真是变态啊！我看我得要把你给杀了。}
{126}{}{好，祝你玩的开心，我要走了。}
{127}{}{把女孩交出来我就饶你一命。}
{128}{}{在你死时好好的想想吧，笨猪。}
{129}{}{}
{130}{}{}
{131}{}{为什么我要那样做呢？}
{132}{}{那样你以后才不会下地狱。}
{133}{}{因为我将是你最可怕的恶梦。把她交出来，不然我就让你求生不得、求死不能。}
{134}{}{因为如果我们战斗，我们其中一个一定会死。我跟你没有一个人想死，因此让我们平静的解决这件事，好吗？}
{135}{}{去你的。}
{136}{}{}
{137}{}{}
{138}{}{那听起来像是一个挑战，我接受。}
{139}{}{}
{140}{}{}
{141}{}{嗯．．我．．喔，好，这是她牢房的钥匙，她在后面房间中。去把她带走，然后不要再回来，不然我们就得斗个你死我活了。}
{142}{}{让我们看看谁最后会活着。}
{143}{}{谢谢，你做的事是对的。}
{144}{}{你唯一能够离开这里的方法就是躺着出去。}
{145}{}{}
{146}{}{}
{147}{}{你是说那被我们玩过，被锁在后面房间里的那个女孩？没有，我没有看过她？}
{148}{}{你这变态！我要把你的心挖出来看看。}
{149}{}{跟她玩玩？什么意思？}
{150}{}{喔，是这样吧。我要走了。}
{151}{}{你真是变态啊，我看得要把你给杀了。}
{152}{}{很好，祝你玩的开心，我要走了。}
{153}{}{把女孩交出来我就饶你一命。}

{154}{}{你回来了，让我们看看谁能活着出去吧。}
{155}{}{我们把那婊子可莉西杀了，现在你也得死了！}