{100}{}{你看见了一个卫兵。}
{101}{}{你看见了一个穿着战斗装甲的卫兵。}
{102}{}{你看见了一个穿着战斗装甲的人，他胸前有一个你不认得的标志。}

{103}{}{没有异状可以报告。}
{104}{}{这里没有事发生，你那边呢？}
{105}{}{你不是应该在站岗吗，士兵？到处乱逛是不好的。}

{106}{}{你没有穿制服。}
{107}{}{你最好赶快到长官那边去领制服。}
{108}{}{你真大胆敢不穿制服。你最好到供应室去报到。}

{109}{}{你们他妈的是谁？士兵！有侵略者！}
{110}{}{我们被侵略了！启动警报！}
{111}{}{有许多的侵略者！启动警报！}

{112}{}{安全警报！封锁基地！}
{113}{}{保护所有的地区！我们正在警报中。}
{114}{}{侵略者警报！启动红色警报！}

{115}{}{我们会把你们给杀死的！}
{116}{}{英克雷军将会统治世界的！}
{117}{}{你们的死亡将会让英克雷军万古长存的！}