{100}{}{你看到一个穿着动力装甲的人。}
{101}{}{你看到一个后勤军官。}
{102}{}{你看到一个穿着设计相当不寻常装甲的人。在胸部上有一个你不熟悉的标志。}
{103}{}{你们他们的是什么人．．警报！有入侵者！}
{104}{}{我知道你为什么在这里，因为你要弄掉你们身上穿的那个古董。}
{105}{}{你为什么没有穿着制服？}
{106}{}{死来！}
{107}{}{嗯，是．．}
{108}{}{嗯．．}
{109}{}{我新来的。}
{110}{}{我不是你们的一员！}
{111}{}{嗯，那．．}
{112}{}{我是新来的。}
{113}{}{我不是你们其中的一员！}
{114}{}{什么？想不出一个好理由吗？我还在等你的答案呢！}
{115}{}{我还没有制服。}
{116}{}{我还没有拿到制服。}
{117}{}{你反应很慢，对不对？唉，那不是你的错。我有一个弟弟就像你一样。你是新来的吗？我以前没有看过你。}
{118}{}{你是新来的吗？我以前没有看过你。}
{119}{}{是的！我是新人！}
{120}{}{是的，我是新来的。}
{121}{}{那你得要去领你的配备。到军火库去领取所需要的东西。在那之后你应该要到上士那边去报告。}
{122}{}{谢谢！}
{123}{}{不用客气，快去吧。我还有工作要做，不要打扰我了。}
{124}{}{我现在很忙，等一下再回来吧。}
{125}{}{你好，新人。我刚刚才收到你上士的一通电话。他说叫我把你穿好制服之后，然后再叫你回去找他。}
{126}{}{是。}
{127}{}{这个基地现在正在警报中，而且我没有见过你。让我看看你的证件，士兵。}
{128}{}{我没带。}
{129}{}{我不需要证件！}
{130}{}{我忘了带；它在我的锁柜里面。}
{131}{}{证件？就在这里！}
{132}{}{你应该要随时的带着证件的！你应该知道那是规则的！}
{133}{}{完成}
