{100}{}{你看到一个鬼！}
{101}{}{你看到鬼魂安娜。}

{150}{}{这是一个鬼，不是你日常可以见到的东西。}
{151}{}{她看起来相当的痛苦。}
{152}{}{[谈话]}
{153}{}{好痛！好热！}
{154}{}{怎么了？}
{155}{}{你是谁？}
{156}{}{滚，邪恶的鬼魂！}
{157}{}{我停下来敲每一个人的门，但是没有人出来，也没有人听见。}
{158}{}{我可以听见你，发生什么事了？}
{159}{}{我想你得要将你的隐形装置关起来，夫人。}
{160}{}{在那里？我找不到！我迷失了！喔．．}
{161}{}{你在找什么？也许我能帮忙。}
{162}{}{你得要停止哀号，并且把话说清楚。}
{163}{}{我的项链！不见了！被偷了！被偷了！}
{164}{}{喔，我才刚刚到这边。不是我干的。}
{165}{}{我可以帮你找到它吗？}
{166}{}{啊，残酷的命运．．}
{167}{}{你听不到我，对不对？}
{168}{}{再见，女鬼。}
{169}{}{再见，我会尽力帮你的。}
{170}{}{我的项链！还我！！喔！！！}
{171}{}{不行！这是我找到的。}
{172}{}{好吧，拿去。}
{173}{}{拿去，希望你安息吧。}
{174}{}{好吧。}
{175}{}{不！}
{176}{}{我的项链，我的项链！我来了，爸爸！我来了！}
{177}{}{再见。}
{178}{}{等一下！不要走！}
{179}{}{走向光明吧！}

{200}{}{它会在那里呢？}
{201}{}{喔。}
{202}{}{妈妈？爸爸？你们在你里？}
{203}{}{我找不到它！}

{500}{}{妈妈．．爸爸．．我来了．．}
{501}{}{好亮啊．．}
{502}{}{祖母，我见到你了．．}
{503}{}{啊，是善良的肯恩先生．．真高兴再见到你．．}

{550}{}{这间房是空的。}
# {551}{}{Oog, pretti bones.}
{551}{}{啊~~相当不错的骨头。}
{560}{}{钟馗！}
{561}{}{嗯。}
