#ipisgfx译
#You see a drug dealer.
{100}{}{你看见一个毒贩子。}
{101}{}{你看见一个毒贩子。}
#If you are looking to deal, I got the stuff.
{102}{}{如果你在寻找某种交易的话，我这有料。}
#Sure, show me.
{103}{}{当然，给我看看。}
#Maybe some other time.
{104}{}{也许下次吧。}
#Find what you need?
{105}{}{找到你需的东西了吗？}
#Thanks. Goodbye.
{106}{}{谢谢，再见。}

#You see a thug.
{200}{}{你看见一个暴徒。}
{201}{}{你看见一个暴徒。}
#I'm here for protection. Talk to the dealer if you wanna buy.
{202}{}{别烦我！！！想买东西和他谈谈。}