#ipisgfx译
{100}{}{你看见一个暴徒。}
#He's Tyler's friend.
{101}{}{他是泰勒的肋手。}

#You here to party?
{110}{}{你来这是来参加派队的？}
#*hickup* Brews on me!
{111}{}{*摇摇晃晃* 给我倒上一杯！}
#Hooker's in the back if you want a ride.大概是这样译。。。
{112}{}{如果你想操婊子，在后面。}

#Nobody fucks up a party when I am around.
{120}{}{有我在没人能搞砸这个派队。}

#{130}{}{We showed those fuckers...Ruining *hickup* a good party and all.}
{130}{}{我们让这些笨蛋...毁了*摇摇晃晃*一个美好的派队。}