##ipisgfx译
{100}{}{你看见一个丹恩城的居民。}
{101}{}{你看见一个丹恩城的居民。}

#Hello and welcome to- Hey! You're the one who helped make this place possible. The people of the Den really appreciate
 what you have done.
{200}{}{你好欢迎~ 你就是让这变成可能的人。丹恩的人们都很感谢你所做的一切。}
#It was my pleasure. How are the children?
{201}{}{是我的荣幸。孩子们还好吗？}
#They are doing fine. Thanks to you they are off the streets and now have a place to live. The squatters you negotiated with
 are also a big help around here. Thanks again for everything!
{202}{}{他们很好。谢谢你让他们远离街头而且还有了住处。流浪者在你的协商下对这也有很大的帮助。再次感谢你做的一切！}
#They are doing fine. Thanks to you they are off the streets and now have a place to live. Thanks again for everything!
{203}{}{他们很好。谢谢你让他们远离街头而且还有了住处。再次感谢你做的一切！}
#Glad to hear it. Well, take care.
{204}{}{很高兴听到这些。很好，保重。}
#Hello again! Help you with something?
{205}{}{你好又见面了！有什么要帮忙的吗？}
#Nope, just looking around.
{206}{}{没什么，只是到处看看。}