#ipisgfx译
#You see a resident of The Den.
{100}{}{你看见一个丹恩城的居民。}
{101}{}{你看见一个丹恩城的居民。}
{102}{}{你好}
{103}{}{很高兴见到你。}
#Not from around here are you?
{104}{}{你不是本地人吧？}
#Mom is a great lady isn't she?
{105}{}{妈妈桑是一个伟大的女士，不是吗？}
#I'm glad the orphans of The Den have a place to live now.
{106}{}{我很高兴丹恩城有一个孤儿可以住的地方了。}

{400}{}{你看见一个小男孩。}
{401}{}{你看见一个小女孩。}

{200}{}{你好先生！}
#I'm glad the other kids aren't stealing anymore.
{201}{}{我很高兴孩子们不再偷别人的东西了。}

{300}{}{你好小姐！}
{301}{}{我很高兴孩子们不再偷别人的东西了。}