#############################################################
#                                                           #
#  Message File: dcPetey.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 12, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and examined.                                    #
#############################################################

{100}{}{你看见一个瘾君子。}
{101}{}{你看见彼特。}

{150}{}{这是个可怜的瘾君子。}
{151}{}{彼特看起来好像很需要别人帮助他。}
{152}{}{[谈话]}
{155}{}{[咳、咳] 有零钱可以施舍给彼特吗？}
{156}{}{当然，拿去吧。}
{157}{}{没有，滚蛋。}
{158}{}{彼大．．？}
{159}{}{你比我还糟。 [咳] 总之谢谢。}
{160}{}{抱歉，再见。}
{161}{}{不客气。}
{162}{}{下次好了，无论如何，谢谢了。[咳]}
{163}{}{[完成]}
{164}{}{非常的谢谢你[咳] 非常...非常...}
{165}{}{不客气。}
{166}{}{是，是。}
{167}{}{先生，[咳] 请问你可以帮助我这个可怜人吗？}
{168}{}{给你 $5.}
{169}{}{今天我不想要帮助别人。}
{170}{}{去找个工作吧，不要整天乞讨。}
{171}{}{好心的小姐，请帮帮[咳] 我这一个可怜人吧。}
{172}{}{你真可怜，给你 $5.}
{173}{}{我从来都不给要饭的钱的。}
{174}{}{不。}
{175}{}{报歉，我没钱。}

{200}{}{嘿，可以给我一些钱吗？}
{201}{}{可以施舍点钱吗？}
{202}{}{可以帮帮我吗？}
{203}{}{施舍点钱吧！}
{204}{}{行行好吧，给点钱吧！}
{205}{}{能给点钱吗？}
{206}{}{嘿，可以给我一些钱吗？}

{220}{}{请帮帮我。先生。}
{221}{}{啊, 好疼啊。}
{222}{}{我需要帮助，我伤的很重。}
{223}{}{小姐，能帮帮我吗？}

{225}{}{非常感谢！}
{226}{}{嘿！你以为你在做什么啊？}

{230}{}{感觉好舒服啊。}
{231}{}{嗯...}
{232}{}{[呵呵呵]}
{233}{}{嗨...}
{234}{}{太－太好了...}
{235}{}{喔也...}

#dealer dead messages
#tubby dead
{300}{}{嘿，谁他妈的杀了塔比？}
{301}{}{塔比发生什么事了？}
{302}{}{妈的，塔比他．．.}
#generic
{303}{}{啊...}
{304}{}{反正我也不喜欢他那混蛋。}
#flick dead
{305}{}{富力克死了？可恨！}
{306}{}{富力克发生什么事了？}
{307}{}{我想念富力克...}

#dealer far, ask for assistance
#ask tubby
{310}{}{嘿，塔比．．我需要一些帮助。}
{311}{}{嘿，塔比！}
#ask any
{312}{}{你好！}
{313}{}{嗨！}
#ask flick
{314}{}{嘿，富力克，我需要一些帮助。}
{315}{}{嘿，富力克！}

#ask dealer for drug messages
#from tubby
{320}{}{嘿，塔比，你能够帮我弄到一些货吗？我有钱的。}
{321}{}{嗯，塔比，我有一些钱。}
#from any
{322}{}{啊...}
{323}{}{我需要一些毒品...}
#from flick
{324}{}{嘿，富力克，你能够帮我弄到一些货吗？我有钱的。}
{325}{}{嗯，富力克，我有一些钱。}
#thank dealer for drugs messages
#thank tubby
{330}{}{嗯．．再次的谢谢你，塔比。}
{331}{}{你真是够朋友，塔比。}
#thank generic
{332}{}{我保证，明天就给你。}
{333}{}{你真够朋友。}
#thank flick
{334}{}{嗯．．再次的谢谢你，富力克。}
{335}{}{你真够朋友，富力克。}
#response from Tubby/Flick
{340}{}{来吧，开打吧。你这个瘾君子。}
{341}{}{拿去滚吧。}