# 0. Look Primitive
{100}{}{你看到一个很大的男人。}
{125}{}{他身上到处都是伤痕。}

{150}{}{你看到一个女人。}
{175}{}{她看起来好像被打了一顿一样。}

# 1. Look Nomad
{200}{}{你看到一个男人。}
{225}{}{他看起来好像不是很健康。}

{250}{}{你看到一个女人。}
{275}{}{她身体很脏，并且显出营养不良的样子。}

# 2. CF: Freed
{300}{}{不要伤我，求求你！}
{301}{}{我们可以走了？}
{302}{}{不说话，一定要走。}
{303}{}{谢谢你帮我们。}
{304}{}{非常的谢谢你！}
{305}{}{你真是一个圣人。}
{306}{}{你在干什么？我们应该走了。}
{307}{}{请帮助我们逃跑。}

# 3. CF: PC is Slaver
{320}{}{你坏！}
{321}{}{我们不跟你说话。}
{322}{}{我们要自由。}
{323}{}{你不能抓我们。}
{324}{}{你奴隶贩子！}
{325}{}{你们奴隶贩子为什么要这样？}
{326}{}{你怎可帮这些人工作？}
{327}{}{我们也是人！}
{328}{}{你没有人性吗？}
{329}{}{我们会发生什么事？}
{330}{}{我们做错了什么？}
{331}{}{离开我们，奴隶贩子！}
{332}{}{不要伤我们！}
{333}{}{离我们远一点！}

# 4. CF: PC is Not Slaver
{350}{}{你是谁？}
{351}{}{你不是奴隶贩子。}
{352}{}{你不会伤我？}
{353}{}{朋友？}
{354}{}{你帮我？}
{355}{}{我们会发生什么事？}
{356}{}{你也被抓了？}
{357}{}{我们不是土人！}
{358}{}{这些人以为他们是谁？}
{359}{}{请救我们！}
{360}{}{把我从这弄出去。}

# 5. BGF: Not Free
{380}{}{你不能关我们在这！}
{381}{}{不对！}
{382}{}{我们不坏！}
{383}{}{我们帮？}
{384}{}{放我们！}
{385}{}{不喜欢！}
{386}{}{坏地方。}
{387}{}{为什么坏人要这样？}
{388}{}{我们不是奴隶！}
{389}{}{我们没做错什么啊。}
{390}{}{让我走！}
{391}{}{发生什么事了？}
{392}{}{好大声？}
{393}{}{谁在打架？}
{394}{}{发生什么事？}
{395}{}{有事发生了吗？}
{396}{}{有谁来救救我们！}
{397}{}{嘿！没有人可以听到我们吗？}
{398}{}{这是不对的！}
{399}{}{我们什么都没做错啊！}
{400}{}{让我们离开这里！}
{401}{}{有人来放我们出去吗！}
{402}{}{我们做错了什么？}
{403}{}{我们什么都没做啊。}
{404}{}{我们为何会落此下场呢？}
{405}{}{那些混蛋！}
{406}{}{救我们！}
{407}{}{让我出去！}
{408}{}{我们不是奴隶！}
{409}{}{我们不是土人！让我们出去！}
{410}{}{发生什么事了？}
{411}{}{有人要来救我们吗？}
{412}{}{在这里！}
{413}{}{救命！不要离开我们！}
{414}{}{那些枪声是怎么回事？}
{415}{}{发生什么事了？}

# 7. BGF: Fleeing
{420}{}{啊！}
{421}{}{嗯！}
{422}{}{不要停！}
{423}{}{是！}
{424}{}{我离尽可能的离开这个地方。}
{425}{}{继续走！}
{426}{}{自由！终于自由了！}

# 8. Metzger is Dead (From Where to go)
{440}{}{那是什么枪声？你要干什么？}
{441}{}{嘿！那些枪声是怎么回事？奴隶贩子都死了吗？}
{442}{}{嘿！那些枪声是怎么回事？发生什么事了？}
{443}{}{那一定是麦塔则发出来的声音。}
{444}{}{喔，没事。只是过来干看而已。再见。}
{445}{}{你可以离开了。麦塔则死了。}
{446}{}{你自由了。}
{447}{}{朋友。他杀麦塔则。你可以走了。}
{448}{}{朋友。她杀麦塔则。你可以走了。}

# 9. Metzger is Dead (From 8)
{460}{}{他死了？我谢谢你！我们会快走的。再见，我的朋友。}
{461}{}{什么？麦塔则死了？喔，谢谢你！我们最好快离开，谢谢你。}
{462}{}{不用客气，赶快离开吧。}
{463}{}{保重。}
{464}{}{不要客气。}

{470}{}{等等，我多问一句。我正在找一个女孩，但是在这里没发现。你知道还有什么地方关着奴隶吗？}
{471}{}{这附近的一个大营地。（部落民指了指西南）2次月升月落的路程。}
{472}{}{从这里往西南方向走2天会有一个营地。我之前关在那里。}
{473}{}{谢谢，赶快离开吧。}
{474}{}{谢谢，保重。}

# 10. Metzger Dead, Next Times (From Where to go)
{480}{}{你要什么？}
{481}{}{你要干什么？}
{482}{}{喔，没事。}

# 11. Bullet (From 8)
{500}{}{嗯？}
{501}{}{算了，你可以走了。麦塔则死了。}

# 12. You Free (From 8)
{510}{}{自由了？坏人没了？我们现在走！谢谢你。你是朋友！再见！}
{511}{}{自由？什么？你杀了他们？谢谢你！我们最好快走。谢谢你。}

# 13. NPC Sold to Slavery (From WTG)
{520}{}{去死吧！}
{521}{}{下地狱吧！}
{522}{}{你会付出代价的。}
{523}{}{你还敢跟我说话啊？}
{524}{}{不要烦我。}
{525}{}{我不要跟你说话。}
{526}{}{你怎能这样？！}
{527}{}{我再也不要看到你了。}
{528}{}{这将不会改变任何事的。}
{529}{}{如果你不介意的话，我要走了。}
{530}{}{求求你不要烦我们。}
{531}{}{就让我上路吧。}
{532}{}{我还是不要跟你说话。}
{533}{}{不要烦我。}
{534}{}{别想。}
{535}{}{你以为这会让情况变得很好吗？}

# 6. BGF: Just Freed
{600}{}{我们走？}
{601}{}{不伤我们？}
{602}{}{走！}
{603}{}{回家！}
{604}{}{自由了？}
{605}{}{嗯？}
{606}{}{什么？}
{607}{}{你说我们自由了？}
{608}{}{我要离开这了！}
{609}{}{我们走吧！}
{610}{}{大家！我们自由了！}
{611}{}{哈哈！！}

{700}{}{你将奴隶们从牢中放出来了。}
