#############################################################
#  Message File: diDiary.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: January 13,1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################
#ipisgfx译
#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

{100}{}{你看见一本很老旧的日记了。}
#{101}{}{It appears to be a diary which belonged to a young girl. The writing on the inside cover says: "Property of Anna"
 Most of the pages are either torn or faded, but one is still readable. "Day 271: Today my mother gave me a gold locket.
 It is the most beautiful thing I have ever owned. I will never part with it."}
{101}{}{看上去这本日记是一个小女孩的。里面写着：“安娜的财产” 很多页已经破了或是褪色 ，其中一页还可以看清。“271天：今天我妈妈给我后一个金制纪念品盒。这是我得到的最漂亮的东西。我会一直把他带在身上。”}
{102}{}{日记已经存在哔哔小子里面了。}