{100}{}{食物！}
{101}{}{给我们食物！}
{102}{}{我们饿死了！}
{103}{}{施舍一些钱给我们这些不幸的人吧。}
{104}{}{帮帮我们！}
{105}{}{食物！}
{106}{}{我好饿啊。}
{107}{}{我的孩子们都很饿。}
{108}{}{没有人关心我们。}
{109}{}{不要杀我！}
{110}{}{我只想要些吃的。}
{111}{}{原谅我。}
{112}{}{乞丐接受了这样物品。}