{100}{}{你看到一位晒黑瘦弱的女子。}
{101}{}{你见到一个农夫。}
{102}{}{你注意她有农夫一般黄褐色的皮肤。}

{200}{}{这是我家。}
{201}{}{可恶的土匪们。}
{202}{}{离开我们吧！}
{203}{}{我恨土匪。}
{204}{}{我们没有什么可以让你抢走的。}
{205}{}{不要杀我。}
{206}{}{我受够了。}
{207}{}{随便你要拿什么就拿什么吧。}
{208}{}{请饶我一命。}
{209}{}{反正我也不喜欢农耕生活。}
{210}{}{求求你不要将房子烧掉。}


{220}{}{别烦我。}

{230}{}{谢谢你帮忙我们。}
{231}{}{我希望世界上多有几个像你这样的人。}