#ipisgfx译
#You see a Mr. Handy Robot.
{100}{}{你看见一个家用机器人。}
#You see a seriously depressed Mr. Handy Robot.
{101}{}{你看见一个情绪低落的家用机器人。}
#This Mr. Handy Robot seems to be very depressed for some reason.
{102}{}{由于某种原因这个家用机器人看走来情绪很低落。}
#O woe is me!
{200}{}{噢，我真不幸。}
#Fed up...
{201}{}{别说了...}
{202}{}{我现在就想死去...}
{203}{}{请杀了我吧...}
{204}{}{所有人都走了...}
{205}{}{我应该做什么？}
{206}{}{无聊中...}
{207}{}{...呜咽中...}
#Life. Don't talk to me about life.
{208}{}{生命。别和我谈论生命。}
#I think you ought to know I'm feeling very depressed.
{209}{}{我想你应该知道我有多么的沮丧。}
#Pardon me for breathing, which I never do anyway so I don't know why I bother to say it, oh God, I'm so depressed.
{210}{}{让我喘口气，我无论如何都不清楚为何我不原提起这个。噢，上帝啊。我很难过。}

#Yeah, just push me over a cliff
{500}{}{是的，只用把我推下悬崖。}
{501}{}{***哔斯~住手！！ *** 哔斯 ***}