{100}{}{你看到一个相当友善的人。}
{101}{}{你看到马克。}
{102}{}{你看到一个相当友善的人。}
{103}{}{你这狗娘养的－你怎能这样对我们呢？}
{104}{}{我可以帮你吗？}
{105}{}{我可以帮你吗？}
{106}{}{喔！喔！啊！}
{107}{}{你是谁？}
{108}{}{这是什么地方？}
{109}{}{谁是这边的负责人？}
{110}{}{没事，再见。}
{111}{}{嗯。不，抱歉，不能够帮你。也许你应该去试试别人吧。}
{112}{}{嗯？}
{113}{}{我是马克。我是这边无所不知道人。 ::他微笑着::}
{114}{}{喔。我还有一些问题。}
{115}{}{再见。}
{116}{}{这是波斯当油轮，如果你想要知道更多的事，请跟船长谈。}
{117}{}{船长？那是谁啊？}
{118}{}{我还有一些问题。}
{119}{}{再见。}
{120}{}{负责人？这边没有负责人的。}
{121}{}{你们都是从那边来的？}
{122}{}{我还有其它的问题要问你。}
{123}{}{再见。}
{124}{}{船长是一个老军人。他对这一艘船有着相当的认识。}
{125}{}{谢谢，我还有更多的问题。}
{126}{}{谢谢。再见。}
{127}{}{喔，我们有些祖先在战争前就住在这里了。你想要知道更多吗？}
{128}{}{是的。}
{129}{}{不，但我想要问你一些其它的事。}
{130}{}{不，就这样。}
{131}{}{我们是一群音乐家，书虫，以及美术家。你还要继续听吗？}
{132}{}{是的。}
{133}{}{不，但我想要问你一些其它的事。}
{134}{}{不，就这样。}
{135}{}{当我们到这边时，我们就想要让这一艘船能够启动。}
{136}{}{你找出启动它的方法了吗？}
{137}{}{告诉我有关哈伯教的事。}
{138}{}{告诉我有关始族的事。}
{139}{}{我还有其它的问题。}
{140}{}{谢谢，再见。}
{141}{}{我想船长找到了方法－但是我们现在有其它的计划。}
{142}{}{是什么？}
{143}{}{我在那可以找到船长？}
{144}{}{我要问一些其它的事。}
{145}{}{再见。}
{146}{}{他们是疯子，不要信任他们－他们只对你的钱或生命有兴趣。他们会不择手段的拿到他们要的东西的。}
{147}{}{你找出启动油轮的方法了吗？}
{148}{}{告诉我有关始族的事。}
{149}{}{我还有其它的问题。}
{150}{}{谢谢，再见。}
{151}{}{他们还算不错。他们对外人不太信任，但是那并不是一件坏事啊。}
{152}{}{你找出启动油轮的方法了吗？}
{153}{}{告诉我有关哈伯教的事。}
{154}{}{我还有其它的问题。}
{155}{}{谢谢，再见。}
{156}{}{你想要知道我们的计划？我们想要找到一个没有受到人类欲望污染的地方，并且尝试着建立一个乌托邦。}
{157}{}{你知道你要怎样去达成你的愿望吗？}
{158}{}{我有其它的问题。}
{159}{}{谢谢，再见。}
{160}{}{我们想如果我们可以从其它社会的错误中记取教训，那我们一定可以达成目标的。}
{161}{}{你找出启动油轮的方法了吗？}
{162}{}{告诉我有关哈伯教的事。}
{163}{}{告诉我有关始族的事。}
{164}{}{我还有其它的问题。}
{165}{}{谢谢，再见。}

{166}{}{你有看到派特爵的女朋友在附近吗？}
{167}{}{我想我看到她在下面。在这油轮的北方有一个大洞。}