{100}{}{你看到一个哈伯教徒。不过，这一个看起来有一些不同。}
{101}{}{你看到ＡＨＳ－７。是副统领。}
{102}{}{你看到一个哈伯教徒。}
{103}{}{卫兵！把他杀掉！}
{104}{}{你。跟我说你的来意。}
{105}{}{啊！}
{106}{}{我有一封信要给ＡＨＳ－９，是由新加州共和国里被启发的人所写的。}
{107}{}{我是到这边与克拉克特谈有关护甲的事。}
{108}{}{我想要参观一下。}
{109}{}{我想要加入你们。}
{110}{}{你是谁？}
{111}{}{我是来将你们全部杀死的。}
{112}{}{嗯，可怜的人。你想要接受灵魂净化吗？}
{113}{}{是！}
{114}{}{不！}
{115}{}{可怜啊，既使是接受了净化之后，还是很笨。进去吧。}
{116}{}{你！}
{117}{}{进去找湾还有薇琪。他们可以帮你的。祝你好运。}
{118}{}{你！}
{119}{}{那你就不能够进去，再见。}
{120}{}{伊！}
{121}{}{很好。不过快一点－他很忙，相当的忙。}
{122}{}{好。}
{123}{}{这不是一个可以随便让你参观的地方，再见。}
{124}{}{-完成-}
{125}{}{很好！进去吧。去与湾还有薇琪谈谈－他们是明星，不过他们将可以帮助你的。}
{126}{}{他们是谁？}
{127}{}{喔！明星！}
{128}{}{我是ＡＨＳ－７，这里的副统领。}
{129}{}{我有一封信要给ＡＨＳ－９，是由新加州共和国里被启发的人所写的。}
{130}{}{我是到这边与克拉克特谈有关护甲的事。}
{131}{}{我想要参观一下。}
{132}{}{我想要加入你们。}
{133}{}{我是来将你们全部杀死的。}
{134}{}{他们是新里诺来的明星。}
{135}{}{我可以在那里找到他们？}
{136}{}{我要走了。}
{137}{}{你可以在祷告室里面找到他们。}
{138}{}{我这就去。}
{139}{}{好吧。}
{140}{}{算了，我要走了。}
{141}{}{你已与湾还有薇琪谈过了。你现在想要加入我们了吗？}
{142}{}{当然，要！要！要！}
{143}{}{当然。}
{144}{}{不是现在，我以后再加入吧。}
{145}{}{那并不适合我，抱歉。}
{146}{}{不要，我认为你们这疯狂的宗教应该要被除掉才是。}
{147}{}{::他微笑着:: 你不会后悔的。你是一个武器的专家，为何不用这个专长帮本帮服务呢？}
{148}{}{好。}
{149}{}{以后吧。}
{150}{}{不要让我们等太久。等到你的灵魂被污染的很严重时，要净化就相当困难了。}
{151}{}{我改变主意了，我要加入。}
{152}{}{我等一下再来跟你谈。}
{153}{}{你可以离开了，但是我劝你最好不要再回来。如果你不加入我们，那就是我们的敌人。}
{154}{}{再见。}
{155}{}{我不认为你能对我怎样的，再见。}
{156}{}{杀我们？卫兵！将他给我干掉！}
{157}{}{-完成-}
{158}{}{你已有许多的时间考虑了，你愿意加入我们吗？}
{159}{}{好。}
{160}{}{不。}
{161}{}{我还要再考虑一下。}
{162}{}{你没有时间了，赶快决定。}
{163}{}{好，我加入。}
{164}{}{我还是不想要加入。}
{165}{}{席德教的人一直都在找我们的麻烦。我们相信如果能将他们的皇帝破坏掉，他们就会发现自己是错误的。你愿意帮我们破坏掉他们的皇帝吗？}
{166}{}{好，我愿意。}
{167}{}{不要，席德教又没有惹我。}
{168}{}{也许你会改变主意吧。哈伯教现在可以帮你什么吗？新人。}
{169}{}{我有一些问题。}
{170}{}{现在没事，谢谢。}
{171}{}{你愿意帮我们对抗席德教吗？宇宙之神会感谢你的。}
{172}{}{我还没有决定是否要帮你。}
{173}{}{好吧。}
{174}{}{你需要些什么？}
{175}{}{我可以到那里找到可以让波斯当油轮用的燃料？}
{176}{}{我可以在那里找到你刚刚使用的专有名词的解释？}
{177}{}{船什么时候离开？}
{178}{}{克拉克特在那里？}
{179}{}{谢谢，再见。}
{180}{}{当你完成后，马上通知我们。}
{181}{}{好。我还有一些问题。}
{182}{}{没问题，再见。}
{183}{}{你将皇帝给破坏掉了吗？}
{184}{}{还没有。}
{185}{}{是的，他死了。}
{186}{}{油轮上的首领是派特爵，他只要一死，其他的人都会听我们的。你愿意帮我们杀掉他吗？}
{187}{}{我愿意。}
{188}{}{他又没有惹我，我才不要。}
{189}{}{你改变主意，要帮我们除掉派特爵了吗？}
{190}{}{我愿意。}
{191}{}{我还是不愿意。}
{192}{}{你将派特爵杀掉了吗？}
{193}{}{还没有。}
{194}{}{是，他死了。}
{195}{}{他们的人现在会支持哈伯教了！你做的很好！}
{196}{}{谢谢，我还有一些问题。}
{197}{}{再见。}
{198}{}{事实上，我也要将你给杀了。}
{199}{}{现在船上装满了燃料，我们只要等ＡＨＳ－９的命令就可以出发了。}
{200}{}{当然。我有一些问题。}
{201}{}{谢谢。再见。}
{202}{}{我想不出来另外一个地方了，席德教，也许吧？}
{203}{}{嗯。我还有更多的问题。}
{204}{}{也许吧。}
{205}{}{我知道席德教有很多的燃料。也许你可以从那边偷一些来。}
{206}{}{那真是好主意。我还有更多的问题。}
{207}{}{也许吧，谢谢。}
{208}{}{使用湾还有薇琪给你的磁片，里面有所有的资料。}
{209}{}{谢谢，可以再问吗？}
{210}{}{谢谢。}
{211}{}{当ＡＨＳ－９下了命令后，我们就可以出发了！}
{212}{}{是啊，我还有一些问题。}
{213}{}{谢谢。}
{214}{}{他一般都是在他的实验室里面。}
{215}{}{谢谢，我还有事想要问你。}
{216}{}{谢谢。}
{217}{}{在你可以成为我们的一员之前，我们得先要净化你的灵魂。你准备好了吗？}
{218}{}{不！不要！}
{219}{}{好了。}
{220}{}{不经过净化，你就不能够加入我们。你真的不要吗？}
{221}{}{当然，我才不要被你的机器拿来乱弄咧。}
{222}{}{好吧，净化我吧。}
{223}{}{我们将你的灵魂净化了。你现在是ＡＨＳ－１。你愿意知道我们的教条吗？}
{224}{}{好。}
{225}{}{不要，不想知道。}

{226}{}{第一课：在这里我们有永恒的，伟大的轮。“指着某样东西”而且这就是我们的所在。“指着某样东西”现在我们所有人还有非常遥远的路要走，我们最终的目地就是要前往乐土。}
{227}{}{伙计，那我们将需要很多很多的鞋子。}

{228}{}{可以再让我想想吗？}
{229}{}{又是你？要干嘛？}
{230}{}{你要我做什么吗？}
{231}{}{我们不欢迎你，请马上离开。}

