{100}{}{你看到一个始族人，穿着白色的衣服。}
{101}{}{你看到一个始族的研究实验室。}
{102}{}{你看到一个穿白衣的始族人正在一个科学实验室里面。}

{103}{}{天．．王真会命令别人做事。}
{104}{}{工作，工作，工作。只会叫我们工作而已。}
{105}{}{这一个实验将会改变整个荒野！}
{106}{}{小心，荒野！我们的研究将会改变你！}
{107}{}{我想要再一次的看到太阳。}
{108}{}{混合这个。混合那个。这真是一个无聊的工作。}
{109}{}{你有没有看到最新实验的成果！令人振奋！}
{110}{}{不好意思。}

{116}{}{哈！那一些间谍是进不来的！}
{117}{}{不过那一些骇客再也不会尝试了。}
{118}{}{如果用科学无法对付他们，那我们就用战士来对付他们。}
{119}{}{罗潘跟龙在一起是相当厉害的组合。}
{120}{}{那一个骇客并没有支撑多久。}
{121}{}{工作，工作，工作。只会叫我们工作而已。}
{122}{}{我们将会改变整个荒野的！}
{123}{}{我们来了，荒野！}
{124}{}{我想要再一次的看到太阳。}

{127}{}{萧明是一个可恨的败类。}
{128}{}{我们快要完成了。}
{129}{}{哈！为了帝王！}
{130}{}{你有听到吗？有人侵入了我们的电脑！}
{131}{}{我想那一定是哈伯教的人干的。}
{132}{}{我们应该要用一些病毒来对付那一些哈伯教的人。}
{133}{}{我要向那一些骇客报仇！}
{134}{}{我有一天会找出侵入我们电脑的凶手。}
{135}{}{工作，工作，工作。只会叫我们工作而已。}

{144}{}{我们在这边工作的很辛苦！}
{145}{}{我们是要拯救荒野的，你这白痴！}
{146}{}{不！不要杀我们的科学家！}
{147}{}{救命！卫兵！}
{148}{}{拜托！你难道不懂吗！}
{149}{}{不！我们的实验！}
