{100}{}{你看到了一个酒保。}
{101}{}{你看到了史林，一个酒保。}
{102}{}{你看到了一个酒保。他穿了一条围裙，他手上有一个杯子。他一直着在清洗那一个杯子，并且不理任何的人。}
{103}{}{我是史林，你想要什么？}
{104}{}{我想要一些讯息。}
{105}{}{你有什么？}
{106}{}{不，我走。}
{107}{}{我想要打听一些事情。}
{108}{}{你有卖些什么呢？}
{109}{}{都不要，我要走了。}
{110}{}{想要问事情吗？我又不是图书馆也不是一台电脑。买酒喝，不然就滚。你到底要不要喝酒？}
{111}{}{好。}
{112}{}{不。}
{113}{}{好吧。如果这东西不能将你杀死，也没有什么可以。}
{114}{}{}
{115}{}{好。}
{116}{}{就这样而已？}
{117}{}{好。}
{118}{}{不。}
{119}{}{等一下吧。}
{120}{}{}
{121}{}{好。}
{122}{}{欢迎回来。要喝酒吗？}
{123}{}{好。}
{124}{}{不。}
{125}{}{我们关门了，再见。}
{126}{}{}
{127}{}{好。}
{128}{}{我们不欢迎你。给我滚！}
{129}{}{}
{130}{}{好。}