#ipisgfx译
#{100}{}{Halt, wastelander! We are searching for an enemy of the Enclave. Identify yourself.}
{100}{}{停止，废土外的人！我们正在搜索英克雷的敌人，识别你的身份。}
{101}{}{人人都恨英克雷。去死吧！#￥%}
{102}{}{英克雷？没听说过。我只是一个旅行者。}

#{103}{}{That's enough for me. Kill him.}
{103}{}{对我来说这就够了。杀了他。}
{104}{}{喔，那将会很有趣的！}

#{105}{}{[Eyes narrow] Why should I believe you? You're in the vicinity of Gecko. You could be the one we're looking for.}
{105}{}{为什么我要相信你？你在蜥蜴城附近。你可能是我们要找的人。}
{106}{}{也许吧，就像我说的。我从没听说过英克雷。我得走了。}
{107}{}{完全正确，我放弃了。有种就来吧！}

{108}{}{你说刚说，你来过蜥蜴城？}
{109}{}{是，当然我来过。有趣的地方。很棒的电脑系统！}
{110}{}{不，之前从来没来过这。为什么？}

{111}{}{好吧，我信你。散开，伙计们。搜索这个区域。我们必需找到那个人。}
{112}{}{不，我不相信你。伙计们这就是我们要找的人！}
{113}{}{[完成]}

{114}{}{为什么你不相信我？我做什么你才会相信？}

#{115}{}{Somebody hacked into the Enclave computer network from the Poseiden Oil Reactor. We're trying to track him down.}
{115}{}{有人从波塞冬石油反应堆入侵了英克雷的电脑网络。我们正试着找出他。}
{116}{}{入侵？喔，那肯定不是我了。我是一个土著。我甚至都不知道怎么用－你们叫这东西什么？－带电的脑？}