{100}{}{你看见了一个又矮又老的僵尸。}
{101}{}{你看见哈欧的助手，廉尼。}
{102}{}{你看见个矮老的僵尸。他看上去好像相当忙的样子。}

{110}{}{你好。我的名字是廉尼。我能帮忙吗？}
{111}{}{又是你。我能帮忙吗？}
{112}{}{我听说你是避难所住民的后代。你知道吗，我见过原来的避难所住民。}
{113}{}{你好。我真不敢相信你看起来有多像避难所住民。我能为你做什么？}
{114}{}{黏尼？嘿。}
{115}{}{你在这边是做什么的？}
{116}{}{我受伤了。你能帮我吗？}
{117}{}{我的朋友受伤了。你能帮忙吗？}
{118}{}{我的朋友受伤了。你能帮他们吗？}
{119}{}{廉尼，你听说过伊甸园创造器吗？}
{120}{}{你有见过我的祖先？}
{121}{}{我只是周围看看而已。再见。}
{122}{}{你能够进行医疗吗？}

{125}{}{是的。你需要什么？}
{126}{}{我想我现在不需要任何东西。}

{130}{}{你不应该离开你的村子的。回去吧。}
{131}{}{家？再见。}

{140}{}{你应该要回家。}
{141}{}{我不能花在你身上太多的时间。}
{142}{}{走开！}

{150}{}{伊甸园创造器？我听说地下掩体市有一个。}
{151}{}{我受伤了。你能帮我吗？}
{152}{}{我的朋友受伤了。你能帮他吗？}
{153}{}{我的祖先，避难所住民，说第１３号避难所欠我们一个。我得要找到它。}
{154}{}{我目前只想要知道这样而已，再见。}

{160}{}{我是帮助哈欧的人。有人受伤的话，我就会帮助他们。}
{161}{}{帮助哈欧做什么？}
{162}{}{叫我问你一些其它的事。}
{163}{}{你会疗伤？}
{164}{}{我受伤了。你能帮我吗？}
{165}{}{我的朋友受伤了。你能帮他吗？}
{166}{}{我会记着的。如果我受伤了，我会来找你的。谢谢。再见。}

{170}{}{叫我看看。我想我是能够帮你的。}
{171}{}{这会要花掉我的钱吗？}
{172}{}{谢谢，廉尼。让我问你其它的问题。}
{173}{}{谢谢，廉尼。再见。}
{174}{}{我可以帮你，但是要花掉你$30。}
{175}{}{我不让为我想要你帮忙。再见。}

{180}{}{你的朋友需要医疗。我可以帮忙。}
{181}{}{看来你身陷了一些麻烦，我想我可以帮忙的。}
{182}{}{这要花钱吗？}
{183}{}{谢谢，廉尼。让我问你其它的事。}
{184}{}{谢谢，廉尼。再见。}
{185}{}{你的朋友受伤了。我可以医疗他们，要$30。}
{186}{}{我可以医疗所有人，但是要收$60。}
{187}{}{你的朋友看起来很好啊。}

{190}{}{我不认识避难所住民。但是我倒是见过他们。}
{191}{}{你见过避难所住民？在那里？}
{192}{}{我该走了，还有事要办，还有人要杀咧，再见。}

{200}{}{在战争之前我是一个医生。}
{201}{}{战争前？那是１６０年前了。}
{202}{}{喔，原来如此，再见。}

{210}{}{那是一种折磨啊。放射线给了我们僵尸更长的寿命，但是我们也因此损失了很多的东西。}
{211}{}{损失了很多东西？}
{212}{}{每件事都有好有坏。再见。}

{220}{}{对啊，我们看起来都很奇怪，而且都没有皮肤。}
{221}{}{真是的，果然是大损失。}
{222}{}{你们确实是不吸引人，再见。}

{230}{}{没错，我宁可少活几年也要过正常人的生活。}
{231}{}{我想那是没希望的。}
{232}{}{是吧，再见。}

{240}{}{如果那些地下掩体市混蛋愿意分享他们的医学技术的话，我想我们是能够将身体里面的放射线给清除的。}
{241}{}{他们不愿意帮你们？}
{242}{}{我听够了。再见。}

{250}{}{你去过地下掩体市？那你就知道他们不会帮我们的。}
{251}{}{真是可惜吧。我想要问你一些其它的事。}
{252}{}{真可惜啊，再见。}

{260}{}{生命实在是太短了。}
{261}{}{没错，廉尼。}

{270}{}{那是很长时候以前了。在一个大城市之中，有一天，我看见有一个跑过市中心。}
{271}{}{跑？}
{272}{}{我听够了，再见。}

{280}{}{是的，跑。我们僵尸是不能够跑步的，所以我肯定他一定是个外地人。我真希望我能加入避难所住民啊．．}
{281}{}{你想加入我的祖先之中？}
{282}{}{门都没有，我的祖先怎么会叫你这样个皮肤的怪人加入呢？再见。}
{283}{}{我很想听完故事，但是我该走了。再见。}

{290}{}{是啊，我有很棒的机会，但是却被我错过了。}
{291}{}{那是什么意思？}
{292}{}{再见。}

{300}{}{后来，我听说避难所住民修好了我们的给水系统。避难所住民救了我们，懂吗？虽然我们是僵尸，他还是愿意帮我们。}
{301}{}{我的祖先是开拓我们部落的先人，我们也都很尊敬他。}
{302}{}{我只关心我的部落，其他人的人下地狱我也不管。再见。}

{310}{}{后来，我听说避难所住民毁灭了变种人的军队。他们又救了我们。真可惜我没有参加，自那之后，我都没有原谅过我自己。}
{311}{}{我想要学习我的祖先的功绩，再给你一个机会，你要参加我吗？}
{312}{}{我肯定你在这边的工作是很有价值的。让我问你一些其它的问题。}
{313}{}{人的心底都是没胆量的。再见。}
{314}{}{谢谢你告诉我有关我祖先的事，再见。}

{320}{}{我太高兴了！我很荣幸。虽然我的动作很慢，但是如果你们有需要，我是可以医疗你们的。}
{321}{}{我真高兴你能加入我们，你的医疗术肯定会很有用处的。}
{322}{}{你的年龄可能不适合跟我们在一起的，对不起，再见。}

{330}{}{我这边有工作，不能够参加。}
{331}{}{你一点都不像你的祖先，真是丢他的脸。}
{332}{}{对于生命，你还要很多要学的东西咧。}
{333}{}{听到你不能够加入，我感到很可惜。}
{334}{}{我本来以为像你这样的人可以从这粪堆里跳出来，没想到你也不过尔尔，再见。}

{340}{}{我帮助哈欧管理这个城市，要处理很多的公文。}
{341}{}{你还说你做过些什么？}
{342}{}{我想那就是所有我想要知道的了，再见。}

{350}{}{你虽然没有足够的钱，但是我也会帮你。因为我不能见死不救。}
{351}{}{我真感谢你。不过，我还需要问你一些事。}
{352}{}{谢谢，廉尼。再见。}

{360}{}{这里太多人了。你不需要我的帮助了。祝你好运。}

{370}{}{你真是败坏你祖先的名声啊！再见。}
{371}{}{我本还很想要加入你的队伍，但是没想到你的人格臭得像猪拉的粪一样。再见。}
{372}{}{我真抱歉你要走了，再见。}
{373}{}{你不行的，对不对？你赶快走开，不然我可能会杀了你。}
{374}{}{是吗。就凭你这没皮肤的浑蛋？滚蛋！}
{375}{}{好。}

{380}{}{你要我做什么。}
{381}{}{廉尼，我知道你尽力了。但是请不要挡住我的路。}
{382}{}{我需要你换个打斗的方法。}
{383}{}{我需要你等在这边。}
{384}{}{医生，请医疗自己吧。}
{385}{}{我需要一些医疗，廉尼。}
{386}{}{我这边的朋友需要一些医疗。}
{387}{}{我需要你医疗我们。}
{388}{}{近来好吗？}
{389}{}{我不需要什么了，廉尼。}

{400}{}{你要我改变战斗的方法？}
{401}{}{我要你改变距离。}
{402}{}{我要你用最好的武器。}
{403}{}{我要你用最好的装甲。}
{404}{}{我要你改变格斗的方法。}
{405}{}{算了。}

{410}{}{你要我离你多远？你知道我不太跟得上。}
{411}{}{我要你离我一点距离就好了。}
{412}{}{我要你离我中等距离。}
{413}{}{我要你离我远一点。}
{414}{}{我要你在前面先探路。}
{415}{}{算了。}

{420}{}{你要我做什么？}
{421}{}{我要你以防御的方式战斗。}
{422}{}{我要你以正常的方式战斗。}
{423}{}{我要你以凶狠的方式战斗。}
{424}{}{算了。}

{430}{}{我想你还是可以叫个老人学新的技术的。}
{431}{}{我就是无论如何都学不会。}
{432}{}{好。}

{440}{}{好，我在这边等你回来。}
{441}{}{就那样吧，廉尼。}
{442}{}{你要等在这，还有．．}
{443}{}{算了。}

{450}{}{我得要去找一把更厉害的枪。}
{451}{}{使用你的最好的武器。}
{461}{}{使用你最好的装甲。}
{462}{}{廉尼，当你穿好你最好的装甲后，我还有事要你去做。}
{463}{}{算了。}

{470}{}{那真是好主意。我真是累死了。}
{471}{}{你应该让我看看你那一些伤口。}
{472}{}{看起来有人需要我来医疗他们的伤口。}
{473}{}{去吧，医疗你自己吧！}
{474}{}{医疗你自己，然后我还有事要你做。}
{475}{}{医疗我吧，谢谢。}
{476}{}{医疗我，然后我还有事要叫你做。}
{477}{}{来医疗我们吧。}
{478}{}{医疗我们，然后我还有事要叫你做。}
{479}{}{算了。}

{480}{}{我不能那样做，我是不会探路的。}
{481}{}{好，算了。}

{490}{}{我会跟紧的。}
{491}{}{跟紧，廉尼。}
{492}{}{跟紧，我还有事要叫你做。}
{493}{}{算了。}

{500}{}{我们不想要成靶子的，对吗？}
{501}{}{不要跟太近，我要他们不容易打中我们。}
{502}{}{不要跟太近。我还要你去做其他的事。}
{503}{}{算了。}

{510}{}{好。我会离远一点点的，反正他们也不较喜欢攻击你的。}
{511}{}{我需要你离远一点点，是为了你的安全。不是因为你臭。}
{512}{}{我们分散前，我要你做一些事。}
{513}{}{算了。}

{520}{}{这几年，我已经学会保护自己了。}
{521}{}{当我们打仗的时候我要你小心一点。}
{522}{}{我不要有意外发生在你身上，你太老了。还有．．}
{523}{}{算了。}

{530}{}{唯一的办法。}
{531}{}{用你平常怎么打斗方法，这样就行了。}
{532}{}{放轻松，按你平常的打法就可以。还有．．}
{533}{}{算了。}

{540}{}{我不行，我这把老骨头了。}
{541}{}{好，算了。}

{1000}{}{你要我做什么？}

{1100}{}{我很好。}
{1200}{}{我有小伤，但是我还能走。}
{1300}{}{好主意。我已经快支撑不住了。}
{1400}{}{我需要治疗，不然我死定了。}

{1500}{}{我会等你回来的，这可以让我有时间可以休息一下。}

{1600}{}{好。}

{1700}{}{我会跟近你的。}
{1800}{}{我不想成为简单靶子的，对不对？}
{1900}{}{好，我会离远一点的。}

{2000}{}{这里太多人了。你不需要我的帮助了。祝你好运。}
{2100}{}{我加入之后，才发现你真是丢脸。你是个败类。再见。}
{2200}{}{我还以为你不会回来了。}

{2300}{}{干吗那么紧张？}
{2301}{}{对不起，我不挡你路了。}
{2302}{}{快点，快点，快点，我已经够快了。对不起，我不是有意的。}
{2303}{}{对不起，我不能再快了。我不挡你路。}
{2304}{}{好，我不挡路。}
{2305}{}{好，我走在后面。}
{2306}{}{我不是有意成为包袱。}
{2307}{}{对不起。}

{3000}{}{太多坏事发生在你身上了。我要赶快离开，不然坏事就要发生在我身上。}
{3001}{}{我不会帮助一个杀小孩的人的，再见。}
{3002}{}{你太残忍了。我不要跟着你了。}
{3003}{}{我不想要帮助一个奴隶贩子。再见。}
{3004}{}{你是个叛徒！你毁灭了我们的发电机。我不要帮你了。}
{3005}{}{我不要与你有任何的关系了。}

{4000}{}{好，但是我不想被丢在这个地方的。}
{4001}{}{好，如果你认为那是个好主意的话。}
{4002}{}{我不喜欢用武器，除非是必要时。我可以用刀，或者手枪。如果真的需要，我可以用冲锋枪，如果不是很响的话。我是个医生，不是战士啊。}
{4003}{}{天，真希望我永远不会用到那个的。}
