{100}{}{你看到一个相当忧郁的人。}
{101}{}{你看到蓝尔皮，史盖特的朋友以及助手。}
{102}{}{你看到一个相当瘦小，并且很不开心的人。}

{110}{}{你看起来比我还要惨啊，可怜的笨蛋。}
{111}{}{我没有时间与笨蛋说话。}
{112}{}{你看起来并没有比双头牛要聪明嘛。}
{113}{}{你没有三两重嘛，对不对？}
{114}{}{你一定是很笨的。}

{120}{}{你好，我叫蓝尔皮。}
{121}{}{那是一个相当不寻常的名字，是怎样得来的？}
{122}{}{你在这边是干什么的？}
{123}{}{很好，我要走了。}

{130}{}{我的真名叫约翰－－但是大家都叫我蓝尔皮。}
{131}{}{为什么呢？}
{132}{}{再见。}

{140}{}{你好。你有没有发现每一个双头牛都有它自己的个性？如果你常与它们在一起，你就会发现。}
{141}{}{是的，真有趣。}
{142}{}{牟牟}
{143}{}{你在这边是干什么的？}
{144}{}{那真有趣。你是谁？}
{145}{}{我对有一些事相当好奇。}
{146}{}{很高兴见到你，再见。}

{150}{}{你好。你是来这边见史盖特的吧。我在这边只是打杂的。}
{151}{}{盖特．．嘻嘻嘻。}
{152}{}{你是谁？}
{153}{}{你在这边是干什么的？}
{154}{}{我有一些问题想要问你。}
{155}{}{喔，那我去与史盖特谈吧，谢谢。}

{160}{}{你好，既然你已经进来了，我可以帮你什么吗？}
{161}{}{我很饿。}
{162}{}{嗯，我想知道史盖特在那里。}
{163}{}{我有一些问题想要问你。}
{164}{}{抱歉，我并不是故意样闯进来的。再见。}

{170}{}{我负责看守双头牛，或者是帮史盖特。}
{171}{}{史盖特是谁？}
{172}{}{让我问你一些其它的问题。}
{173}{}{再见。}

{180}{}{那可以说是一个玩笑。你看，他们叫我们皮肤光滑的人。但是地下掩体市的人却对我不好。}
{181}{}{为什么地下掩体市的人对你不好呢？}
{182}{}{再见。}

{190}{}{史盖特是一个机器技工。他可以将任何的东西拆开，然后装回去。有时候经过他重装后，机器反而会运作的更好咧。}
{191}{}{我在那里可以找到史盖特？}
{192}{}{真有趣，让我问你一些其它的问题。}
{193}{}{那就是我想要知道的，再见。}

{200}{}{他说我不够像人，因为我的身体可以抗放射线。但是他们不喜欢我，对我相当的差。}
{201}{}{真的？}

{210}{}{有一天，我终于受不了了。我认为在荒野中死总比在那边死好。}
{211}{}{那你为什么会来到这边呢？}

{220}{}{一个从破碎丘来的商队将我带到这边来的。自那之后我就一直在这里。这边的僵尸的好处就是他们不会以貌取人。大家都是很好的朋友。}
{221}{}{破碎丘？那是什么？}
{222}{}{很有趣。让我问你一些其它的问题。}
{223}{}{很高兴你喜欢这个地方。再见。}
{224}{}{再见。}

{230}{}{破碎丘是我们取得发电厂需要的铀矿的地方。据我所知，在那边铀矿是由变种人开采的，但是贸易方面却是由人类所管理。}
{231}{}{为什么是人类帮他们管理呢？}

{240}{}{你想要知道什么？}
{241}{}{你真是充满好奇啊。好吧，你想要知道什么？}
{242}{}{现在你想要知道什么？}
{243}{}{那些外面的垃圾都是些什么？}
{244}{}{你在这边是干什么的？}
{245}{}{谁是史盖特？}
{246}{}{这附近有什么不寻常的事情发生吗？}

{250}{}{那是因为他们也与地下掩体市有交易。地下掩体市对于任何不是纯人类的生物都相当的不尊敬。因此，破碎丘用人类来当交易的人。我想是一个叫查德的人。}
{251}{}{查德？我会记得的。让我问你一些其它的事。}
{252}{}{再见。}

{260}{}{这些是他们在建造反应炉时留下来的。其它的东西呢？都是史盖特的收集品。}
{261}{}{谁是史盖特？}
{262}{}{我还有事情要问你。}
{263}{}{再见。}

{270}{}{他就在这边。眼睛睁大一点吧。}
{271}{}{史盖特一向都在他的工场里面。就在未完成的反应炉的南边。}
{272}{}{谢谢，再见。}
{273}{}{我不知道史盖特最近都跑到那边去了。}

{280}{}{我随时都在工作，可以有时候我晚上会听到一些东西。}
{281}{}{听到东西？像什么呢？}
{282}{}{告诉我你都听到一些什么，我不会跟别人说的。}
{283}{}{我也是，但是我以为那只是我的耳朵在作怪而已。}

{290}{}{我好像听到有人每天晚上在反应炉心里面走来走去的声音。}
{291}{}{人？每天晚上？}
{292}{}{让我问你一些其它的事。}

{300}{}{我不能告诉你，人们都以为我是疯子。不过，那也可能是风吹的声音吧。}
{301}{}{我告诉你我没有听到什么，不要再烦我了。}
{302}{}{让我问你一些其它的事。}

{310}{}{(接近看着你的眼睛) 你听到一些东西？}
{311}{}{没有，事实上是没有。}
{312}{}{是啊。}

{320}{}{很好。我原本开始要担心你了。}
{321}{}{谢谢你，让我问你一些其它的问题。}
{322}{}{再见。}

{330}{}{我一见到你就知道你是疯子了，但是我还不能够确定。滚滚滚，你这疯子。}
{331}{}{随你说，再见。}
{332}{}{你也是疯子！}

{340}{}{我不知道那是不是人声，但是每过几个的晚上就会有声音从反应炉心中传出来。}
{341}{}{不知道那里面到底有什么东西．．}
{342}{}{再见。}
{343}{}{反应炉心不是有很强的放射线，不可能会有生物可以存活在里面的吗？}

{350}{}{不，这一的部份的反应炉还没有完成。}
{351}{}{原来如此，让我问你一些其它的事吧。}
