{100}{}{你看到一个相当大的变种人。}
{101}{}{你看到一个监狱的守卫，他是一个很强壮的变种人。}
{102}{}{你看到一个全身武装的守卫；一个拿着奇异武器的变种人。}

{103}{}{我可以帮你吗？}
{104}{}{啊啊！}
{105}{}{我要进去！啊！}
{106}{}{只是到处看看而已。}
{107}{}{嗯，不，不用了。}
{108}{}{是的，我是来跟你们的囚犯说话的。}
{109}{}{你们有没有想过你们拘禁那些犯人是非法的事呢？}

{110}{}{喔，请你离开。}
{111}{}{啊啊啊！}
{112}{}{好吧！}

{113}{}{是的，嗯，到别处去吧。我们这边的人都是罪犯。走吧。}
{114}{}{喔，好吧。}

{115}{}{到这边来的人我们都会尽量的帮助，但是如果你没事的话，请你离开。}
{116}{}{有种把我架走吧！}
{117}{}{知道了。}

{118}{}{你需要跟他们说话？有什么问题跟我们说就好了。你想要说什么？}
{119}{}{你们有没有想过你们拘禁那些犯人是非法的事呢？}
{120}{}{看招，变种人！}
{121}{}{没事，我要走了。}

{122}{}{你那是什么意思？}
{123}{}{我的意思是说，他们除了发表自己的言论之外，并没有犯法。他们只不过是说了一些反变种人的言论而已，难道发表自己的看法也是一种罪吗？}
{124}{}{有力量的人就可以撰写法律，我有力量。}

{125}{}{不，但是他们却是相当危险的人物。}
{126}{}{直到他们犯了法之前，他们都是无罪的。不是吗？}
{127}{}{危险？我也很危险啊，你也很危险啊，这样一来我们不是都会被关在牢中了吗？}
{128}{}{那又怎样？}

{129}{}{好吧，好吧。我希望你说的是对的。这是钥匙。}
{130}{}{那就是我要的。太好了。谢谢，再见。}

{131}{}{在有人能够给我一个更好的应该把他们放出来的理由，我是不会放他们出来的。现在，请离开这边。}
{132}{}{不！}
{133}{}{好吧。}

{134}{}{他们得待在牢里面，因为我们得要保护我们的社会。请你离开吧。}
{135}{}{不！}
{136}{}{好吧。}

{137}{}{你！你他妈的在这边干什么？你他妈的给我滚开！}

{138}{}{请你马上将你的武器拿开。}

{139}{}{又是你？你要干什么？}
{140}{}{只是到处看看而已。}
{141}{}{嗯，不。}
{142}{}{我是来与你的囚犯谈谈的。}
{143}{}{你们有没有想过你们拘禁那些犯人是非法的事呢？}

{144}{}{你不应该在这边逗留的，离开吧。}
{145}{}{如果被我知道那些囚犯逃到那边去了，我一定不会放过他们！}