{100}{}{你看见了一个相当矮的人。}
{101}{}{你看见米基，一个寻宝的人。}
{102}{}{你看见一个很矮的人，他正在地上寻找着会发光的东西？}
{103}{}{嘿，朋友。你有没有在这附近看到什么值钱的珠宝呢？}
{104}{}{这附近有没有我应该知道的可以找到宝藏的地方呢？}
{105}{}{你有没有需要找到任何的财富呢？我是这方面的高手。}
{106}{}{没有}
{107}{}{有的，我需要你的帮忙。}
{108}{}{你是谁？}
{109}{}{再见。}
{110}{}{今天没有，不过若有的话，我会让你知道的。}
{111}{}{是的，我相信你将会是一个合作的好伙伴的。}
{112}{}{你叫什么名字？}
{113}{}{算了。}
{114}{}{我是米基，破碎丘的寻宝者。}
{115}{}{寻宝者？}
{116}{}{再见。}
{117}{}{寻宝者？}
{118}{}{很好，再见。}
{119}{}{你没听说过我？}
{120}{}{没有。}
{121}{}{我从来都没有听过你这一号人物。}
{122}{}{真是的，等有时间，我会告诉你我所有的冒险故事的。}
{123}{}{好。}
{124}{}{我会期待着的。}
{125}{}{真是的，不过，我也不吃惊。近来的寻宝者越来越少了，人们越来越不喜欢冒险了。记着，如果你知道些什么，就跟我分享吧。}
{126}{}{好。}
{127}{}{我会先跟你讲的。}
{128}{}{真的？太好了！那是什么宝藏呢？金子、珠宝、还是稀有的古物呢？}
{129}{}{是很多的钱。}
{130}{}{算了。}
{131}{}{我想应该是很多的钱，可以让人舒服过一辈子的数目。}
{132}{}{我看我还是自己先试试看好了。}
{133}{}{这就是我一直在期待的冒险！怎样，我们平分好吗？}
{134}{}{好！}
{135}{}{不，再见。}
{136}{}{好吧。}
{137}{}{我看我还是先自己去试试看好了，再见。}
{138}{}{太好了！你要我做些什么呢？}
{139}{}{跟我来，要你去一个黑暗的地方。}
{140}{}{我只能够告诉你，你将会在本地的一个地洞中花上一些时间。}
{141}{}{很好，告诉我在那里吧。}
{142}{}{在那里？市中心吗？}
{143}{}{我还不太清楚，不过有人跟我说我在这附近可以找到一些宝藏。}
{144}{}{什么，跟你那样说的人一定是疯了。我找过整个破碎丘，什么都没有找到过。原本还想要离开这个地方咧。}
{145}{}{真是的，再见了。}
{146}{}{真是的，我原本还以为你可以告诉我些什么咧。}
