{100}{}{你看到一个老人。}
{101}{}{你看到孔尼洛斯。}
{102}{}{除了他脸上有些忧容之外，他看起来相当的正常。}

{150}{}{欢迎来到萝丝的旅店。我叫萝丝－－我是说，孔尼洛斯－－我是这个旅店的负责人。我可以帮你吗？}
{151}{}{如果你是这个地方的负责人，那为什么它叫作萝丝旅店呢？}
{152}{}{我正在找一个金表。}
{153}{}{你在这边是干什么的？}
{154}{}{谁是萝丝？}
{155}{}{我想要一间房间。}
{156}{}{问题？我有问你什么吗？你好，我叫孔尼洛斯。}
{162}{}{你有很严重的问题，老人。}
{163}{}{费尔把你的表放在墙上的保险箱中。}
{164}{}{我在费尔的家中找到了你的表。你是对的；费尔是一个小偷。}
{165}{}{看起来好像有一只老鼠把你的表给叼走了。我在它的巢中找到了你的表。}
{166}{}{你好！我们以前见过吗？}
{176}{}{我的天！有人杀了我最好的朋友，费尔！现在全镇都在找那杀人犯。当我们抓到他时我们会好好的教训他的！}
{177}{}{我杀了他。你能怎样呢？你这疯老头！}
{178}{}{哇！时间不早了，我要走了。}
{179}{}{萝丝是我的老婆；这个地方就是以她取名的。你不知道我结婚了吗？}
{180}{}{我可以问你一些问题吗？}
{181}{}{那你为什么问不那个混蛋费尔？也许他会把从我这边偷走的表给卖给你呢！现在，如果你不介意的话，我还很忙。}
{182}{}{我是负责这个旅店的。如果不是我的话，这一个地方早就完蛋了。你有看到这里有多干净吗？这都是我的功劳。}
{183}{}{这里干不干净跟这有什们关系？}
{184}{}{萝丝是我的老婆。她是负责厨房的。你在这边再也找不到比她煮的好吃的了。萝丝相当的漂亮，我总有一天会跟她结婚的。}
{185}{}{你不是刚刚才说萝丝是你的老婆吗？}
{186}{}{我有一间房，我睡在那边。你睡在那边？}
{187}{}{我不认为你知道我在说什么。我今晚想要租一间房。}
{188}{}{不久前，我三、四十年的好朋友偷走了我的金表。那是我的传家之宝，我明明把它收了起来，但是后来就不见了。}
{189}{}{我会帮你把表找回来的。}
{190}{}{你有去看看你的桌子吗？}
{191}{}{你愿意帮我？太好了！去把费尔打一顿然后把我的表拿回来。他也许把它藏起来了，因此，你得要拆了他的家才能够找到。}
{192}{}{你在说什么吗？}
{193}{}{听着，我不想要与这种事沾上边。}
{194}{}{杀了费尔，把表拿回来。我马上回来。}
{195}{}{杀了费尔？谁要把费尔给杀了呢？我会亲手把想要杀费尔的人给抓起来的。}
{196}{}{我愿意接受这个工作，不过在我完成后我要收钱。}
{197}{}{我受不了了，我要走了。}
{198}{}{当然，我会付你钱的。当你把谷仓清好后再来找我。}
{199}{}{我有一支表，那是一支金表。不知道被我放到那里去了？}
{200}{}{是，是，是。我到处都找过了，就是没有。}
{201}{}{我会帮你注意你的表的。}
{202}{}{我才不要帮你这种疯老人咧。我要走了。}
{203}{}{我就知道我不能够信任他！在他把我的表还我之前，我会好好的对付他的。}
{204}{}{这边什么都没有。我跟侨警长已经看到了。}
{206}{}{是吗？我就知道。我会狠狠的教训他一顿的。你最好待在这边，不然你也许会受伤。}
{207}{}{那是我的表！你要它拿去干什么？还来！ [他从你手中把表抢走。] 我想你最好离开；我们对小偷是相当不客气的。}
{208}{}{那对你来说是感谢了。}
{209}{}{你有试过萝丝的蛋饼吗？非常的好吃喔。}
{210}{}{我在井旁边看到乔尼以及拉蒂再玩，他真是一个好孩子吧。}
{211}{}{除非你活腻了，不然我劝你不要到鬼农场那边。}
{212}{}{麦丽雅是一个好女孩。她在小时候最喜欢扮医生了。}
{213}{}{达宾是一个好男孩。不过真不知道他为什么看起来一点都不像他爸爸？}
{214}{}{我有一天坐在马桶上，突然有一条狗从排水管里面爬出来，吓死我了。}
{215}{}{葛力斯韩是一个好人。}
{216}{}{你最好不要靠近鸡圈！我喂那些东西时差点被咬掉一条手臂。}
{217}{}{萝丝的狗很凶，不过我丢了一些肉干给它们，因此它们理都不理我。}
{218}{}{费尔是我最好的朋友。}
{219}{}{拉蒂是一条聪明的狗。我一天到晚都与它说话。}
{220}{}{我听说葛力斯韩想要把他的孩子都嫁出去。不知道如果我再娶一个太太，萝丝会不会生气？}
{222}{}{我要走了，再见。}
{223}{}{我找到杀人犯了！他承认杀死了费尔！抓住他！}
{224}{}{我找到杀人犯了！她承认杀死了费尔！抓住她！}
{225}{}{我杀费尔。}

{300}{}{萝丝．．房间．．跑．．}
{301}{}{嗯。}

{501}{}{我就知道你是个小偷！}
{502}{}{你怎可以这样对你最好的朋友！}
{503}{}{我要杀了你！}
{504}{}{我要把你的头挂在墙上！}

{550}{}{他看起来正在想别的事。}

{600}{}{你把表还给了孔尼洛斯了。}
{650}{}{你解决了孔尼洛斯以及费尔之间的纠纷。}
