# 0. QUICK LOOK (WTG)
{100}{}{你看到比尔。}

# 0. LOOK (WTG)
{150}{}{你看到有着白眉的男人。他看起来需要喝一杯。}

# 1. FLOATS (WTG)
{200}{}{::咳咳::}
{201}{}{::瞪着酒保::}
{202}{}{::比着再来一杯的手势::}
{203}{}{::注视着::}

# 2. STUPID FLOATS (WTG)
{210}{}{给我滚，笨蛋。}

# 3. NORMAL (WTG)
{220}{}{(当你走近时，他连看都不看你一眼。正这注视着酒吧后面的墙。)}
{221}{}{嗯，嘿，你在干什么？}
{222}{}{嘿，你觉得我戴着的这一幅新眼镜如何？}
{223}{}{嘿，你有没有杀过任何人？}
{224}{}{(不要烦他)}

# 4. FALLOUT2 = ENCLAVE_DESTROYED (3)
{230}{}{你那是什么王八问题？}
{231}{}{喔，我只是好奇而已。}
{232}{}{算了。}

# 5. FALLOUT2 = ENCLAVE_DESTROYED (4, 6)
{240}{}{小心一点。}
{241}{}{让我先把你打得落花流水好了。}

# 6. FALLOUT2 = ENCLAVE_DESTROYED (3)
{250}{}{(那男人转头，并且瞪着你。) 你看起来像一个白痴一样。}
{251}{}{不要生气，我只是想要问问你的意见而已。}
{252}{}{谢谢你诚实的看法。}

# 7. What's going on?
{260}{}{(比着叫你住嘴并且滚开的手势)}
{261}{}{(我看我最好不要烦他)}
