{100}{}{你看到了}
{101}{}{。}

{150}{}{他看起来没什么特别的。}
{151}{}{看起来并没有那么难缠。}
{152}{}{我想他小时候一定时常被欺负。}


{200}{}{你看见一个非常瘦的白种人，他看起来很软件弱。}
{201}{}{他的下巴瘦的都快只有骨头了。}
{202}{}{看起来他7秒都坚持不了。}
{203}{}{看起来你能把他轻松搞定成一块一块的。}

{210}{}{你看见一个蹲着的黑人。他的样子看起来就像一个粗爆的野人。}
{211}{}{他耳朵上有好大一个环，那一定很痛。}

{220}{}{他的手臂好壮．．．}
{221}{}{他的手臂好像有我的大腿粗了。}
{222}{}{当他走起来，就像要地震一样。}
{223}{}{他的样子很可怕。}
{224}{}{他的脸好丑，好像猩猩。}