# QUICK LOOK
{100}{}{你看到一个生病的奴隶。}
{101}{}{你看到一个中毒的奴隶。}
{102}{}{你看到一个奴隶。}

# EXAMINES
# 1. [SICKLY MALE SLAVE]
{150}{}{你看到一个男人，他的眼睛正在左右张望。}
{151}{}{你看到一个生病的奴隶。他看起来相当的害怕，而他的眼睛好像没有办法注视着你。}
{152}{}{你看到一个生病的奴隶。他的衣服到处都是缝补，而他的表皮都破掉了。}
{153}{}{你看到一个生病的奴隶。他正在严重的咳着，而他的衣服上都沾满了血迹。}
{154}{}{你看到一个生病的奴隶。干掉的屎与尿的味道从他身上传出来。}
{155}{}{你看到一个生病的奴隶。他的牙都掉光了，而他的眼睛充满着血丝。}
{156}{}{你看到一个生病的奴隶。他的脸上还有脖子上都长满了疹子。}
# 2. [SICKLY FEMALE SLAVE]
{160}{}{你看到一个女人，她一直看着地上，不敢抬头。}
{161}{}{你看到一个生病的奴隶。她看起来相当的害怕，而她的眼睛好像没有办法注视着你。}
{162}{}{你看到一个生病的奴隶。她好像没有注意到吸血苍蝇停在她的手上。}
{163}{}{你看到一个生病的奴隶。他的衣服到处都是缝补，而他的表皮都破掉了。}
{164}{}{你看到一个生病的奴隶。她每呼一口气都相当的吃力。}
{165}{}{你看到一个生病的奴隶。干掉的屎与尿的味道从她身上传出来。}
{166}{}{你看到一个生病的奴隶。她的脸上还有脖子上都长满了疹子。}
{167}{}{你看到一个生病的奴隶。她看起来好像在哭，但是却没有眼泪。}
# 3. [MALE SLAVE, DRUGGED]
{170}{}{你看到一个男人，他正在注视着远方，没有表情。}
{171}{}{你看到一个中毒的奴隶。他正在四处看着。}
{172}{}{你看到一个中毒的奴隶。你看到他用牙齿把自己的前臂上的肉咬下来，并且开始咀嚼。}
{173}{}{你看到一个中毒的奴隶。他的脸上有微微的笑容，而他的眼睛却没有精神。}
{174}{}{你看到一个中毒的奴隶。他正在望着远方，口水从他的嘴角流出来。}
{175}{}{你看到一个中毒的奴隶。当他看到你时，他痛苦的笑了一下。}
4. [DRUGGED FEMALE SLAVE]
{180}{}{你看到一个女人，正在看着地上。}
{181}{}{你看到一个中毒的奴隶。她正在笑着，而她的嘴角可以看到有一些血迹。}
{182}{}{你看到一个中毒的奴隶。她的手臂上都是割伤还有鞭伤的痕迹。}
{183}{}{你看到一个中毒的奴隶。她很快的在眨着眼，好像眼睛相当的干一样。}
{184}{}{你看到一个中毒的奴隶。她正在抓着自己的手臂，抓到后来皮肤都掉下来了。}
{185}{}{你看到一个中毒的奴隶。在她的裙子上有吐的痕迹。}
# 5. [MALE SLAVE, BEATEN]
{190}{}{你看到一个年轻人，全身都是伤痕。}
{191}{}{你看到一个被打的奴隶。}
{192}{}{你看到一个略小的奴隶。全身都是伤口。}
# 6. [DRUGGED FEMALE SLAVE]
{195}{}{你看到一个发抖的女人，她群身都是伤口，她的衣服都破了。}
{196}{}{你看到一个女性的奴隶。}
{197}{}{你看到一个女性的奴隶，她正在微微的逃跑。}

# FLOAT:
# 7. [SICKLY SLAVE]
{200}{}{::斯::}
{201}{}{::咳咳咳::}
{202}{}{::咳咳::}
{203}{}{::抓伤自己::}
{204}{}{::赶苍蝇::}
# 8. [DRUGGED SLAVE]
{210}{}{::斯::}
{211}{}{*格格的笑*}
{212}{}{嘻}
{213}{}{嘻嘻哈哈}
{214}{}{噫噫噫噫噫噫噫}
# CLICK:
# 9. [SICKLY SLAVE]
{220}{}{::茫然的看着你::}
{220}{}{::望着你看::}
{221}{}{::默默的哭::}
{222}{}{::茫然的瞪着你::}
{223}{}{::呆呆的对你眨眼::}
{224}{}{::又喘又咳::}
{225}{}{::念着你听不懂的话::}
{226}{}{呵－－呵}
{227}{}{::擦着鼻子::}
{228}{}{呵}
{229}{}{嗯嗯．．嗯．::咳::}
# 10. [DRUGGED SLAVE]
{240}{}{::揉眼睛::}
{241}{}{::像猪般的呼声::}
{242}{}{::抓着头，擦着眼::}
{243}{}{嘻嘻嘻}
{244}{}{啊啊啊．．}
{245}{}{呼．呼．}
{246}{}{噫噫噫}
{247}{}{我的眼很黑的。}
{248}{}{嗯．．}
{249}{}{呼．呼．}
{250}{}{呼．呼．}
{251}{}{我好，我坏，我好，我坏。}
{252}{}{两倍的好}
# 11. [BEATEN SLAVE vs. SLAVER]
{260}{}{是的，我有主人了，我的主人有我的卖身契。}
{261}{}{请离开我。我已经属于别人的了。}
{262}{}{我求求你，你有看到两个暗色头发的小孩吗？他们两年前被奴隶贩子卖到北方去了。}
{263}{}{拜托，我是不准和任何人说话的。}
{264}{}{请让我回去工作，我主人很快就回来了。}
{265}{}{如果我的主人把我埋回去奴隶贩子那，我就惨了。}
{266}{}{我有主人了，如果你再和我说话，她是会不高兴的。}
{267}{}{我不能和你说话，我要工作。}
{268}{}{如果我和奴隶贩子说话被抓到，他们就会抓我去试毒品了。}
{269}{}{请离开，奴隶贩子。我们不要任何的麻烦。}
{270}{}{离开？我从没想过要离开这里。我不敢违背我的主人。}

# 12. [BEATEN AND/OR GENERIC SLAVE]
{280}{}{如果我们抓到我与你说话，他们就会开始用我来进行实验的。}
{281}{}{我本来是属于另一个奴隶贩子的，但是他几天前死于嗑药过度。}
{282}{}{他们用我们来测试药品，有一些是有毒的。}
{283}{}{我主人．．对我很好。}
{284}{}{我主人不准我和其他人说话。}
{285}{}{我没有经过准许，无法与你说话。}
{286}{}{请让我回去工作，我主人很快就回来了。}
{287}{}{如果被我主人抓到我和你说话，他会打我的。}
{288}{}{我的主人很好，他并不常打我。}
{289}{}{我并没不见小孩，我主人对我很好。}
{290}{}{我是从北边的部落来的，那里的生活比这里好的多。}
{291}{}{我是在丹恩那里被抓到的。}
{292}{}{我不能和你说话，我要工作。}
{293}{}{在主人回来前，我必需完成我的工作。}
{294}{}{说话是违反规定的。}
{295}{}{请走开，我求你。你只会造成我的麻烦而已。}
{296}{}{离开？要逃到那去？这荒野中到处都有怪物会吃掉逃走的人。}
{297}{}{奴隶通常要是生病的话就会被杀。}
{298}{}{我是从新里诺来的奴隶。有两个奴隶生病摔倒，奴隶贩子就射杀了他们。}
{299}{}{是的，我能帮你什么吗？}
{300}{}{我听谣言说这里有条地铁，但是并没人敢试着离开。}
{301}{}{茱莉亚离开了，但隔天就被抓到葛洛沙去，他们把她绑在轮子上活活的饿死。}
{302}{}{逃跑者都会被奴隶贩子抓到葛洛沙去处死。}
{303}{}{不，我不知道我的家人现在在那里。有时会想起他们，但却不是经常。}
{304}{}{新里诺是地狱，不过在某种情况下，仍然比丹恩要好的多。}
{305}{}{::害怕的转身离去::}
{306}{}{::害怕的忽视你的存在::}
{307}{}{只要你记住你新主人要的，鞭打就不会常发生。}
{308}{}{我是很久以前被奴隶贩子抓到的，我几乎记不得了。}
{309}{}{我有两个小孩，但是他们被卖到北方去了。我希望他们去的地方比这里还好。}
{310}{}{我很抱歉，但是我没时间说话。}
{311}{}{我主人最近对我很不高兴，他说如果我再让他生气它就要把我卖给马厩。}
{312}{}{逃跑的奴隶不是死在葛洛沙就是被卖到马厩去实验。}