#############################################################
#  Message File: obj_dude.msg                               #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: April 14, 1998                                  #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when	    #
#  glanced and and examined.				    #
#############################################################
{100}{}{}
{101}{}{}

#############################################################

{110}{}{你的脚真的很痒。}
{120}{}{你两只脚都长了很可怕的肉瘤。}
{130}{}{你的鞋子觉得越来越紧了；那一些肉瘤开始发炎了。}
{140}{}{那一些肉瘤长得大到好像你多了一只脚趾似的。不过，至少你再也感觉不到那烦人的痒感了。}
{141}{}{我的天，是贝丝！}

{150}{}{你得到了}
{151}{}{点经验值，因为你取得了伊甸园创造器。}