{100}{}{你看到一个穿着英克雷军动力装甲的士兵。}
{101}{}{你报看到葛兰耐特上校。}
{102}{}{你看到一个有着上校标制的士兵。}
{103}{}{让我们去抓那个疯子吧。}
{104}{}{是啊，让我去吧！}
{105}{}{上吧！}
{106}{}{准备好了。}
{107}{}{让我们去把那怪物抓回来吧！}
{108}{}{上！}
{109}{}{我准备好了。}
{110}{}{我们上！}
{111}{}{上吧！}
{112}{}{我喜爱杀掉那些白痴。}
{113}{}{你可以走了。}
{114}{}{我什么都没有看到。}
{115}{}{我们不是在找机器人。}
{116}{}{快走。}
{117}{}{我对杀人感到厌烦了。}
{118}{}{上吧！}
{119}{}{稍息。}
{120}{}{变种人，在外面给我小心点。}
{121}{}{祝你好运，变种人，你需要的。}
{122}{}{等一下！你在这边干什么？}
{123}{}{我正想要回到我的同胞那边去。}
{124}{}{不关你的事。}
{125}{}{我没有时间回答你的问题。}
{126}{}{你是谁？}
{127}{}{你知道那怪人，也就是荷瑞根，刚刚才冲过这边。}
{128}{}{那是谁啊？}
{129}{}{我想你想错了。我正想要干涉那件事。现在，你他妈的在这边干什么啊？}
{130}{}{我正想要回到船上，这样我才能跟我的族人一起逃走。}
{131}{}{你最好空些时间出来。}
{132}{}{为什么？你是什么意思？}
{133}{}{我没有时间，再叫我就把你杀了。}
{134}{}{随便你，但是不要跟我说我们没有警告过你。}
{135}{}{警告我？什么啊？}
{136}{}{是啊，警告的对啊。去死吧，英克雷军的败类。}
{137}{}{他是一个基因工学的产物。原本是总统的保镳。现在他整个人几乎都变成机器了。}
{138}{}{听起来是一个坏消息。}
{139}{}{我杀过比他更厉害的人咧，等一下他就会变成地上的一团污渍了。}
{140}{}{我好害怕啊。住口！}
{141}{}{他很厉害的，他速度快、强壮、而且很坏。我曾看过他怎样对待变种人，那并不是很漂亮的景像。}
{142}{}{我不是一个变种人．．他做了什么？}
{143}{}{我不想要提起那件事。那会让我做恶梦。这样吧，让我跟你说，那些墙上黏的东西并不是锈．．}
{144}{}{听起来我要对付他是很难的一件事。}
{145}{}{你还真有种啊，不过，我真同情你，马上就要被他杀了。}
{146}{}{同情？让我告诉你，你们发电场的电脑就快要融毁了，你们就快要变成死尸了，除非}
{147}{}{我不需要同情。我只要你去死！}
{148}{}{我没有事可以做。你们反正都要死了。享受在世界上最后的几分钟吧。}
{149}{}{除非什么？！？}
{150}{}{除非你帮我一起杀了荷瑞根让我回到船上去。}
{151}{}{算了。我没有时间跟你谈。再见。}
{152}{}{喔，是啊。如果反应炉有问题，那为什么灯还亮着？嗯？}
{153}{}{那只是“紧急”的灯光而已。嘿，你们都要死了，除非。}
{154}{}{我没有时间再跟你谈了。希望你们都很会游泳。再见。}
{155}{}{你还真会说故事啊。你笑死我了。如果你跟荷瑞根交手，能够撑过一分钟就算新记录了。祝你好运，变种人。}
{156}{}{我最好先暖身一下．．拿你们来暖身。}
{157}{}{你最好希望那个装甲会浮起来。再见。}
{158}{}{好，好。我们帮你好了。我才不想要淹死咧。}
{159}{}{算你聪明。让我们去对付他吧。我们得要快走了。}
{160}{}{ＥＣ部的葛兰耐特上校。}
{161}{}{ＥＣ部？}
{162}{}{英克雷控制部。我们是负责防护基地的。}
{163}{}{喔，我知道了。}

{170}{}{除非你帮我一起杀了荷瑞根让我回到我的飞鸟上去。}