{100}{}{你看到一个穿着蓝色衣服的男人。}
{101}{}{你看到马丁．富罗彼希尔，第１３号避难所囚犯的代言人。}
{102}{}{你看到一个穿着跟你的衣服一样的男人。}
{103}{}{把我们救出去！}
{104}{}{把门的能源关掉。}
{105}{}{关电之后，我们就能出去了！}
{106}{}{把我们弄出这鬼地方！}
{107}{}{电关起来！门就开了！}
{108}{}{我们完蛋了。}
{109}{}{在他们进行更多实验之前，把我们救出去吧。}
{110}{}{这些人是谁啊？}
{111}{}{为什么是我们？}
{112}{}{我们得要离开这个地方。}
{113}{}{嘿你，这边！}
{114}{}{你在找我吗？}
{115}{}{想要知道发生了什么事吗？}
{116}{}{救命！}
{117}{}{我是马丁，这边。}
{118}{}{嘿你，我是富罗彼希尔，这边！}
{119}{}{在这边！}
{120}{}{嘿嘿嘿！}
{121}{}{到这边来！}
{122}{}{我可以告诉你你想要知道的事。}
{123}{}{我的名字是马丁。}
{124}{}{我可以告诉你发生什么事了。}
{125}{}{你好，我是马丁．富罗彼希尔。是这一些人的代言人。谢谢主你来了。}
{126}{}{你想要知道些什么？}
{127}{}{很漂亮的衣服，跟我的一样。你们是谁啊？}
{128}{}{你们这些人在这边干什么？}
{129}{}{你是监督者吗？}
{130}{}{你们这些人是怎么到这边来的？}
{131}{}{很高兴见到你，马丁，但是我还有人等我去拯救。再见。}
{132}{}{是，我希望那就是为什么你在这边的原因。你得要把我们放出去。}
{133}{}{救你？我原本是要救我自己的族人而已。}
{134}{}{当然，我不会让任何人困在这个地方的。}
{135}{}{你们这些人在这边干什么啊？}
{136}{}{他们用我们来实验一种致命病毒的解药。}
{137}{}{什么样的病毒呢？}
{138}{}{那听起来很不好。让我问你一些其它的事。}
{139}{}{你很幸运。你现在也许知道我祖先，避难所住民，的痛苦了吧。我希望你们都受苦。再见。}
{140}{}{他们叫它ＦＥＶ病毒。在杀死你之前，它会在你身上产生很可怕的效果。}
{141}{}{那听起来很可怕，为什么他们要在人的身上做实验呢？}
{142}{}{他们需要纯种的人类来做实验。因此他们把我们抓了过来。}
{143}{}{他们抓了你？怎么抓，从那抓来的？}
{144}{}{他们从避难所的前门进来的，他们不知道从那边取得的进来的密码。他们将门打开，穿着装甲的士兵们将我们带进了飞鸟，然后飞到这边来。然后就开始进行实验了。（他开始发抖）}
{145}{}{那听起来很可怕。让我问你一些其它的事。}
{146}{}{避难所？你是从那一个避难所来的？}
{147}{}{当然是第１３号避难所。}
{148}{}{我到那边去找伊甸园创造器。}
{149}{}{我到了那边去找伊甸园创造器来救我的同胞，可是你们都不见了。}
{150}{}{我正在找那个地方。嘿，你是监督者吗？}
{151}{}{伊甸园创造器？我们有一些，你当然可以拿一个去。我好像看到一个士兵将我们的一个伊甸园创造器拿进了飞鸟之中。}
{152}{}{你看到他们拿走了一个伊甸园创造器？你知道它被放在那里吗？}
{153}{}{没关系，我已经拿了一个伊甸园创造器了。让我问你一些其它的事。}
{154}{}{我不知道他们把它放在那里，不过我倒是有听到他们说要把它放在下面那一层中。}
{155}{}{太好了，谢谢你。我要走了。}
{156}{}{啊，让我问你一些其它的事。}
{157}{}{等一下！你得要把我们救出这个地方吧。}
{158}{}{我会的。我现在到到下层去把发电机关起来，这样才能放你们出来。当电力中断的时候，跑到地面上去，我准备了一艘船在那边。}
{159}{}{我应该要如何做呢？}
{160}{}{在将我的祖先驱出避难所之前，你就应该要考虑了。我希望你们都死在这边，再见。}
{161}{}{谢谢你，祝你好运。}
{162}{}{再见，祝你好运。}
{163}{}{谢谢，但是先让我问你一些问题。}
{164}{}{我有感觉我会需要所有的运气的。}
{165}{}{要让力场失效，我想你得要将电源给切断。}
{166}{}{我应该要如何才能达到那个目地呢？}
{167}{}{我听说电力是由一部大型的电脑所控制的，它就在下面三层的地方。如果你能将它破坏，我们就能离开了。}
{168}{}{好主意。我可以用我的炸药将它炸毁。然后你们就可以跑到上面到我的船中。我随后就到。}
{169}{}{很好的主意，但是我不知道要如何将反应炉炸掉。我没有任何的炸药。}
{170}{}{只要有士兵看守的地方，就一定会有军火的，那边一定会有炸药的。}
{171}{}{好主意，我能够在取得炸药之后将电脑炸掉。然后你们就可以跑到上面到我的船中。我随后就到。}
{172}{}{原本有监督者，但是他做了坏事并且离开了避难所。}
{173}{}{我也不怪你们，曾也一个监督者把我的祖先给赶走了。}
{174}{}{那是多久以前的事？有没有八十年呢？}
{175}{}{是的，那确实是八十年前。你怎么知道呢？}
{176}{}{八十年前，一个英雄拯救了我们的避难所，但是监督者却将他给放逐了。有许多人跟随着他，然后他们就音讯全无了。我们对那件事相当的抱歉。}
{177}{}{嘿！你是说我们的同胞，他们都是从第１３号避难所来的。}
{178}{}{让我问你一些其它的问题。}
{179}{}{我不认为你们受了足够的罚，再见。}
{180}{}{那是我们的避难所！没想到我们又要让避难所住民的后人拯救！}
{181}{}{那是我们的避难所！没想到我们又要让避难所住民的后人拯救！}
{182}{}{我真希望我能知道如何拯救你。}
{183}{}{我会考虑一下的。}
{184}{}{真是一个奇妙的巧合。让我问你一些其它的事。}

{190}{}{这样吧，我到楼下的能量室关上电源，力场就会消失，你们就跑到顶层的飞鸟里，我会去那找你们的。}
{191}{}{好主意。我会用炸药把这个电脑炸上天的。然后你们就跑到顶层的飞鸟里，随后我会跟上你们的。}
{192}{}{好主意。我会用炸药把这个电脑炸上天的。然后你们就跑到顶层的飞鸟里，随后我会跟上你们的。}