{100}{}{你看到一个穿着实验服的秃头。}
{101}{}{你看到汤姆．莫雷，他是原子能源委员会的主席。}
{102}{}{你看到一个相当紧张的男人。}
{103}{}{我的机器！我漂亮的机器完了（哭泣）}
{104}{}{我们完蛋了。}
{105}{}{没有了电脑，我们的反应炉将会融毁！}
{106}{}{我不会游泳啊。}
{107}{}{也许我可以修好它。}
{108}{}{为什么警铃在响呢？}
{109}{}{这边发生了什么事了？}
{110}{}{不要慌张。不要慌！！！！！！！！！}
{111}{}{好，冷静下来。}
{112}{}{也许这只是一个演习而已。}
{113}{}{回到禁闭层去。}
{114}{}{你真的无法分辨不同。}
{115}{}{你的额头都突出来了。}
{116}{}{你的头骨不够大，对不对？}
{117}{}{如果你表现的好，回到牢里后我会给你一个棒棒糖的。}
{118}{}{你，你不应该在这边穿着那个东西的。}
{119}{}{我想要在那边穿着我的装甲是我的自由。}
{120}{}{喔，抱歉长官。那我走了。}
{121}{}{好吧，那我只好报告你了。}
{122}{}{去啊，随便你。}
{123}{}{喔，请不要那样做。我这就走，再见。}
{124}{}{我是汤姆．莫雷。原子能源委员会的主席。我负责这边的原子发电场。你他妈的是谁，在这边干什么？}
{125}{}{你他妈的要干什么？}
{126}{}{我需要将原子反应炉关起来。}
{127}{}{我只不过是对你们反应炉的运作方式感到相当的好奇而已。}
{128}{}{我得要将你们全部杀光。}
{129}{}{救命！救我！救命！}
{130}{}{入侵者！警报！}
{131}{}{逃命吧！有土人在这边！}
{132}{}{卫兵！救命命命命～！}
{133}{}{侵入者警报！侵入者警报！}
{134}{}{关起来？你发疯了吗。我不会让你把我的反应炉关起来的。}
{135}{}{是，你最好跟我说如何进行，不然我就会把你杀了。}
{136}{}{你是说关起来吗？我很抱歉，我只不过是想要知道你的反应炉是如何运作的。}
{137}{}{喔，那是你的？我很抱歉，我并不知道。好吧，再见。}
{138}{}{让我告诉你，我会帮你，不过如果你关得太快的话，它就会过热。}
{139}{}{我不管。去把反应炉关起来，不然我就像一条鱼一样把你给切开。}
{140}{}{那听起来很危险。好吧，我看算了。再见。}
{141}{}{你在骗我，你不敢的。}
{142}{}{我敢的，如果你不帮我，你就死定了。}
{143}{}{我原本是要给你与我合作的机会，但你却不识相。为了怕你启动警铃，我只好杀了你。}
{144}{}{嘿，我只是在开玩笑而已。你们的反应炉到底是如何运作的？}
{145}{}{是，我想你是对的。你最好不要发出任何的声音，再见。}
{146}{}{好，好。我愿意了。不要生气。但是我得要告诉你。当我把轴心棒放下去时，炉将会马上过热。如果我们就这样把炉关起来，整个反应炉都会爆炸－那我们就得搬离这里了。} 
{147}{}{是啊，随你说。马上去把那东西给我关上！}
{148}{}{那听起来很危险。也许我应该要找另外一个方法。我当然不想要伤害这边的人。再见。}
{149}{}{我才不会让这边的人有危险呢，不会的。}
{150}{}{我很抱歉听到那件事。我猜我只好将你给杀了。不要怪我。}
{151}{}{那为什么会危害到大家的生命呢？告诉我你的反应炉是怎样运作的？}
{152}{}{我猜我找好另寻方法将电源关上了。我走之后，你最好不要出声。再见。}
{153}{}{知道了。好，嗯，将这个调到绿色。 (他正操作着一个控制台。) 好，好了，不过这将不会持续稳定太久。}
{154}{}{你做的很对。现在，我得要走了。你最好乖乖的待在这里不要出声。}
{155}{}{做得好，现在，我得要杀死你了。抱歉，但是我不能留下任何的证人。}
{156}{}{我得要走了。再见。}
{157}{}{我并不是负责那么多的反应炉操作。在反应炉北方的中央电脑才是控制着大部份的电厂功能。如果没有那电脑的话，我们就不会有能源的。}
{158}{}{没有能源？}
{159}{}{不会有太多的能源。不过，照明、生命维持、还有防御系统应该还会运作一段时间，但是力场还有其它使用大量电力的系统将会马上失去作用。}
{160}{}{听起来你们将会几乎失去所有重要的系统。}
{161}{}{对啊，那将不会是一个好情况的。不过，所有的铁门在那个情况之下将会关上，而且不论如何都不会打开。那就是一个备份的防御系统。}
{162}{}{真有趣。还有一些东西我想要知道。}
{163}{}{那就是我所想要知道的。谢谢你，你帮了我不少。不过我走之后，你最好乖乖的不要张扬。}
{164}{}{谢谢，很可惜你将不会活着见到的。再见了。}