{100}{}{你看见一部电脑终端机。}
{101}{}{你看见一部电脑终端机。}
{102}{}{你看见DataPlex 2000的电脑终端机。有64G的记忆体，是最新电脑技术。只可惜它坏掉了。}
{103}{}{你看见DataPlex 2000的电脑终端机。有64G的记忆体，是最新电脑技术。}
{104}{}{欢迎进入波斯当网路，请输入你的选择：}
{105}{}{登入。}
{106}{}{线上求助。}
{107}{}{离线。}
{108}{}{这个终端机正在拨着印第安人的电影，相当的无聊。}
{109}{}{这个终端机正在显示着一个训练射击的程式。}
{110}{}{这个终端机正在显示着一些美术品的图片。}
{111}{}{你看见个一个终端机，它显示着一个绿色炸弹沿着画面上的对角线移动着。}
{112}{}{这个终端机上面显示着：“你现在可以安全的将电脑关上。”你不知道那是什么意思。}
{113}{}{你看见红色、绿色、以及蓝色的灯亮所组成的图片．．}
{114}{}{你看到一个丑陋的脸正在看着你．．等一下．．原来这一个终端机是关着的。}
{115}{}{你在画面上看不到什么。}
{116}{}{你看到画面上显示着：“正在第一次启动“门９８”作业系统．．”}
{117}{}{嗯．．你看到这台终端机上面正在执行着“异尘余生二代”，哇！真好，不但有多人连线功能，而且是３Ｄ的！}
{118}{}{输入使用者代号：}
{119}{}{(让我试试看)列出所有使用者。}
{120}{}{(让我试试看这有没有用．．)史密斯．Ｊ。}
{121}{}{返回前一页。}
{123}{}{我想我最好还是在别的地方进行这件事好了。}
{124}{}{正在显示中．．(电脑显示出约５００多个名字。)}
{125}{}{正在显示中．．(电脑显示出许多的名字。)}
{126}{}{选择使用者代号并且离线：}
{127}{}{(这一个代号应该有足够的系统权限。)史密斯．Ｊ。}
{128}{}{(这一个代号看起来相当的特别。)总统专用安全登入。}
{129}{}{(这一个代号看起来有着相当大的系统权限。)莫雷．Ｔ。}
{130}{}{(这一个代号的权限还不错。)卡林．Ｃ医生。}
{131}{}{(这一个代号看起来有着不错的系统权限。)柏德．Ｄ。}
{132}{}{(我等一下再来试试好了。)离线。}
{133}{}{请选择：}
{134}{}{		原子能发电机运作程序}
{135}{}{		安全状态？}
{136}{}{下载原子能发电机运作程序}
{137}{}{安全状态}
{138}{}{回到使用者代号页：}
{139}{}{请选择：}
{140}{}{		安全程度：目前状态}
{141}{}{		化学部门：计划状态报告}
{142}{}{		原子能发电机运作程序}
{143}{}{		安全状态？}
{144}{}{安全程度：目前状态}
{145}{}{下载化学部门：计划状态报告}
{146}{}{下载原子能发电机运作程序}
{147}{}{安全状态}
{148}{}{回到使用者代号页：}
{149}{}{请选择：}
{150}{}{		国家状态：目前状态}
{151}{}{		（词语列表）}
{152}{}{		安全程度：目前状态}
{153}{}{		化学部门：计划状态报告}
{154}{}{		原子能发电机运作程序}
{155}{}{		安全状态？}
{156}{}{国家状态：目前状态}
{157}{}{下载词语列表}
{158}{}{安全程度：目前状态}
{159}{}{下载化学部门：计划状态报告}
{160}{}{下载原子能发电机运作程序}
{161}{}{安全状态}
{162}{}{回到使用者代号页：}
{163}{}{选择：安全状态？}
{164}{}{安全程度：目前状态}
{165}{}{结束连线}
{166}{}{下载完成。}
{167}{}{国家状态：目前状态}
{168}{}{下载词语列表}
{169}{}{安全程度：目前状态}
{170}{}{下载化学部门：计划状态报告}
{171}{}{下载原子能发电机运作程序}
{172}{}{回到使用者代号页：}
{173}{}{下载完成。}
{174}{}{下载词语列表}
{175}{}{安全程度：目前状态}
{176}{}{下载化学部门：计划状态报告}
{177}{}{下载原子能发电机运作程序}
{178}{}{安全状态}
{179}{}{回到使用者代号页：}
{180}{}{下载完成。}
{181}{}{国家状态：目前状态}
{182}{}{安全程度：目前状态}
{183}{}{下载化学部门：计划状态报告}
{184}{}{下载原子能发电机运作程序}
{185}{}{安全状态}
{186}{}{回到使用者代号页：}
{187}{}{军营警戒区：安全炮塔正在备战状态。}
{188}{}{军营警戒区：安全炮塔正在正常状态。}
{189}{}{军营警戒区：安全炮塔正在解除警戒保养状态。}
{190}{}{实验品拘禁区：安全炮塔正在备战状态。}
{191}{}{实验品拘禁区：安全炮塔正在正常状态。}
{192}{}{实验品拘禁区：安全炮塔正在解除警戒保养状态。}
{193}{}{研究及发展计划地区：安全炮塔正在备战状态。}
{194}{}{研究及发展计划地区：安全炮塔正在正常状态。}
{195}{}{研究及发展计划地区：安全炮塔正在解除警戒保养状态。}
{196}{}{高级官员办公室地区：安全炮塔正在备战状态。}
{197}{}{高级官员办公室地区：安全炮塔正在正常状态。}
{198}{}{高级官员办公室地区：安全炮塔正在解除警戒保养状态。}
{199}{}{资料处理室以及发电地区：安全炮塔正在备战状态。}
{200}{}{资料处理室以及发电地区：安全炮塔正在正常状态。}
{201}{}{资料处理室以及发电地区：安全炮塔正在解除警戒保养状态。}
{202}{}{改变安全程度}
{203}{}{国家状态：目前状态}
{204}{}{下载词语列表}
{205}{}{下载化学部门：计划状态报告}
{206}{}{下载原子能发电机运作程序}
{207}{}{安全状态}
{208}{}{回到使用者代号页：}
{209}{}{下载完成。}
{210}{}{国家状态：目前状态}
{211}{}{下载词语列表}
{212}{}{安全程度：目前状态}
{213}{}{下载原子能发电机运作程序}
{215}{}{安全状态}
{216}{}{回到使用者代号页：}
{217}{}{下载完成。}
{218}{}{国家状态：目前状态}
{219}{}{下载词语列表}
{220}{}{安全程度：目前状态}
{221}{}{下载化学部门：计划状态报告}
{222}{}{安全状态}
{223}{}{回到使用者代号页：}
{224}{}{本终端机正在进行全面性的自我测试，请使用另外一部终端机。}
{225}{}{欢迎来到波斯当网路线上求助系统。很抱歉，您目前的求助档案已经太旧了。您要更新求助档案吗？（是／否）}
{226}{}{是}
{227}{}{不，回上一页}
{228}{}{求助档案更新功能无法在试用板的波斯当网路软体使用。请购买完整版的软体。您的试用版本已经过期59439天了。}
{229}{}{回到上一页}
{230}{}{结束程式}
{231}{}{需要总统密码。目前可以执行的功能有：反暴动功能、紧急系统关闭功能。}
{232}{}{(让我试试看这一个功能。)选择反暴动功能。}
{233}{}{(让我试试看这一个功能。)紧急系统关闭功能。}
{234}{}{(也许我应该试试别的功能。)回到使用者代号页：}
{235}{}{(我还是不要乱动好了。)离线。}
{236}{}{反暴动功能，可以让发生暴动的时候，启动所有武器，并且攻击最具有威胁性的目标。目前仅能于入口地区使用。}
{237}{}{(那听起来是相当有用的功能。)启动反暴动功能。}
{238}{}{(下一次再试试看好了。)回去上一页。}
{239}{}{(我不想要再玩电脑了。)离线。}
{240}{}{总统权限已确认。你好，总统先生．．紧急反暴动功能启动．．目标已确认。}
{241}{}{(我想我应该看看会发生些什么事。)}
{242}{}{总统权限已确认。你好，总统先生．．紧急反暴动功能启动．．＊发生错误＊．．请填表格FG-I-106-32-0635申请修理。谢谢您使用避难所科技的产品。}
{243}{}{(这也许是指停船的地方。我应该到那边去试试。)回到使用者代号页：}
{244}{}{(不知道我还能够试些什么功能。)回到上一页。}
{245}{}{需要总统钥匙才能使用这一个功能。}
{246}{}{(不知道我还能够试些什么功能。)回到上一页。}
{247}{}{紧急系统关闭可以暂时性的将所有地区的安全系统关上。这一个系统可以进行自我检查，然后进行重新开机。}
{248}{}{(听起来是相当好玩的功能。)启动紧急系统关闭。}
{249}{}{(下一次再试试看好了。)回去上一页。}
{250}{}{(我不想要再玩电脑了。)离线。}
{251}{}{找到总统钥匙卡，你好，总统先生．．紧急系统关闭功能启动．．自我测试中．．第一系统．．第二系统．．第三系统．．。}
{252}{}{(我看我还是下次再玩好了。)回去上一页。}
{253}{}{(我看在这系统在自我检察时，我还是先走好了。)离线。}
{254}{}{无法找到总统钥匙。无法进入系统。}
{255}{}{(不知道我是不是可以骗骗这一个系统，让我试着侵入吧。)}
{256}{}{(喔，至少我试过了。)回去上一页。}
{257}{}{安全钥匙扫瞄器出现问题．．重新设定扫瞄器．．}
{258}{}{(那就是我的机会．．现在，只要我能够让电脑以为我有总统钥匙卡的话．．)}
{259}{}{(可恨，没有用。)回去上一页。}
{260}{}{扫瞄器重新设定完成。重新扫瞄中．．}
{261}{}{(来吧，来吧！)你很快的敲打着键盘。}
{262}{}{发现非法的输入程序。无法继续．．已经要求维修人员前来修复。}
{263}{}{操，那并不是我要的啊。}
{264}{}{经过了10分钟疯狂的操作，最终你侵入了主通路文件。几分钟后你找到了你想去的地方。}