{100}{}{你看到一个高大、瘦小的男人。他正在看着你。}
{101}{}{你看到贾序．罗伦斯，断气酒吧的老板。}
{102}{}{你看到一个正在上下打量着你的男人。}
{103}{}{请离开这里。}
{104}{}{你在这边干什么，白痴？}
{105}{}{这不是你可以来的地方。}
{106}{}{滚，你这白痴！}
{107}{}{在你把这边弄脏之前给我滚出去。}
{108}{}{你好，朋友。我叫贾序．罗伦斯。是这边的老板。}
{109}{}{我可以帮你什么吗？}
{110}{}{这到底是一个什么地方？}
{111}{}{我想要来一杯。}
{112}{}{我想要请在场每一个人都来一杯。}
{113}{}{我想要为我这边的朋友们买一杯。}
{114}{}{最近镇里发生什么事了？}
{115}{}{我只是经过而已，再见。}
{116}{}{没有那种东西。}
{117}{}{请叫你的 *朋友* 出去。}
{118}{}{这里不是马戏团，请马上离开。}
{119}{}{那不可以进到这边来。}
{120}{}{我们不服务那种东西，滚。}
{121}{}{这里是断气酒吧以及殡仪馆。一个服务的场所。}
{122}{}{那真是一个相当奇怪的组合啊。}
{123}{}{嗯．．}
{124}{}{如果我想要买一副棺材，要怎样做呢？}
{125}{}{我要如何才能够得到葬礼服务呢？}
{126}{}{我会离你那些棺材远远的。}
{127}{}{当然，那一共是$5。}
{128}{}{这是你的钱。}
{129}{}{我想我现在还是不要喝啤酒好了。不过，让我问你一些事。}
{130}{}{你真大方。那一共是$50。}
{131}{}{拿去，这是你的钱。}
{132}{}{让我问你一些问题。}
{133}{}{那一共是}
{134}{}{那是值得的。拿去。}
{135}{}{再想一下，我看我还是不要让别人都喝醉。不过，让我问你一些事。}
{136}{}{你的康凯真是帮助了我的生意啊。不过，再给我一些其它的事做吧。}
{137}{}{我的生意一向都相当的平淡。就像一个坟墓一样的安静，不过，最近以来，那倒是没有什么意义。}
{138}{}{什？那是什么意思？}
{139}{}{光是埋葬死人并不能养活我自己－因此，我便开始卖酒类饮料了。}
{140}{}{让我问你一些其它的事。}
{141}{}{当别人看到这边的棺材，难道不会觉得可怕吗？}
{142}{}{我要走了，再见。}
{143}{}{那一些矿工相当喜欢咧，让他们觉得活着是很幸运的事。}
{144}{}{我觉得你有一些问题。}
{145}{}{这样啊，让我问你一些其它的事。}
{146}{}{我想也许有一些人会那样觉得吧。但是我并不是其中一个。}
{147}{}{哼，我还听说土人会吃人咧，这种事对你还说应该是小意思才对。}
{148}{}{不然我们要怎么办？}
{149}{}{嘿，我们吃之前会先煮咧。我们并不是野人啊。}
{150}{}{那真是荒谬，你是从那里听说的？}
{151}{}{我不知道，但是，你们的牙齿要不是为了吃人，为什么都是尖的呢？回答我！}
{152}{}{我才不．．算了。让我问你一些其它的问题。}
{153}{}{谢谢你，还有什么我可以帮你的吗？}
{154}{}{事实上，还有一些东西。}
{155}{}{没有，谢谢你。}
{156}{}{你是什么意思？}
{157}{}{我只不过是说那听起来是一个相当不寻常的组合而已。}
{158}{}{没事。让我问你一些问题。}
{159}{}{我的意思是说我要去另外一个没有那么可怕的地方喝酒而已。再见。}
{160}{}{我最近花了很多时间将隔壁坟场的死人重新的下葬。有人，或是有一些东西，一直的将那些尸体挖出来。又不是说那些尸体有什么值钱的，真不知道为什么会被挖出来。}
{161}{}{那些坟被挖开了？}
{162}{}{你怎知那些尸体没有什么值钱的东西在他们身上？}
{163}{}{大概是老鼠干的好事吧。让我问你其它的事。}
{164}{}{嗯，我不却定，但是我只是猜猜而已。嘿，来一杯免费的啤酒吧。}
{165}{}{我不知道你想要影射什么，但是我很不高兴。}
{166}{}{啤酒谢谢啦！你说有东西将他们挖出来是什么意思？}
{167}{}{你说有东西将他们挖出来是什么意思？}
{168}{}{我什么都没有看见，但是每一个星期都会有坟被挖开。真不知道为什么有东西会想要那样做。}
{169}{}{那真是奇怪啊。}
{170}{}{那真是令人困惑。现在所有的矿工都说他们死后宁可不要下葬，也不要被别人挖出来。我并不介意将可爱的人留着，但总不能每一个死人都不下葬吧。}
{171}{}{让我问你一些其它的事。}
{172}{}{那真是一个谜啊。我要走了，再见。}
{173}{}{好吧，如果你有先煮过的话．．等一下，那还是吃人啊！你真是令我作呕。}
{174}{}{不要认真了，我只不过是在开玩笑而已。我们只不过是吃他们的一部份而已。}
{175}{}{一部份？那些部份呢？}
{176}{}{谁管啊。一部份就是任何的一部份。}
{177}{}{让我问你一些其它的问题。}
{178}{}{是啊，我懂了．．}
{179}{}{让我问你一些其它的问题。}
{180}{}{这样说来，我有一点饿了。再见。}
{181}{}{哼，食人族就是食人族。}
{182}{}{嘿，我们吃之前会先煮咧。我们并不是野人啊。}
{183}{}{放开我的腿，你这食人族！我还需要它咧。去找其他的人吃吧。}
{184}{}{不要怕，反正你看起来也很难吃。哈哈哈，我只是开玩笑而已。让我问你一些其它的问题。}
{185}{}{我会去看看的，但是如果我找不到更好吃的，我会回来找你的。再见。}
{186}{}{打算要买不动产吗？}
{187}{}{不，让我问你其它的问题。}
{188}{}{不，再见。}
{189}{}{我告诉你，马力安警长是不会喜欢那种行为的。}
{190}{}{让我问你一其它的问题。}
{191}{}{这样啊．．再见了。}