{100}{}{又是一个卫兵。一定有人养了一窝卫兵，他们长得都一模一样。}
{101}{}{又是一个卫兵。他看起来并不欢迎你。}
{102}{}{你仔细得看看他，你确定他是个卫兵。}
{103}{}{你没有得到允许可以在这出现的。}
{104}{}{我可以看你的通行证吗？}
{105}{}{这是政府地盘。离开吧，陌生人。}
{106}{}{你是新来的？}
{107}{}{如果你还没和卡洛森谈过，那我劝你快去。}
{108}{}{卡洛森正在等你。}
{109}{}{卡洛森现在要见你。}
{110}{}{我希望你想要说的是很重要的事，因为卡洛森是很忙的人。}
{111}{}{他在里面，我建议你在里面待太久。}