{100}{}{一个变种人－一个没有骨气的人。}
{101}{}{那是廉尼，记得吗？那个讨厌的人。}
{102}{}{这家伙真是特别。除了他是绿色的而且很丑之外，他身上的伤痕比一个老妓女还要多。这一个人确定是一个战士。}
{103}{}{我是廉尼，而你是人渣，滚！}
{104}{}{你为什么要烦廉尼呢？}
{105}{}{你想要廉尼怎样，你这讨厌的人类？}
{106}{}{如果你再碰我的话，我就送你升天。}
{107}{}{很高兴见到你，我是廉尼－你一定就是狗屎脑吧，哈哈哈！}
{108}{}{告诉你我叫廉尼，你这奴隶。}
{109}{}{廉尼想问你为什么要跟这人类在一起呢？}
{110}{}{廉尼才不跟奴役变种人的王八在一起呢。}
{111}{}{廉尼说你跟你们可以去死！}
{112}{}{廉尼你不是好惹的。}
{113}{}{嘿，白皮肤的小子回来啦！}
{114}{}{不要烦我，人类！}
{115}{}{滚！}
{116}{}{有事吗？找人换你的尿布吗？}
{117}{}{你真顽固。}