{100}{}{你看到一个穿着沾满污诟、血迹衣服的男人。}
{101}{}{那是他们抓到的歹徒人犯。}
{102}{}{他的脸上还有手上都有着刀疤，他的眼神一看就好像是坏蛋的样子。}
{103}{}{你在浪费你的时间。我没有什么跟你好说的。}
{104}{}{滚，不要烦我。}
{105}{}{为什么突然很臭呢？}
{106}{}{你要干什么，逼我说话吗？}
{107}{}{你吓不了我的。}
{108}{}{走开。}
{109}{}{啊！你居然想要杀我？卫兵！}
{110}{}{说话，不然我就把你杀了。}
{111}{}{没有人可以帮你的，如果你想要活着，就说！}
{112}{}{好啦！你想要知道什么？不要再伤我了。}
{113}{}{告诉我第１５号避难所的事。}
{114}{}{关于第１５号避难所，你知道些什么？}
{115}{}{我并不是一个重要的人，达里安才是，去跟他谈谈吧。}
{116}{}{真的，我什么都不知道！知道的我都说了！不要伤我了。}
{117}{}{我不会中计了！}