{100}{}{你看到一个半狗半机器的奇怪东西。它看起来好像启动了。}
{101}{}{那是机器狗！大家都喜欢的宠物！}
{102}{}{这东西是半狗半机器的。}
{103}{}{汪！ <喀> 汪！}
{104}{}{...吱...}
{105}{}{.呜...我不是狗狗。}
{106}{}{吼～～～～}
{107}{}{汪！汪汪汪！}
{108}{}{<吱> 喵．．错误。}
{109}{}{汪汪汪汪汪汪汪汪汪汪汪汪！}
{110}{}{吼～～}
{111}{}{呜呜！}
{112}{}{汪汪！}
{113}{}{危险！危险！}
{114}{}{吼吼！}
{115}{}{不是鸟，不是飞机，我不是青蛙，是我－机器狗！}
{116}{}{机机狗！}
{117}{}{哔哔哔哔哔！}
{118}{}{汪！}
{119}{}{吼吼！}
{120}{}{汪汪汪汪汪汪汪！}
{121}{}{好}
{122}{}{我不认为我现在想要加入你们，再见。}
{123}{}{吼？汪？}
{124}{}{你好吗？}
{125}{}{我要你在这边等，直到我回来。}
{126}{}{先这样吧。}
{127}{}{汪汪～～！}
{128}{}{算了。}
{129}{}{好}
{130}{}{生命值：}
{131}{}{目前机器狗不能够再修理了。}
{132}{}{机器狗已经被尽量的修理了。}
{133}{}{机器够都被修好了。}

#specific party messages
{1000}{}{汪！汪？}
{1100}{}{汪汪！}
{1200}{}{汪汪！?}
{1300}{}{嗯嗯。}
{1400}{}{吼吼！}
{1500}{}{哔哔哔哔哔哔哔哔哔哔哔哔！} //Wait here resoponse
{1600}{}{当然，我会把它拿开的。}  //Put weapons away
{1700}{}{汪汪，距离设定为近。}
{1800}{}{汪汪，距离设定为中。}
{1900}{}{汪汪，距离设定为远。}
{2000}{}{我不是一个狗狗。}
{2100}{}{吼吼！}
{2200}{}{汪汪汪！}

{2204}{}{你现在保持的距离很好。}