{100}{}{你看见了一块凸起的地板。它好像是陷阱的一部分。}

# NPC name prepends this line
{101}{}{看见了一块凸起的地板。它好像是陷阱的一部分。}

{102}{}{你看见了一块凸起的地板。}

# NPC name prepends this line
{103}{}{看见了一块凸起的地板。}

{104}{}{你触动了机关，好险你躲开了从墙里射出的东西。}

# NPC name prepends this line
{105}{}{触动了机关，好险你躲开了从墙里射出的东西。}

{106}{}{你看见一块凸起的地板，它看起来不会造成什么威胁了。}