{100}{}{你看到一个布告栏。}
{101}{}{你看到一个贴有新加州共合国法律的布告栏。}
{102}{}{这是一个典型的布告栏，上面贴了好几张纸。最引人注意的就是新加州共和国的法律了。}
{103}{}{欢迎来到新加州共和国！在你进入我们美好的城市之前，请花数分钟熟悉我们的规例与条款。}
{104}{}{武器不能够公然的在公共场所上面持有。}
{105}{}{受到毒品或是酒精影响的人将会被逮补。}
{106}{}{奴役制、赌搏、以及卖春在本市是犯法的。}
{107}{}{不守法是没有藉口的。}
{108}{}{如果你无法遵守这一些法律，就请你离开！}
{109}{}{你最好把你的武器收起来。我们是认真的！}
{110}{}{守法就是好市民。}
{111}{}{回去}
{112}{}{我听够了。}
{113}{}{这代表着你不能够进行你一般最喜欢的娱乐了。}
{114}{}{很好，这代表着不会有瘾君子跟你要钱了。}
{115}{}{回去}
{116}{}{我听够了。}
{117}{}{总是会有其它赚钱的方法吧？}
{118}{}{看起来他们好像正在尽力的创造一个受人尊敬并且拥有高生活水准的环境。}
{119}{}{回去}
{120}{}{我听够了。}
{121}{}{很严的法律。不过不知道是不是有严格的执行就是了。}
{122}{}{法律之前，人人平等。}
{123}{}{回去}
{124}{}{我听够了。}
{125}{}{让这些人能够尊敬你看来是现在首要的事。}
{126}{}{那听起来很严，但是却说的相当清楚。}
{127}{}{回去}
{128}{}{我听够了。}

# {130}{}{My head hurt. Too much readie.}
{130}{}{我的头受伤了。有太多的疑问。}