#ipisgfx译
{100}{}{}
{101}{}{你看见一个部落成员。}
{102}{}{你看见马力。}
{103}{}{你看见一个又高又壮的战士。}

#{110}{}{Go away. I'm thinking and I don't want to be disturbed by a stranger. Come back some other time.}
{110}{}{走开。我在思考我不想被一个陌生人扰乱。别的时间再来吧。}
{111}{}{不用这么粗鲁吧。再见。}

#{112}{}{Hmph, touching other people's property without permission. At least the well works again.}
{112}{}{哈，没经别人允许就碰别人的东西。不过最少井又可以用了。}
#{113}{}{Right. No thanks required.}
{113}{}{好的，没有感谢的必要。}
#{114}{}{Whatever. Way to be ungrateful.}
{114}{}{无论如何。算了。}

#{120}{}{Hello, what do you want?}
{120}{}{你好，你想要什么？}
#{121}{}{I see that you are having some trouble with that well over there. What's wrong exactly?}
{121}{}{我看你有些麻烦是关于那井吗，出什么问题了？}

#{130}{}{Well, we don't know who did it but someone stole the rope to the well. We've been relying on the rainwater ever since but it won't be enough.  We need a new rope so we can get at the water.  Could you help us?}
{130}{}{好吧，我们不知道谁干的不过有人偷了井上的绳索。我们以前都靠雨水，不过那不够用。我们需要一根缆索就能取水了。你能帮我们吗？}
#{131}{}{Well, yeah.  I guess so. I'll find a rope and return as soon as possible.}
{131}{}{好的，我想可以。我会尽快找一根缆索回来的。}
#{132}{}{I think it's a little beyond me.  I'll come back some other time.}
{132}{}{我想对来我说有点难。我别的时间再来吧。}

#{140}{}{Have you fixed the well yet?}
{140}{}{你修好井了吗？}
{141}{}{还没呢。}

{150}{}{嗨，你修好井了吗？}
{151}{}{是的，现在一根新的缆索在那了。}

#{160}{}{*glances to well* You know, it won't work until the bucket is reattached. Do that and I'll see that you're rewarded.}
{160}{}{*看了看井* 你知道的，没有桶就没法工作。帮个忙我知道你愿意效劳的。}
{161}{}{好的。}

{170}{}{找到桶了吗？}
{171}{}{不，还没。}

#{180}{}{So have you fixed the well? With the bucket attached as well?}
{180}{}{你修好了井？还加上了桶？}
{181}{}{是的，全搞定了。}

#{190}{}{Great. You don't know how much this will help the tribe. Here, take this money. I found this stash in the wastes and we have no use for it.}
{190}{}{太好了。你不知道这对我们有多重要。拿去，拿着这些钱。我在荒漠里找到的，这对我们没什么用。}
{191}{}{谢谢。}

{200}{}{嗨，这口井现在可以用了。}
{201}{}{谢谢你的帮助。}
{202}{}{再次见到你很高兴。}

{1000}{}{你修好了部落的井。}