#ipisgfx译
#{200}{}{Greetings warrior. What business brings you to our tribe?}
{200}{}{你好战士。你给我们部落带来了什么生意？}
#{201}{}{I'm on a holy quest for Arroyo, my village, to save it from certain destruction.}
{201}{}{我正为拯救我的村庄阿由罗而执行一个神圣的任务。}
{202}{}{我正为拯救我的村庄阿由罗而执行一个神圣的任务。}
#{203}{}{I can't really say. I was just passing through.}
{203}{}{我只是偶然经过这。}


#{210}{}{Arroyo, yes, I've heard of that village before. It's to the north, yes?  So who are you? One of their warriors? Scouts?}
{210}{}{阿罗由，是的，我听过那个村。在北方，是吗？所以呢你是谁？战士？侦察员？}
#{211}{}{Yeah, I'm a warrior. I was the only one to pass the temple of trials and thus be given the quest.}
{211}{}{是的，我是一个战士。我是唯一通过神庙考验的人，所以被指派了这个任务。}


#{220}{}{Very noble of you warrior, I must say. You seem to have the skills necessary to survive in this harsh world. Possibly, if you have the time, you could do me a favor for the village?}
{220}{}{我必需说，非常高尚。你看上去有生存在这个荒芜世界的能力。可能的话，如果你有时间，你能帮我个忙吗？}
{221}{}{你需要做什么？}
{222}{}{对不起，但是我的任务已经占据我所有时间了。如果我有空闲时间我会回来的。}

#{230}{}{Well, our warriors are stretched very thin at the moment. Our tribe has suffered a lot in the past few years from deaths and very few births. What with defending the tribe from other tribes and hunting for food, our stock of weapons has been almost destroyed. I need perhaps, ten normal knives and five regular spears. Could you collect these for me?}
{230}{}{很好，我们的战士现在很稀少。在过去几年里部落经受了屠杀和出生率少的磨难。用于防卫其他部落和打猎用的武器现在大部分都毁坏了。我需要大约10把小刀和5把长矛。你能帮我收集这些东西吗？}
{231}{}{没问题，我收集好后会回来的。}
{232}{}{我已经收集够了。如果它们对你有帮助给你吧。}
{233}{}{实际上我有，不过它们对我还有用，不能给你。}

{240}{}{太好了，谢谢你！这将对我们的战士有很大的帮助。我很报歉我没东西给你。我们是一个朴素的部落没有实际的财产。你会，不，你将永远受到我们部落的欢迎。}
#{241}{}{Thank you. I'll stop to talk if I ever pass through here again.}
{241}{}{谢谢你。我会再来看你们的。}

#{250}{}{Have you managed to find the items we need?}
{250}{}{你设法找到我们需要的东西了吗？}
#{251}{}{Yes, here they are.}
{251}{}{是的，它们在这。}
#{252}{}{No, not as yet.  They're not easy to find at all.}
{252}{}{不，还没呢。找它们不容易。}
#{253}{}{Actually, yes I do. I think I will hold on to them though.}
{253}{}{实际上，是的我找到了。不过我想它们现在是我的。}
{254}{}{每种武器你各要多少？}
{255}{}{我们部落需要10把小刀和5把长矛，长矛磨不磨尖没关系，我相信你在旅行中会找到这些的。}
{256}{}{顺利的话，我找到就带回来。}
{257}{}{正确，我不会错过任何我能翻的瓶瓶罐罐或是任何能点击的东西，这花不了太多时间，回见。}

#{260}{}{Hello again. What can I do for you?}
{260}{}{嗨又见面了。我能为你做什么？}
#{261}{}{Can I ask you a few questions?}
{261}{}{我能问你点问题吗？}
{262}{}{没事，再见。}

{270}{}{行。}
#{271}{}{Tell me about the tribe.}
{271}{}{和我说说这个部落吧。}
{272}{}{和我说说你自己吧。}
#{273}{}{Is there anything happening here I should know about?}
{273}{}{这里有什么事我应该要知道的吗？}

#{280}{}{Well, there's not much to tell you about really. We're a small peaceful tribe that's been settled here for many years. We fight only to protect ourselves and find food. Our tribal leader was originally from the north before settling here. Originally she intended to travel back there to find her brother but as time passed she became happy here. Our shaman is a little crazed but helps to keep most of the injured from dying.}
{280}{}{好的，也没太多要说的。我们是一个爱好和平的小部落，定居这很多年了。我们只为保护自己和打猎时才战斗。我们部落领导者定居在这之前来自北方。原先她想回到那找她的兄弟，但是随着时间慢慢过去她变得很喜欢这了。我们的巫师有一点疯狂但对受伤的人确很有办法。}
#{281}{}{Right, thanks for the info. Tell me a bit about yourself.}
{281}{}{对，谢谢你的信息。说说你自己吧。}

#{290}{}{Me? I've been here for two years now. My tribe was destroyed by savages and I was the sole survivor. I wandered around the wastes for days until I came across this tribe and they accepted me as the head warrior.}
{290}{}{我？我来这有两年了。我的部落被野蛮人摧毁了。我是唯一的生还者。我在荒漠徘徊了几天直到我经过这个部落他们认为我能成为他们战士的队长。}
#{291}{}{That was lucky. Bye then.}
{291}{}{那真不错。那么回见。}

#{301}{}{Well, you seem skilled in fighting. I wonder if you could help our village?}
{301}{}{很好，你看上去很熟悉战斗。我想知道你能帮助我们村庄吗？}
{302}{}{我想我可以，你需要什么？}
{303}{}{我没时间，报歉。}

#{310}{}{Well, I still need a favor done. Do you have the time to help us?}
{310}{}{好的，我确是需要有人帮个助。你有时间帮我们吗？}
#{311}{}{Why?  What's wrong?}
{311}{}{为什么？出什么事了？}
#{312}{}{Not right now. I'll return as soon as I can.}
{312}{}{不是现在，我现在要赶快回去了。}

#{320}{}{Well, as you ask, then yes. The well's broken and needs to be fixed. Ask Marli, the guy by the well, for more details.}
{320}{}{那么，你问起了，那我就说吧。我们的井坏了需要修理。详细的事问问马力，这小子就在井边。}
{321}{}{谢了，再见。}


{100}{}{你看见一个战士。}
{101}{}{你看见了这个部落的战士队长。}
{102}{}{这个部落最强的战士。}

{330}{}{你好战士。}
{331}{}{见到你很高兴。}
{332}{}{你的任务怎么样了？}

#{400}{}{Ah, it is good to see you again. Do you have a moment, I could use your assistance again.}
{400}{}{哈，很高兴再次见到你。你有时间吗？我再次需要你的协助。}
{401}{}{当然，你需要什么？}
{402}{}{现在不行，再见。}
#{403}{}{Well, our hunting party has not returned from their weekly hunt at the hunting grounds. Serin and Jerem are very good warriors of ours so surely something disastorous has happened.}
{403}{}{好的，我们的打猎小队去猎场打猎有一周了都没回来。肖恩和杰里都是非常好的战士。一定出什么大事。}
#{404}{}{Ok, but where should I begin?}
{404}{}{好的，不过我该从哪开始呢？}
#{405}{}{Oh yes, I should probably tell you where our hunting grounds are. Well, the fastest way to get there is from the coastal side of our camp. There is a cave entrance there from which a long, narrow passage leads to our hunting grounds.We found this passage on one of our scouting missions. It is not a very sturdy looking passage but it quicker than our normal route. Go speak to the guard at the entrance to the cave. Tell him I give you permission to enter to look for the hunters.}
{405}{}{哦是的，我应该告诉你我们的猎场在哪。嗯，最快到那的方法是从我们营地旁的海岸旁的洞穴。从那通过又长又窄的通道就能到猎场了。虽然通道不是很安全但是比通常的路线快很多。去和洞穴入口的守卫谈谈。告诉他我允许你进去找猎人。}
#{406}{}{I'll report back what I find.}
{406}{}{找到后我会回来报告的。}
#{407}{}{Are you ready to help me with what I need?}
{407}{}{你准备好帮我了吗？}

#{408}{}{Any news on the hunters?}
{408}{}{有猎人的新消息吗？}
#{409}{}{No, not yet. I am working on it.}
{409}{}{不，还没呢。我正在努力中。}
#{410}{}{Yes. They are all dead. I found their bodies crushed by a rock slide in the cave.}
{410}{}{是的，他们全死了。我在洞穴里找到被岩石压碎的他们的尸体。}
#{411}{}{What?! Oh, this is terrible news. Serin and Jerem were great hunters. [The man sighs] Their loss will be great. [The man looks away for a moment and then returns eye contact.] Thank you for your help. Now if you excuse me...}
{411}{}{什么？！真是个坏消息。肖恩和杰里是最棒的战士。[他叹息] 哎！ [他看上去很伤心] 谢谢你的帮忙。如果你不介意我...}
{412}{}{[完成]}
{413}{}{肖恩和杰里都是好人。他们不会被忘记的。}

#{500}{}{Thank you for helping us locate our hunters. The loss of Jerem is great, he was a skilled warrior. Serin has recovered nicely and should be able to hunt again in a few days. We won't be able to use our shortcut anymore, but that is ok; good things don't last forever. Thank you again, friend. You have our thanks.}
{500}{}{谢谢你找到我们的猎人。失去的杰里是个好战士。肖恩恢复的很好，再过几天又可以再次打猎了。我们不会再用这个捷径了，哎，算了，好事不长久嘛。再次谢谢你我的朋友。}
{501}{}{不客气，保重。}

{1000}{}{你为这个部落补给了很多武器。}
