#ipisgfx译
{100}{}{你想要什么？}
{101}{}{你是谁为什么守在这？}
{102}{}{没什么，对不起打扰你了。}

#{110}{}{I am guarding the holy leader of our small tribe. He is both wise and knowledgeable. You have no business bothering me and therefore him. Leave now.  }
{110}{}{我在守护神圣部落酋长。他既英明又知识渊博。没有他的允许你别打扰我。现在走开吧。}
{111}{}{[完成]}

#{120}{}{I've asked you to leave already, but you insist on trying my patience. Go away.}
{120}{}{我已经叫你走开了，但是你还坚持来试探我的耐性。滚开。}
{121}{}{[完成]}

#{130}{}{I hear you have done good things for our tribe. I'm sorry for my earlier rudeness, but we have to be wary of outsiders here. You have earned the right to see our leader. Go on in. He is waiting for you.}
{130}{}{我听说你帮我们的部落一些忙。我对以前的粗鲁感到十分报歉，但是我们还是得对外界提高警戒。你现在可以见见我们酋长了。进去吧。他在等你。}
{131}{}{谢谢。}

{140}{}{祝福你。}
{141}{}{什么事，战士？}
{142}{}{进来吧。}
#{143}{}{Well met, warrior.}
{143}{}{幸会，战士。}
{144}{}{很高兴再次见到你。}

{300}{}{你看见一个强壮土著。}
{301}{}{你看见部落酋长的护卫。}
#{302}{}{This man is watching you with a piercing gaze. Clearly, he is guarding someone important.}
{302}{}{这个人用犀利的眼神看着你。显然，他在守护什么重要的人。}