{100}{}{这一台终端机正显示着一些发光的图表。}
{101}{}{你看到一部地下掩体市的医疗电脑。}
{102}{}{这一台终端机正显示着一些发光的图表。}
{103}{}{如果你用科学的眼光来看的话，你也许能够在这终端机上取得更多的资讯。}
{104}{}{你无法懂得如何操作这一个终端机。}
{105}{}{可恶的电脑。}
{106}{}{你无法懂得如何操作这一个终端机。}
{107}{}{可恶的电脑。}
{108}{}{你登入了地下掩体市医疗资料库。虽然说它的介面相当的难懂，但是资料库本身看起来却相当详细的分了好几大类。}
{109}{}{搜寻资料库，找出其它避难所的位置。}
{110}{}{搜寻资料库，找出任何提到伊甸园创造器的文件。}
{111}{}{搜寻资料库，找出任何有趣的资料。}
{112}{}{离线。}
{113}{}{你在资料库中找不到任何提到其它避难所的资料。里面的资料大部份都是医疗上的文件：生物结构、疾病、疗程、药物、以及手术等资料。}
{114}{}{搜寻资料库，找出任何提到伊甸园创造器的文件。}
{115}{}{搜寻资料库，找出任何有趣的资料。}
{116}{}{离线。}
{117}{}{你在资料库中找不到任何提到伊甸园创造器的资料。里面的资料大部份都是医疗上的文件：生物结构、疾病、疗程、药物、以及手术等资料。}
{118}{}{搜寻资料库，找出其它避难所的位置。}
{119}{}{搜寻资料库，找出任何有趣的资料。}
{120}{}{离线。}
{121}{}{你搜寻的资料库，但是医疗资料库里面的文件都相当的深奥。如果你是医生的话，也许你还会看得懂。}
{122}{}{继续搜寻电脑资料库。}
{123}{}{离线。}
{124}{}{你搜寻资料库，对于里面所有的资料量感到惊讶。地下掩体市目前正在进行的研究相当的有趣；他们的医疗技术是你前所未见的先进。}
{125}{}{你搜寻资料库，但是没有找到任何有趣的东西。}
{126}{}{你再一次的搜寻了资料库．．但是没有找到任何新的东西。如果你再搜寻２０次，也许会发现新的资料吧。}
{127}{}{我们只是在开玩笑而已。这边真的没有什么新的资料了。如果你再搜寻３０次，你也许真的会找到新的资料。哈哈。}
{128}{}{嗯．．听着，继续去玩其它的游戏吧。你不能够一直的待在这里啊。}
{129}{}{好吧，随便你，要在这边浪费时间是你的事，我才不管咧。}
{130}{}{只是在浪费时间而已。}
{131}{}{你的智力只有４，对不对？}
{132}{}{该住手了吧。}
{133}{}{你为什么不去与护士玩呢？}
{134}{}{这边没有东西了！}
{135}{}{你搜寻资料库，没有找到任何的东西。}
{136}{}{你已经搜寻了这一个资料库５３次了。你还是找不到任何有趣的资料。}
{137}{}{你就是还要在多做一次，是不是？}
{138}{}{好吧，听着。这是一个大秘密。你一定要在完成游戏之后去使用第３层的电脑。现在请离线，到别的地方去玩吧。}
{139}{}{你搜寻资料库，没有找到任何的东西。}
{140}{}{继续搜寻电脑资料库。}
{141}{}{再次搜寻资料库，确定没有漏掉什么东西。}
{142}{}{继续搜寻电脑资料库。}
{143}{}{离线。}
{144}{}{你花了将近一个小时在这资料库上。你发现了一些相当古老的资料，里面记载有一种“战斗植入器”的设计图。}
{145}{}{研究那设计图。}
{146}{}{设计图上面记有着人头骨的防撞外壳还有散热膜设计。可以让一个人忍受更高的撞击以及耐更高的热。那看起来像是一个相当复杂的程序。}
{147}{}{记下你的发现，然后继续搜查资料库。}
{148}{}{记下资料，然后离线。}
{149}{}{你回到了主选单。在这边列有一系列的资料库以及搜寻程式。}
{150}{}{搜寻资料库，找出其它避难所的位置。}
{151}{}{搜寻资料库，找出任何提到伊甸园创造器的文件。}
{152}{}{搜寻资料库，找出任何有趣的资料。}
{153}{}{离线。}
{200}{}{你完成搜寻地下掩体市的医疗资料库了。}
{201}{}{你的朋友想要叫你看看那个发出哔哔声响的东西，但是你却不知道要如何将它打开，最后，你放弃了。}
{202}{}{离开。}
{203}{}{哔。}
{204}{}{哔，哔。}
{205}{}{叮叮叮。}
{206}{}{哔}
{207}{}{哔。}
{208}{}{乒！}
{209}{}{我很抱歉，达夫。我不能那样做。}
{210}{}{危险！威尔．罗宾逊！}
{211}{}{还有三十秒才能达到最短安全距离。}
{212}{}{我说，兵！}
{213}{}{请将你的卡取出，然后取出现金。}
{214}{}{奇怪的游戏。唯一能够致胜的方法就是不要玩。}