{100}{}{你看到一个启动的电脑终端机。}
{101}{}{在仔细检察电脑之后，你看到上面写着“I*tel Inside”。}
{102}{}{你看不懂荧幕上面显示的东西。}

#NPC is unable to read what is on the monitor
{200}{}{看不懂荧幕上面显示的东西。}

{103}{}{主要电源＝断线
		       备用电源＝上线
					     重新启动安全程式
				  警告－电压过低－力场强度只有５０％
		      载入完成．．
						  天网安全系统检查站１
			       请键入密码：_}
{104}{}{天网安全系统检查站１
			     请键入密码：_}
{105}{}{柴可夫斯基}
{106}{}{给我开门}
{107}{}{山岭}
{108}{}{世界末日}
{109}{}{侵入安全系统}
{110}{}{你不知道。离开。}
{113}{}{力场已关闭－第一层}
{115}{}{离开}
{117}{}{本终端机的控制已被终结了。}
{119}{}{离开}
{121}{}{错误２９
							    无法与伺服器连线
				     请重新开机}
{123}{}{离开}
{124}{}{成功进入系统
						 第一层力场：已关闭}
{125}{}{离开}
{126}{}{错误的密码
						      无法进入系统
						      请键入密码：_}
{127}{}{柴可夫斯基}
{128}{}{给我开门}
{129}{}{山岭}
{130}{}{世界末日}
{131}{}{侵入安全系统}
{132}{}{你不知道。离开。}
{133}{}{[按下 <Ctrl><Alt><C> 让程式当掉了。你真希望其它的安全系统都这样容易的就可以解除了。]}
{134}{}{离开。}
{135}{}{第一层有人入侵
				   启动安全程序
				   本终端机连线已终结
		      结束传送}
{136}{}{离开}
{137}{}{你笨拙的行为将警钟给触动了。}
{138}{}{那没有用，这程式实在是太复杂了，你没有办法弄懂。}
{139}{}{离开}

{300}{}{这电脑看起来好像有一些防卫的系统。}
{301}{}{你被电击了，受到}
{302}{}{被电击了，受到}
{303}{}{点的损伤。}