#
# This is all of the combat messages used by combat.c
# Note: all %d values will be filled with a number greater than 1
#
# Truly Generic strings (no need for gender/number issues)
#
{100}{}{你需要 %d 点动作点数。}
{101}{}{没有弹药了。}
{102}{}{目标不在范围内。}
{103}{}{战斗无法中断，因为仍有敌人存在。}
{104}{}{你被遮住了，无法瞄准。}
{105}{}{你的双手都受伤了，无法使用武器。}
{106}{}{你的一只手受伤了，无法使用需要双手操作的武器。}
{107}{}{你不够强壮，不能够使用这一样武器。}
{108}{}{并且}
#
# Combat Flag Strings (all of these happen to you, the MALE player)
#
{200}{}{你被打晕了}
{201}{}{你被打倒了}
{202}{}{伤了你的左腿}
{203}{}{伤了你的右腿}
{204}{}{伤了你的左臂}
{205}{}{伤了你的左臂}
{206}{}{你被打瞎了}
{207}{}{你一命呜呼了}
{208}{}{被打中了}
{209}{}{你处境危险了}
{210}{}{你着火了}
{211}{}{穿破了你的装甲}
{212}{}{你的武器爆炸了}
{213}{}{你的武器毁坏了}
{214}{}{你的武器掉了}
{215}{}{你失去了下一回合的攻击机会}
{216}{}{你打到了自己}
{217}{}{你掉了所有的弹药}
{218}{}{你射了一发没用的子弹}
{219}{}{你打伤了自已}
{220}{}{你随便乱打一顿}
{221}{}{你伤了自己的一个肢体}
{222}{}{你被打的五马分尸}
#
# Combat Flag Strings (all of these happen to you, the FEMALE player)
#
{250}{}{你被打晕了}
{251}{}{你被打倒了}
{252}{}{伤了你的左腿}
{253}{}{伤了你的右腿}
{254}{}{伤了你的左臂}
{255}{}{伤了你的左臂}
{256}{}{你被打瞎了}
{257}{}{你一命呜呼了}
{258}{}{被打中了}
{259}{}{你处境危险了}
{260}{}{你着火了}
{261}{}{穿破了你的装甲}
{262}{}{你的武器爆炸了}
{263}{}{你的武器毁坏了}
{264}{}{你的武器掉了}
{265}{}{你失去了下一回合的攻击机会}
{266}{}{你打到了你自己}
{267}{}{你掉了所有的弹药}
{268}{}{你射了一发没用的子弹}
{269}{}{你打伤了自已}
{270}{}{你随便乱打一顿}
{271}{}{你伤了自己的一个肢体}
{272}{}{你被打的五马分尸}
#
# Combat Flag Strings (all of these happen to a male)
#
{300}{}{他被打晕了}
{301}{}{他被打倒了}
{302}{}{伤了他的左腿}
{303}{}{伤了他的右腿}
{304}{}{伤了他的左臂}
{305}{}{伤了他的左臂}
{306}{}{他被打瞎了}
{307}{}{他一命呜呼了}
{308}{}{被打中了}
{309}{}{他处境危险了}
{310}{}{他着火了}
{311}{}{穿破了他的装甲}
{312}{}{他的武器爆炸了}
{313}{}{他的武器毁坏了}
{314}{}{他的武器掉了}
{315}{}{他失去了下一回合的攻击机会}
{316}{}{他打到了自己}
{317}{}{他掉了所有的弹药}
{318}{}{他射了一发没用的子弹}
{319}{}{他打伤了自已}
{320}{}{他随便乱打一顿}
{321}{}{他伤了自己的一个肢体}
{322}{}{他被打的五马分尸}
#
# Combat Flag Strings (all of these happen to a female)
#
{400}{}{她被打晕了}
{401}{}{她被打倒了}
{402}{}{伤了她的左腿}
{403}{}{伤了她的右腿}
{404}{}{伤了她的左臂}
{405}{}{伤了她的左臂}
{406}{}{她被打瞎了}
{407}{}{她一命呜呼了}
{408}{}{被打中了}
{409}{}{她处境危险了}
{410}{}{她着火了}
{411}{}{穿破了她的装甲}
{412}{}{她的武器爆炸了}
{413}{}{她的武器毁坏了}
{414}{}{她的武器掉了}
{415}{}{她失去了下一回合的攻击机会}
{416}{}{她打到了自己}
{417}{}{她掉了所有的弹药}
{418}{}{她射了一发没用的子弹}
{419}{}{她打伤了自已}
{420}{}{她随便乱打一顿}
{421}{}{她伤了自己的一个肢体}
{422}{}{她被打的五马分尸}
#
# Miscellaneous combat messages (all of these happen to you, the male player)
# Note: the first %s will be replaced by the value of line 506, which
#          should be the language's equivalent to 2nd person male singular,
#          which is "You" in English. The first letter of line 506 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 509
#          where the second %s is the name of another creature
{506}{}{你}
{509}{}{啊！ %s 被打到了，虽然你原本是要打 %s ！}
{511}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{512}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{513}{}{%s 被打中了，失去了 %d 点生命值}
{514}{}{%s 没有打中}
{515}{}{%s 没打中}
{520}{}{%s 被打中了，失去了 %d 点生命值}
{521}{}{%s 的 %s 被打中了，失去了1点生命值}
{522}{}{%s 的 %s 被打中了，失去了1点生命值}
{523}{}{%s 被打中了，失去了1点生命值}
{524}{}{%s 被打中了，失去了1点生命值}
{525}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{526}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{527}{}{%s 被打中了，但是没有失去任何的生命值}
{528}{}{%s 被打中了，但是没有失去任何的生命值}
{533}{}{%s 没有打中，但是失去了1点生命值}
{534}{}{%s 没有打中，但是失去了 %d 点生命值}
#
# Miscellaneous combat messages (all of these happen to you, the female player)
# Note: the first %s will be replaced by the value of line 556, which
#          should be the language's equivalent to 2nd person female singular,
#          which is "You" in English. The first letter of line 556 should
#          be capitalized, since it will start a sentence.
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 559
#          where the second %s is the name of another creature
{556}{}{你}
{559}{}{啊！ %s 被打到了，虽然你原本是要打 %s ！}
{561}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{562}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{563}{}{%s 被打中了，失去了 %d 点生命值}
{564}{}{%s 没有打中}
{565}{}{%s 没打中}
{570}{}{%s 被打中了，失去了 %d 点生命值}
{571}{}{%s 的 %s 被打中了，失去了1点生命值}
{572}{}{%s 的 %s 被打中了，失去了1点生命值}
{573}{}{%s 被打中了，失去了1点生命值}
{574}{}{%s 被打中了，失去了1点生命值}
{575}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{576}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{577}{}{%s 被打中了，但是没有失去任何的生命值}
{578}{}{%s 被打中了，但是没有失去任何的生命值}
{583}{}{%s 没有打中，但是失去了1点生命值}
{584}{}{%s 没有打中，但是失去了 %d 点生命值}
#
# Miscellaneous combat messages (all of these happen to a male)
# Note: the first %s is the name of the male creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 609
#          where the second %s is the name of another creature
#
{608}{}{啊！ %s 被打到了，虽然他原本是要打你！}
{609}{}{啊！ %s 被打到了，虽然他原本是要打 %s ！}
{611}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{612}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{613}{}{%s 被打中了，失去了 %d 点生命值}
{614}{}{%s 没有打中}
{615}{}{%s 没打中}
{620}{}{%s 被打中了，失去了 %d 点生命值}
{621}{}{%s 的 %s 被打中了，失去了1点生命值}
{622}{}{%s 的 %s 被打中了，失去了1点生命值}
{623}{}{%s 被打中了，失去了1点生命值}
{624}{}{%s 被打中了，失去了1点生命值}
{625}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{626}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{627}{}{%s 被打中了，但是没有失去任何的生命值}
{628}{}{%s 被打中了，但是没有失去任何的生命值}
{633}{}{%s 没有打中，但是失去了1点生命值}
{634}{}{%s 没有打中，但是失去了 %d 点生命值}
#
# Miscellaneous combat messages (all of these happen to a female)
# Note: the first %s is the name of the female creature
#       the second %s (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 709
#          where the second %s is the name of another creature
#
{708}{}{啊！ %s 被打到了，虽然他原本是要打你！}
{709}{}{啊！ %s 被打到了，虽然他原本是要打 %s ！}
{711}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{712}{}{%s 的 %s 被打中了，失去了 %d 点生命值}
{713}{}{%s 被打中了，失去了 %d 点生命值}
{714}{}{%s 没有打中}
{715}{}{%s 没打中}
{720}{}{%s 被打中了，失去了 %d 点生命值}
{721}{}{%s 的 %s 被打中了，失去了1点生命值}
{722}{}{%s 的 %s 被打中了，失去了1点生命值}
{723}{}{%s 被打中了，失去了1点生命值}
{724}{}{%s 被打中了，失去了1点生命值}
{725}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{726}{}{%s 的 %s 被打中了，但是没有失去任何的生命值}
{727}{}{%s 被打中了，但是没有失去任何的生命值}
{728}{}{%s 被打中了，但是没有失去任何的生命值}
{733}{}{%s 没有打中，但是失去了1点生命值}
{734}{}{%s 没有打中，但是失去了 %d 点生命值}
#
# Hit Locations (by art_num alias)
#
# regular humans
#
{1110}{}{头}
{1111}{}{左臂}
{1112}{}{右臂}
{1113}{}{身体}
{1114}{}{右腿}
{1115}{}{左腿}
{1116}{}{眼睛}
{1117}{}{跨下}
{1118}{}{任何部位}
#
# Brahmin (Mutant 2-Headed Cows)
#
{1150}{}{头}
{1151}{}{左后腿}
{1152}{}{右后腿}
{1153}{}{身体}
{1154}{}{右前腿}
{1155}{}{左前腿}
{1156}{}{眼睛}
{1157}{}{下部}
{1158}{}{任何部位}
#
# dogs
#
{1160}{}{头}
{1161}{}{左后腿}
{1162}{}{右后腿}
{1163}{}{身体}
{1164}{}{右前腿}
{1165}{}{左前腿}
{1166}{}{眼睛}
{1167}{}{下部}
{1168}{}{任何部位}
#
# Mr. Handy
#
{1170}{}{中央处理器}
{1171}{}{触手}
{1172}{}{触手}
{1173}{}{主体}
{1174}{}{移动器}
{1175}{}{移动器}
{1176}{}{感应器}
{1177}{}{稳流器}
{1178}{}{任何部位}
#
# Super Mutants             # Fallout 2: Reserved?
#
{1180}{}{头}
{1181}{}{左臂}
{1182}{}{右臂}
{1183}{}{身体}
{1184}{}{右腿}
{1185}{}{左腿}
{1186}{}{眼睛}
{1187}{}{跨下}
{1188}{}{任何部位}
#
# Mole-Rat
#
{1190}{}{头}
{1191}{}{左前爪}
{1192}{}{右前爪}
{1193}{}{身体}
{1194}{}{右腿}
{1195}{}{左腿}
{1196}{}{眼睛}
{1197}{}{跨下}
{1198}{}{任何部位}
#
# big humans and mutants
#
{1210}{}{头}
{1211}{}{左臂}
{1212}{}{右臂}
{1213}{}{身体}
{1214}{}{右腿}
{1215}{}{左腿}
{1216}{}{眼睛}
{1217}{}{跨下}
{1218}{}{任何部位}
#
# Radscorpion
#
{1220}{}{头}
{1221}{}{尾巴}
{1222}{}{爪}
{1223}{}{甲壳}
{1224}{}{前脚}
{1225}{}{后脚}
{1226}{}{眼睛}
{1227}{}{头脑}
{1228}{}{任何部位}
#
# Floater
#
{1230}{}{头}
{1231}{}{嘴}
{1232}{}{前嘴}
{1233}{}{身以}
{1234}{}{浮袋}
{1235}{}{尾巴}
{1236}{}{神经线}
{1237}{}{产卵管}
{1238}{}{任何部位}
#
# masrat? a rat perhaps?
#
{1240}{}{头}
{1241}{}{左前爪}
{1242}{}{右前爪}
{1243}{}{身体}
{1244}{}{右腿}
{1245}{}{左腿}
{1246}{}{眼睛}
{1247}{}{跨下}
{1248}{}{任何部位}
#
# Centaur
#
{1250}{}{头}
{1251}{}{左臂}
{1252}{}{右臂}
{1253}{}{身体}
{1254}{}{右腿}
{1255}{}{左腿}
{1256}{}{眼睛}
{1257}{}{跨下}
{1258}{}{任何部位}
#
# human midgets and children
#
{1270}{}{头}
{1271}{}{左臂}
{1272}{}{右臂}
{1273}{}{身体}
{1274}{}{右腿}
{1275}{}{左腿}
{1276}{}{眼睛}
{1277}{}{跨下}
{1278}{}{任何部位}
#
# Overseer                  # Fallout 2: Reserved?
#
{1460}{}{头}
{1461}{}{左臂}
{1462}{}{右臂}
{1463}{}{身体}
{1464}{}{右腿}
{1465}{}{左腿}
{1466}{}{眼睛}
{1467}{}{跨下}
{1468}{}{任何部位}
#
# Gizmo                     # Fallout 2: Reserved?
#
{1490}{}{头}
{1491}{}{左臂}
{1492}{}{右臂}
{1493}{}{身体}
{1494}{}{右腿}
{1495}{}{左腿}
{1496}{}{眼睛}
{1497}{}{跨下}
{1498}{}{任何部位}
#
# The Master!               # Fallout 2: Reserved?
#
{1500}{}{头}
{1501}{}{???}
{1502}{}{???}
{1503}{}{身体}
{1504}{}{???}
{1505}{}{???}
{1506}{}{眼睛}
{1507}{}{中央处理器}
{1508}{}{任何部位}
#
# Death Claw
#
{1510}{}{头}
{1511}{}{左臂}
{1512}{}{右臂}
{1513}{}{身体}
{1514}{}{右腿}
{1515}{}{左腿}
{1516}{}{眼睛}
{1517}{}{跨下}
{1518}{}{任何部位}
#
# Mantis
#
{1520}{}{头}
{1521}{}{触脚}
{1522}{}{触脚}
{1523}{}{下腹}
{1524}{}{足}
{1525}{}{翅膀}
{1526}{}{眼睛}
{1527}{}{后胸}
{1528}{}{任何部位}
#
# Robobrain
#
{1530}{}{中央处理器}
{1531}{}{触手}
{1532}{}{触手}
{1533}{}{主体}
{1534}{}{移动器}
{1535}{}{移动器}
{1536}{}{感应器}
{1537}{}{稳流器}
{1538}{}{任何部位}
#
# Eyeball (Robot)
#
{1540}{}{中央处理器}
{1541}{}{触手}
{1542}{}{触手}
{1543}{}{主体}
{1544}{}{移动器}
{1545}{}{移动器}
{1546}{}{感应器}
{1547}{}{稳流器}
{1548}{}{任何部位}
#
# Mutant Pig Rat (small Mole-Rat)
#
{1550}{}{头}
{1551}{}{左前爪}
{1552}{}{右前爪}
{1553}{}{身体}
{1554}{}{右腿}
{1555}{}{左腿}
{1556}{}{眼睛}
{1557}{}{跨下}
{1558}{}{任何部位}
#
# Deathclaw Egg
#
{1580}{}{壳}
{1581}{}{壳}
{1582}{}{壳}
{1583}{}{壳}
{1584}{}{壳}
{1585}{}{壳}
{1586}{}{壳}
{1587}{}{壳}
{1588}{}{任何部位}
#
# Lesser Radscorpion
#
{1590}{}{头}
{1591}{}{尾巴}
{1592}{}{爪}
{1593}{}{甲壳}
{1594}{}{前脚}
{1595}{}{后脚}
{1596}{}{眼睛}
{1597}{}{头脑}
{1598}{}{任何部位}
#
# Lesser Death Claw
#
{1600}{}{头}
{1601}{}{左臂}
{1602}{}{右臂}
{1603}{}{身体}
{1604}{}{右腿}
{1605}{}{左腿}
{1606}{}{眼睛}
{1607}{}{跨下}
{1608}{}{任何部位}
#
# Giant Plant
#
{1650}{}{口}
{1651}{}{茎}
{1652}{}{茎}
{1653}{}{主干}
{1654}{}{根}
{1655}{}{根}
{1656}{}{触手}
{1657}{}{底部}
{1658}{}{任何部位}
#
# Security Robot
#
{1660}{}{头}
{1661}{}{火箭发射器}
{1662}{}{机关枪发射器}
{1663}{}{身体}
{1664}{}{右腿}
{1665}{}{左腿}
{1666}{}{感应器}
{1667}{}{下身}
{1668}{}{任何部位}
#
# Gecko 2
#
{1670}{}{头}
{1671}{}{左前爪}
{1672}{}{右前爪}
{1673}{}{身体}
{1674}{}{右腿}
{1675}{}{左腿}
{1676}{}{眼睛}
{1677}{}{跨下}
{1678}{}{任何部位}
#
# Gecko
#
{1680}{}{头}
{1681}{}{左前爪}
{1682}{}{右前爪}
{1683}{}{身体}
{1684}{}{右腿}
{1685}{}{左腿}
{1686}{}{眼睛}
{1687}{}{跨下}
{1688}{}{任何部位}
#
# Alien Thing
#
{1800}{}{头}
{1801}{}{左触手}
{1802}{}{右触手}
{1803}{}{身体}
{1804}{}{右腿}
{1805}{}{左腿}
{1806}{}{眼?}
{1807}{}{下半身}
{1808}{}{任何部位}
#
# End Boss
#
{1850}{}{头}
{1851}{}{左臂}
{1852}{}{右臂}
{1853}{}{身体}
{1854}{}{右腿}
{1855}{}{左腿}
{1856}{}{眼睛}
{1857}{}{跨下}
{1858}{}{任何部位}
#
# Alien Queen
#
{1860}{}{头}
{1861}{}{左触手}
{1862}{}{右触手}
{1863}{}{身体}
{1864}{}{右腿}
{1865}{}{左腿}
{1866}{}{眼?}
{1867}{}{下半身}
{1868}{}{任何部位}
#
# Gun Turret 2
#
{1900}{}{中央处理器}
{1901}{}{枪关节}
{1902}{}{枪关节}
{1903}{}{本体}
{1904}{}{底部关节}
{1905}{}{底部关节}
{1906}{}{感应器}
{1907}{}{导流器}
{1908}{}{任何部位}
#
# Giant Ant
#
{1970}{}{头}
{1971}{}{左前脚}
{1972}{}{右前脚}
{1973}{}{下腹}
{1974}{}{右后脚}
{1975}{}{左后脚}
{1976}{}{触角}
{1977}{}{后胸}
{1978}{}{任何部位}
#
# Goris Robed
#
{1990}{}{头}
{1991}{}{左臂}
{1992}{}{右臂}
{1993}{}{身体}
{1994}{}{右腿}
{1995}{}{左腿}
{1996}{}{眼睛}
{1997}{}{跨下}
{1998}{}{任何部位}
#
# Goris UnRobed
#
{2000}{}{头}
{2001}{}{左臂}
{2002}{}{右臂}
{2003}{}{身体}
{2004}{}{右腿}
{2005}{}{左腿}
{2006}{}{眼睛}
{2007}{}{跨下}
{2008}{}{任何部位}
#
# Gun Turret 2
#
{2010}{}{中央处理器}
{2011}{}{枪关节}
{2012}{}{枪关节}
{2013}{}{本体}
{2014}{}{底部关节}
{2015}{}{底部关节}
{2016}{}{感应器}
{2017}{}{导流器}
{2018}{}{任何部位}
#
# Fruit Fly
#
{2050}{}{头}
{2051}{}{螫针}
{2052}{}{触须}
{2053}{}{胸膛}
{2054}{}{前脚}
{2055}{}{后脚}
{2056}{}{眼睛}
{2057}{}{翅膀}
{2058}{}{任何部位}
#
# Cockroach
#
{2060}{}{左触须}
{2061}{}{后脚}
{2062}{}{右触须}
{2063}{}{下腹}
{2064}{}{胸部}
{2065}{}{前脚}
{2066}{}{嘴}
{2067}{}{尾巴}
{2068}{}{任何部位}
#
# Komodo Lizard
#
{2070}{}{头}
{2071}{}{左后脚}
{2072}{}{右前脚}
{2073}{}{身体}
{2074}{}{右后脚}
{2075}{}{左前脚}
{2076}{}{眼睛}
{2077}{}{跨下}
{2078}{}{任何部位}
#
# Sewer Rat
#
{2080}{}{头}
{2081}{}{左后脚}
{2082}{}{右前脚}
{2083}{}{身体}
{2084}{}{右后脚}
{2085}{}{左前脚}
{2086}{}{眼睛}
{2087}{}{跨下}
{2088}{}{任何部位}

#
# Critical Hit Messages
#
# 5000 series - men (including generics)
#
{5000}{}{而且很痛}
{5001}{}{。造成了相当大的伤害}
{5002}{}{而且没有装甲保护}
{5003}{}{。这一击太重了，打得他不省人事}
{5004}{}{。这一击将他打得站不起来}
{5005}{}{。头顶的重击将他打晕了}
{5006}{}{。那一击将他的太阳穴打碎了}
{5007}{}{，马上就死了}
{5008}{}{，将手肘打碎了}
{5009}{}{，将手臂打脱臼了}
{5010}{}{，留下了一个伤痕}
{5011}{}{，将左臂打残了}
{5012}{}{，将左臂打得只剩下皮肤挂着}
{5013}{}{。那条手臂看起来血肉模糊}
{5014}{}{，将右臂打残了}
{5015}{}{。他的右臂被那强力的一击打烂了}
{5016}{}{，在一记重击中}
{5017}{}{穿过了装甲}
{5018}{}{，造成了更多的伤害}
{5019}{}{对方没有穿装甲，因此被摔到地面上}
{5020}{}{打得不成人型，他倒在地上无法继续战斗}
{5021}{}{。很不幸的，你现在可以看到他的脊椎骨露在外面}
{5022}{}{把他的脚打得重伤}
{5023}{}{，把他打得像保龄球瓶一样倒在地上}
{5024}{}{，将他那腿打成残废}
{5025}{}{，把膝盖打得粉碎。他应声倒下}
{5026}{}{。断腿的痛苦使他无法继续战斗}
{5027}{}{又让他倍加痛苦。}
{5028}{}{将他打瞎了，算他倒霉}
{5029}{}{，而且那边没有保护，使得痛苦加倍。}
{5030}{}{，而且用力的一击也使他瞎了眼睛}
{5031}{}{。失去眼睛对他来说打击太大了，他因此倒在地上}
{5032}{}{，可怜的他就这样的死了}
{5033}{}{。啊！那一定很痛}
{5034}{}{，而且他并没有穿戴任何的护具}
{5035}{}{而且在没有护具的情况之下，他倒下来，并且疼痛哀号}
{5036}{}{。疼痛的程度已经超过了他能忍受的极限，他因此应声倒下}
{5037}{}{。在叫了一声″妈妈″之后，他便翻白眼了}
#
# series 5100 - women
#
{5100}{}{而且很痛}
{5101}{}{。造成了相当大的伤害}
{5102}{}{而且没有装甲保护}
{5103}{}{。这一击太重了，打得他不省人事}
{5104}{}{。这一击将他打得站不起来}
{5105}{}{。头顶的重击将他打晕了}
{5106}{}{。那一击将他的太阳穴打碎了}
{5107}{}{，马上就死了}
{5108}{}{，将手肘打碎了}
{5109}{}{，将手臂打脱臼了}
{5110}{}{，留下了一个伤痕}
{5111}{}{，将左臂打残了}
{5112}{}{，将左臂打得只剩下皮肤挂着}
{5113}{}{。那条手臂看起来血肉模糊}
{5114}{}{，将右臂打残了}
{5115}{}{。他的右臂被那强力的一击打烂了}
{5116}{}{，在一记重击中}
{5117}{}{穿过了装甲}
{5118}{}{，造成了更多的伤害}
{5119}{}{但没有穿装甲，战斗者摔到地面上}
{5120}{}{打得不成人型，他倒在地上无法继续战斗}
{5121}{}{。很不幸的，你现在可以看到他的脊椎骨露在外面}
{5122}{}{把他的脚打得重伤}
{5123}{}{，把他打得像保龄球瓶一样倒在地上}
{5124}{}{，将他那腿打成残废}
{5125}{}{，把膝盖打得粉碎。他应声倒下}
{5126}{}{。断腿的痛苦使他无法继续战斗}
{5127}{}{又让他倍加痛苦。}
{5128}{}{将他打瞎了，算他倒霉}
{5129}{}{，而且那边没有保护，使得痛苦加倍。}
{5130}{}{，而且用力的一击也使他瞎了眼睛}
{5131}{}{。失去眼睛对他来说打击太大了，他因此倒在地上}
{5132}{}{，可怜的他就这样的死了}
{5133}{}{。啊！那一定很痛}
{5134}{}{，将他打倒在地上}
{5135}{}{而且在没有护具的情况之下，他倒下来，并且疼痛哀号}
#
# series 5200 - children
#
{5200}{}{。那小孩开始放声大哭}
{5201}{}{。小孩倒在地上不省人事}
{5202}{}{。痛！}
{5203}{}{。那一击并不轻，让小孩不省人事}
{5204}{}{，把小孩打的像一块破地毯一样}
{5205}{}{。那小孩的左臂现在有了个伤痕}
{5206}{}{，小孩在失去平衡后倒在地上}
{5207}{}{，那手臂啪的一声就断了。小孩开始放声大哭}
{5208}{}{，好像棒棒糖一样那条手臂就被折断了。}
{5209}{}{。右臂开始发踵，像个气球一样}
{5210}{}{，并且开始哭}
{5211}{}{一个敏感的地方}
{5212}{}{。在击中了一个主要的器官后，小孩倒了下去}
{5213}{}{，像娃娃一样将这小孩打倒}
{5214}{}{。现在，这一个小孩永远都不用体验到人生的痛苦了}
{5215}{}{，伤口切得很深}
{5216}{}{。那一击把小孩打到地上，并且将腿打断}
{5217}{}{，将那小孩打成重伤}
{5218}{}{。小孩看着你，并且开始大哭}
{5219}{}{，将他弄瞎了}
{5220}{}{，重重的给他那小小的鼻子一击}
{5221}{}{。一个切口出现在眼睛上方，血随即泉涌而出}
{5222}{}{，将眼睛打爆了。小孩因此而发了愣}
{5223}{}{让眼睛瞎了。那小孩因此倒在地上}
{5224}{}{，那一击打穿了小孩的脑袋}
{5225}{}{。小孩子全身发抖}
{5226}{}{，将那年幼的身体打到地上}
#
# series 5300 - Super Mutants
#
{5300}{}{，伤了那强壮的变种人}
{5301}{}{，打中了一个要害}
{5302}{}{，打中了一个要害，并且将那巨大的怪物打到地上}
{5303}{}{。那巨大的变种人四处看看，然后随即倒在地上}
{5304}{}{。它的头就像巨大的西瓜一样爆炸了}
{5305}{}{，让巨大的变种人受了重伤}
{5306}{}{，让那巨大的变种人气得乱骂三字经}
{5307}{}{，打中了主要的神经，让它抓着自己的手臂直喊着疼}
{5308}{}{。那一击将它的手腕打碎了}
{5309}{}{，将他那粗大的手臂打断，并且血溅五步}
{5310}{}{，让那巨人失去平衡，并且像被砍伐的大树一样倒在地上}
{5311}{}{，然后它的内脏全部都流到地上}
{5312}{}{，将它打得飞到地上}
{5313}{}{。变种人摇摇晃晃的，最后倒在地上，因为它的腿已经无法支称它的重量了。}
{5314}{}{，打中了了要害。变种人的腿应声而断。}
{5315}{}{，既使是这样大的怪物也受不了那样的疼痛。}
{5316}{}{，差一点就将变种人给打瞎了}
{5317}{}{，将生气的变种人给打瞎了}
{5318}{}{，差一点就将变种人打瞎了，不过，它却失去了平衡}
{5319}{}{。变种人既使是瞎了也没有减低他的斗志}
{5320}{}{，将不省人事的变种人打瞎了}
{5321}{}{。变种人的眼睛慢慢地失去的光明－永远的。}
#
# series 5400 - Ghouls
#
{5400}{}{。对于你这突如其来攻击，僵尸来不及接招而被打个正着}
{5401}{}{。这一击将该僵尸送进了坟墓}
{5402}{}{。被突然的击中，僵尸的手应声而断}
{5403}{}{，这一击穿过了装甲，直接的打断了僵尸的关节}
{5404}{}{，这一击穿过了装甲，直接的切断了僵尸的双手}
{5405}{}{。僵尸的眼睛被打个正着，因此它失去了一只眼}
{5406}{}{。它那里并没有穿任何的装甲}
{5407}{}{，因为没有保护，因此僵尸被打瞎了}
{5408}{}{，让僵尸不知道自己是怎么死的}
#
# series 5500 - Brahmin
#
{5500}{}{，将这大野兽倒在地上}
{5501}{}{，击中了这野兽的两个头，以致它随即倒在地上}
{5502}{}{。这双头牛大声的哀号}
{5503}{}{，打断了双头牛的一条腿}
{5504}{}{，将这双头牛打成重伤}
{5505}{}{，很容易的就打穿这猛兽的皮}
{5506}{}{，穿过双头牛的身体，直接的打中了它的心脏}
{5507}{}{，一击就将它两双眼给打瞎了}
{5508}{}{，将全部的眼都打瞎了，让这只双头牛不知所措}
{5509}{}{，将双头牛打瞎，并且打晕}
{5510}{}{，这巨兽失去了平衡一阵子}
{5511}{}{。双头牛很生气}
{5512}{}{。双头牛愤怒的哀号}
{5513}{}{。对于你密集的攻击双头牛感到很生气}
#
# series 5600 - Radscorpions
#
{5600}{}{，将毒蝎子打得飞上了天}
{5601}{}{，将它的头与身体分开了}
{5602}{}{，将尾巴打得伤重不已}
{5603}{}{，在爪子上造成了严重的伤害}
{5604}{}{。那一击打重了甲壳之间的接缝}
{5605}{}{，穿过了毒蝎坚硬的外壳}
{5606}{}{，穿过了毒蝎与生俱来的装甲，并且将其打倒在地上}
{5607}{}{。对于这前所未有，失去内脏的感觉，毒蝎感到无法承受}
{5608}{}{，毒蝎飞上了天，同时失去了它的一些脚}
{5609}{}{。那一击打中了它腿上没有保护的地方，因此腿应声而断}
{5610}{}{，让毒蝎受了相当严重的伤害}
{5611}{}{，差一些就可以将毒蝎的脑给打烂。这就是将一只虫碾死的感觉吧}
{5612}{}{，差一些就可以将毒蝎的脑给打烂，不过却将它打瞎了}
{5613}{}{。这是简单的一击，但是对毒蝎来说却是致命的一击}
{5614}{}{。如果那是一个人的话，他一定会相当的生气}
{5615}{}{，将那可怜的昆虫打得乱七八糟}
{5616}{}{，将它打得脑浆四溢}
#
# series 5700 - Rats
#
{5700}{}{。老鼠头骨碎裂的声音听起来也令人感到恶心}
{5701}{}{，将老鼠的头像一颗蛋一样打烂}
{5702}{}{，而且左边的爪子好像不见了}
{5703}{}{。老鼠的左爪被炸烂了}
{5704}{}{。左边的爪子受到了相当严重的伤}
{5705}{}{，将右爪给炸掉了}
{5706}{}{。老鼠被这一击给打成重伤}
{5707}{}{，重伤的老鼠开始慌张的跑}
{5708}{}{，将老鼠打得肝脑涂地}
{5709}{}{，将右脚打残了}
{5710}{}{，在左腿上开了一个大洞}
{5711}{}{，那一击的伤害特别重，因为你打中了老鼠特别敏感的地方}
{5712}{}{，将它送上了西天}
#
# series 5800 - Floaters
#
{5800}{}{，浮游特随即倒在地上}
{5801}{}{，浮游特随即倒在地上，看上去毫无生命的迹象}
{5802}{}{，让这生物无法继续的活着}
{5803}{}{，让这下等的生物吓了一跳}
{5804}{}{，打中了特别虚弱的地方，让这下等的生物吓了一跳}
{5805}{}{。这一击让浮游特严重的哀号}
{5806}{}{，这一击让浮游特相当的生气}
{5807}{}{。浮游特突然的着火了}
{5808}{}{然后它开始抽动，一副相当痛苦的样子}
{5809}{}{，那一击打中了它的弱点}
{5810}{}{。那生物现在相当的焦虑}
#
# series 5900 - Centaurs
#
{5900}{}{，这一击使得多脚兽倒在地上}
{5901}{}{当那一击打中了要害时}
{5902}{}{，破坏了神经线路}
{5903}{}{，这暴力的攻击让它相当的惊讶}
{5904}{}{，废了它的臂膀}
{5905}{}{打到了一个弱点，废了它的臂膀}
{5906}{}{，将多脚怪打在地上，并且废了它的腿}
{5907}{}{，让它还不知道发生了什么事时就断了一条腿的倒在地上}
{5908}{}{，让它瞎了眼}
{5909}{}{，攻其不备的，让它失去了平衡}
{5910}{}{，攻其不备的，让它倒在地上}
{5911}{}{，攻其不备的，让它血肉模活倒在地上}
{5912}{}{。那一击并没有你想像中那样大的效果}
#
# series 6000 - Robots
#
{6000}{}{，让它的外部受到了一些伤害}
{6001}{}{，让机器人暂时的失去了作用}
{6002}{}{，打中了一个主要的零件，让机器人开始失去控制}
{6003}{}{，打中了一个主要的零件，让机器人的系统失去作用}
{6004}{}{。机器人开始尝试着自我修复}
{6005}{}{。机器人尽力的跳过被损坏的系统}
{6006}{}{，打中了一些主要的零件，造成了相当大的损伤}
{6007}{}{，造成了相当严重的外部损伤}
{6008}{}{，打中了一个主要的系统，造成了相当大的伤害}
{6009}{}{。在重击之后机器人无法正常的运作}
{6010}{}{，并将机器人给分解了}
{6011}{}{。机器人开始尝试着自我修复，但却失败了，它即刻应声倒在地上}
{6012}{}{。机器人承受了太大的力量，因此倒在地上}
{6013}{}{，打碎了感应器的镜片}
#
# series 6100 - Dogs
#
{6100}{}{，将狗打得躺在地上}
{6101}{}{，正中鼻子}
{6102}{}{。狗四脚朝天，但却仍在呼吸}
{6103}{}{，那只狗吐出了一泡鲜血}
{6104}{}{，废了它的腿}
{6105}{}{，废了它的腿。它试着要爬起来，但是却失败了}
{6106}{}{。瞎了眼的狗开始凄惨的叫着}
{6107}{}{，将那只可怜的狗阉了}
#
# series 6200 - Manti
#
{6200}{}{，将那变种的昆虫打倒了}
{6201}{}{，然后便四脚朝天了}
{6202}{}{。螳螂应该是活不久了}
{6203}{}{，废了它的脚}
{6204}{}{，因此螳螂开始舔它的伤口。它伤得很重}
{6205}{}{，打穿了它的壳}
{6206}{}{。螳螂开始发抖抽动}
{6207}{}{，让螳螂倒在地上。它的脚被折断变成奇怪的形状}
{6208}{}{，翅膀开始发抖}
{6209}{}{，打穿了它的壳，并且将它打得飞出去}
{6210}{}{，准确的一击将那昆虫给打瞎了}
#
# series 6300 - Deathclaw
#
{6300}{}{。既使是像那样强的怪物也被这突然而来的一击给吓到了}
{6301}{}{，穿过了怪物巨大的爪子直接打中了它的身体。死亡爪开始因疼痛而发抖}
{6302}{}{。结果是造成了死亡爪眼部的伤害}
#
# series 6400 - Spore Plant  # Was The Master
#
{6400}{}{，穿过了植物的防卫}
{6401}{}{，将它一些的叶子给扯了下来}
{6402}{}{，将它的一些枝叶给打断了}
{6403}{}{，将它的叶绿素给打得流了出来}
{6404}{}{，将它打的花粉都喷了出来}
{6405}{}{。差点将它给打翻了}
{6406}{}{，将它的一些树枝给折断了}
#
# series 6500 - The Player
#
{6500}{}{。你就算明天还活着的话，头也会相当的痛}
{6501}{}{。对于这相当准确的一击，你的装甲也发挥不了什么保护作用}
{6502}{}{。你感觉到了短暂的痛楚，接着而来的就是昏天黑地的感觉．．}
{6503}{}{，穿过了你的装甲。那一击将你打得倒在地上}
{6504}{}{，力量大到让你看不清楚。过一会儿后，你发现你的视觉又回复正常了}
{6505}{}{。当你头飞掉的一瞬间，你第一次从不同的角度看到了你的身体}
{6506}{}{。令你惊讶的是，这伤口并没有那么痛}
{6507}{}{，让你吃了一惊}
{6508}{}{。感觉到了相当的痛苦}
{6509}{}{。那一击让你的手臂失去了作用}
{6510}{}{，穿过了你的装甲。那一击打碎了你手臂里的骨头}
{6511}{}{，穿过了你的装甲。现在你的手臂只剩下皮连着挂在身上}
{6512}{}{。伤口会让你看起来更有英雄气概，疤痕更将是开派对时的好话题}
{6513}{}{，打伤了你的内脏。你现在只能够一直吐血}
{6514}{}{，将你的头打飞了}
{6515}{}{，将你打得飞出去，并且将你的腿折断了}
{6516}{}{，将你的装甲打碎。那一击很严重的伤了你的膝盖}
{6517}{}{。断腿之痛让你昏了过去}
{6518}{}{。那疼痛的一击让你叫了一声，如此而已}
{6519}{}{。不幸的，那也让你失去了视觉}
{6520}{}{。你将眼中的血擦掉}
{6521}{}{，穿过了你的装甲。你站在那边，惊讶的发现你看不见了}
{6522}{}{。你觉得头里很奇怪，你发现你的脑已受了重伤}
{6523}{}{，使得你变得畏缩}
{6524}{}{。你双手抓着你的下体并且痛得在地上打滚}
{6525}{}{。疼痛的程度还不足以让你昏过去。}
{6526}{}{。你现在感到的疼痛是言语所不能形容的}


# Fallout 2:

#
# series 6700 - Gecko
#
{6700}{}{，穿过了蜥蜴的防卫}
{6701}{}{，将它身上一些黏答答的皮肤扯了下来}
{6702}{}{，将它一些指头打断了}
{6703}{}{，让它不能够呼吸}
{6704}{}{，把它的内脏打了出来}
{6705}{}{，差一点将它打倒了}
{6706}{}{，将他的手脚打伤了}
#
# series 6800 - Alien
#
{6800}{}{，穿过了那生物的防卫}
{6801}{}{，将它的外皮扯了一些下来}
{6802}{}{，将它的一些器官打伤了}
{6803}{}{，让它不能够呼吸(?)了}
{6804}{}{，让它吐出了一些恶心的东西}
{6805}{}{，差点让它失去平衡}
{6806}{}{，打伤了它一些触脚}
#
# series 6900 - Giant Ant
#
{6900}{}{，过穿过了蚂蚁的防卫}
{6901}{}{，将它的触角给拔了下来}
{6902}{}{，打断了它的嘴}
{6903}{}{，将它打成了重伤}
{6904}{}{，将它打的在地上打滚}
{6905}{}{，差点让他四脚朝天}
{6906}{}{，打伤了它的外壳}
#
# series 7000 - Gun Turret  -- WIP! Won't Work!
#
{7000}{}{，过穿过了蚂蚁的防卫}
{7001}{}{，将它的触角给拔了下来}
{7002}{}{，打断了它的嘴}
{7003}{}{，将它打成了重伤}
{7004}{}{，将它打的在地上打滚}
{7005}{}{，差点让他四脚朝天}
{7006}{}{，打伤了它的外壳}

# Series 7100 - End Boss
{7100}{}{，穿过了保护的装甲}
{7101}{}{，打穿他的膝盖保护}
{7102}{}{，破坏了手臂操作系统}
{7103}{}{，破坏了腿部转动系统}
{7104}{}{，打碎了他的生化眼}
{7105}{}{，强烈的攻击让他剧烈的摇动}
{7106}{}{，打穿了他的护胸}