#
# 控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# 控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控
#
#
{100}{}{完成}
{101}{}{选项}
{102}{}{取消}
{103}{}{列印}
{104}{}{年龄}
{105}{}{性别}
{106}{}{名字}
{107}{}{男性}
{108}{}{女性}
{109}{}{额外能力}
{110}{}{道德良知}
{111}{}{杀敌数}
{112}{}{技能点数}
{113}{}{等级:}
{114}{}{经验:}
{115}{}{下次升级:}
{116}{}{人物点数}
{117}{}{技能}
{118}{}{你一定要使用所有的人物点数之后才} # 1
{119}{}{可以进行游戏！}         # 2
#
{120}{}{人物点数}
{121}{}{这一些点数可以用来分配到人物基本的状态数值中。}
{122}{}{到下次升级}
{123}{}{到下一次升级所需要的经验点数。}
{124}{}{特别技术}
{125}{}{道德}
{126}{}{战绩}
{127}{}{额外能力给予人物更多的技术。人物每升三个等级时，就可选择一种新的额外能力。}
{128}{}{人物在游戏中的种种行迳都会影响到这一个数值的变化。}
{129}{}{这一项所显示的是人物在整个游戏中所杀死的人物或是生物。}
{130}{}{技能点数}
{131}{}{使用这一些点数来增加某一技能的等级，让人物对该技能更加的熟练。当等级越高，所需要升级的技术点术就会增加，因此，要能够将一项技术练好是相当困难的事。}
#
{132}{}{已在最大值。}   # 1
{133}{}{无法再增加。}   # 2
{134}{}{已在最小值。}   # 1
{135}{}{无法再减少。}   # 2
{136}{}{技术点数不够。}
{137}{}{基本:}
{138}{}{特长技能}
{139}{}{可选择人物特征}
{140}{}{你已经选择了}   # 1
{141}{}{三个特长技能}   # 2
{142}{}{在你进入游戏前必需选足} # 1
{143}{}{人物特长技能}   # 2
{144}{}{特长技能}
{145}{}{特长技能是人物所专长的技能。每一个选择的技能在升级的速度上比其他技能要快两倍。你一定要选择三种。}
{146}{}{人物特征}
{147}{}{人物特征是一个人物的特性与能力。每一种能力都有优劣处，你一定要选择两种。}
{148}{}{你已经选择了}   # 1
{149}{}{两种人物能力了} # 2
{150}{}{技能}
{151}{}{技能是随着经验而熟练的。技能等级越高，技能使用的成功率就越好。}
#
{152}{}{选一个额外能力}
{153}{}{选一个新的特征}
{154}{}{去掉一个特征}
{155}{}{选择一个新的选择技能}
{156}{}{特征}
#
{157}{}{在游戏开始之前，所有的点数} # 1
{158}{}{都得要在1到10之间！}          # 2
# Fallout 2:
{160}{}{警告：你还没有改变人物的名字，你要继续使} # 1
{161}{}{用这一个人物吗？}        # 2

{175}{}{到下一等级:}  # Short for Level:


#
# Abbreviated basic stat levels
#
{200}{}{非常糟} # Terrible
{201}{}{糟糕}   # Bad
{202}{}{贫弱}   # Poor
{203}{}{尚可}   # Fair
{204}{}{平均}   # Average
{205}{}{好}     # Good
{206}{}{非常好} # Very Good
{207}{}{棒极了} # Great
{208}{}{完美}   # Excellent
{209}{}{超强}   # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{生命点数}
{301}{}{行动点数}
{302}{}{防护等级}
{303}{}{空手伤害力}
{304}{}{肉搏战伤害力}
{305}{}{抗击能力}
{306}{}{抗毒性}
{307}{}{抗辐射性}
{308}{}{行动顺序}
{309}{}{康复速度}
{310}{}{致命一击机率}
{311}{}{可携带重量}
{312}{}{中毒}
{313}{}{辐射伤害}
{314}{}{眼部受伤}
{315}{}{右臂受伤}
{316}{}{左臂受伤}
{317}{}{右腿受伤}
{318}{}{左腿受伤}

#
# Damage info texts
#
# Poisoned
{400}{}{你的人物中毒了。毒将会在一段时间中造成伤害，直到它被治好，或者是失去作用为止。}
# Radiation
{401}{}{你的人物受到了大量放射线的影响。越多的放射线将会造成越多的伤害。}
# Eye Damage
{402}{}{这代表着你的人物的一只眼、或者是双眼受了很重的伤。这将会影响你的感知。}
# Crippled right arm
{403}{}{这代表你的右臂受了伤，失去功能了。一只臂受了伤便不能使用双臂的武器。如果两臂都受了伤，便无法使用任何武器。}
# Crippled left arm
{404}{}{这代表你的左臂受了伤，失去功能了。一只臂受了伤便不能使用双臂的武器。如果两臂都受了伤，便无法使用任何武器。}
# Crippled right leg
{405}{}{你的人物伤了右腿。}
# Crippled left leg
{406}{}{你的人物伤了左腿。}

# Month strings
{500}{}{一月}
{501}{}{二月}
{502}{}{三月}
{503}{}{四月}
{504}{}{五月}
{505}{}{六月}
{506}{}{七月}
{507}{}{八月}
{508}{}{九月}
{509}{}{十月}
{510}{}{十一月}
{511}{}{十二月}

#
# Option menu text
#
{600}{}{储存}
{601}{}{读取}
{602}{}{列印到档案}
{603}{}{删除}
{604}{}{完成}
{605}{}{你确定要将目前的人物设定}      # line 1
{606}{}{完全删除吗？}                 # line 2
{607}{}{成功的被储存了。}
{608}{}{成功的被读取了。}
{609}{}{已经存在了。}
{610}{}{你想要重覆写入吗？}
{611}{}{储存错误}
{612}{}{读取错误}
{613}{}{非法的人物档案。}
{614}{}{非法的人物资料。}
{615}{}{无法读取档案名单！}
{616}{}{PRINT}
{617}{}{PLAYER}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{异尘余生}                   # Title line 1
{621}{}{第１３号避难所人员记录} # Title line 2
{622}{}{小时} # Title line 3
# -
# -
#{000}{}{力量: 00        生命点数: 000/000         行动顺序: 00}
#{000}{}{感知: 00        防护等级: 000             康复速度: 00}
#{000}{}{耐力: 00        动作点数: 000         致命一击机率: 000%}
#{000}{}{魅力: 00    肉搏战伤害力: 000           可携带重量: 000 lbs.}
#{000}{}{智力: 00        抗击能力: 000%}
#{000}{}{敏捷: 00        抗辐射性: 000%}
#{000}{}{运气: 00          抗毒性: 000%}
#
{623}{}{ ::: 资      料 :::}
{624}{}{           力量:}
{625}{}{            生命力:}
{626}{}{        攻击次序:}
# -
{627}{}{         感知:}
{628}{}{            防御力:}
{629}{}{              治愈力:}
# -
{630}{}{           体力:}
{631}{}{          动作点数:}
{632}{}{         致命一击机率:}
# -
{633}{}{           魅力:}
{634}{}{          空手伤害:}
{635}{}{         可携带重量:}
# -
{636}{}{           智力:}
{637}{}{        伤害免役力:}
# -
{638}{}{           敏捷:}
{639}{}{      放射线免役力:}
# -
{640}{}{           运气:}
{641}{}{          毒免役力:}
# -
# -
#{000}{}{ 名字: 01234567890        Age: 00         Gender: Female}
{642}{}{  名字:}
{643}{}{年龄:}
{644}{}{                性别:}
{645}{}{男性}
{646}{}{女性}
#-
#{000}{}{ Level: 00                 Exp: 000,000    Next Level: 000,000}
{647}{}{  等级:}
{648}{}{             经验值:}
{649}{}{到下次升级:}
#-
{650}{}{ :::人物特征:::}
{651}{}{ :::额外能力:::}
{652}{}{ :::道德良知:::}

#-
{653}{}{ :::  技能  :::                ::: 杀敌数 :::}
#-
{654}{}{ ::: 物     品 :::}
#-
{655}{}{                                            总重量:}
{656}{}{ ::: 上      瘾 :::}
{657}{}{ ::: 名      誉 :::}

#
# Karma name strings
#
{1000}{}{道德良知分数}
{1001}{}{疯子}
{1002}{}{赢家}
{1003}{}{杀小孩者}
{1004}{}{核子可乐瘾君子}
{1005}{}{巴服特瘾君子}
{1006}{}{曼他特瘾君子}
{1007}{}{赛可瘾君子}
{1008}{}{抗辐射药瘾君子}
{1009}{}{酒精瘾君子}
{1010}{}{杰特瘾君子}
{1011}{}{迷上悲剧卡的人}
{1012}{}{THIS GOES WITH THE TEMPORARY ONE FOR DESCRIPTIONS #1112: DON'T TRANSLATE THIS}
{1013}{}{性爱高手}
{1014}{}{奖金斗士}
{1015}{}{牛郎}
{1016}{}{盗墓者}
{1017}{}{左右手：沙尔瓦多}
{1018}{}{已婚}
{1019}{}{色情片明星}
{1020}{}{奴隶贩子}
{1021}{}{荒野的处女（男）}
{1022}{}{左右手：彼希}
{1023}{}{左右手：莫丁诺}
{1024}{}{左右手：莱特}
{1025}{}{离婚者}
{1026}{}{烟鬼}

#
# Karma description strings
#
{1100}{}{这代表着一般人对你的看法，数字越高，别人对你越尊敬。如果这个数字是负值，表示你做了太多邪恶的事了。}
{1101}{}{你杀了太多的人。这并不是一件好事，不过，邪恶的人都会比较喜欢你。}
{1102}{}{你的种种所作所为让他人都对你刮目相看，你与邪恶战斗的故事在人们之间传着。好人都会对你较为尊敬。}
{1103}{}{你曾杀过小孩，这是一件相当可怕的事。别人都认为你是相当邪恶的人。}
{1104}{}{你很喜欢核子可乐，核战后世界所爱的饮料。}
{1105}{}{你上了巴服特的瘾，你若不按时服用，就会觉得很痛苦。}
{1106}{}{你上了曼他特的瘾，你若不按时服用，就会觉得很痛苦。}
{1107}{}{你上了赛可的瘾，，你若不按时服用，就会觉得很痛苦。但是，如果你服用的话，其他人就倒霉了。}
{1108}{}{你的身体上了辐射药的瘾。虽然它并不会威胁你的生命，但是你还是得按时服用。}
{1109}{}{你不能够控制自己饮用酒精的量。}
{1110}{}{你上了杰特的瘾，你若不按时服用，就会觉得很痛苦。}
{1111}{}{你上了″悲剧牌″的瘾，你随时都在寻找最新的、更强的牌。}
{1112}{}{TEMPORARY - What is this?}
{1113}{}{你懂得性。你懂得如何进行前戏。你懂得如何取悦异性，让他们事后仍意犹未尽。}
{1114}{}{你是北加州重量级的拳击冠军。你得到了名誉、尊敬．．以及许多的奖金。}
{1115}{}{让我们开门见山的说：只要是两只脚的都可以与你上床。}
{1116}{}{“他们死了，不会介意的。”是你的座右铭。对你来说，将死人遗骨挖出变成了你的习惯。}
{1117}{}{你成为了沙尔瓦多家族的左右手。现在每一个人都认识你、尊敬你。}
{1118}{}{恋爱的坟墓，家庭的枷锁。}
{1119}{}{你是一颗明亮的巨星。你在三级片中的大胆演出已是新里诺众人皆知的。}
{1120}{}{你是奴隶贩子中的一个。在你臂上的刺青明显的告诉别人你的职业。}
{1121}{}{你真的得要多玩玩，你还从未有．．性经验咧。}
{1122}{}{你成为了彼希家族的左右手。现在每一个人都认识你、尊敬你。}
{1123}{}{你成为了莫丁诺家族的左右手。现在每一个人都认识你、尊敬你。}
{1124}{}{你成为了莱特家族的左右手。现在每一个人都认识你、尊敬你。}
{1125}{}{你的配偶已然离开你了，你又自由了。}
{1126}{}{You are a smoker. They say it'll kill ya, but you're not dead yet. And anyway, it's a good way to look damn cool in a post-apocalyptic world.}

#
# Town reputations
#
{2000}{}{偶像}
{2001}{}{受欢迎}
{2002}{}{被接受}
{2003}{}{中立}
{2004}{}{受怀疑}
{2005}{}{被讨厌}
{2006}{}{被怀恨}

{2100}{}{因为你英勇的事迹，这里每一个人都想要变成你。}
{2101}{}{每一个人都会向你打招呼。每一个人都听过你的事迹。}
{2102}{}{虽然不是每一个人都会向你打招呼，不过每一个人都认识你。}
{2103}{}{虽然对于外人都会半存怀疑的态度，但是这里的人还未对你有什么看法。}
{2104}{}{你对这里的人来说，不过是另一个外人，也许有什么不良的企图吧。}
{2105}{}{你证明了这一些人原本对你的不信任是对的。这一些人都知道你有不良的企图。}
{2106}{}{这一些人看到你不是闪开，就是对你吐口水。每一个人都认为你是一个最邪恶的人。}

#
# Karma status strings
#
{3000}{}{救世主}
{3001}{}{荒野守护神}
{3002}{}{希望之盾}
{3003}{}{防御者}
{3004}{}{幻想者}
{3005}{}{背叛者}
{3006}{}{绝望之剑}
{3007}{}{荒野的秃鹰}
{3008}{}{恶魔转生}

#
# Karma section titles.
#
{4000}{}{名誉}
{4001}{}{上瘾}

#
# Karma section descriptions.
#
{4100}{}{代表着你某一方面的名誉。}
{4101}{}{一些让你上瘾的东西。}

#
# Special Demo version only text
#
{5000}{}{Sorry, you can only print your}   # 1
{5001}{}{character in the full version.}   # 2
{5002}{}{Sorry, you can only save your}    # 1
{5003}{}{character in the full version.}   # 2
{5004}{}{Sorry, you can only load a saved} # 1
{5005}{}{character in the full version.}   # 2
{5006}{}{CHEAT MODE}
{5007}{}{Not available in demo.}
