#
# Inventory messages from inventry.c
#
{0}{}{力量}
{1}{}{感知}
{2}{}{体力}
{3}{}{魅力}
{4}{}{智力}
{5}{}{敏捷}
{6}{}{运气}
{7}{}{生命点数}
{8}{}{防护等级}
{9}{}{	普通}
{10}{}{  激光}
{11}{}{  火焰}
{12}{}{  电浆}
{13}{}{  爆炸}
{14}{}{没有物品}
{15}{}{损伤:}
{16}{}{射程:}
{17}{}{弹药:}
{18}{}{(没有装备)}
{19}{}{你没有足够的行动点数来使用物品。}
{20}{}{总重量:}
{21}{}{移动物品}
{22}{}{全部}
{23}{}{设定计时器}
{24}{}{肉搏战伤害力:}
{25}{}{你的载重量已到达极限，无法捡起该物品。}
{26}{}{你已经没有地方放该物品了。}
{27}{}{那是一个很好的交易。}
{28}{}{不，你所开出的条件不够好。}
{29}{}{你成功使用了偷窃的技术，因此你得到了 %d 点经验值。}
{30}{}{重量。}
{31}{}{你无法负荷那样多的东西。}
{32}{}{你无法负荷那样多的东西。}

{50}{}{你找不到任何可以拿取的东西。}
