#
# Inventory messages from inventry.c
#
{0}{}{力量}
{1}{}{感知}
{2}{}{体力}
{3}{}{魅力}
{4}{}{智力}
{5}{}{敏捷}
{6}{}{运气}
{7}{}{生命点数}
{8}{}{防护等级}
{9}{}{  常规}
{10}{}{  激光}
{11}{}{  火焰}
{12}{}{  电浆}
{13}{}{  爆炸}
{14}{}{没有物品}
{15}{}{伤害:}
{16}{}{射程:}
{17}{}{弹药:}
{18}{}{(没有装备)}
{19}{}{你没有足够的行动点数来使用物品栏。}
{20}{}{总重量:}
{21}{}{移动物品}
{22}{}{全部}
{23}{}{设定计时器}
{24}{}{徒手伤害:}
{25}{}{你的负重已到达极限，无法拾取该物品。}
{26}{}{你已经没有空间放置该物品了。}
{27}{}{好的，这真是个不错的交易。}
{28}{}{不行，你开出的条件不够好。}
{29}{}{你成功使用了偷窃技能，得到了 %d 点经验值。}
{30}{}{重量}
{31}{}{你无法携带那么多的物品。}
{32}{}{物品太多你无法携带。}

{50}{}{你找没有找到任何可拾取的物品。}
