#
#   Messages from perk.c
#
#
#   PERK NAMES
#
{101}{}{警觉力}
{102}{}{快速徒手攻击}
{103}{}{额外的空手伤害}
{104}{}{额外的出手机会}
{105}{}{额外的攻击距离}
{106}{}{额外的开火速度}
{107}{}{先发制人}
{108}{}{快速恢复}
{109}{}{更多的致命一击}
{110}{}{夜视能力}
{111}{}{现身}
{112}{}{辐射抵抗力}
{113}{}{强悍过人}
{114}{}{善背}
{115}{}{神射手}
{116}{}{衔枚疾走}
{117}{}{适者生存}
{118}{}{大奸商}
{119}{}{知识份子}
{120}{}{医疗师}
{121}{}{寻宝者}
{122}{}{更强的致命一击}
{123}{}{神入}
{124}{}{杀手}
{125}{}{狙击手}
{126}{}{暗杀}
{127}{}{活力小子}
{128}{}{意志力}
{129}{}{强韧生命力}
{130}{}{闪躲高手}
{131}{}{吃蛇人}
{132}{}{维修大师}
{133}{}{医学常识}
{134}{}{神偷}
{135}{}{发言人}
{136}{}{飞刀手！}
{137}{}{ERROR -- UNIMPED}  # was -- Friendly Foe
{138}{}{妙手空空}
{139}{}{神出鬼没}
{140}{}{八面玲珑}
{141}{}{搜寻者}
{142}{}{探险家}
{143}{}{高免役力}
{144}{}{寻路者}
{145}{}{动物之友}
{146}{}{斥侯}
{147}{}{神秘陌生人}
{148}{}{野外专家}
{149}{}{快速翻找}
{150}{}{舌灿莲花}
{151}{}{聪明过人}
{152}{}{增加特长技能}
{153}{}{突变！}
{154}{}{上了核子可乐的瘾}
{155}{}{上了巴福特的瘾}
{156}{}{上了曼他特的瘾}
{157}{}{上了赛可的瘾}
{158}{}{上了辐射药的瘾}
{159}{}{长程武器}
{160}{}{武器准确度}
{161}{}{武器穿透度}
{162}{}{武器震撼力}
{163}{}{动力装甲}
{164}{}{战斗装甲}
{165}{}{远距狙击}
{166}{}{枪械快速上膛}
{167}{}{武器夜视镜}
{168}{}{玩火专家}
{169}{}{高级装甲Ｉ}
{170}{}{高级装甲ＩＩ}
{171}{}{杰特中毒}
{172}{}{悲惨上瘾}
{173}{}{装甲强度}
{174}{}{剥蜥蜴皮}
{175}{}{皮肤装甲}
{176}{}{增强的皮肤装甲}
{177}{}{凤凰生化装甲}
{178}{}{凤凰抗击生化装甲}
{179}{}{地下掩体市疫苗接种}
{180}{}{肾上线素}
{181}{}{小心翼翼}
{182}{}{吸收力}
{183}{}{爆破专家}
{184}{}{赌徒}
{185}{}{增加力量}
{186}{}{增加感知}
{187}{}{增加体力}
{188}{}{增加魅力}
{189}{}{增加智力}
{190}{}{增加敏捷}
{191}{}{增加运气}
{192}{}{无辜嘴脸}
{193}{}{马上升级}
{194}{}{闪避徒手攻击}
{195}{}{知名性爱专家}
{196}{}{道德}
{197}{}{潜行}
{198}{}{生物学家}
{199}{}{吸引力的人格}
{200}{}{谈判专家}
{201}{}{爱收东西的人}
{202}{}{纵火狂}
{203}{}{百折不挠}
{204}{}{推销员}
{205}{}{铜墙铁壁}
{206}{}{小偷}
{207}{}{武器专家}
{208}{}{地下掩体市的训练}
{209}{}{酒精增加生命力}
{210}{}{酒精增加生命力２}
{211}{}{酒精减少生命力}
{212}{}{酒精减少生命力２}
{213}{}{自动医生增加生命力}
{214}{}{自动医生增加生命力２}
{215}{}{自动医生减少生命力}
{216}{}{自动医生减少生命力２}
{217}{}{经验丰富的探险家}
{218}{}{武器增加打倒在地的力量}
{219}{}{倒霉鬼}
{220}{}{酒精上瘾}
{221}{}{烟鬼}

#
#   PERK DESCRIPTIONS
#
{1101}{}{拥有这项能力，当你检查每一个生物时都会得到更多的资料。你可以看到他们的生命点数以及身上配有的武器。}
{1102}{}{你学到了东方的神秘技巧，或者你只是拳出的很快而已。无论如何，你的空手攻击将会少使用１点的动作点数。}
{1103}{}{熟悉空手攻击技巧让你有更高的破坏力。你在空手或是武器攻击时每个等级都会造成＋２的伤害。}
{1104}{}{这种能力每提高一级你都会在每一轮得到２点的动作点数。也就是说，每一个等级中，你都可以多移动２格。}
{1105}{}{你在长程武器和枪炮方面的训练让你的长程攻击力大增。在每一个等级中若使用长程武器，你都会造成＋２的伤害。}
{1106}{}{这个能力可以让你更快的开火，同时保有原来的准头。每种长程的武器在使用上都会少用１个动作点数。}
{1107}{}{在每一个等级中，你的战斗顺序点数都会＋２，因此你在一个战斗之中几乎都可以比你的敌人先移动。}
{1108}{}{在每一个等级中，你都会得到＋２的治疗速率。这是在普通速率上面另外加上去的点数，因此，你自我疗伤的速度会更加的快。}
{1109}{}{你在战斗中将可更容易的使出特别攻击。这能力的每一级都会增加５％的特别攻击使出机会。}
{1110}{}{当你拥有这项能力，你夜晚与地道中时可以看得更清楚。这能力会将画面的阴暗度减少２０％。}
{1111}{}{你只要进入房间内就会特别引人注意。别人对你的第一印象在每个等级都会增加１０％。}
{1112}{}{你将会变得较能抵抗放射线伤害。每个等级都会增加１５％的放射线免疫力。}
{1113}{}{当你有壮大的体格时，就比较不易受到伤害。每个等级都会增加１０％的普通攻击免疫力。}
{1114}{}{每个等级你都可以多背５０磅的物品。}
{1115}{}{你得到了可在射程之外射中目标的能力。每个等级都会增加２点的观察能力。现在攻击射程之外的敌人就更加容易了！}
{1116}{}{拥有这能力之后你可以更快的移动，但是仍然不会发出声音。如果没有这项能力，只要一跑步就会跳出潜行模式。}
{1117}{}{你是野外求生的专家。这一个能力可以让你在任何的环境中生存得更好。你得到了＋２５％的野外求生点数。}
{1118}{}{你得到了讨价还价的能力，现在你可以用更便宜的价钱买到许多物品。当你有这项能力时，你与商店或者是商人买东西时都会得到七五折的优待。}
{1119}{}{每个等级都会让人物在升级时增加＋２点的技术点数。你越早得到这一项能力，对你越有利。}
{1120}{}{拥有这项能力，对你的治伤技术会有很大的帮助。每个等级都可以让你在治伤时多治４～１０的生命点数。}
{1121}{}{你拥有寻找钱的能力。在每次找到钱的时候，你找到的数量都会比较多。}
{1122}{}{你在战斗时所使出的特别攻击将具有更高的伤害力。你在特别攻击表中将会多得２０％的点数，也就是说，攻击时会造成更大的伤害。不过这将不会影响使出特别攻击的机率。}
{1123}{}{你对于人们都有着相当的研究，让你可以很清楚的了解他们的心情。你在与他人长谈时可以看到他们目前对你的感觉为何。}
{1124}{}{你是世上一流的杀手！在空手攻击时你的每一击都会变成特别攻击，造成相当强的杀伤力。}
{1125}{}{你对于长程武器相当的拿手。拥有这个能力，每当你成功的使用长程武器攻击敌人时，每一击都会变成特别攻击。}
{1126}{}{当你在潜行的模式并从敌人背后攻击，你的空手攻击破坏力都会变成双倍。}
{1127}{}{每个等级的能力都会给予你更多的动作点数。}
{1128}{}{这一种能力可以让你不受到外界的脑波干扰。你只能从别人的身上学到这种技术，或是每天到酒吧待到很晚也可以练成这种技术。}
{1129}{}{当你升级时每个等级都会多得到４点生命点数。这是除了每次升级都会增加的生命点数之外额外的增加值。}
{1130}{}{如果你拥有这项能力，在战斗中你就比较不会被打中。你会增加＋５点到你的防御点数之中。}
{1131}{}{嗯！好喝！每个等级你的毒免疫力都会增加２５％。}
{1132}{}{这个能力会增加１０％的维修以及科学技术点数。不过只会增加一次。}
{1133}{}{这个能力会增加１０％的急救以及治疗技术点数。不过只会增加一次。}
{1134}{}{一个厉害的小偷是个偷东西以及开锁专家。你会得到＋１５的偷窃技术以及＋１５的开锁技术点数。}
{1135}{}{这个技术可以让你的演说能力增加２０％，只会增加一次。}
{1136}{}{每个等级都会增加２点的力量（最高１０点）。}
{1137}{}{ERROR.UNIMPED!}
{1138}{}{你将比一般小偷拥有更高深的偷窃技术。因为当你得到这个能力时，你在偷东西时无论敌人是谁，你都能以平常心去进行偷窃的工作。}
{1139}{}{当太阳下山时，或是当你到达一个没有灯的地方，你都可以像鬼魂一样移动而不被他人发现。你的潜行能力会在黑暗中增加２０％。}
{1140}{}{你在人心目中的印象将会永远是正面的。没有这个能力的话，你的名誉将会改变他人对你的看法。对于邪恶的人来说，他们也会对你有好印象，以为你也是邪恶的人。}
{1141}{}{你比别人都容易找到武器的弹药。这个能力会让你每一次找到弹药的数量变成双倍。}
{1142}{}{探险家最主要的目的就是寻找新的东西及地方。当你有这个能力时，你找到特别地方或是人物的机率就会增加。}
{1143}{}{当你拥有这个能力时，你就比较不容易上化学药品的瘾。（上瘾机率会变成平常的５０％）就算你上瘾后，回复正常的速度也是别人的两倍。}
{1144}{}{这个能力可以让你较容易找到最短的捷径。这个能力的每个等级都会将你在世界地图上移动的时间减少２５％。}
{1145}{}{动物们都不会攻击他们自己的朋友，除非他们首先受到了攻击或是遭到了威胁。}
{1146}{}{你远眺的能力增强了，在世界地图上看到范围的每个方向将会增加一格。当然，你遇到特别事件的机率也会增加。}
{1147}{}{当你有这个能力时，你将会得到神秘陌生人更多的注意，这些陌生人将会随时出现助你一臂之力。不过，他们将不会代替你死去的战友。}
{1148}{}{你的野外求生能力将会增加１５％。你在路上遇到的敌人将会减少许多，不过却会时常的遇到“特别”的事件。}
{1149}{}{你学会如何将物品作更有效的整理。这能力可以让你拿取背包内物品时只使用２点动作点数，而不是平常的４点。}
{1150}{}{你的对话反应选项会增加，虽然你并不知道你在说什么。这个能力的每个等级都会增加１点的智力点数，直到最高１０点为止。这一些增加的点数只对谈话有效。}
{1151}{}{拥有这个能力，你就是个学习速度快的人。当你每一次升级时都会多得到５％的经验值。因此越早得到这个能力对你越有利。}
{1152}{}{你可以再选择另一个“特长技能”了。“特长技能”的点数比普通技能点数增加的速度要快两倍。}
{1153}{}{在荒野中的放射线已经改变了你的体质！你的其中一种特征已经变成了另一种特征了．．}
{1154}{}{你想要再来一瓶核子可乐。}
{1155}{}{你全身发抖。}
{1156}{}{你觉得没有力气。}
{1157}{}{你觉得头昏眼花。}
{1158}{}{你觉得想吐。}
{1159}{}{长程武器}
{1160}{}{武器准确度}
{1161}{}{武器穿透度}
{1162}{}{武器反弹力}
{1163}{}{动力装甲}
{1164}{}{战斗装甲}
{1165}{}{武器射程}
{1166}{}{武器快速上膛}
{1167}{}{武器夜视镜}
{1168}{}{玩火专家}
{1169}{}{装甲升级１}
{1170}{}{装甲升级１}
{1171}{}{每一样东西都在动．．你需要更多的杰特，现在就要！}
{1172}{}{你觉得心中好想要再一次体验悲惨的滋味。}
{1173}{}{装甲能力}
{1174}{}{你有着如何将蜥蜴的皮剥下来的能力。}
{1175}{}{你有着先天的保护，可以受住所有的徒手攻击。}     # Dermal Impact Armor
{1176}{}{你有着特别的先天保护，可以受住所有的徒手攻击。}  # Dermal Impact Assault Enhancement
{1177}{}{你有着先天的保护，可以受住所有的能源攻击。}     # Phoenix Armor Implants
{1178}{}{你有着特别的先天保护，可以受住所有的能源攻击。}  # Phoenix Assault Enhancement
{1179}{}{你得到了＋１０％的毒以及放射线免疫力。}  # Vault City Inoculations
{1180}{}{当得到这个能力时，每当你的生命值低于一半的时候，你的力量会增加１。}  # Adrenaline Rush
{1181}{}{你在野外时你的警觉力会增加，因此敌人从背后偷袭的情况会减少。你的感知会增加３点。}  # Cautious Nature
{1182}{}{当你在读书时比别人更加专心，因此你在读书时会增加５０％或更多的技术点数。}  # Comprehension
{1183}{}{你是一个处理爆炸物的专家。当你要炸药爆炸，它就会爆炸，反之亦然。当然，你所装置的炸弹也会有着更强的伤害力。}  # Demolition Expert
{1184}{}{你是一个专业的赌徒。你的赌博技术会增加２０％。}  # Gambler
{1185}{}{这个能力会增加力量１点。}     # Gain Strength
{1186}{}{这个能力会增加感知１点。}   # Gain Perception
{1187}{}{这个能力会增加体力１点。}　   # Gain Endurance
{1188}{}{这个能力会增加魅力１点。}     # Gain Charisma
{1189}{}{这个能力会增加智力１点。}     # Gain Intelligence
{1190}{}{这个能力会增加敏捷１点。}   # Gain Agility
{1191}{}{这个能力会增加运气１点。}     # Gain Luck
{1192}{}{你无辜的外表让你偷起东西来更加容易。你的偷窃技术增加了２０％的点数。} # Harmless
{1193}{}{这个能力会让你马上升一个等级。} # Here and Now
{1194}{}{如果你的手都没拿东西，当每一轮结束后你都会得到２点防御点数，还有１／１２点的空手技术。}  # HtH Evade
{1195}{}{当你要用性来取悦对方时，你是一流的专家。} # Kama Sutra Master
{1196}{}{你的道德点数无论是好是坏都会变两倍。道德点数的影响，让大家对你的态度与反应都变成两倍。}  # Karma Beacon
{1197}{}{你很灵活、幸运、而且随时都很小心。这个能力会将你遇到陷阱的机率减半。}  # Light Step
{1198}{}{你对于生物的力量及弱点了若指掌。你会得到一次的１０％医疗能力增加，并且每次在攻击生物时都会多造成５点伤害。}  # Living Anatomy
{1199}{}{你可以多带一个队员，不过超过５个人就会变得相当的麻烦。}  # Magnetic Personality
{1200}{}{你是一个很会谈判的人。你不但很会讨价还价，而且可以鼓动不烂之舌就躲避各种麻烦。这个能力会增加１０％的杀价技术以及演说技术。}  # Negotiator
{1201}{}{你对物品的整理方面相当的有效率。让你总可以多放一点东西在背包里面。}  # Pack Rat
{1202}{}{你在使用火焰武器时可以造成更多的伤害，敌人总是会以最痛苦的“烈火焚身”方式死去。}  # Pyromaniac
{1203}{}{你被打倒时，很快的就可以再爬起来。}  # Quick Recovery
{1204}{}{你是一个很厉害的推销员。这个能力可以增加２０％的还价技巧。}  # Salesman
{1205}{}{你在战斗中将会很不容易被打倒在地。}  # Stonewall
{1206}{}{小偷的血流满你的全身。拥有这能力，你可以得到一次的１０％增加在潜行、开锁、偷窃、以及陷阱等方面。}  # Thief
{1207}{}{你可以舞动更大的武器。你得到了３个力量点数。}  # Weapon Handling
{1208}{}{你得到了地下掩体市的医疗训练。}  # Vault City Training
{1209}{}{你的生命点数因为你时常喝醉酒而增加了一些。}  # Alcohol Enhanced hit points
{1210}{}{你的生命点数因为你时常喝醉酒而增加了一些。}  # Alcohol Enhanced hit points II
{1211}{}{你的生命点数因为你时常喝醉酒而减少了一些。}  # Alcohol Lowered hit points
{1212}{}{你的生命点数因为你时常喝醉酒而减少了一些。}  # Alcohol Lowered hit points II
{1213}{}{你的生命点数因为你时常使用自动医生而增加了一些。}  # Autodoc Enhanced hit points
{1214}{}{你的生命点数因为你时常使用自动医生而增加了一些。}  # Autodoc Enhanced hit points II
{1215}{}{你的生命点数因为你时常使用自动医生而减少了一些。}  # Autodoc Lowered hit points
{1216}{}{你的生命点数因为你时常使用自动医生而减少了一些。}
{1217}{}{你拥有抛掷牛只的怪力。}
{1218}{}{武器增加击倒的力量}
{1219}{}{好消息是在你身边所有人都有更多的特别失败率，坏消息是你也一样！}
