#
# 控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控
#
# Text labels and messages used in PIPBOY.C
#
# (These MUST match "text message" enumeration on the top of PIPBOY.C)
#
# 控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控控

#
# Special holiday dates
#
{100}{}{新年快乐！}                 # New years
{101}{}{情人节快乐！}               # April fools
{102}{}{愚人节快乐！}               # April fools
{103}{}{游戏发行日快乐！}           # Shipping day!
{104}{}{美国国庆日快乐！}           # Independence day
{105}{}{万圣节快乐！}               # Halloween
{106}{}{感恩节快乐！}               # Thanksgiving
{107}{}{圣诞节快乐！}               # X-mas

#
# System messages
#
{200}{}{更多}
{201}{}{返回}
{202}{}{状况}
{203}{}{没有任何工作。}
{204}{}{提示}  # clues gone
{205}{}{地图}
{206}{}{影片资料库}
{207}{}{资料}
{208}{}{}
{209}{}{}
{210}{}{状况}
{211}{}{资料}
{212}{}{／}
{213}{}{页}
{214}{}{完成}
{215}{}{你不可以在这里休息！}

#
# Alarm clock
#
{300}{}{闹钟}
{301}{}{生命值}
{302}{}{休息十分钟}
{303}{}{休息卅分钟}
{304}{}{休息一小时}
{305}{}{休息两小时}
{306}{}{休息三小时}
{307}{}{休息四小时}
{308}{}{休息五小时}
{309}{}{休息六小时}
{310}{}{休息到早上(0800)}
{311}{}{休息到中午(1200)}
{312}{}{休息到晚上(1800)}
{313}{}{休息到半夜(0000)}
{314}{}{休息到生命值全满}
{315}{}{休息到全队的生命值全满}

#
# Holodisk titles
#
{400}{}{第１３号避难所实体显像磁片}
{401}{}{军用基地外部}
{402}{}{军用基地第一区}
{403}{}{军用基地第二区}
{404}{}{军用基地第三区}
{405}{}{军用基地第四区}
{406}{}{山岭基地ＥＸＰ记录}
{407}{}{山岭基地医生记录}
{408}{}{山岭基地彻出记录}
{409}{}{山岭基地ＧＮＮ记录}
{410}{}{山岭基地任务报告}
{411}{}{哈伯教教条}
{412}{}{地下掩体市设计记录}
{413}{}{地下掩体市旅程记录}
{414}{}{新加州共和国间碟实体显像磁片}
{415}{}{新加州共和国国史实体显像磁片}
{416}{}{卫斯丁的实体显像磁片}
{417}{}{国家现况}
{418}{}{文字表}
{419}{}{计划}
{420}{}{发电场操作手册}

#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{InterPlay公司标志}               # Not shown in Pipboy
{501}{}{开场电影}
{502}{}{长老的谈话}
{503}{}{找回避难所制服}
{504}{}{阿罗由失败}
{505}{}{阿罗由摧毁}
{506}{}{发动车子}
{507}{}{卡土西家族}
{508}{}{死亡爪的首领}
{509}{}{前往油田}
{510}{}{在英克雷的囚犯}
{511}{}{油田爆炸}
{512}{}{阿罗由之梦１}
{513}{}{阿罗由之梦２}
{514}{}{阿罗由之梦３}
{515}{}{阿罗由之梦４}
{516}{}{制作小组}

#
# Things for the Mac version to speak
#
#
{600}{}{Status}
{601}{}{Clues}  # Clues gone
{602}{}{Automaps}
{603}{}{Archives}
{604}{}{Alarm Clock}
{605}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{606}{}{Welcome to the Rob Co Pipboy 2000.}
{607}{}{So long.}
{608}{}{Wake up.}


#
# Status thread text
#
# Format:
# 0 City name
# 1 ... 9 thread/quest name
#
{700}{}{Vault 13}
{701}{}{Calm rebel faction.}
{702}{}{Destroy the Mutant leader.}
{703}{}{Destroy the source of the Mutants.}
{704}{}{Find the Water Chip.}
{705}{}{Find the Water Thief.}
#
{710}{}{Buried Vault}
#
{720}{}{Shady Sands}
{721}{}{Cure Jarvis of Radscorpion Poison.}
{722}{}{Make Poison Antidote.}
{723}{}{Rescue Tandi from the Raiders.}
{724}{}{Stop the Radscorpions.}
#
{730}{}{Junktown}
{731}{}{Help Saul.}
{732}{}{Kill Killian.}
{733}{}{Rescue Sinthia.}
{734}{}{Save Trish.}
{735}{}{Stop Gizmo.}
{736}{}{Bust the Skulz gang.}
#
{740}{}{Raiders}
#
{750}{}{Necropolis}
{751}{}{Destroy the Super Mutants at the Watershed.}
{752}{}{Fix the Necropolis water pump.}
#
{760}{}{Hub}
{761}{}{Destroy Deathclaw.}
{762}{}{Dispose of Jain.}
{763}{}{Dispose of merchant.}
{764}{}{Find the missing caravans.}
{765}{}{Steal necklace from the Merchants.}
#
{770}{}{Brotherhood}
{771}{}{Become an Initiate.}
{772}{}{Rescue Initiate from the Hub.}
#
{780}{}{Military Base}
#
{790}{}{Glow}
{791}{}{Disarm Traps for the Facility.}
{792}{}{Turn on power for the Glow.}
#
{800}{}{Boneyard}
{801}{}{Become a Blade.}
{802}{}{Deliver Locket for Romero.}
{803}{}{Deliver package from the Gun Runners.}
{804}{}{Find Children spy in the Followers.}
{805}{}{Fix hydroponic farms in Adytum.}
{806}{}{Rescue Jason Zimmerman.}
{807}{}{Stop the Gangs from attacking Adytum.}
#
{810}{}{Cathedral}


#
# Holodisk text
#

# GVAR_NCR_FAKE_VAULT13_HOLODISK
#
{1000}{}{第１３号避难所磁片}
{1001}{}{**END-PAR**}
{1002}{}{这张磁片纪录着第１３号避难所的地点，}
{1003}{}{其所在地已经标示在你的地图上了。}
{1004}{}{**END-DISK**}
# *** ***
# GVAR_HOLODISK_MB_OUTSIDE
{2000}{}{给：CHQ}
{2001}{}{我们的科学小组已经完成测试从基地所取得的样品了。}
{2002}{}{我们确定样品的纯度是９０％。我们预定样品会快就会}
{2003}{}{送达你手中。就如同我们预估的一样，工人们在接触了}
{2004}{}{高纯度的样品后都急速的变种。虽然相当多的人都死了}
{2005}{}{，但是死亡的人数却在可以接受的范围之内。我下令所}
{2006}{}{有人员马上彻出基地，等到最后一个我方人员彻出之后}
{2007}{}{，我们就会将入口炸封，将所有的工人都封在里面。}
{2008}{}{}
{2009}{}{}
{2010}{}{山德上校}
{2011}{}{**END-DISK**}

# *** ***
# GVAR_HOLODISK_MB_LEVEL_1
{3000}{}{这是皮卡队长在第一检查点报告。我们与第二、三检查}
{3001}{}{点的通讯都中断了。我们只能够作最坏的的打算。许多}
{3002}{}{的怪物都从矿坑中涌上来。所有阻止他们的方法都失败}
{3003}{}{了。我们将会尽全力在这一个据点档住他们，但是我们}
{3004}{}{将不会支持的了太久的。}
{3005}{}{}
{3006}{}{**END-DISK**}

# *** ***
# GVAR_HOLODISK_MB_LEVEL_2
{4000}{}{第三号检查点正遭受攻击。我们已经将矿坑的电梯关起}
{4001}{}{来以防万一，但是我能够听到他们正在爬上来的声音。}
{4002}{}{天啊！丑陋的怪物正在一层一层的向上爬！这一定就是}
{4003}{}{高层军官所提到的超级士兵。当我们对一只开火后，后}
{4004}{}{面马上就踊出了两只怪物，然后，原来被打中的那一只}
{4005}{}{也站起来了！它们一直向我们冲来，我们一点都挡不住}
{4006}{}{他们。天啊！我们需要更多的支－－}
{4007}{}{}
{4008}{}{**END-DISK**}

# *** ***
# GVAR_HOLODISK_MB_LEVEL_3
{5000}{}{布拉克斯中士从第三检查点报告。一切的情况就如同平}
{5001}{}{常一样毫无异样。我不知道高层的军官为什么要派重兵}
{5002}{}{来守住这一些讨厌的矿工。他们每一个人都骨瘦如柴，}
{5003}{}{而且个个都相当的虚弱。他们每一个连拿起武器的力量}
{5004}{}{都没有……喔，刚刚许多研究员拿了大量的样品过来，}
{5005}{}{他们好像对于那一些样品感到相当的兴奋。你知不知道}
{5006}{}{他们是否已经找到他们要找的东西了呢？有许我们终于}
{5007}{}{可以离开这一个阴森的地方了。等一下，又有另一批货}
{5008}{}{运上来了。天啊！它们是什么东西？它们正在快速的冲}
{5009}{}{向我们的据点！我们需要支援！我重覆，这是第三号检}
{5010}{}{查点，我们需－－}
{5011}{}{}
{5012}{}{}
{5013}{}{**END-DISK**}

# *** ***
# GVAR_HOLODISK_MB_LEVEL_4
{6000}{}{彻离的行动与原先计划的进度一样。从旧基地的地图看}
{6001}{}{来，我们应该很快就可以到达仓库地带。我们从收集的}
{6002}{}{空气以及泥土的样本中发现了ＦＥＶ病毒的含量正在增}
{6003}{}{加当中。不过，好险我们所穿的防护衣将病毒都过虑掉}
{6004}{}{了。请向英克雷军的高层报告我们很快就会有高纯度的}
{6005}{}{变种物质了。}
{6006}{}{}
{6007}{}{**END-PAR**}
#
{6008}{}{还有，我开始发现很多的矿工都开始产生了一些变化。}
{6009}{}{他们都出现了体力增强、耐力增强、以及肤色变化的征}
{6010}{}{状。很明显的他们开始受到了ＦＥＶ病毒的变种影响。}
{6011}{}{我的部下每一个人都开始担心，因为他们也发现了矿工}
{6012}{}{身体的变话。虽然说我在每一个据点都增加了守兵，但}
{6013}{}{是我担心如果所有的矿工都完全的变种了，我们将会敌}
{6014}{}{不过他们。我希望这一些工人不会完全的变种，因为他}
{6015}{}{们并没有直接的接触到变种的物质。还有，一些本地的}
{6016}{}{动物对ＦＥＶ病毒都产生了免疫的体质。不过，从来没}
{6017}{}{有人知道在这样高浓度的ＦＥＶ病毒浓度下，人会变成}
{6018}{}{什么样子。因此，我建议我们应该要在矿坑的出口装设}
{6019}{}{许多的炸药。等到我们得到了高纯度的样品之后，我们}
{6020}{}{马上可以将出口封住，防止这些矿工逃出来……}
{6021}{}{}
{6022}{}{}
{6023}{}{}
{6024}{}{}
{6025}{}{}
{6026}{}{}
{6027}{}{}
{6028}{}{}
{6029}{}{}
{6030}{}{**END-DISK**}

#
{7000}{}{山岭军事基地－研究与开发部门}
{7001}{}{驻基地医生－列克特博士}
{7002}{}{私人记录}
{7003}{}{**END-PAR**}
{7004}{}{六月 28, 2077}
{7005}{}{今天那一些生化储存部的人跟我开了一个大玩笑。其中}
{7006}{}{一个人改变了避难所科技的自动内脏取出器的程式，因}
{7007}{}{此卡罗下士的结肠被取了出来。好险他早就死了，不然}
{7008}{}{我就完了。为了要避免这以后再发生同样的事，我将那}
{7009}{}{机器设定为只会取出人脑，并且无法再接受程式更改。}
{7010}{}{我一定会想办法整回那一班人的。}
{7011}{}{}
{7012}{}{}
{7013}{}{**END-PAR**}
{7014}{}{六月 29, 2077}
{7015}{}{我今天将卡罗下士的肝脏给取出来，并且将其煮熟。我}
{7016}{}{在盘子上并且加了许多的豆子，闻起来还很香咧。我将}
{7017}{}{那道“菜”送到了生化储存部门去，他们那些人还以为}
{7018}{}{那是将军送给他们的感谢礼咧。干得好！我真爱我的工}
{7019}{}{作！}
{7020}{}{**END-PAR**}
{7021}{}{六月 30, 2077}
{7022}{}{我在一个病人身上试验了一种新的药品。结果相当的令}
{7023}{}{人振奋。那病人在接受了药物之后，变得相当的残爆，}
{7024}{}{并且逃出了他的牢房。好险新的安全机器人及时的赶到}
{7025}{}{，将他给制服了。我得要叫维修人员来将那扇被打烂的}
{7026}{}{门换掉。}
{7027}{}{}
{7028}{}{}
{7029}{}{}
{7030}{}{**END-PAR**}
{7031}{}{七月 1, 2077}
{7032}{}{我最喜爱的实验品今天死了。我从很久以前就一直喂他}
{7033}{}{曼他特以及我个人特别配方的混合式药品。他从原本的}
{7034}{}{ＩＱ３９在几个星期之内就变成了ＩＱ２００。我很伤}
{7035}{}{心，因为他是我聊天的好伙伴，以后我就没有人可以说}
{7036}{}{话了。我会相当的怀念他的。}
{7037}{}{}
{7038}{}{**END-PAR**}
{7039}{}{七月 5, 2077}
{7040}{}{我们认为新的生化脑终于完成了。我们还得要再进行一}
{7041}{}{些实验，不过我想应该是没什么问题了。}
{7042}{}{}
{7043}{}{**END-PAR**}
{7044}{}{七月 6, 2077}
{7045}{}{机械部的人很不高兴，因为他们最强大的电脑居然被改}
{7046}{}{装用来进行处理基地彻离的事。我对于这一件事也相当}
{7047}{}{的不高兴，因为天网电脑在我们设计新的生化脑时也帮}
{7048}{}{了我们不少的忙。}
{7049}{}{}
{7050}{}{**END-PAR**}
{7051}{}{七月 9, 2077}
{7052}{}{彻离一事提前了。真不是一个好时间啊。我们才要刚刚}
{7053}{}{开始安装我们新的生化脑。他们说彻离只是暂时性的，}
{7054}{}{也就是说我可以在我们回来之后继续的工作。这也许是}
{7055}{}{我这段时间之内最后的一个记录，我得要收拾整理我的}
{7056}{}{研究资料了。}
{7057}{}{}
{7058}{}{}
{7059}{}{}
{7060}{}{**END-DISK**}
#
{8000}{}{七月 5, 2077}
{8001}{}{山岭军事基地－医疗部门}
{8002}{}{驻基地医生－所罗门博士}
{8003}{}{对象－迪克森下士}
{8004}{}{意外报告 # 8332-523D}
{8005}{}{**END-PAR**}
{8006}{}{迪克森下士尝试着要安装一个地雷在储存库里面，如同}
{8007}{}{彻离计划上面的指示一般。不过，该地雷却爆炸了，将}
{8008}{}{迪克森下士以及克里夫顿将军都炸伤了。迪克森下士的}
{8009}{}{手、胸部、以及脸部都遭到了严重的裂伤。他的右手完}
{8010}{}{全的被炸断了，而且我们无法找到残肢为他进行接驳手}
{8011}{}{术。脸部以及胸部的裂伤则需要作许多次的手术才能够}
{8012}{}{修复。我在他身上取出了３２个地雷的碎片，他的右眼}
{8013}{}{我们也无法治好，因此我们将他的右眼给取出。不过，}
{8014}{}{我们希望将他的右眼放在我们正在实验中的生化软胶，}
{8015}{}{他的眼睛会自我修复。然后，我们就可以将他的眼睛动}
{8016}{}{手术接回去。这一种新的生化软胶在实验中可以刺激生}
{8017}{}{物细胞重新的自我繁殖，只不过要在这种情况下实验实}
{8018}{}{在是相当不幸的一件事。}
{8019}{}{}
{8020}{}{}
{8021}{}{}
{8022}{}{}
{8023}{}{}
{8024}{}{}
{8025}{}{}
{8026}{}{}
{8027}{}{}
{8028}{}{**END-DISK**}
#
{9000}{}{六月 9, 2077}
{9001}{}{紧集通知}
{9002}{}{}
{9003}{}{}
{9004}{}{敬告所有人员。山岭军事基地的彻离已然提前了一个星}
{9005}{}{期。所有的安全以及防御设备一定要在彻离前完成。所}
{9006}{}{有的人员请与你的队长联络，取得新的工作命令。在这}
{9007}{}{一段期间之内，所有的安全条例都会被严格的执行；身}
{9008}{}{份卡随时都得要带在身上。}
{9009}{}{}
{9010}{}{}
{9011}{}{}
{9012}{}{}
{9013}{}{克里夫顿将军}
{9014}{}{**END-DISK**}

# Sierra Base Mission Statement
{10000}{}{山岭军事基地}
{10001}{}{任务纲要 1942 - 1991}
{10002}{}{储存并且维持一定数量的军用物品。在邻近基地遭到侵}
{10003}{}{略并且需要物资支援时，才能够很快的调动物品。}
{10004}{}{}
{10005}{}{}
{10006}{}{**END-PAR**}
{10007}{}{山岭军事基地}
{10008}{}{任务纲要 1992 - 2050}
{10009}{}{这一个任务是要将储从中多出来而再也不会用到的军用}
{10010}{}{品消毁。我们将与ＩＯＣ以及ＥＰＡ两个组织共同的研}
{10011}{}{究能够如何环保的将这一些物品销毁。}
{10012}{}{}
{10013}{}{}
{10014}{}{}
{10015}{}{**END-PAR**}
{10016}{}{山岭军事基地}
{10017}{}{任务纲要 2050 - 2076}
{10018}{}{最高机密}
{10019}{}{需要第五级的安全等级才能观看}
{10020}{}{这一个基地将会备有最先进的科技，而基地本身将会被}
{10021}{}{用来进行机器、生化、以及武器等方面的秘密研究。}
{10022}{}{}
{10023}{}{}
{10024}{}{**END-PAR**}
{10025}{}{山岭军事基地}
{10026}{}{任务纲要 2077}
{10027}{}{由于人员的短缺，山岭军事基地将会被改装成一个拥有}
{10028}{}{自动防御系统的基地。因此，所有的人员将会被重新分}
{10029}{}{配到邻近的基地，或是前线。}
{10030}{}{}
{10031}{}{**END-DISK**}

# Sierra Base GNN Transscript
{11000}{}{银河新闻网}
{11001}{}{拨放记录：一月 11, 2073}
{11002}{}{今天的头条。在众多方面的合作之下，今天美国成功的}
{11003}{}{钻得了全世界最后的石油。直到最近，许多人都认为这}
{11004}{}{一些存在太平洋底部的油是无法取得的，因为它们都位}
{11005}{}{在地底下几千尺的地壳中。由于世界存油都快要用光了}
{11006}{}{，许多国家都开始争先恐后想要取得太平洋的存油。我}
{11007}{}{们很高兴的为你报导，美国是第一个钻得的国家，因此}
{11008}{}{这一些油都是美国的财产了。做得好，美国！}
{11009}{}{}
{11010}{}{}
{11011}{}{}
{11012}{}{}
{11013}{}{}
{11014}{}{**END-PAR**}
{11015}{}{当然，中国对于美国成功采得石油的消息作出了极强烈}
{11016}{}{的反应。据中国政府表示，他们的钻油台原本可以在好}
{11017}{}{几个月前就钻到石油，但是，中国的钻油台上面发生了}
{11018}{}{一系列的事故，以致进度被美国超过。中国领导人更加}
{11019}{}{的表示他们拥有证据证明美国政府就是一系列事故的幕}
{11020}{}{后破坏者。因此，他要求组成一个国际委员会来调查这}
{11021}{}{一个事件。}
{11022}{}{}
{11023}{}{}
{11024}{}{}
{11025}{}{**END-PAR**}
{11026}{}{另外一则消息，全国到处都传有暴乱发生，因为油价已}
{11027}{}{经高涨到了前所未见的高价。现在，汽油的价钱已经远}
{11028}{}{超过了金条的价值了。}
{11029}{}{}
{11030}{}{**END-PAR**}
{11031}{}{现在报告天气，冬天的温度已经袭来了，现在每天的平}
{11032}{}{均温度约为华氏38到41度，每天最低温度已经达到了寒}
{11033}{}{冷的30度。请出外多穿衣服！}
{11034}{}{**END-PAR**}
{11035}{}{银河新闻网}
{11036}{}{拨放记录：六月 24, 2074}
{11037}{}{与世界领袖的石油谈判今天产生了一个惊人的局面。美}
{11038}{}{国总统在许久的争吵之后离开了会议中心。他最后表示}
{11039}{}{全球最后的石油是美国的财产，只有美国能用。他也不}
{11040}{}{会将油卖给任何的国家。这一种情形就连联合国也没有}
{11041}{}{办法调解。}
{11042}{}{}
{11043}{}{}
{11044}{}{}
{11045}{}{**END-PAR**}
{11046}{}{全球的工业都因石油危机而停摆了，不过，美国的工业}
{11047}{}{却不受影响。就算联合国设立了经济制裁，美国的出口}
{11048}{}{量还是增加了２０倍。美国现在的经济成长是自从雷根}
{11049}{}{以来成长最高的一次。}
{11050}{}{}
{11051}{}{}
{11052}{}{**END-PAR**}
{11053}{}{银河新闻网}
{11054}{}{拨放记录：二月 14, 2075}
{11055}{}{今天是历史性的一刻，因为加拿大人民投票决定要成为}
{11056}{}{美国的一部份。美国总统表示：“加拿大拥有世界上最}
{11057}{}{好的冰上曲棍球球员，因此欢迎他们加入美国。”当然}
{11058}{}{加拿大会得到由美国控制的１０％的世界最后存油，也}
{11059}{}{可以享有５０％的免税率。}
{11060}{}{}
{11061}{}{}
{11062}{}{}
{11063}{}{}
{11064}{}{**END-PAR**}
{11065}{}{运动消息，小岩城圣者队以及艾那韩飞机队今天举行了}
{11066}{}{第两百一十届超级杯美式足球赛。这场赛事可以说是一}
{11067}{}{场拉距战，不过最后Montana IV从五码线一直跑到了底}
{11068}{}{线得分，最后比数是９５－９０，由艾那韩取得胜利。}
{11069}{}{}
{11070}{}{}
{11071}{}{}
{11072}{}{**END-PAR**}
{11073}{}{银河新闻网}
{11074}{}{拨放记录：二月 15, 2075}
{11075}{}{今天下议会以及上议会团结一致的投票将总统罢免，因}
{11076}{}{他过马路不走斑马线。两个议会都表示总统不应该知法}
{11077}{}{犯法，穿越马路。不过，两个议会都表示总统的罢免与}
{11078}{}{最近让加拿大加入美国一事没有关连。}
{11079}{}{}
{11080}{}{}
{11081}{}{**END-PAR**}
{11082}{}{银河新闻网}
{11083}{}{拨放记录：三月 30, 2076}
{11084}{}{今天总统下令将大量的海上舰队派到太平洋保护美国秘}
{11085}{}{密的钻油台。总统表示，最近中国军队开始在相当靠近}
{11086}{}{石油区的地带进行军事演习。不过，中国政府表示他们}
{11087}{}{的演习并没有任何的恶意。}
{11088}{}{}
{11089}{}{}
{11090}{}{**END-PAR**}
{11091}{}{在一个民调表示，５４％的宇宙新闻网的观众认为总统}
{11092}{}{最近下令派兵到太平洋的动作只不过是一个分散民众注}
{11093}{}{意力的技俩。让民众不要再将注意力放在总统最近承认}
{11094}{}{拥有许多婚外情的事实。不过，我们的民调也表示高达}
{11095}{}{７０％的民众对于婚外情觉得没有关系，并且对总统目}
{11096}{}{前治理国家的方式感到满意。高达６０％的民众也认为}
{11097}{}{总统应该要继续的进行婚外情，只要国家治理的好就好}
{11098}{}{了。}
{11099}{}{}
{11100}{}{**END-PAR**}
{11101}{}{银河新闻网}
{11102}{}{拨放记录：十月 10 2077}
{11103}{}{战争！中国侵入了美国的阿拉斯加。虽然美国在联合国}
{11104}{}{上强烈抗议，但联合国却对于这一件事视而不见。美国}
{11105}{}{总统现在要每一个国民都出力保护这一个国家。现在就}
{11106}{}{到你本地的征兵处报到吧！}
{11107}{}{}
{11108}{}{}
{11109}{}{}
{11110}{}{}
{11111}{}{}
{11112}{}{**END-PAR**}
{11113}{}{银河新闻网}
{11114}{}{拨放记录：十月 22, 2077}
{11115}{}{谢谢勇敢的士兵们，也感谢新发明的超级战斗装甲，美}
{11116}{}{国军队已经将中国入侵者打败了。由于中国军队没有足}
{11117}{}{够的燃料，因此他们已经全部的被我们赶回北京了。}
{11118}{}{}
{11119}{}{}
{11120}{}{**END-DISK**}


# Elron Bible
{12000}{}{欢迎！}
{12001}{}{欢迎进入哈伯教磁片！在这一些电子画面内，你将会了}
{12002}{}{解本帮的信条以及我们以前遭到压制的信仰。这一张磁}
{12003}{}{片并不代表着本教全部的信仰，而只是大略的介绍而已}
{12004}{}{。让我们成为你精神上的守护者吧。}
{12005}{}{}
{12006}{}{}
{12007}{}{**END-PAR**}
{12008}{}{主画面}
{12009}{}{历史}
{12010}{}{信仰}
{12011}{}{字汇解释}
{12012}{}{参考文献}
{12013}{}{**END-PAR**}
{12014}{}{历史}
{12015}{}{我们是由一位相当有未来眼光的先锋者所建立，他们名}
{12016}{}{字是狄克．哈伯。在当时，他眼见医疗技术的失败、宗}
{12017}{}{教所产生的问题，以及政府们的无能，他深深的了解到}
{12018}{}{人民所需要的是一个新的领导……世界需要哈伯教。受}
{12019}{}{到了当时音乐的影响，以及与外星人的接触，他带着我}
{12020}{}{们，领导着我们，前往一个前所未见的新世界。}
{12021}{}{}
{12022}{}{}
{12023}{}{}
{12024}{}{**END-PAR**}
{12025}{}{我们叫他“哈伯”，经由他的领导，让我们了解到我们}
{12026}{}{在宇宙中所扮演的角色。就像一个轮子一样，他是我们}
{12027}{}{的轮轴，让我们能够体会他的思想，在生命中转动。}
{12028}{}{}
{12029}{}{**END-PAR**}
{12030}{}{在撰写了许多的书以及报告之后，哈伯开始向许多的人}
{12031}{}{传授他的看法－不过，马上就有许多的人开始攻击他的}
{12032}{}{主义。他们称哈伯的信仰为“伪科学”、“危险的”、}
{12033}{}{“妖言惑众的”。既使是全世界到处都有人看到外星人}
{12034}{}{的踪迹，政府以及大型的企业们居然都尽力的要掩盖这}
{12035}{}{一个事实。哈伯知道，这一些人都是迷失的子民。}
{12036}{}{}
{12037}{}{}
{12038}{}{}
{12039}{}{}
{12040}{}{}
{12041}{}{**END-PAR**}
{12042}{}{因为各界的打压，往后的许多年，哈伯教变成了一个地}
{12043}{}{下组织。不过，哈伯教徒并不是待宰的羔羊，为了实现}
{12044}{}{理想，许多的信徒都深入了那一些想要将哈伯教毁灭的}
{12045}{}{组织。并且制作了许多的“电视节目”，透过它向人民}
{12046}{}{揭穿政府的阴谋。}
{12047}{}{}
{12048}{}{}
{12049}{}{}
{12050}{}{**END-PAR**}
{12051}{}{不过，许多的人仍然不相信哈伯的远见。甚至，还有人}
{12052}{}{认为哈伯教徒都是一些疯子。就在这个时候，我们伟大}
{12053}{}{的领袖去世了。}
{12054}{}{}
{12055}{}{}
{12056}{}{**END-PAR**}
{12057}{}{所有的信徒都知道依照哈伯的说法，我们将可以与宇宙}
{12058}{}{间的力量连线，因此，这一股力量将所有的信徒团结起}
{12059}{}{来，不致分散瓦解。许多的信徒都相信，在这一个宇宙}
{12060}{}{中有一个比这一个世界更好的居住地方。我们有着宇宙}
{12061}{}{中还有其他生物的证据，并且懂得宇宙的真缔。所有的}
{12062}{}{人都是因为仰慕我们的知识而来。}
{12063}{}{}
{12064}{}{}
{12065}{}{}
{12066}{}{}
{12067}{}{}
{12068}{}{}
{12069}{}{}
{12070}{}{}
{12071}{}{**END-PAR**}
{12072}{}{信仰}
{12073}{}{哈伯教的信仰相当的简单，是所有宗教以及哲学的结晶}
{12074}{}{。我们相信生命、宇宙、以及所有的都东西都可以用一}
{12075}{}{个轮子来解释。轮子的外圈，代表是那一些对真像没有}
{12076}{}{认知的人们。我们称他们为“轮底”，也就是当轮子转}
{12077}{}{动的时候被压在下面的东西。他们不但不是轮子的一部}
{12078}{}{份，对于轮子本身也没有认知。}
{12079}{}{}
{12080}{}{}
{12081}{}{}
{12082}{}{**END-PAR**}
{12083}{}{那一些信仰哈伯教的人们就如同轮子的一部份一样。不}
{12084}{}{但懂得轮子因何会转动，而且会尽全力的让轮子不断地}
{12085}{}{转动。那一些控制轮子的就叫作“哈伯人”，一群受到}
{12086}{}{启示的人，为了人类的福祉而卖命。}
{12087}{}{}
{12088}{}{}
{12089}{}{}
{12090}{}{}
{12091}{}{**END-PAR**}
{12092}{}{我们运用由哈伯所发明的科学技术让我们能够自我净化}
{12093}{}{、自我检讨。只有能够自我检讨，我们才能够不断的进}
{12094}{}{步、才能够了解我们在宇宙中的地位。}
{12095}{}{}
{12096}{}{}
{12097}{}{}
{12098}{}{}
{12099}{}{}
{12100}{}{}
{12101}{}{}
{12102}{}{}
{12103}{}{**END-PAR**}
{12104}{}{我们自认为我们的教派是一个结合科学以及精神的结晶}
{12105}{}{……我们希望你也能够加入我们，成为我们的一员。}
{12106}{}{}
{12107}{}{}
{12108}{}{**END-PAR**}
{12109}{}{这是我们的创造论：}
{12110}{}{许久以前，人与人之间都和平共处。所有生物的身体、}
{12111}{}{思想、以及灵魂都是合为一体的。当时科技的进步，完}
{12112}{}{全只是因为人类的想像力而已。那是一个和平、创造的}
{12113}{}{时代。接着，黑暗时代来临了。战争的爆发，将生物的}
{12114}{}{灵魂以及躯体都毁灭了，散播到宇宙之间。我们的巨轮}
{12115}{}{险些便要脱离轮轴，永远的迷失了。}
{12116}{}{}
{12117}{}{}
{12118}{}{}
{12119}{}{}
{12120}{}{}
{12121}{}{**END-PAR**}
{12122}{}{就在这时候，救星到了。万能的哈伯将我们团结起来。}
{12123}{}{教了我们许多的知识，让我们对于自已以及宇宙有着更}
{12124}{}{多的认知。}
{12125}{}{}
{12126}{}{}
{12127}{}{}
{12128}{}{}
{12129}{}{}
{12130}{}{}
{12131}{}{}
{12132}{}{}
{12133}{}{}
{12134}{}{**END-PAR**}
{12135}{}{字词解释}
{12136}{}{哈伯寻找者：一个人被启示的程度与他灵魂的清净程度}
{12137}{}{有着很大的关系。将身体内负面的能源转成正面的能源}
{12138}{}{才能够达成足够的力量，前往乐土。}
{12139}{}{}
{12140}{}{}
{12141}{}{}
{12142}{}{}
{12143}{}{**END-PAR**}
{12144}{}{调整：当你的灵魂遭到负面能源的影响，我们就会对你}
{12145}{}{的灵魂进行调整，清除掉遭到污染的能源。不过，进行}
{12146}{}{过多的调整对于灵魂是有害的。}
{12147}{}{}
{12148}{}{}
{12149}{}{**END-PAR**}
{12150}{}{启示：启示是少数的人可以达成的境界，当他们达到启}
{12151}{}{示的境界时，就等于是宇宙的一部份，而不再受到肉体}
{12152}{}{的影响。不过，少数得到启示的人仍然选择留在地球上}
{12153}{}{，带领其他的人达到相同的境界。}
{12154}{}{}
{12155}{}{}
{12156}{}{}
{12157}{}{**END-PAR**}
{12158}{}{巨轮：这代表的是宇宙、空间、以及时间的结合。所有}
{12159}{}{的东西都是巨轮的一部份。极少部份的人拥有能够控制}
{12160}{}{巨轮的能力，我们称他们为“神”。}
{12161}{}{}
{12162}{}{}
{12163}{}{}
{12164}{}{}
{12165}{}{**END-PAR**}
{12166}{}{灵魂：也就是生命的起源，相当的容易受到负面能源的}
{12167}{}{影响。}
{12168}{}{}
{12169}{}{}
{12170}{}{**END-PAR**}
{12171}{}{压迫：一些人的灵魂受到了大量负面能源的影响，变得}
{12172}{}{邪恶。他们压迫那一些想要取得启示境界的人。这一些}
{12173}{}{人不懂得巨轮的意义，并且想尽办法，想要毁坏这一个}
{12174}{}{巨轮的运作。}
{12175}{}{}
{12176}{}{}
{12177}{}{}
{12178}{}{**END-PAR**}
{12179}{}{乐土：也就是星父在我们净化自己之后，将会领导我们}
{12180}{}{所去的地方。}
{12181}{}{}
{12182}{}{}
{12183}{}{**END-PAR**}
{12184}{}{轮底：一个普通人，对于灵魂的净化仍未明白。}
{12185}{}{}
{12186}{}{**END-PAR**}
{12187}{}{星父：也有人叫他们“神”。我们宁可叫他为星父。}
{12188}{}{}
{12189}{}{}
{12190}{}{}
{12191}{}{**END-PAR**}
{12192}{}{升天：当我们达到了净化的程度，或者是了解了宇宙的}
{12193}{}{意义时，星父就会将我们带领到乐土中，与宇宙其}
{12194}{}{他的生物一结合。}
{12195}{}{}
{12196}{}{}
{12197}{}{}
{12198}{}{}
{12199}{}{**END-PAR**}
{12200}{}{Zeta扫瞄：也就是“调整”，Zeta扫瞄可以将你的灵魂}
{12201}{}{净化。它是一台机器，将大量经过精心调整的电力通过}
{12202}{}{你的身体，达到除去负面能源的目的。}
{12203}{}{}
{12204}{}{}
{12205}{}{}
{12206}{}{}
{12207}{}{}
{12208}{}{}
{12209}{}{**END-PAR**}
{12210}{}{参考文献}
{12211}{}{哈伯之书}
{12212}{}{(这里有太多的书了，要一一念出要花太多时间了。)}
{12213}{}{}
{12214}{}{}
{12215}{}{}
{12216}{}{}
{12217}{}{}
{12218}{}{**END-DISK**}

{13000}{}{地下掩体市设计记录}
{13001}{}{**END-PAR**}
{13002}{}{地下掩体市的建造经过许多不同的阶段。它原是由李奥}
{13003}{}{那多．布亚斯基、杰森．安德森、费拉格斯．勿拉哈特}
{13004}{}{、以及克理斯．阿法隆所设计。史古托．依法特设计了}
{13005}{}{地图，并且进行了结构上的设计。法蓝克斯坦、罗伯．}
{13006}{}{哈特思坦三代以及丹．史比特利，还有艾力克．普利普}
{13007}{}{西几乎将他们的命都卖了，来测试这一个大型的城市。}
{13008}{}{}
{13009}{}{**END-PAR**}
{13010}{}{Chris要感谢以下的人对于“异尘余生２”设计的}
{13011}{}{帮忙：Rob, Scotty, Dan, Eileen, Sarah, Emily, }
{13012}{}{Chris Wright。}
{13013}{}{}
{13014}{}{}
{13015}{}{**END-PAR**}
{13016}{}{Scotty想要感谢：Aileen Evert以及Avis Andre。}
{13017}{}{并且感谢Bill Bridges带来所有酷的Fading Suns书。}
{13018}{}{}
{13019}{}{**END-PAR**}
{13020}{}{Dan想要感谢：Aplit Enz, James Cameron, }
{13021}{}{Joe Viskocil, Chong, Carlos Kotkin, Jon Land, }
{13022}{}{Red Dwarf, 还有父母。}
{13023}{}{Rob Hertenstein想要感谢：Becky Warner,}
{13024}{}{Billie Ryder,Little Ryder, 以及Nicole Roman。}
{13025}{}{}
{13026}{}{Eric Pribish想要感谢：Tommy Hood, Jr.,}
{13027}{}{ Joe Isip, 以及Julio Mata, Brade and }
{13028}{}{Dave Carnes。最后，我想要感谢我的女朋友}
{13029}{}{Ronda Lauffer忍受我因为设计游戏而不回家。}
{13030}{}{}
{13031}{}{**END-PAR**}
{13032}{}{感谢英特卫国际有限公司的“傻瓜精神”，让异尘余生}
{13033}{}{２中文版可在Ｉｎｔｅｒｐｌａｙ不看好改版能力的情}
{13034}{}{况下终于在１９９９年顺利和大家见面。中文版改版翻}
{13035}{}{译庄振宇；特别感谢为了抓翻译错字与调整系统而连续}
{13036}{}{多日熬夜工作的程式工程师邱创义与测试工程师张俊程}
{13037}{}{（凯文）。}
{13038}{}{**END-PAR**}
{13039}{}{Fallout 2 Chinese charactor verson creator from}
{13040}{}{Interwise CO., Ltd. soft charactor translator: }
{13041}{}{Allen Cheng-Yu Chuang. Localization Programer}
{13042}{}{and Debuger: Lawrence Chiu. Chinese charactor }
{13043}{}{debug, recheck, and game tester: Kevin Chang. }
{13044}{}{}
{13045}{}{We try to do best! }
{13046}{}{ ....... Interwise CO., LTD. }
{13047}{}{}
{13048}{}{**END-PAR**}
{13049}{}{为了奖赏你打倒英克雷军。Chris, Scotty, Rob, Dan,}
{13050}{}{以及Eric想要告诉你：在这一个舞台的左上角有一部电}
{13051}{}{脑终端机，去用用看吧，会有意想不到的东西喔。}
{13052}{}{}
{13053}{}{**END-PAR**}
{13054}{}{恭喜你拯救了世界，并且更感谢你购买“异尘余生二代}
{13055}{}{中文版”这套游戏。}
{13056}{}{}
{13057}{}{**END-DISK**}

{14000}{}{地下掩体市北加州旅行记录}
{14001}{}{**END-PAR**}
{14002}{}{警告：如果地下掩体市公民一定要离开地下掩体市的话}
{14003}{}{，一定要携带下面几样东西：}
{14004}{}{}
{14005}{}{一、一份包装好了的地下掩体市所发的粮食包。别食用}
{14006}{}{　　外来食物，不然你可能会受到细菌或是辐射的感}
{14007}{}{    染。}
{14008}{}{二、一个盖氏探测器。无论你到那里都得要注意周围放}
{14009}{}{　　射线的含量。}
{14010}{}{}
{14011}{}{三、至少两个治伤注射针。一点小伤都可能会让细菌进}
{14012}{}{　　入你的体内。}
{14013}{}{}
{14014}{}{}
{14015}{}{}
{14016}{}{}
{14017}{}{**END-PAR**}
{14018}{}{瑞丁城：位于地下掩体市西边的一个小采矿城。瑞丁城}
{14019}{}{以金矿与地下掩体市交换医疗用品。所有的地下掩体市}
{14020}{}{公民到达瑞丁城时要格外小心，因为当地的矿工并没有}
{14021}{}{受到很严格的纪律管制。}
{14022}{}{}
{14023}{}{人口：没有准确的数字，但是很多人相信瑞丁城有着上}
{14024}{}{百人的居民。}
{14025}{}{}
{14026}{}{政府：城主以及镇民议会。}
{14027}{}{}
{14028}{}{辐射含量：没有准确数字。}
{14029}{}{}
{14030}{}{变种率：不知道，不过相信很低。}
{14031}{}{**END-PAR**}
{14032}{}{新里诺：地下掩体市西南方的城市。用金矿与地下掩体}
{14033}{}{市交换医疗用品。里诺在战争时遭到很少的破坏（当然}
{14034}{}{当地帮派的破坏还是有的），因此很多的街道及建筑都}
{14035}{}{还是完好的。警告！在该处没有政府，也没有警察。赌}
{14036}{}{博、娼妓、以及毒品到处都是。地下掩体市公民应该要}
{14037}{}{尽全力的不要前往新里诺！}
{14038}{}{}
{14039}{}{人口：没有准确数字，但是相信有数千人。}
{14040}{}{}
{14041}{}{政府：新里诺正处于混乱状态。从报告看来，当地有许}
{14042}{}{多的“犯罪家族”控制着各自的地盘。}
{14043}{}{}
{14044}{}{辐射含量：没有准确数字。}
{14045}{}{}
{14046}{}{变种率：不知道，不过相信很低。}
{14047}{}{}
{14048}{}{}
{14049}{}{}
{14050}{}{**END-PAR**}
{14051}{}{新加州共和国：它的领土位于地下掩体市很远的南方。}
{14052}{}{他们以机械仪器、金、以及许多过剩的产品与地下掩体}
{14053}{}{市交换医疗科技。最近新加州共和国开始想要地下掩体}
{14054}{}{市成为他们一部份，因此公民前往新加州共和国时要格}
{14055}{}{外小心。}
{14056}{}{人口：虽然有人口调查，但是我们无法取得这一些资料}
{14057}{}{。我们相信新加州共和国有数万的人口。}
{14058}{}{}
{14059}{}{政府：总统以及一个议会。}
{14060}{}{}
{14061}{}{辐射含量：没有准确数字。}
{14062}{}{}
{14063}{}{变种率：每一个地带都不一样。}
{14064}{}{}
{14065}{}{}
{14066}{}{**END-PAR**}
{14067}{}{破碎丘：位于地下掩体市南方，采集铀矿的采矿城。他}
{14068}{}{们用铀矿与地下掩体市交换医疗用品，大部分都是防放}
{14069}{}{射线的药品。很多人相信当地的人类还有变种人以及疆}
{14070}{}{尸都被迫住在同一个小镇中。由于当地的居民成份，地}
{14071}{}{下掩体市公民应该尽量不要前往当地。}
{14072}{}{}
{14073}{}{人口：没有准确数字，不过相信有数百人。}
{14074}{}{}
{14075}{}{政府：有人传言当地的首领是一个变种人。不过这不太}
{14076}{}{可能，因为变种人无法进行高度的思考。不过，这若是}
{14077}{}{真的话，这就是另一个不要前往当地的理由。}
{14078}{}{}
{14079}{}{辐射含量：没有准确数字，不过相信很高。}
{14080}{}{}
{14081}{}{变种率：相信很高。当地极可能有相当多的恶性变种。}
{14082}{}{}
{14083}{}{}
{14084}{}{}
{14085}{}{}
{14086}{}{}
{14087}{}{**END-PAR**}
{14088}{}{地下掩体市：这是一个没有犯罪或是其它社会问题的乐}
{14089}{}{土。从第８号避难所出来之后，这一个城市就是一个独}
{14090}{}{立的城市。地下掩体市的经济相当繁荣，完全依靠医疗}
{14091}{}{技术的外销存活。所有的公民没事最好不要离开地下掩}
{14092}{}{体市。}
{14093}{}{人口：最新调查１０３个公民。}
{14094}{}{}
{14095}{}{政府：第一公民以及议会。}
{14096}{}{}
{14097}{}{辐射含量：档案被删除，遗失以下的字串：}
{14098}{}{[-$蜥蝪-/-$地下水-污染-]}
{14099}{}{}
{14100}{}{变种率：档案被删除，遗失以下的字串：}
{14101}{}{[-$出生率 %-]}
{14102}{}{}
{14103}{}{}
{14104}{}{**END-DISK**}

{15000}{}{新加州共和国资料磁片５}
{15001}{}{**END-PAR**}
{15002}{}{这一张磁片上面看起来载有了各种有关新加州共和国的}
{15003}{}{种种资料：每月制造总额、商队行程表、安全记录、议}
{15004}{}{会记录、秘密议会报告、派驻新里诺、瑞丁城、以及地}
{15005}{}{下掩体市的外交人员报告甚至坦蒂总统数星期的行程表}
{15006}{}{。这里面没有任何有关第１３号避难所或伊甸园创造器}
{15007}{}{资料。所有报告内容都是给达里安的，并且都有署名为}
{15008}{}{“费－”。}
{15009}{}{}
{15010}{}{}
{15011}{}{**END-DISK**}

{16000}{}{新加州共和国资料磁片１}
{16001}{}{**END-PAR**}
{16002}{}{我们在这里！为何不加入我们呢？}
{16003}{}{**END-PAR**}
{16004}{}{有一个相当完美的未来就在眼前，垂手可得。那就是新}
{16005}{}{加州共和国！}
{16006}{}{**END-PAR**}
{16007}{}{那是什么呢？你想知道吗？}
{16008}{}{**END-PAR**}
{16009}{}{新加州共和国有多大？}
{16010}{}{建立于８０年前，新加州共和国现在是由莎地、洛杉矶}
{16011}{}{、麦克森、哈伯、以及达可罗所组成的。约有７０万居}
{16012}{}{民很高兴的住在新加州共和国之中。}
{16013}{}{}
{16014}{}{**END-PAR**}
{16015}{}{新加州共和国所代表的为何？}
{16016}{}{新加州共和国为西部居民带来了和平、安全、以及法治}
{16017}{}{。新加州共和国优良的警队不断的巡逻并逮捕任何的歹}
{16018}{}{徒、食人族、奴隶贩子、以及没有法治的变种人。新加州}
{16019}{}{共和国的军队更在边境保护，防止外面的人侵入。为了}
{16020}{}{能够确保人民自由以及法治，所有的人民都可以使用新}
{16021}{}{加州共和国的法庭，并可以经由选举选出他们喜欢的民}
{16022}{}{意代表。就如坦蒂总统所说的一句话：“安全的人民就}
{16023}{}{是强壮的人民。”}
{16024}{}{}
{16025}{}{}
{16026}{}{}
{16027}{}{**END-PAR**}
{16028}{}{谁是这里的统治者？}
{16029}{}{新加州共和国与你所习惯的环境不一样。在这边没有军}
{16030}{}{阀、地痞流氓、国王、或独裁者。我们的领导阶层都是}
{16031}{}{由人民所选出来的！没错，每一个地方都可以选出自己}
{16032}{}{的民意代表在议会中为他们争取权利。这一些代表将会}
{16033}{}{选出总统及副总统，并提供施政意见给总统。坦蒂总统}
{16034}{}{因为她的智慧以及先见，连任十届以来都是议会全面表}
{16035}{}{决通过所选出来的总统。}
{16036}{}{}
{16037}{}{}
{16038}{}{}
{16039}{}{}
{16040}{}{**END-PAR**}
{16041}{}{听起来很不错！我要如何加入新加州共和国呢？}
{16042}{}{所有守法的人类或是变种人都可成为新加州共和国的公}
{16043}{}{民。想成为新加州共和国的公民只要搬到新加州共和国}
{16044}{}{国内，并且提出移民申请。在公民讯训练以及手续后，}
{16045}{}{你将成为试用公民。到那时候，成为完整公民的路就不}
{16046}{}{远了。}
{16047}{}{}
{16048}{}{}
{16049}{}{**END-PAR**}
{16050}{}{当然，新加州共和国并不是来者不拒。奴役主、没有教}
{16051}{}{育的变种人、歹徒、还有其它的不良份子请勿提出申请！}
{16052}{}{}
{16053}{}{**END-PAR**}
{16054}{}{如果整个小镇都想要加入呢？}
{16055}{}{看视小镇的位置而定。新加州共和国接受村庄、小镇、}
{16056}{}{基地、城市、地区、甚至小国家提出变成新加州共和国}
{16057}{}{的申请。当申请通过后，新加州共和国将会给你的小镇}
{16058}{}{领土的地位。在警队及军队成立，并且将当地的治安的}
{16059}{}{经过整理之后，你的小镇就可以成为新加州共和国的一}
{16060}{}{部份。就是这么简单！}
{16061}{}{}
{16062}{}{}
{16063}{}{}
{16064}{}{**END-PAR**}
{16065}{}{所以，记着－我们在这里！为何不加入我们呢？}
{16066}{}{**END-PAR**}
{16067}{}{新加州国外关系委员会所制作。}
{16068}{}{**END-PAR**}
{16069}{}{编号 #A7-7893b}
{16070}{}{这一页是故意空白的。}
{16071}{}{**END-DISK**}

{17000}{}{第一公民琳娜特；}
{17001}{}{**END-PAR**}
{17002}{}{送信者将你交代送来的磁片送达了。你是对的，当然，}
{17003}{}{在磁片上的资料对下次的议会讨论大有帮助。磁片上面}
{17004}{}{的资料可以让我阻止任何想促进新加州共和国以及新里}
{17005}{}{诺联合的动作。}
{17006}{}{}
{17007}{}{**END-PAR**}
{17008}{}{如果事情如我所想的发展，我可以确定新加州共和国再}
{17009}{}{也不会对地下掩体市产生任何干扰。我是相当尊敬你们}
{17010}{}{的主权的，对于想要剥夺你们自由的人，我无法苟同。}
{17011}{}{}
{17012}{}{}
{17013}{}{}
{17014}{}{**END-PAR**}
{17015}{}{你的朋友，}
{17016}{}{罗杰．卫斯丁}
{17017}{}{**END-DISK**}

# State of the Nation
{18000}{}{通知：国家目前状况}
{18001}{}{来自：迪克．理察森总统}
{18002}{}{给：这一个伟大国家的人民们}
{18003}{}{主题：国家目前的计划}
{18004}{}{**END-PAR**}
{18005}{}{美国的人民们，我很荣幸的宣布我将会带领美国的人民}
{18006}{}{找到美洲大陆，将美国取回来。我们将是一百年来首批}
{18007}{}{不会再受到变种人威胁的人们。}
{18008}{}{}
{18009}{}{}
{18010}{}{**END-PAR**}
{18011}{}{这真是一个长期的等待，而且要达成这一个目标的准备}
{18012}{}{也相当的困难。虽然曾有一段时间我们都认为这是无法}
{18013}{}{达成的目标，但是由于许多勇敢以及不辞劳苦人们的努}
{18014}{}{力，以及我们化学部门的卡林博士的研究，我们的时代}
{18015}{}{终将来临。}
{18016}{}{}
{18017}{}{**END-PAR**}
{18018}{}{勇敢的，等等……等等……天吧！真的有人会听完这}
{18019}{}{一些东西吗？}
{18020}{}{**END-PAR**}
{18021}{}{--给自己的便条--}
{18022}{}{1)  就像这样让人民不要知道卡林博士的计划。}
{18023}{}{2)  告诉每一个人他们多么勇敢…………等等，}
{18024}{}{    等等……}
{18025}{}{**END-PAR**}
{18026}{}{不要忘记提一下竞选连任的事。}
{18027}{}{**END-PAR**}
{18028}{}{记得千万不要在下演讲台的时候抱我的实习生。}
{18029}{}{}
{18030}{}{**END-PAR**}
{18031}{}{重要：赶快将这写完。我们很快就可以将那一些可恶的}
{18032}{}{变种人杀光……如果卡林的报告是正确无误的话。}
{18033}{}{}
{18034}{}{**END-DISK**}

# Word List
{19000}{}{便条：字表}
{19001}{}{来自：副总统丹尼尔．伯德}
{19002}{}{给：我}
{19003}{}{主题：我的字表}
{19004}{}{**END-PAR**}
{19005}{}{困难的字：}
{19006}{}{--------------------}
{19007}{}{Potato}
{19008}{}{Tomato}
{19009}{}{Psycho}
{19010}{}{California}
{19011}{}{To be prepared}
{19012}{}{Verbosity}
{19013}{}{Inarticulate}
{19014}{}{Subtle}
{19015}{}{**END-PAR**}
{19016}{}{得要更换的字：}
{19017}{}{----------------------}
{19018}{}{Potatoe}
{19019}{}{Tomatoe}
{19020}{}{Sycho}
{19021}{}{Kalifornia}
{19022}{}{To be prepared}
{19023}{}{Suttell}
{19024}{}{Jackelope-将这变成国家标志（这是种美国的动物吗）}
{19025}{}{}
{19026}{}{**END-DISK**}

# The Project
{20000}{}{便条：计划}
{20001}{}{来自：查尔斯．卡林博士，美国化学部}
{20002}{}{给：参谋团}
{20003}{}{主题：计划马上就可以达到完整行动状况。}
{20004}{}{**END-PAR**}
{20005}{}{我很荣幸以及高兴的报告，我们的计划已经快要完成了}
{20006}{}{。经多年的研究之后，我们成功的粹取出了ＦＥＶ病毒}
{20007}{}{毒性最强的部份。我们最近从大陆荒废的军事基地中找}
{20008}{}{到的资料已经都被解码了，那一些资料对于我们的研究}
{20009}{}{有着相当的帮助。}
{20010}{}{}
{20011}{}{**END-PAR**}
{20012}{}{我们发现ＦＥＶ病毒一开始并不是设计用来制造超级士}
{20013}{}{兵的东西。ＦＥＶ病毒原本是设计用来当作生化武器的}
{20014}{}{。后来ＦＥＶ病毒才被用来制造超级士兵。}
{20015}{}{}
{20016}{}{}
{20017}{}{**END-PAR**}
{20018}{}{在许久的研究以及旧有的资料相互结合之下，我们将原}
{20019}{}{ＦＥＶ病毒改变成更加具有毒性的版本，名为ＦＥＶ卡}
{20020}{}{林１３。}
{20021}{}{}
{20022}{}{}
{20023}{}{**END-PAR**}
{20024}{}{最后运用阿罗由村民所进行的人体使用显示受到ＦＥＶ}
{20025}{}{感染的存活率是０％。在遭到.0001%的空气感染之后，}
{20026}{}{通常在一个小时之内都会致命。不过，从第１３号避难}
{20027}{}{所抓来的人则会在死亡之前产生皮肤腐烂等症状，并且}
{20028}{}{要１４的小时之后才会致命。}
{20029}{}{}
{20030}{}{}
{20031}{}{}
{20032}{}{**END-PAR**}
{20033}{}{无论如何，ＦＥＶ病毒的毒性已经可将所有非英克雷军}
{20034}{}{的人全部都杀掉了。目前的毒性可以将９５％的人全部}
{20035}{}{清除，但是，上级建议等到毒性达到可以清除９９％的}
{20036}{}{清除率时，再执行清除行动。}
{20037}{}{}
{20038}{}{}
{20039}{}{}
{20040}{}{}
{20041}{}{}
{20042}{}{}
{20043}{}{**END-PAR**}
{20044}{}{目前的ＦＥＶ卡林１３制造速度显示我们在六个星期之}
{20045}{}{内就可以生产到计划所需的量，也就是２５００００加}
{20046}{}{仑。}
{20047}{}{**END-PAR**}
{20048}{}{恭喜，先生与小姐们，我们许多年的努力终于要结束了}
{20049}{}{}
{20050}{}{神佑美国。}
{20051}{}{**END-DISK**}

# Power Plant Operations
{21000}{}{便条：原子能员协会状况简介}
{21001}{}{来自：汤姆．莫雷，会长，原子能源协会}
{21002}{}{给：参谋团}
{21003}{}{主题：所有的反应炉控制过份依赖中央电脑}
{21004}{}{}
{21005}{}{**END-PAR**}
{21006}{}{给参谋团：我也不喜欢老是提起这档子事，不过我还是}
{21007}{}{要重申反应炉的控制应该要尽快的分摊给其它的电脑系}
{21008}{}{统来操作。以下是我的官方报告，当你看完之后，你就}
{21009}{}{会了解为什么我们需要一个备份的系统。}
{21010}{}{}
{21011}{}{}
{21012}{}{－－汤姆}
{21013}{}{**END-PAR**}
{21014}{}{原子能源反应炉控制器}
{21015}{}{------------------------------------------}
{21016}{}{避难所科技公司的新型铀反应炉一直到目前都以最高效}
{21017}{}{率运作。由于精密的电脑系统操作着反应炉的冷却系统}
{21018}{}{，因此我们不需要大量的人就可以让发电机以最大的功}
{21019}{}{率运作。}
{21020}{}{}
{21021}{}{}
{21022}{}{**END-PAR**}
{21023}{}{新的电脑系统可以同时的操作冷确系统以及中子与铀撞}
{21024}{}{击反应等等。当电脑系统离线的时候，反应炉将会马上}
{21025}{}{的失去平衡，并且造成一个连锁反应，产生一个等于十}
{21026}{}{万吨的核爆。}
{21027}{}{}
{21028}{}{}
{21029}{}{}
{21030}{}{}
{21031}{}{}
{21032}{}{}
{21033}{}{}
{21034}{}{**END-PAR**}
{21035}{}{反应炉的一部份是位在水底，这样一来，海水就可以作}
{21036}{}{为冷却的冷媒。然后，在５００公尺底下的海水会被抽}
{21037}{}{到反应炉里面，并且被核心快速加热，变成蒸气，并且}
{21038}{}{推动发电机。放射性水将会在清洁后再次使用。}
{21039}{}{}
{21040}{}{}
{21041}{}{}
{21042}{}{}
{21043}{}{}
{21044}{}{}
{21045}{}{}
{21046}{}{}
{21047}{}{}
{21048}{}{}
{21049}{}{**END-PAR**}
{21050}{}{受到大量放射污染的重水以及其它的放射废料将会经由}
{21051}{}{一个废料管通到南加州以及墨西哥的海中，造成了重大}
{21052}{}{的污染。许多的海岸都有着相当高浓度的污染辐射，}
{21053}{}{并且造成了许多生物的突变。很幸运的，这并不是我们}
{21054}{}{的问题。}
{21055}{}{}
{21056}{}{}
{21057}{}{}
{21058}{}{**END-PAR**}
{21059}{}{当基地的发电机坏掉时，我们的基地还有备用的电源能}
{21060}{}{够使用。不过，这一些电源并不能提供使用高电源的设}
{21061}{}{备，例如力场发射器。还有，当电源减少的时候，所有}
{21062}{}{在基地中到处的防水门都会关起来，防止海水流进基地}
{21063}{}{，这样也会限制基地内人员的行动。不过，所有的人员}
{21064}{}{还是能够移动到基地的最上层的。}
{21065}{}{}
{21066}{}{}
{21067}{}{}
{21068}{}{}
{21069}{}{**END-PAR**}
{21070}{}{真正的问题是，如果电脑离线了，或是被摧毁了，无论}
{21071}{}{这两个情况多么的不可能会发生，都会在两个小时之内}
{21072}{}{造成反应炉爆炸。因此，我们必须要安装一些由人员操}
{21073}{}{作的手动系统，不要完全依靠电脑系统。我知道你们一}
{21074}{}{向觉得我过度小心，但是防患未然总是好的。}
{21075}{}{}
{21076}{}{}
{21077}{}{}
{21078}{}{**END-PAR**}
{21079}{}{在还未有备份系统之前，我们应该要小心不要将主电脑}
{21080}{}{给弄坏了（哈哈哈）。}
{21081}{}{**END-PAR**}
{21082}{}{汤姆．莫雷}
{21083}{}{**END-DISK**}
