#
#   Messages from skill.c
#
#
#   SKILL NAMES
#
{100}{}{小型枪械}
{101}{}{大型枪械}
{102}{}{能量武器}
{103}{}{肉搏}
{104}{}{近战武器}
{105}{}{抛掷力}
{106}{}{急救}
{107}{}{医疗}
{108}{}{潜行}
{109}{}{开锁}
{110}{}{偷窃}
{111}{}{陷阱}
{112}{}{科技}
{113}{}{修理}
{114}{}{口才}
{115}{}{杀价}
{116}{}{赌博}
{117}{}{野外生活}
#
#   SKILL DESCRIPTIONS
#
{200}{}{对于小型武器：枪、小机关枪、来福枪等的武器有着相当的知识。}
{201}{}{对于大型武器：大枪、火箭炮、火焰发射器等等的武器有着相当的知识。}
{202}{}{对于能量武器，任何使用电浆或是激光科技的武器有着相当的知识。}
{203}{}{拳击、武功、以及其它的空手战斗技巧，用你的手以及脚的作战技巧。}
{204}{}{使用没有射程的武器：刀、锤、矛、棒等等的技巧。}
{205}{}{使用以肌肉操作的长程武器，如飞刀、掷矛、以及手榴弹的技巧。}
{206}{}{普通的治疗技巧。用来治疗小切伤、擦伤以及其它小伤。在游戏里面，使用急救箱可以比休息恢复更多的生命点数。}
{207}{}{可以治疗重伤或是受伤的肢体的技巧。没有这一项技巧，人物就得要休息相当长的一段时间才能够恢复。}
{208}{}{可以快速移动，以及不被发现的技巧。如果成功的话，别人将比较不容易找到你。你可以同时轻步以及跑步。}
{209}{}{可以不用钥匙就将锁打开的技巧。使用开锁工具组或是电子开锁器将会增强这一项技巧。}
{210}{}{你以将别人的东西据为己有的技巧。}
{211}{}{发现并且拆除陷阱的技巧，以及设定炸弹的技巧。}
{212}{}{包括了许多高科技的技巧，例如电脑、生物、物理、以及地质等方面的技巧。}
{213}{}{运用科学知识修理仪器、机器、以及电子物品的技巧。}
{214}{}{以有效率以及达意的方式与人沟通的技巧，说服别人你是正确的技巧，以及说谎不被抓到的技巧。}
{215}{}{商务以及相关的事物。可以在买、卖东西时取得较好价钱的技巧。}
{216}{}{赌博的技巧。纸牌、骰子、等等的赌具。}
{217}{}{对于互外有着相当的知识，在野外求生、以及对于动物以及植物的认识。}
#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{300}{}{+ (4 x AG)}
{301}{}{+ (2 x AG)}
{302}{}{+ (2 x AG)}
{303}{}{+ (2 x (AG + ST))}
{304}{}{+ (2 x (AG + ST))}
{305}{}{+ (4 x AG)}
{306}{}{+ (2 x (PE + IN))}
{307}{}{+ (PE + IN)}
{308}{}{+ (3 x AG)}
{309}{}{+ (PE + AG)}
{310}{}{+ (3 x AG)}
{311}{}{+ (PE + AG)}
{312}{}{+ (4 x IN)}
{313}{}{+ (3 x IN)}
{314}{}{+ (5 x CH)}
{315}{}{+ (4 x CH)}
{316}{}{+ (5 x LK)}
{317}{}{+ (2 x (EN + IN))}
#
#   Skill Use Text
#
{500}{}{你治愈了%d点生命点数。}
{501}{}{你看起来健康多了。}
{502}{}{%s看起来健康多了。}
{503}{}{你的治疗失败了。}
{505}{}{你成功使用特别技巧，因此得到了%d点经验值。}
{510}{}{\nskill_use: 使用了非法的技巧。}
{512}{}{你不能对死者进行治疗。}
{513}{}{让死者安详的去吧。}
{514}{}{他已死了，不要再烦他了。}
{520}{}{你治疗%s。}
{521}{}{你治疗%s。}
{525}{}{你无法治疗%s。}
{526}{}{你无法治疗%s。}
{530}{}{受伤的眼}    # Lines 530-534 are the endings to lines 525 & 526.
{531}{}{受伤的左臂}
{532}{}{受伤的右臂}
{533}{}{受伤的右腿}
{534}{}{受伤的左腿}
{550}{}{你开锁失败了。}
{551}{}{你无法找到任何的陷阱。}
{552}{}{你无法学到任何的东西。}
{553}{}{你无法修理那个。}
{570}{}{你偷%s被抓到了。}
{571}{}{你偷了%s。}
{572}{}{你偷放%s被抓到了。}
{573}{}{你偷放了%s。}
{590}{}{你已经证明了你那一个技巧还不成熟，再等等吧。}
{591}{}{你已相当累了。}
{592}{}{疲劳很可能会要了你的命。}

# Fallout 2!
{600}{}{你还没有足够的技巧来治疗重伤。}
{601}{}{机器已到了无法修复的境界。}



#
# Fallout 2: Party Member skill use generic responses
#

#   I'll try
{1000}{}{让我帮忙。}
{1001}{}{我会那样做。}
{1002}{}{我懂了。}
{1003}{}{很高兴能帮忙。}
{1004}{}{好。}
{1005}{}{我会尽全力的。}

#   Player wants to do it
{1100}{}{如果你不行的话，告诉我。}
{1101}{}{懂吗？}
{1102}{}{如果你要那样的话。}
{1103}{}{试试看吧。}
{1104}{}{试试看吧。}
