#
#	 Messages from stat.c
#
#
#	 STAT NAMES
#
{100}{}{力量}
{101}{}{感知力}
{102}{}{体力}
{103}{}{魅力}
{104}{}{智力}
{105}{}{敏捷}
{106}{}{运气}
{107}{}{最高生命值}
{108}{}{最高行动点数}
{109}{}{防御力}
{110}{}{空手伤害力}
{111}{}{武器伤害力}
{112}{}{目前负荷重量}
{113}{}{战斗顺序}
{114}{}{恢复速度}
{115}{}{特别攻击机率}
{116}{}{特别机率}
{117}{}{伤害极限}
{118}{}{激光伤害极限}
{119}{}{火焰伤害极限}
{120}{}{电浆伤害极限}
{121}{}{电力伤害极限}
{122}{}{灵力伤害极限}
{123}{}{爆炸伤害极限}
{124}{}{伤害防御}
{125}{}{激光伤害防御}
{126}{}{火焰伤害防御}
{127}{}{电浆伤害防御}
{128}{}{电力伤害防御}
{129}{}{灵力伤害防御}
{130}{}{爆炸伤害防御}
{131}{}{辐射防御度}
{132}{}{毒药防御度}
{133}{}{年龄}
{134}{}{性别}
{135}{}{目前生命力}
{136}{}{目前中毒度}
{137}{}{目前辐射含量}
#
#	 STAT DESCRIPTIONS
#
# @ Basic stats @
#
# Strength
{200}{}{身体的力量。力量越高杀伤力就越强。影响项目：生命力、武器伤害力、以及最高负荷重量。}
# Perception
{201}{}{视觉、听觉、味觉、以及能够发现不寻常情况的能力。高度的敏感度对于狙击手相当的有帮助。影响项目：战斗顺序以及远距离的战斗。}
# Endurance
{202}{}{忍耐力以及体能上的忍受能力。拥有高度体力的人将可以在战斗中存活的较久。影响项目：生命力、毒以及辐射的防御能力、恢复速度、以及升级时所增加的生命值。}
# Charisma
{203}{}{外表吸引他人的能力。拥有高度的魅力比较能够轻易的说服他人。影响项目：非玩家人物的反应、以及交易的能力。}
# Intelligence
{204}{}{知识、智慧、以及反应力。无论是怎的角色，智力都是相当重要的一个项目。影响项目：每一个等级所得到的新技巧、更多的谈话选项、以及许多的技术。}
# Agility
{205}{}{是否能够灵活移动的能力。在战斗上，拥有高度的敏捷尤其重要。影响项目：行动点数、防御能力、战斗顺序、以及许多其它的技术。}
# Luck
{206}{}{命运、灵力等。运气与一切的行动都有密不可分的关系。许多在游戏中的事件都会因玩家的运气值而有所不同。}
#
# Derived/Non Derived stats
#
# Maximum Hit Points
{207}{}{在死亡之前可以承受的损伤。如果ＨＰ变成了０或是更低的数目，就代表死亡。}
# Maximum Action Points
{208}{}{在一回合结束之前一个角色可以进行的动作多寡。}
# Armor Class
{209}{}{改变这个角色在受到攻击时被打到的机率。}
# Unarmed Damage
{210}{}{在空手战斗时你的人物可以给予敌人的额外损伤。}
{211}{}{在空手战斗时你的人物可以给予敌人的额外损伤。}
# Carry Weight
{212}{}{你的人物可以负荷的最高物品总重量，单位以磅计算。}
# Sequence
{213}{}{决定你的人物在一个回合的战斗中的反应力。}
# Healing Rate
{214}{}{每经过一天，生命力会回复的点数。如果人物正在休息的话，每六个小时就会回复显示的点数。}
# Critical Chance
{215}{}{在一个战斗中玩家可以使出能够造成大量伤害力攻击的机率。}
{216}{}{特别机率}
{217}{}{伤害极限}
{218}{}{激光伤害极限}
{219}{}{火焰伤害极限}
{220}{}{电浆伤害极限}
{221}{}{电力伤害极限}
{222}{}{灵力伤害极限}
{223}{}{爆炸伤害极限}
# Damage Resistance
{224}{}{在遭到攻击时，敌人的伤害点数减掉这个点数就是玩家所受到的实际伤害。穿上护具可以增加这一项点数。}
{225}{}{激光伤害防御}
{226}{}{火焰伤害防御}
{227}{}{电浆伤害防御}
{228}{}{电力伤害防御}
{229}{}{灵力伤害防御}
{230}{}{爆炸伤害防御}
# Radiation Resistance
{231}{}{实际的辐射乘以这一个百分比就是人物真正承受到的辐射含量。不同的装甲或是药物都会改变这一个数值。}
# Poison Resistance
{232}{}{可以让人物对毒更加的免疫。}
{233}{}{年龄}
{234}{}{性别}
{235}{}{目前生命力}
{236}{}{目前中毒度}
{237}{}{目前辐射含量}
#
# STAT LEVEL DESCRIPTIONS
#
{301}{}{非常糟}
{302}{}{糟糕}
{303}{}{贫弱}
{304}{}{尚可}
{305}{}{平均}
{306}{}{好}
{307}{}{非常好} 	# Abbreviated for character editor
{308}{}{棒极了}
{309}{}{完美}
{310}{}{超强}
#
#	 PC STAT NAMES
#
{400}{}{还未使用的点数}
{401}{}{等级}
{402}{}{经验}
{403}{}{名誉}
{404}{}{道德}
#
#	 PC STAT DESCRIPTIONS
#
# Unspent Skill Points
{500}{}{升级后所得到的点数。每一点可以用来增加％１的技能点数，若是专长技术则会增加％２。}
# Level
{501}{}{代表人物目前的各项能力的等级。}
# Experience
{502}{}{每升一个等级都要一定的经验点数。在游戏中只要完成战斗、或者是完成一个任务之后就会得到许多的经验点数。}
# Reputation
{503}{}{在游戏中其他的人物对你的看法或是印象，随着数值的高低，游戏中的角色对你的反应也会不同。}
# Karma
{504}{}{玩家处事的态度会影响这项数值。游戏中的人物会随着这项数值的不同对你有不同的反应。}

#
#  Experience-gain messages
#
{600}{}{你升级了。}
