#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{高速循环系统}
{101}{}{彪形大汉}
{102}{}{小巧琳珑}
{103}{}{单枪客}
{104}{}{战略大师}
{105}{}{特攻队}
{106}{}{暴力战士}
{107}{}{快枪手}
{108}{}{瘟神}
{109}{}{笨手笨脚}
{110}{}{烂好人}
{111}{}{药瘾}
{112}{}{药物排斥}
{113}{}{异性吸引力}  # was: Night Person
{114}{}{专家}
{115}{}{天赋异禀}
#
#   TRAIT DESCRIPTIONS
#
{200}{}{你的新陈代谢是别人的两倍。这代表着你对放射线以及毒的防御力较低，但是你的伤会恢复的比较快。}
{201}{}{动作很慢，但是身体很壮。你在战斗时也许攻击的次数会比较少，但是每一次攻击会造成相当大的伤害力。你的最高动作点数会比较低，但是力量会比较高。}
{202}{}{你与其他的人比起来要小一号，但是动作却比别人快。你无法负荷很重的重量，但是你的敏捷会比较高。}
{203}{}{你的一只手臂比另一只要发达许多，因此你对于单手使用的武器相当的在行，不过，双手使用的武器则会造成一些困扰。}
{204}{}{你的普通攻击所造成的伤害并不多，但是你时常的可以使出特别攻击，造成相当大的伤害力。}
{205}{}{你对于周遭的危险全然不在乎，因此你的动作相当的快。因此，你的防御点数将只是身上装甲所提供的点数，不过，在战斗中你通常都会由你先攻。}
{206}{}{你的手臂力量相当的大，但是却不灵活。在攻击时可以造成相当大的伤害，但是却不常能够使出特别攻击。}
{207}{}{你开枪的速度很快，但是你却不能够瞄准特别的部位。使用枪或是空投武器时所使用的动作点数都会比正常人少用一个点数。}
{208}{}{不知道为什么，你遇到的人如果会死，就会以最惨的方式死去。你总是会看到他人惨死的景象。}
{209}{}{好消息是，你遇到的战斗对手无论进行什么攻击都不太容易成功；坏消息是，你也是一样！}
{210}{}{小时候你并没有学习许多有关战斗的技巧，因此，你的战斗力一开始会比较差。不过，医疗技术、急救、演说能力、以及杀价能力都会以相当快的速度进步。}
{211}{}{你比别人容易对一种化学药品上瘾，但是，你受到化学药品的影响时间也比别人要短。}
{212}{}{你对一种化学药品上瘾的机会是别人的５０％，但是，你受到化学药品的影响时间却是别人的两倍。}
{213}{}{你很有魅力。异性都会被你深深的吸引而对你有不同的态度，但是，同性别的却会因嫉妒而对你有敌意。}
{214}{}{你花相当多的时间来磨炼一项技术，因此，每一次升级你都会比一般人多得到五个技术点数。不过，每升四级你才会得到另外的技术。}
{215}{}{你拥有与生俱来的能力，不过你却不细心你的技术。一开始你每一项数值都比别人多一点，但是你所有的技术在一开始都会比别人要少１０％，还有，你每一次升级所得到可分配的点数都会少五点。}
