#{100}{}{You see a bespectacled young monk.}
{100}{}{你看到一个戴眼镜的年轻修士。}
#{101}{}{You see Brother Jason.}
{101}{}{你看到的杰森修士。}
#{102}{}{This monk seems to be brooding.}
{102}{}{这个修士似乎在沉思。}

#{200}{}{[The young monk quickly pockets a deck of "Tragic" cards as you approach.] What do you want?}
{200}{}{[当你接近时，年轻的修士用你难以置信的速度把“悲惨”卡放到口袋里] 有什么能帮你的?}
#{201}{}{Nothing from you. Bye.}
{201}{}{没什么事，再见。}
#{202}{}{I want to know why you just hid that card deck from me.}
{202}{}{为什么在我过来的时候要把卡收起来？}

#{210}{}{I don't know what you're talking about. I don't have any card deck.}
{210}{}{我不知道你在说什么。我没有任何卡牌。}
#{211}{}{Don't lie to me. I saw you put it away in your pocket. I just wanted to know why.}
{211}{}{冷静下来，兄弟。我看见你把它放在你的口袋里。我只是想知道为什么。}
#{212}{}{Alright, whatever you say. See ya.}
{212}{}{好吧，无论你说什么。再见。}

#{220}{}{Look, don't tell anyone, alright? We're not suppose to "use" pre-war relics, just worship them. But these Tragic cards are so damn cool. [He seems to get lost in another world as he gazes lovingly at the deck. After a moment, he looks up at you.] Oh, sorry. I'm Brother Jason by the way. I, uh, don't suppose you play Tragic?}
{220}{}{听着，别告诉任何人，好吗？我们不允许去碰战前的遗物，遗物是用来朝拜的。但这些悲剧卡简直太酷了。[当他用爱恋的眼神看着那组卡牌时，他好像迷失在另一个世界。过了一会，他抬头看到你。]哦，对不起。我是Brother Jason。我，嗯，你不玩悲剧卡？}
#{221}{}{BRING FORTH THE GARNERING!!!}
{221}{}{带来了！！！ }
#{222}{}{Hell yeah, I love Tragic the Garnering.}
{222}{}{我喜欢死“悲剧”卡了。 }
#{223}{}{I've tried it, but it's not for me.}
{223}{}{我试过了，但这个不适合我。}
#{224}{}{I used to be addicted as hell to that game. I try to stay away from it now.}
{224}{}{那个游戏曾经让我陷入上瘾的地狱。现在我试图远离它。 }
#{225}{}{Nope.}
{225}{}{没关系}
#{226}{}{Hell no. Do I look like a pathetic loser to you?}
{226}{}{我觉得你看起来像一个可怜的失败者。 }
#{230}{}{Hey, fuck you asshole. Just leave me alone.}
{230}{}{嘿，你他妈的混蛋。别再来打扰我。 }
#{231}{}{Hey, fuck you whore. Just leave me alone.}
{231}{}{嘿，他妈的婊子。别再来打扰我。}
#{232}{}{I'd love to, but I'm overcome with a desire to do you great bodily harm.}
{232}{}{我很愿意，但我必须要说，我在很不容易地克服一个想法，那就是把你揍一顿。}
#{233}{}{Alright, fine. Bye.}
{233}{}{好吧，好。再见. }
#{234}{}{Look, I'm sorry. That was rude of me. I'm just not a fan of Tragic.}
{234}{}{我很抱歉。请原谅我的粗鲁。我不是一个“悲剧”卡的粉丝，所以我们只是看法有些不同而以。}


# {240}{}{Ah man, I'd love to play against you, but it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.}
{240}{}{嗨伙计，我非常希望和你玩，但是风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。}
# {241}{}{Ah man, I know what you mean. I wish I could play more myself, but it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.}
{241}{}{嗨伙计，我明白你的意思。我希望自己能多玩一些，但是风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。}
# {242}{}{[He chuckles.] We got an addict on our hands here, I see. I wish I could play more myself, but it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.}
{242}{}{[他咯咯地笑。]上瘾的停不下来了，我懂。我希望自己能多玩一些，但是风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。}
# {243}{}{It doesn't matter, we wouldn't be able to play anyway -- it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.} 
{243}{}{没关系，我们不能再玩了--风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。} 
# {244}{}{Yeah, that does sound stupid.}
{244}{}{对，的确听起来很蠢。}
# {245}{}{If you don't agree with the ideals of your order, then why are you a monk?}
{245}{}{如果你不赞同这些规矩，那你为什么还要做一个修道士？}

# {250}{}{You think I *chose* to be a monk? I was born into this shitty lifestyle. I just wish the others would wake up and see how stupid it is to not take advantage of all this sweet stuff we've collected. But no, they're perfectly content to worship and catalog the relics, but never actually do anything useful with them. Like I said, it's fucking moronic.}
{250}{}{你觉得是我*选择*成为修道士？我生来如此，没得选。我只是希望其他人能早点醒悟，明白不好好利用这些东西是多么愚蠢的行为。但是呢，不，他们只是满足于崇拜和整理归类这些遗物，从来不想怎么使用。就像我说的，这太傻逼了。}
# {251}{}{You got a point, that does sound pretty stupid.}
{251}{}{你说到点子上了，的确听起来很蠢。}
# {252}{}{About as moronic as me sitting here listening to you bitch about your life. Bye.}
{252}{}{我也像傻逼一样坐在这听你哔哔你的生活。拜。}
# {253}{}{If you think it's so stupid, then why don't you do something to try and change things?}
{253}{}{如果你觉得这样很蠢，为什么不行动起来尝试做些改变呢？}

#{260}{}{Finally, someone who agrees with me! Look, I have this idea, and maybe you could help me out. You see, the monks here have spent *years* transcribing pre-war information into our computer database. If someone were to "accidentally" format the database, they'd lose all that work. I think something like that might shock them back to their senses and we might finally give up this stupid way of life. So, what do you say?}
{260}{}{终于有人同意我的观点了！看，我有个想法，也许你可以帮我。这里的僧侣们在*年复一年*地抄录战前知识到我们的计算机数据库。如果有人“不小心”格式化数据库，那他们之前做的工作就都白费了。我认为这件事可能会冲击到他们，让我们可以最终摆脱这种愚蠢的生活方式。那么，你认为如何？}

#{261}{}{I say that's a terrible idea and that I'm done talking to you.}
{261}{}{我觉得这是个糟糕的主意，你的看法我不认同。}
#{262}{}{Erase years of someone else's hard work? Sounds fun. I'll do it.}
{262}{}{干掉别人多年的辛勤工作成果？听起来很有趣。我会做的。 }
#{263}{}{Why don't you format it yourself?}
{263}{}{你为什么不自己做这件事呢？}
#{264}{}{If you hate it here, why don't you just leave?}
{264}{}{如果你讨厌这里，你为什么不离开呢？}

#{270}{}{Actually, I *do* have an idea of how to change things. Maybe you could help me out. You see, the monks here have spent *years* transcribing pre-war information into our computer database. If someone were to "accidentally" format the database, they'd lose all that work. I think something like that might shock them back to their senses and we might finally give up this stupid way of life. So, what do you say?}
{270}{}{事实上，我*有*一个想法去改变这件事。也许你可以帮我。这里的僧侣们在*年复一年地*抄录战前知识到我们的计算机数据库。如果有人“不小心”格式化数据库，那他们之前做的工作就都白费了。我认为这件事可能会冲击到他们，让我们可以最终摆脱这种愚蠢的生活方式。那么，你认为如何？}
#{271}{}{I say that's a terrible idea and that I'm done talking to you.}
{271}{}{我认为和你说话这件事太可怕了。}
#{272}{}{Erase hundreds of years of someone else's hard work? Sounds fun. I'll do it.}
{272}{}{干掉别人多年的辛勤工作成果？听起来很有趣。我会做的。}
#{273}{}{Why don't you format it yourself?}
{273}{}{你为什么不自己做这件事呢？}
#{274}{}{If you hate it here, why don't you just leave?}
{274}{}{如果你讨厌这里，你为什么不离开呢？}

#{280}{}{Are you kidding me? They'd crucify me if I did that. You however, you're an experienced adventurer. Hell, I bet you could massacre everyone here without breaking a sweat. So will you do it, or are you afraid of a bunch of pacifist monks?}
{280}{}{你跟我开玩笑？他们会把我干掉的。但你是一个经验丰富的冒险家。我敢打赌，你可以干掉这里所有人而不流一滴汗。所以你要不要做？还是你竟然在怕一群修士？ }
#{281}{}{I'm not afraid of anyone. I'll do it.}
{281}{}{我不害怕任何人。我会做的。}
#{282}{}{Alright. I'll do it.}
{282}{}{好，这件事我接下来了}
#{283}{}{Nah, instead I think I'll test out your massacre theory. Starting with you.}
{283}{}{我觉得你说得不错，我想我会测试你的大屠杀理论，就从你开始好了。 }
#{284}{}{I'll pass. That's just not my style. Bye.}
{284}{}{我不会做这件事。这不是我的风格。再见.}
#{285}{}{No, I'm not going to do it. If you hate it here, why don't you just leave?}
{285}{}{不，我不打算这样做。如果你讨厌这里，你为什么不离开呢？ }

#{286}{}{Unless you've changed your mind about helping me, fuck off.}
{286}{}{除非你改变了你的主意，帮助我，他妈的。 }
#{287}{}{Alright. I'll do it.}
{287}{}{好吧。我会做的。}
#{288}{}{No, I'm not going to do it. If you hate it here, why don't you just leave?}
{288}{}{不，我不打算这样做。如果你讨厌这里，你为什么不离开呢？}

# {290}{}{You will? Seriously? Oh man, that's awesome. But first, you'll need to get access, 'cause they're pretty protective of the database. It shouldn't be too hard though, these monks are pretty trusting. They're gonna be pissed as hell when you format it, but they're all a bunch of wimps, so don't worry about it. Just try not to kill anyone -- I don't want things to get too out of hand, you know?}
{290}{}{你真的会做？哦天，太棒了。但首先，你需要权限，因为数据库保护的很好。这不会太难，这些修道士很容易相信别人。当他们发现数据库被格式化一定怒不可遏，但他们是一帮软蛋，别担心。试着别杀人--我不希望事情失去控制，明白？}
# {291}{}{Sure. Anything else?}
{291}{}{当然。还有什么事？}
# {292}{}{I make no promises. Anything else?}
{292}{}{我不能保证。还有什么事？}

{300}{}{Just format it, then take off, cause they're not going to want you around here. Don't even bother to come tell me you did it, because I'll have to act just as pissed as everyone else or they'll suspect something's up. Thanks again for doing this. It's for their own good.}
#{300}{}{你只要格式化数据库，然后离开就行了。他们不会想你留这里的。不需要回来告诉我你是怎么做到的，因为这样做别人也会怀疑我的。再次感谢你的帮忙。这件事是为了他们自己好。 }
#{301}{}{Whatever you say. Bye.}
{301}{}{你说的没错。再见. }

#{310}{}{Are you crazy? I've never been out in the wastes, but I've got a pretty damn good idea as to what it's like. I'd be lucky to make if fifty yards before a radscorpion shoved a foot-long stinger up my ass. Or even worse, I'd get captured and tortured by a gang of maniac raiders *or* I'd be eaten alive by cannibalistic tribals. Whatever. I just know that if I left here, I'd be fucked. So no, I'm stuck here.}
{310}{}{你疯了吗？我从来没有在荒野待过，在外面我可能会在50开码外被一支长矛扎个洞，会被辐射蝎毒死，碰到食人族把我吃掉，或者被一群疯子抓住折磨。如果我离开这里，我肯定会死掉的，我被困在这里了！ }
#{311}{}{Hey, it's not *that* bad out there... Actually, you're right. You probably wouldn't even make it to Gecko. At least, not without help. But what if I said I'd escort you?}
{311}{}{嘿，事情没有你想得这么糟…事实上，你是对的，你单独去蜥蜴城的确很难的。但不是没有人帮助你的。如果我说我会护送你呢？ }
#{312}{}{Sucks to be you. Bye.}
{312}{}{再见}
#{313}{}{Keep your hopes up. I'm sure there is a town nearby that would be safe to travel to.}
{313}{}{振作起来，好吗。这附近有一个小镇，你可以到那边去，而且我敢肯定，这是一趟安全的旅行。}
#{315}{}{Yeah, well if you find one, let me know.}
{315}{}{是啊，如果你找到这么一个地方，请让我知道。}
#{316}{}{Will do. Bye.}
{316}{}{我会做的。再见.}

#{320}{}{To Gecko? That's the ghoul town, right? Thanks, but no thanks.}
{320}{}{到蜥蜴城？那个小镇全是变种人，对吗？谢谢你的建议，但还是免了。}
#{321}{}{Hey, the ghouls there are actually really friendly. Besides, I know one in particular that loves a good game of Tragic.}
{321}{}{嘿，相信我好吗，那边的变种人非常友好。而且他们有一个酒吧，里面的人都很喜欢玩"悲剧"卡。 }
#{322}{}{Hey, the ghouls there are actually really friendly.}
{322}{}{嘿，那个确实是变种人的小镇，但那边的变种人其实非常友好的。 }
#{323}{}{Hey, I hear the ghouls there are actually really friendly.}
{323}{}{嘿，但我听说那里的变种人是很友好的。 }
#{324}{}{Alright. Suit yourself. Bye.}
{324}{}{好吧。随你便。再见. }

#{330}{}{No shit, another Tragic player? Hmm, that kind of changes things... I wonder if he'd have a Black Dahlia to
 trade. Alright. I'll go if you'll escort me.}
{330}{}{另一个悲剧的爱好者？嗯，那种事情有可能吗…这不会是一个陷阱吧，。好吧。如果你能陪我，我就去。}
#{331}{}{Lets go.}
{331}{}{我们出发吧。}
#{332}{}{Alright, but I need to take care of some things first. I'll let you know when I'm ready to go.}
{332}{}{好吧，但我需要先处理一些事情。我准备好之后会回来找你的。 }

#{340}{}{Oh yeah? That doesn't change the fact that they look like brahmin shit. No thanks.}
{340}{}{哦，是吗？这并不能改变事实，这个建议看起来像双头牛屎。谢谢。}
#{341}{}{Alright. Suit yourself. Bye.}
{341}{}{好吧。随你便。再见. }

#{350}{}{What do you want?}
{350}{}{你想要什么？}
#{351}{}{I just wanted to say hi. See ya.}
{351}{}{我只是来打个招呼。再见。}
#{352}{}{I changed my mind. I'll format the computer for you.}
{352}{}{我改变主意。我会为你格式化电脑。}
#{353}{}{Hey, you might want to reconsider my offer to take you to Gecko, because I know
 someone there that loves a good game of Tragic.}
{353}{}{嘿，我觉得你可能要重新考虑，我带你到蜥蜴城的提议，因为我知道有个人和你一样喜欢玩"悲剧"卡。}
#{354}{}{Hey, I know someone in Gecko that loves a good game of Tragic. I could take you there.}
{354}{}{嘿，我知道有个人和你一样喜欢玩"悲剧"卡，他就在蜥蜴城。我可以带你去那里。}
 
#{360}{}{Are we ready to go yet? I'm dying to know what kind of Tragic cards this guy's got.}
{360}{}{我们准备好了吗？我很想知道那个"悲剧"卡高手在那里}
#{361}{}{Alright, let's go.}
{361}{}{好吧，我们出发吧。 }
#{362}{}{Not yet. I'll let you know.}
{362}{}{还没有，我一会再过来。 }

# {370}{}{[Upon arriving in Gecko you introduce the young monk to Wooz. They quickly hit it off and begin comparing their Tragic card decks. You're about to leave when Brother Jason pulls himself away from Tragic long enough to have a word with you.]}
{370}{}{[一到蜥蜴城你就把年轻的修道士介绍给了Wooz。他们迅速打成一片，开始对比各自的卡组。Brother Jason立刻沉迷于悲剧卡而顾不上和你说一整句话，你准备离开。]}
# {371}{}{[MORE]}
{371}{}{[更多]}
# {372}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me. Here, I, uh, "borrowed" this from the Abbey's Memorabilia, amazingly it's one of the few tech relics that still works. [He hands you a Stealth Boy.] See ya.}
{372}{}{我靠，Wooz*真的*有黑色大丽花！这趟旅程值了。的确，僵尸看起来丑死了，不过只有我戴着眼镜的时候丑。怎么说呢，非常感谢你带我过来。这是我，呃，从Abbey那里*借*来的东西，很少见的能使用的战前遗物，[他递给你一个Stealth Boy。]回见。}
# {373}{}{Thanks. Bye.}
{373}{}{谢了，拜。}
# {374}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{374}{}{我很高兴不用再听你像婊子一样唠叨了。拜。}


#{380}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly
 as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me here.
 Here, [He reaches into his pocket, then frowns.] what the hell? I could swear I had it. Uh, sorry, but looks like I misplaced
 your reward, so you'll have to make due with a simple thanks. See ya.}
{380}{}{我的天！*黑色大丽花*稀有的牌组！光这个就让这次旅行值回票价了。虽然这些变种人很丑，但我发现如果我摘掉眼镜，我就看不到他们了。无论如何，谢谢你带我来这里。我有个东西要给你[他伸手进口袋，然后皱了皱眉。]靠！？我可以发誓我有把它带出来的。呃，对不起，看来我没法给你物质上的报酬，只能简单地对你说一句感谢了。再见。}
#{381}{}{Oh, uh, don't worry about it. Just glad I could help. Bye.}
{381}{}{没有关系。我很高兴我能帮上忙。再见. }
#{382}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{382}{}{我很高兴我不会再听到你抱怨了。再见. }

#{400}{}{Can't talk... must build more powerful deck...}
{400}{}{不要打扰我…我要建一副更强的牌组… }

#{500}{}{Leave me alone.}
{500}{}{让我静一静。}
#{501}{}{Go away.}
{501}{}{走开。}
#{502}{}{Fuck off.}
{502}{}{滚开.}

#{600}{}{Oh, hey, it's you. Somebody blew up the reactor at Gecko and all the ghouls left. No reason for me to stay there,
 so I left and came back here. Luckily for me the monks here didn't question my absence, so I'm not in any trouble for leaving.
 This sucks though, I thought I was going to have a new life doing what I love. [He sighs deeply]}
{600}{}{哦，嘿，是你。有人炸掉了蜥蜴城的反应堆，所有的食尸鬼都离开了。没有理由让我留在那里，所以我离开了，回到了这里。对我来说幸运的是，这里的修士没有质疑我的缺席，所以我没有任何麻烦离开。但这很糟糕，原本我想我会有一个新的生活，做我喜欢的事情。[他深深叹了口气]}


#{601}{}{Sorry to hear that. See you around.}
{601}{}{听到这个很抱歉。以后常见面}
#{602}{}{That's life. One minute you're on top of the world and the next instant you're face down in the mud. Live and learn. Bye.}
{602}{}{这才是人生呀！一分钟你就在世界的顶端，下一瞬间你就在泥里。生活与学习。再见. }

#{610}{}{Guess I just gotta get used to this place.}
{610}{}{我想我必须习惯这个地方}

#{1000}{}{You safely escort Brother Jason to his new home.}
{1000}{}{你安全护送杰森修士到他的新家。}

