{100}{}{你看见一个中年修士。}
{101}{}{你看见修士马太。}
{102}{}{他正站在讲台上为阿比的市民讲道。}

{200}{}{阿比善良的人们。给我片刻，我有一些话要说。}

#new speech for RP 1.3
#{201}{}{Here we collect, the holy relics of an age long past.}
{201}{}{于此，吾等尽集先祖神圣之智。}
#{202}{}{Scorched by the Flame Deluge, into the dark, we were cast.}
{202}{}{烈焰曾噬吾等先辈，吾等迫匿黑暗。}
#{203}{}{A Memorabilia we shall make, to preserve the wisdom of old.}
{203}{}{吾等汇聚于此，职记先辈之繁盛。}
#{204}{}{We must guard and care for it, though the flame has gone cold;}
{204}{}{先祖之智，吾等珍重。}
#{205}{}{It could ignite once again, should the wisdom be misused.}
{205}{}{是日，烈焰尽熄。若指日先祖之智蔓延，其若重燃。}
#{206}{}{Thus, no one shall learn, for fear of another, Flame Deluge.}
{206}{}{故先祖之智，吾等止于视。}
#{207}{}{But one day, men shall rise above their desire for destruction.}
{207}{}{故先祖之智，吾等止于守。}
#{208}{}{And the Memorabilia will be there, awaiting re-introduction.}
{208}{}{指日烈焰重降，吾等即为壁城，指日烈焰重降，吾等复还先祖之智。}
#{209}{}{So we tend to our holy task, lest all that wisdom, we lose.}
{209}{}{吾等皆居圣职，力竭不息。}
#{210}{}{We must preserve and protect it, but never shall we use.}
{210}{}{先祖之智，吾等止于视，先祖之智，吾等止于守。}
#{211}{}{So go now my friends, and let your spirits be lifted;}
{211}{}{振汝躯体，竭力神职;}
#{212}{}{For the guardians of knowledge, we have each, been gifted.}
{212}{}{尽守先祖之智，余皆异秉。}
#{213}{}{Now, please take a moment and reflect on what I have said.}
{213}{}{现在，请用一点时间来细想一下我说的这些。}

#{224}{}{Now, please take a moment and reflect on what I have said.}
{224}{}{现在，请用一点时间来细想一下我说的这些。}

#{300}{}{Greetings friend. I don't think I have seen you around here before. My name is Brother Matthew and I help spread
 the word about the importance of books and the knowledge contained within them.}
#{300}{}{祝福你朋友，我想我以前没见过你吧。我叫马太修士，我向世界传播书本中知识的价值。}
#{301}{}{It's good to meet you Matt. My name is }
{301}{}{很高兴见到你马太。我的名字是}
#{302}{}{ and I am on a quest for the holy GECK.}
{302}{}{ 我正在寻找神圣的伊甸园创造器。}
#{303}{}{Sorry, I must be going.}
{303}{}{对不起，我得走了。}

#{400}{}{A GECK, huh? I do remember reading something about that during one of my reading sessions. Go to the second floor
 and ask for access to one of our computers. I am sure you will find something useful there. And while you are at it, take
 a moment to peruse through our library. Not all our books have been copied over to the computers yet and a great many books
 are still found in their original format.}
{400}{}{伊甸园创造器？我记得读过一些相关的资料。去二楼查寻下我们的电脑。我相信你会找到一些有用的资料的。你可以到那细读一下我们的图书馆里的书。不是所有书都拷贝到电脑里的，很多伟大的书都是原版。}
#{401}{}{I think I just might. I have some questions though.}
{401}{}{我想我会的。我还有一些问题。}
#{402}{}{Thank. I shall go do that now.}
{402}{}{谢谢，我现在就去。}

#{500}{}{I am at your service. What would you like to know?}
{500}{}{你想知道什么？}
#{501}{}{What can you tell me about this place?}
{501}{}{你能说说这个地方吗？}
#{502}{}{You seem to be very poetic in your preaching. Any reason for this?}
{502}{}{你在演讲时看上去很有诗意。为此有什么理由吗？}
#{503}{}{Nevermind. Take care.}
{503}{}{没什么，别介意。}

#{600}{}{The Abbey is home to anyone, so long as they don't cause trouble. We are an independent community and rarely get visitors, such as yourself. The majority of those you see here are descended from the original founders that settled in this old monastery not long after the great Flame Deluge.}
{600}{}{修道院是任何人的家，只要他们不惹麻烦。我们是一个独立的社区，这里很少有访客，比如你。你所看到的大多数人都是最初的创始人的后裔，他们在巨大的火焰洪流之后不久就定居在这个古老的修道院中。}

#{601}{}{Go on.}
{601}{}{继续}

#{602}{}{The quiet, peaceful quality of this place has made it an appealing home to other travelers that have wandered here over the years, seeking to escape from the dark chaos of the wastes. Of course, the true value of this place lies in its vast library. It's filled with old tomes, containing the strange wisdom of a lost age. Over time, we've come to fancy ourselves the keepers and guardians of that wisdom.}
{602}{}{这里远离尘嚣，它成为了多年来路过这里的旅行者的一个吸引人的家园，在这里，他们试图逃离荒芜的黑暗。当然，这个地方的真正价值在于它巨大的图书馆。它充满了古老的信息，包含了一个逝去时代的奇异智慧。随着时间的推移，我们认为自己是智慧的守护者和保存者。}

#{603}{}{Very interesting. Another question.}
{603}{}{很有趣，问下别的问题。}
{604}{}{很有趣，我得走了。}

#{700}{}{[The man chuckles at your question] No, no particular reason. I have just read much poetry throughout my life
 and I enjoy applying it to my teachings. It helps leave a greater impact on those listening.}
{700}{}{[因为你的问题他吃吃的笑] 不，不，没什么特别的理由。只是因为在我的一生里我读了很多诗，我很享受把它应用到我的演讲里，这有助于他们聆听。}
#{701}{}{Fair enough. Another question.}
{701}{}{非常好。另一个问题。}

{800}{}{很高兴再次见到你。}
{801}{}{我能为你做点什么？}
{802}{}{我有一些问题。}
{803}{}{没什么，再见。}
