{100}{}{你看见一个年轻人，看上去很强壮。}
{101}{}{你看见彼得斯先生。}

{200}{}{你好，朋友。以前没见过你。你一次来阿比？}
{201}{}{很高兴再次见到你。我能为你做点什么？}
{202}{}{是，你能介绍一下这个地方吗？}
{203}{}{我正在找神圣的伊甸园创造器。关于这个你知道什么吗？}
{204}{}{塞缪尔修士说你可能知道一些关于谁在墓地捣乱的事。他说你在田里听到一些声音。}
{205}{}{别介意，我得走了。}

{300}{}{好的，阿比是一个很安宁的地方。我和我的妻子跟着一个商队到这边做过几年的生意，后来我们很喜欢这里，最终决定留下。 从那后我们开始种一些农作物养活自己。}
{301}{}{你来自一个商队？商队会经常来这里吗？}
{302}{}{不，阿比修道院是一个二流的商业线路，商队不会经常来这里。如果你想知道更多关于商队的事。问问那边商店的比尔，他可能知道更多的事，你可以在南边找到他。}
{303}{}{那听上去不错。我先走了。}
{304}{}{很有趣，我想知道点别的事。}
{305}{}{别介意。我得走了。}

{400}{}{你还要知道什么？}
{401}{}{关于阿比你能告诉我什么？}
{402}{}{你知道关于伊甸园创造器的事吗？}

{500}{}{伊甸园创造器？嗯....我记得在大教堂的档案室读过一点有关的资料。我不记得上面怎么说的了。如果我是你的话就去查查那些文件，也许你能找到一些有用的信息。}
{501}{}{谢谢，我就去看看。我还有一些问题。}
{502}{}{谢谢你的消息。我现在就去查查。}

{600}{}{塞缪尔修士叫你来的？什么他现在酒醒了？}
{601}{}{说说你遇到了些什么。}
{602}{}{(约翰坐到了椅子上喝了几口酒) 好吧，一切始于几天前，我和我的妻子在家，晚上，我们听到一些奇怪的沙沙声，所以我拿着提灯跑出去看是什么东西发出这种声音，但当我到了田里的时候声音就没了。}
{603}{}{继续。}
{604}{}{听着。我真必需走了。}
{605}{}{然后第二晚我们就没听见任何声音了。又过了一晚上，我们又听见那个沙沙声，这次我只是小心地在窗口里看着。这次我看见好像是一个老旧的提灯发出的小光圈在田里移动，过了一会光圈移动到了墓地那边。}
{606}{}{到了早上我去田里查看，发现很多农作物被吃了，周围还有很多新的脚印。}
{6061}{}{我去问塞缪尔墓地发生什么事，塞缪尔说有人盗墓，但从被掘开的墓地痕迹来看，干这事的人力量很差。所以我猜测可能是一个没什么力气的小孩或者老人在干这件事。老实说，我不介意我的庄稼被需要的人吃掉了，但我对小偷没什么好感。如果查出是哪些人做的，请你告诉他们停手吧。如果我能帮到他们的话，我很乐意帮忙。}


{607}{}{我会试着找出这些人的。也许我夜晚在那里等着就能找到一些线索了。谢谢你这些线索，保重。}
{608}{}{我会看看我能做点什么。走之前我还有一些问题。}
{609}{}{这故事真是有一点长。再见。}
#{610}{}{Let me get this straight. You'd be happy to help someone that lurks around your house at night, steals yourcrops, and tries to rob your dead? I've met a lot of loonies in my day, but you just might take the cake. It's a marvelyou've survived this long.}
{610}{}{等等，让我先弄清楚。你很乐意帮助那些晚上在你的房子周围偷你的庄稼，并且试图盗墓的人?我在这段日子遇到过很多疯子，但你竟然活了这么久，这真是一个奇迹。}

#{611}{}{[He narrows his eyes, but manages to hold his composure.] That's how we do things here at the Abbey. If kindnessis so offensive to you, then I suggest you get the hell outta my house. I'm not gonna sit here and let some wanderingtribal insult me in front of my wife.}
{611}{}{[他额头的青筋显了出来，但设法保持镇静] 这就是我们在修道院做的事情！另外我建议你离开我的房子！我不会坐在这里，让一些人，在我妻子面前肆意侮辱我！}

#{612}{}{Alright, alright, I'm leaving.}
{612}{}{好吧,好吧,我离开。}

#{613}{}{OK tough guy, now this "wandering tribal" is going to kill you in front of your wife. Then maybe I'll kill her too.Hell, maybe I'll kill everyone in this pathetic fucking place. You thought you could all hide from the horror of the wasteland?Well guess what, my naive friend? Horror has found you, and its name is }
{613}{}{好吧，硬汉，现在这个"流浪的部落人"会在你的妻子面前杀了你。也许我还会杀了她，也许我会杀了在这里所有的人。你觉得这里是一个很安宁的地方？你错了，你碰到了荒原的恐怖?我天真的朋友?你不找恐怖，恐怖找到你了，它的名字是。}


#{700}{}{Get the hell outta here.}
{700}{}{滚出去。}

#added in RP 2.1
#{710}{}{Good to see you again. Tom's been a big help around here. Thanks again for sorting all that out. Now, what can I do for you?}
{710}{}{很高兴再次见到你。汤姆在这里帮了大忙。现在，我能为您做些什么?}
