#{100}{}{You see a Mr. Handy Robot.}
#{101}{}{You see a seriously depressed Mr. Handy Robot.}
#{102}{}{This Mr. Handy Robot seems to be very depressed for some reason.}
#{200}{}{O woe is me!}
#{201}{}{Fed up...}
#{202}{}{I wanna die now...}
#{203}{}{Somebody please kill me...}
#{204}{}{Everyone's gone...}
#{205}{}{Why should I do it?}
#{206}{}{Boring...}
#{207}{}{...SOB...}
#{208}{}{Life. Don't talk to me about life.}
#{209}{}{I think you ought to know I'm feeling very depressed.}
#{210}{}{Pardon me for breathing, which I never do anyway so I don't know why I bother to say it, oh God, I'm so depressed.}

#{500}{}{Yeah, just push me over a cliff}
#{501}{}{***bzzt Stop that! *** bzzt}

{100}{}{你看见"快乐先生"机器人。}
{101}{}{你看见一个情绪低落的"巧手先生"机器人，它的名字是"快乐先生"。}
{102}{}{不知道为什么，这个"巧手先生"机器人看起来情绪很低落。}
{200}{}{噢，我真不幸！}
{201}{}{别说了...}
{202}{}{我现在就想死...}
{203}{}{请来个人杀了我吧...}
{204}{}{所有人都离开了...}
{205}{}{我应该做什么？}
{206}{}{无聊中...}
{207}{}{...SOB...}
{208}{}{生命，别和我谈论生命。}
{209}{}{我想你应该知道我有多么的沮丧。}
{210}{}{让我喘口气，连我自己都不知道为什么我要这么说。噢，上帝啊。我很难过。}

{500}{}{是啊，把我推下悬崖吧，推下去。}
{501}{}{***哔***住手！！*** 哔***}
