#{100}{}{You see a hologram.}
#{101}{}{You see a hologram.}

{100}{}{你看到一个全息图.}
{101}{}{你看到一个全息图.}


#{200}{}{Zzzzzt...Hello... zzZzzt..Are..zzzZzzZtt...stand...me?}
#{201}{}{Excuse me?}
#{202}{}{Right. Bye.}
#{203}{}{My...zZzzzt..sensor...ZzzzzzZzt...*garble*..fixed?}
#{204}{}{Sorry, but I can't understand you. There's too much static. I'll see if I can maybe fix it somehow.}
#{205}{}{I don't have time for this. Bye.}

{200}{}{Zzzzzt[电流声]...你好... zzZzzt[电流声]..是..zzzZzzZtt[电流声]...站...我?}
{201}{}{对不起?}
{202}{}{再见。}
{203}{}{我的...zZzzzt[电流声]..传感器...ZzzzzzZzt[电流声]...旁边*红*..修理?}
{204}{}{对不起，我听不懂你说的。有太多干扰了，你说旁边红色的机器？我试试能不能修好它}
{205}{}{我没有时间做这件事。再见。}


#{300}{}{Ah, thank you so much for repairing me! I was dreading the thought of some visitor happening along and asking me questions which I'd be unable to properly answer due to all the static. Of course, you're the first visitor I've seen since the war, but still, *had* I encountered someone else, that could have been quite embarrassing.}
#{301}{}{No problem. So what exactly is this place anyway?}
#{302}{}{[He grins, seemingly delighted at the prospect of having questions to answer.] You're standing in the Environmental Protection Agency, more commonly referred to as the EPA. We're a government research facility that specializes in testing chemicals to ensure that they're safe for the Earth's environment. But that's just scratching the surface. We had all sorts of exciting things going on here, at least until the facility was vacated due to the war. Things haven't quite been the same since.}
#{303}{}{Interesting. So, what exactly is your purpose here?}
#{304}{}{Well, unlike the other holograms you will encounter, I wasn't created for a specific task. I'm merely here to answer visitor's questions or help solve difficult mathematical problems that the human mind cannot accomplish.}
#{305}{}{I see. Then perhaps you could answer some questions for me?}

{300}{}{啊，谢谢你修理了我！我一直都很害怕观光客会问我一些问题，因为都是干扰，如果有问题我根本无法正确回答。当然，你是我自从战争以来见过的第一个访客，但如果*我*遇到的是其它人，那可能会很尴尬。}
{301}{}{没问题，到底这个地方到底是做什么的？}
{302}{}{[他咧嘴笑着，似乎很高兴有问题要回答]这里是环境保护局，更常被称为EPA。我们是一个政府研究机构，专门研究化学物质以确保它们对地球环境是安全的。但这只是表面上的解释拉，我们这里经常发生各种令人兴奋的事情，至少在这个设施因战争而被弃置之前是这样的。}
{303}{}{有趣，那么，你在这里是做什么的？}
{304}{}{嗯，我不像你遇到的其他全息图，我不是为一个特定的任务而创建的。我只是在这里回答游客的问题，或者帮助解决人类思维无法解决的数学难题。}
{305}{}{我明白了。那么你可以回答我一些问题吗?}


#{310}{}{Oh, I'd love to answer your questions. Ask away and I'll answer them to the best of my ability.}
#{311}{}{I keep seeing references to a Blue Level. How do I access it?}
#{312}{}{I found another way into this facility, but it requires a passcode. The service elevator brings you to it.}
#{313}{}{Can you identify some items I found around here?}
#{314}{}{Nevermind. I don't need anything.}

{310}{}{哦，我很乐意回答你的问题。请你开始问吧，我将尽我所能回答它们。}
{311}{}{我看到这里的电脑一个关于蓝色区域的资料，我要访问它的话要怎么做?}
{312}{}{我找到了另一种方法进入这个设施，但它蓝色区域需要一个密码。}
{313}{}{你能解释一下我在附近发现的这些东西的用途吗?}
{314}{}{我目前不需要任何的东西。}



#{320}{}{Why of course, the main elevator at the surface should take you where you want to go! Why would you go through the
 ventilation system?}
#{321}{}{Well, that elevator is not working anymore and the only way in I found was through the vents.}
#{322}{}{Oh, I see. That makes more sense. Well, there is another way in. There is a service elevator which stops on level two.
 It should be accessible from under the Doctor's workshop. He can be found outside, to the east of the main entrance to the EPA.
 You will need an access code to get inside, however. Since I am grateful for you repairing me, I shall tell you code. The code is "FLOWERPOT".}
#{323}{}{Thanks. Let me ask you something else.}
#{324}{}{Oh, I'm sorry but the Blue Level contains top secret research. Access to that level is restricted to... oh, to hell with it. You were kind enough to repair me, so I suppose I could give you the password. It's "FLOWERPOT".}

{320}{}{这里的主升降机应该带你去任何你想去的地方才对！你为什么要用另一个方法？通风系统？}
{321}{}{哦，那个电梯坏了，我找到的唯一办法是通过通风口。}
{322}{}{哦，我明白了。还有另一种方法，有一个服务电梯停在第二层，但是，您需要一个访问密码才能进入内部。既然我感激你修理我，我就告诉你密码，密码是"FLOWERPOT"。}
{323}{}{谢谢，让我问你一些其它事}
{324}{}{哦，对不起，蓝色的层次包含绝密的研究。进入这一级别仅限于...哦，见鬼去吧。你对我很好，所以我想我可以给你密码，密码是"FLOWERPOT"。}


#{330}{}{I will do my best. What item would you like me to identify?}
#{331}{}{What is the purpose of this dog food?}
#{332}{}{I found this syringe full of an unknown substance. Could you tell me what it does?}
#{333}{}{I found this rack of test tubes. Anything specific I can do with it?}
#{334}{}{What are the effects of using these drugs I found?}
#{335}{}{I made some unknown chemicals with the Mr. Chemmie! machine. What do they do?}
#{336}{}{I found some dynamite that was different than ones that I have encountered. How do I use it?}
#{337}{}{Actually, let me ask you something else.}

{330}{}{我将尽我最大的努力。您想让我识别什么东西？}
{331}{}{这狗食有什么用？}
{332}{}{我发现这个注射器充满了一种未知的物质。你能告诉我是怎么回事吗?}
{333}{}{我发现了这些试剂，这是什么用途的。}
{334}{}{使用这些药物的会造成什么影响？}
{335}{}{我用"点石成金"先生做了一些不知名的化学制品，它们是做什么用的？}
{336}{}{我发现了一些与众不同的炸药，我如何使用它?}
{337}{}{实际上，让我问你一些别的问题。}

{340}{}{Well, the original designers of this place always liked to place little references from movies, books, and other
 such sources all over the place. They found it funny and so did many others. The dog food is a reference to a movie,
 but I'll leave it up to you to figure out.}
{341}{}{Alright. Let me ask you something else.}

{350}{}{Well, those basic instruments for any chemist. I suppose if you want to create something then one would find
 a use for them.}
{351}{}{Alright. Let me ask you something else.}

#{360}{}{Ah, that's an interesting specimen you have there. I'm afraid I don't recognize it. Please, place it in the container next to me and I'd be happy to analyze it for you.}
#{361}{}{Alright. [You place the item in the container and close the lid.]}
#{362}{}{On second thought, let me ask you something else.}
#{363}{}{Reading molecular make-up of liquid in syringe...Success. Analysis Complete. Interesting, it seems this syringe contains a unique serum with traces of feline DNA. It appears to be an experimental drug with the potential to enhance a human's agility. Of course, I wouldn't recommend you use anything that's still in the experimental stage.}
#{364}{}{Alright. Let me ask you something else.}

{360}{}{啊，恐怕单凭观察我无法知道这是什么，请把它放在我旁边的容器里，我很乐意为你分析具体的成份。}
{361}{}{[你把东西放在容器里，然后盖上盖子]}
{362}{}{让我问你一些别的问题。}
{363}{}{解析注射器中的液体的分子构成...分析成功，分析完成。这种注射器似乎含有一种独特的血清，带有猫科动物的DNA，它似乎是一种具有增强人类速度的实验性药物。当然，我不建议你使用任何还在实验阶段的东西。}
{364}{}{好吧。让我问你一些别的问题。}


#{370}{}{Ah, that would be cannabis, also known as marijuana, weed, and ganja, among other things. It's a type of illegal drug that may induce psychoactive effects when smoked or consumed. Some of the technicians here used to be fond of smoking it to help them relax. If you smoke it, you should be aware that it may cloud your mind and lower your reaction time for a period of time.}
#{371}{}{Alright. Let me ask you something else.}

{370}{}{啊，那是大麻，在战前它是一种非法药物，如果你点燃并吸入它的话可能会产生精神上的影响。这里的一些技术人员过去喜欢抽大麻来帮助他们放松。如果你抽过大麻，短时间内你的大脑反应会因为兴奋而提升，但你应该意识到之后它会使你的大脑变得迟钝，并且会持续一段时间。}
{371}{}{好了。让我问你一些别的问题。}




#{380}{}{Ah, that's an interesting specimen you have there. I'm afraid I don't recognize it. Please, place it in the container next to me and I'd be happy to analyze it for you.}
#{381}{}{Alright. [You place the item in the container and close the lid.]}
#{382}{}{On second thought, let me ask you something else.}
#{383}{}{Unfortunately, I have no information in my database which describes this item. As with any unknown substance, I'd advise you to take great caution before deciding to use it. Sorry I couldn't be of more help.}
#{384}{}{Alright. Let me ask you something else.}

{380}{}{啊，恐怕单凭观察我无法知道这是什么，请把它放在我旁边的容器里，我很乐意为你分析具体的成份。}
{381}{}{[你把东西放在容器里，然后盖上盖子]}
{382}{}{好吧。让我问你一些别的问题。}
{383}{}{抱歉，我的数据库中对这个项目没有描述。和任何未知的物质一样，我建议你在决定使用它之前要非常谨慎。抱歉，我帮不到您。}
{384}{}{好了。让我问你一些别的问题。}


#{390}{}{This is an interesting item. Unlike other dynamite which has a timer, this dynamite is controlled by a radio trigger.
 Just place the dynamite where ever you want it to go off and press the trigger to detonate it. Quite a nifty item, don't
 you think?}
#{391}{}{Definitely. Let me ask you something else.}

{390}{}{这是一个有趣的项目。不像其他有计时器的炸药，这个炸药由一个无线电触发器控制。只要把炸药放在你想要的地方，按下扳机引爆，然后就会发出很漂亮的光芒。 }
{391}{}{好的，让我问你一些别的问题。}



#{400}{}{Hello again. Something else I can help you with?}
#{401}{}{I have some questions.}
#{402}{}{Nevermind. Bye.}

{400}{}{你好了。还有什么我可以帮你的吗?}
{401}{}{我有一些问题。}
{402}{}{没什么事，再见。}


#{500}{}{You open up the side panel to the hologram emitter and look inside. You see a mess of cables and circuit boards.}
#{501}{}{Well, let's get started.}
#{502}{}{After some time you isolate the problem and correct it. You close up the panel and wipe the sweat from your brow.}
#{503}{}{You have successfully repaired the hologram.}
#{504}{}{After some experimentation you fail to figure out what is wrong with the hologram.}
#{505}{}{Damn. This is too hard for me. Repair just isn't my forte.}
#{506}{}{You fail to repair the hologram.}
#{507}{}{[DONE]}


{500}{}{你把全息图投影仪侧板打开，往里面看，发现有一堆的电路板和电线。}
{501}{}{好吧，让我们开始吧。}
{502}{}{在一段时间后，你把问题找出来并修正了，你关上面板，擦去额头上的汗。}
{503}{}{你已经成功地修复了全息图投影仪。}
{504}{}{在做了一些测试之后，你仍然无法弄清楚全息图投影仪到底有什么问题。}
{505}{}{该死。这对我来说太难了。修理不是我的专长。}
{506}{}{你没有修理好全息图。}
{507}{}{[结束]}
