#{100}{}{Unauthrorized Access Requested. Locking door.}
#{101}{}{Authorization Granted. Unlocking door.}
#{102}{}{Door is already unlocked.}
#{103}{}{You see a door to the Security Wing.}
#{104}{}{You see a reinforced door for the Security Wing.}

#{200}{}{There is no lock to pick.}


{100}{}{不被授权的访问请求，门已锁死。}
{101}{}{授权批准，门已解锁。}
{102}{}{门已经解锁了。}
{103}{}{你看到安全部门的门了。}
{104}{}{你看到安全部门的门了，它看起来很硬很厚。}

{200}{}{这门上面没有锁。}