# Message file for epai1.ssl 
# Number of nodes: 1

#{100}{}{You see a pamphlet.}
#{101}{}{}
#{102}{}{This is an introductory leaflet given out at the start of tours.}

{100}{}{你看到小册子。}
{101}{}{}
{102}{}{这是在观光开始时分发的介绍性传单。}

# Node  0  [Node001]
{200}{}{欢迎来到EPA！在参观我们的设施时，请不要被半透明全息人吓倒，他们不是鬼——他们是我们友好的新员工！他们是计算机程序以人类形态表达的科学奇迹！他们很乐意回答你的任何问题。所以请不要害怕亲近他们[警告！全息图像是通过一个带有反重力装置的悬浮晶体进行投影的，如果晶体被挪动，可能会非常不稳定。所以为了你自己的安全，不要试图去触摸任何东西。感谢您的配合，祝您旅途愉快!]}
{201}{}{结束}
{202}{}{You need to take this out of inventory first.}
