#{100}{}{The generator has a damaged circuit board. Maybe you could scavenge replacement parts from some junk.}
#{101}{}{You see a generator.}
#{102}{}{You see an EPA lighting generator.}
#{103}{}{You see a generator that controls the lighting in the EPA.}
#{104}{}{After a lengthy search, a circuit board with some damaged pieces is located. Maybe if some junk is found to scavenge through, some replacement parts could be obtained.}
#{105}{}{There's the problem!}
#{106}{}{The broken parts have been mended together and the generator is back online.}
#{107}{}{Nothing wrong can be found with the generator. It just doesn't seem work.}
#{108}{}{It's working. There's nothing else to do.}
#{109}{}{Something doesn't seem right with this generator.}

#{200}{}{*whirr*}
#{201}{}{*bzzt*}



{100}{}{发电机有一个损坏的电路板，也许你可以从一些垃圾中找到替换零件。}
{101}{}{你看到一台发电机。}
{102}{}{你看到一个EPA的照明发电机。}
{103}{}{你看到一个发电机，它控制着EPA的照明。}
{104}{}{在经过长时间的搜寻后，你发现一个线路板已经烧焦了。走运的是，损坏的只是连接的电线而以，也许垃圾里面可以找到一些替换用的电线。}
{105}{}{有问题! }
{106}{}{破损的部分已被修复，发电机重新联机。}
{107}{}{在发电机中检查不出什么问题。}
{108}{}{这个发电机正在工作，没什么其它的事可以做。}
{109}{}{这个发电机似乎有些不对劲。}

{200}{}{*哔咔哔咔*}
{201}{}{*咔咔咔*}