#{100}{}{Hibernation Chamber Control Computer. Select an option.}
#{101}{}{Subject history.}
#{102}{}{Retrieve a test subject.}
#{103}{}{[DONE]}

{100}{}{休眠仓控制计算机，请选择一个选项。}
{101}{}{历史记录。}
{102}{}{检索实验体。}
{103}{}{[结束]}

#{104}{}{Hibernation Chambers. Three individuals were sealed within these chambers before the war, each for specific classified
 reasons. Subjects remain sealed and unaware of their surroundings. Log entries are available for each subject.}
#{105}{}{Return to Main Menu.}
#{106}{}{WARNING: Extended periods of time in a deep freeze environment alters the chemical processes of the body.
 Without proper application of chemicals to the subject's body on exiting the chambers, they may suffer from ERS
 (Environmental Rejection Syndrome). To ensure the safety of the subject, it is highly recommended that you place an ERSI
 (Environmental Rejection Syndrome Inhibitor) canister into the dispenser before continuing.}
#{107}{}{Oh wonderful. I've just woken up a pile of bones.}
#{108}{}{No, return to Main Menu.}
#{109}{}{Retrieving test subject.}

{104}{}{战争前，有三个人被封存在这些休眠仓里，每个人都有特定机密的原因。目前实验对象仍然在封存中，实验体的详细信息请参阅日志文档。}
{105}{}{[返回主菜单]}
{106}{}{[警告！]长时间在深度冰冻环境中休眠会改变身体的化学构造，如果在解除休眠前没有适当地将化学物质应用到受试者的身体，他们可能会受到未知且不可逆的伤害
(环境拒绝综合症)。为了确保实验体的安全，强烈建议您置入一个ERSI(环境排斥综合征抑制剂)。}
{107}{}{哦，好了，我刚刚把一个冰鲜罐头弄醒了。}
{108}{}{不，返回主菜单。}
{109}{}{检索实验体。}

#{110}{}{Retrieving test subject.}
#{111}{}{Retrieving test subject.}
#{112}{}{Thank you for using the Hibernation Control Computer.}
#{113}{}{You see a large computer.}
#{114}{}{You see The Hibernation Control Computer.}
#{115}{}{You see a computer that is used to regulate anything to do with the Hibernation Vats.}

{110}{}{检索实验体。}
{111}{}{检索实验体。}
{112}{}{感谢你使用休眠控制计算机。}
{113}{}{你看到一个大的计算机。}
{114}{}{你看到了休眠控制计算机。}
{115}{}{你看到一个计算机，它的工作是调节休眠仓的所有相关事务。}


#{116}{}{Place ERSI canister into the dispenser.}
#{117}{}{Proceed anyway.}

{116}{}{请将ERSI罐放入分配器。}
{117}{}{休眠仓解锁。}


#{118}{}{Environmental Rejection Syndrome Inhibitors were successfully applied to the specimen. Heart rate of specimen appears normal. Please
 proceed to the Cryo chamber for retrieval.}
#{119}{}{WARNING: No Environmental Rejection Syndrome Inhibitors were applied to the specimen. State of specimen is unknown. Please
 proceed to the Cryo chamber for retrieval.}
#{120}{}{Hmm, maybe I should go see if I can find one of these ERSI canisters. There's got to be someplace around here to get those chemicals...}

{118}{}{环境排斥综合症抑制剂[ERSI]被成功地应用于实验体，实验体的心率正常，请打开休眠仓进行检查。}
{119}{}{警告:环境排斥综合症抑制剂[ERSI]没有被应用于实验体，实验体的状态未知。请打开休眠仓进行检查。}
{120}{}{嗯，也许我应该去看看能不能找到这里所说的ERSI，这里应该有个地方可以弄到这些化学品...}

#{200}{}{Read log entries.}

#{210}{}{Please choose a subject.}
#{211}{}{Subject A.}
#{212}{}{Subject B.}
#{213}{}{Subject C.}
#{214}{}{Back.}

{200}{}{阅读日志。}

{210}{}{请选择一份文档。}
{211}{}{日志文档 A。}
{212}{}{日志文档 B。}
{213}{}{日志文档 C。}
#{214}{}{[返回]}


#{220}{}{Log Entry #87983: It's finally happened. They've launched their nukes at us and we've launched ours at them.
 Brass won't go into detail, but it's probably already Judgment Day topside by now. Radio communications have been disrupted
 indefinitely. Good thing I've grown used to this place. I've got no illusions about ever seeing the surface again.}
#{221}{}{[MORE]}
#{222}{}{They brought in a woman to be cryoed. Didn't say why; only that it was top secret business. She was quite the looker.
 Petite, Chinese-looking, and there was something about her eyes. She took down two secret service agents when she found
 out what we had in mind. Caught them off guard and opened them both up with one of Delnay's scalpels, Jesus Christ. That was
 a sight for tired eyes. The third one managed to subdue her. It's not like she wouldn't be spending the rest of her
 life down here if she'd managed to kill them all, anyway. She's unconscious now and they're prepping her tank.
 It's right next to that psychopath Patrick's, too. What a shame. I would've liked to have gotten to know her better.
 -Dr. David Kimble, 10/23/2077}
 
{220}{}{日志#87983：终于还是发生了，他们向我们发射了他们的核武器，我们向他们发射了我们的核武器。政府没有详细说明，但现在可能已经是审判日了，无线电通讯中断了。幸好我已经习惯了这个地方，我对再见到地面没有任何幻想。}
{221}{}{[更多]}
{222}{}{他们带来了一个要冷冻的女人，没说为什么，只是说那是绝密的事。她相当的漂亮，身材娇小，看起来像中国人，她的眼睛特别有味道。当她意识到我们的目的时，她对押送的特工们突施杀手。两个特工被她用Delnay的手术刀开膛破肚了，啧啧，那场面真是少儿不宜。要是第三个特工没能制服这个女人，她下半辈子准不会在这儿度过。现在她在昏迷之中。他们正在准备她的休眠仓，就放在那疯子Patrick的旁边。太可惜了，我真希望能了解她多一点。
 -David Kimble博士, 10/23/2077}

#{230}{}{Log Entry #81977: Dexter "Dex" Patrick is a rather interesting specimen. He's a narcissistic, woman hating,
 sociopathic murderer, known to occasionally dabble in necrophilia and cannibalism. He is cold hearted to the extreme,
 showing no remorse for his victims, who ranged from innocent children to the elderly and disabled. His preferred targets
 were attractive young women, who he'd usually seduce into intercourse before brutally dispatching them.}
#{231}{}{[MORE]}
#{232}{}{Despite his antisocial behavior, he remains remarkably sociable, even charming. In fact, several female
 staff members seem to be taken with him, despite knowing the numerous atrocities he's committed. Dex's confirmed
 victims is currently 68, though he has boasted the actual number is well into the triple digits.
 While Dex has proven to be a compulsive liar, I still find it difficult to doubt the validity of his claim.}
 
{230}{}{日志# 81977：Dexter “Dex” Patrick是相当有趣的标本。他是个自恋狂，憎恶女人，反社会的杀人犯，据说还有恋尸癖和吃人肉的前科。冷酷无情，对待任何受害者都毫不手软，无论是无辜的儿童，老年人还是残疾人。他的首选目标都是那些漂亮的年轻女子，在残忍地打发她们之前，他通常会勾引她们上床。}
{231}{}{[更多]}
{232}{}{尽管Dex有反社会行为，但他仍然很爱交际，甚至称得上迷人。事实上，尽管知道他犯下过许多暴行，但几个女性工作人员似乎仍然被他所吸引。目前已证实的Dex的受害者人数达到68人，尽管他吹嘘说实际数字已经达到了三位数。虽然Dex谎话连篇，但我愿意相信这一说法的真实性。}
 
 
#{233}{}{[MORE]}
#{234}{}{The only emotional attachment Dex seems to have is for a mid-20th century rock 'n roll idol, whom he admires
 as a role model and perhaps even as a father figure. He's also shown an unhealthy attachment to a severed human ear,
 which we have identified as belonging to Vicky Safron, Dex's high school sweet heart and one of his early victims.
 He claims to keep the ear in his pocket so Vicky can hear the screams of all his victims.}
 
{233}{}{[更多]}
{234}{}{唯一让Dex有情感依恋的似乎是一个20世纪中叶的摇滚乐偶像。他钦佩他，作为一个榜样，甚至是一个父亲式的人物。他还对一个切下来的人类耳朵表现出病态的依恋。我们已经确定耳朵属于维姬·瑟芬，Dex的高中情人，也是他的一个早期受害者。他声称把耳朵放在口袋里，这样维姬就能听到所有受害者的尖叫声。}
 
#{235}{}{[MORE]}
#{236}{}{I've decided to have Dexter frozen for the time being, as the government has re-routed funds away from our
 project in order to further fuel the war effort, and my team is being re-assigned to other locations. Let it be noted
 that I deem this a terrible mis-step, as our studies on the nature of human evil are progressing swiftly and I believe
 we are near a major breakthrough that would be far more valuable to our government than the production of more "tin suits".
 But I digress.}
 
{235}{}{[更多]}
{236}{}{我决定先把Dex冻起来。政府正在从我们这里撤资，好支援它的战争计划，我的团队也要被重新部署到其他地方。这是一个错误，因为我们关于人类邪恶本性的研究进展得很快，我相信马上会迎来一个重大的突破，这将比我们生产更多的“锡罐头”对我们的政府更有价值。不过我离题了。}
 
#{237}{}{[MORE]}
#{238}{}{Dex is to remain frozen here until the powers-that-be come to their senses and resurrect this vastly important
 project. I only hope I'm still around to resume my work when that day comes.
 -Dr. Dustin C. Delnay, 04/13/2075}
 
{237}{}{[更多]}
{238}{}{Dex将在这里继续冻结，直到政府高层们恢复理智并且重启这个极其重要的项目，我希望那天到来时我还能继续工作。 -Dustin C. Delnay博士, 04/13/2075}
 
 
#{240}{}{Log Entry #80052: Sergeant Christopher "Cat" Jules was assigned to the EPA military security detail on 17/02/2074.
 Prior to this, he was attached to a reconnaissance unit of the 205th Airborne. The Sergeant has an impressive combat record,
 and is one of the highest-graded energy arms and unarmed combat specialists in his unit. However, these achievements are
 marred by an equally long history of accusations of very petty theft, repeated counts of being out of uniform, and an attitude
 of extreme arrogance to superior officers.}
#{241}{}{[MORE]}

{240}{}{日志# 80052：Christopher “Cat” Jules中士在2074年2月17日被分配到EPA军事安全部队。在此之前，他在第205空降兵的侦察部队服役。中士的战斗记录令人印象深刻，是他所在单位中最尖端的能量武器和徒手格斗专家之一。然而，这些光辉成绩不能掩盖他长期以来小偷小摸，不穿制服和顶撞上级的大量记录。}
{241}{}{[更多]}

#{242}{}{Sgt. Jules was recruited as a test subject for the Human Reflex Enhancement Project on 10/05/2075 in exchange for the removal of
 some of these reports from his file. Complications arose from the initial trial and Sgt. Jules was sedated for the safety
 of himself those around him.}
#{243}{}{[MORE]}

{242}{}{为了从档案中删除这些不良记录，Jules中士在2075年10月5日作为测试对象加入了人体反射增强项目。在最初的测试中出现了并发症状，出于Jules中士和他周围人安全考虑，他被注射了麻醉剂。}
{243}{}{[更多]}

#{244}{}{A few days have passed and Sgt. Jules appears to be in good health, but he has developed lengthened canines and
 certain eccentric characteristics in addition to the project goals of improved reflexes and heightened sensory capability.
 I have logged several reports with the base Commander requesting further funding, but alas it seems there are those who do not
 wish for my project to continue. This is quite a shame, since the tissue samples and psych reports for Sgt. Jules indicate
 only minor disfigurement and a tendency to a slightly reduced attention span. Other than this, he is perfectly fit
 for service and in fact, he is likely more capable than before as a result of the treatment. Until more funding is
 received for this project, Sgt. Jules shall remain in suspended animation.
 -Dr. R.D. Crichton, 11/04/2075}
 
{244}{}{几天过去了，Jules中士显得很健康，不过，除了达到了项目中的提高反射能力和感知能力目标以外，他还长出了加长的犬齿和其他一些古怪的特征。我已经向基地指挥官提交了几份报告，要求进一步提供资金，但遗憾的是，似乎有一些人不希望我的项目继续下去。这是一大遗憾，因为根据组织样品和心理报告，Jules中士只表现出轻微的畸形和注意力不集中。除此之外，他完全健康，能够服役。事实上，由于治疗，他可能比以前更有能力。在更多的资金投入这个项目前，Jules中士将保持休眠状态。
 -R.D. Crichton博士, 11/04/2075}


{300}{}{选择一个休眠仓:}
{301}{}{Christopher "Cat" Jules中士}
{302}{}{Dexter "Dex" Patrick}
{303}{}{Kitsune}
