#{100}{}{You see a functional computer.}
#{101}{}{You see the EPA's Top Secret Research and Development Terminal.}
{100}{}{你看见一台计算机。}
{101}{}{你看见EPA的最高机密研究开发终端。}

#{102}{}{Welcome to EPA's Top Secret Research and Development Terminal. Error initializing quick access procedure. Please
 search for something specific.}
#{103}{}{Search for anything of importance.}
#{104}{}{Logoff.}
#{105}{}{After 30 minutes of sifting through all the files you find four of which appear useful. Please make a choice below.}
#{106}{}{Access FEV history log.}
#{107}{}{Access file on Epilepsy cure.}
#{108}{}{Keep searching.}
#{109}{}{Please make a choice below.}

{102}{}{欢迎使用EPA的最高机密研究开发终端。快速访问初始化错误，请搜索详细信息。}
{103}{}{搜索任何有价值的资料。}
{104}{}{[结束]}
{105}{}{经过30分钟的搜索过滤，最后找到4个有价值的文件。请选择。}
{106}{}{访问FEV历史记录。}
{107}{}{访问有关癫痫病治疗文件。}
{108}{}{[继续查找]}
{109}{}{[请选择]}


#{110}{}{As tensions continued to mount between the US and China, a fear at the forefront of the minds of our military officials
 was that the Chinese would deploy biological weapons against American troops. As a result, West Tek, a major high tech
 defense contractor, was hired to develop a counter agent. This led to West Tek's research on the Pan-Immunity Virion
 Project (PVP) with the intent of creating immunity in soldiers by restructuring their DNA. During testing of PVP in 2076,
 abnormal side effects were observed in test subjects. The test animals began to grow dramatically and their brain activity
 increased.}
#{111}{}{[MORE]}
#{112}{}{Seeing the potential there, the Army quickly commandeered the project and renamed it FEV: Forced Evolutionary Virus.
 Not content with mere immunity to disease, FEV would potentially turn soldiers into abnormally strong and intelligent
 "supermen". Once testing on animals reached its logical conclusion, FEV research was moved to its current location at
 the Mariposa Military Base. There, we have learned that the testing will proceed to the next level, as they begin top
 secret testing on military prisoners. We eagerly anticipate the results of these exciting experiments.}
#{113}{}{Back.}

{110}{}{随着美国和中国之间的紧张局势不断升级，我们的军事官员们的脑海中出现了一种恐惧。那就是中国可能会对美国军队部署生物武器。WestTek，一个高科技公司被要求开发可与其对抗的武器。这导致了对免疫系统粒子研究的开始，这个项目被命名为PVP：Pan-Immunity Virion Project，目标是通过重组士兵的DNA以增强士兵的免疫力。但在2076年PVP测试期间，试验对象中观察到异常的副作用，实验动物肌肉量显著地生长，并且他们的脑容量也得到增长。}
{111}{}{[更多]}
{112}{}{看到此项目的潜力，军队迅速占领了这个项目，并重新命名为FEV：Forced Evolutionary Virus（强迫进化病毒）。不仅仅满足于对疾病免疫，FEV旨在增强士兵身体，并取得智力增长，目标是制造"超人"。在动物实验取得合乎逻辑的结果后，FEV研究被转移到马里泊萨号军事基地，在那里将对军事囚犯进行人体测试。我们急切地期待着这些激动人心实验的结果。}
{113}{}{[返回]}




#{120}{}{One of our researches, Dr. Hodkin, has made a wonderful discovery in his recent research on the way the human brain
 processes verbal responses. Apparently, by repeating a series of letters with the proper inflections, a listener can be
 cured of a number of neurological diseases, such as autism or epilepsy. Included in this log is the exact string of letters
 (and the proper inflections) used by Dr. Hodkin in his experiments. This is wonderful news and is a great beginning to
 further research into treatment for chronic neurological disorders.}
#{121}{}{This might be useful. Make note of the string and search for something else.}

{120}{}{我们其中一个研究员，霍金博士近来有了一个伟大的发现，是有关人类大脑在说话时的反应过程的。用他的理论通过重复一系列的字母和适当的词形变化，可以影响到精确的大脑位置，这可以治愈好一些神经疾病，如孤独症或癫痫。这对于神经疾疾学来说真是一个很好的消息。[在这个日志中包含了精确的字母串]}
{121}{}{这可能会很有用的。记下来吧。再查查别的资料}


#{130}{}{You find nothing more of interest.}
#{131}{}{You still find nothing more of interest.}
#{1311}{}{Don't give up. Something is bound to be found.}
#{132}{}{Maybe if you search a little more, you might find something?}
#{133}{}{Maybe one more search?}
#{134}{}{After much painful searching, you come across a hidden file.}
#{135}{}{Access file labeled: Mass Fluoridation Project.}

{130}{}{你发现没什么有用的资料了。}
{131}{}{你还是找不到什么有用的资料。}
{1311}{}{别放弃，一定还会有些其它资料的。}
{132}{}{也许还能找到一些，你要继续查找吗？}
{133}{}{也许再找找。}
{134}{}{经过许多痛苦的查找。你找到了一个隐藏文件。}
{135}{}{访问标题为MFP：Mass Fluoridation Project（大规模氟化项目）的文件。}


#{136}{}{In the continued effort to make the citizens of the United States more controllable, the inclusion of sodium
 fluoride in all available drinking water is effective immediately. Long term effects in testing has resulted in
 subjects becoming more "stupid and docile." In addition, it was observed that sodium fluoride caused slight damage to
 a specific part of the brain, making it more difficult for the person affected to defend his freedom and causing the
 individual to become more docile towards authority.}
#{137}{}{[MORE]}
#{138}{}{In our most recent experimentation, we have chosen military official, General J. Ripper, as a subject. Initially,
 he was unaware of our intent but now seems to have caught on. He has become obsessed with the phrase "precious bodily
 fluids" and avoids drinking any substance he does not know from where it originated. He has even stopped having sexual
 intercourse as he fears that women seek "the life essence."}
#{139}{}{Back.}

{136}{}{经过持续的努力，美国公民变得更容易控制了，在他们的饮用水中加了钠氟化物看来非常有用。项目的长期效果已经产生，样本变得更"温顺和听话"了。经观察钠氟化物可以对生物的大脑某个精确部分产生损伤，这样可以让人们变得更顺从。}
{137}{}{[更多]}
{138}{}{我们最近实验中，我们选择了一个军事官员，杰．瑞派将军，作为实险对象。一开始他没有察觉到我们的目的，但是现在似乎知道了。他变得很困扰，开始不喝任何东西，他不知道哪里出有问题。他甚至放弃了性，因为他害怕女人会吸走他的精华。}
{139}{}{返回。}
 
{200}{}{你知道了在水中加钠氟化物的真正目的。}


 
 
#new in RP 1.3
#{150}{}{Gender Modification.}
#{151}{}{Virus-laden Fruit Flies.}
#{160}{}{Dr. Glen Wood has achieved a new breakthrough in his research into gender modification that he claims will
 revolutionize our countries espionage efforts. With just a simple procedure, a man could become a woman, or vice versa.
 Dr. Wood has insisted that he be the first to undergo the radical transformation. Once the operation is complete, he has
 requested that he, or she, be referred to as Glenda.}
#{170}{}{The mutant fruit flies are now successfully carrying the virus. However, before we unleash them on foreign soil,
 it's been decided that we shall first expose the fruit flies to a small isolated American community, where we can monitor
 the effects outside of a lab environment. The civilian casualties that are likely to result are an unfortunate, yet
 necessary, sacrifice. Besides, any true American would be honored to give up their life for the good of our great nation.}
 
{150}{}{性别改变项目}
{151}{}{"甜蜜"果蝇项目}
{160}{}{格伦.伍德博士在改变性别研究中取得了重大突破。他声称这份研究将彻底改革我们国家的间谍活动，只要一个简单的程序，男人就可以成为女人，反之亦然。伍德博士成为第一个接受彻底转变的人，手术完成后，他/她要求身边的人称呼他/她为格琳达.伍德博士。}
{170}{}{变异果蝇已经成功地携带了病毒。然而，在我们将它们释放到国外之前，我们首先要把果蝇暴露在一个小而孤立的美国社区里，在那里我们可以检测项目在自然环境中的作用。对此可能造成的平民伤亡是不幸的，但这是必要的牺牲。任何真正的美国人都应当可以为我们伟大祖国的利益而牺牲自己的生命。}
 


#{200}{}{You learn about the true intent of water fluoridation.}

{200}{}{你了解到MFP：Mass Fluoridation Project（大规模氟化项目）的真正意图。}

{311}{}{Whirrrr....}
{312}{}{BEEP!!}
{313}{}{Clunk...}
