#{100}{}{There seems to be a problem with this elevator.}
#{101}{}{This elevator is obviously not working. You'll have to find another way.}
#{102}{}{You see a damaged elevator door.}
#{103}{}{On closer inspection, the elevator car is missing and the doors are jammed.}
#{104}{}{You don't have a chance of repairing this.}

{100}{}{这电梯好像出了问题。}
{101}{}{这个电梯显然不工作了，你得另寻出路。}
{102}{}{你看到一个损坏的电梯门。}
{103}{}{On closer inspection, the elevator car is missing and the doors are jammed.}
{104}{}{你没有机会修理这个。}