#{100}{}{You see a computer.}

{100}{}{你看到一台计算机。}

#general interaction
#{150}{}{Please select an option below.}
#{151}{}{Information}
#{152}{}{Employee Access}

{150}{}{请选择所需的功能。}
{151}{}{信息}
{152}{}{员工访问}

#{160}{}{Please select an option below.}
#{161}{}{Lower Force Field}
#{162}{}{[BACK]}

{160}{}{请选择所需的功能。}
{161}{}{关闭力场}
{162}{}{[返回]}

#{170}{}{To lower force fields, please enter access password. (If password is lost or forgotten, please see Hologram 40011, Director of Public Relations.)}
#{171}{}{ABRE}
#{172}{}{[BACK]}

{170}{}{关闭力场需要管理员权限，请输入密码(如果密码丢失或遗忘，请咨询公共关系总监，全息图像40011)}
{171}{}{ABRE}
{172}{}{[返回]}

#{180}{}{Thank you. Force fields are now disengaged.}
#{181}{}{[DONE]}

{180}{}{力场已经关闭了。}
{181}{}{[返回]}

#petting zoo
#{200}{}{Welcome to the EPA Petting Zoo! Here you'll have the pleasure of interacting with these unique creatures that
 look like hideously deformed humans! That's because these ugly beasts are the result of exciting experiments where our
 brilliant scientists are attempting to splice human and animal DNA!}
#{201}{}{[MORE]}
#{210}{}{In theory, this new science might one day allow us to create a "Super Person". Imagine a US Soldier with the sight
 of an eagle, the speed of a cheetah, and the strength of an ape! Imagine how this "Super Soldier" would strike fear into
 the hearts of commies! It sounds like science fiction, but it may soon be science fact!}
#{211}{}{[MORE]}
#{220}{}{The creatures you see here are the results of experiments that haven't quite met with success. Instead of euthanizing
 these failed abominations, we thought it'd be fun to put them in a petting zoo. Don't worry, despite their horrific appearance,
 they're not likely to attack as long as they're well fed. We're happy to report only three visitor casualties have occurred
 in the past year!}
#{221}{}{[Logoff.]}


{200}{}{欢迎来到EPA的宠物乐园！在这里你可以和这些独特的生物互动。看起来有点像畸形人对吗，不要害怕！这些生物其实是一项伟大技术的产物，聪明的科学家正试图将人类和动物的DNA拼接起来！}
{201}{}{[更多]}
{210}{}{在理论上，也许某天我们会出创造一个"超人"。想象一名美国士兵，他拥有鹰的眼睛，豹的速度，熊的力量！这个"超级战士"将让那些共产混球恐惧不已！不久的将来，它可能就会成为科学事实！}
{211}{}{[更多]}
{220}{}{你在这里看到的都是尚未成功的实验结果。作为人道，我们没有安乐死这些实验体，我们认为把它们放在宠物乐园会更有趣。别担心，只要食物充足，他们就不会造成什么危险。我们很高兴地报告，在过去的一年里，只有三名游客伤亡！ }
{221}{}{[退出]}


#Wanamingos
#{300}{}{Welcome to our newest exhibit! The strange looking tentacled creatures you'll see in this cage might look like they
 came from outer space, but they're not aliens, in fact, they were made right here in America! As you may have guessed,
 these guys weren't created by mother nature, they were created by science!}
#{301}{}{[MORE]}

{300}{}{欢迎来到我们的最新展览！你在这个笼子里看到这些奇怪的触手，可能你认为他们来自外太空，但他们不是外星人，事实上，他们都是"美国制造"！你们可能已经猜到了，这些都不是大自然的产物，而是由科学创造的奇迹!}
{301}{}{[更多]}



#{310}{}{That's right, these fearsome monstrosities were engineered by American scientists in top secret laboratories, as
 the newest weapon in the war for freedom. Their powerful tentacles and sharp teeth were specifically designed to tear
 apart America's enemies. Their tentacles also excel at digging, so the commies won't even be safe in their underground
 bunkers! Also, these ferocious killers have skin so thick, that bullets have a hard time penetrating it!}
#{311}{}{[MORE]}
#{320}{}{You're looking at the future of biological warfare! But don't worry, these vicious slaughter machines can't get
 you, as they're safely locked within the confines of their highly secure cage. You'll have to excuse the dim lighting,
 but these guys are happiest when dwelling in cool, dark places, and you wouldn't want them to get angry, would you?}
#{321}{}{[Logoff.]}

{310}{}{这些可怕的生物是美国科学家在顶级秘密实验室设计，为自由而战的最新武器。它们强有力的触须和锋利的牙齿将会撕裂美国的敌人！他们的触须也擅长挖掘。即使那些共产混球躲在地下掩体里，他们也不会安全！而且，这些凶残的杀手皮肤很厚，子弹很难穿透它！}
{311}{}{[更多]}
{320}{}{你正在为生物战争的未来担心？别担心！这些恶毒的屠杀机器是得到高度控制的，他们都被安全地锁在了高度安全的笼子里。}
{321}{}{[退出]}




#spore plants
#{400}{}{Here you can see plant life unlike any you've seen before! This exciting new species, derived from the Venus Fly
 Trap, was specifically engineered by our brilliant scientists to be able to survive in a world devastated by a nuclear
 war. Why would we want to do that? It's simple.}
#{401}{}{[MORE]}

{400}{}{这里你可以看到全新的植物生命。和你平常所见的植物不同，这是一个令人兴奋的新物种，它的部分基因源自火星上的陨石碎片。它由我们杰出的科学家设计的，能够在核战摧毁后世界中生存的全新生命体。我们为什么要这么做？原因很简单。}
{401}{}{[更多]}


#{410}{}{After a global nuclear war, scientists believe that much of the Earth will become a barren wasteland. Plant life
 will have a difficult time surviving in this harsh new environment. Now imagine us emerging from the safety of our
 Vault-Tec vaults only to find that all the plants are dead! That'd mean no more salads for Mom, and no more lawns for
 Billy and Rover to play fetch in.}
#{411}{}{[MORE]}

{410}{}{在一场全球核战争之后，科学家们相信地球的大部分将变成贫瘠的荒地，旧的植物在这个严酷的新环境下很难生存下去。现在想象一下，当我们打开大门从避难所中走出来，发现所有植物都没有了，那就意味着我们的晚餐没有沙拉了，我们也没有草坪让比利和罗孚一起去玩了。}
{411}{}{[更多]}

#{420}{}{Sounds terrible, doesn't it? But don't worry. These new plants may be the answer to that problem. Instead of
 relying on fertile soil and rainfall, they're able to derive nutrients by killing and eating animals, just like
 people! All through the wonders of science!}
#{421}{}{[Logoff.]}

{420}{}{听起来很可怕，不是吗？但是别担心。这些新植物可能是这个问题的答案。他们像人那样，能够通过宰杀和食用动物来获取营养，而不是依靠肥沃的土壤和雨水。这是科学的奇迹！}
{421}{}{[退出]}

