{100}{}{你看见一个部族女性。}
{101}{}{你看见Kurisu，史力克的妹妹。}
{102}{}{你看到一个年轻、丰满的女人，带着些耳环和纹身。}

{150}{}{[结束]}

{200}{}{史力克！[她紧抱自己，开始低语] 那是灵魂开的玩笑，还是那真的是你，哥哥？}
{201}{}{我？不，我是获选者。你一定是想这老骨头鼻子了吧。}
{202}{}{[史力克冲到门口，紧握住他妹妹的手。你转头离开，为他们感人的重逢留出私处的空间。片刻之后，听到屋外折断树枝的声音，史力克立即松开她妹妹，抄起他的武器，瞥了一眼门外。外面除此之外没有别的声音。]}
{203}{}{[更多]}
{204}{}{[Sulik's sister turns to you.] Bonespirits say you be leading Sulik. Name's Kurisu, but now not the time for proper greetin'. Please, you needin' to get us out of cage and away from de wicked men ruled by spirits of lust. [She sneers and spits in the dirt.] Filthy dogs will not be laying hands on us again. [Upon hearing this, Sulik's eyes widen as his face contorts with rage. He reaches for his weapon.]}
{205}{}{Hold on there, Sulik, we're outnumbered here. Let me see if I can lockpick this door and we can sneak our way out of here.}
{206}{}{Hold on there, Sulik, we're outnumbered here. I got the key to this door. Let's keep it quiet and we'll sneak our way out of here.}
{207}{}{[你对史力克点头]那些混蛋会付出代价。弹药上膛吧，老伙计。}
{208}{}{[几分钟过去了，你也最终听到门锁发出咔的一声。门被打开了。]}
{209}{}{[向Kurisu]那好，靠近我，低着头。[向别的奴隶]保持安静向树林移动。}
{210}{}{[几分钟过去了，你没能搞定门锁。]}
{211}{}{一定还有别的方法打开这门。让我试试能否找到一把钥匙。呆在这，我会回来的。}
{212}{}{好吧史力克，是时候兑现你的计划，干掉那群垃圾了。}
{213}{}{[You put the key in the lock and unlock the gate, it screeches as it opens.]}

{214}{}{找到了么，朋友？求求你快点吧。}
{215}{}{不还没有。我还在努力寻找。}
{216}{}{我拿到钥匙了。是时候救你出来了。}
{217}{}{Why there be so much commotion out there? Ah, I sense many have gone to join the spirits. Who be... Sulik? Do the spirits be teasing, or is that really you, brother?}
{218}{}{Why there be so much commotion out there? Ah, I sense many have gone to join the spirits. And I sense you be the one sending em. What you be needin', Ghost-maker?}
{219}{}{我是来救你的。}

{221}{}{Praise the spirits! Please, you needin' to get us out of cage. Away from this evil place.}
{222}{}{Spirits praise you! Now I must go and return to my people. Long have I been missed. Please, stop by my village. It be near the Great Salt Water, a few days south west of here. Thank you, fren.}
{223}{}{[Sulik rushes to the gate door and clasps the outstretched hands of his sister. You turn away to give some privacy to their emotional reunion. Moments later, his sister turns to you.] Bonespirits say you be leading Sulik. Name's Kurisu, but now not the time for proper greetin'. The Slavers, they be dead, yes?}
{224}{}{Yes, the slavers are dead.}
{225}{}{Praise the spirits! Please, unlock this door. We eager to go from this evil place.}
{226}{}{Don't worry. I got a key.}
{227}{}{Alright, let me try and lockpick this door.}

{400}{}{我们赶紧上路吧。}
{401}{}{求你了，我想要回家。}

{410}{}{[向Kurisu] Wait, I don't want to leave here until I free the slaves in the other holding pens. You wait here until I free everyone from this camp. [向别的奴隶]保持安静向树林移动。我会解决那些守卫的。}

{500}{}{如果你是来干我的，那你就别怪我打死你 —— 等等，你的头上并没有恶魔的标记。你是谁？}
{501}{}{我是“获选者”，你是谁？}
{502}{}{我的名字是 }
{503}{}{。你的名字是？}

{510}{}{我叫Kurisu。我来自西南边大盐水旁的部落。奴隶贩子抓住了我和其他人，但其他人被送往了别处。奴隶贩子们说不会对我怎样，却围着我让我满足他们邪恶的欲望。求你了，帮我们逃离这笼子，远离那些邪恶的人。}

{511}{}{别担心，我这就就你出去。我拿到了钥匙和许可，带你离开这里。}
{512}{}{那好，让我试试能不能撬开这扇门。}

{530}{}{这真的安全么？你让那些奴隶贩子们去见灵魂了？}
{531}{}{是的，安全了。我们能去你村子了。}
{532}{}{是的，但在我们走之前让我先去解救其他奴隶。}

{533}{}{不，还没有。我会在确保安全后回来。}

{600}{}{赞美灵魂，我们终于能回家了！真是太感谢你了，朋友。}
{601}{}{不用客气。但你是怎么被抓住的？}
{602}{}{Was trading in nearby village. Slavers came. Much bloodshed and chaos. Then, everything go dark. Awoke in packed cage reeking of shit. Soon moved to smaller cage, with ones they like to be keeping. Peeped many slaves come and go. Sad to see people be treated like cattle.}
{603}{}{是啊，奴隶制真是个糟糕的东西。我很抱歉听到你遭受那样的事情，Kurisu。那么，你现在打算怎么做？}
{604}{}{Slavers hurt me, but I far from broken. The spirits guided you to ensure my freedom. Clearly, the spirits be planning something big for me. Spirits got big plans for you, too. And brother Sulik. He will be much missed, but the spirits say his place is walking by-and-by with you. Hell, even Grampy Bone like you, so I know Sulik in good hands. You take care.}
{605}{}{谢谢你，Kurisu，待会见。}
{606}{}{Slavers hurt me, but I far from broken. The spirits guided you to ensure my freedom. Clearly, the spirits be planning something big for me. Soon, I think I be going to hunt down brother. Knowing Sulik, he prolly got in trouble, trying to come help me. Now, perhaps I be the one helping him.}
{607}{}{Actually, I think I've seen your brother. Face full of tattoos and a big bone in the nose, right?}
{608}{}{That be Sulik alright! And Grampy Bone, too! Please, could you go bring Sulik home? I be missing that man so much.}
{609}{}{没问题，我会带他来这里的。待会见，Kurisu。}
{610}{}{我真做不到。你也知道，史力克死了。}
{611}{}{Sulik... dead? Truly, this be a dark day. I know he be with Grampy now, but Sulik... he will be much missed. [She looks away as tears fill her eyes.] Please... I need being alone now. Thank you... for bringing me home.}


{650}{}{你好，朋友。还有你史力克！}
{651}{}{[更多]}
{652}{}{[Kurisu rushes to Sulik, who sweeps her up into an embrace. You turn away to give them some privacy during their emotional reunion. Several moments later, Kurisu turns to you with a grin as she wipes tears from her eyes.] Thank you, fren, for finding brother. Spirits got big plans for you and Sulik. He will be much missed, but the spirits say his place is walking by-and-by with you. Hell, even Grampy Bone like you, so I know Sulik in good hands. You take care.}
{653}{}{你好朋友。你有找到我哥哥史力克？}
{654}{}{没有，仍在寻找。当我找到他我会回来的。}

{700}{}{再次感谢你，朋友。愿灵魂们保佑你。}
{701}{}{我真的很想念史力克哥哥。}

{800}{}{你与邪恶的灵魂一路！滚吧！}

{810}{}{回去屋子里，Kurisu！我会解决他们的！}

{820}{}{求求你，别让他们伤害我们。}

{1000}{}{你让史力克和他的妹妹重逢。}

# dumb dialogue
{900}{}{我？不，我是“获选者”。你说史力克？}
{910}{}{是的，坏人死了。}

{920}{}{我拿到钥匙了。}
{921}{}{我试试开锁把。}
{922}{}{[你向史力克点头]我们去和坏人战斗吧。}
{923}{}{我还有事要做。}

{930}{}{[向Kurisu]我保护你。[向别的奴隶]回家吧。}

{940}{}{撬锁看来没用。我去寻找钥匙。你等着。}
{941}{}{撬锁看来没用。[你转向史力克]我们去和坏人战斗吧。}


{950}{}{我“获选者”，你呢？}
{951}{}{我 }
{952}{}{。 你是？}

{960}{}{安全了。我们回家吧。}
{961}{}{还没安全。还有坏人需要被杀。}

{970}{}{你客气了。他们怎么抓住你的？}
{971}{}{是的，坏人们太坏。接下来你想做什么？}
{972}{}{谢~谢~。再见！}
{973}{}{我认识史力克。史力克我朋友。他说话跟我一样。他和他鼻子上的骨头交谈。}
{974}{}{我带他来。他想念你。}
{975}{}{我抱歉。他死了。}
{976}{}{我还在寻找。}

# PC had defeated the Enclave
{2000}{}{我就*知道*骨魂赋予你了伟大使命。}
{2001}{}{你不仅拯救了我，之后你又拯救了世界。你真是一位英雄。}
{2002}{}{你或许真的不需要史力克了吧，可以么？}
