#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the name which will  #
#           be displayed for critter or items when they     #
#           get hit. Each script from scripts.lst should    #
#           have a name associated with it.                 #
#                                                           #
#  Created: October 06, 1997                                #
#############################################################

{101}{}{}                               # obj_dude.int    ; Player script.
{102}{}{测试 0}                  # Test0.int       ; Used to Test Scripts
{103}{}{测试 1}                  # Test1.int       ; Used to Test Scripts
{104}{}{测试 2}                  # Test2.int       ; Used to Test Scripts
{105}{}{测试 3}                  # Test3.int       ; Used to Test Scripts
{106}{}{测试4}                  # Test4.int       ; Used to Test Scripts
{107}{}{测试5}                  # Test5.int       ; Used to Test Scripts
{108}{}{阿罗由战士}                 # ACWarior.int    ; Generic Warrior in Arroyo
{109}{}{阿罗由村民}                # ACVillgr.int    ; Generic Villager of Arroyo
{110}{}{曼那克}                          # ACMynoc.int     ; Mynoc, Bridge Guard of Arroyo
{111}{}{阿罗由长老}                   # AHElder.int     ; Elder of Arroyo
{112}{}{哈库林}                        # AHHakun.int     ; Hakunin, Shaman of Arroyo
{113}{}{门}                           # Door.int        ; generic locked and trapped door
{114}{}{一般的}                        # Generic.int     ; Generic dialog for scripts
{115}{}{箱子}                          # AILkBox.int     ; Locked box in Arroyo Elder's room
{116}{}{上锁的盒子}                        # Containr.int    ; Generic locked and trapped container
{117}{}{双头牛}                        # ACBrahmn.int    ; Brahmin for pen in Arroyo
{118}{}{胞子植物}                    # ACSporPl.int    ; Spore plants in Arroyo
{119}{}{}                               # ZClRat.int      ; Generic lesser rat
{120}{}{小毒蝎}                # ZClScorp.int    ; Generic lesser scorpion
{121}{}{小蟑螂}                  # ZClManti.int    ; Generic lesser mantis
{122}{}{小死亡爪}               # ZClDthCL.int    ; Generic lesser death claw
{123}{}{花瓶}                           # AIVase.int      ; Vase in Arroyo Villager's Hut
{124}{}{箱子}                          # AIChest.int     ; Chest in Arroyo Shaman's Hut
{125}{}{阿罗由山洞}                   # ArCaves.int     ; Map Script for Arroyo Caves
{126}{}{木门}                    # DoorL100.int    ; Generic Locked Door (+100%) (Wood)
{127}{}{阿罗由村}                 # ArVillag.int    ; Map Script for Arroyo Village
{128}{}{阿罗由桥}                  # ArBridge.int    ; Map Script for Arroyo Bridge
{129}{}{老旧的门}                       # AICavDor.int    ; Locked wooden door in Arroyo Caves (0/-20)
{130}{}{地板}                    # SprTrp0.int     ; Generic spear Trap (0)
{131}{}{地板}                    # SprTrp50.int    ; Arroyo Spear Trap for Caves (50)
{132}{}{地板}                    # SprTrp51.int    ; Arroyo Spear Trap for Caves (50)
{133}{}{地板}                    # SprTrp52.int    ; Arroyo Spear Trap for Caves (50)
{134}{}{地板}                    # SprTrp53.int    ; Arroyo Spear Trap for Caves (50)
{135}{}{门}                           # AIBkDor.int     ; Door w/out a handle In Arroyo Caves
{136}{}{上瘾者}                         # DCAddict.int    ; Addict from the Den
{137}{}{士兵}                          # DCG2Grd.int     ; Gang 2 Guard from the Den
{138}{}{镇民}                    # DCCustmr.int    ; Generic Customer in the Den
{139}{}{暴徒}                           # DCCustmr.int    ; Thug in the Den
{140}{}{孤儿}                         # DCOrphan.int    ; Thieving Orphan in the Den
{141}{}{乔伊}                           # DCJoey.int      ; Special thug in the Den
{142}{}{富力克}                          # DCFlick.int     ; Kwik N Save store owner in the Den
{143}{}{士兵}                          # DCG2Grd.int     ; Gang 2 Guard in the Den
{144}{}{彼特}                          # DCPetey.int     ; Petey, the alley addict in the Den
{145}{}{史密提}                         # DCSmitty.int    ; Smitty the junkyard guy in the Den
{146}{}{麦塔则}                        # dcMetzge.int    ; Metzger the Slaver in the Den
{147}{}{奴隶商人}                         # DCSlaver.int    ; Regular Slaver in the Den
{148}{}{塔比}                          # DCTubby.int     ; Tubby the store owner in the Den
{149}{}{安娜}                           # DCAnna.int      ; Anna the Ghost in the Den
{150}{}{伊克}                            # DCVic.int       ; Trader Vic in the Den, can be a party member
{151}{}{法兰基}                        # DCFranki.int    ; Frankie, owner of the Hole in the Den
{152}{}{丽蓓嘉}                        # DCRebecc.int    ; Rebecca in the Den
{153}{}{比利}                          # DCBilly.int     ; One-tooth Billy in the Hole in the Den
{154}{}{希拉}                         # DCSheila.int    ; Sheila, the prostitute in the Hole in the Den
{155}{}{妈妈桑}                            # DCMom.int       ; Mom, who run's Mom's in the Den
{156}{}{村人}                       # DCSlvRun.int    ; Generic People for Slave Runs
{157}{}{抓苦力}                      # DNSlvRun.int    ; Map Script for Den Slave Runs
{158}{}{运奴车}                     # DISlvCrt.int    ; Slave Cart to take the Player to Den
{159}{}{丹恩城商业区}              # DenBus1.int     ; Map Script for Den business area 1
{160}{}{丹恩城商业区}              # DenBus2.int     ; Map Script for Den business area 2
{161}{}{丹恩城住宅区}           # DenRes1.int     ; Map Script for Den residential area
{162}{}{坟墓}                          # diAnnGrv.int    ; Grave of Anna the ghost in the Den
{163}{}{坟墓}                          # diDadGrv.int    ; Grave of Anna the ghost's Dad in the Den
{164}{}{坟墓}                          # diMomGrv.int    ; Grave of Anna the ghost's Mom in the Den
{165}{}{尸骨}                          # diBones.int     ; Bones of Anna the ghost in the Den
{166}{}{日记}                          # diDiary.int     ; Diary of Anna the ghost in the Den
{167}{}{项链}                         # diLocket.int    ; Locket of Anna the ghost in the Den
{168}{}{蒸馏器}                          # diStill.int     ; Still that Maggie has in the basement in the Den
{169}{}{坟墓}                          # ziGenGrv.int    ; Generic grave
{170}{}{二十一点}                     # ziBlkJck.int    ; Generic black jack table
{171}{}{奴隶}                          # zcSlave.int     ; Generic slave
{172}{}{二十一点}                     # dcBlkJck.int    ; Den black jack table from Maggie's place
{173}{}{门}                           # diChcDor.int    ; Church door from the Den
{174}{}{威士卡包伯}                    # KCBob.int       ; Whiskey Bob from Klamath
{175}{}{骰子}                          # dcCraps.int     ; Maggie Craps dealer in the den
{176}{}{艾尔多}                           # KCAldo.int      ; Aldo from Klamath
{177}{}{艾丁}                          # KCArdin.int     ; Ardin from Klamath
{178}{}{小孩}                          # KChild.int      ; Child from Klamath
{179}{}{市民}                        # KCitizen.int    ; Citizen from Klamath
{180}{}{麦达}                          # KCMaida.int     ; Maida from Klamath
{181}{}{沙贾}                          # KCSajag.int     ; Sajag from Klamath
{182}{}{莎丽}                          # KCSally.int     ; Sally from Klamath
{183}{}{史麦力}                         # KCSmiley.int    ; Smiley from Klamath
{184}{}{珍妮}                          # KCJenny.int     ; Jenny from Klamath
{185}{}{史林}                           # KCSlim.int      ; Slim from Klamath
{186}{}{托尔}                           # KCTorr.int      ; Torr from Klamath
{187}{}{丹顿}                         # KCDunton.int    ; Dunton from Klamath
{188}{}{公民}                        # VCCrtCit.int    ; Vault City Courtyard Citizen
{189}{}{旅行者}                       # VCCrtOut.int    ; Vault City Courtyard Outsider
{190}{}{地下掩体市卫兵}               # VCCrtGrd.int    ; Vault City Courtyard Guard
{191}{}{地下掩体市卫兵}               # VCInGrd.int     ; Vault City Inner Guard
{192}{}{史提夫}                          # VCSteve.int     ; Steve from Vault City
{193}{}{安迪尔}                         # VCAndy.int      ; Andy the Medic in the Central Vault City
{194}{}{地下掩体市卫兵}               # VCGatGrd.int    ; Vault City Main Gate Guard
{195}{}{裘伊医生}                       # VCDrTroy.int    ; Vault City Dr. Troy in the Vault
{196}{}{大黄狗}                     # KCYellow.int    ; Yellow Dog in Klamath
{197}{}{巴尔赛斯}                        # mcBaltha.int    ; Balthas in Modoc
{198}{}{孔尼洛斯}                      # mcCornel.int    ; Cornelius in Modoc
{199}{}{达宾}                          # mcDavin.int     ; Davin in Modoc
{200}{}{费尔}                         # mcFarrel.int    ; Farrel in Modoc
{201}{}{葛力斯韩}                        # mcGrisha.int    ; Grisham in Modoc
{202}{}{乔}                             # mcJo.int        ; Jo in Modoc
{203}{}{乔尼}                          # mcJonny.int     ; Jonny in Modoc
{204}{}{卡尔}                           # mcKarl.int      ; Karl in Modoc
{205}{}{拉帝}                         # mcLaddie.int    ; Laddie in Modoc
{206}{}{麦丽雅}                          # mcMiria.int     ; Miria in Modoc
{207}{}{保护者}                      # mcProtec.int    ; Protector in Modoc
{208}{}{萝丝}                           # mcRose.int      ; Rose in Modoc
{209}{}{比格}                         # mcVegeir.int    ; Vegeir in Modoc
{210}{}{爱德}                             # VCEd.int        ; Ed the Brahma dealer in Vault City
{211}{}{哈利}                          # VCHarry.int     ; Happy Harry the store keep in Vault City
{212}{}{史密斯太太}                     # VCFSmith.int    ; Mrs. Smith from Vault City (Farmer)
{213}{}{麦琳达}                        # VCMelind.int    ; Town Greeter Melinda, Vault City
{214}{}{蜥蜴猎人}                        # KCTrapr.int     ; Generic trapper in Klamath
{215}{}{史密斯先生}                      # VCMSmith.int    ; Mr. Smith from Vault City (Farmer)
{216}{}{史其夫}                         # VCSkeeve.int    ; Skeeve, sells fake passes to Vault City
{217}{}{葛列格理地方官}              # VCGreg.int      ; Proconsul Gregory of Vault City
{218}{}{南西护士}                    # VCNancy.int     ; Nurse Nancy in Vault City
{219}{}{蓝提尔}                         # VCRandal.int    ; Chief Admenities Officer of Vault City
{220}{}{黏液}                            # KTGoo.int       ; Toxic Goo in the rat caves (Klamath)
{221}{}{巴尔可斯}                         # VCBarkus.int    ; Barkus, Vault City Service Coordinator
{222}{}{村人}                       # VCGenVil.int    ; Generic Villager around Vault City
{223}{}{史塔克}                          # VCStark.int     ; Vault City Sargent Stark
{224}{}{地下掩体市卫兵}               # VCVltGrd.int    ; Guard for entrance into the Vault of VC
{225}{}{老乔}                        # VCOldJoe.int    ; Crazy Old Joe (Vault City)
{226}{}{康尔}                         # VCConnar.int    ; Connar from Vault City
{227}{}{华莱士}                        # VCWalace.int    ; Wallace the Customs Official (Vault City)
{228}{}{琳娜特}                        # VCLynett.int    ; First Citizen Lynette of Vault City
{229}{}{麦卡路}                        # VCMClure.int    ; Senior Council Member MCclure (Vault City)
{230}{}{变种鼠}                    # GCBrain.int     ; Intelligent rat in Gecko
{231}{}{费斯特}                         # GCFestus.int    ; Festering ghoul in Gecko
{232}{}{格登}                         # GCGordon.int    ; Ghoul with economic data in Gecko
{233}{}{韩克}                           # GCHank.int      ; Ghoul that monitors the reactor in Gecko
{234}{}{杰米}                         # GCJerem.int     ; Ghoul in charge of supply cabinet in Gecko
{235}{}{蓝尔皮}                          # GCLumpy.int     ; Watches the Brahmin and helps Skeeter
{236}{}{史盖特}                        # GCSkeetr.int    ; Gadgeteer in Gecko
{237}{}{祖可}                          # GCZomak.int     ; Muscle man for the Brain
{238}{}{伍兹}                           # GCWooz.int      ; Bar owner and Tragic player
{239}{}{廉尼}                          # GCLenny.int     ; Stuttering ghoul that can join party
{240}{}{僵尸卫兵}                    # GGCRDesk.int    ; Reactor Desk guard
{241}{}{僵尸工人}                   # GCRWorkr.int    ; Reactor worker
{242}{}{发光的工人}                 # GCRGlow.int     ; Reactor glowing one
{243}{}{僵尸卫兵}                    # GCRGuard.int    ; Reactor guard
{244}{}{机器人}                          # GCRRobot.int    ; Reactor robot
{245}{}{僵尸市民}                  # GCFolk.int      ; Townsfolk in Gecko
{246}{}{地图}                     # DepoLv1.int     ; Map script for Sierra Army Depot, Level 1
{247}{}{地图}                     # DepoLvA.int     ; Map script for Sierra Army Depot Underground
{248}{}{地图}                     # DepoLvB.int     ; Map script for Sierra. Underground B
{249}{}{安全机器人}                 # WCSecBot.int    ; Sierra Base, Security Robot (generic)
{250}{}{维修机器人}                   # WCRepBot.int    ; Sierra Base, Repair Robot (generic)
{251}{}{全息卡带}                       # WIEvcDsk.int    ; Sierra Base, Evacuation Holodisk
{252}{}{全息卡带}                       # WIMedDsk.int    ; Sierra Base, Medical Log 1 Holodisk
{253}{}{全息卡带}                       # WIExpDsk.int    ; Sierra Base, Experiment Log Holodisk
{254}{}{控制器}                       # WSTerm1A.int    ; Security Computer, Level 1 -- Sierra Base
{255}{}{控制器}                       # WSTerm1B.int    ; Security Systems, Level 1 -- Sierra Base
{256}{}{控制器}                       # WSTerm2A.int    ; Security Computer, Level 2 -- Sierra Base
{257}{}{控制器}                       # WSTerm2B.int    ; Security Systems, Level 2 -- Sierra Base
{258}{}{控制器}                       # WSTerm2C.int    ; Auto Repair System, Level 2 -- Sierra Base
{259}{}{控制器}                       # WSTerm3A.int    ; Security Computer, Level 3 -- Sierra Base
{260}{}{控制器}                       # WSTerm3B.int    ; Skynet Terminal, Level 3 -- Sierra Base
{261}{}{控制器}                       # WSTerm3C.int    ; Robobrain Activator, Level 3 -- Sierra Base
{262}{}{控制器}                       # WSTerm4A.int    ; Security Computer, Level 4 -- Sierra Base
{263}{}{控制器}                       # WSTerm4B.int    ; Organ Extractor, Level 4 -- Sierra Base
{264}{}{控制器}                       # WSTerm4C.int    ; BioStorage Computer, Level 4 -- Sierra Base
{265}{}{纸片}                          # WIPaswrd.int    ; Piece of paper with the password on it
{266}{}{度伯士兵}                  # WCDobbs.int     ; Private Dobbs, Sierra Army Depot
{267}{}{中央机器人}                      # WCBrnBot.int    ; Brain Bot in the Army Depot
{268}{}{电梯}                       # ZSElev01.int    ; Generic Elevator
{269}{}{电梯}                       # ZSElev02.int    ; Generic Elevator
{270}{}{上锁的盒子}                        # DITubBox.int    ; Tubby's box of inventory
{271}{}{上锁的盒子}                        # DIFlkBox.int    ; Flick's box of inventory
{272}{}{Tandi}                          # SHTandi.int     ; Tandi the talking head in the NCR2 area
{273}{}{刺针陷阱}                     # ATSrTrp0.int    ; Arroyo Spear Trap for Caves (50)
{274}{}{刺针陷阱}                     # ATSrTrp1.int    ; Arroyo Spear Trap for Caves (50)
{275}{}{刺针陷阱}                     # ATSrTrp2.int    ; Arroyo Spear Trap for Caves (50)
{276}{}{刺针陷阱}                     # ATSrTrp3.int    ; Arroyo Spear Trap for Caves (50)
{277}{}{刺针陷阱}                     # ATSrTrp4.int    ; Arroyo Spear Trap for Caves (50)
{278}{}{刺针陷阱}                     # ATSrTrp5.int    ; Arroyo Spear Trap for Caves (50)
{279}{}{刺针陷阱}                     # ATSrTrp6.int    ; Arroyo Spear Trap for Caves (50)
{280}{}{刺针陷阱}                     # ATSrTrp7.int    ; Arroyo Spear Trap for Caves (50)
{281}{}{刺针陷阱}                     # ATSrTrp8.int    ; Arroyo Spear Trap for Caves (50)
{282}{}{刺针陷阱}                     # ATSrTrp9.int    ; Arroyo Spear Trap for Caves (50)
{283}{}{刺针陷阱}                     # ATSrTrpA.int    ; Arroyo Spear Trap for Caves (50)
{284}{}{刺针陷阱}                     # ATSrTrpB.int    ; Arroyo Spear Trap for Caves (50)
{285}{}{刺针陷阱}                     # ATSrTrpC.int    ; Arroyo Spear Trap for Caves (50)
{286}{}{刺针陷阱}                     # ATSrTrpD.int    ; Arroyo Spear Trap for Caves (50)
{287}{}{刺针陷阱}                     # ATSrTrpE.int    ; Arroyo Spear Trap for Caves (50)
{288}{}{刺针陷阱}                     # ATSrTrpF.int    ; Arroyo Spear Trap for Caves (50)
{289}{}{鬼山洞一}                 # GstCav1.int     ; Modoc Ghost Cave 1
{290}{}{鬼山洞二}                 # GstCav2.int     ; Modoc Ghost Cave 2
{291}{}{鬼农场}                     # GstFarm.int     ; Modoc Ghost Farm
{292}{}{摩多克城牧场}            # ModBrah.int     ; Modoc Brahmin Field
{293}{}{摩多克城花园}                   # ModGard.int     ; Modoc Garden
{294}{}{摩多克城旅店}                      # ModInn.int      ; Modoc Inn
{295}{}{摩多克城总干线}                     # ModMain.int     ; Modoc Main
{296}{}{摩多克城!#&^}                     # ModShit.int     ; Modoc under the shitter
{297}{}{摩多克水井}                       # ModWell.int     ; Modoc Well
{298}{}{新加州共和国第二区}                     # ncr2.int        ; NCR area 2
{299}{}{阿罗由花园}                 # ArGarden.int    ; Arroyo Gardens map script
{300}{}{蜥蜴}                          # ACGecko.int     ; generic Gecko creature
{301}{}{布拉克花}                    # AIBroc.int      ; Arroyo Broc Flower
{302}{}{山德根}                    # AIXander.int    ; Arroyo Xander Root
{303}{}{双头牛}                        # ZCBrahmn.int    ; Generic Brahmin
{304}{}{巴尔塞克之妻}                   # mcBalWif.int    ; Modoc Balthas wife
{305}{}{双头牛}                        # mcBrahmn.int    ; Modoc brahmin
{306}{}{野狗}                       # mcAtkDog.int    ; Modoc Attack Dog
{307}{}{石头}                          # miDclRks.int    ; Modoc Rocks in front of the death claw cage
{308}{}{石头}                          # miShtRks.int    ; Modoc Rocks under the shitter
{309}{}{保险箱}                      # miWalSfe.int    ; Modoc Farrel's wall safe
{310}{}{钱袋}                       # miCoinBg.int    ; Modoc Coin bags at the bottom of the well
{311}{}{厕所}                         # miToilet.int    ; ; Modoc Toliet
{312}{}{箱子}                            # miLstFnd.int    ; Modoc Lost and Found at Rose's
{313}{}{乔登}                         # ACJordan.int    ; Jordan. Trains player in Melee
{314}{}{莫丽姑妈}                    # ACMorlis.int    ; Aunt Morlis. Has flint to give player
{315}{}{卢卡斯}                          # ACFist.int      ; Standing Fist. Trains player in Unarmed
{316}{}{费尔格斯}                        # ACEric.int      ; Whiny person asking to fix the well
{317}{}{井}                           # ASWell.int      ; Arroyo Well. It's broken. Fix w/ Repair
{318}{}{甘德}                        # OCGrutha.int    ; Vault 13 Gruthar Deathclaw leader
{319}{}{地图}                     # Kladwtwn.int    ; Map script for Klamath Downtown
{320}{}{史盖特}                         # SCSkeete.int    ; Doofus dialog script for NCR Entrance area
{321}{}{那多儿}                          # ACNagor.int     ; You cousin who has lost his dog
{322}{}{飞烟}                          # ACDog.int       ; Nagor's dog Smoke
{323}{}{新加州共和国第一区}                     # Ncr1.int        ; Ncr area 1 map
{324}{}{新加州共和国第三区}                     # Ncr3.int        ; Ncr area 3 map
{325}{}{新加州共和国第四}                     # Ncr4.int        ; Ncr area 4 map
{326}{}{新加州共和国入口}              # Ncrent.int      ; Ncr area Entrance map
{327}{}{麦卡}                          # SCMikey.int     ; NCR Lizard Dealer
{328}{}{麦卡的箱子}                    # SIMbox.int      ; NCR Mikey's inventory box. (off Screen)
{329}{}{发射器}                        # WSEmit1a.int    ; Emitter, Level 1, Section A   (Sierra Base)
{330}{}{发射器}                        # WSEmit1b.int    ; Emitter, Level 1, Section B   (Sierra Base)
{331}{}{发射器}                        # WSEmit1c.int    ; Emitter, Level 1, Section C   (Sierra Base)
{332}{}{发射器}                        # WSEmit1d.int    ; Emitter, Level 1, Section D   (Sierra Base)
{333}{}{发射器}                        # WSEmit1e.int    ; Emitter, Level 1, Section E   (Sierra Base)
{334}{}{发射器}                        # WSEmit2a.int    ; Emitter, Level 2, Section A   (Sierra Base)
{335}{}{发射器}                        # WSEmit2b.int    ; Emitter, Level 2, Section B   (Sierra Base)
{336}{}{发射器}                        # WSEmit2c.int    ; Emitter, Level 2, Section C   (Sierra Base)
{337}{}{发射器}                        # WSEmit2d.int    ; Emitter, Level 2, Section D   (Sierra Base)
{338}{}{发射器}                        # WSEmit3a.int    ; Emitter, Level 3, Section A   (Sierra Base)
{339}{}{发射器}                        # WSEmit3b.int    ; Emitter, Level 3, Section B   (Sierra Base)
{340}{}{力场}                    # WSFeld1a.int    ; F. Field, Level 1, Section A   (Sierra Base)
{341}{}{力场}                    # WSFeld1b.int    ; F. Field, Level 1, Section B   (Sierra Base)
{342}{}{力场}                    # WSFeld1c.int    ; F. Field, Level 1, Section C   (Sierra Base)
{343}{}{力场}                    # WSFeld1d.int    ; F. Field, Level 1, Section D   (Sierra Base)
{344}{}{力场}                    # WSFeld1e.int    ; F. Field, Level 1, Section E   (Sierra Base)
{345}{}{力场}                    # WSFeld2a.int    ; F. Field, Level 2, Section A   (Sierra Base)
{346}{}{力场}                    # WSFeld2b.int    ; F. Field, Level 2, Section B   (Sierra Base)
{347}{}{力场}                    # WSFeld2c.int    ; F. Field, Level 2, Section C   (Sierra Base)
{348}{}{力场}                    # WSFeld2d.int    ; F. Field, Level 2, Section D   (Sierra Base)
{349}{}{力场}                    # WSFeld3a.int    ; F. Field, Level 3, Section A   (Sierra Base)
{350}{}{力场}                    # WSFeld3b.int    ; F. Field, Level 3, Section B   (Sierra Base)
{351}{}{警报器}                         # WSKlaxon.int    ; Changes lights to Flashing w/ Sierra on Alert
{352}{}{霸斯特}                         # SCBuster.int    ; Buster gun dealer at NCR entrance
{353}{}{书架}                      # SIShelf1.int    ; Busters shelves where items are kept
{354}{}{书架}                      # SIShelf2.int    ; Busters shelves where items are kept
{355}{}{书架}                      # SIShelf3.int    ; Busters shelves where items are kept
{356}{}{歹徒}                         # ECRaider.int    ; Random Encounter Raider
{357}{}{平民}                        # ECPeasnt.int    ; Random Encounter Peasant
{358}{}{商人}                       # ECMrchnt.int    ; Random Encounter Merchant
{359}{}{士兵}                          # ECGuard.int     ; Random Encounter Guard
{360}{}{客人}                 # SCRawpat.int    ; Rawhide patron in NCR Entrance
{361}{}{地板}                          # WTElFlr2.int    ; Electric Floor on Level 2 Sierra Base
{362}{}{电浆陷阱}                    # WTPlTrp0.int    ; Plasma Trap for Sierra Base(-30)
{363}{}{电浆陷阱}                    # WTPlTrp1.int    ; Plasma Trap for Sierra Base(-30)
{364}{}{控制器}                       # WSPwrDwn.int    ; Power Switch for the Sierra Base
{365}{}{布告栏}                 # KSBboard.int    ; Klamath bulletin board
{366}{}{大门}                           # ASCrlDr.int     ; Arroyo Corral Gate
{367}{}{黏液}                            # ATGoo.int       ; Goo in the Garden Map
{368}{}{门}                           # KSCVDoor.int    ; Door in Klamath Rat Caves
{369}{}{门}                           # KSMalldr.int    ; Door in Klamall..get key from Slim or Dog
{370}{}{}                          # ZCGecko.int     ; Generic gecko
{371}{}{}                   # ZCLGecko.int    ; Generic Golden Gecko
{372}{}{地图}                     # 2ndSt.int       ; 2nd Street Map Script
{373}{}{地图}                     # ChopShop.int    ; Chop Shop Map Script
{374}{}{地图}                     # GeckPwpl.int    ; Gecko Power Plant Map Script
{375}{}{地图}                     # GeckTunl.int    ; Gecko Tunnels Map Script
{376}{}{地图}                     # KlaCnyn.int     ; Klamath Canyon Map Script
{377}{}{地图}                     # MBase12.int     ; Military Base Level 1,2 Map Script
{378}{}{地图}                     # MBase34.int     ; Military Base Level 3,4 Map Script
{379}{}{地图}                     # MBClose.int     ; Military Base Closed Map Script
{380}{}{地图}                     # ModShit.int     ; Map Script for Modoc Shitter
{381}{}{地图}                     # NCR1.int        ; Map Script for NCR1
{382}{}{地图}                     # NCR2.int        ; Map Script for NCR2
{383}{}{地图}                     # NCR3.int        ; Map Script for NCR3
{384}{}{地图}                     # NCR4.int        ; Map Script for NCR4
{385}{}{地图}                     # NCREx.int       ; Map Script for NCR Exit
{386}{}{地图}                     # Stable.int      ; Map Script for Stables
{387}{}{地图}                     # V13_Orig.int    ; Map Script for Original Vault 13
{388}{}{地图}                     # V13Ent.int      ; Map Script for Vault 13 Entrance
{389}{}{地图}                     # V15_Orig.int    ; Map Script for Original Vault 15
{390}{}{地图}                     # V15Ent.int      ; Map Script for Vault 15 Entrance
{391}{}{地图}                     # Vault13.int     ; Map Script for Vault 13
{392}{}{地图}                     # Vault15.int     ; Map Script for Vault 15
{393}{}{地图}                     # VaultNec.int    ; Map Script for Necropolis Vault
{394}{}{地图}                     # VCtyVlt.int     ; Map Script for Vault City Vault
{395}{}{地图}                     # Virgin.int      ; Map Script for Virgin (these still exist?)
{396}{}{蒸馏器}                          # Kstill.int      ; Script for still in Klamath
{397}{}{酒吧顾客}                   # Kcggcust.int    ; Script for Klamath golden gecko customer
{398}{}{酒吧顾客}                   # Kcbhcust.int    ; Script for Klamath buckner house customer
{399}{}{沃尔斯}                         # SCVortis.int    ; Script for Vortis slave pen dude in NCR entrance
{400}{}{澡堂服务生}                 # Kcbgirl.int     ; Script for Klamath bath girl
{401}{}{奴隶}                         # SCSlaves.int    ; Script for NCR Entrance slaves
{402}{}{辐射蝎}                       # Kcscorp.int     ; Script for Klamath scorpions on the graze map
{403}{}{双头牛}                        # Kcbrahmn.int    ; Script for Klamath brahmin on the graze map
{404}{}{车}                            # ZSDrvCar.int    ; Drivable Car for the player
{405}{}{桌子}                          # diVicTbl.int    ; Den, table that Vic works at
{406}{}{地图}                     # Klagraz.int     ; Map Script for Klamath graze map
{407}{}{地图}                     # CarDesrt.int    ; Car Out of Gas Desert Map
{408}{}{地图}                     # GeckSetl.int    ; Map Script for Gecko Settlement
{409}{}{地图}                     # VCtyCtyd.int    ; Map Script for Vault City Courtyard
{410}{}{可维嘉}                        # Kscorveg.int    ; Klamath broken car with fuel injection
{411}{}{地图}                     # KlaToxCv.int    ; Klamath Toxic Caves  Map Script
{412}{}{铁门}                     # SISlvdor.int    ; Slave pen door in NCR Entrance
{413}{}{地图}                     # RndDsrt.int     ; Random Encounter Desert Map Script
{414}{}{地图}                     # RndCoast.int    ; Random Encounter Coast Map Script
{415}{}{地图}                     # RndMnt.int      ; Random Encounter Mountain Map Script
{416}{}{上锁的盒子}                        # Kidbox.int      ; Klamath dunton inventory box
{417}{}{上锁的盒子}                        # Kibbox.int      ; Klamath buckner inventory box
{418}{}{上锁的盒子}                        # Kisbox.int      ; Klamath sajag inventory box
{419}{}{拉契}                          # SCRatch.int     ; Ncr entrance JUNK dealer
{420}{}{拳击手}                          # ncBoxer.int     ; New Reno Generic Boxer
{421}{}{迈可．麦尼力}                  # ncMcKnee.int    ; New Reno Mike McKneely
{422}{}{伊凡．好莱菲}                 # ncHollyf.int    ; New Reno Evan Hollyfeld
{423}{}{割碎机}                     # ncTyson.int     ; New Reno Mike Tyson
{424}{}{科学家}                      # ncScient.int    ; New Reno Generic Scientist
{425}{}{麦尔科}                           # SCMerk.int      ; Merk an NCR mob type guy
{426}{}{拳击迷}                            # ncBoxFan.int    ; New Reno Boxing Fan
{427}{}{贩毒者}                    # ncDrgDlr.int    ; New Reno Drug Dealer
{428}{}{赌客}                  # ncCasPat.int    ; New Reno Casino Patron
{429}{}{皮条客}                           # ncPimp.int      ; New Reno Generic Pimp
{430}{}{吸毒者}                         # ncJunkie.int    ; New Reno Generic Junkie
{431}{}{家具}                      # stuff.int       ; signals critters on steal attempt
{432}{}{地板}                          # trespass.int    ; same as stuff only for an area
{433}{}{格朗特}                         # ATDeath.int     ; Spatial telling the player about Nagor dead
{434}{}{全息卡带}                       # SIFakhlo.int    ; Fake holodisk you get from Merk in NCR.
{435}{}{廉尼}                          # SCLenny.int     ; Lenny a guy in NCR Entrance
{436}{}{箱子}                            # SCPtbox.int     ; Players temp box to hold his stuff for the fight with lenny
{437}{}{妓女}                     # ncProsti.int    ; New Reno Prostitute with billions of messages
{438}{}{奴隶}                          # ncSlave.int     ; New Reno Slaves
{439}{}{瑞可}                           # ncRico.int      ; New Reno Rico, Monte's thug
{440}{}{AV女明星}                   # ncActres.int    ; New Reno Porn Actress
{441}{}{临时演员}                        # ncFluffe.int    ; New Reno Porn Fluffer/Extra
{442}{}{地图}                     # Klacanyn.int    ; Map script for Klamath Canyon
{443}{}{狼}                           # ECWlfPck.int    ; Military Base Wolf Pack
{444}{}{发电机}                      # ESPwrGen.int    ; Military Base Power Generator
{445}{}{门}                           # ESLkDor.int     ; Military Base Locked Door (-30)
{446}{}{超级变种人}                   # ECGenMut.int    ; Military Base Generic Mutant
{447}{}{沙尔瓦多的手下}                # ncSalMen.int    ; New Reno Salvatore's Men
{448}{}{彼希的手下}                   # ncBisMen.int    ; New Reno Bishop's Men
{449}{}{莫丁诺的手下}                  # ncMorMen.int    ; New Reno Mordino's Men
{450}{}{莱特的孩子}                 # ncWriTee.int    ; New Reno Wright's Sons & Daughters
{451}{}{赌场保镳}                 # ncCasBou.int    ; New Reno Generic Casino Bouncer
{452}{}{麦拉}                           # SCMira.int      ; NCR entrance bartender
{453}{}{新里诺处女街}         # NewR1.int       ; New Reno Map Virgin Street
{454}{}{新里诺第二街}            # NewR2.int       ; New Reno Map 2nd Street
{455}{}{新里诺商业区}        # NewR3.int       ; New Reno Map Commercial Row
{456}{}{新里诺东区}             # NewR4.int       ; New Reno Map East Side
{457}{}{新里诺马棚}               # NewRSt.int      ; New Reno Map Stables
{458}{}{新里诺肉店}             # NewRCS.int      ; New Reno Map Chop Shop
{459}{}{新里诺葛洛沙}              # NewRGo.int      ; New Reno Map Gologtha
{460}{}{新里诺彼希的地下室}       # NewRBa.int      ; New Reno Map Bishop Basement
{461}{}{全息卡带}                       # EIOutDsk.int    ; Military Base Holodisk (Outside)
{462}{}{全息卡带}                       # EILv1Dsk.int    ; Military Base Holodisk (Level 1)
{463}{}{全息卡带}                       # EILv2Dsk.int    ; Military Base Holodisk (Level 2)
{464}{}{全息卡带}                       # EILv3Dsk.int    ; Military Base Holodisk (Level 3)
{465}{}{全息卡带}                       # EILv4Dsk.int    ; Military Base Holodisk (Level 4)
{466}{}{士兵}                          # SCGteGrd.int    ; Ncr gate guard
{467}{}{矿车}                      # ESMinCrt.int    ; Military Base Mine Cart to explode on door
{468}{}{麦尔开}                       # ECMelchr.int    ; Melchoir the Magnificent (pseudo-mage)
{469}{}{变种野兽}                  # ECMutRat.int    ; Mutated Rats in Military Base
{470}{}{FEV 黏液}                        # ETGoo.int       ; FEV Goo in the Military Base
{471}{}{卫兵队长}                  # SCGGCap.int     ; NCR Entrance Gate guard captain
{472}{}{奴隶工头}                 # SCslvovr.int    ; NCR Entrance slave overseer
{473}{}{麦尔开的宠物}                 # ECMelPet.int    ; Melchior's Pets
{474}{}{奴隶商的卫兵}                   # SCslvgrd.int    ; Slaver Guard in NCR Entrance
{475}{}{门}                           # SIclsdor.int    ; Closing door
{476}{}{控制器}                       # SITerm.int      ; Slave pen terminals NCR Entrance
{477}{}{吃角子老虎}                   # ziSlots.int     ; Generic Slot Machine
{478}{}{小孩}                          # ncWriChi.int    ; New Wright children
{479}{}{西比}                           # ncSheb.int      ; New Reno Sheb
{480}{}{士兵}                          # SCMrkGrd.int    ; Merk's guards NCR Entrance and council
{481}{}{发射器}                        # SIEmtr.int      ; Emitter in NCR Entrance
{482}{}{力场}                    # SIFField.int    ; Force field in NCR Entrance
{483}{}{史力克}                          # Kcsulik.int     ; Sulik from Klamath
{484}{}{亨利医生}                      # SCHenry.int     ; Henry NCR Entrance
{485}{}{士兵}                          # SCCarGrd.int    ; Carlson's guards NCR2
{486}{}{卡洛森卫兵攻击}          # STCaratk.int    ; Carlson's guards attack spatial
{487}{}{卡洛森守门兵}          # SCcgtgrd.int    ; Carlson's gate Guards
{488}{}{囚犯}                       # VCOutPrs.int    ; Vault City Outsider Prisoner (Generic)
{489}{}{囚犯}                       # VCCitPrs.int    ; Vault City Citizen Prisoner (Generic)
{490}{}{公民}                        # VCGenFam.int    ; Vault City Generic Family
{491}{}{阿曼提斯的助手}                  # VCAmAid.int     ; Vault City Amenities Aid
{492}{}{接应卫兵}                     # GCRDesk.int     ; Gecko Reactor Desk Guard
{493}{}{僵尸工人}                   # GCRGhoul.int    ; Gecko Reactor Ghoul Worker
{494}{}{发光的人}                    # GCRGlow.int     ; Gecko Glowing One
{495}{}{僵尸卫兵}                    # GCRGuard.int    ; Gecko Red Door Guard
{496}{}{机器人}                          # GCRobot.int     ; Gecko Reactor Robot
{497}{}{僵尸}                          # GCFolk.int      ; Gecko Townsfolk
{498}{}{朝拜者}                     # GCWorshp.int    ; Gecko Worshippers
{499}{}{哈欧}                         # GCHarold.int    ; Harold in Gecko
{500}{}{警卫}                        # GCPACOff.int    ; Gecko Powered Armor Com Officer
{501}{}{多多}                           # SCToto.int      ; Toto hlper bot in NCR 1
{502}{}{德露西}                        # SCDoroth.int    ; Dorothy Repair chick in NCR 1
{503}{}{镇民}                    # ncPerson.int    ; New Reno Generic Townsperson/Citizen
{504}{}{僵尸卫兵}                    # GCYGuard.int    ; Gecko Yellow Door Guard
{505}{}{僵尸卫兵}                    # GCGuard.int     ; Gecko Generic Guard
{506}{}{刚德}                           # SCGond.int      ; Ranger Guard, NCR 1
{507}{}{杜普}                          # SCDuppo.int     ; Stockman's yard store owner
{508}{}{东西}                          # SIdtbl.int      ; Duppo's tables in shop
{509}{}{包伯}                            # SCsalbob.int    ; Salt Beef Bob NCR 3
{510}{}{赌场侍女}                    # ziDceGrl.int    ; Generic Casino Girl with Dice Game
{511}{}{赌场侍女}                    # niDceGrl.int    ; New Reno Casino Girl with Dice Game
{512}{}{魔幻的八号球}               # zi8Ball.int     ; EPA Magic 8 Ball
{513}{}{双头牛}                        # ncAngBra.int    ; New Reno Angry Brahmin
{514}{}{吃角子老虎}                   # niMcGSlt.int    ; New Reno McGee's Slot Machine
{515}{}{老人麦可基}                  # ncMcGee.int     ; New Reno Old Man (Bobby) McGee
{516}{}{三张牌定胜负}               # nc3Monte.int    ; New Reno Three Card Monte
{517}{}{阿尔基南}                       # ncAlgern.int    ; New Reno Algernon
{518}{}{比尔}                           # ncBill .int     ; New Reno Bill (Trees Lounge)
{519}{}{保镳}                      # ncBisGrd.int    ; New Reno Bishop's Bodyguards
{520}{}{约翰彼希}                    # ncBishop.int    ; New Reno John Bishop
{521}{}{赌场机器}                 # niCasMac.int    ; New Reno Casino Machine
{522}{}{机器行员工}                  # ncChpBoy.int    ; New Reno Chop Shop Boys
{523}{}{克里斯．莱特}                   # ncChrWri.int    ; New Reno Chris Wright
{524}{}{寇弟}                           # ncCody .int     ; New Reno Cody
{525}{}{克里西根兄弟}                # ncCorBro.int    ; New Reno Corsican Bothers
{526}{}{爱尔及}                       # ncEldrid.int    ; New Reno Eldridge
{527}{}{依希．莱特}                   # ncEthWri.int    ; New Reno Ethyl Wright
{528}{}{塔里神父}                   # ncFTully.int    ; New Reno Father Tully
{529}{}{可哥迪多}               # ncHumper.int    ; New Reno HumperdumperDIDO
{530}{}{基苏．莫丁诺}             # ncLilJes.int    ; New Reno Lil' Jesus Mordino
{531}{}{吉米Ｊ}                 # ncJimmyJ.int    ; New Reno Jagged Jimmy J
{532}{}{基斯．莱特}                   # ncKeiWri.int    ; New Reno Keith Wright
{533}{}{理．安．彼希}                # ncLABish.int    ; New Reno Lee Anne Bishop
{534}{}{漂亮男孩洛依德}               # ncLloyd.int     ; New Reno Pretty Boy Lloyd
{535}{}{梅森}                          # ncMason.int     ; New Reno Mason
{536}{}{士兵}                          # ncMyrGrd.int    ; New Reno Myron's Guards
{537}{}{麦朗}                          # nhMyron.int     ; New Reno Myron (Talking Head)
{538}{}{妮基}                          # ncNikki.int     ; New Reno Darlin' Nikki
{539}{}{奥薇尔．莱特}                 # ncOrvill.int    ; New Reno Orville Wright
{540}{}{老板}                       # ncPitBos.int    ; New Reno Generic Pit Boss
{541}{}{洛尼司可}         # ncRenesc.int    ; New Reno Renesco the Rocket-Man
{542}{}{研究员}                     # ncResear.int    ; New Reno Stables Researcher
{543}{}{沙尔瓦多老大}                 # ncSalvat.int    ; New Reno Boss Salvatore
{544}{}{史度特．理特}                  # ncStuLit.int    ; New Reno Stuart Little (Agent)
{545}{}{Ｔ雷}                          # ncTRay .int     ; New Reno T-Ray
{546}{}{婊子}                          # ncBitch.int     ; New Reno Corsican Brothers Bitches
{547}{}{莱特的小孩}                   # ncWriPly.int    ; New Reno Wright Children Playing
{548}{}{新加州共和国员警}                     # SCCop.int       ; NCR cop
{549}{}{奥斯瓦德}                         # SCOswald.int  ; Raider Oswald captive NCR 1
{550}{}{达士地}                          # SCDusty.int     ; Dusty bartender in NCR 1
{551}{}{朱尔斯}                          # ncJules.int     ; New Reno Jules
{552}{}{凯蒂小姐}                     # ncKitty.int     ; New Reno Miss Kitty
{553}{}{酒保}                      # ncBarten.int    ; New Reno Bartender
{554}{}{卡尔副手}                    # SCKarl.int      ; NCR Deputy
{555}{}{牢门}                      # SIKdoor.int     ; NCR Cell door
{556}{}{大莫丁诺}              # ncBigJes.int    ; New Reno Big Jesus Mordino
{557}{}{荷斯}                           # SCHoss.int      ; Hoss, bully NCR 1 map
{558}{}{变型糖浆}                # SIMserum.int    ; Mutagenic Serum
{559}{}{箱子}                            # niSalBox.int    ; New Reno Salvatore Bartender Shop Inventory
{560}{}{箱子}                            # niMorBox.int    ; New Reno Mordino Bartender Shop Inventory
{561}{}{箱子}                            # niBisBox.int    ; New Reno Bishop Bartender Shop Inventory
{562}{}{箱子}                            # niTmpBox.int    ; New Reno Personal Inventory Swap Box
{563}{}{朱伯利医生}                 # SCDocJub.int    ; Doctor Jubilee NCR Map 1
{564}{}{门}                           # GSYDoor.int     ; Yellow Door in Gecko Reactor
{565}{}{门}                           # GSRDoor.int     ; Red Door in Gecko Reactor
{566}{}{书柜}                       # SIdshelf.int    ; Bookshelf for the Doc NCR 1
{567}{}{杜门警长}                 # SCsherif.int    ; Sheriff in NCR map 1
{568}{}{依丽莎}                          # SCElise.int     ; Elise in NCR map 1 ranger leader chick
{569}{}{牧场工人}                     # SCwrHand.int    ; Westin Ranch Hand NCR 3
{570}{}{菲利}                          # SCFelix.int     ; Westin's forman on NCR 3
{571}{}{卫斯丁}                         # SCWestin.int    ; Westin big dude on NCR 3
{572}{}{蓝多}                          # SCRondo.int     ; Rondo Ranger NCR 1
{573}{}{机器狗}                        # SCRobo.int      ; Robodog NCR 1
{574}{}{楼梯}                         # NIBissta.int    ; New Reno Bishop's stairs
{575}{}{哈尔}                            # SCHal.int       ; Hal, Drive Leader
{576}{}{甘德}                        # SCGunthr.int    ; Gunther Tandi's assistant NCR 2
{577}{}{双头牛}                        # ECCrtBra.int    ; Random Encounter Brahmin for carts
{578}{}{沙漠商队首领}                 # ECCvnMst.int    ; Random Encounter Caravan Master
{579}{}{沙漠商队驾驶}                 # ECCvnDrv.int    ; Random Encounter Caravan Driver
{580}{}{沙漠商队卫兵}                  # ECCvnGrd.int    ; Random Encounter Caravan Guard
{581}{}{歹徒}                         # ECRadLdr.int    ; Random Encounter Raider Leader
{582}{}{帮派份子}                        # ECMobstr.int    ; Random Encounter Mobster (Outside New Reno)
{583}{}{猎人}                         # ECHntLdr.int    ; Random Encoutner Hunting Party Leader
{584}{}{猎人}                         # ECHunter.int    ; Random Encounter Hunting Party
{585}{}{巡警}                         # ECRanger.int    ; Random Encounter NCR Rangers (Patrol)
{586}{}{佣兵}                      # ECMercs.int     ; Random Encounter Mercenaries
{587}{}{佣兵}                      # ECMrcLdr.int    ; Random Encounter Mercenary Leader
{588}{}{歹徒}                         # ECRadGrp.int    ; Random Encounter Raider Party
{589}{}{沙漠商队驾驶}                 # ECRndDrv.int    ; Random Encounter Other Caravan Driver
{590}{}{沙漠商队卫兵}                  # ECRndGrd.int    ; Random Encounter Other Caravan Guard
{591}{}{巡逻兵}                   # ECVltPat.int    ; Random Encounter Vault City Patrols
{592}{}{巡逻兵队长}                 # ECVltCpt.int    ; Random Encounter Vault City Patrol Capt.
{593}{}{农夫}                         # ECFarmer.int    ; Random Encounter Farmer
{594}{}{双头牛}                        # ECBraHrd.int    ; Random Encounter Brahmin Herd
{595}{}{双头牛}                        # ECLedBra.int    ; Random Encounter Lead Brahmin
{596}{}{旅行者}                       # ECTrvlr.int     ; Random Encounter Traveler
{597}{}{巡逻兵}                   # ECGhlPat.int    ; Random Encounter Ghoul Patrol
{598}{}{巡逻兵队长}                 # ECGhlCpt.int    ; Random Encounter Ghoul Patrol Capt.
{599}{}{巡逻兵}                   # ECMutPat.int    ; Random Encounter Mutant Patrol
{600}{}{巡逻兵队长}                 # ECMutCpt.int    ; Random Encounter Mutant Patrol Capt.
{601}{}{双头牛驾驶}                 # ECBraDrv.int    ; Random Encounter Brahmin Driver
{602}{}{偷牛贼}                        # ECBraRst.int    ; Random Encounter Brahmin Rustler
{603}{}{流浪汉}                       # ECSquatr.int    ; Random Encounter Squatters
{604}{}{废奴主义者}                   # ECAbolst.int    ; Random Encounter Abolitionist
{605}{}{私贩酒者}                     # ECMonShn.int    ; Random Encounter Moonshine Runner
{606}{}{超级变种人}                   # ECRogMut.int    ; Random Encounter Rogue Super Mutants
{607}{}{渔夫}                      # ECFshrmn.int    ; Random Encounter Fisherman
{608}{}{奴隶商人}                         # ECSlaver.int    ; Random Encounter Slaver
{609}{}{蜥蜴猎人}                        # ECTrappr.int    ; Random Encounter Trapper
{610}{}{卡洛森的小孩}                  # SCCarkid.int    ; Carlson's kid NCR map 2
{611}{}{卡洛森}                        # SCCarlsn.int    ; Carlson NCR 2
{612}{}{}                               # Animfrv.int     ; Animate forever
{613}{}{杰克}                   # SCOfjack.int    ; Officer Jack NCR 1
{614}{}{受启蒙的人}            # SCEnlOne.int    ; The Enlightened One NCR 1
{615}{}{门}                           # diDoor.int      ; Den Auto Closing Door
{616}{}{电脑}                       # GsTerm.int      ; Gecko robot control terminal
{617}{}{双头牛}                         # SCBrahmn.int    ; NCR Map 4 Brahmin.
{618}{}{死亡爪}                      # SCDthcla.int    ; NCR Map 4 Deathclaw.
{619}{}{出口}                      # SIExit.int      ; NCR Map 4 Exit Grid control
{620}{}{电脑}                       # SSComp.int      ; NCR Map 1 computer terminal that blows up
{621}{}{费尔格斯}                        # SCFergus.int    ; NCR Map 2
{622}{}{爱瑞儿}                          # OCAriel.int     ; Vault 13 Ariel
{623}{}{菲妮美}                     # RCFannie.int    ; Fannie Mae the hooker in Redding
{624}{}{电脑控制台}              # OCComptr.int    ; Computer terminal in Vault 13
{625}{}{达莉雅}                          # OCDalia.int     ; Dalia in Vault 13
{626}{}{达尔}                            # OCDar.int       ; Dar Deathclaw guard Vault 13
{627}{}{达夫}                           # OCDave.int      ; Dave NPC in Vault 13
{628}{}{格登}                         # OCGordon.int    ; Gordon the shrine temple dude
{629}{}{倒闭标志}           # ziClosed.int    ; Generic "Out of Business" signs
{630}{}{反应炉控制机器}      # gsReactr.int    ; Script to animate reactor
{631}{}{吉米}                          # OCJimmy.int     ; Jimmy guy in computer room Vault 13
{632}{}{约瑟夫}                         # OCJoseph.int    ; The Doctor in Vault 13
{633}{}{麦特}                           # OCMatt.int      ; Matt prisonner in Vault 13
{634}{}{}                               # RCFitRat.int    ; Redding Fighting Molerats
{635}{}{地图}                     # RedMEnt.int     ; Redding Mine Entrance Map Script
{636}{}{第１３号避难所地图}                 # vault13.int     ; Vault13 map script
{637}{}{珊蒂}                          # OCSandy.int     ; Sandy Vault 13 child.
{638}{}{箱子}                            # ziTmpBox.int    ; Generic Temporary swap box
{639}{}{史恩}                         # OCThearn.int    ; Vault 13 Guard Thearn.
{640}{}{箱子}                            # miGriBox.int    ; Modoc Grisham Merchant box
{641}{}{箱子}                            # miJoBox.int     ; Modoc Jo Merchant box
{642}{}{比尔地斯}                         # OCValdis.int    ; Valdis guard in Vault 13
{643}{}{电脑控制台}              # OSvdrcmp.int    ; Door computer vault 13 entrance
{644}{}{铁锁柜}                   # OILocker.int    ; Metal locker in Vault 13
{645}{}{锁柜}                     # OIftlkr.int     ; Footlocker in Vault 13
{646}{}{死亡爪卫兵}                # OCgrunt.int     ; Generic Vault 13 Deathclaw guard
{647}{}{革力士}                          # OCGoris.int     ; Goris possible party NPC vault 13
{648}{}{箱子}                            # miBalBox.int    ; Modoc Balthas Merchant box
{649}{}{铁锁柜}                   # siLocker.int    ; Guard's lockers in NCR 1
{650}{}{作弊者}                        # Cheater.int     ; Cheater Character
{651}{}{第１５号避难所地图}                 # vault15.int     ; Vault 15 map script
{652}{}{费尔}                           # bcPhil.int      ; Phil the secret vault 15 entrance guard
{653}{}{比尔}                           # bcBill.int      ; Bill in Vault 15 Entrance
{654}{}{屠夫}                        # mcButchr.int    ; Slaughter house guys in Modoc
{655}{}{达莉雅}                          # bcDalia.int     ; Guard who guards a trail and shows up in v13
{656}{}{约翰}                           # bcJohn.int      ; Vault 15 guy entrance
{657}{}{琼斯}                          # BCJones.int     ; Vault 15 doctor
{658}{}{卡拉}                          # BCKarla.int     ; Karla Vault 15 guard.
{659}{}{第１５号避难所秘密入口地图}        # V15sent.int     ; Vault 15 secret entrance map
{660}{}{丽蓓嘉}                        # BCRebecc.int    ; Vault 15 Rebecca
{661}{}{门}                           # miDoor.int      ; Modoc Doors
{662}{}{死亡爪}                     # mcDthClw.int    ; Modoc Rose's "Chicken"
{663}{}{萝伯可}                        # bcRobert.int    ; Roberta Vault 15 Entrance
{664}{}{莎拉}                           # bcSara.int      ; Sara vault 15 Entrance
{665}{}{希克}                           # bcZeke.int      ; Zeke vault 15 Entrance mayor dude
{666}{}{双头牛}                        # bcBrahmn.int    ; Generic Brahmin in Vault15 Entrance
{667}{}{木门}                      # BiEntDr.int     ; Trapped Vault15 entrance door
{668}{}{可莉西}                        # BCCrissy.int    ; Crissy, Rebecca's daughter
{669}{}{达里安}                         # BCDarion.int    ; Big bad dude in Vault 15
{670}{}{达里安的卫兵}                 # BCDargrd.int    ; Darion's guard in Vault 15
{671}{}{达里安的狗}                   # BCDardog.int    ; Darion's dog in Vault 15
{672}{}{盖西迪}                        # VCCasidy.int    ; Cassidy the  bar person in Vault City
{673}{}{水井}                           # miWell.int      ; Modoc Well
{674}{}{地鼠}                       # mcMolRat.int    ; Modoc Shitter Mole Rat
{675}{}{双头牛肉}                  # miBraMea.int    ; Modoc Brahmin Chunks
{676}{}{双头牛}                        # mcKilBra.int    ; Modoc Slaughterhouse brahmin
{677}{}{电梯门}                  # bsElev.int      ; Elevator door in V15sent
{678}{}{狗}                            # mcKilDog.int    ; Modoc Dog that hangs out at the slaughter house
{679}{}{老鼠}                            # mcRat.int       ; Modoc Garden Rat
{680}{}{阳光点}                       # ziSunSpt.int    ; Generic Sun Spot
{681}{}{贝丝}                           # mcBess.int      ; Modoc Bess the Brahmin
{682}{}{箱子}                            # miJkyBox.int    ; Modoc Jerky box
{683}{}{骰子庄家}                   # zcCrpDel.int    ; Craps Dealer
{684}{}{第１５号避难所卫兵}                 # bcGenGrd.int    ; Vault 15 Khan Guard
{685}{}{溶渣}                           # mcSlag.int      ; Modoc Generic Slag
{686}{}{地毯}                            # mtRug.int       ; Modoc Spacial Script for Rug
{687}{}{小孩}                          # mcChild.int     ; Modoc Child
{688}{}{爱琳}                         # hcAileen.int    ; Aileen in Broken Hills
{689}{}{士兵}                          # hcBnkGrd.int    ; Bank Guard in Broken Hills
{690}{}{荷里代医生}                    # hcDoc.int       ; Doc in Broken Hills
{691}{}{追从者}                       # hcencha.int     ; Henchman A in Broken Hills
{692}{}{追从者}                       # hcenchb.int     ; Henchman B in Broken Hills
{693}{}{女人}                          # hcfemale.int    ; Female in Broken Hills
{694}{}{法蓝西斯}                        # hcFranci.int    ; Francis in Broken Hills
{695}{}{法兰克}                          # hcFrank.int     ; Frank in Broken Hills
{696}{}{僵尸}                          # hcGhoul.int     ; Ghoul in Broken Hills
{697}{}{丽莎}                            # hcLiz.int       ; Liz in Broken Hills
{698}{}{男人}                            # hcmale.int      ; Male in Broken Hills
{699}{}{曼森}                         # hcManson.int    ; Manson in Broken Hills
{700}{}{马可世}                         # hcMarcus.int    ; Marcus in Broken Hills
{701}{}{矿工}                          # hcMiners.int    ; Miners in Broken Hills
{702}{}{变种人}                         # hcMutant.int    ; Mutant in Broken Hills
{703}{}{比尔}                           # hcOutfit.int    ; Outfitter in Broken Hills
{704}{}{费尔}                           # hcPhil.int      ; Phil the bartender in Broken Hills
{705}{}{史提夫}                          # hcSteve.int     ; Steve in Broken Hills
{706}{}{上司}                     # hcSuper.int     ; Supervisor in Broken Hills
{707}{}{赛斯}                          # hcZaius.int     ; Zaius in Broken Hills
{708}{}{杰克伯}                          # hcJacob.int     ; Jacob in Broken Hills
{709}{}{化学实验用品}                  # hchems.int      ; Chemistry Set in Broken Hills
{710}{}{工具}                           # miGstPrp.int    ; Modoc Ghost Farm Prop
{711}{}{门}                           # bssdor1.int     ; Shack doors on V15sEnt map
{712}{}{电脑}                       # BSComp1.int     ; Library Computer Vault 15
{713}{}{查德}                           # hcchad.int      ; Chad from Broken Hills
{714}{}{胞子植物}                    # ECPlant.int     ; Random Encounter Spore Plant
{715}{}{}                               # ECGecko.int     ; Random Encounter Gecko
{716}{}{辐射蝎}                    # ECScorp.int     ; Random Encounter Scorpions
{717}{}{}                               # ECRat.int       ; Random Encounter Rats
{718}{}{战士}                        # ECWarPty.int    ; Random Encounter War Party
{719}{}{食人族}                       # ECCanibl.int    ; Random Encounter Cannibals
{720}{}{被逐出的人}                        # ECOutCst.int    ; Random Encounter Outcasts
{721}{}{圣人}                    # ECHlyPpl.int    ; Random Encounter Holy People
{722}{}{游牧者}                          # ECNomad.int     ; Random Encounter Nomads
{723}{}{无家可归的人}                # ECHomles.int    ; Random Encounter Homeless
{724}{}{土匪}                         # ECBandit.int    ; Random Encounter Bandit
{725}{}{强盗}                         # ECRobber.int    ; Random Encounter Robber
{726}{}{拦路强盗}                     # ECHiwymn.int    ; Random Encounter Highwaymen
{727}{}{奴隶商人}                         # ECSlvRun.int    ; Random Encounter Slavers on a Slave Run
{728}{}{奴隶}                          # ECSlave.int     ; Random Encounter Slaves
{729}{}{人}                        # ECRavPty.int    ; Random Encounter Rave Party
{730}{}{螳螂}                         # ECMantis.int    ; Random Encounter Mantis
{731}{}{双头牛}                        # ECBrahmn.int    ; Random Encounter Brahmin
{732}{}{狗}                            # ECWldDog.int    ; Random Encounter Wild Dogs
{733}{}{电脑}                       # BSComp2.int     ; Darion's computer terminal Vault15
{734}{}{电脑}                       # BSComp3.int     ; Force field computer terminal
{735}{}{电脑控制台}              # BSComp4.int     ; Force Field control computer by entrance Vault 15
{736}{}{电脑}                       # BSComp5.int     ; Computer at the Power area. Vault 15
{737}{}{发电机}                # BSPower.int     ; Power Generator in Vault 15
{738}{}{力场}                    # BSField.int     ; Force Field in Vault 15
{739}{}{平民}                        # mcPeasan.int    ; Modoc Peasant Person
{740}{}{发射器}                        # bsEmtr.int      ; Emitter in Vault 15
{741}{}{避难所门}                     # osv13dr.int     ; Vault 13 Door
{742}{}{安全门}                  # osDoor1.int     ; Vault 13 Door that shows deathclaws
{743}{}{遇到贝丝}                 # rndBess.int     ; Random Encounter for Bess outside of modoc
{744}{}{贝丝}                           # ECBess.int      ; Bess in Bess's Encounter (she's dead jim)
{745}{}{双头牛}                        # ECBesCow.int    ; One of the Brahmin in Bess's herd
{746}{}{安琪拉．彼希}                  # ncAngBis.int    ; New Reno Angela Bishop
{747}{}{汤米}              # ncTommy.int     ; New Reno Tommy the Balls (YEAH! OUR HERO)
{748}{}{保险箱}                           # niABisSf.int    ; New Reno Angela Bishop's Safe
{749}{}{保险箱}                           # niMrBSf.int     ; New Reno Mr. Bishop's Safe
{750}{}{保险箱}                           # niMrsBSf.int    ; New Reno Mrs. Bishop's Safe
{751}{}{保险箱}                           # niOWriSf.int    ; New Reno Orville Wright's Safe
{752}{}{坟墓}                          # niPriGrv.int    ; New Reno Pritchard's Grave
{753}{}{梳妆台}                        # niWridrs.int    ; New Reno Richard Wright's Dresser
{754}{}{坟墓}                          # niWriGrv.int    ; New Reno Righard Wright's Grave
{755}{}{蒸馏器}                          # niWriSti.int    ; New Reno Wright Stills
{756}{}{洛米洛兹}                        # ncRamire.int    ; New Reno Ramirez
{757}{}{山洞1乱数地图}    # cave01.int      ; Cave 1 Random Encounter Map
{758}{}{箱子}                            # niRenBox.int    ; New Reno Renesco Box
{759}{}{门}                           # niDoor.int      ; New Reno Door
{760}{}{山洞2乱数地图}    # cave02.int      ; Cave 2 Random Encounter Map
{761}{}{山洞3乱数地图}    # cave03.int      ; Cave 3 Random Encounter Map
{762}{}{山洞4乱数地图}    # cave04.int      ; Cave 4 Random Encounter Map
{763}{}{山洞２乱数地图}    # cave02.int      ; Cave 2 Random Encounter Map
{764}{}{门}                           # VIEntDor.int    ; Vault City Entrance Door
{765}{}{地图}                     # VCtyDwtn.int    ; Vault City Downtown Map script
{766}{}{陷阱门}                      # miTrpDor.int    ; Modoc Ghost Farm Trap Door
{767}{}{上锁的盒子}                        # Hilbox.int      ; Broken Hills Liz inventory box
{768}{}{房间}                           # ntLydRom.int    ; New Reno Lloyd Room
{769}{}{汤姆士．摩尔}                   # VCMoore.int     ; Thomas Moore from Vault City
{770}{}{门}                           # ZILckDor.int    ; Generic Locked Door (-20)
{771}{}{锁柜}                         # niLydBox.int    ; New Reno Lloyd's Loot Box
{772}{}{地下水道通道}                        # niManhol.int    ; New Reno Manhole to Lloyd's Loot
{773}{}{坟墓}                          # niLydGrv.int    ; New Reno Lloyd's Loot Grave
{774}{}{补给品卫兵}                   # VCSupGrd.int    ; Vault City Supply Guard Martin
{775}{}{地图}                     # broken1.int     ; Map Script for Broken Hills Map 1
{776}{}{地图}                     # rndexcow.int    ; Map Script for Low Luck encounter
{777}{}{疯牛}                    # eccowbmb.int    ; The cows that blow
{778}{}{汉克斯威尔}                      # RCHakes.int     ; Hakeswill from Redding
{779}{}{瑞丁城市中心}               # REDDown.int     ; Redding Downtown map script
{780}{}{地图}                     # BHRndDst.int    ; Broken Hills Caravan Desert Map
{781}{}{地图}                     # BHRndMtn.int    ; Broken Hills Caravan Mountain Map
{782}{}{卢}                            # RCLou.int       ; Lou from Redding
{783}{}{亚瑟}                         # ECArthur.int    ; Arthur the leader of the Special Encounter knights
{784}{}{罗宾}                          # ECRobin.int     ; Robin one of the Knights with Arthur
{785}{}{班地梅尔}                        # ECBedemi.int    ; Bedemir one of the Knights with Arthur
{786}{}{蓝瑟安特公爵}                  # ECSirLau.int    ; Sir Launcelot one of the Knights with Arthur
{787}{}{加拉韩德}                        # ECGalaha.int    ; Galahad one of the knights with Arthur
{788}{}{班．伟德}                       # RCWade.int      ; Ben Wade from Radding
{789}{}{阿沙巴士卡．狄克}                 # RCDick.int      ; Athabaska Dick from Redding
{790}{}{寡妇罗妮}                   # RCRooney.int    ; Widow Rooney from Redding
{791}{}{镇民}                    # RCGenPes.int    ; Generic Townsperson in Redding
{792}{}{史丹威尔}                       # RCStanwl.int    ; Stannwell from Redding
{793}{}{沙文力}                      # RCSavine.int    ; Savinelli from Redding
{794}{}{马琪}                          # RCMarge.int     ; Marge LeBarge from Redding
{795}{}{马德嘉士琪夫人}                 # RCModjes.int    ; Madam Modjeska from Redding
{796}{}{詹姆士．哈菲}                    # RCHoffy.int     ; James Hoffy, Caravan Master for Redding
{797}{}{地图}                     # Rndholy1.int    ; Random Encounter Holy Knights 1 map
{798}{}{派西}                          # ECPatsy.int     ; Arthur's horse HOLY 1 encounter
{799}{}{康克地}                       # ECConcor.int    ; Concord Launcelot's horse.
{800}{}{艾力克}                           # ECEric.int      ; Robin's horse
{801}{}{约翰}                           # ECJohn.int      ; Bedemir's horse
{802}{}{约瑟}                         # ECJoshua.int    ; Joshua Robin's minstrel
{803}{}{拉德}                         # miLadder.int    ; Modoc Shitter Ladder
{804}{}{大头}                       # ecBHead.int     ; Big Head special encounter
{805}{}{黑色英雄}                     # ecBlkHro.int    ; Black Hero model
{806}{}{红色女英雄}                    # ecRedHro.int    ; Red Heroine model
{807}{}{背景}                            # ecSet.int       ; Set in Cafe of Broken Dreams
{808}{}{坦蒂}                          # ecTandi.int     ; Tandi in Cafe of " "
{809}{}{白色英雄}                     # ecWhro1.int     ; White Hero Model 1 " " "
{810}{}{白色英雄}                     # ecWhro2.int     ; White Hero Model 2 " " "
{811}{}{白色女英雄}                  # ecWheon1.int    ; White Heroine Model 1
{812}{}{箱子}                            # NiJulBox.int    ; New Reno Jules Shop Inventory Box
{813}{}{箱子}                            # niEldBox.int    ; New Reno Eldridge Shop Box
{814}{}{箱子}                            # niEldBx2.int    ; New Reno Eldridge Shop Box (For Made Men)
{815}{}{地图}                     # rndholy2.int    ; Hi-Luck random Holy knight encounter 2
{816}{}{老鼠}                     # ECVorRat.int    ; Vorpal Rat for Holy Knight 2
{817}{}{狗}                            # ECPDog.int      ; Pariah Dog... not good to have following you around
{818}{}{演习上校}                 # CCDrill.int     ; Drill Seargant in Colusa/Nevarro
{819}{}{士兵}                          # CCGuard.int     ; Guard in Colusa/Nevarro
{820}{}{技术人员}                     # CCTech.int      ; Technician in Colusa/Nevarro
{821}{}{指挥官}                      # CCMandr.int     ; Commander in Colusa Nevarro
{822}{}{基斯}                          # CCChris.int     ; Chris the gas station attendant in Colusa
{823}{}{房间主管}                 # CCMaster.int    ; Quarter Master in Colusa/Nevarro
{824}{}{士兵}                          # CCGGuard.int    ; Gate Guard in Colusa/Nevarro
{825}{}{坟墓}                          # ntLydGrv.int    ; New Reno Lloyd's Loot Grave (Spacial Script)
{826}{}{车}                            # ntCar1.int      ; New Reno Stolen Car Seed Spacial 1
{827}{}{车}                            # ntCar2.int      ; New Reno Stolen Car Seed Spacial 2
{828}{}{坟墓}                          # niMorGrv.int    ; New Reno Mordino Stash Grave
{829}{}{穿长袍的人物}                   # EcBridge.int    ; Bridge guy special encounter
{830}{}{牲口买家}                   # SCdrvpay.int    ; Cattle drive from NCR to redding.
{831}{}{地图}                     # RndBridg.int    ; Random Bridge encounter
{832}{}{神秘的陌生人}            # ECMstStr.int    ; Mysterious Stranger
{833}{}{疯牛}                    # ECgcwbmb.int    ; Generic Cow bomb
{834}{}{日本憋三成员}                  # ECYakuza.int    ; Random Encounter Yakuza
{835}{}{怀尔得}                         # ECWilder.int    ; Random Encounter Wilder
{836}{}{狗}                            # ncWriDog.int    ; New Reno Wright Dog
{837}{}{箱子}                            # niRamBox.int    ; New Reno Box to be delivered to Ramirez
{838}{}{巡逻队员}                  # ECUniPat.int    ; Unity Patrol Random Encounter
{839}{}{农夫}                       # ECTravlr.int    ; Random Encounter Travler
{840}{}{烟}                          # KtSmoke.int     ; displays message about smoke smell in Duntons
{841}{}{商人}                         # ECTrader.int    ; Random Encounter Trader
{842}{}{僵尸}                      # ECScaven.int    ; Random Encounter Scavenger
{843}{}{商人}                       # FCMercha.int    ; San Fran Air bag merchant
{844}{}{平民}                        # FCBadPea.int    ; San Fran Bad Peasants
{845}{}{阿罗由神殿}                  # ARTemple.int    ; Arroyo Temple map script
{846}{}{码头工人}                    # FCDokWrk.int    ; San Fran Dock Worker
{847}{}{平民}                        # FCGudPea.int    ; San Fran Good Peasants
{848}{}{始族卫兵}                      # FCShiGrd.int    ; San Fran Shi Guard
{849}{}{卡梅伦}                        # ACTemVil.int    ; Temple challenge person
{850}{}{门}                           # AITemDor.int    ; Temple doors that lock at the challenge
{851}{}{克林特}                          # ACKlint.int     ; Klint the guardian of the temple exit
{852}{}{谷物}                          # AICrops.int     ; Crops that die after a period of time
{853}{}{始族科技}                   # FCslabte.int    ; San Fran Shi Lab techs
{854}{}{小孩}                          # FCSkids.int     ; San Fran Shi Kids
{855}{}{僵尸}                          # GCWander.int    ; wandering ghouls in Gecko
{856}{}{方博士}                        # FCDrFung.int    ; San Fran Dr Fung
{857}{}{交尔}                            # OCJul.int       ; Vault 13 Denmother Guard
{858}{}{科瑞斯}                         # OCKerith.int    ; Vault 13 Den Mother
{859}{}{箱子}                          # AITemCst.int    ; Temple Chest to hold the players things
{860}{}{僵尸}                          # GCRGhul.int     ; Reactor ghoul that doesn't move
{861}{}{}                               # ECRaiBow.int    ; Random Encounter Gays
{862}{}{}                               # ECMstAmy.int    ; Random Encounter Master's Army
{863}{}{采矿者}                     # ECProspe.int    ; Random Encounter Prospector
{864}{}{帮派成员}                    # ECPrsGng.int    ; Random Encounter Press Gang
{865}{}{游牧民族首领}                    # ECNomChf.int    ; Random Encounter Nomad Chief
{866}{}{哈伯教}                     # ECElRon.int     ; Hubologist Patrol
{867}{}{疯子}                          # ECCrazy.int     ; Crazies from Random Encounter
{868}{}{骗子}                   # ECClmJmp.int    ; Random Encounter Claim Jumpers
{869}{}{食人族}                       # ECCanbal.int    ; Random Encounter Cannibals
{870}{}{游牧民族巫师}                   # ECNomSha.int    ; Random Encounter Nomad Shamon
{871}{}{掠劫者}                       # ECMaradr.int    ; Random Encounter Marauder
{872}{}{恶棍}                          # ECRogue.int     ; Random Encounter Rogue
{873}{}{隐士}                         # ECHermit.int    ; Random Encounter Hermit
{874}{}{}                               # ECGangs.int     ; Random Encounter Gangs
{875}{}{商队首领}                 # ECMstKla.int    ; Random Encounter Klamath Caravan Master
{876}{}{商队首领}                 # ECMstDen.int    ; Random Encounter Den Caravan Master
{877}{}{商队首领}                 # ECMstNew.int    ; Random Encounter New Reno Caravan Master
{878}{}{商队首领}                 # ECMstRed.int    ; Random Encounter Redding Caravan Master
{879}{}{商队首领}                 # ECMstBro.int    ; Random Encounter Broken Hills Caravan Master
{880}{}{商队首领}                 # ECMstGec.int    ; Random Encounter Gecko Caravan Master
{881}{}{商队首领}                 # ECMstSan.int    ; Random Encounter San Fran Caravan Master
{882}{}{商队首领}                 # ECMstNCR.int    ; Random Encounter NCR Caravan Master
{883}{}{商队首领}                 # ECMstV15.int    ; Random Encounter Vault 15 Caravan Master
{884}{}{农夫的老婆}                  # ECFrmWfe.int    ; Random Encounter Farmer's wife
{885}{}{农夫的小孩}                   # ECFrmKid.int    ; Random Encounter Farmer's Kid
{886}{}{农场主}                    # ECHomest.int    ; Random Encounter Homesteader
{887}{}{农场女主人}             # ECHomwfe.int    ; Random Encounter Homesteader's Wife
{888}{}{农场主的小孩}              # ECHomKid.int    ; Random Encounter Homesteader's Kid
{889}{}{商队首领}                 # ECMstVC.int     ; Random Encounter Vault City Caravan Master
{890}{}{}                               # ECAlien.int     ; Random Encounter Alien
{891}{}{}                               # ECDthclw.int    ; Random Encounter Deathclaws
{892}{}{}                               # ECFloatr.int    ; Random Encounter Floater
{893}{}{}                               # ECCentur.int    ; Random Encounter Centaurs
{894}{}{英克雷军巡逻员}              # ECElvPat.int    ; Random Encounter Enclave Patrol
{895}{}{队长}                   # icMrcCpt.int    ; Raiders Merc Captain
{896}{}{歹徒}                    # icMerc.int      ; Raiders Merc
{897}{}{"影者"}             # icScout.int     ; Raiders Scout
{898}{}{保险箱}                           # iiSafe.int      ; Raiders Safe
{899}{}{}                               # raiders1.int    ; Raiders 1 Enterance
{900}{}{}                               # raiders2.int    ; Raiders 2 Caves
{901}{}{}                               # HSCellDr.int    ; Broken Hills bank/jail door
{902}{}{箱子}                            # niTRyBox.int    ; New Reno Chop Shop T-Ray Box
{903}{}{理察森总统}           # qhPrzRch.int    ; Enclave President Richardson talking head.
{904}{}{豪卫慈}                       # WIHowitz.int    ; Howitzer in the Sierra Base
{905}{}{门}                           # WIEntDor.int    ; Entrance to Sierra Base Door
{906}{}{死亡爪幼虫}                 # OCBabDth.int    ; Baby Deathclaws in Vault 13
{907}{}{危险 丹}                  # RCMcGrew.int    ; Dangerous Dan McGrew from redding
{908}{}{强森}                    # RCDrJohn.int    ; Painless Doc Johnson (breaks Jet)
{909}{}{马力安警长}                 # RCMarion.int    ; Sheriff Earl Marion
{910}{}{阿思寇提市长}                  # RCAscort.int    ; Mayor Ascorti of Redding
{911}{}{诺丁}                        # RCNord.int      ; Nording, the payoff man for Stanwell
{912}{}{凡拉尼}                         # RCVelani.int    ; Velani, the payoff man for Savinelli
{913}{}{芬尔堂}                       # RCFern.int      ; Ferndown, the payoff man for Wade
{914}{}{龙}                     # FCDragon.int    ; The Dragon, San Fran
{915}{}{马厩工人}                     # mcSblBoy.int    ; Modoc Stable Boy
{916}{}{商人}                         # mcTrader.int    ; Modoc Trader
{917}{}{镇民}                    # mcPerson.int    ; Modoc Townspeople
{918}{}{溶渣}                           # mcSlgExt.int    ; Ghost Farm Slag Exit Guard
{919}{}{溶渣}                           # mcSlgGrd.int    ; Ghost Farm Slag Enterance Guard
{920}{}{罗潘}                         # FCLoPan.int     ; Lo Pan in San Fran.
{921}{}{派特爵}                         # FCBadger.int    ; Badger in San Fran.
{922}{}{贾序}                           # RCJosh.int      ; Josh Laurance of Redding
{923}{}{卡麦那多}                      # RCCamint.int    ; Caminetto in bar fight in redding
{924}{}{贝蒂}                          # RCBette.int     ; Blasphemous Bette in bar fight in redding
{925}{}{枪商}                   # FCGunmer.int    ; San Fran's gun Merchant
{926}{}{门}                           # ZIWodDor.int    ; Generic Wooden Door
{927}{}{门}                           # ZIMtlDor.int    ; Generic Metal Door
{928}{}{发射器}                        # SSEmtN2.int     ; Emitter in NCR area 2
{929}{}{鼠神}                        # ZCRatGod.int    ; Rat God in Klamath
{930}{}{}                               # ECBox.int       ; Random box that has stuff in it.
{931}{}{卡贾}                           # ECKaga1.int     ; Random Encounter Kaga 1
{932}{}{卡贾}                           # ECKaga2.int     ; Random Encounter Kaga 2
{933}{}{卡贾}                           # ECKaga3.int     ; Random Encounter Kaga 3
{934}{}{卡贾}                           # ECKaga4.int     ; Random Encounter Kaga 4
{935}{}{卡贾}                           # ECKaga5.int     ; Random Encounter Kaga 5
{936}{}{奖金猎人}                  # ECBHunter.int   ; Random Encounter Bounty Hunter
{937}{}{电脑}                       # VIMedCom.int    ; Vault City Medical Computer
{938}{}{电脑}                       # VICenCom.int    ; Vault City Central Computer
{939}{}{电脑}                       # VIAloCom.int    ; Vault City Allocation Computer
{940}{}{达洛}                         # VCDarrow.int    ; Vault City Sub-Amenities Officer Darrow
{941}{}{费尔}                        # VCFarrel.int    ; Vault City Sub-Amenities Officer Farrell
{942}{}{酒吧客人}                     # VCBarPat.int    ; Vault City Bar Patron
{943}{}{地下掩体市公民}                  # VCWrkCit.int    ; Vault City Working Citizen
{944}{}{地下掩体市奴仆}                  # VCSlave.int     ; Vault City Slave
{945}{}{通风口}              # VIShft2b.int    ; Vault City Ventilation Shaft 2B
{946}{}{查理}                        # VCCharli.int    ; Vault City Puking Charlie
{947}{}{冷却器控制介面}          # GSValve.int     ; Gecko Coolant Control Panel
{948}{}{牛粪}                            # ziBraPoo.int    ; Generic BRAHMIN SHIT!!! YES YES YES
{949}{}{葛兰}                          # scWesGrd.int    ; Westin's Force Field Guard
{950}{}{发射器}                        # SSEmiWes.int    ; Westin's Force Field Emitter
{951}{}{发射器}                        # SSEmiWe1.int    ; Westin's force field on the other map.
{952}{}{电脑控制台}              # SICmpWes.int    ; Westin's computer terminal for the field.
{953}{}{皇帝电脑终端机 v8.8}          # FSEmpTer.int    ; Computer Terminal in San Fran
{954}{}{副总统飞鸟}            # QCBird.int      ; Enclave, Vice President Bird
{955}{}{马丁}                         # QCMartin.int    ; Enclave, Martin Frobishner, V13 spokesman
{956}{}{李健}                        # FCKenLee.int    ; Ken Lee in San Francisco
{957}{}{葛兰耐特上校}                   # QCGranit.int    ; Sgt. Granite of the Enclave Patrol
{958}{}{法兰克．荷瑞根}                 # QCFrank.int     ; Secret Service Agent Frank (End Boss)
{959}{}{地图}                     # GeckJunk.int    ; Map Script for Gecko Junkyard
{960}{}{地图}                     # GeckTunl.int    ; Map Script for Gecko Tunnels
{961}{}{门}                           # SSFrgDor.int    ; Fergus's Door script
{962}{}{门}                           # SSGunDor.int    ; Gunther's Door script to Tandi
{963}{}{门}                           # SSFlxDor.int    ; Felix's Door script
{964}{}{绳子}                           # SSRope.int      ; Rope.. for you to climb
{965}{}{发射器}                        # SSEmiEnt.int    ; Emitter in Ncr Entrance
{966}{}{卡林博士}                    # QCCurlng.int    ; Dr. Charles Curling, Chem Corps.
{967}{}{布告栏}                 # SSSign.int      ; Sign in NCR Entrance
{968}{}{地鼠}                       # mcMolRat.int    ; Ghost Farm Mole Rat
{969}{}{总统的秘书}          # QCPrsSec.int    ; President's personal intern (uh sectertary)
{970}{}{汤姆．莫雷}                     # QCMurray.int    ; Tom Murray, head of AEC
{971}{}{坚固的门}                    # SSCrpDor.int    ; Craps table door in NCR
{972}{}{镇民}                    # mcPeasan.int    ; Modoc Peasant, they attack the farm
{973}{}{地下掩体市行政区}        # VCtyCocl.int    ; Map Script Vault City Council Area
{974}{}{空气清净机}                   # HSPurify.int    ; Air Purifier for Broken Hills
{975}{}{石头}                          # esEntRks.int    ; Military Base Entrance Rocks
{976}{}{赌徒}                        # RCGamble.int    ; Redding Generic Gamblers
{977}{}{假的尸体}                 # HtCorpse.int    ; Spatial Script for Corpses
{978}{}{来自ＮＣＲ的骗子}                        # SCCheat.int     ; Cheat Character for NCR
{979}{}{囚犯}                       # QCGenPrs.int    ; Enclave Generic Prisoner
{980}{}{市民}                        # QCGenCit.int    ; Enclave Generic Citizens
{981}{}{士兵}                          # QCGenGrd.int    ; Enclave Generic Guards
{982}{}{科学家}                      # QCGenSci.int    ; Enclave Generic Scientist
{983}{}{控制器}                       # QIPzlTrm.int    ; Enclave terminal in the Puzzle Level
{984}{}{}                               # etEnter.int     ; Military Base Enterance Spacial Message
{985}{}{}                               # etBattle.int    ; Military Base Battle Area Spacial Message
{986}{}{发射器}                        # SSEmiEn1.int    ; Ncr emitters for ncr entrance on map 1
{987}{}{门}                     # QIBstDr1.int    ; Blast Door for Reactor Off to remain closed
{988}{}{门}                     # QIBstDr2.int    ; Blast Door for Reactor On to remain closed
{989}{}{达洛的存货}                 # VIDarBox.int    ; Vault City Darrow Shop Inventory
{990}{}{门}                           # HSCrlDr.int     ; Jail cell door for Broken Hills
{991}{}{超级变种人}             # ecTlkMut.int    ; Military Base Conversation Mutants
{992}{}{化学家}                        # fcChemst.int    ; Chemist in San Francisco
{993}{}{古朗多}                        # ecGrunde.int    ; Military Base Mouse Hunter
{994}{}{小孩}                            # ecMelKid.int    ; Some Town USA, Melchior's Kid
{995}{}{视网膜扫瞄器}                # WIRetScn.int    ; Retinal Scanner in the Sieera Base
{996}{}{电梯门}                  # WIElvDor.int    ; Elevator Door in the Seirra Base
{997}{}{生化箱}          # WIBrkBrn.int    ; Broken Brain Bot in the Sierra Base
{998}{}{墙}                           # WIScrtDr.int    ; Sierra Base Secert Door
{999}{}{地图}                     # broken2.int     ; Map Script for Broken Hills Map 2
{1000}{}{费罗的存货}               # VIFarBox.int    ; Vault City Farrell Shop Inventory
{1001}{}{哈利的存货}                 # VIHarBox.int    ; Vault City Harry Shop Inventory
{1002}{}{箱子}                           # VICtyBox.int    ; Vault City Courtyard Temp Inventory Box
{1003}{}{箱子}                           # VIDwtBox.int    ; Vault City Downtown Temp Inventory Box
{1004}{}{德瑞克}                         # dcDerek.int     ; Derek in the Den
{1005}{}{塔比的朋友}                # dcTubFri.int    ; Tubby's Junkie Friends in the Den
{1006}{}{赌徒}                       # dcGamble.int    ; Gamblers in the Den
{1007}{}{奴隶}                         # dcSlave.int     ; Pen Slaves in the Den
{1008}{}{士兵}                         # dcMetRom.int    ; Metzger Room Guard in the Den
{1009}{}{奴隶商人}                        # dcPenGrd.int    ; Slaver Pen Guard in the Den
{1010}{}{萝拉}                          # dcLara.int      ; Lara in the Den
{1011}{}{泰勒}                         # dcTyler.int     ; Tyler in the Den
{1012}{}{马克}                          # dcMarc.int      ; Marc in the Den
{1013}{}{布告栏}                # diBulBrd.int    ; Bulletin Board in the Den
{1014}{}{奴隶商人}                        # dcVicGrd.int    ; Vic Guard in the Den
{1015}{}{奴隶商人}                        # dcSlvGrt.int    ; Slaver Greeter in the Den
{1016}{}{弗瑞德}                          # dcFred.int      ; Fred in the Den
{1017}{}{箱子}                           # diFliBox.int    ; Flick Box in the Den
{1018}{}{箱子}                           # diMomBox.int    ; Mom Box in the Den
{1019}{}{箱子}                           # diSmiBox.int    ; Smitty Box in the Den
{1020}{}{后车箱}                     # ZICrTrnk.int    ; generic script for Car Trunk
{1021}{}{安全门}                 # QIPzlDor.int    ; Door for the puzzle room in the Enclave
{1022}{}{电脑控制台}             # FSPhySta.int    ; Physics computer station in San Fran
{1023}{}{电脑控制台}             # FSBioSta.int    ; Biology computer station in San Fran
{1024}{}{电脑控制台}             # FSCheSta.int    ; Chemistry computer station in San Fran
{1025}{}{朱流}                      # FCLaoCho.int    ; Merchant in San Fran
{1026}{}{}                              # FIPaper.int     ; Scrap Papers that combine should only be put on one of thepeaces.
{1027}{}{通风口}             # CSVent.int      ; Ventilation shaft for Navarro
{1028}{}{地图}                    # EncTrp.int      ; Map Script for Enclave Trap Rooms
{1029}{}{尸体}                     # HtBody.int      ; Script for dead bodies in Broken Hills
{1030}{}{电线}                 # QIWires.int     ; Wires on the ground in the trap room
{1031}{}{箱子}                           # diMetBox.int    ; Metzger Box from Slave Crap
{1032}{}{奴隶}                         # dcRunSlv.int    ; Den Slave Run Fleeing Slaves
{1033}{}{奴隶}                         # dcAtkSlv.int    ; Den Slave Run Hostile Slaves
{1034}{}{奴隶商人}                        # dcRnSlvr.int    ; Den Slave Run Slavers
{1035}{}{钱币}                          # FCChip.int      ; Chip in San Fran no spleen
{1036}{}{反应炉}                       # QIReactr.int    ; Reactor in the Enclave
{1037}{}{反应炉电脑}              # QIRctrCm.int    ; Reactor Computer in the Enclave
{1038}{}{收银员}                   # RCCshTnd.int    ; Redding Cash Tender in the Casino
{1039}{}{钱箱}                      # RICshBox        ; Cash Box for the Cash Tender
{1040}{}{瓦那明球}                     # RCWanami.int    ; Wanamingo
{1041}{}{酒吧客人}                    # dcStory1.int    ; Story Teller 1 in the Den
{1042}{}{酒吧客人}                    # dcStory2.int    ; Story Teller 2 in the Den
{1043}{}{牢门}                     # RIJalDor.int    ; Jail Door in Redding
{1044}{}{苏}                          # FCSuze.int      ; Suze in San Fran
{1045}{}{朗麦尔队长}            # FCRonMey.int    ; Captain Ron Meyers
{1046}{}{门}                      # diPenDor.int    ; Slave Pen Door in the Den
{1047}{}{瓦那明球矿坑}                # RedWan1.int     ; Map Script for Wanamingo Mine
{1048}{}{瓦那明球矿坑入口}       # RedWane.int     ; Map Script for Wanamingo Mine Entrance
{1049}{}{“青蛙”．摩顿}                   # RCFrog.int      ; Frog Morton
{1050}{}{达夫H.}                       # FCDaveh.int     ; Dave Handy in San Fran
{1051}{}{门}                          # diVicDor.int    ; Vic's Room Door in the Den
{1052}{}{门}                          # diRomDor.int    ; Metzger's Room Door in the Den
{1053}{}{查理}                # vccharly.int    ; Puking Charlie in Vault Courtyard
{1054}{}{画}                      # SIPaint.int     ; Revales Vault 13 on examination.
{1055}{}{地图}                    # SFChina.int     ; San Fran China Map
{1056}{}{酒保}                     # VCCouBar.int    ; Vault City Council Area Bartender
{1057}{}{箱子}                           # VIBarBox.int    ; Vault City Slave Sale Inventory Dump
{1058}{}{自动医生}                      # VIAutDoc.int    ; Vault City Courtyard Auto-Doc
{1059}{}{}                              # RIMinEnt.int    ; Entrance Back to the Mines
{1060}{}{坑道}                 # RedMTun.int     ; Map Script for Mining Tunnel
{1061}{}{机器人}                         # KCRob.int       ; Robot on Klamath Canyon
{1062}{}{}                              # FiGunTbl.int    ; Gun Merchant table in San fran
{1063}{}{地图}                    # KlaMall.int     ; Map Script for Klamath Mall area
{1064}{}{地图}                    # KlaTrap.int     ; Map Script for Klamath Still area
{1065}{}{莉蒂雅}                         # VCDwnBar.int    ; Vault City Downtown Bartender
{1066}{}{}                              # RedDTun.int     ; Redding Downtown Tunnels
{1067}{}{火箭人}                     # FCRocMan.int    ; Rocket man in San Fran
{1068}{}{AHS-7}                         # FCOz7.int       ; Oz 7 in San Fran
{1069}{}{克拉克特}                      # FCCrocke.int    ; Crockett in San Fran
{1070}{}{阿曼达}                        # VCAmanda.int    ; Vault City Coutryard Amanda, Joshua's Wife
{1071}{}{约瑟}                        # VCJoshua.int    ; Vault City Courtyard Joshua, Slave
{1072}{}{薇拉瑞}                       # VCMainWk.int    ; Valerie, Vic's Daughter and Maintence Worker
{1073}{}{教学系统}               # VITeach.int     ; Vault City Teaching System
{1074}{}{箱子}                         # diCrate.int     ; Den Crate in Church
{1075}{}{随地小便的人}                    # VCUrine.int     ; Peeing Guy in Vault City Council Area
{1076}{}{科提斯}                        # VCCurtis.int    ; Curtis, Amanda and Joshua's Son
{1077}{}{马克}                          # FCMarc.int      ; Marc, Punk in San Fran
{1078}{}{电脑}                      # FSElComp.int    ; Hubologists computer
{1079}{}{AHS-9}                         # FCOz9.int       ; Hubologist main dude
{1080}{}{士兵}                         # FCElGrd.int     ; Hubologist's guards
{1081}{}{一堆石头}                 # VIRocks.int     ; Pile of Rocks w/ Hidden Wrench
{1082}{}{门}                          # VIVltDor.int    ; Vault City 2nd floor doors
{1083}{}{士兵}                         # dcRebGrd.int    ; Den Rebecca Guard
{1084}{}{士兵}                         # dcRebDor.int    ; Den Rebecca Door Guard
{1085}{}{门}                          # diRebDor.int    ; Den Rebecca Door
{1086}{}{通缉标示}                   # ZSWsign.int     ; Generic Wanted Sign
{1087}{}{王博士}                      # FCDrWong.int    ; Dr. Wong in San Fran area
{1088}{}{桌子}                         # FIlaotbl.int    ; Lao Cho's stock tables in san Fran
{1089}{}{门}                          # WILv1Dor.int    ; Locked Door on Level 1 Entrance         # local_vars=8
{1090}{}{混混}                          # FCFemPnk.int    ; San Fran Female punk
{1091}{}{混混}                          # FCMalPnk.int    ; San Fran Male Punk
{1092}{}{莱恩}                          # FCRyan.int      ; San Fran Punk Ryan
{1093}{}{箱子}                           # HIBh1Box.int    ; Broken Hills Temp Inventory Box
{1094}{}{}                              # FCJuavki.int    ; Juan and Vikkin in San Fran Elron Camp
{1095}{}{地下水道通道}                       # HIManHol.int    ; Manhole to Basement in Liz's Store
{1096}{}{地图}                    # SFElronb.int    ; Elron Base map Script
{1097}{}{梯子}                        # HILadder.int    ; Ladder up to Liz's Store
{1098}{}{沙包}                  # WIPnchBg.int    ; Punching Bag in the Sierra Depot
{1099}{}{门}                          # WIBayDor.int    ; Sierra Base Repair Bay Door
{1100}{}{警铃}                         # GSAlarm.int     ; Gecko Reactor alarm
{1101}{}{地板}                   # WIPlTrp2.int    ; Plasma Floor Trap Level 2 of Seirra
{1102}{}{地板}                   # WIPlTrp3.int    ; Plasma Floor Trap Level 2 of Seirra
{1103}{}{地板}                   # WIPlTrp4.int    ; Plasma Floor Trap Level 2 of Seirra
{1104}{}{地板}                   # WIPlTrp5.int    ; Plasma Floor Trap Level 2 of Seirra
{1105}{}{地板}                   # WIPlTrp6.int    ; Plasma Floor Trap Level 2 of Seirra
{1106}{}{地板}                   # WIPlTrp7.int    ; Plasma Floor Trap Level 2 of Seirra
{1107}{}{地板}                   # WIPlTrp8.int    ; Plasma Floor Trap Level 2 of Seirra
{1108}{}{地板}                   # WIPlTrp9.int    ; Plasma Floor Trap Level 2 of Seirra
{1109}{}{地板}                   # WIPlTrpA.int    ; Plasma Floor Trap Level 2 of Seirra
{1110}{}{地板}                   # WIPlTrpB.int    ; Plasma Floor Trap Level 2 of Seirra
{1111}{}{地板}                   # WIPlTrpC.int    ; Plasma Floor Trap Level 2 of Seirra
{1112}{}{地板}                   # WIPlTrpD.int    ; Plasma Floor Trap Level 2 of Seirra
{1113}{}{地板}                   # WIPlTrpE.int    ; Plasma Floor Trap Level 2 of Seirra
{1114}{}{地板}                   # WIPlTrpF.int    ; Plasma Floor Trap Level 2 of Seirra
{1115}{}{发射器}                       # WSEmit4a.int    ; Emitter, Level 4 in Sierra Base
{1116}{}{发射器}                       # WSEmit4b.int    ; Emitter, Level 4 in Sierra Base
{1117}{}{发射器}                       # WSEmit4c.int    ; Emitter, Level 4 in Sierra Base
{1118}{}{力场}                   # WSFeld4a.int    ; Force Field, Level 4 in Sierra Base
{1119}{}{力场}                   # WSFeld4b.int    ; Force Field, Level 4 in Sierra Base
{1120}{}{力场}                   # WSFeld4c.int    ; Force Field, Level 4 in Sierra Base
{1121}{}{哈伯教}                    # FCElrInd.int    ; Elron Indoctrinee
{1122}{}{电脑}                      # FStnkCmp.int    ; Posiden Tanker Computer
{1123}{}{门}                   # WIBnkDor.int    ; Bunker Door for the Sierra Depot
{1124}{}{大门}                          # miGate.int      ; Modoc Gate
{1125}{}{箱子}                           # WITrpBx1.int    ; Sierra Base Trapped Box
{1126}{}{摩顿兄弟}                # RCMorBrs.int    ; Morton Brothers, Inc.
{1127}{}{发射器}                       # FSEmt1.int      ; Force Field emitter 1 in San Fran
{1128}{}{发射器}                       # FSEmt2.int      ; Force Field emitter 2 in San Fran
{1129}{}{发射器}                       # FSEmt3.int      ; Force Field emitter 3 in San Fran
{1130}{}{地图}                    # Cave6.int       ; Fake Vault 13 Cave map
{1131}{}{侠特}                          # VCChet.int      ; Illicit Allocations Officer Chet
{1132}{}{地图}                    # NewRVB.int      ; New Reno Helicopter Script Map
{1133}{}{飞鸟}                     # nsVertib.int    ; New Reno Helicopter Script Vertibird
{1134}{}{沙尔瓦多的卫兵}               # ncHSSal1.int    ; New Reno Helicopter Script Salvatore 1
{1135}{}{沙尔瓦多的卫兵}               # ncHSSal2.int    ; New Reno Helicopter Script Salvatroe 2
{1136}{}{士兵}                      # ncHSPow1.int    ; New Reno Helicopter Script Power Armor 1
{1137}{}{士兵}                      # ncHSPow2.int    ; New Reno Helicopter Script Power Armor 2
{1138}{}{箱子}                         # niHSCrat.int    ; New Reno Helicopter Script Crate
{1139}{}{韩地先生}                     # ncHSHand.int    ; New Reno Helicopter Script Handy
{1140}{}{沙尔瓦多的卫兵}               # ncHSGSal.int    ; New Reno Helicopter Script Salvatore Guard
{1141}{}{特别任务}                # ntHSGrd.int     ; New Reno Helicopter Script Guarding Spacial
{1142}{}{门}                          # niEldDor.int    ; New Reno Elderidge Door
{1143}{}{门}                          # niSalDor.int    ; New Reno Salvatore Door
{1144}{}{门}                          # niMyrDor.int    ; New Reno Myron Door
{1145}{}{}                              # FcMonst.int     ; Monster in the PMS Tanker
{1146}{}{地图}                    # SFTanker.int    ; San Fran Tanker map
{1147}{}{奴隶}                         # VCSlav2.int     ; Vault City Prisoner Slaves
{1148}{}{地下掩体市公民}                 # VCBarCit.int    ; Vault City Bar Patron
{1149}{}{门}                          # niBasDor.int    ; New Reno Locking Doors
{1150}{}{拳击手}                         # ncFightr.int    ; New Reno Boxer Actually Fighting
{1151}{}{避难所门}                    # RIVltDor.int    ; Locked Vault Door in Redding
{1152}{}{查恩}                          # CcXarn.int      ; Xarn in Navarro
{1153}{}{罗乌}                          # CcRaul.int      ; Raul in Navarro
{1154}{}{昆西}                        # CcQuincy.int    ; Quincy in Navarro
{1155}{}{总管}                 # CcQmstr.int     ; Quartermaster in Navarro
{1156}{}{士兵}                         # CcMedGrd.int    ; Med Lab Guard in Navarro
{1157}{}{机器狗}                # CcK9.int        ; K9 in Navarro
{1158}{}{博士}                        # CcDoctor.int    ; Dr Shreber in Navarro
{1159}{}{技术人员}                    # CcATech.int     ; Air Tech in Navarro
{1160}{}{技术人员}                    # CcACon.int      ; Air Control in Navarro
{1161}{}{士兵}                         # CcDrGrd.int     ; Door Guard in Navarro
{1162}{}{士兵}                         # Ccggbak.int     ; Gate Guard Backup in Navarro
{1163}{}{士兵}                         # CcGrdca.int     ; Guard (combat armor) in Navarro
{1164}{}{士兵}                         # CcGrdpa.int     ; Guard (power armor) in Navarro
{1165}{}{技术人员}                    # CcTech1.int     ; Com Tech1 in Navarro
{1166}{}{技术人员}                    # CcTech2.int     ; Com Tech2 in Navarro
{1167}{}{技术人员}                    # CcComp1.int     ; Computer Tech1 in Navarro
{1168}{}{技术人员}                    # CcComp2.int     ; Computer Tech2 in Navarro
{1169}{}{坍坊}                       # HICaveIn.int    ; Broken Hills Caved-In mine
{1170}{}{英克雷军巡逻兵}             # QCEPSqad.int    ; Enclave EP Squad (joins player in fighting
{1171}{}{门}                    # QIEndDor.int    ; Doors at the End Fight Area
{1172}{}{地图}                    # EncDet.int      ; Map Script for Enclave Detention Center
{1173}{}{地图}                    # EncDock.int     ; Map Script for Enclave Dock
{1174}{}{地图}                    # EncGd.int       ; Map Script for Enclave Guard Barracks
{1175}{}{地图}                    # EncPres.int     ; Map Script for Enclave Presidential Area
{1176}{}{地图}                    # EncRetr.int     ; Map Script for Enclave Reactor Area
{1177}{}{地图}                    # EncFite.int     ; Map Script for Enclave Fight Area
{1178}{}{安全机器人}                # QCSecBot.int    ; Enclave Security Robot
{1179}{}{Poor盒子}                      # niTulBox.int    ; New Reno Poor Box
{1180}{}{遗体}                          # hiDead.int      ; Dead body in Broken Hills Tunnels
{1181}{}{箱子}                           # HiJacBox.int    ; Broken Hills Jacob inventory box
{1182}{}{箱子}                           # HiDocBox.int    ; Broken Hills Doc Holliday Inventory box
{1183}{}{箱子}                           # HiOutBox.int    ; Broken Hills Outfitter inventory box
{1184}{}{商队卫兵}                 # RCCvnGrd.int    ; Generic Caravan Guard
{1185}{}{商队驾驶}                # RCCvnDrv.int    ; Generic Caravan Driver
{1186}{}{拳击拨报员}                # ncAnounc.int    ; New Reno Boxing Announcer
{1187}{}{拳击女郎}                     # ncRngGrl.int    ; New Reno Ring Grrrl
{1188}{}{拳击手}                         # ncPrzFtr.int    ; New Reno Prize Fighter
{1189}{}{门}                          # VIVltDr2.int    ; Vault Doors in Vault 8
{1190}{}{骗子}               # ncCheat.int     ; New Reno Cheat Character
{1191}{}{全息卡带}                      # WIGNNDsk.int    ; Sierra Base GNN Transscript
{1192}{}{全息卡带}                      # WIMisDsk.int    ; Sierra Base Mission Statement Disk
{1193}{}{全息卡带}                      # FIElrDsk.int    ; Hubologist Holodisk
{1194}{}{纸条}                          # HINote.int      ; Script for Francis/Zaius Note
{1195}{}{狗肉}                       # ECDogMet.int    ; Dog Meat from Special random encounter
{1196}{}{猫爪杂志第5期}         # niCatPw5.int    ; New Reno Cat's Paw magazine 5
{1197}{}{歹徒地图}                   # niRaiMap.int    ; New Reno Raiders Map in Bishop's Safe
{1198}{}{狗}                    # ECPariah.int    ; Pariah Dog in Low Luck encounter
{1199}{}{警报器}                        # QIKlaxon.int    ; Klaxon Lights for Enclave when under alert
{1200}{}{矿坑}                          # IIMine.int      ; Mines in Raiders Cave
{1201}{}{洞穴}                           # IIPit.int       ; Pits in the Raiders Cave
{1202}{}{油舰商人}               # FCTnkGmr.int    ; Tanker Gun Merchant San Fran
{1203}{}{油舰酒保}              # FCTnkBar.int    ; Tanker Bar Tender
{1204}{}{油舰商人}               # FCTnkMer.int    ; Tanker Merchant
{1205}{}{}                              # FITGunTb.int    ; Tanker Gun Mer's table
{1206}{}{}                              # FITMerTb.int    ; Tanker Merchant's Table
{1207}{}{发射器}                       # FSPemtr1.int    ; Palace Emitter 1
{1208}{}{发射器}                       # FSPemtr2.int    ; Palace Emitter 2
{1209}{}{发射器}                       # FSPemtr3.int    ; Palace Emitter 3
{1210}{}{发射器}                       # FSEmpEmt.int    ; Emporor Computer's Force Field
{1211}{}{异尘余生２攻略本}            # niF2Hint.int    ; New Reno Fallout 2 Hintbook
{1212}{}{}                              # csTouch.int     ; Script to signal if dude touches container objects (in Navarro)
{1213}{}{}                              # csArea.int      ; Script to signal if dude enters an area (in Navarro)
{1214}{}{士兵}                         # RCAscGrd.int    ; Generic Guard for Ascorti's Bar
{1215}{}{采矿者}                    # ECLdPros.int    ; Random Encounter Lead Prospector
{1216}{}{私贩酒者}                   # ECLdBoot.int    ; Random Encounter Lead Bootlegger
{1217}{}{}                              # csOpen.int      ; Script to signal if dude uses door w/o permission (in Navarro)
{1218}{}{Dan}                           # hcDan.int       ; Dan, Spouse of murdered conspirator.
{1219}{}{烂喜剧演员}               # ncComedi.int    ; New Reno Comedian
{1220}{}{歌手}               # ncBand.int      ; New Reno Trashcan Band
{1221}{}{地图}                    # ARDead.int      ; Destroyed Arroyo Bridge map script
{1222}{}{}                              # csGate.int      ; Script to signal if dude uses gate w/o permision (in Navarro)
{1223}{}{坟墓}                         # niWilGrv.int    ; New Reno Coffin Willie's Grave
{1224}{}{威利}                 # ncWillie.int    ; New Reno Coffin Willie
{1225}{}{没有键盘的入口控制电脑}        # FSFobTer.int    ; Fob Terminal
{1226}{}{没有键盘的入口}            # FSFobDor.int    ; Fob Door
{1227}{}{电脑}                      # ccNComp.int     ; Navarro Computer
{1228}{}{卡欧}                          # vcKohl.int      ; Vault City Info Officer Kohl
{1229}{}{小孩}                         # ECChild.int     ; Random Encounter Children
{1230}{}{厨师}                          # ccCook.int      ; Navarro Cook
{1231}{}{炮台}                        # ccTurret.int    ; Navarro Turret
{1232}{}{布莱恩}                         # hcBrian.int     ; Brian, the Power Technician
{1233}{}{发电机}                     # hiPower.int     ; Power Generator for Broken Hills
{1234}{}{控制台}                       # hiConsole.int   ; Power Station Console in Broken Hills
{1235}{}{巨蚁}                     # hcAnt1.int      ; Standard Broken Hills Ant
{1236}{}{巨蚁}                     # hcAnt2.int      ; Broken Hills Ant - Missing Person Quest
{1237}{}{门}                          # csXDoor.int     ; Another lousy door script -signals xarn to leave
{1238}{}{}                              # htSecret.int    ; Spatial for secret area of Broken Hills Mine
{1239}{}{箱子}                           # niEthBox.int    ; New Reno Ethyl Wright Shop Box
{1240}{}{艾力克}                          # hcEric.int      ; Eric the Smelly Boy, Broken Hills
{1241}{}{}                              # htFlies.int     ; Spatial Flies script for Broken Hills
{1242}{}{箱子}                           # viRanBox.int    ; Randal's Stock Box in Vault City
{1243}{}{大毒蝎}                # iiScorp.int     ; Raiders Scorpions 2X poison
{1244}{}{珍}                          # RCJane.int      ; Redding Jackpot Jane
{1245}{}{}                              # VTAloMrk.int    ; Spatial Script for Allocation Computer VCity
{1246}{}{地图}                    # Cave7.int       ; Fake Vault 13 map
{1247}{}{真皮的哔哔小子}                # niDermal.int    ; New Reno Dermal Pip Boy
{1248}{}{波奇}                         # ncEldDog.int    ; New Reno Eldridge Dogs
{1249}{}{罗特雷}                       # RCRatray.int    ; Rattray, Doc Johnson's assistant
{1250}{}{夫妇}                        # HCHusWif.int    ; Mutant Husband/Wife Broken Hills
{1251}{}{罗潘卫兵}                   # FCLoGrd.int     ; LoPan Guard in San Fran
{1252}{}{地图}                    # Navarro.int     ; Map script for Navarro
{1253}{}{门}                          # VIVltDr3.int    ; Vault Door in Vault 8 - Martin
{1254}{}{机器狗}                # CcFak9.int      ; Fake K-9 Scenery obj
{1255}{}{路克}                          # FCNLuke.int     ; Luke in NCR
{1256}{}{约瑟}                        # FCDJosh.int     ; Joshua BOS in the Den
{1257}{}{大门}                          # iiLockDr.int    ; Gates in Raiders area
{1258}{}{麦特}                          # FCFmatt.int     ; Matt in San Fran BOS
{1259}{}{门}                          # FSBroDor.int    ; Brotherhood Door
{1260}{}{士兵}                         # hcGrd2.int      ; Bank Guard 2 in Broken Hills
{1261}{}{门}                          # QIGeckDr.int    ; Door Requiring the player to use the geck
{1262}{}{电脑}                      # FSFace.int      ; Ace Computer system in San Fran
{1263}{}{控制器}                      # QITurTrm.int    ; Generic Enclave Turret Terminal
{1264}{}{炮台}                        # QCTurret.int    ; Enclave Turrets
{1265}{}{恰克．史度杰}                # hcChuck.int     ; Chuck Stodgers, Broken Hills
{1266}{}{}                              # htChuck.int     ; Spatial Script for waking up Chuck
{1267}{}{控制器}                      # viTerm.int      ; Vault City Vault Terminal
{1268}{}{帮派份子}                     # RCMotGng.int    ; Frog Morton's gang
{1269}{}{作弊者}                       # ccCheat.int     ; Cheat character in Navarro
{1270}{}{}                              # FSTnkrdr.int    ; Tanker Doors in San Fran
{1271}{}{平民}                       # OCPeaon.int     ; NCR peaons
{1272}{}{凡德之花}           # diRebBok.int    ; Den Becky's Book
{1273}{}{辐射蝎}                   # hcScorp.int     ; Broken Hills Scorpion
{1274}{}{教授}                     # hcProf.int      ; Broken Hills Professor
{1275}{}{箱子}                           # hiPrfBx1.int    ; Professor's Box in Broken Hills
{1276}{}{箱子}                           # hiPrfBx2.int    ; Professor's Box in Broken Hills
{1277}{}{西莫}                       # hcSeymore.int   ; Seymour the talking Plant/Broken Hills
{1278}{}{约翰．苏罗文}                 # hcSulvan.int    ; John Sullivan - Broken Hills
{1279}{}{蓝尔皮}                         # hcLumpy.int     ; Lumpy the car accident victim - Broken Hills
{1280}{}{}                              # BISpyHol.int    ; Spy Holodisk for NCR
{1281}{}{}                              # SIHisHol.int    ; NCR History Holodisk
{1282}{}{}                              # SIWesHol.int    ; Westin Holodisk
{1283}{}{士兵}                         # SCBGrd.int      ; Buster's Guard
{1284}{}{}                              # SIElnObj.int    ; Elise Notify Object
{1285}{}{}                              # SIGcaObj.int    ; NCR Guard Captain notify obj
{1286}{}{泰丰}                        # hcTyphon.int    ; Typhon, Son of Set - Broken Hills
{1287}{}{保镳}                     # ECBdyGrd.int    ; BodyGuard in Vignette
{1288}{}{地图}                    # GamMovie.int    ; Game Movie map
{1289}{}{锁柜}                        # ziLocker.int    ; Generic Locker Script
{1290}{}{水井}                          # hiWell.int      ; Broken Hills Well
{1291}{}{米奇}                         # hcMicky.int     ; Mickey the Dwarf - Broken Hills
{1292}{}{炮台}                        # WCTurret.int    ; Turret for Sierra Depot
{1293}{}{老僵尸}                     # hcOldGhl.int    ; Ghouls in Old-Folks Home - Broken Hills
{1294}{}{追从者}                      # hcHench.int     ; Broken Hills Outfitter Henchmen
{1295}{}{艾尔摩}                          # hcElmo.int      ; Elmo - Broken Hills
{1296}{}{厕所}                        # niToilet.int    ; Toilet - Contains Grenades - New Reno
{1297}{}{十字架}                         # niCross.int     ; Cross - Golgotha - Buried Cash
{1298}{}{犁}                          # viPlow1.int     ; Plow - Vault City
{1299}{}{犁}                          # viPlow2.int     ; Plow - Vault City
{1300}{}{辐射蝎}                      # kcScorpa.int    ; Attacking scorpion in klamath
{1301}{}{发电机}                     # kcGnratr.int    ; Generator player repairs in toxic caves
{1302}{}{门}                          # kcLvatr.int     ; Elevator door in toxic caves
{1303}{}{门}                          # SIVDor.int      ; Vortis Slave Door
{1304}{}{医疗哔哔小子}               # niMedica.int    ; New Reno "Doctor Skill" Upgrade
{1305}{}{锁柜}                        # niPrstLk.int    ; New Reno Prostitute"Locker"
{1306}{}{锁柜}                        # niBigJLk.int    ; New Reno Big Jesus "Locker"
{1307}{}{锁柜}                        # niMor1Lk.int    ; New Reno Mordino No Lock/No Ignore "Locker"
{1308}{}{锁柜}                        # niBoxrLk.int    ; New Reno Boxer "Locker"
{1309}{}{锁柜}                        # niBis1Lk.int    ; New Reno Bishop Family OK "Locker"
{1310}{}{锁柜}                        # niPornLk.int    ; New Reno Porn Actress "Locker"
{1311}{}{锁柜}                        # niBtchLk.int    ; New Reno Bitch "Locker"
{1312}{}{锁柜}                        # niBis2Lk.int    ; New Reno Bishop Family NO IGNORE "Locker"
{1313}{}{锁柜}                        # niEldrLk.int    ; New Reno Eldridge "Locker"
{1314}{}{锁柜}                        # niWrT1Lk.int    ; New Reno Wright Teen NO IGNORE "Locker"
{1315}{}{锁柜}                        # niOWriLk.int    ; New Reno Orville Wright "Locker"
{1316}{}{锁柜}                        # niWrT2Lk.int    ; New Reno Wright Teen FAMILY IGNORE "Locker"
{1317}{}{锁柜}                        # niMor1Lk.int    ; New Reno Mordino FAMILY IGNORE "Locker"
{1318}{}{锁柜}                        # niMyGdLk.int    ; New Reno Myron Guard "Locker"
{1319}{}{锁柜}                        # niMor2Lk.int    ; New Reno Mordino NO IGNORE "Locker"
{1320}{}{锁柜}                        # niMyrnLk.int    ; New Reno Myron "Locker"
{1321}{}{锁柜}                        # niChp1Lk.int    ; New Reno Chop Shop Boy LOCKED "Locker"
{1322}{}{锁柜}                        # niChp2Lk.int    ; New Reno Chop Shop Boy NO-LOCK "Locker"
{1323}{}{锁柜}                        # niTryLk.int     ; New Reno Tray "Locker"
{1324}{}{锁柜}                        # niMor3Lk.int    ; New Reno Mordino locker, no warning
{1325}{}{地图}                    # rndtoxic.int    ; Random Toxic Map
{1326}{}{你看不到我}              # ecirrad.int     ; critter that irradates
{1327}{}{铁皮人}                  # ecTinWod.int    ; Tin Woodsman
{1328}{}{地图}                    # rndTinWd.int    ; Tin Woodsman Map Script
{1329}{}{石阵}               # ecGrdFrv.int    ; Guardian of Forever
{1330}{}{}                              # rndForvr.int    ; Guardian of Forever Rnd Enct Map Script
{1331}{}{控制器}                      # ecGrdTrm.int    ; Guardian of Forever Water Chip Terminal
{1332}{}{锁柜}                        # niEld2Lk.int    ; New Reno Eldridge "Locker" HARD LOCK
{1333}{}{}                              # SiRagobj.int    ; Uhh box that Rondo cares
{1334}{}{地图}                    # SFCHINA2.int    ; China 2 map
{1335}{}{安全机器人}                  # WCDedBot.int    ; Fighting Bot that does nothing
{1336}{}{安全机器人}                  # KCWupass.int    ; Klamath Guard Robot under Toxic Caves
{1337}{}{锁柜}                        # viHarWch.int    ; VCty - Harry Watch Script
{1338}{}{锁柜}                        # viEdWch.int     ; VCty - Ed Watch Script
{1339}{}{锁柜}                        # viAndWch.int    ; VCty - Doc Andrew Watch Script
{1340}{}{锁柜}                        # viLynWch.int    ; VCty - Lynette Watch Script
{1341}{}{锁柜}                        # viGrgWch.int    ; VCty - Gregory Watch Script
{1342}{}{锁柜}                        # viCGWch1.int    ; VCty - Prison Door Watch Script
{1343}{}{锁柜}                        # viCGWch2.int    ; VCty - Greeting Watch Script
{1344}{}{锁柜}                        # viRNWch1.int    ; VCty - Randal1 Watch Script
{1345}{}{锁柜}                        # viRNWch2.int    ; VCty - Randal2 Watch Script
{1346}{}{锁柜}                        # viStkWch.int    ; VCty - Stark Watch Script
{1347}{}{锁柜}                        # viBarWch.int    ; VCty - Barkus Watch Script
{1348}{}{锁柜}                        # viVLWch1.int    ; VCty - Valerie1 Watch Script
{1349}{}{锁柜}                        # viVLWch2.int    ; VCty - Valerie2 Watch Script
{1350}{}{锁柜}                        # viWalWch.int    ; VCty - Wallace Watch Script
{1351}{}{锁柜}                        # viSkvWch.int    ; VCty - Greeting Watch Script
{1352}{}{锁柜}                        # viInWch1.int    ; VCty - InGrd Watch Script
{1353}{}{锁柜}                        # viInWch2.int    ; VCty - InGrd Watch Script
{1354}{}{锁柜}                        # viInWch3.int    ; VCty - InGrd Watch Script
{1355}{}{锁柜}                        # viFamWch.int    ; VCty - GenFam Watch Script
{1356}{}{锁柜}                        # viCsWch1.int    ; VCty - Cassidy Watch Script
{1357}{}{码头的流浪汉}                 # FCDocSqa.int    ; San Fran - Doc Squatter
{1358}{}{码头的小孩}                      # FCDocKid.int    ; San Fran - Doc Kids
{1359}{}{地图}                    # RndWhale.int    ; Random Whale Script
{1360}{}{派西．克普}                   # gcPercy.int     ; Percy Crump, Gecko Merchant
{1361}{}{箱子}                           # giPerBox.int    ; Percy's Stock Box
{1362}{}{箱子}                           # giJnkBox.int    ; Gecko Junkyard Temp Inventory Box
{1363}{}{门}                          # niWriDor.int    ; New Reno Wright Room Door
{1364}{}{伟大的安安妮斯}             # dcAnan.int      ; The Great Ananias, Mummy Master
{1365}{}{地图}                    # RndUVilg.int    ; Unwashed Villager map
{1366}{}{无知村民}             # ECWash.int      ; Unwashed Villagers... Ug You figure out where they go.
{1367}{}{Spammer}                       # ECSpammr.int    ; Spammer in Unwashed Encounter
{1368}{}{Map}                           # eiSanMap.int    ; Military Base San Francisco Map
{1369}{}{地图}                    # RndShutl.int    ; Random Shuttle Map
{1370}{}{地图}                    # rndParih.int    ; Random Pariah Map Script
{1371}{}{地图}                    # rndBHead.int    ; Random Big Head map
{1372}{}{地图}                    # rndcafe.int     ; Random Cafe Map
{1373}{}{核子可乐贩卖机}             # ZINuke.int      ; Nuka-Cola Machine
{1374}{}{码头}                          # sfdock.int      ; map script for San Fran Dock
{1375}{}{门}                          # ciCrisDr.int    ; Chris's Door
{1376}{}{地雷}                     # rtlndmin.int    ; Redding Land Mines
{1377}{}{地雷}                     # wtlndmin.int    ; Sierra Depot Land Mines
{1378}{}{你的配偶}                       # ncExSpou.int    ; New Reno Ex-Spouse script
{1379}{}{梅尔}                           # ECMel.int       ; Mel that Dogmeat Creates.
{1380}{}{通风口}                          # ciVent.int      ; Vent into Navarro
{1381}{}{凯文}                         # ccKevin.int     ; Kevin in Navarro
{1382}{}{警铃}                         # csAlarm.int     ; Navarro base on alert lights
{1383}{}{锁柜}                        # ciQunWch.int    ; Quincy Locker watch script
{1384}{}{锁柜}                        # ciRulWch.int    ; Raul Locker Watch Script
{1385}{}{锁柜}                        # ciCmdWch.int    ; Commanded Locker Watch Script
{1386}{}{}                              # SSSign.int      ; NCR Statue
{1387}{}{}                              # ctFob.int       ; Fob EXP Spatial Script
{1388}{}{}                              # ctPlans.int     ; Vertibird EXP Spatial Script
{1389}{}{}                              # ctK9Part.int    ; K9 Part EXP Spatial Script
{1390}{}{}                              # csArea2.int     ; Script to signal if dude enters an area
{1391}{}{}                              # csOpen2.int     ; Script to signal if dude uses door w/o permision (in Navarro)
{1392}{}{}                              # ctSound.int     ; Soundproof Room Spatial Script
{1393}{}{}                              # csOpen3.int     ; Script to signal if dude uses door w/o permis
{1394}{}{私贩酒者}                    # ECTlkMon.int    ; Talking Moonshiners
{1395}{}{}                              # ziWeakLk.int    ; Generic Weak Lock Watch Script
{1396}{}{}                              # ziMedmLk.int    ; Generic Medium Lock Watch Script
{1397}{}{演艺团小孩}                     # dcCarnKd.int    ; Carny Kid - The Den
{1398}{}{}                              # ciDocWch.int    ; Raul Locker Watch Script
{1399}{}{}                              # ziHardLk.int    ; Generic Hard Lock Watch Script
{1400}{}{矿坑}                          # CIMine.int      ; Mines in Raiders Cave
{1401}{}{锁柜}                        # niBisHLk.int    ; New Reno Bishop Hard Locker
{1402}{}{门}                          # niBisHDr.int    ; New Reno Bishop Hard Locked Door
{1403}{}{}                              # ntRicRom.int    ; New Reno Richard Wright Room Spacial
{1404}{}{}                          # MIMirDor.int    ; Miria's Bedroom Door  
{1405}{}{}                          # MIDavDor.int    ; Davin's Bedroom Door 
{1406}{}{}                          # SIPtbox2.int    ; box where Merk hides your car trunk stuff
{1407}{}{}                          # sfshutl1.int    ; map script to Hubologist entrance (shuttle)
{1408}{}{}                          # abbey.int       ; Abbey map script
{1409}{}{}                          # abbilbox.int    ; bill's storage box
{1410}{}{比尔}                      # abbill.int      ; Abbey Bill
{1411}{}{}                          # abbook.int      ; Abbey library book
{1412}{}{小孩}                     # abchild.int     ; Abbey child
{1413}{}{死亡爪}                # abdeathc.int    ; Dave's Door
{1414}{}{伊莱恩姐妹}             # abelaine.int    ; Dave's Door
{1415}{}{坟墓}                     # abgrave1.int    ; Dave's Door
{1416}{}{坟墓}                     # abgrave2.int    ; Dave's Door
{1417}{}{汉克兄弟}              # abhank.int      ; Dave's Door
{1418}{}{修道院医生}              # abhealer.int    ; Dave's Door
{1419}{}{约翰}              # abjohn.int      ; Dave's Door
{1420}{}{马克斯}               # abmax.int       ; Dave's Door
{1421}{}{商人}                  # abmerch1.int    ; Dave's Door
{1422}{}{商人}                  # abmerch2.int    ; Dave's Door
{1423}{}{商人守卫}            # abmergrd.int    ; Dave's Door
{1424}{}{彼得斯夫人世间}             # abmsptsn.int    ; Dave's Door
{1425}{}{修道院市民}             # abpeople.int    ; Dave's Door
{1426}{}{彼得斯先生}              # abpetson.int    ; Dave's Door
{1427}{}{抽水机}                # abpump.int      ; Dave's Door
{1428}{}{塞约尔}            # absamuel.int    ; Dave's Door
{1429}{}{修道院市民}             # abstand.int     ; Dave's Door
{1430}{}{托马斯}            # abthomas.int    ; Dave's Door
{1431}{}{汤姆}                       # abtom.int       ; Dave's Door
{1432}{}{Abbey computer}            # acompu.int      ; Dave's Door
{1433}{}{Abbey Head Monk}           # ahmonk.int      ; Dave's Door
{1434}{}{Abbey monk}                # amonk1.int      ; Dave's Door
{1435}{}{Abbey monk}                # amonk2.int      ; Dave's Door
{1436}{}{Abbey monk}                # amonk3.int      ; Dave's Door
{1437}{}{Abbey monk}                # amonk4.int      ; Dave's Door
{1438}{}{Brother Paul}              # amonk5.int      ; Dave's Door
{1439}{}{Tribal}                    # atribal.int     ; Dave's Door
{1440}{}{Brother Matthew}              # abmatt.int      ; Abbey Matthew
{1441}{}{map}                           # vill.int      ; Vault Village map script
{1442}{}{Mole Rat}                      # zclvillrat.int      ; Vault Village Monster
{1443}{}{Ann}                           # vilann.int      ; Ann in Village
{1444}{}{Head Warrior}                  # tribec1.int     ; script for head warrior
{1445}{}{Marli}                         # tribec2.int     ; Script for Marli at well in tribe
{1446}{}{Villagers}                     # tribec3.int     ; script for random people in tribe
{1447}{}{Shaman}                        # tribec4.int     ; script for tribe shaman
{1448}{}{Ghost}                         # tribec5.int     ; script for ghost in tribe
{1449}{}{Tribal}                        # tribec6.int     ; man outside tent for sulik's sister.
{1450}{}{Kurisu}                        # tribec7.int     ; sulik's sister script
{1451}{}{水井}                          # tribei1.int     ; script for well in tribe
{1452}{}{Tribe map}                     # tribem1.int     ; map script for tribe
{1453}{}{Tribal}                        # tribec8.int     ; tribal fishermen/women
{1454}{}{Serin}                         # tribec9.int     ; Missing Tribal (Serin)
{1455}{}{Tribe map2}                    # tribem2.int     ; Primitive Tribe Map 2
{1456}{}{Tribe map 2 - spacial 1}       # tribesp1.int    ; cave entrance spacial
{1457}{}{Tribe map 2 - spacial 2}       # tribesp2.int    ; cavein spacial
{1458}{}{Gecko}                         # tribec10.int    ; Gecko in Tribe Cave
{1459}{}{Cave Guard}                    # tribec11.int    ; Tribal guarding entrance to cave
{1460}{}{dead body}     {尸体}     # tribec5a.int    ; Karla's dead body
{1461}{}{woods spacial}                 # tribesp3.int    ; spacial to trigger seeing the ghost
{1462}{}{Don}                           # slvcc1.int      ; Head of Slaver Camp
{1463}{}{奴隶商人}                        # slvcc2.int      ; Guards at Slaver Camp
{1464}{}{地图}                    # slvcm1.int      ; Map Script to Slaver's Camp
{1465}{}{狗}                           # slvcc3.int      ; guard dog on Slaver Map
{1466}{}{奴隶商人}                        # slvcc5.int      ; Slaver on patrol
{1467}{}{奴隶}                         # slvcc4.int      ; slaves at Slaver Camp
{1468}{}{slavepen door}                 # slvco1.int      ; script to locked slavepen door
{1469}{}{Shelf}                         # hicdshlf.int    ; Chad's Shelf in BH map 2
{1470}{}{门}                          # hichaddr.int    ; Door to Chad's house in BH 2
{1471}{}{Little Johnny}                 # dcliljny.int    ; Abused boy in Den Residential
{1472}{}{Little Johnny's Father}        # dcljfthr.int    ; Drunken Father of Johnny
{1473}{}{流浪汉}                      # dcaddct2.int    ; Addicts who live in building which will become the orphanage
{1474}{}{Drug Dealer}                   # dcdealer.int    ; Dealer/Body guard in Den Residential
{1475}{}{Den Resident}                  # dcpeasnt.int    ; Citizen of Den Residential
{1476}{}{孤儿}                        # dcorphn2.int    ; Orphan living at the Orphanage
{1477}{}{平民}                       # dcpesnt2.int    ; Peasant 2 of Den Residential
{1478}{}{地图}                    # gcenclen.int    ; Enclave Verti Encounter near Gecko
{1479}{}{Enclave Guard}                 # gcenc.int       ; gecko enclave patrol guard
{1480}{}{Enclave Guard}                 # gcenc2.int      ; gecko enclave patrol leader
{1481}{}{保险箱}                          # hisafe.int      ; safe at hubologist stash
{1482}{}{士兵}                         # hcdorgrd.int    ; Door Guard at Hub Stash
{1483}{}{哈伯教}                    # hcstldr.int     ; Leader at the Hub Stash
{1484}{}{Hubologist Guard}              # hcguard.int     ; generic Hub stash guard
{1485}{}{Hubologist Guard}              # hcguard2.int    ; generic Hub stash guard
{1486}{}{Metal Door}                    # himndor.int     ; Main Door to Hubologist Stash
{1487}{}{地图}                    # hubstash.int    ; Map script to Hubologist Stash
{1488}{}{container script}              # hicontnr.int    ; script to containers in Hub Stash
{1489}{}{双头牛}                       # kcdunbra.int    ; Dunton's brahmin in Klamath
{1490}{}{门}                          # slvco2.int      ; door to slave holding (not the pen)
{1491}{}{大门}                          # slvco3.int      ; script to gate of big slave pen at slavers camp
{1492}{}{Tribal Chief}                  # tribec12.int    ; Chief to primitive tribe
{1493}{}{Barking Man}                   # ncbrkmn.int     ; Barking man in New Reno
{1494}{}{epax map script}               # epa1.int        ; EPA Map Script (epax.map)
{1495}{}{EPA MAIN}                      # epa2.int        ; SubLevels Map
{1496}{}{EPA warehouse map}             # epa3.int        ; map for Doctor's warehouse
{1497}{}{Mr. handy Robot}               # epac1.int       ; Script for depressed Mr Handy
{1498}{}{Hologram 00000}                # epac2.int       ; Hologram 00000 script
{1499}{}{The Brave Little Toaster}      # epac3.int       ; Talking Toaster
{1500}{}{Hologram 10001}                # epac4.int       ; Script for Hologram 10001
{1501}{}{Hologram 12001}                # epac5.int       ; Script Hologram 12001
{1502}{}{Hologram 10031}                # epac6.int       ; Script for Hologram 10031
{1503}{}{Hologram 40011}                # epac7.int       ; Script for Hologram 40011
{1504}{}{EPA plant}                     # epac8.int       ; Script for EPA Plants
{1505}{}{Mr. Chemmie!}                  # epac9.int       ; Script for crafting computer
{1506}{}{Dex}                           # epac10.int      ; Script for Diplomatic/Evil player
{1507}{}{Cat Jules}                     # epac11.int      ; Script for combat char from the vats
{1508}{}{Kitsune}                       # epac12.int      ; Script for Stealth Character
{1509}{}{战士}                       # epac13.int      ; Doctor's personal bodyguards
{1510}{}{Bug Spray}                     # epac14.int      ; Script for bug spray
{1511}{}{Doctor's Prisoner}             # epac15.int      ; Script for captured tribals
{1512}{}{巨蚁}                     # epac16.int      ; Script for EPA ants
{1513}{}{The Doctor}                    # epac17.int      ; Script for EPA Doctor
{1514}{}{Fruit Fly}                     # epac18.int      ; Script for mutant fruit flies
{1515}{}{Creature}                      # epac19.int      ; Script for doctors crestures
{1516}{}{机器人}                         # epac20.int      ; Script for the moving robots
{1517}{}{机器人}                         # epac21.int      ; robot script
{1518}{}{EPA Leaflet}                   # epai1.int       ; A leaflet for the EPA
{1519}{}{Voice Computer}                # epai2.int       ; Script for voice computer
{1520}{}{Research Computer}             # epai3.int       ; Script for main research computer
{1521}{}{Electric Chair Computer}       # epai4.int       ; Script for Electric Chair Computer
{1522}{}{Electronic door}               # epai5.int       ; Script for Electronic doors
{1523}{}{Hologram Generator}            # epai6.int       ; Script for Hologram Generator
{1524}{}{安全门}                 # epai7.int       ; Script for Security doors
{1525}{}{电梯门}                 # epai8.int       ; Script for Elevator doors
{1526}{}{门}                          # epai9.int       ; Script for doors on ground level
{1527}{}{Random Chemicals}              # epai10.int      ; Script for Random Chemicals
{1528}{}{Fertile ground}                # epai11.int      ; script for ground in arroyo
{1529}{}{Fertile ground}                # epai12.int      ; fertile ground 2 script
{1530}{}{Hibernation Computer}          # epai13.int      ; Script for Hibernation Computer
{1531}{}{Lighting Generator}            # epai14.int      ; Script for Lighting Generator
{1532}{}{Forcefield}                    # epai15.int      ; Script for forcefield to release Holograms
{1533}{}{Plant spray}                   # epai16.int      ; Script for Plant spray
{1534}{}{Magnetic coil computer}        # epai17.int      ; Script for Magnetic coil computer
{1535}{}{Forcefield}                    # epai18.int      ; Script for Forcedfield to warriors
{1536}{}{Projection machine}            # epai19.int      ; Script for projection of Hologram00000
{1537}{}{门}                          # epai20.int      ; door to chemical level
{1538}{}{电脑}                      # epai21.int      ; Location Finder
{1539}{}{门}                          # epai22.int      ; Script for doors that look like elevators
{1540}{}{电脑}                      # epai23.int      ; Script for computer controlling forcefields
{1541}{}{Forcefield}                    # epai24.int      ; Script for forcefield for critters
{1542}{}{Dynamite}                      # epai25.int      ; Script for dynamite
{1543}{}{Dynamite Trigger}              # epai26.int      ; Script for dynamite trigger
{1544}{}{Stuff on Desk}                 # epai27.int      ; Script for finding paper
{1545}{}{锁柜}                        # epai28.int      ; Script for passcoded locker
{1546}{}{Spatial Script}                # epas1.int       ; Elevator Spatial Script
{1547}{}{Spatial Script}                # epas2.int       ; Gas Level Spatial Script
{1548}{}{Spatial Script}                # epas3.int       ; Spatial script for electric chair
{1549}{}{Spatial Script}                # epas4.int       ; Spatial script for chemicals
{1550}{}{Spatial Script}                # epas5.int       ; Spatial script for elevator2
{1551}{}{Spatial Script}                # epas6.int       ; Spatial script for message about magnetic field
{1552}{}{Spatial Script}                # epas7.int       ; Spatial script on entry to the gas areas
{1553}{}{Spatial Script}                # epas8.int       ; Spatial script for access to vents idea
{1554}{}{Air Conditioning Vent}         # epai29.int      ; Vent to allow player to enter vent shafts of epa
{1555}{}{Fan}                           # epai30.int      ; Left Fan Script
{1556}{}{Fan}                           # epai31.int      ; Right Fan Script
{1557}{}{spatial script}                # epas2a.int      ; Fumes near Mr. Chemmie (become harmless when fans fixed)
{1558}{}{电脑控制台}             # epai32.int      ; EPA Biology Terminal
{1559}{}{fertile ground}                # epai33.int      ; Ground where EPA seeds can be planted
{1560}{}{spatial}                       # epas9.int       ; Spatial script for sprouted seeds
{1561}{}{A hologram}                    # epac22.int      ; Malfunctioning hologram
{1562}{}{spatial}                       # epas10.int      ; teleports dude_obj to maze
{1563}{}{}                              # epac23.int      ; Monster in Doctor's maze
{1564}{}{hologram computer}             # epai34.int      ; machine controlling hologram that gives static
{1565}{}{小孩}                         # vilchild.int    ; Children at Vault Village
{1566}{}{spatial}                       # vsraispt.int    ; spatial for catching the raiders in the act at VC
{1567}{}{Vertibird}                     # civerti.int     ; Flyable Vertibird
{1568}{}{电脑}                      # cisactrl.int    ; Navarro Satellite control computer
{1569}{}{spatial}                       # qsvertel.int    ; spatial for vertibird elevator at enclave
{1570}{}{Mr. Handy}                     # qcwrkbot.int    ; Worker bot (enclave verti pad)
{1571}{}{Nuke}                          # qinuke.int      ; Nuke at the Enclave
{1572}{}{水井}                          # viwell.int      ; VC Courtyard Well
{1573}{}{水井}                          # giwell.int      ; Gecko Well
{1574}{}{}                              # patchinf.int    ; Patch Information Script
{1575}{}{NCR Ranger}                    # scrangr.int     ; Ranger at a safe house
{1576}{}{object name}                   # ncrngsh1.int    ; Maps script to Ranger Safe House 1
{1577}{}{object name}                   # ncrngsh2.int    ; Maps script to Ranger Safe House 2
{1578}{}{object name}                   # ncrngsh3.int    ; Maps script to Ranger Safe House 3
{1579}{}{Map}                           # sirngmap.int    ; Ranger Safe House Map
{1580}{}{NCR Ranger}                    # scatkrng.int    ; Ranger that aids you in attack on Slaver Camp
{1581}{}{奴隶商人}                        # scatkslv.int    ; Slaver that aids you in attack on Ranger Safe Houses
{1582}{}{}                              # ktcavn1.int     ; creates rubble when you destroy supports
{1583}{}{}                              # ktcavn2.int     ; creates rubble when you destroy supports
{1584}{}{}                              # ktcavn3.int     ; creates rubble when you destroy supports
{1585}{}{}                              # ktcavn4.int     ; creates rubble when you destroy supports
{1586}{}{}                              # klaratcv.int    ; Rat Caves at Klamath
{1587}{}{}                              # rtcavn1.int     ; Creates a cave in if the support beam is destroyed
{1588}{}{}                              # scdmymk.int     ; Dummy script for Merk and his guards
{1589}{}{门}                          # kivicdor.int    ; Door to Vic's house in Klamath
{1590}{}{}                              # simrkstr.int    ; Script to stairs leading to Merk's basement
{1591}{}{暴徒}                          # dcg1grd2.int    ; Tyler's Friend (he's having the party)
{1592}{}{trip wire}                     # witripwr.int    ; Trip Wire in SAD (level 2)
{1593}{}{trip wire spatial}             # wstripwr.int    ; Spatial for Trip Wire in SAD (level 2)
{1594}{}{Prostitute}                    # dcprosti.int    ; Prostitute at Tyler's Party (Den)
{1595}{}{黏液}                           # esgoo.int       ; Goo in EPA
{1596}{}{Spatial}                       # wstrpwr2.int    ; Spatial that trips the wire in SAD
{1597}{}{Hibernation Chamber spatial}   # eshib.int       ; Hibernation Chamber spatial
{1598}{}{}                              # nscody.int      ; Spatial script for Cody's death
{1599}{}{Locker}                        # eplkr.int       ; Script controlling the lockers holding the NPC's belongings (EPA)
{1600}{}{Map Script}                    # easter.int      ; RP Easter Egg Map Script
{1601}{}{Modder}            		# eastereg.int    ; Script for all those who helped make the RP possible
{1602}{}{Smoking}            		# zismoke.int     ; Script used by cigs/weed
{1603}{}{Peeing}            		# peeing.int      ; Script for player peeing
{1604}{}{Map Script}                    # abbasem.int     ; Abbey Basement
{1605}{}{Map Script}                    # abundgr.int     ; Abbey Underground
{1606}{}{Merchant}                      # tribemer.int    ; Roy the merchant
{1607}{}{Merchant Guard}                # tribemg1.int    ; Warren - Roy's bodyguard
{1608}{}{Merchant Guard}                # tribemg2.int     ; Second guard for Roy the Merchant
{1609}{}{Merchant Map}                  # merchant.int     ; Map Script to Primitive Tribe Merchant Encounter
{1610}{}{computer}                      # epai35.int      ; EPA museum computer
{1611}{}{computer}                      # epai36.int      ; EPA petting zoo computer
{1612}{}{auto-doc}                      # epai37.int      ; EPA Character Modification Machine
{1613}{}{Brother Jason}                 # abjason.int     ; Angry monk at Abbey
{1614}{}{Todd}                          # viltodd.int     ; Little Todd - Vault Village
{1615}{}{Robert Baron}                  # vibaron.int     ; Robert Baron - Vault Village caravan provider
{1616}{}{Guard}                         # vimergrd.int    ; Merchant Guard - Robert Baron
{1617}{}{Crate}                         # tribei2.int     ; Crate of Stimpacks (Primitive Tribe)
{1618}{}{Ravenous Human}                # epac24.int      ; Ravenous Humans at EPA Green Level
{1619}{}{map}                           # vilmerch.int    ; Vault Village Merchant Map
{1620}{}{force field panel}             # epai38.int      ; force field panel (EPA level 7)
{1621}{}{Fan}                           # epai39.int      ; Fan to enter EPA base
{1622}{}{Guard}                         # fcbtgrd.int     ; Shi Motor Boat Guard
{1623}{}{Motor Boat}                    # sfmboat.int     ; Script to Motor Boat at Shi Docks
{1624}{}{Guard}                         # fcbtech.int     ; Shi Sub Tech Guard
{1625}{}{Junk}                          # abjunk.int      ; Abbey Junk Piles
{1626}{}{stairs}                        # epai40.int      ; EPA Greenhouse stairs
{1627}{}{elevator shaft}                # epai41.int      ; EPA broken elevator shaft entrance
{1628}{}{spatial}                       # epas11.int      ; EPA elevator shaft entrance spatial
{1629}{}{elevator shaft}                # epai42.int      ; EPA elevator shaft level 1
{1630}{}{Locker}                        # epai43.int      ; EPA Locker with Solar Scorcher
{1631}{}{Dock Guard}                    # fcdokgrd.int    ; Shit Guard at Motor Boat
{1632}{}{Technician}                    # fcsbtec1.int    ; Sub Power Console Techie
{1633}{}{Technician}                    # fcsbtec2.int    ; Sub Target Console Techie
{1634}{}{Technician}                    # fcsbtec3.int    ; Sub Torpedo Console Techie
{1635}{}{spatial}                       # httunnel.int    ; spatial script for Broken Hills tunnels
{1636}{}{Dock Worker}                   # fcdkwrk2.int    ; Named Shi Dock Worker (gives info about sub)
{1637}{}{map script}                    # sfsub.int       ; Shi Sub Map
{1638}{}{Door}                          # fssubdr.int     ; Shi Sub Rusted Door
{1639}{}{spatial}                       # fssubint.int    ; Shi Sub Interior Greeting Spatial
{1640}{}{power console}                 # fcsubpwr.int    ; Shi Sub Power Console
{1641}{}{torpedo console}               # fcsubtco.int    ; Shi Sub Torpedo Console
{1642}{}{targeting console}             # fcsubtar.int    ; Shi Sub Targeting Console
{1643}{}{torpedo bay}                   # fcsubtor.int    ; Shi Sub Torpedo Bay
{1644}{}{sub hatch}                     # fcsubhat.int    ; Shi Sub Outer Hatch
{1645}{}{Guard}                         # fcsubgrd.int    ; Shi Sub Guard
{1646}{}{vertibird}                     # ncverti.int     ; Vertibird at Salvatore Secret Transaction
{1647}{}{spatial}                       # fssubsp.int     ; Shi Sub Interior Text Spatial
{1648}{}{serum}                         # epai44.int      ; Agility +1 serum at the EPA
{1649}{}{Old Caravan Guard}             # abguard.int     ; Retired Caravan Guard
{1650}{}{Dr. Sheng}                     # fcdrshng.int    ; Dr. Sheng
{1651}{}{Plant Creature}                # fcplntmn.int    ; Dr. Sheng's Plant Creature
{1652}{}{Dr. Sheng's hideout}           # sfsheng.int     ; Dr. Sheng's hideout
{1653}{}{Door}                          # fcshngdr.int    ; Door to Dr. Sheng's laboratory
{1654}{}{Door}                          # fcshngd2.int    ; Door to Dr. Sheng's experiments
{1655}{}{spatial}                       # tribesp4.int    ; Spatial script upon entering the main area of Umbra Tribe
{1656}{}{Repair Robot}                  # wcrpbot2.int    ; Sierra Base, Repair Robot (generic), level 4
{1657}{}{Security Robot}                # wcscbot2.int    ; Sierra Base, Security Robot (generic), level 4
{1658}{}{Door}                          # wibaydr2.int    ; Sierra Base Repair Bay Door (level 4)
