#
#
#
#
#
{0}{}{游戏选项}
{1}{}{荧幕设置}

{50}{}{荧幕设置}
{51}{}{自订}
{52}{}{宽度}
{53}{}{高度}
{54}{}{确定}
{55}{}{取消}
{56}{}{异尘余生必须重新启动以应用设置。}
{57}{}{你现在就想要重新启动异尘余生吗？}
{58}{}{是}
{59}{}{否}
{60}{}{}

{100}{}{分辨率}
{101}{}{大小}
{102}{}{色彩品质}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{改变侧边栏样式}
{107}{}{翻转列表}
{108}{}{窗口模式}
{109}{}{设置滚动键}
{110}{}{界面大小X2}
{111}{}{刷新速率}

{130}{}{Win键}
{131}{}{选择}
{132}{}{名称}

{140}{}{图像显示模式:}
{141}{}{基础}
{142}{}{Sfall DirectX 9 模式:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}

{150}{}{Panel Scaling}
{151}{}{None}
{152}{}{Fit}
{153}{}{Fill}

{154}{}{Movies}
{155}{}{Splash}
{156}{}{Help}
{157}{}{Death}
{158}{}{End Slides}
{159}{}{Main Menu}

{200}{}{Sfall}
{201}{}{SCALE-TO: RES.}
{202}{}{DX-9 模式}
{203}{}{关}
{204}{}{全屏幕}
{205}{}{窗口模式}
{206}{}{GPU输出中}
{207}{}{这个选项在基本图像模式下该选项无效}

{250}{}{忽略PC滚动限制}
{253}{}{寻路距离限制}
{254}{}{普通}
{255}{}{最大}
{256}{}{使用战争迷雾}
{257}{}{迷雾可见度}
{258}{}{黑暗}
{259}{}{明亮}

{300}{}{按下A键或ESC来取消.}

{500}{}{高分辨率补丁设置.}
{501}{}{Setup the Screen Resolution, Colour mode and Refresh Rate for FullScreen Mode.}
{502}{}{Setup the Fullscreen Colour output here.}
{503}{}{Setup the Fullscreen Refresh Rate here. Set this to '0' for the driver default setting.}
{504}{}{Customize the Fullscreen Width by clicking the number box.}
{505}{}{Customize the Fullscreen Height by clicking the number box.}
{506}{}{Enable or Disable Window Mode.}
{507}{}{In Window Mode, this is the key you will hold down when using the mouse to scroll the Game and World maps.}
{508}{}{Press the red button to select a different key. Or click the number box to edit the Windows Virtual key code.}
{509}{}{The name of the currently selected key.}
{510}{}{Enable X2 scaling. This will also up the min res to 1280x960. With Window mode requiring more space for its frame.}
{511}{}{Enable or Disable Fog Of War. For best results this should be enabled before entering a map for the first time.}
{512}{}{Adjust the light level and the Mouse 'look at' visibility of floors, walls and scenery under the fog.}
{513}{}{Floors, walls and scenery will always be visible and Mouse "look at" will function normally.}
{514}{}{Floors, walls and scenery will be darkened and unresponsive to Mouse "look at" until discovered.}
{515}{}{When enabled, scrolling away from the Player Character is unlimited. This works well if Fog Of War enabled.}
{516}{}{Increase the number of search nodes to extend the path finding distance. 20 levels in 2000 node increments.}
{517}{}{2000 path search nodes (original value). Note: Each level requires an additional 156.25 KB of memory.}
{518}{}{40 000 path search nodes. Note: requires 3200000 bytes (3125 KB) of memory.}
{519}{}{Adjust how certain screens are displayed.}
{520}{}{Original size.}
{521}{}{Stretched to fit the size of the screen while maintaining the original aspect ratio.}
{522}{}{Stretched to fill the screen. Note: A space will remain at the bottom of the screen if subtitles are enabled.}
{523}{}{Click below to cycle the in-game interface Side Bar options.}
{524}{}{Apply any changes and Exit.}
{525}{}{Exit without saving.}


