{100}{}{你看见一个计算机终端机。}
{101}{}{你看到达理安的计算机终端机。}
{102}{}{你看到一个标准的计算机终端机。看上去，它相当正常，而且还在等待着新命令输入。}
{103}{}{你很快的用计算机查询所有的数据。在几个个人的记录中你找到几份与新加州共和国有关的详细资料。根据你的分析，新加州共和国的参议会里有个间谍。你把报告拷贝到磁盘里。}
{104}{}{你无法查任何的数据。}
{105}{}{完成。}
{106}{}{除了新加州共和国的参议会里的间谍报告之外，计算机没有其他有用的数据。}
{107}{}{完成。}
