{100}{}{你看到一个计算机终端机。}
{101}{}{你看到一个安全计算机终端机。}
{102}{}{你看到一个标准的计算机终端机。它看起来还在正常运作，并且等待着命令。}
{103}{}{这一个终端机控制的是力场发射器。上面显示所有系统运作正常。}
{104}{}{这一个终端机控制的是力场发射器。上面显示因为电源问题，目前系统是关上的。}
{105}{}{关掉力场。}
{106}{}{打开力场。}
{107}{}{完成。}
{108}{}{你输入关掉力场的命令。}
{109}{}{你看来没有办法得到安全密码将力场关起来。}
{110}{}{完成。}
{111}{}{你输入打开力场的命令。}
{112}{}{你看来没办法得到安全密码来将力场打开。}
{113}{}{完成。}

{114}{}{这一个终端机控制的是力场发射器。上面显示力场是关上的。}
{115}{}{这一个终端机控制的是力场发射器。上面显示力场暂时的被关上了。}
{116}{}{这一个终端机控制的是力场发射器。上面显示力场被破坏了。}
