{100}{}{发电机运转正常，电力已在最高点。}
{101}{}{发电机处于紧急状态，电力在最低点。}
{102}{}{试着找出问题吧。}
{103}{}{我要走了。}
{104}{}{系统里面一定是有那里短路了。紧急的保险丝断掉了，也许你能够将它修好吧。}
{105}{}{你看不出来它有什么问题。}
{106}{}{试着修理它吧。}
{107}{}{该走了。}
{108}{}{你把它修好了，电力也恢复了。}
{109}{}{干！这个比看起来的还难。}
{110}{}{做好了。}
