{100}{}{你看见一位守卫。}
{101}{}{你看见一位穿着动力装甲的守卫。}
{102}{}{你看见一位守卫穿着不同型的动力装甲，他的胸前有一个你没见过的图案。}

{103}{}{不要在这边停留。}
{104}{}{我在工作，没有时间跟你谈话。}
{105}{}{继续走，铁门在那边。}

{106}{}{最好先去领你的军服。}
{107}{}{没穿着军服不要到处乱跑。}
{108}{}{你现在是一个军人，不要没穿着军服的到处乱跑。}

{109}{}{入侵者在前门！}
{110}{}{有入侵者，快响警报！}
{111}{}{快派人去前门，那边有入侵者！}

{112}{}{前门的警报响了！}
{113}{}{大家戒备！前门被攻击了！}
{114}{}{前门现在处于红色戒备中！}

{115}{}{我们会把你打进地狱的！}
{116}{}{英克雷军会统治世界的！}
{117}{}{英克雷军会活下来的，所以你得死！}
