# 8. BF: Hostile Primitive
{245}{}{安静点！他们来了。}
{246}{}{杀死坏人。}
{247}{}{不要将我的家人抓走。}
{248}{}{我要保护我的家人。}
{249}{}{一定要躲起来。}
{250}{}{他们是坏人。}

# 9. BF: Hostile Nomad
{260}{}{奴隶贩子要来了。大家小心。}
{261}{}{小心，我想他们就在附近了。}
{262}{}{我会尽全力反抗的。}
{263}{}{他们休想要抓我们去当奴隶。}
{264}{}{那一些奴隶贩子会付出代价的。}
{265}{}{奴隶贩子休想把我的家人带走。}
# looks
# primitive
{100}{}{这一个人看起来很壮。}
{101}{}{他虽然身材不高大，但是相当壮。}

# nomads
{200}{}{他看起来很瘦，但是很生气。}
{201}{}{他看起来还挺壮的。}
{202}{}{他动作相当轻巧。}

{210}{}{她看起来像从来没有洗过澡一样。}
{211}{}{她看起来像是一个战士。}
{212}{}{他看起来好像不太想要惹麻烦一样。}

# 12. Combat Float: Hostile Primitive
{300}{}{死吧！}
{301}{}{杀杀！}
{302}{}{你别想碰我家人的一根汗毛！}
{303}{}{你别想抓走我的家人！}
{304}{}{我会保护家人的！}
{305}{}{去死！}
{306}{}{给我去死！}
{307}{}{死！}
{308}{}{我会对付你的。}

# 13. Combat Float: Hostile Nomad
{350}{}{你休想将我的家人抓走，奴隶贩子！}
{351}{}{死吧，你这奴隶贩子！}
{352}{}{你会付出代价的，王八！}
{353}{}{我会用我的性命保护我的家人的！}
{354}{}{你会付出代价的！}
{355}{}{你别想抓走任何一个人！}
{356}{}{我会让你付出代价的！}
{357}{}{可恶的奴隶贩子！}
{358}{}{你会付出代价的！}
