#0. Look
{100}{}{你看见了一位守卫。}
{101}{}{你看见了一位丽贝卡赌博酒场的守卫。}
{150}{}{他正在看人群中有没有小偷。}
{151}{}{她正在观察房间里的每一个人。}

#1. Hostile
{200}{}{这次你完了。}
{201}{}{这一次你逃不掉了。}

#2. CF: Generic
{210}{}{对不起，贝齐不希望我们来打搅顾客。}
{211}{}{欢迎光临。}
{212}{}{我们绝对不会忍受任何的小偷的。}
{213}{}{在这几面墙里面你是非常安全的。}
{214}{}{丽贝卡卖的都是最好的饮料。}
{215}{}{丽贝卡是我有过最好的老大。}
{216}{}{今天你的运气如何？２１点是我的最爱。}
{217}{}{假如你需要任何东西，贝齐就在那里。}
{218}{}{丽贝卡的赌桌绝对不会骗钱的，去试试你的运气吧。}

#3. Self: Caught Stealing
{230}{}{我们不会忍受你的所作所为的。}
