{100}{}{来吧小老鼠。}
{101}{}{古朗多要用你来炖一锅好吃的。}
{102}{}{来吧，你这小笨蛋。}
{103}{}{好心的古朗多是不会伤害你的。}
{104}{}{好吃的小东西。}
{105}{}{快一点来，小老鼠，我已经很饿了。}
{106}{}{吱！吱～～}
{107}{}{好吧，我骗你的，我其实是要将你吃掉。}

{110}{}{啊，你这只老鼠还真不小。古朗多可以吃一餐好的啦。}
