{100}{}{你看见一个奇特的怪物。}
{101}{}{你看见一个发疯的超级变种人。}
{102}{}{停！}
{103}{}{不要再接近了！伟大的麦尔开命令你！}
{104}{}{看好了，我是世界上的最厉害的魔术师！}
{105}{}{在伟大的麦尔开力量之下发抖吧！}
{106}{}{我的宠物会把你的骨头吃光！}
{107}{}{我警告过你了！攻击，我的宠物们！}

# CREATION COMMENTS
# DEATH CLAWS
{1000}{}{啊！}
{1001}{}{我的爪子宠物会杀你。}
{1002}{}{爪子进攻！}

# FIRE GECKOS
{1010}{}{啊吧达吧啦！}
{1011}{}{麦尔开造火动物烧死人。}
{1012}{}{烧啊，人！}

# FLOATERS
{1020}{}{嗡嗡！}
{1021}{}{利牙动物咬死你！}
{1022}{}{咬碎他！}

# MOLE RATS
{1030}{}{喀咯！}
{1031}{}{他妈的！我只剩下肥鼠了。}
{1032}{}{我快没动物了。}

# OUT
{1050}{}{啊。我没动物可变了。}
