{100}{}{啊！又是一个新成员。}
{101}{}{加入，不然就死路一条！}
{102}{}{尽你的全力吧。}
{103}{}{为你佣兵的身份而自豪吧。}
{104}{}{加入我们吧！}
{105}{}{4F。}
{106}{}{该到别处去看看了。}
{107}{}{去加入海军吧。}
{108}{}{可恶！}
{109}{}{啊！不早了，我得走了！}
{110}{}{新成员。}
{111}{}{上士。}
