{100}{}{你看见……塞特。}
{101}{}{你看见一个头上伸出机器物品的腐烂僵尸。很难说他是不是老了还是傻了。}
{102}{}{你看见塞特。他在自言自语。}
{103}{}{你看见塞特。他在自言自语。}
{104}{}{“德特那普！”}
{105}{}{“德特那普！”}
{106}{}{“德特那普！让我的影子变长吧……”}
{107}{}{嘿嘿。}
{108}{}{德特。}
{109}{}{那普。}
{110}{}{德特那普！}
{111}{}{嘿嘿。我统治耐克拉普思。}
{112}{}{诺密思。所有地方，诺密思。}
{113}{}{“名字是塞特。你的世界全是痛苦。”}
{114}{}{嘿嘿。}
{115}{}{那普。德特。那普德特！}
