{100}{}{这些应该能在市场卖个好价钱。}
{101}{}{小心别弄坏了货。}
{102}{}{你是将会是一个活泼的奴隶。}
{103}{}{这真不妙。}
{104}{}{撤退！}
{105}{}{说不定我应该改卖家具。}
{106}{}{奴隶贩子不应该攻击同伴的。}
{107}{}{工会会听到你的作为的！}
{108}{}{你在 做什么？}
{109}{}{运气好吗？}
{110}{}{找到好奴隶了吗？}
{111}{}{我们正在找新货。}
{112}{}{这是我们的地盘。}
