{100}{}{你看见一个白色的女英雄雕像。}
{101}{}{你看见一位穿着第１３号避难所服装的漂亮女孩。她正在和周围的人谈笑风生。}
{102}{}{你看见一个白色的女英雄雕像。她正在说笑着。}
{103}{}{你看见一个白色的女英雄雕像。她正在说笑着。}
{104}{}{我想我原本是被一个隐形的人所控制着。}
{105}{}{他总是想要偷别人的东西……通常……他都会得手。}
{106}{}{但是……如果没有得手的话……}
{107}{}{我从来都没见过有人存取进度那么多次。}
{108}{}{你知道吗，我很喜欢我穿战斗装甲的样子。}
{109}{}{我从来都没提过，但是伊恩经常在异尘余生一代中常常注视着我。}
{110}{}{那让我感觉挺尴尬的。}
{111}{}{我本来想和游戏制作人说的，但是我不想要小题大作。}
{112}{}{伊恩还挺好好看的；不过他却需要一个新发型。}
{113}{}{并且洗个澡。噢～～}
