{100}{}{你看到一个全身被烧伤的人。}
{101}{}{你看到蜥蝪城的市民。}
{102}{}{他的皮肤是被放射线所烧伤的。}

{110}{}{你好，你需要一些补给吗？}
{111}{}{如果你需要补给，你需要一个请求表格。}
{112}{}{如果你需要什么，你应该去与杰米谈。}
{113}{}{杰米是负责所有补给品的人。}
{114}{}{你最好去与杰米谈谈；他最讨厌就是有人不跟他知会就把东西拿走。}
{115}{}{在你与杰米谈之前我都不能帮你。}
{116}{}{去与杰米谈。}

{120}{}{我想这些老旧的仪表都坏掉了。}
{121}{}{我只不过敲它一下，想要让它正常的运作。}
{122}{}{我不认为这一部机器有正常运作过。}
{123}{}{我很骄傲有着反应炉的工作。}
{124}{}{当所有的仪表都显示红灯时，我就会很开心。}
{125}{}{我希望我们很快就会取得从破碎丘来的另一批铀矿。}
{126}{}{我们快要没有铀矿了。}
{127}{}{我专门从原子中取得能源；你是干什么的呢？}
{128}{}{这里面的温度越来越舒服了。}
{129}{}{在这边工作一段时间之后，你就不再需要看仪表了。}
{130}{}{我好无聊啊，反正这一些仪表都是坏的。}
{131}{}{漏？什么东西在漏？}

{140}{}{这是全蜥蝪城最适合居住的地方。}
{141}{}{暖暖的，好舒服。}
{142}{}{这边随时都是暖暖的，真舒服。}
{143}{}{很惊讶看到你在这边，皮肤光滑的人。}
{144}{}{很多的皮肤光滑的人都很怕放射线。}
{145}{}{如果我一天不接受放射线，就好像一天没有晒太阳一样。}
{146}{}{真高兴。}
{147}{}{啦啦啦……}
{148}{}{如果没有这个反应炉的话，大家都活不下去了。}
{149}{}{希望那些地下掩体市的人不要把我们都杀了。}

{150}{}{谢谢你，谢谢你，谢谢你。}
{151}{}{谢谢你帮我们修好反应炉。}
{152}{}{我们的家园现在安全了，谢谢你。}
{153}{}{我们的反应炉现在可以正常运作了。谢谢你。}
{154}{}{我们的反应炉功率现在好多了。}

{160}{}{我真不敢相信地下掩体市帮助了我们。}
{161}{}{谢谢你帮我们把反应炉的功率提高了。}
{162}{}{我很高兴反应炉的输出更高了。}
{163}{}{这里面最近变得好冷啊。}
{164}{}{这里面不是很冷吗？}

{170}{}{你在这边偷偷摸摸的干什么？}
{171}{}{嗯，我还是看得到你的，知道吗？}
{172}{}{为什么你要用那种奇怪的方法走路？}
{173}{}{我以为我听到大象在走路，原来是你。}
{174}{}{我们都在看着你。}
{175}{}{你最好不要有什么不良的企图。}
{176}{}{如果我们这边有事发生，我们第一个找你。}
{177}{}{卫兵！有一个光皮肤的人正在偷偷摸摸的。}
{178}{}{你一定是有不良的企图。}
