#############################################################
#  Message File: GeckJunk.msg				    #
#							    #
#  Created: August 14, 1998				    #
#							    #
#  Updated:						    #
#############################################################

{100}{}{你进入了蜥蝪城的废车厂。}
