# 0. QUICK LOOK
{100}{}{你看到一个火力很强的佣兵。}

# 0. LOOK
{150}{}{你看到一个穿着皮装甲的男人。他全身都是伤口。不过，他的装甲以及武器都保养的相当好。}
{151}{}{你看到一个火力很强的歹徒。他正在站岗。}

# 1. FLOAT DIALOGUE: INTRUDER (WTG)
{200}{}{看看这小王八蛋……}
{201}{}{有人！}
{202}{}{这一个地区被侵入了！}
{203}{}{兄弟们，有入侵者！}
{204}{}{出动，我们有入侵者！}
{205}{}{看看谁来了。}
{206}{}{可恶！有人发现我们了！}
{207}{}{我们有人侵入这一个地区了。}
{208}{}{你真是走错了地方了，婊子。}
{209}{}{看看这婊子啊……}

# 2. FLOAT DIALOGUE: NORMAL (WTG)
{250}{}{我们得要去喝一杯。}
{251}{}{我们得要到那些山洞中去检查一下……}
{252}{}{巡逻的时间又到了。}
{253}{}{天啊，那个土人还真臭啊。}
{254}{}{可恨的地下掩体市雷射炮。}
{255}{}{我真是懒得在枪上打蜡了。}
{256}{}{我们得这在这外面待多久啊？}
{257}{}{我们应该要离开了。}
{258}{}{我们等不及要回到新里诺了。}
{259}{}{看来那些毒蝎肚子饿了，昨晚听到他们的声音。}
{260}{}{你有没有检查那些矿坑的入口？}
{261}{}{我被队长骂了一顿，因为我差一点让那商人给逃走。}
{262}{}{真不知道我要怎样作才不用穿这制服。}
{263}{}{琳娜特是一个相当漂亮的女人。}
{264}{}{那家伙说的笑话每次当让我笑得半死。}
{265}{}{准备好了。}
{266}{}{队长真是把我给修理惨了。}
{267}{}{我感觉我在这边站了好久了。}
{268}{}{真希望我能够到其它的游戏里面去。}
