# Flee
{100}{}{快跑！}
{101}{}{救命啊！}
{102}{}{我们被地面人攻击了！}
{103}{}{请不要打我！}
{104}{}{为什么我们一定要打起来呢！}

# Attack
{150}{}{滚回去你来的地方吧！}
{151}{}{我们这里不欢迎你！}
{152}{}{你们地面人都是一样的！}
{153}{}{你逃不掉了！}

# General Dialogue (above ground)
{200}{}{嗯！}
{201}{}{砰！}
{202}{}{喔喔喔。}
{203}{}{*鏮*}
{204}{}{*鏮*}

# General Dialogue (below ground)
{250}{}{我们以前是住在地面上的。}
{251}{}{地面长的是什么样子？}
{252}{}{地面的世界好大噢！}
{253}{}{太阳长的是什么样子呢？}
{254}{}{地面人，你好！}

# General Dialogue when Seed is completely done
{300}{}{我早就知道我们是可以信任你的！}
{301}{}{谢谢你能帮我们的忙。}
{302}{}{我很高兴又能见到你。}
