# 0. QUICK LOOK, BOXES (WTG)
{100}{}{你看见几个装满化学药品的箱子。}

# 0. LOOK, BOXES (WTG)
{150}{}{你看见几个装满化学药品的箱子。你不知道那些是什么化学药品，不过它们都被很小心的包装了起来。}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{175}{}{你看见飞鸟。}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{199}{}{你看见飞鸟……一种相当先进的直升机。很不幸的，你不知道要如何操作它。}

# 2. NORMAL ACTION SEQUENCE (WTG)
{200}{}{(这些人让我感到害怕。)}
{000}{}{(住口，他们来了。)}
{000}{}{你有我们要的货吗？}
{000}{}{是的，全部都在这边。如果你要验货的话，请便吧。}
{000}{}{不用了。}
{000}{}{你知道如果药品不合我们的意，会发生什么事吗？}
{000}{}{知道，而你，你带了我们要的雷射枪了吗？}
{000}{}{雷射枪在我们的货舱里面。}
{000}{}{为了要确保交易顺利，我们搬完化学药品之后才会将枪的启动方法给你们。}
{000}{}{好……弟兄们，去搬吧。}
{000}{}{不。}
{000}{}{我们会搬货的。}
{000}{}{当然……嗯……让路给他们。}
{000}{}{好。我们没问题了……所有的人，在这边看着。你，新人，回到新里诺等我们吧。}

# 3. FLOAT SEQUENCE: INTRUDER (WTG)
{250}{}{有人在看我们！}
{000}{}{杀了他们！}
{000}{}{看来我们有个间谍！}
{000}{}{任务中断！货品保险程序启动。}
{000}{}{杀死敌对目标，然后回到基地。}

# 4. FLOAT SEQUENCE: OUT OF POSITION WARNING (WTG)
{300}{}{不要接近那些穿着装甲的，他们会把你大卸八块的。}
{000}{}{回到你的岗位。}
{000}{}{不要那样，那些人不喜欢你这样的。}

# 5. FLOAT SEQUENCE: OUT OF POSITION, FINAL (WTG)
{350}{}{你在干什么？}
{000}{}{回去你的岗位……你他妈的在干……？}
{000}{}{任务中断！货品保险程序启动。}
{000}{}{杀死敌对目标，然后回到基地。}

# 6. VERTIBIRD SEQUENCE: (WTG)
{400}{}{[看来那是一道门，打开并且爬进去吗？]}
{000}{}{是的}
{000}{}{离开}
{000}{}{进入飞鸟里面。}
{000}{}{不要理它。}

# 7. VERTIBIRD: TAKE OFF (7)
{450}{}{[门关上了，飞鸟起飞了，你没有办法把门打开了！]}
{000}{}{不好了……}
{000}{}{完了……}

# 8. DISPLAY TEXT: BOXES (WTG)
{500}{}{这些箱子里面装满了许多的铁容器。从它谨慎的包装上看来，这里面装的是危险的化学药品。}
