{100}{}{你看见一位穿着蓝色的工作服的公民。好像是避难者的衣服，但是后面没有号码。}
{101}{}{你看见地下掩体市公民。}
{102}{}{你看见一位穿着蓝色的工作服的公民。好像是避难者的衣服，但是后面没有号码。}
{103}{}{::拍手::}
{104}{}{英雄来了！你看！}
{105}{}{天啊！英雄来了，来到地下掩体市了！}
{106}{}{您好，队长。}
{107}{}{地下掩体市万岁，队长。}
{108}{}{公民，你好。}
{109}{}{地下掩体市万岁，公民。}
{110}{}{啊！变种人！来人啊！}
{111}{}{啊！僵尸！来人啊！}
{112}{}{你是怎么进来的呢？}
{113}{}{对不起，请问你有白昼通行证吗？}
{114}{}{哼！又是个外人。}
{115}{}{愈来愈多外人进城了???}
{116}{}{我真希望你有个白昼通行证。}
{117}{}{最近好像每个外人都有个白昼通行证耶～～～}
{118}{}{你的英雄事迹，我已略有所闻。你给地下掩体市，给全世界立了大功。}
{119}{}{你与英克雷军大战的事情，连第一公民也佩服。}
{120}{}{听说你南下一游有达到三～番～市～这是真的吗？}
{121}{}{也许地下掩体市应该欢迎外人。}
{122}{}{是真的吗？旧的政府还在打仗吗？}
{123}{}{你应该把你所去的地方在地下掩体市的计算机上纪录下来。}
{124}{}{英雄，你想要留多久就让你留多久。}
{125}{}{你应该把你与英克雷军的大战在地下掩体市的计算机上纪录下来。}
{126}{}{＊哈欠＊???咦？啥？什么事？}
{127}{}{现在拜访有点晚啰???}
{128}{}{大部分的公民都已经睡着了。}
{129}{}{睡觉？已经不睡了。}
{130}{}{请明天早上再回来。我明天还要写清单呢！}
{131}{}{您好，队长。}
{132}{}{地下掩体市万岁，队长。}
{133}{}{我可以给您拿一个甜甜圈吗，队长？}
{134}{}{有什么事情吗，队长？}
{135}{}{我真希望那些肮脏的外人没有找麻烦，队长。}
{136}{}{您有关于外面的世界的故事吗，队长？}
{137}{}{你好，公民。}
{138}{}{地下掩体市万岁，公民。}
{139}{}{我今天心情很好。你呢？}
{140}{}{身为公民，必需写表格。}
{141}{}{我花了一整天的时间来做那个表格，之后再检查。我最爱做列表了。}
{142}{}{我大部分时间都在列表办公室里工作。我们在地下掩体市最爱做表格了。}
{143}{}{我大部分时间都在列表办公室里工作。我们在地下掩体市最爱做表格了。}
{144}{}{听说你还去过外面的世界。在那群肮脏的外人中生活何以残存至今？}
{145}{}{噢！你是那位新的公民。欢迎来到地下掩体市。}
{146}{}{你需要地方住吗？}
{147}{}{议会都是为人民而工作的。}
{148}{}{我们需要保持一个干净的城市。}
{149}{}{仆人啊？仆人只做一些微小的工作。}
{150}{}{那昨天的议会真是相当的有趣啊。}
{151}{}{啥？}
{152}{}{有什么事情需要我帮你吗???外人？}
{153}{}{对不起，你刚才说什么？}
{154}{}{我？我在做事。}
{155}{}{我可以看一下你的白昼通行证吗？}
{156}{}{噢，对不起。我还以为你是个仆人呢！}
{157}{}{我现在真的没空跟一个外人聊天。}
{158}{}{你可以保持距离吗？}
{159}{}{请站那里。}
{160}{}{仆人让我们可以将精力放在更加重要的工作上面。}
{161}{}{仆人啊？仆人只做一些微小的工作。}
{162}{}{嗯，我能闻得出???看得出来你是个外人。}
{163}{}{你是个外人？真奇怪。}
