{100}{}{你看到一个有疲倦神色的妇人。}
{101}{}{你看到史密斯太太。}
{102}{}{你得与我的丈夫谈谈。}
{103}{}{我与我的丈夫都相当的感谢你。}
{104}{}{谢谢你……我与我的丈夫有一样东西要给你，作为谢礼。}
{105}{}{我们很快就会需要那个犁……}
{106}{}{快滚，不然我要叫卫兵了！}
{107}{}{你看起来像是一个好人。可不可以帮我们一个忙呢？}
