{100}{}{你看到一个穿着做工的衣服的壮男人。他眼睛在看地下。}
{101}{}{你看见地下掩体市的一个奴隶。}
{102}{}{你看到一个穿着工作服的壮男人。他眼睛在看地下。}
{103}{}{你看见一个穿着工作服的健康的女人。他的眼睛在看地下。}
{104}{}{你看见地下掩体市的一个奴隶。}
{105}{}{你看见一个穿着工作服的健康女人。他的眼睛在看地下。}
{106}{}{你的英雄事迹，我已略有所闻。你给地下掩体市，给全世界立了大功。}
{107}{}{你与英克雷军的大战连第一公民也佩服。}
{108}{}{我无以为报???只能说声谢谢。}
{109}{}{其他的仆人知道我跟你这位英雄谈话的话一定会羡慕我的。}
{110}{}{是的，队长？}
{111}{}{队长？}
{112}{}{队长有何吩咐？}
{113}{}{队长要我做什么吗？}
{114}{}{对不起，队长。我会更加努力的。}
{115}{}{对不起，队长。我会提高警觉的。}
{116}{}{什么，公民？}
{117}{}{公民？}
{118}{}{公民，有何吩咐？}
{119}{}{公民，要我做什么吗？}
{120}{}{对不起，公民。我会更加努力的。}
{121}{}{对不起，公民。我会提高警觉的。}
{122}{}{城内不容变种人！}
{123}{}{如果他们看到你的变种人朋友，你们会被赶走的。}
{124}{}{城里不可以有变种人。你必需离开这里。}
{125}{}{城内不容僵尸！}
{126}{}{如果他们看到你的僵尸朋友，你们会被赶走的。}
{127}{}{城里不可以已有僵尸。你必需离开这里。}
{128}{}{是的，我已经有主人了。奴仆分配中心里有我的文档。}
{129}{}{请让我走。我是地下掩体市的奴隶。}
{130}{}{我求你：你有没有看到两个黑头发的小孩子？他们两年前被抓去送到北边去了。}
{131}{}{不好意思，我不能跟任何人讲话。}
{132}{}{如果公民抓到我跟奴隶贩子讲话的话，我会被罚的。}
{133}{}{你再继续跟我讲话的话，他们就会把我抓走。}
{134}{}{我不准跟你讲话。我有事情要做的。}
{135}{}{奴隶商人，请走开。请不要给我添麻烦。}
{136}{}{逃？我从来都没试过。这里的生活很好。}
{137}{}{公民跟我说如果我很努力的话，也许有一天我会升为公民喔。}
{138}{}{公民教我们“苦尽甘来”。}
{139}{}{公民说我们的}
{140}{}{还好当初地下掩体市缺少仆人。否则我有可能会被送到新里诺城啰。}
{141}{}{地下掩体市给忠心的仆人更多的食物。}
{142}{}{听说新里诺的奴隶生活都过得很辛苦。}
{143}{}{公民把我的部落的兄弟都带进城来当仆人。}
{144}{}{公民把我带进城来，也教我读书。}
{145}{}{公民对我很好。吃穿不愁。}
{146}{}{我不准跟外人讲话。}
{147}{}{我原先很思念我的家庭，不过已经很久没有见到他们了。}
{148}{}{我是在北边的部落。不过呢，这里的生活比较好。}
{149}{}{我本被擒于丹恩城。幸好结果来到这里。}
{150}{}{听说第一公民常常对她的仆人脾气暴躁。}
{151}{}{我不能跟你讲话。我有事情要做的。}
{152}{}{我必需在一小时内完成任务。}
{153}{}{与外人讲话犯法。}
{154}{}{逃？为什么？}
{155}{}{我可以帮你吗？}
{156}{}{事隔多年，我已经记不清楚了。}
{157}{}{我以前有两个孩子，不过他们被送到北边去了。我真希望有朝一日能够团圆。}
{158}{}{对不起，我没有时间跟你讲话。}
