{100}{}{一个计算机终端机。}
{101}{}{那看起来像是安全终端机。}
{102}{}{你看不懂显示屏幕上写的是什么。}
{103}{}{天网安全系统
					     不准进入}
{104}{}{}
{105}{}{离开}
{106}{}{错误！
								 程序档案不存在
				      请重新启动}
{107}{}{}
{108}{}{}
{109}{}{离开}


{200}{}{看不懂显示屏幕上写的是什么。}
{300}{}{这计算机好像有某种防御系统。}
