{100}{}{你看见了个矮胖的修女。}
{101}{}{你看见了伊莱恩。}
{102}{}{你仍旧看见她。}

{200}{}{祝福你!}
{201}{}{你好，你叫什么名字？}
{202}{}{关于这你能告诉我些什么？}
{203}{}{再见。}

{300}{}{如果你想知道更多关于我们的工作，和我们的领导者谈谈吧。他在三楼。}
{301}{}{明白了。再问几个问题...}

{400}{}{例如？}
{401}{}{你叫什么名字？}
{402}{}{不要在意，回见。}
{403}{}{关于这你能告诉我些什么？}

{500}{}{叫我伊莱恩。}
{501}{}{明白了。再问几个问题...}

{600}{}{Hey! Before you go, perhaps you could do me a favor. I'm supposed to bring this machine part to Max in the basement copy room. But you see, my left knee has been acting up lately, and it's a real pain for me to go up and down all those stairs. Would it trouble you too much to bring him this part for me?}
{601}{}{Sure.}
{602}{}{Sorry, I don't have time for this. Bye.}
{603}{}{Do I look like your personal delivery service? Do it yourself, you fat lazy bitch. Bye.}  #new in RP 1.3

{604}{}{Thanks! Here's the part. The copying room is in the basement. Just use the stairs directly behind Brother Matthew in the chapel area.}
{605}{}{Not a problem. [You take the part.] I'll bring it down to Max right away.}

#dumb dialgoue
{700}{}{Me }
{701}{}{. Who you?}

{710}{}{Hehe. That pretty name.}
{711}{}{Bye!}

{720}{}{You're a special little guy aren't you? Could you do me a BIG favor and be my special helper today?}
{721}{}{You're a special little gal aren't you? Could you do me a BIG favor and be my special helper today?}
{722}{}{Me special. Me help.}
{723}{}{Me no wanna help.}

{730}{}{Really? Great! Please give this machine part to Max in the copying room. He can be found in the BASEMENT. Okay?}
{731}{}{I no let you down!}

{740}{}{You keep on truckin' now.}