# {100}{}{You see a grave marker.}
{100}{}{你看到一个墓碑。}
# {101}{}{The grave marker reads: }
{101}{}{墓碑上写道： }
#{102}{}{"Here lies Brother Gregory. A man who knew no limits."}
{102}{}{"这里躺的是格雷戈里。一个拥有无限知识的人。"}
# {103}{}{"Aunt Patty. Good riddance indeed."}
{103}{}{"佩蒂姨。解脱了，真的。"}
# {104}{}{"Here lies Per Joner. Died one rock too short."}
{104}{}{"这里躺的是博 乔纳。他死在了石头旁边。"}
# {105}{}{"Here lies Father Michael. Founder, Father, Fighter."}
{105}{}{"这里躺的是爸爸迈克尔。创始人，父亲，斗士。"}
# {106}{}{"An Atheist. All dressed up and no place to go."}
{106}{}{"一个无神论者。穿戴整齐却无处可去。"}
# {107}{}{"Here lies Johnny Yeast. Pardon me for not rising."}
{107}{}{"这里躺的是强尼 伊斯特。抱歉不能向你行礼。"}
# {108}{}{"Mary Jane. Loving wife and mother."}
{108}{}{"玛丽。敬爱的妻子和母亲。"}
# {109}{}{"'Checkmate!' was the call to dear old Jon, On the chessboard of life, He was just a pawn.}
{109}{}{"'将军！' 是谁在召唤亲爱的老乔。可惜，在人生的棋盘上他仅是一个卒子。}
# {110}{}{"Sir John Strange, here lies an honest lawyer, and that is Strange."}
{110}{}{"乔 贾爵士，律师。贾律师，是真律师，不掺假。"}
# {111}{}{"Tears cannot restore her -- therefore I weep."}
{111}{}{"泪水也无法挽回她，所以，我选择流泪。"}
# {112}{}{"Every day in every way, I am getting better and better."}
{112}{}{"每一天，每一方面，我都在进步。"}

# {250}{}{There are no markings on this grave marker.}
{250}{}{这个墓碑上什么也没有。}
# {251}{}{The grave marker is too cracked and broken to be read.}
{251}{}{这个墓碑太破旧了，已经无法看清写的什么。}
# {252}{}{The name on the grave marker reads John Doe.}
{252}{}{这个墓碑上的名字是乔 某某}
# {253}{}{The name and date on this headstone have been worn off by the weather.}
{253}{}{这个墓碑上的名字和日期被已经被岁月磨平。}
