# {100}{}{You see a Tough Guard.}
{100}{}{你看到一个强壮的保安。}
# {101}{}{You see an impressively muscled, but aging guard with sun burnt skin. He must have been quite something in his prime. His piercing gaze seems to follow you everywhere.}
{101}{}{你看到一个上了年纪却肌肉健壮的保安，他的皮肤被太阳烧伤了。他年轻时肯定是个了不起的人物。无论你走到哪里都逃不过他锐利的眼神。}

# {200}{}{Hi there, traveler. Welcome to the Abbey. Keep your nose clean and we'll get along just fine.}
{200}{}{嗨，旅行者。欢迎来到大教堂。不要鬼鬼祟祟，我们就能好好相处。}
# {201}{}{I'm watching you, slaver. One wrong move and you'll be tainting our graveyard for the rest of eternity. I wouldn't wish that on you, and I'm fairly sure you wouldn't enjoy that either, so don't get any funny ideas in that warped brain of yours.}
{201}{}{我在盯着你哟，奴隶。动错一步你的余生就要在墓地里度过了。我不希望那样，确定你也不希望那样，所以，你的脑袋瓜不要打什么小聪明的主意。}
# {202}{}{Who are you?}
{202}{}{你是谁？}
# {203}{}{Where can I barter for some supplies?}
{203}{}{在哪能买到补给？}
# {204}{}{Somebody is digging up graves, why don't you do anything about it?}
{204}{}{有些人在掘墓，你就不能做点什么吗？}
# {205}{}{I heard something about animals in the basement. Know anything about that?}
{205}{}{我听说地下室里动物的事了。你了解多少？}
# {206}{}{I think it's time I send you to a grave. Let's dance, old man.}
{206}{}{我看是时候送你进坟墓里。咱们比划一下吧，老头。}
# {207}{}{Nevermind. Goodbye.}
{207}{}{算了。再见。}

# {300}{}{Nobody... Just an old retired caravan guard. A lot of people mistake me for some sort of sheriff because I'm the closest thing resembling the law in these parts, but I'm not. I just look out for this community because I think it's worth protecting.}
{300}{}{什么也不是...就是一个退休的商队老保安。因为我是这附近和唯一和法律沾点边的老东西，他们就错把我当成治安官了。我之所以保护着这个社区，因为它值得我这么做。}
# {301}{}{And in return the community looks out for me. I get some complimentary booze from the monks, Peterson makes sure I'm fed and Bill makes sure I've got ammo and stims. Not a bad retirement gig, if you ask me.}
{301}{}{作为回报，社区也照顾我。我可以从修道士那里拿到免费的酒水，彼得森管我吃的，比尔则提供弹药和针。我这休退的不算坏，如果你要问我的话。}
# {302}{}{I'm the one keeping you in line, and that's all you need to know. Now get on with your business and leave me alone.}
{302}{}{你能知道的就是，我是那个让你守规矩的人。好了，走吧，做你的事去吧。}
# {303}{}{That is a nice arrangement. Let me ask you something else.}
{303}{}{真是不错的约定。让我问你其他的事吧。}
#  {304}{}{Whatever, goodbye.}
{304}{}{不管怎样，再见。}
# {305}{}{You think you can keep me in line? Let's see you try it, old man. This should be fun.}
{305}{}{你认为你能管得住我？你来试试啊，老家伙。我们来找点乐子。}

# {400}{}{You can find Bill, our resident trader, in the building across from here. Other than that, you ought to go to Percy's Survival Gear Locker at the Junkyard in Gecko or Happy Harry's in the Courtyard at Vault City.}
{400}{}{你可以找比尔，我们这的商人，穿过这里那座建筑。除此之外，你可以去蜥蜴城的波西的摊，或者找地下掩体市广场里的快乐哈里。}
# {401}{}{Good to know. I have another question.}
{401}{}{很高兴知道。我还有一个问题。}
# {402}{}{Thanks, bye.}
{402}{}{谢了，拜。}

# {500}{}{If someone is poor or greedy enough to try and dig up graves, that's their business. It's not like the dead can use what they're buried with anyway. Not my problem... I'm not losing any sleep over it.}
{500}{}{如果有人因为穷或贪婪而去掘墓，那是他们自己的事。反正死人也不用上那些东西了。和我无关，我不会睡不着的。}
# {501}{}{Let me ask you something else.}
{501}{}{让我问问其他的事。}
# {502}{}{Bye.} 
{502}{}{拜。} 
# {600}{}{Yes, and Brother Thomas is missing. He was a smart man, but a bit foolhardy. I don't know what's down there, but I don't think it's just a bunch of rats and radscorpies.}
{600}{}{对，托马斯兄弟失踪了。他很精明，但有点鲁莽。我不清楚那下面发生了什么，但我不认为仅仅是老鼠和辐射蝎这么简单。}
# {601}{}{Yes, and Brother Thomas is missing. I don't know what's down there, but I don't think it's just a bunch of rats and radscorpies. Why don't you find out, tough guy?}
{601}{}{对，托马斯兄弟失踪了。他很精明，但有点鲁莽。我不清楚那下面发生了什么，但我不认为仅仅是老鼠和辐射蝎这么简单。你怎么不去找找看，狠家伙？}
# {602}{}{So why don't you go look?}
{602}{}{你为什么不去？}
# {603}{}{You're the tough guy around here, aren't you? Why don't you drag your ass down there?}
{603}{}{你是个狠家伙，对不对？为什么不带着你的大屁股过去看看呢？}

# {610}{}{It's a bit embarrassing, but after spending so much time outdoors with the caravans, I get very nervous when I go underground. The walls just close in on me and I have trouble breathing... Maybe you can find out what happened to Brother Thomas?}
{610}{}{说起来有些难堪，跟随商队走南闯北这么多年，我一进底下就会抑郁。感觉被关在墙里无法呼吸...也许你能查出托马斯发生了什么事？}
# {611}{}{I'll see what I can do. In the meantime, let me ask you something else.}
{611}{}{我会看看我能做些什么。同时，我还有其他问题。}
# {612}{}{Bye.}
{612}{}{拜。}
# {613}{}{I am a tough guy, which is why I'm gonna kick your ass.}
{613}{}{我够狠，所以，我要教训你。}

# {700}{}{What else do you want to know?}
{700}{}{你还想知道什么？}

#{800}{}{It's good to see you again.}
{800}{}{很高兴再见到你。}
# {801}{}{I'm keeping my eye on you.}
{801}{}{我会盯着你哟。}
