# {100}{}{You see a bespectacled young monk.}
{100}{}{你看到一个戴眼镜的修道士。}
# {101}{}{You see Brother Jason.}
{101}{}{你看到Brother Jason。}
# {102}{}{This monk seems to be brooding.}
{102}{}{这个修道士看起来在沉思。}

# {200}{}{[The young monk quickly pockets a deck of "Tragic" cards as you approach.] What do you want?}
{200}{}{[在你靠近时，这个修道士麻利地将一组“悲剧卡”放进口袋。]你想要什么？}
# {201}{}{Nothing from you. Bye.}
{201}{}{不是你。拜。}
# {202}{}{I want to know why you just hid that card deck from me.}
{202}{}{我想知道你为什么把那组卡藏起来。}

# {210}{}{I don't know what you're talking about. I don't have any card deck.}
{210}{}{我不明白你在说什么。我可没什么卡。}
# {211}{}{Don't lie to me. I saw you put it away in your pocket. I just wanted to know why.}
{211}{}{别装了。我都看到了。我想知道为什么。}
# {212}{}{Alright, whatever you say. See ya.}
{212}{}{好吧，不管你怎么说，回头见。}

# {220}{}{Look, don't tell anyone, alright? We're not suppose to "use" pre-war relics, just worship them. But these Tragic cards are so damn cool. [He seems to get lost in another world as he gazes lovingly at the deck. After a moment, he looks up at you.] Oh, sorry. I'm Brother Jason by the way. I, uh, don't suppose you play Tragic?}
{220}{}{听着，别告诉任何人，好吗？我们不允许去碰战前的遗物，遗物是用来朝拜的。但这些悲剧卡简直太酷了。[当他用爱恋的眼神看着那组卡牌时，他好像迷失在另一个世界。过了一会，他抬头看到你。]哦，对不起。我是Brother Jason。我，嗯，你不玩悲剧卡？}
# {221}{}{BRING FORTH THE GARNERING!!!}
{221}{}{拿出你的库存！！！}
# {222}{}{Hell yeah, I love Tragic the Garnering.}
{222}{}{哈，该死的。我爱死收集悲剧卡了。}
# {223}{}{I've tried it, but it's not for me.}
{223}{}{我试过了，但真的不适合我。}
# {224}{}{I used to be addicted as hell to that game. I try to stay away from it now.}
{224}{}{我曾经对这游戏上瘾的不能行。现在，我试着不去碰它。}
# {225}{}{Nope.}
{225}{}{不。}
# {226}{}{Hell no. Do I look like a pathetic loser to you?}
{226}{}{该死的，不。你看我像一个可怜的撸sir吗？}

# {230}{}{Hey, fuck you asshole. Just leave me alone.}
{230}{}{嗨，干死你个婊子养的。滚吧。}
# {231}{}{Hey, fuck you whore. Just leave me alone.}
{231}{}{嗨，干死你个婊子。滚吧。}
# {232}{}{I'd love to, but I'm overcome with a desire to do you great bodily harm.}
{232}{}{我非常想，但我控制不了体内想海扁你的欲望。}
# {233}{}{Alright, fine. Bye.}
{233}{}{好的，行吧。拜。}
# {234}{}{Look, I'm sorry. That was rude of me. I'm just not a fan of Tragic.}
{234}{}{你瞧，我很抱歉。我有些粗鲁。我只是不热悲剧卡而已。}


# {240}{}{Ah man, I'd love to play against you, but it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.}
{240}{}{嗨伙计，我非常希望和你玩，但是风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。}
# {241}{}{Ah man, I know what you mean. I wish I could play more myself, but it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.}
{241}{}{嗨伙计，我明白你的意思。我希望自己能多玩一些，但是风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。}
# {242}{}{[He chuckles.] We got an addict on our hands here, I see. I wish I could play more myself, but it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.}
{242}{}{[他咯咯地笑。]上瘾的停不下来了，我懂。我希望自己能多玩一些，但是风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。}
# {243}{}{It doesn't matter, we wouldn't be able to play anyway -- it's too risky. I don't want these taken from me. That's what I hate about this place. We're sitting on a damn goldmine of awesome things from before the war, but we're forbidding ourselves from indulging in it. It doesn't make any sense. It's fucking moronic.} 
{243}{}{没关系，我们不能再玩了--风险太高。我不希望它们被夺走。这就是我为什么恨这个地方。我们坐拥战前的宝贝玩意儿，却不允许自己放纵一下。这压根不合理，太傻逼了。} 
# {244}{}{Yeah, that does sound stupid.}
{244}{}{对，的确听起来很蠢。}
# {245}{}{If you don't agree with the ideals of your order, then why are you a monk?}
{245}{}{如果你不赞同这些规矩，那你为什么还要做一个修道士？}

# {250}{}{You think I *chose* to be a monk? I was born into this shitty lifestyle. I just wish the others would wake up and see how stupid it is to not take advantage of all this sweet stuff we've collected. But no, they're perfectly content to worship and catalog the relics, but never actually do anything useful with them. Like I said, it's fucking moronic.}
{250}{}{你觉得是我*选择*成为修道士？我生来如此，没得选。我只是希望其他人能早点醒悟，明白不好好利用这些东西是多么愚蠢的行为。但是呢，不，他们只是满足于崇拜和整理归类这些遗物，从来不想怎么使用。就像我说的，这太傻逼了。}
# {251}{}{You got a point, that does sound pretty stupid.}
{251}{}{你说到点子上了，的确听起来很蠢。}
# {252}{}{About as moronic as me sitting here listening to you bitch about your life. Bye.}
{252}{}{我也像傻逼一样坐在这听你哔哔你的生活。拜。}
# {253}{}{If you think it's so stupid, then why don't you do something to try and change things?}
{253}{}{如果你觉得这样很蠢，为什么不行动起来尝试做些改变呢？}

# {260}{}{Finally, someone who agrees with me! Look, I have this idea, and maybe you could help me out. You see, the monks here have spent *years* transcribing pre-war information into our computer database. If someone were to "accidentally" format the database, they'd lose all that work. I think something like that might shock them back to their senses and we might finally give up this stupid way of life. So, what do you say?}
{260}{}{终于，有人赞同我了！瞧，我有个主意，也许你能帮我。这些修道士花了*数年*来将战前的资料录入电脑。如果某人*无意间*把数据库格式化，他们的努力就白费了。我想他们会先被震惊，之后回归理性，最后放弃这种愚蠢的生活方式。你觉得怎么样？}
#  {261}{}{I say that's a terrible idea and that I'm done talking to you.}
{261}{}{我觉得这太可怕了，咱俩谈话结束了。}
# {262}{}{Erase years of someone else's hard work? Sounds fun. I'll do it.}
{262}{}{让某些人数年的努力全部白费？很有趣，我会做。}
# {263}{}{Why don't you format it yourself?}
{263}{}{为什么你不自己做？}
# {264}{}{If you hate it here, why don't you just leave?}
{264}{}{如果你恨这个地方，为什么不离开呢？}

# {270}{}{Actually, I *do* have an idea of how to change things. Maybe you could help me out. You see, the monks here have spent *years* transcribing pre-war information into our computer database. If someone were to "accidentally" format the database, they'd lose all that work. I think something like that might shock them back to their senses and we might finally give up this stupid way of life. So, what do you say?}
{270}{}{实际上，我*有*个主意改变现状。也许你能帮忙。这些修道士花了*数年*来将战前的资料录入电脑。如果某人*无意间*把数据库格式化，他们的努力就白费了。我想他们会先被震惊，之后回归理性，最后放弃这种愚蠢的生活方式。你觉得怎么样？}
# {271}{}{I say that's a terrible idea and that I'm done talking to you.}
{271}{}{我觉得这太可怕了，咱俩谈话结束了。}
# {272}{}{Erase hundreds of years of someone else's hard work? Sounds fun. I'll do it.}
{272}{}{让某些人几百年的努力全部白费？很有趣，我会做。}
# {273}{}{Why don't you format it yourself?}
{273}{}{为什么你不自己去格式化？}
# {274}{}{If you hate it here, why don't you just leave?}
{274}{}{如果你恨这个地方，为什么不离开呢？}

# {280}{}{Are you kidding me? They'd crucify me if I did that. You however, you're an experienced adventurer. Hell, I bet you could massacre everyone here without breaking a sweat. So will you do it, or are you afraid of a bunch of pacifist monks?}
{280}{}{你开玩笑吗？他们会把我钉上十字架的。而你，却是经验丰富的冒险家。该死，我打赌你不出一滴汗就把这个荡平了。你做不做，还是你害怕一群坚持和平主义的修道士？}
# {281}{}{I'm not afraid of anyone. I'll do it.}
{281}{}{我谁也不怕，我会做。}
# {282}{}{Alright. I'll do it.}
{282}{}{好吧，我会做。}
# {283}{}{Nah, instead I think I'll test out your massacre theory. Starting with you.}
{283}{}{啊哈，我会试试你的不出汗理论。从你开始。}
# {284}{}{I'll pass. That's just not my style. Bye.}
{284}{}{别把我算进来，这不是我的方式。拜}
# {285}{}{No, I'm not going to do it. If you hate it here, why don't you just leave?}
{285}{}{不，我不会去干。如果你恨这个地方，为什么不离开呢？}

# {286}{}{Unless you've changed your mind about helping me, fuck off.}
{286}{}{除非你改变主意要帮忙，滚蛋吧。}
# {287}{}{Alright. I'll do it.}
{287}{}{好吧，我会做。}
# {288}{}{No, I'm not going to do it. If you hate it here, why don't you just leave?}
{288}{}{不，我不会去干。如果你恨这个地方，为什么不离开呢？}

# {290}{}{You will? Seriously? Oh man, that's awesome. But first, you'll need to get access, 'cause they're pretty protective of the database. It shouldn't be too hard though, these monks are pretty trusting. They're gonna be pissed as hell when you format it, but they're all a bunch of wimps, so don't worry about it. Just try not to kill anyone -- I don't want things to get too out of hand, you know?}
{290}{}{你真的会做？哦天，太棒了。但首先，你需要权限，因为数据库保护的很好。这不会太难，这些修道士很容易相信别人。当他们发现数据库被格式化一定怒不可遏，但他们是一帮软蛋，别担心。试着别杀人--我不希望事情失去控制，明白？}
# {291}{}{Sure. Anything else?}
{291}{}{当然。还有什么事？}
# {292}{}{I make no promises. Anything else?}
{292}{}{我不能保证。还有什么事？}

# {300}{}{Just format it, then take off, cause they're not going to want you around here. Don't even bother to come tell me you did it, because I'll have to act just as pissed as everyone else or they'll suspect something's up. Thanks again for doing this. It's for their own good.}
{300}{}{格式化，然后闪人，他们肯定不希望在附近看到你。也别来告诉我你成功了，因为我必须装的和其他人一样愤怒，不然就会引起怀疑。再次感谢，这是为了他们好。}
# {301}{}{Whatever you say. Bye.}
{301}{}{不管怎样。拜。}

# {310}{}{Are you crazy? I've never been out in the wastes, but I've got a pretty damn good idea as to what it's like. I'd be lucky to make if fifty yards before a radscorpion shoved a foot-long stinger up my ass. Or even worse, I'd get captured and tortured by a gang of maniac raiders *or* I'd be eaten alive by cannibalistic tribals. Whatever. I just know that if I left here, I'd be fucked. So no, I'm stuck here.}
{310}{}{你疯了？我没在废土生活过，但我可是知道它什么样。如果我五十码内没被辐射蝎扎烂屁股，已算幸运了。更糟的，我会被帮派份子抓走然后折磨致死*或者*被食人族掳走生吃。不管怎么样，我离开这肯定就是这些下场。所以不，我困在这了。}
# {311}{}{Hey, it's not *that* bad out there... Actually, you're right. You probably wouldn't even make it to Gecko. At least, not without help. But what if I said I'd escort you?}
{311}{}{嗨，外边没有*那么*糟...好吧，你是对的。你没法活着到蜥蜴城。至少，没有帮助是到不了。但如果说我愿意护送你呢？}
# {312}{}{Sucks to be you. Bye.}
{312}{}{你真逊。拜。}
# {313}{}{Keep your hopes up. I'm sure there is a town nearby that would be safe to travel to.}
{313}{}{别放弃希望啊。我肯定这附近就有小镇，你可以安全抵达的。}

# {315}{}{Yeah, well if you find one, let me know.}
{315}{}{好的，如果你找到一个，告诉我。}
# {316}{}{Will do. Bye.}
{316}{}{会的。拜}

# {320}{}{To Gecko? That's the ghoul town, right? Thanks, but no thanks.}
{320}{}{蜥蜴城？那是个僵尸镇对不？谢了，算了吧，谢了。}
# {321}{}{Hey, the ghouls there are actually really friendly. Besides, I know one in particular that loves a good game of Tragic.}
{321}{}{嗨，那的僵尸非常友好的。并且，我知道有个僵尸也大爱悲剧卡。}
# {322}{}{Hey, the ghouls there are actually really friendly.}
{322}{}{嗨，那的僵尸非常友好的。}
# {323}{}{Hey, I hear the ghouls there are actually really friendly.}
{323}{}{嗨，我听说那的僵尸非常友好的。}
# {324}{}{Alright. Suit yourself. Bye.}
{324}{}{好吧，你随意吧。拜。}

# {330}{}{No shit, another Tragic player? Hmm, that kind of changes things... I wonder if he'd have a Black Dahlia to trade. Alright. I'll go if you'll escort me.}
{330}{}{不是吧，另一个悲剧卡玩家？嗯，我得改变主意了...我好奇他有没有黑大丽花交易。好的，如果你愿意护送我，我就去。}
# {331}{}{Lets go.}
{331}{}{我们走。}
# {332}{}{Alright, but I need to take care of some things first. I'll let you know when I'm ready to go.}
{332}{}{好的，但我要先处理点事。准备好就告诉你。}

# {340}{}{Oh yeah? That doesn't change the fact that they look like brahmin shit. No thanks.}
{340}{}{是吗？但这并不能改变他们看起来像婆罗门狗屎的现实。算了吧，谢了。}
# {341}{}{Alright. Suit yourself. Bye.}
{341}{}{好吧，你随意吧。拜。}

# {350}{}{What do you want?}
{350}{}{你要什么？}
# {351}{}{I just wanted to say hi. See ya.}
{351}{}{我只是打个招呼。回见。}
# {352}{}{I changed my mind. I'll format the computer for you.}
{352}{}{我改变主意了。我会为你格式化数据库。}
# {353}{}{Hey, you might want to reconsider my offer to take you to Gecko, because I know someone there that loves a good game of Tragic.}
{353}{}{嗨，也许你会重新考虑我带你去蜥蜴城的提议，因为我知道那里有个悲剧卡的玩家。}
# {354}{}{Hey, I know someone in Gecko that loves a good game of Tragic. I could take you there.} 
{354}{}{嗨，我知道蜥蜴城有个悲剧卡的玩家。我可以带你过去。} 
# {360}{}{Are we ready to go yet? I'm dying to know what kind of Tragic cards this guy's got.}
{360}{}{准备好出发了吗？我迫不及待想知道他有什么样的悲剧卡。}
# {361}{}{Alright, let's go.}
{361}{}{好，我们走。}
# {362}{}{Not yet. I'll let you know.}
{362}{}{还没有，我会让你知道。}

# {370}{}{[Upon arriving in Gecko you introduce the young monk to Wooz. They quickly hit it off and begin comparing their Tragic card decks. You're about to leave when Brother Jason pulls himself away from Tragic long enough to have a word with you.]}
{370}{}{[一到蜥蜴城你就把年轻的修道士介绍给了Wooz。他们迅速打成一片，开始对比各自的卡组。Brother Jason立刻沉迷于悲剧卡而顾不上和你说一整句话，你准备离开。]}
# {371}{}{[MORE]}
{371}{}{[更多]}
# {372}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me. Here, I, uh, "borrowed" this from the Abbey's Memorabilia, amazingly it's one of the few tech relics that still works. [He hands you a Stealth Boy.] See ya.}
{372}{}{我靠，Wooz*真的*有黑色大丽花！这趟旅程值了。的确，僵尸看起来丑死了，不过只有我戴着眼镜的时候丑。怎么说呢，非常感谢你带我过来。这是我，呃，从Abbey那里*借*来的东西，很少见的能使用的战前遗物，[他递给你一个Stealth Boy。]回见。}
# {373}{}{Thanks. Bye.}
{373}{}{谢了，拜。}
# {374}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{374}{}{我很高兴不用再听你像婊子一样唠叨了。拜。}


# {380}{}{Holy shit, Wooz *does* have a Black Dahlia! That alone has made this trip worthwhile. Sure, the ghouls are ugly as hell, but I found if I take off my glasses, then they're kinda tolerable. Anyway, thanks a lot for bringing me here. Here, [He reaches into his pocket, then frowns.] what the hell? I could swear I had it. Uh, sorry, but looks like I misplaced your reward, so you'll have to make due with a simple thanks. See ya.}
{380}{}{我靠，Wooz*真的*有黑色大丽花！这趟旅程值了。的确，僵尸看起来丑死了，不过只有我戴着眼镜的时候丑。怎么说呢，非常感谢你带我过来。这里，[他伸手进口袋，然后皱眉。]他妈的，我发誓我带着。呃，对不起，我把你的奖励弄丢了，你就收下我的口头谢意吧，谢谢。回见。}
# {381}{}{Oh, uh, don't worry about it. Just glad I could help. Bye.}
{381}{}{哦，啊，别担心。很高兴我能帮忙。拜。}
# {382}{}{I'm just happy I won't have to hear you bitch anymore. Bye.}
{382}{}{我很高兴不用再听你像婊子一样唠叨了。拜。}

# {400}{}{Can't talk... must build more powerful deck...}
{400}{}{顾不上...必须组一套更强力的牌。}

# {500}{}{Leave me alone.}
{500}{}{离我远点。}
# {501}{}{Go away.}
{501}{}{走开。}
# {502}{}{Fuck off.}
{502}{}{滚蛋。}

# {600}{}{Oh, hey, it's you. Somebody blew up the reactor at Gecko and all the ghouls left. No reason for me to stay there, so I left and came back here. Luckily for me the monks here didn't question my absence, so I'm not in any trouble for leaving. This sucks though, I thought I was going to have a new life doing what I love. [He sighs deeply]}
{600}{}{哦，嗨，是你。某人炸了蜥蜴城的反应堆，僵尸们全离开了。我也没理由留在这里，我走了又回来。很幸运修道士没有因为我不在而质疑。这一切太糟了，我决定重新开始，做我喜欢做的事。[他深深地叹了口气。]}
# {601}{}{Sorry to hear that. See you around.}
{601}{}{听到这些我很抱歉。回头见。}
# {602}{}{That's life. One minute you're on top of the world and the next instant you're face down in the mud. Live and learn. Bye.}
{602}{}{这就是生活。前一分钟你还春风得意，下一分钟你就摔个狗啃屎。且行且珍惜。拜。}

# {610}{}{Guess I just gotta get used to this place.}
{610}{}{我猜我需要慢慢适应这个地方。}

# {1000}{}{You safely escort Brother Jason to his new home.}
{1000}{}{你安全的将Brother Jason护送到他的新家。}