{100}{}{你看见一个中年修士。}
{101}{}{你看见修士马太。}
{102}{}{他正站在讲台上为阿比的市民讲道。}

{200}{}{阿比善良的人们。给我片刻，我有一些话要说。}

#new speech for RP 1.3 translate by Marv
# {201}{}{Here we collect, the holy relics of an age long past.}
{201}{}{在这里，我们收集的是很久以前遗留下的神圣遗物。}
# {202}{}{Scorched by the Flame Deluge, into the dark, we were cast.}
{202}{}{被我们自己释放的天火焚烧，化为黑色。}
# {203}{}{A Memorabilia we shall make, to preserve the wisdom of old.}
{203}{}{我们祭拜它，怀念它，因为古老的智慧幸存其中。}
# {204}{}{We must guard and care for it, though the flame has gone cold;}
{204}{}{即使天火的烈焰已然冷却，它们也应该被悉心守护。}
# {205}{}{It could ignite once again, should the wisdom be misused.}
{205}{}{一旦，智慧被滥用，怒焰必将重燃。}
# {206}{}{Thus, no one shall learn, for fear of another, Flame Deluge.}
{206}{}{因此，我们要敬畏天火，封存圣物。}
# {207}{}{But one day, men shall rise above their desire for destruction.}
{207}{}{直到有一天，人类战胜了自相残杀的欲望。}
# {208}{}{And the Memorabilia will be there, awaiting re-introduction.}
{208}{}{圣物才能被开启，古老的智慧才能被启用。}
# {209}{}{So we tend to our holy task, lest all that wisdom, we lose.}
{209}{}{我们的光荣使命，就是保证古老的智慧。}
# {210}{}{We must preserve and protect it, but never shall we use.}
{210}{}{被保存，被守护，但是，不被使用。}
# {211}{}{So go now my friends, and let your spirits be lifted;}
{211}{}{我的朋友，重整精神，向前走吧。}
# {212}{}{For the guardians of knowledge, we have each, been gifted.}
{212}{}{我们都是天选之子，来作为知识的守护者。}
# {213}{}{Now, please take a moment and reflect on what I have said.}
{213}{}{静下心来，好好想想我说的话吧。}

{224}{}{Now, please take a moment and reflect on what I have said.}
{224}{}{静下心来，好好想想我说的话吧。}

# {300}{}{Greetings, friend. I don't think I have seen you around here before. My name is Brother Matthew and I help spread the word about the importance of preserving the knowledge of the old ones.}
{300}{}{祝福你，朋友。我之前好像没有见过你。我的名字是Brother Matthew，我负责教授人们封存圣物的重要性。}
# {301}{}{It's good to meet you Matt. My name is }
{301}{}{很高兴认识你Matt。我的名字是}
# {302}{}{ and I am on a quest for the holy GECK.}
{302}{}{ 我在寻找神圣的伊甸园制造器。}
# {303}{}{Sorry, I must be going.}
{303}{}{抱歉，我必须走了。}

# {400}{}{A GECK, huh? I seem to remember reading something about that during one of my transcribing sessions. So it must be in our database, but I'm afraid access to our computers is restricted. However, if you talk to the Abbot, it's possible he'll grant you access. It couldn't hurt to try, anyway. Oh, and feel free to browse through our collection of holy pre-war relics. I'd ask you not to damage anything, but I'm afraid everything's already broken beyond repair.}
{400}{}{伊甸园制造器？我好像在录入资料的时候读到过这个东西。我们的数据库里一定查得到，不过电脑被管制的很严。这样吧，你找Abbot谈谈，可能他会给你权限，问问无妨。哦，欢迎参观我们的战前圣物，小心不要碰坏。其实，他们早已经坏的没有修的价值了。}
# {401}{}{I think I just might. I have some questions though.}
{401}{}{我想我会的。我还有一些问题。}
# {402}{}{Thanks. I think I'll go do that now.}
{402}{}{谢了。我现在就去做。}

# {500}{}{I am at your service. What would you like to know?}
{500}{}{我来为您服务。请问你想知道什么？}
# {501}{}{What can you tell me about this place?}
{501}{}{关于这个地方，你能告诉我些什么？}
# {502}{}{You seem to be very poetic in your preaching. Any reason for this?}
{502}{}{听起来你的布道非常诗意，为什么？}
# {503}{}{Nevermind. Take care.}
{503}{}{算了。保重。}

# {600}{}{The Abbey is home to anyone, so long as they don't cause trouble. We are an independent community and rarely get visitors, such as yourself. The majority of those you see here are descended from the original founders that settled in this old monastery not long after the great Flame Deluge.}
{600}{}{阿比是每一个安分守己的人的家。我们是与世隔绝的社区，鲜有外来者，比如你。天火降临不久，我们的祖先就来到这个古老的修道院，定居下来，慢慢建立了这里的一切。}
# {601}{}{Go on.}
{601}{}{继续。}
# {602}{}{The quiet, peaceful quality of this place has made it an appealing home to other travelers that have wandered here over the years, seeking to escape from the dark chaos of the wastes. Of course, the true value of this place lies in its vast library. It's filled with old tomes, containing the strange wisdom of a lost age. Over time, we've come to fancy ourselves the keepers and guardians of that wisdom.}
{602}{}{很多人为了逃避混乱不堪的废土世界而来到这个安静和平的地方。当然，这里真正的宝藏就在大图书馆里，里边放满了存有奇怪智慧的各式古书。慢慢的，我们就成了智慧的守护者。}
# {603}{}{Very interesting. Another question.}
{603}{}{非常有趣。下一个问题。}
# {604}{}{Interesting. Well, I must be going.}
{604}{}{有趣。好吧，我必须走了。}

# {700}{}{[The man chuckles at your question] No, no particular reason. I have just read much poetry throughout my life and I enjoy applying it to my teachings. It helps leave a greater impact on those listening.}
{700}{}{[这个人因为你的问题而笑了] 没有什么特别的原因。我这辈子读了太多的诗，而我也很乐意把它用到我的教授之中。这样会给听众们带来更深的印象。}
# {701}{}{Fair enough. Another question.}
{701}{}{很合理。下一个问题。}

# {800}{}{It is good to see you again }
{800}{}{很高兴再见到你。}
# {801}{}{. What can I do for you?}
{801}{}{。 我能为你做什么？}
# {802}{}{I have some questions.}
{802}{}{我有一些问题。}
# {803}{}{Nothing. See you around.}
{803}{}{没什么。回头见。}