#############################################################
#  Message File: ACMynoc.msg                                #
#                                                           #
#       Body Type:  NMPRIM                                  #
#       Combat AI: Berzerker                                #
#       Weapons: Sledgehammer[in hand]                      #
#       HP: 75                                              #
#       Skills to note: 80% Throwing                        #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################

{100}{}{你看到守桥兵。}
{101}{}{你看到曼那克，守桥兵。}

#############################################################
#  The following lines are for the dialog which the NPC     #
#  says. This will be disorganized because of the Design    #
#  Tool.                                                    #
#############################################################

{150}{}{站在你面前的是个强壮的战士，手持一只矛。}
{151}{}{[谈话]}
{152}{}{你好，获选者，要去找伊甸园创造器了吗？}
{153}{}{是。}
{154}{}{是。但是在我走之前，我想要问你一些问题。}
{155}{}{还没有，我想要在这边看看。}
{156}{}{好吧，希望神保佑你。}
{157}{}{谢谢你，再见。}
{158}{}{你想要知道什么？}
{159}{}{对于跟我们村里交易的那个男人，你知道些什么？}
{160}{}{对于这一个从避难所来的东西，你知道些什么？}
{161}{}{没事，算了。}
{162}{}{好吧，但是不要浪费时间。因为没有伊甸园创造器的话，我们就完了。}
{163}{}{我知道，不要担心－－我会做好的。}
{164}{}{为什么？}
{165}{}{我得走了，再见。}
{166}{}{那商人吗？他们每两个月都会从克拉马斯来。这一个月之内他们都不会再来的。不过，克拉马斯就在这里的东边。}
{167}{}{谢谢，再见。}
{168}{}{对于这一个从避难所来的东西，你知道些什么？}
{169}{}{看起来像是一个铁水瓢。}
{170}{}{你可以告诉我是谁将这东西带到村里来的呢？}
{171}{}{谢谢你，我得走了。再见。}
{172}{}{我希望你可以。}
{173}{}{你千万不要自信满满，再见！}
{174}{}{再见。}
{175}{}{看看－－我们的村子快要灭亡了。小孩挨饿，老人死去。赶快将伊甸园创造器拿回来吧！}
{176}{}{我会的，再见。}
{177}{}{我是获选者－－只要是我喜欢，怎样做都可以。再见。}
{178}{}{我不记得他的名字，只记得他很老，说话很大声－－而且没有礼貌－－但是，他知道很多的东西。他是从克拉马斯来的。}
{179}{}{谢谢你，再见。}
{180}{}{你还在这边？你一定要去找伊甸园创造器，杵在这边是帮不了我们的。}
{181}{}{你只要专心守着这桥就好了。}
{182}{}{我正要去，再见。}
{183}{}{我不想再跟你说了，猪头！}
{184}{}{我想要问你另外一个问题。}
{185}{}{好快啊！你找到了神圣的第１３号避难所了吗？}
{186}{}{是。}
{187}{}{还没有。}
{188}{}{你找到了？真好！那你找到了伊甸园创造器了吗？}
{189}{}{没有。}
{190}{}{没有，我还没有跟避难所里面的人谈。}
{191}{}{我觉得这是与你无关的，我的朋友。}
{192}{}{没有？获选者，自你离开后，已有三个老人死亡了。已经没有时间了，不要再浪费时间了。}
{193}{}{我会去找的，不要担心。}
{194}{}{你一直烦我，我觉得很讨厌。}
{195}{}{那你为什么要跟我说话呢？去跟他们谈啊，去拿伊甸园创造器啊。}
{196}{}{我会的。}
{197}{}{你一直烦我，我觉得很讨厌。}
{198}{}{有什么好消息，获选者？}
{199}{}{我找到避难所了！}
{200}{}{我无法找到第１３号避难所。}
{201}{}{看啊，是获选者。}
{202}{}{你好。}
{203}{}{住口。}
{204}{}{我可以问你一个问题吗？}
{205}{}{我没有时间。}
{206}{}{再见。}
{207}{}{好吧，再见。}
{208}{}{去死。}
{209}{}{你好，过桥小心，不要掉下去了。}
{210}{}{嗯．．嗯？}
{211}{}{你让整个村庄都很失望！}
{212}{}{你背叛了我们。你去死吧！}
{213}{}{你是背叛者。}
{214}{}{你为什么要这样？}
{215}{}{长老错了，你是邪恶的。}

{300}{}{我的爸爸教过我如何让刀变得更锐利。帮我找块磨刀石，我就把你的矛磨尖。}
{301}{}{我在那可以找到磨刀石呢？}
{302}{}{他们说你的莫丽姑妈有一块，但是她脾气不好。我想，如果你跟她要的话，她不会免费给你的。}
{303}{}{谢谢，再见。}
{304}{}{你拿到了磨刀石了吗？}
{305}{}{有，就在这边。}
{306}{}{还没有。}
{307}{}{看起还很好，把你的矛给我。}
{308}{}{拿去。}
{309}{}{我想吧，我没有。}
{310}{}{你将它这样．．}
{311}{}{获选者没有矛？那你可以拿我的。}
{312}{}{这是你的新矛。}
{313}{}{谢谢你，我的朋友－－那会帮我很多忙的。}
{314}{}{是，但我刚刚在看你的矛。它看起来有一些不同。}


# added in for time limit
{400}{}{欢迎回家，获选者！你找到避难所了吗？找到了伊甸园创造器了吗？}
{401}{}{没有。}
{402}{}{没，我还没有找到。}
{403}{}{我没有心情回答你的问题。再见。}
{404}{}{这边情况很糟。干旱越来越严重了，我们已经快没有吃的了。}
{405}{}{为何不与其他村庄交易呢？}
{406}{}{我会尽力，会带伊甸园创造器回来的。}
{407}{}{为什么不与其他村庄交换食物呢？}
{408}{}{我会尽力的。我会带伊甸园创造器回来的。}
{409}{}{我们没有什么可以跟别人交换的东西。}
{410}{}{这样啊。}
{411}{}{这样啊。}
{412}{}{你是我们最后的希望，请不要让我们失望！}
{413}{}{很高兴见到你，事情办得如何了？}
{414}{}{我还在找。}
{415}{}{我还在找。}
{416}{}{我不想要提这件事。}
{417}{}{那你得快。这边的情况越来越糟了。}
{418}{}{获选者！请告诉我你完成了你的任务。}
{419}{}{还没，我还再找。}
{420}{}{还没，我还再找。}
{421}{}{情况如何？}
{422}{}{我很抱歉，但是我对你的能力开始质疑了。请快去找伊甸园创造器！}
{423}{}{我们情况已糟到极点了。}
{424}{}{我还在找。}
{425}{}{我会尽力的。}
{426}{}{你回来了，我希望你这次不是空手回来的。}
{427}{}{抱歉，我还没有找到。}
{428}{}{抱歉，我还没有找到。}
{429}{}{我受够了。}
{430}{}{村民开始死了，我看你也不用回来了。}

{500}{}{你跟长老谈过了吗？}

#############################################################
#  TELL - ME - ABOUTS					    #
#############################################################
{1000}{}{长老}
{1001}{}{创造者}
{1002}{}{避难所住民}
{1003}{}{阿罗由}
{1004}{}{克拉马斯}
{1005}{}{避难所}
{1006}{}{获选者}
{1007}{}{巫师}
{1008}{}{哈库林}
{1009}{}{治伤粉}
{1010}{}{桥}
{1011}{}{曼那克}

{1100}{}{长老是你的母亲，是我们的领袖。}
{1101}{}{伟大的祖先给予了我们知识。}
{1102}{}{对付混乱的第一人。}
{1103}{}{这就是我们漂亮的村庄。}
{1104}{}{在东边几天的路程有一个贸易集散地。}
{1105}{}{避难所是天堂。}
{1106}{}{你是获选者。}
{1107}{}{他用草药以及魔法治疗我们。他在村的北方。}
{1108}{}{他用草药以及魔法治疗我们。他在村的北方。}
{1109}{}{他用草药以及魔法治疗我们，但是治疗之后却会想睡觉。}
{1110}{}{那桥是通往村外的唯一道路，就在村的南边。}
{1111}{}{那就是我。}

#added by killap - expansion
{600}{}{Any final advice for me before I head out into the unknown?}
{601}{}{Certainly. Beware the weapons of the Outsiders. The gecko's bite is nothing compared to the destructive power of their boom-sticks.}
{602}{}{Got it. Anything else?}
{603}{}{Do not give your trust freely. Honor means very little out in the wastes. Stay alert and always question the motives of others.}
{604}{}{Sure thing. Is that all?}
{605}{}{Never forget your roots. The world outside our village is full of shiny toys and luxuries that might make our life here in Arroyo appear simple and plain. But remember that the lifestyle of the Outsiders produces wicked men ruled by greed and corruption. Be wary not to become like He-Who-Must-Not-Be-Named.}
{606}{}{I'll never forget my roots. Thanks for the advice, Mynoc.}
{607}{}{He-Who-Must-Not-Be-Named? Uh... who?}
{608}{}{Are you so drunk with the glory of being the Chosen One that you've forgotten about... [Mynoc quickly glances around to be sure no one is listening in, then leans forward and lowers his voice to a whisper.] ... Kaga?}
{609}{}{Oh! Yeah, that guy. I'll make sure I don't end up like him. Thanks.}
{610}{}{Oh, that's who I thought you meant. But, uh, why don't you go ahead and tell me what his deal is again. I really love that story.}
{611}{}{[Mynoc mumbles something under his breath and shakes his head before beginning his tale.] As you should know, he was once the greatest warrior of our tribe. He led many expeditions into the outside world, and it was there where corruption began to poison his mind.}
{612}{}{He became infatuated with the ways of the Outsiders, where power could bring anyone great respect and luxury. He began to view himself as superior to his fellow tribesmen who were content to live a more simple life.}
{613}{}{What a jerk.}
{614}{}{Go on.}
{615}{}{When our tribe fell into these hard times, he deemed himself our people's savior and entered the Temple of Trials to prove himself to be the Chosen One.}
{616}{}{Go on.}
{617}{}{Nevermind, I don't want to hear this story anymore. Bye.}
{618}{}{He made his way through the Temple, quickly reaching the final test: a hand-to-hand battle with a fellow warrior.}
{619}{}{Go on.}
{620}{}{Wait, he blew up that door and everything? Do we have it rebuilt every time someone goes through the temple? Speaking of that, who built the temple in the first place?}
{621}{}{I don't have time to answer all your silly questions. Do you want me to finish the tale, or not?}
{622}{}{Sorry. Please continue.}
{623}{}{Actually, I think I'm ready to go. See you around.}
{624}{}{During the final trial, He-Who-Must-Not-Be-Named unsheathed a hidden blade and used it to kill his opponent. When the Elder confronted him about his dishonorable use of a hidden weapon, he argued that it was not cheating, but rather proved him to be a cunning warrior.}
{625}{}{The Elder did not agree. He-Who-Must-Not-Be-Named was forcibly exiled from our tribe and his name was never to be spoken amongst us again. As he was cast away into the wastes, he swore an oath of vengeance. Vengeance against our tribe, and especially against you.}
{626}{}{Me? What'd I do?}
{627}{}{Thanks for the story, but I'd best be on my way now.}
{628}{}{You are the Chosen One, a title he feels is rightfully his. His pride will not allow you to live.}
{629}{}{I'm not going to worry about it. He's probably dead out in the wastes by now, anyway.}
{630}{}{I'll be on my guard. Hopefully he's dead out in the wastes by now.}
{631}{}{Listen, and understand. He-Who-Must-Not-Be-Named is out there. He can't be bargained with. He can't be reasoned with. He won't feel pity, or remorse, or fear. And he absolutely will not stop, ever, until you are dead.}
{632}{}{You know, I think you might be overdoing it with the melodrama, just a tad. Anyway, thanks for the advice. I'll see you around, Mynoc.}
{633}{}{I'll keep that in mind. Take care, Mynoc.}

{640}{}{Could you tell me anything about this Kaga guy?}
{641}{}{[His eyes go wide and he looks around nervously as if expecting to suddenly be struck by lightning.] Have you lost your senses out in the wastes?! You should know better than to speak the name of the outcast! He is to be referred to only as He-Who-Must-Not-Be-Named. Our village suffers enough without inviting the wrath of the Gods upon us. [He raises his eyes nervously to the sky.]}
{642}{}{Sorry about that, Mynoc. But would you mind telling me what Ka... I mean, "He-Who's" deal is again? I really love that story.}
{643}{}{You know, I'd forgotten how stupidly superstitious you people could be. I'll see you around.}

{650}{}{I've faced him before, so I'm sure I can handle him if our paths cross again.}
{651}{}{Actually, he's already dead. I left his corpse out there to rot in the wastes.}
{660}{}{[Mynoc nods grimly.] He may have strayed from the path, but he was once a great and respected warrior. I hope his troubled soul has found peace in the next world.}

{661}{}{Indeed. I'll see you around, Mynoc.}
{662}{}{Whatever. He seemed like an asshole to me. I'll see you around, Mynoc.}
