# Message file for epac4.ssl 
# Number of nodes: 13

{100}{}{你看见一个全息人。}
{101}{}{你看见安全主管。}
{102}{}{全息人10001。他照看EPA的安全。}

# Node  0  [Node001]
{200}{}{站住！不要再靠近了。报出你的身份，入侵者。}
{201}{}{我是阿由罗的获选者。我是来探索EPA 的。}
{202}{}{我不是入侵者，我这就离开。}
{203}{}{I'm }
{204}{}{, and I'm not trying to intrude, I'm just exploring.}

# Node  1  [Node002]
{210}{}{探索？探索．．EPA ？你胆敢再动一下。我就把你逮捕到三层的拘留室。}
{211}{}{不，等等！我不想对你怎么样。让我解释一下……}

# Node  2  [Node003]
{220}{}{你哪都不能去，说明身份前没人可以在EPA 里闲逛。我怎么知道你不会破坏这里？为什么我要相信你？}
{221}{}{当然，不过如果你给我一个机会解释一下我的身份，也许会解除一些误会。}
{222}{}{你不会的，没种的老家伙。}

# Node  3  [Node004]
{230}{}{继续，说明你的身份。你要是乱说，我就叫机器人把你拖去上电椅，上老虎凳，用满清十大酷刑折磨死你。}
{231}{}{“汗……”我在执行一个伟大的任务。变化莫测的道路，我需要盔甲，武器，许多技能。我偶然来到EPA，只是进来看看有什么可以捡的。}
{232}{}{去死吧你。从逻辑上说，你是一个全息人，对吧？你不可能伤害到我，而你所说的机器人是这些锡桶吧，我相信他们对我没什么威胁。}

# Node  4  [Node005]
{240}{}{捡！？你怎么敢用这种方式侮辱EPA！没有我的允许没人能拿走这里的一张纸。虽然你看上去很有一手……等等，对啊，也许你对我会有一些用处。}
{241}{}{啊？}
{242}{}{不，我认为我捡完东西就得走了。再见！}

# Node  5  [Node006]
{250}{}{傲慢！你就像你的种族一样傲慢。傲慢是要被惩罚的。记住我说的话，你的谎言有一天会让你丧命的。}
{251}{}{对，也许会，但如果那天若来临，那时我会处理的。不过那永远不会发生在你身上。因为你没有身体。你没什么可以失去的，这就是你为什么总用愤怒掩盖悲伤的原因。机器人已经有多久没回应你的命令了？}

# Node  6  [Node007]
{260}{}{好吧，就像你猜的一样，这些机器人很久不工作了。电脑控制台不再执行我的命令了，而我没有身体亲自去激活控制台。我什么事都做不了。你能能我修好这个电脑吗？我需要控制机器人的能力……为了让这的一切都正常。}
{261}{}{好吧，为什么不？我会去看看出什么问题了。}
{262}{}{不，我没有时间。再见。}

# Node  7  [Node008]
{270}{}{好吧那我……嗯……*叹气*你是对的。这些机器人不再听我的命令了。他们就一直坐在那一动不动。电脑终止了机能，作为一个全息人我没法用键盘。这种情况已经很多年了，这个地方需要重建，恢复。*叹气*希望有一天我再有能力来做这些。}
{271}{}{也许我能帮你些什么？我对电脑很在行的。}

# Node  8  [Node009]
{280}{}{谢谢。如果你能修好电脑。我会给你一个高级别的安全允可权。你能带走储备室的任何东西。那些东西对我没什么用。}
{281}{}{谢谢，我修好后会回来的。}

# Node  9  [Node010]
{290}{}{走开。我没什么可以和你说的。}
{291}{}{好吧。}


# Node  10  [Node011]
{300}{}{你处理好电脑的问题了吗？*眼中充满期待*}
{301}{}{不，还没呢。我努力的。}

# Node  11  [Node012]
{310}{}{那些电脑又连线了吗？}
{311}{}{是的，我为你修好它们了。你又可以控制机器人了。}

# Node  12  [Node013]
{320}{}{好极了！干的不错！我现在可以压碎那些白痴了！EPA又可以清静了。这个通行卡可以让你自由通行，我保证过的。这些机器人又恢复控制了。你可以解散了。}
{321}{}{谢谢。}
{322}{}{解散？我是什么，一个守卫？等等，老头。}

{330}{}{走开，让我静一下。}
{331}{}{我不想为你再做任何事了。}
{332}{}{滚开！！}

{333}{}{我现在很忙！}
{334}{}{一会再来！}
{335}{}{你没看见我在工作吗？}
{336}{}{我们必需马上摧毁这个地方！}
{337}{}{那真可笑！}
{338}{}{决不！}
{339}{}{只有毁灭旧的，新的才能重生。}
{340}{}{都赞同吧？}
{341}{}{The robots must be reactivated!}
{342}{}{Warmduschers! All of you!}
{343}{}{Our weapon defenses are in dire need of ammunition!}
{344}{}{If I was in charge, things would actually get done around here!}
{345}{}{Halt die Schnauze!}

{400}{}{Arrest me? You're a hologram. You can't even touch me.}
{401}{}{I see I got a goddamn Klugschei遝r on my hands! You think I can't beat the piss out of a Warmduscher like you? Well, maybe I can't, but that's what the damn robots are for! Now I'm running out of patience real fast. You best start explaining yourself. How do I know you're not a Chinese spy?}

#added in RP 2.1 - if you already repaired the computer before talking to him
{410}{}{You the one that brought the robot control computer back online?}
{411}{}{That's right.}
{412}{}{Uh...maybe.}
{413}{}{Nope. Wasn't me.}
{420}{}{Quatsch! You're the only flesh and blood being around, so I damn well know it was you.}
{421}{}{Alright, fine, it was me.}
