{100}{}{这个发电机看上去有一些问题。也许你能修好它。}
{101}{}{你看见一个发电机。}
{102}{}{你看见EPA的照明发电机。}
{103}{}{你看见一个发电机，那是撑控EPA的照明系统的。}
{104}{}{经过几分钟的查找，你发现一个电路有些部件损坏了。也许你能从路上找到的那些垃圾碎片里找到可代替这部份的东西。}
{105}{}{那有问题。}
{106}{}{你修好了损坏的部分，发电机又开始运行了。}
{107}{}{Nothing wrong can be found with the generator. It just doesn't seem work.}
{108}{}{It's working. There's nothing else to do.}
{109}{}{Something doesn't seem right with this generator.}

{200}{}{*whirr*}
{201}{}{*bzzt*}