# 0. QUICK LOOK
{100}{}{你看见火箭人．洛尼司可。}

# 0. LOOK (GLASSES = DISCOUNT, FREEBIE, DONE)
{150}{}{你看见一位带又大又厚的眼镜的老人。}

# 0. LOOK (GLASSES = NOTHING)
{200}{}{你看见火箭人．洛尼司可。他把它的破碎的眼镜拿下来，把唯一好的透镜擦干净。}
{201}{}{你看见火箭人．洛尼司可。他把它的破碎的眼镜拿下来，把唯一好的透进擦干净。}

# 1. FLOAT DIALOGUES (WTG)
{210}{}{再一个透镜我就别无所求。}
{211}{}{他妈的烂货眼镜！}
{212}{}{干！我的眼睛！}
{213}{}{你要买东西吗？}
{214}{}{这里不是间厨房。你要买东西吗？}
{215}{}{如果我再坚持下去我的眼睛就要瞎了。}
{216}{}{我需要多一点的干铁九号。}
{217}{}{要求上涨了。}

# 2. FLOAT DIALOGUES (WTG)
{225}{}{去死。}
{226}{}{快出去。不然我就杀了你。}
{227}{}{滚出去！}
{228}{}{滚！滚！滚！滚！滚！}

# 3. INTRO SPIEL (WTG)
{235}{}{(老人把眼镜调一下，叹一声说)你要什么？}
{236}{}{快点啦。}
{237}{}{快点啦。}
{238}{}{你最好退后喔；我要脱裤子了。}
{239}{}{你最好退后喔；我要脱奶罩了。}
{240}{}{你要什么？你有什么？}
{241}{}{看他一下，确定他是真的，然后走掉。}
{242}{}{你是谁？}
{243}{}{喂，我有一副眼镜，你要吗？}
{244}{}{你的眼镜怎么了？}
{245}{}{你知道吗，有些没咖啡碱的咖啡跟真货味道一模一样。}
{246}{}{我来错地方了。再见。}

# 4.  RETARD (3, 5)
{255}{}{吓一跳。}
{256}{}{又是一个浑蛋！滚蛋！不要回来！(举起拳头）滚！}
{257}{}{对不起}
{258}{}{我不会穿奶罩}
{259}{}{不要叫}
{260}{}{恨你！}
{261}{}{我走了，我走了。暂时．．．}

# 5.  WHO ARE YOU? (3)
{270}{}{我？呵呵，我是圣诞老公公！神经病～～～}
{271}{}{我？呵呵，我是圣诞老公公！而你一定是那个流浪的痞子！}
{272}{}{我？呵呵，我是圣诞老公公！而你一定是那个变态的小子！}
{273}{}{我？呵呵，我是圣诞老公公！而你一定是那个给老人服务的淫娃！}
{274}{}{还好我不需要自我介绍。你在这里做什么，“老公公”？}
{275}{}{圣诞老公公？他是谁啊？}
{276}{}{喂，老公公，你再胡言乱语的话小心我把你的牙齿做成个项链。}
{277}{}{喂，这次我当作没听见好了。你是谁？}
{278}{}{你真文雅，“老公公”。你是这里人吗？}
{279}{}{算了。我走了。}

# 6. WHO ARE YOU? (3, 5)
{290}{}{(盯着你。)我的名字叫洛尼司可。怪物，你要什么就快点说出来。 (瞪着你。)你看起来像个猩猩。}
{291}{}{我是从西北边的小镇，阿罗由来的。}
{292}{}{你卖什么？}
{293}{}{我要什么？大部分时间我走到别人家里，看道好东西就拿。嘿嘿～～就像那个！}
{294}{}{真是出口成章。你是这里人吗？}
{295}{}{我走了。}

# 7. WHAT DO YOU SELL? (6, 36, 42)
{305}{}{我卖毒品，所以他们才叫我“火箭人”。我也卖商队的材料。你要什么？}
{306}{}{“火箭人”？有个旧歌说“火箭人，烧于家中之——”；他到底在说什么啊？}
{307}{}{我能看你的货吗？}
{308}{}{你在店里卖毒品？}
{309}{}{你是说卖毒品给莱特的儿子？}
{310}{}{回去做你的事情吧。}

# 8. ROCKETMAN/IGNORE QUEST (6, 7, 32, 36)
{320}{}{(洛尼司可瞪着你，在脑子里幻想你的裸体。）}
{321}{}{算了。我有其它问题。}
{322}{}{算了。}

# 9. YOU SELL DRUGS IN THE STORE? (7)
{330}{}{(洛尼司可瞪着你。)已经不是二十世纪了，毒品只在店里卖不在街上卖。}
{331}{}{好吧，那——}
{332}{}{但是——}
{333}{}{我最好——}

# 10. YOU SELL DRUGS IN THE STORE? (9)
{350}{}{这是是新里诺；没有警察，没有律法，而且有一大堆人喜欢到药局里买毒药。懂了吗，山顶洞人？}
{351}{}{还有：莱特的儿子是你的顾客吗？}
{352}{}{好啦，好啦；你有什么？}
{353}{}{其实呢，我有些问题．．．}
{354}{}{就如你所说，毒品害人的心灵；你仍无为所动吗？}
{355}{}{当然啦。我走了。}

# 11. DOES IT BOTHER YOU TO SELL DRUGS IN THE STORE? (10)
{365}{}{卖毒品给白痴，奴隶分子，黑社会老大，土人，与其他孬种难道会影响世界吗？想一想喔！}
{366}{}{好吧．．．我可以看看你的货吗？}
{367}{}{好啦，好啦；我有些别的问题。}
{368}{}{这里的毒品发散天下，并且害人不浅。你忍心吗？}
{369}{}{我想我得走了。}

# 12. YOU SELL DRUGS IN THE STORE 2? (11)
{375}{}{那又如何？我管他们去死！}
{377}{}{人类正于重建之中，从新开始；而杰特是人类克星。}
{378}{}{随便吧。我该走了。}

# 13. SOME OF THE PEOPLE BEING HARMED ARE . . . (12)
{385}{}{那又如何？又没人逼他们服用！}
{386}{}{看来——}
{387}{}{但是不要——}
{388}{}{那是你的——}

# 14. SOME OF THE PEOPLE BEING HARMED ARE . . . 2 (13)
{395}{}{那些瑞丁的白痴知道他们在做什么，所以我没有一点愧疚！我觉得杰特可以帮助消灭人类大战中该死的败类！}
{396}{}{呃，好吧。我能看你的货吗？}
{397}{}{瑞丁在哪里啊？你为什么提及他们？}
{398}{}{杰特为什么在瑞丁城那么普遍？}
{400}{}{那是你的看法。而我走了。}

# 15. REDDING 1 (14)
{410}{}{瑞丁城很特别。里诺保证瑞丁城的毒品供应。一吃杰特就上瘾了。我这样才能做生意啊。}
{411}{}{我能看你的货吗？}
{412}{}{谁保证瑞丁城的供应？又为什么？}
{413}{}{我也发现到这一点．．．我有别的问题．．．}
{414}{}{原来如此。我该走了。}

# 16. WHO'S SUPPLYING REDDING? (15)
{420}{}{喂，土人，你大概还没发现到，里诺没有开发什么产品。但是瑞丁城．．．。}
{421}{}{继续。}
{422}{}{生产有用的东东。}
{423}{}{够了！}

# 17. . . . DOES PRODUCE SOMETHING USEFUL (16)
{430}{}{喂，我警告你，先等我讲完！山顶洞人．．．难怪你们还用木枪．．．}
{431}{}{我倒不一样；我会用各种武器杀人。我弄给你看。}
{432}{}{对不起。请继续。}
{433}{}{去死。我走了。}

# 18. GO ON ABOUT REDDING (16, 17)
{440}{}{瑞丁城都是掘金矿；新里诺用的到那些金子。他们只要上瘾，他们的金子就都是我们的了！}
{441}{}{不错，可是：杰特是从哪里冒出来的？}
{442}{}{谁想叫工人上瘾？}
{443}{}{嗯，我懂了。我有其它问题．．．}
{444}{}{我听够了。我走了。}

# 19. WHERE DID JET COME FROM? (20)
{450}{}{(指着麦朗。)你何不问你的麦朗啊？他一定会很高兴地告诉你。(瞪着麦朗。)是不是？}
{451}{}{我们要多谢莫丁诺的小神童，麦朗。是他发明杰特的。大基苏．莫丁诺只告诉大家在哪里可以得到杰特。}
{452}{}{告诉我麦朗的事情。}
{453}{}{杰特有解毒剂吗？}
{454}{}{我有些别的问题．．．}

# 20. WHERE DID JET COME FROM? (18)
{460}{}{大基苏．莫丁诺把毒品给瑞丁城的工人，叫他们上瘾。他们就越来越上瘾啰。}
{461}{}{杰特是从哪里冒出来的呢？}
{463}{}{我有别的问题．．．}

# 21. TALK ABOUT MYRON (19, 24)
{470}{}{又好色又聪明的小鬼。但是很聪明喔。智商很高。浪费他的脑筋来做毒品。}
{471}{}{我哪里可以找到他？}
{472}{}{我有些别的问题．．．}

# 22. WHERE CAN I FIND MYRON? (21)
{480}{}{莫丁诺把他关在什么地方我也不知道，不过一定守得很紧吧。}
{481}{}{谢谢。我能看看你的货吗？}

# 23. ANY CURE FOR JET? (19, 20)
{490}{}{解毒剂？我只知道两个，一个是自杀，一个是把自己关在笼子里一年不碰杰特。哈！怎么会有解毒剂？！}
{492}{}{一定有解毒剂的。杰特的成份是什么？}

# 24. JET COMPOSITON? (23)
{505}{}{你问你的朋友吧；是他发明的。}
{506}{}{我只卖杰特；你应该去问个科学家．．．或者问麦朗。是他发明的。}

# 25. TALK ABOUT VILLAGE (6, 42)
{515}{}{(洛尼司可安静地盯着你。)}
{516}{}{(洛尼司可再次安静地盯着你。)}
{517}{}{我想你一定会喜欢阿罗由的。那里是个平静的地方。}
{518}{}{喂，你有没有听说过伊甸园创造器，或者避难所１３吗？}
{519}{}{好吧，我走了。}

# 26. TALK ABOUT VILLAGE 2 (25)
{525}{}{(洛尼司可还在盯着你。)}
{526}{}{有时候老人为了小事发脾气，像那夜我跟神腿瑞纳去偷情．．．}
{1526}{}{有时候老人为了小事发脾气，像那夜我跟神雷格儿去偷情．．．}

# 27. TALK ABOUT VILLAGE 2 (26)
{535}{}{(洛尼司可瞪你。)}
{536}{}{就如昨天．．．瑞纳的银身体在月光下．．．你可能会喜欢老人喔。她差不多你的年纪。}
{1536}{}{就如昨天．．．格儿的铜身体在月光下．．．你可能会喜欢老人喔。她差不多你的年纪。}

# 28. WHO ARE YOU? (27)
{545}{}{(洛尼司可还是在看你，好像他会用内功把你的身体消失掉。)}
{546}{}{我有没有说阿罗由是我的祖宗，避难所人所创造的？(骄傲。)现在，轮到我寻找神秘的伊甸园创造器！}
{547}{}{好了。故事说完没？我走了。避难所万岁！}

# 29. GECK? (25, 26, 27, 28, 36)
{555}{}{(洛尼司可累了。)}
{556}{}{伊甸园创造器？有复制装置，幻碟机，还有一个小的手电筒？}
{557}{}{是，但是现在还不重要。我要讲完阿罗由的故事。}
{558}{}{是！我的村子长不出东西来！你知道哪里可以找得到一个伊甸园创造器，来就我的村子吗？}
{559}{}{传说那东西是锁在第１３号避难所中．．．你知道这个地方吗？}
{560}{}{你不愿意听的话，我就走了。}
{561}{}{可能吧。我该走了。}

# 30. I HAVEN'T FINISHED TELLING YOU ABOUT ARROYO (29)
{570}{}{你他妈的找伊甸园创造器干嘛？}
{571}{}{我要伊甸园创造器来从造家园。}
{572}{}{据说在避难所１３。你知道那是哪里吗？}
{573}{}{我还不想告诉你。再见。}

# 31. GECK NEEDED TO RESTORE VILLAGE (29, 30)
{580}{}{当然可以啰。如果你找得到的话。你大概不知道从哪里开始找．．．新加州共和国还是地下掩体市也许有吧，可是．．．}
{581}{}{还是．．．}

# 32. GECK NEEDED TO RESTORE VILLAGE (31)
{590}{}{还是，那些自以为是的混帐也许可以指点你。如果他们慢慢地讲话而且用比较小的字．．．}
{591}{}{新加州共和国还是地下掩体市吗？我去那些地方问问市民们。谢谢。}
{592}{}{为什么不能在避难所１３里呢？经文里说伊甸园创造器在里面喔。}
{593}{}{很好笑。我有些别的问题．．．}
{594}{}{好吧，我去检查一下。谢谢。}

# 33. GECK NEEDED TO RESTORE VILLAGE (X)
{600}{}{不是啦，山顶洞人。我听过避难所，可是没听过避难所１３。最相近的就是地下掩体市，在东北边，就算那些高级人士住过避难所一次，他们一定现在不在了。}
{601}{}{地下掩体市？我会去找此地下掩体市，并询问他们关于伊甸园创造器的事情。}
{602}{}{什么？难道不只一个避难所吗？}
{603}{}{我有其它问题。}

# 34. THANKS (32, 33, 35)
{610}{}{你要去地下掩体市的话，不要谢我。你在新里诺比较安全。至少给你量棺材的人比较诚实。}
{611}{}{好吧，我要到地下掩体市去了。避难所万岁！}
{612}{}{原来如此。谢谢你的警告。}

# 35. MORE THAN ONE VAULT? (33)
{620}{}{否则怎么会叫避难所１３啊？白痴！你们的部落是不是脑筋发育不良？}
{623}{}{你又在夸奖我了。谢谢你的资料。}

# 36. YOUR VOCABULARY IS IMPRESSIVE (6, 42)
{630}{}{一个人过去不是好话题．．．你到底要什么？}
{632}{}{你听起来颇有才学。你听说过伊甸园创造器还是避难所１３吗？}
{634}{}{算了，没事。}

# 37. GLASSES (3, 42)
{640}{}{(洛尼司可把你的眼镜抓过去然后带上去。)里诺他妈的！原来这个店是这副德性啊！书架上是什么啊？看起来像双头牛粪。}
{641}{}{不客气。}
{642}{}{好好享用。}

# 38. YOU'RE WELCOME (37)
{650}{}{哼！你从哪里得来的？}
{651}{}{有一只超小的辐射蝎，还有一个科学家。科学家在训练辐射蝎，还有．．．你知道吗？连我都不信！你收下来就好了，好吗？}
{652}{}{就说我在某某地方找到的。某某地方。}

# 39. YOU'RE WELCOME 2 (37)
{660}{}{喂！等一下！你是从哪里得来的？}
{661}{}{有一只超小的辐射蝎，还有一个科学家。科学家在训练辐射蝎，还有．．．你知道吗？连我都不信！你收下来就好了，好吗？}

# 40. I GOT THEM (38, 39)
{670}{}{我．．．其实我很感激你；我还以为我永远都要用那副烂眼镜．．．如果你需要什么，告诉我；我会．．．想一想。}
{671}{}{给我减价如何？}
{672}{}{算了。祝你身体健康。我还有其他问题。}
{673}{}{有一天，我会叫你帮我做件事情。现在呢，就当作是我女儿的生日给你的礼物。}

# 41. DISCOUNT (40)
{680}{}{喔～～}
{681}{}{呜～～}
{682}{}{那么～～}
{683}{}{好啦，好啦！我给你减价啦！哼。}
{684}{}{好不好啦？小的减价就好啦。好不好啦？}
{687}{}{好！我来看看你有什么，兄弟。}
{688}{}{太好了！我还有些别的问题．．．}
{689}{}{我下次再回来来。}

# 42. QUESTIONS? (8, 10, 11, 14, 15, 18, 19, 20, 21, 22, 23, 24, 32, 33, 41, 49, 50, 51, 54, 55, 57, 65, 66, 67, 68, 71, 72, 73, 74, 75)
{700}{}{有话快说，有屁快放。}
{701}{}{喂，我很忙耶。}
{702}{}{紧啊！}
{703}{}{说啊．．．}
{704}{}{我跟你讲过我的故乡阿罗由的故事吗？}
{706}{}{你卖了杰特给莱特吗？}
{707}{}{我来给沙尔瓦多纳贡。}
{710}{}{我来找破碎丘的矿零件。}
{711}{}{你真文雅。很有意思。你是这里人吗？}
{712}{}{算了。}

# 43.  TOOLS: SO? (3, 42)
{725}{}{(缩眼。)那又怎么样？}
{726}{}{我需要一些材料来修一修我的空气清净器。听说你可以帮我的。}
{727}{}{我需要一些材料来修一修我的空气清净器。赛斯叫我来的。他说．．．呃．．．他妈的。}
{728}{}{我需要一些材料来修一修我的空气清净器。赛斯叫我来的。他说“金丝彩雀踢水桶”。}

# 44.  TOOLS: SURE. HERE'S SOME MONEY (43)
{735}{}{是，我有你所要的零件。＄１００。}
{736}{}{好！我要了。给你。}
{737}{}{＄５如何？}
{738}{}{呃，我没带足够的钱。我等下再回来。}

# 45.  200 OR NOTHING (3, 42, 44)
{745}{}{最近生意不景气喔～～～＄２００。}
{746}{}{(皱眉头。)＄２００。}
{747}{}{＄２００？！你刚才还说＄１００呢！}
{748}{}{好啦。我买啦。}
{749}{}{我身上现金不足～～～下次再来。}

# 46.  HE SAID: SHIT (43)
{755}{}{我不相信他说什么“金丝彩雀踢水桶”。}
{756}{}{是啦。}

# 47.  HE SAID: AND . . . (43, 46)
{760}{}{还有——}
{761}{}{“还有？”}

# 48.  SECOND PART? (47)
{765}{}{而接着是第二部分是？}
{766}{}{第二部分？没了啊！他没说！那个浑——}

# 49.  HE DIDN'T?! THAT BASTARD! (44, 45)
{769}{}{我只是在试探你而已。没有第二部分。如果真的是赛斯叫你来的话，我也许有东西可以给你的。}
{770}{}{给你。拿好。}
{771}{}{谢谢。我有些别的问题．．．}
{772}{}{呃，谢啦。}

# 50. YOU SELL DRUGS TO WRIGHT'S SON? (7, 10, 42)
{780}{}{不要怪我！如果你真的想知道是谁做的，问张三跟李四如果他们还在卖有砒霜的杰特。}
{781}{}{张三李四？谁啊？}
{782}{}{朱尔斯叫我问你。他说你的货都很烂。}
{783}{}{歪吉米叫我问你的。他说你的货都很烂。}
{784}{}{他们都都叫我去问你。他们都说你的货都很烂。}
{785}{}{我不觉得他是因砒霜而死的。我觉得他是中毒而身亡。}
{786}{}{你能解释这个空的杰特包装吗？}
{788}{}{我去问他们。}

# 51. WHO ARE THEY? (50)
{795}{}{那些人狗嘴里土不出象牙来。他们两个都是骗子。一个比一个烂。}
{798}{}{他们都叫我问你。他们都说你卖的是烂货。致命的烂货。}
{800}{}{我去问他们。}

# 52. THEY SAID ASK YOU. (51)
{805}{}{喂，你不知道你在说什么。}
{806}{}{我想——我——}
{807}{}{是吗？你何不——}
{808}{}{算了。我有些别的问——}
{809}{}{我得走——}

# 53. THEY SAID ASK YOU 2. (52)
{815}{}{你再乱叫一声，跟莱特暗示我或你跟那小子的毒，我们的生命就不如双头牛粪啰。如果真的——}
{816}{}{噢？那你——}
{817}{}{我？等——}

# 54. THEY SAID ASK YOU 3. (53)
{825}{}{如果真的发生的话，我要你先死！记清楚了：他没有跟我买任何东西！再也不要提及他的名字，否则——}
{826}{}{朱尔斯说不是他。吉米说不是他。你又说不是你。你们其中一个有鬼。}
{827}{}{朱尔斯说不是他。吉米说不是他。你又说不是你。除非你们都在骗我，还是——另有他人。}
{828}{}{你能告诉我莱特的事情吗？他跟谁混在一起？}
{829}{}{我有其它问题。}
{830}{}{好啦，我走啦。}

# 55. THEY SAID THEY DON'T KNOW. (54)
{835}{}{当然是他们其中一个在撒谎。他们两在里诺卖百分之九十的杰特。一定是他们。}
{836}{}{或着有人跟你们其中一个买的。你有没有跟受害者有关系的客人？}
{837}{}{你能告诉我些别的关于莱特吗？他跟谁混在一起？}
{838}{}{原来如此。我有些别的问题．．．}
{839}{}{我走了。}

# 56. THEY SAID ASK YOU. (55)
{845}{}{你笨蛋。}
{846}{}{你婊子。}
{847}{}{我叫你不要乱叫的。滚蛋！我在看见你的话，我就把你给杀了。如果莱特来找我的话，你先死！}
{848}{}{不要威胁我，老头。}
{849}{}{哇。我走了。}

# 57. KILLER REVEALED! . . . (55)
{855}{}{我不知道。我不认识他，所以我就没办法告诉你他的朋友或习惯。唯一能告诉的人早就死在葛洛沙了。}
{856}{}{葛洛沙？}
{858}{}{也许吧。再见。}

# 58. TRIBUTE (3, 42)
{865}{}{看来你白来一趟了。我两周前早已付给他了。我不知道你是谁，可是我一毛也不给你。滚。}
{866}{}{喂，老头，不要为难我了。快给我，否则准备受死。}
{867}{}{我是沙瓦尔多的人。快快把钱交过来。}
{868}{}{我回去检查一下，再回来。}

# 59. TRIBUTE 2 (58)
{875}{}{你耳聋了吗？}
{876}{}{你没听见吗？}
{877}{}{我说我早．已．付．给．他．了。你是沙瓦尔多的人的话你就明白啰。滚蛋。}
{878}{}{最后一次。交过来。}
{879}{}{我是沙瓦尔多派来收钱的。快快交出来。}
{880}{}{我已经警告你了。准备受死吧。}
{881}{}{我回去检查一下，再回来。}

# 60. SPEECH SUCCESS (59)
{890}{}{证明你是沙瓦尔多的人，我就也许会给你的否则，你什么也别想跟我要。}
{891}{}{我不需要证明我自己。我是他们的人。}
{892}{}{你觉得这个激光手枪是假的吗？}
{893}{}{我给你五秒钟。}

# 61. SPEECH FAILURE (59, 60)
{900}{}{滚蛋，否则我就亲自把你给杀了！}
{901}{}{我警告过你了。准备受死。}

# 62. SHOW OFFICIAL, CAN'T PAY (3, 42, 60)
{910}{}{哼，没用，我已经没钱了。上次差点把我给洗光了。}
{911}{}{我管。沙瓦尔多不要听你的理由。}

# 63. GIVE ME MONEY EVEN THOUGH YOU CAN'T PAY (62)
{920}{}{没用啦。我没钱啦。他会生我的气，但他也会生你的气。沙瓦尔多不喜欢空手而回的人。}
{921}{}{我已经帮你付了。但是你要给我减价。}
{924}{}{我想一想再回来。}

# 64. IN EXCHANGE FOR FREE ACCESS TO YOUR STORE (63)
{930}{}{等等，山顶洞人．．．}
{931}{}{我不跟你多说了。我的耐性有限。}

# 65. THOSE ARE MY TERMS (64)
{940}{}{好啦，给你减价。}
{941}{}{让我按一看你有什么。我现在要买东西。}
{943}{}{我下次再回来。}

# 66. HOW'S THE GLASSES (64)
{950}{}{(无奈。)也吧。如果你在等待奖状的话，你搞错了。你要什么？}
{951}{}{他妈的什么死爪还是买卖管理养你的？你要什么吗？拿，全都拿走！}
{952}{}{让我看看你的货。}
{953}{}{我有一些问题。}
{955}{}{这是什么东西？}

# 67. POISONED (50)
{960}{}{中毒了？你在说什么？}
{961}{}{他是中了辐射蝎的毒而死的。是因为杰特中有毒，而不是因为服用太多。}
{962}{}{我找到一个空的杰特包装在他的房里。有辐射蝎的毒在里面。}
{963}{}{算了。我有其它问题。}
{964}{}{算了。我走了。}

# 68. POISONED 2 (67, 73, 74)
{970}{}{蝎子？(大惊．．．好像记的什么了．．．)}
{971}{}{你这崽子，是你毒死他的，是不是？}
{972}{}{你知道一些东西，是不是？}

# 69. POISONED 3 (68)
{980}{}{喂喂！！等一下。}
{981}{}{不要耍花招，洛尼司可。别想逃了！否则我让你的下场跟他一样！懂吗？}
{982}{}{我去和莱特说。再见，洛尼司可。很高兴能认识你。}

# 70. POISONED 4 (69)
{990}{}{等一下！喂，我没有卖给他！他什么都没跟我买！是别人叫我做的！但是我没卖给他啊！}
{991}{}{有人叫你做有毒的杰特？是谁叫你做的？}
{992}{}{你卖给谁了？}

# 71. POISONED 5 (70)
{995}{}{沙尔瓦多叫我买的——我还不知道他们要给莱特那小子．．．相信我！我不会去毒死小孩子的！}
{996}{}{毒死大人而已吗？你这个浑蛋．．．}
{997}{}{你为什么要那样做？你不知道会弄出人命的吗？}
{998}{}{好啦，我相信你。我有其它问题。}
{999}{}{闭嘴。我有其它问题。}
{1000}{}{沙尔瓦多吗？莱特一定很想知道吧。}

# 72. RESPONSE (71)
{1005}{}{沙尔瓦多拥有我，我的店；他们要什么，我就给他们，否则我就死定了。我真的并非想杀害那小子。}
{1007}{}{闭嘴。我有其它问题。 }
{1008}{}{嗯，我相信你是以良心家毒的。再见。}
{1009}{}{再见。}

# 73. JET CANISTER (50)
{1020}{}{是空的。是个很平凡的杰特包装。还有呢？}
{1021}{}{是不是你的？}
{1022}{}{知道关于里面的辐射蝎的毒的事情吗？}
{1023}{}{嗯，我有问题。}

# 74. JET CANISTER (73)
{1030}{}{不。还有事情吗？}
{1033}{}{没有了。再见。}

# 75. GOLGOTHA? (57)
{1040}{}{葛落沙？很大的墓地在城外南边。沿着臭味可到。比你还要臭的臭味。}
{1041}{}{噢。我有其它问题。 }
{1042}{}{小心你的嘴巴！}
{1043}{}{谢谢。}

{2000}{}{你曝露了洛尼司可与莱特公子之死有关系的消息。}

# END LINES
{5257}{}{很大。我走了。}
{5259}{}{不要叫你要什么一直叫不要叫}
{6259}{}{杀你。}
{5260}{}{他们会找人来扁你的喔！到时候就吃冰淇淋跟蛋糕来庆祝——}
 
 
# Heart pills quest - RP
{6000}{}{I was looking for some pointers on heart health. Think you could fill me in on a thing or two?}

{6010}{}{I know this must come as something of a shock to you, but a white smock does not automatically confer a cardiology degree. I am a pharmacist. I produce chems. Then you buy them. Then, you leave. Quietly.}
{6011}{}{Fair enough. Moving on, then...}
{6012}{}{C'mon, could you humor me? Just this once? Pretty pleeease?}

{6020}{}{Fine. My prescription is cigarettes and red meat, in large quantities. Was that all? If I have to put up with much more vacuous prattle today, I'm liable to have a stroke myself.}
{6021}{}{Yeah, you are pretty high strung, aren't you? I'll bet Hakunin could help you with that. He's the medicine man back home, in Arroyo. Say, have I ever told you about Arroyo?}
{6022}{}{And wouldn't that be a tragedy. Next question...}
{6023}{}{Okay then, just one more quick thing...}
{6024}{}{Gee, thanks Renesco. I knew I could count on you. You take care now.}

{6030}{}{I need you to fix me up with a special order.}
{6031}{}{So, about that special order we were discussing...}

{6040}{}{Yes? And? Were you expecting me to read your mind, or would you like me to surprise you?}
{6041}{}{Not on your life, asshole. What I need are some... um... pills. For, um... (trail off, glance pointedly in the direction of your belt buckle, look Renesco in the eye, and clear your throat).}
{6042}{}{Not on your life, asshole. What I need are some... um... pills. For, um... a man's... (trail off, glance pointedly in the direction of your belt buckle, look Renesco in the eye, and clear your throat).}
{6043}{}{I'd like you to make me a batch of, erm, "Corsican Brothers chewable multivitamins."}
{6044}{}{I'm looking for something you'd use to, uh, sharpen your spear, you know? Put a little bite back into your gecko?}
{6045}{}{I'm looking for something a man would use to, uh, sharpen his spear, you know? Put a little bite back into his gecko?}
{6046}{}{I'm looking for a complex PDE5-inhibitor compound, and I need the pills made according to my distinct specifications.}

{6050}{}{What in Golgotha are you babbling about? English, Tribal! Do you speak it?}
{6051}{}{(Sigh...) I would like you to make me some... erectile dysfunction medication.}
{6052}{}{You know. Boner pills. Uh, for a friend.}
{6053}{}{Boner pills. Not for me, obviously.}
{6054}{}{You know exactly what I mean, you withered old bastard.}

{6060}{}{(He leers derisively at you.) Hnn! I wouldn't exactly call that a "special" order. Half the reason this deviant cesspit of a city exists is to provide rutting degenerates such as yourself with an easy means of drowning in their own unsavory juices.}
{6061}{}{I've got over a dozen brands here. Take your pick. And don't hurt yourself thinking too hard about it; they're all completely identical aside from the packaging.}
{6062}{}{None of that is going to cut it. I need these made to order.}
{6063}{}{That's a good start, but I had something specific in mind.}

{6070}{}{(He sneers.) Oh, discerning customer, are you? Fine. Go on. It's been awhile since I got to charge anyone the specialty rate. Most of the local street vermin could care less what they're killing themselves with.}
{6071}{}{Yeah, I hear that works out pretty well for you. Get those dollar signs out of your eyes, though, I'm not asking for anything too special. Just take some of that off the rack crap, grind it up, and shape it into smooth, circular, red pills, about yea big. Sound doable?}
{6072}{}{(Show Renesco one of the heart pills.) What I need you to do is to make me a batch of those pills, only they need to look *exactly* like this one.}
{6073}{}{Chemically, the base formulation can match the generic. As far as physical parameters... hmm... let's say, about a centimeter and a half in diameter, smooth, mildly rounded face, dull red coating. Lozenge edge of about an eighth-centimeter. Shouldn't be too much of a challenge for a man of your experience.}

{6080}{}{Hmmm. Is that all? Remedial stuff, really. And the base materials are dirt cheap. Accounting for labor... $200 should suffice.}
{6081}{}{What?! If I wanted to get screwed, I'd have gone to the Cat's Paw! At least I'd know what I was getting myself into.}
{6082}{}{You know as well as I do that we're talking about $15 in chems and five minutes of mortar work. I think we need to talk some numbers here.}
{6083}{}{All right. You've got overhead, I've got better places to be. $200.}
{6084}{}{Not sure I can spare that much at the moment. Maybe we'll come back to this later.}

{6090}{}{(His scowl deepens.) I'm not in the mood to beat around the bush with you. You think I'm going to buy that you're just some particularly picky homo not-so-erectus? PLEASE! Do you have any idea how long I've been doing this?}
{6091}{}{You obviously haven't spent much time out of your cave, so take my word for it when I say there aren't too many kinds of pills going around that match that oddly specific description of yours, and one *very notable* one comes to mind immediately. "Specialty" items, specialty prices, throwback. Welcome to New Reno. That'll be $300.}
{6092}{}{Look, I made sure no one even *breathed your name* in connection with that Wright affair. You do this for me, we're square. Okay?}
{6093}{}{I covered your ass with Salvatore. Consider this collection on your debt.}
{6094}{}{I don't think *Mr. Bishop* would be very happy with you if he knew you were hindering his interests like this, Renesco.}
{6095}{}{Fine. $300, and that's for the pills *and* your discretion. Understand?}
{6096}{}{Whoa, easy there fuzzy little man peach. Maybe I'll just come back when you're in a better mood.}

{6100}{}{Well. I guess that concludes our business, then. I must say, tribal, this has been... almost *tolerable*. Now, sit on your hands and try not to ruin the moment. (Renesco takes your money and goes to work.)}
{6101}{}{(Minutes pass. Renesco dusts off his hands and rolls a pill bottle indistinguishable from Westin's across the counter at you.) There you are. Now, are we done here?}
{6102}{}{Let me ask you something else.}
{6103}{}{That's it for me. See you around.}

{6110}{}{(Renesco flushes, nostrils flaring in anger, but then looks down and begins cleaning his glasses very intently on his smock as he speaks.) Primate, the ONLY two things I will EVER be indebted to you for are JACK and SHIT.}
{6111}{}{Now, that being the case... if it will disabuse you of this intolerable provincial delusion that you've somehow got something over me, the very THOUGHT of which makes me ill in ways I lack the words to describe... }
{6112}{}{I... SUPPOSE... your thrice damned pills are a small price to pay. And if I EVER AGAIN hear you say a word that even RHYMES with "owe," the shop is getting a new chimp-skin rug. Sit down, shut up, and work on growing a pair of opposable thumbs while I get this compounded. (Renesco goes to work.)}

{6120}{}{(Renesco gazes around wide-eyed at the rest of the shop's chemically stupefied patrons before leaning in and rounding on you in a lowered voice, sibilant with rage) You. IGNORANT. Toad-licking, tumleweed worshipping ass. I don't think *Mr Bishop* would be very happy AT ALL if he were to hear that one of the talking brahmin turds on his payroll had been dropping his name while purchasing HIGHLY SPECIALIZED MURDER WEAPONS.}
{6121}{}{In fact, I don't think *anyone involved* would be very happy about it in the end, unless you count the feeling of relief that comes when Bishop's people finally tire of pulling bits off of you with METALWORKING TOOLS and decide to FINISH THE JOB.}
{6122}{}{(He blanches.) Oh God. I didn't hear this. I can't know this. Turn around. Get out. NOW. Find somewhere else to finish this mystical, ancestral vision quest up your own ass. Somewhere far, far away. (Renesco hurries off to look busy on the other side of his cage.)}

{6130}{}{All the parts that weren't belches or grunts, anyway. Now wait here. (Renesco takes your money and goes to work). And for the love of God, *try* not to get any of my merchandise stuck in your simian face-holes while my back is turned.}

{6141}{}{Oh, *this* again. My fee is $200, in the highly likely event that it slipped your mind.}
{6142}{}{Once more, in case you were distracted by something shiny the first time around: $300. And don't push your luck.}
