{100}{}{你看到一个很老，但是看起来很亲切的人。}
{101}{}{那是朱伯利医生。}
{102}{}{那是一个有着雪白胡子的老人。}
{103}{}{我是朱伯利医生。那里不对劲吗，年轻人？}
{104}{}{那里不对劲吗，年轻人？}
{105}{}{我好痛。}
{106}{}{我需要一个医生。}
{107}{}{你难道不能吃一些药或者是怎么样的，但是不要来烦我好吗？}
{108}{}{哼，你根本就几乎没有在流血嘛。}
{109}{}{我不知道。但是我不觉得我能够救你的腿，也许我们得要把它切掉。}
{110}{}{你在开玩笑吧。}
{111}{}{哈哈。}
{112}{}{就是那样，小子。}
{113}{}{再一次。}
{114}{}{谢谢，医生。也许你可以给我一些答案。}
{115}{}{再见。}
{116}{}{那会花掉你$50。}
{117}{}{赶快帮我治疗吧。}
{118}{}{我不要待在这里。}
{119}{}{你觉得好多了。}
{120}{}{我要走了。}
{121}{}{不，不是开玩笑。我最好在坏死之前把那条腿切下来。}
{122}{}{你不能够把任何的部份切掉，懂吗？}
{123}{}{我受够了，我要走了。}
{124}{}{如果他发炎了，可不要怪我啊。}
{125}{}{我这边又不是慈济医院。在我能帮你治伤之钱，你得要先付我钱。}
{126}{}{我可以帮你做什么吗？}
{127}{}{说吧。}
{128}{}{第１３号避难所？}
{129}{}{知道我在那里可以找到第１３号避难所吗？}
{130}{}{我听闻有人说卫斯丁先生身体不太好，那是真的吗？我很担心会有什么事发生在他身上。他还欠我一些钱咧。}
{131}{}{有一个叫咸牛的人说你从他那边偷走了一张地图。怎么回事？}
{132}{}{我正在找工作，知道那边有工作吗？}
{133}{}{医生，你不会知道有一群人正在对抗那些邪恶的奴隶贩子一事吧？}
{134}{}{不用担心，如果他不再残害自己的身体，并且听从我的建议按时服药，他也许都会比我们活得要久呢。}
{135}{}{那真是好消息。我还要知道一些事情。}
{136}{}{谢谢，医生。}
{137}{}{那个老醉鬼！我唯一从他手上得到的就是一幅画而已－用来代替现金的。}
{138}{}{一幅画？我可以看看它吗？}
{139}{}{也不能算是一张地图．．让我问你一些其它的事吧。}
{140}{}{我得要走了。}
{141}{}{在咸牛被送到这边来之后，我就没有听过有人提到那个地方了。咸牛因中暑被送到这边来，发了三天烧，一直喊着他找到了第１３号避难所．．还有提到罗德妈妈．．}
{142}{}{罗德妈妈？}
{143}{}{那它到底在那里？}
{144}{}{避难所在那？}
{145}{}{不知道，咸牛一直都说他有一张地图，但是从来都没有人看过。}
{146}{}{咸牛？}
{147}{}{问更多。}
{148}{}{那对我来说已经算是很多资料了。}
{149}{}{咸牛是老铀矿的采矿者－更准确的说，一个醉鬼。现在他住在卫斯丁那个地方。}
{150}{}{再一个问题．．}
{151}{}{谢谢你的故事。}
#CMH changing per Fergus.. Now you have to pay 1000 or steal the painting off of him.
{152}{}{我原本是希望能够卖得一些钱。不过我愿意卖掉它，只要$}
{153}{}{下次吧，我还有另一个问题．．}
{154}{}{下次吧，我要走了。}
{155}{}{咸牛是老铀矿的采矿者。现在他住在卫斯丁那个地方。}
{156}{}{再一个问题．．}
{157}{}{谢谢你的故事。}
{158}{}{你最好去与坦蒂总统谈谈。我听说她正在找一些特别的人。}
{159}{}{再一个问题．．}
{160}{}{谢谢。}
{161}{}{我也许知道．．有一个团体是反对奴隶制的。}
{162}{}{再一个问题．．}
{163}{}{谢谢。}
{164}{}{嘿，把你的手放开，混混！}
{165}{}{小心！}
{166}{}{把它放回去！你一不小心就会伤到自己的。}
{167}{}{这些是为卫斯丁先生做的，不是你的。把它们放回去。}
{168}{}{离开那里。小心一点，我们可不要让卫斯丁先生吃错了药。}
{169}{}{小心！我才刚刚量好了卫斯丁先生的药量。}

{170}{}{我是朱伯利医生，有什么不对吗，小姐？}
{171}{}{有什么不对吗，小姐？}
{172}{}{你在那里啊，小姐。}
{173}{}{你不用担心，小姐。如果他不再残害自己的身体，并且听从我的建议按时服药，他也许都会比我们活得要久呢。}
{174}{}{当然，这里是$}
{175}{}{谢谢，我一直都想要从咸牛的身上拿钱回来，但是那混帐从来都没半毛。}
{176}{}{。}

#RP content - killap
{200}{}{Whoa there, }
{201}{}{son! }
{202}{}{missy! }
{203}{}{You can't be messing with that stuff! I just measured out Mr. Westin's dose and we wouldn't want him getting the wrong meds now. What in blazes do you think you're doing?}
{204}{}{I was just trying to get a look at those pills you have on the shelf there.}
{205}{}{Oh, don't mind me. I was just window shopping.}
{206}{}{Sorry. I've just always had this irresistible compulsion to dig around in other people's stuff that I've never been able to shake.}
{207}{}{Honestly? Not expecting you to be that observant. I guess I'm going to have to improvise.}

{210}{}{Were you, now? (Doc Jubilee regards you coolly.) I'd guess you were a mite young to be suffering from a bum ticker.}
{211}{}{And you'd be right. I'm asking for my friend Cassidy. Older fella. He's got a bad heart, and traveling the wastes is getting kind of rough on him.}
{212}{}{And I'd wish you were right. I got it from my pa. Or so they tell me.}
{213}{}{Oh, nothing like that. I'm just overbearingly inquisitive, I guess.}

{220}{}{Well, you can't. This is a private practice, not a drugstore. You might want to try Duppo's, a tetch north of here.}
{221}{}{Sounds like just what I'm looking for. Bye.}
{222}{}{I'll check 'em out. In the meantime, though, do you mind if I ask you a few things?}
{223}{}{No, I think I came to the right place. I can see you're doing good work here. I thought I might offer a donation.}

{230}{}{(The doctor blinks. He blinks again.) You should probably talk to somebody about that. Unfortunately, I ain't the right kind of doctor. All's you need to know about that shelf is that if you mix up or taint any of those prescriptions, some poor fella's liable to end up in a world of hurt, if they're still in this world at all. Best keep your hands to yourself.}
{231}{}{Will do, doc. But, uh, say-- I've got a buddy who could really use some of those heart pills you've got there. Think you'd be willing to sell me some?}

{240}{}{Awww, }
{241}{}{son, }
{242}{}{miss, }
{243}{}{I wish I could help you, but I'm not taking on any new patients right now. Council's got me on retainer. Can't sell you no pills, neither-- Councilman Westin's people are supposed to pick those ones up in }
{244}{}{ days, }
{245}{}{ day, }
{246}{}{and just ain't no way I'm going to have time to mix up another batch before then.}
{247}{}{I understand, doc. Maybe I'll find a decent pharmacist somewhere else. If it's not too much to ask, though, is there any advice you could give me on the subject? You don't find medicine like that too often.}
{248}{}{Those are the breaks, I guess. Anyway, I should be alright. I've picked up *tons* about cardamomagy from old comic books. Cut the hard chems back to twice a day, TOPS, make sure to get your exercise in short, strenuous bursts so your heart doesn't have time to act up, all kinds of good stuff.}

{250}{}{I feel for you, friend, but I'm afraid those pills are for Councilman Westin, and I ain't taking on any new patients right now so I wouldn't be able to write you up a script. Now please, don't go messing around on that shelf anymore. Those prescriptions get mixed up, someone could wind up in a pretty bad way.}

{260}{}{Let's be clear here, }
{261}{}{mister. }
{262}{}{missy. }
{263}{}{What exactly do you mean by "donation?"}
{264}{}{A charitable contribution, in furtherance of your service to the public, say... $150? You can count it out in the back room. Should only take a minute, right?}
{265}{}{Uh, actually, I think I'd better check with my accountant before I do anything rash. See you later, doc.}

{270}{}{No can do, I'm afraid. Those are for Councilman Westin. His people are due by to pick them up in }
{271}{}{ days, }
{272}{}{ day, }
{273}{}{and I'm not going to have the time to mix up another batch before then. I'm sure you can find a pharmacist with a lighter workload.}
{274}{}{I see. Well, thanks anyway.}

{280}{}{(Doc Jubilee gapes at you for a moment.) Aw, you're puttin' me on, right? You've gotta be puttin' me on. (glances at you again, shakes head, blows out cheeks) Hooo, boy. Either way, I wouldn't be no kind of doctor if I let you walk out of here without a few pointers, at least.}
{281}{}{Let's see... for starters, you should prob'ly stop doing... well, near to just about everything oughta cover it. No drinking, no smoking, no red meat, NO chems. Try to get a half-hour a day of MILD exercise. And take it easy. Life ain't a race, 'least not the kind where you want to be first to finish. Truth told, no one ever listens to this stuff, but at least I'll be able to rest easier tonight.}
{282}{}{More important, you need to find you a half-decent chemist and tell 'em you need set up with a regular supply of Triproxinil. Tri-prox-i-nil. Wasteland stock ain't gonna be as fancy as what I got on the shelf there, but chemically, it's all the same once you get down to brass tacks. 30 milligrams, twice a day.}
{283}{}{Now, you gotta be sure to drink plenty of water while you're on this stuff. And for criminy sakes, you stay *as far as you can* from those pecker pills like they got up in New Reno, understand? They don't play nice together. Fella takes one while he's on the other, his John Thomas ain't nearly the only part of him going stiff that day, if you follow.}
{284}{}{(To yourself) Hmm, that could work. Yeah. Maybe something in the way of a PDE-5 inhibitor compound...}
{285}{}{Oh-- And if you *do* go through one of them Reno hucksters, they might go tellin' you that this stuff'll proof your heart against just about any pusher's poison you'd care to try. I ain't gonna lie to you-- there's prob'ly some truth to that. Still don't make bein' a junkie any more glamorous. You're grown and out of britches, so I ain't gonna lecture, but there it is.}
{286}{}{Thanks a million, doc. You have no idea what a help you've been. Take care.}
{287}{}{Tri-prox-i-nil, no bo-ner-pill. Heh heh. I'll keep that in mind. See you around, doc.}

{290}{}{You think you're dealing with some shifty bartertown sawbones, }
{291}{}{son, }
{292}{}{girlie, }
{293}{}{is that it? Don't. I am a trained and accredited NCR medical professional, and that's worth a lot more than that pocketful o' chump change.}
{294}{}{My apologies. Obviously, a practitioner of your caliber rates a donation of no less than $250.}
{295}{}{(hang head) Look, I'm really sorry. I'm not proud of myself, and I would normally never have tried anything like that, but I'll be honest with you: I was desperate for those pills.}
{296}{}{Sorry for the trouble. I think I'd better just go before I dig myself a bigger hole.}

{300}{}{(Doc Jubilee begins to turn red.) I don't think you heard me the first time,}
{301}{}{ boy, }
{302}{}{ woman, }
{303}{}{so listen close: I am a doctor of the NCR. It's a solemn duty, and it came with a solemn oath. You ask me one more time to piss on that oath, the ONLY part of it that's going out the window is "first, do no harm." You got me?}
{304}{}{Alright, screw it. If you're as great as you seem to think you are, maybe you'll be able to sew yourself back together after this.}
{305}{}{Whoa, now. Didn't mean to step on any toes, doc. I'll just leave you be for awhile.}

{310}{}{Say, doc, I was wondering about those heart pills you've got up there on the shelf.}
{311}{}{Are you sure you can't reconsider selling me some of those pills?}

{320}{}{Sorry, Councilman Westin's people are due by to pick those up in }
{321}{}{ days, }
{322}{}{ day, }
{323}{}{and I'm just too busy to mix up another batch in time.}

{324}{}{(Mutters to himself) Where the hell did I put those pills for Mr. Westin. His heart aint gonna last long without 'em. (He looks up) Oh, sorry. What can I do for you today?}
{325}{}{I couldn't help overhearing what you said about heart pills. I was actually going to ask you about such medicine.}
{330}{}{(Mutters to himself) I can't believe Mr. Westin's dead. Couldn't have been my fault, I measured out those pills preciesly. (He looks up) Oh, sorry. What can I do for you today?}
