#{100}{}{You see trader Bill.}ipisgfx译
#{101}{}{You see an older looking merchant.}
{100}{}{你看见商人比尔。}
{101}{}{你看见一个像是店主的老头。}

#{200}{}{Hello there traveler. What can I get for you?}
{200}{}{你好，旅行者！我可以帮你什么忙吗？}
#{201}{}{Welcome back. Need something else?}
{201}{}{欢迎回来。需要点别的什么？}
#{202}{}{Let's barter.}
{202}{}{让我看看你有些什么吧。}
#{203}{}{I heard you are the man to talk to about caravans.}
{203}{}{我听说你是可以和我谈谈关于商队的事的人。}
#{204}{}{Nevermind. Bye}
{204}{}{我会留意的。回见~}

{210}{}{我注意到了阿比收集了很多旧的物品和装备。你有没有发现什么特别的东西呢？}
{211}{}{嗯，是的。阿比的居民喜欢收集东西，那能让我们记住过去的时光。（看了看马可世）真有意思，我可能有样东西会让你的朋友感兴趣的。}
{212}{}{嗯，是的。阿比的居民喜欢收集东西，那能让我们记住过去的时光。（看了看你们）抱歉，我觉得这里没有对你有用的东西。}
{213}{}{哦，好吧，让我们看看你店里有什么。}
{214}{}{好吧，让我问点其他的事情。}
{215}{}{嗯？}
{216}{}{一个商队前端时间来过这里。他们从非常遥远的南方过来，似乎惹上了一些非常卑劣的变种人（转向马可世）别介意。不管怎么说，他们抢到了一件变种人穿过的盔甲。当商队把盔甲给我的时候我也知道该怎么处理，只好先收下来。这玩意太重了，拖到其他城镇太累。最后花了一点钱就归我了。}
{217}{}{好的，我想这东西应该对马可世有用。多少钱？}
{218}{}{真有趣。可是，马可世已经很壮了。我不觉得他需要这件东西。让我问点其他的事情。}
{219}{}{这套坏东西融化了能做三四件金属护甲呢。一口价$3000。}
{220}{}{我有足够的钱。}
{221}{}{等会再说。让我问点其他的事情。}
{222}{}{搞定。这玩意要我们两个人才能搬动，让我来帮你朋友套上。}
{223}{}{[完成]}
{224}{}{嘿，穿起来正合适！}

#{300}{}{I might know a thing or two. What would you like to know?}
{300}{}{我略知一二，你想知道什么？}
#{301}{}{How often do you get resupplied?}
{301}{}{你多久补给一次？}
#{302}{}{Are the caravans hiring?}
{302}{}{商队雇佣人吗？}
#{303}{}{On second thought, I have to go.}
{303}{}{想想，我得走了。}
#{304}{}{I get a new shipment of supplies twice a month. Frankly, I wish they would come more often but we are only on a minor trade route so I guess this is the best we can get.}
{304}{}{坦白说，我每月进两次新货。 我希望更频繁一点，但是我们在一个次要的商业路线上，所以我想这是我们能做的最好的了}
#{305}{}{I'm not quite sure. Usually the ones that stop by here are pretty well equipped and not really interested in hanging around very long. If you are looking to get hooked up with one of them though, I would head over to Redding or even NCR. Caravans are always going through those places and good help is always wanted.}
{305}{}{我不太确定。通常有精良装备的人停留在这都不会有兴趣在这闲逛太久。如果你希望推荐自己的话，去瑞丁或是新加州共和国吧。商队总是通过那些地方，他们一直都需要帮手。}
#{306}{}{Interesting. I was curious about something else.}
{306}{}{很有趣。我对其他一些事也很好奇。}
#{307}{}{Thanks. Let's barter.}
{307}{}{谢谢。让我们交易吧。}
#{308}{}{Well, thanks for the information. See you around.}
{308}{}{很好，谢谢你的消息。回见!}

#{400}{}{Found everything you need?}
{400}{}{找到你需要的所有东西了吗？}
#{401}{}{Actually I'd like to take another look at your goods if I may.}
{401}{}{实际上如果可以的话我想看看你其他的货物.}
#{402}{}{Yes I did. See you around.}
{402}{}{是的找到了。回头见。}
