#You see a stout nun.
{100}{}{你看见了个矮胖的修女。}
#You see Elaine.
{101}{}{你看见了伊莱恩。}
#You still see her.
{102}{}{你仍旧看见她。}

#Greetings!
{200}{}{祝福你!}
#Hi, what is your name?
{201}{}{你好，你叫什么名字？}
#What can you tell me about Abbey?
{202}{}{关于这你能告诉我些什么？}
#Bye.
{203}{}{再见。}

#If you want to know more about our order, talk to our leader. He is on the third floor.
{300}{}{如果你想知道更多关于我们的工作，和我们的领导者谈谈吧。他在三楼。}
#I see. A few more questions...
{301}{}{明白了。再问几个问题...}

#Such as?
{400}{}{例如？}
#What is your name?
{401}{}{你叫什么名字？}
#Nothing really, bye.
{402}{}{不要在意，回见。}
#What can you tell me about Abbey?
{403}{}{关于这你能告诉我些什么？}

#Call me Elaine.
{500}{}{叫我伊莱恩。}
#I see. A few more questions...
{501}{}{明白了。再问几个问题...}

#Hey! Before you go, could you give this machine part to Max in the copying room?
{600}{}{嗨！在你走之前能帮忙把这个机器零件拿给在复印室的麦克斯吗？}
#Sure.
{601}{}{当然。}
#Sorry, I don?t have time for this. Bye.
{602}{}{报歉，我没时间做这个。再见。}
#Thanks! Here?s the part.
{603}{}{谢谢！这是零件。}
#Got it. I'll give it to Max right away.
{604}{}{拿来吧。我马上就拿去给麦克斯。}