#ipisgfx译
{100}{}{你看见修士约翰。}
{101}{}{你看见一个阿比的老修士。}
{102}{}{你看见一个老修道士。他看上去有70岁了。}

#{300}{}{Hi there, youngster.}
{300}{}{嗨，年青人。}
{301}{}{你是谁？}
#{302}{}{Have you heard anything about a GECK or Vault 13?}
{302}{}{你有没有听过伊甸园制造器或是13号避难所？}
{303}{}{再见。}

#{400}{}{My name is John, I'm one of the oldest monks here.}
{400}{}{我叫约翰，我是这最老的修士之一。}
#{401}{}{So, what's your job?}
{401}{}{那么，你的工作是？}
{402}{}{我明白了，再见。}
#{403}{}{Well, I used to work on a farm, but it was bad for my heart.}
{403}{}{好的，我通常在农场工作，不过这对我的心脏很不好。}
#{404}{}{You have heart problems?}
{404}{}{你有心脏问题？}
#{405}{}{That's too bad, bye!}
{405}{}{那真是不幸，再见！}
#{406}{}{Yeah, I have a bad heart. If I still had my heart pills, it would ease my life a lot more. It is very difficult to find medicine for that problem in today's world you know.}
{406}{}{是的，我有一颗不健康的心脏。如果我一直都有心脏病的药的话，可能我的生活会安逸的多。不过现今的世界很难找到解决这个问题的药。}
#{407}{}{I might have a solution for your heart problems...}
{407}{}{我可能有解决你心脏问题的方法...}
#{408}{}{Sorry to hear that, Bye.}
{408}{}{很遗憾听到那个。再见。}

{410}{}{再见。}
#{411}{}{You do? Are you saying that you actually HAVE heart pills?}
{411}{}{你有？你是说你有心脏病的药？}
#{412}{}{Yes, I do. It would be a pleasure to give them to you.}
{412}{}{是的，我有。我很乐意把它给你。}
#{413}{}{Yeah, I have heart pills. You can have them for $400.}
{413}{}{是的，我有心脏病的药，你给$400的话它就是你的。}
#{414}{}{I was only joking. I don't have any heart pills.}
{414}{}{开个玩笑而已，我没有任何心脏病的药。}
#{415}{}{(He takes the pills from you) Thank you my friend! Take this item as a gesture of gratitude.}
{415}{}{(你把药给了他) 谢谢我的朋友！ 拿着这个，代表一点心意。}
#{416}{}{Happy to help, and thanks for the item. Bye!}
{416}{}{很高兴能帮你，谢谢。再见。}
#{417}{}{(He becomes quite angry, but then calms down) Ok, fine, here's your money. Now give me the pills!}
{417}{}{(他变得很生气，不过一会他平静下来) 好吧，钱在这，给我药！}
#{418}{}{I have decided to keep the pills myself. Thanks for the money!}
{418}{}{我确定我自己要保留这些药。多谢这些钱！}
#{419}{}{Nice doing business with you, Bye.}
{419}{}{很荣幸和你交易。再见。}
{420}{}{噢，对不起我没听过。和我们的领导者谈谈，他可能知道一些。}
#{421}{}{I'll do that thanks. Now I have some other questions.}
{421}{}{谢谢我会的。现在我有一些别的问题。}
#{422}{}{If I weren't so sick, I would beat the shit out of you. NOW GET OUT OF HERE!}
{422}{}{如果我没有生病，我一定会把你踢出去。现在滚出去！·#￥%}
#{423}{}{Fine, I'll go.}
{423}{}{很好，我就走。}

#{500}{}{Thank you again for those heart pills, my friend. Good luck on your travels.}
{500}{}{再次感谢你的药，我的朋友。祝你一路顺见。}

#{600}{}{Just go away, please.}
{600}{}{走开！}

#{700}{}{You showed John just how cruel the world is.}
{700}{}{你向约翰展现了这个世界多么残酷。}