{100}{}{你看见麦克斯。}
{101}{}{你看见一个阿比的修士。}
{102}{}{他看上去有点不安。}

{200}{}{你好，我能为你做什么？}
{201}{}{我从伊莱恩那带来了一点东西……}
{202}{}{这是什么地方?}
{203}{}{再见。}

{300}{}{让我猜猜。是我需要的某个维修部件，对吗？}
{301}{}{是的，这就是。}
{302}{}{不，我只是测试一下你。}

{303}{}{(他拿过你手里的零件) 很好！现在我们能修理这个复印机了。谢谢你的帮忙，给你这个野外生存手册。}
{304}{}{谢谢。}

{305}{}{听着我没时间和你开玩笑。你到底有没有那个零件？}
{306}{}{是的，我有。}
{307}{}{无论如何我得走了。}

{400}{}{这是我们的复印工厂。我们在这复印书籍。}
{401}{}{好的，谢谢你的信息。}

{500}{}{你获得100点经验值因为你帮忙送零件。}

#dumb dialgoue
{600}{}{I be BIG helper today. I have macheen part from pretty name woman.}

{610}{}{That must be the service part that I requested from Elaine. Thanks for bringing this to me. Here, take this
 survival manual for your trouble...uh if you can read it that is.}
{611}{}{I read ten words. I likie pitcher books more. They fun to look. Tankee!}
