{100}{}{你看见一个年轻人，看上去很强壮。}
{101}{}{你看见彼得斯先生。}

{200}{}{你好，朋友。以前没见过你。你一次来阿比？}
{201}{}{很高兴再次见到你。我能为你做点什么？}
{202}{}{是，你能介绍一下这个地方吗？}
{203}{}{我正在找神圣的伊甸园创造器。关于这个你知道什么吗？}
{204}{}{塞缪尔修士说你可能知道一些关于谁在墓地捣乱的事。他说你听到一些噪声在你的田里。}
{205}{}{别介意，我得走了。}

{300}{}{好的，阿比是一个很安宁的地方，不象其他地方你能找到自我。我和我的妻子和一个商队到这只有几年。 我们很喜欢这最终决定留下。 从那后我们开始种一些农作物卖钱。}
{301}{}{你自一个商队？你经常到这？}
{302}{}{不是的。。阿比是一个二流的商业线路使得商队不会经常停在这。如果你想获悉理多关于商队的事。问问那边商店的比尔。他可能知道更多的事。你可以在南边找到他。}
{303}{}{那听上去不错。不过我真的要走了。}
{304}{}{很有趣，我想知道点别的事。}
{305}{}{别介意。我得走了。}

{400}{}{你还要知道什么？}
{401}{}{关于阿比你能告诉我什么？}
{402}{}{你知道关于伊甸园创造器的事吗？}

{500}{}{伊甸园创造器？嗯....我记得在大教堂的档案室读过一点有关的资料。我不记得上面怎么说的了。如果我是你我就去查查那些文件。也许你能找到一些有用的信息。}
{501}{}{谢谢，我就去看看。我还有一些问题。}
{502}{}{谢谢你的消息。我现在就去查查。}

{600}{}{塞缪尔修士叫你来的？什么他现在酒醒了？}
{601}{}{所以你听说了什么...}
{602}{}{(约翰坐到了椅子上喝了几口酒) 好吧，一切始于几天前，我和我的妻子在家，当我们听到一些沙沙声后我就准备到田间查看一下。我拿着提灯匆忙出去看是什么发出这种声音。当我到了田里时声音就没了。}
{603}{}{继续。}
{604}{}{听着。我真必需走了。}
{605}{}{然后第二晚我们就没听见任何声音了。又一晚我们又听见那个沙沙声。这次我小心的到窗口看外面。这次我看见一个暗光。好像是一个老旧的提灯发出的，在农田间移动。几分钟后这个暗光移向了墓地。}
{606}{}{第二天我去田里查看，发现很多农作物被吃了，周围还有很多新的脚印。我不介意给穷人吃。不过我对小偷没什么好感。之后我的农作物又开始少了。我问塞缪尔修士墓地发生了什么。他说有人盗墓，而且不是一次了。如果查出是哪些人做的，请你告诉他们停住吧。我很乐意帮肋这些人如果我能帮到他们的话。}
{6061}{}{After that, I asked Brother Samuel if anything had happened in the graveyard. That's when he told me someonehad begun digging up some of the graves. Apparently, whoever's doing this isn't strong enough to dig in one night.I'd guess it's an old beggar hoping to dig up some treasure. If you ever find out who's doing this, please tell 'em tostop by. There's no need for thievery here in the Abbey and I'd be happy to help this person in any way I can.}
{607}{}{我会试着找出这些人的。也许我夜晚在那周围等着就能找到一些东西了。好的，谢谢这些消息。保重。}
{608}{}{我会看看我能做点什么。走之前我还有一些问题。}
{609}{}{这故事真是有一点长。再见。}
{610}{}{Let me get this straight. You'd be happy to help someone that lurks around your house at night, steals yourcrops, and tries to rob your dead? I've met a lot of loonies in my day, but you just might take the cake. It's a marvelyou've survived this long.}
{611}{}{[He narrows his eyes, but manages to hold his composure.] That's how we do things here at the Abbey. If kindnessis so offensive to you, then I suggest you get the hell outta my house. I'm not gonna sit here and let some wanderingtribal insult me in front of my wife.}
{612}{}{Alright, alright, I'm leaving.}
{613}{}{OK tough guy, now this "wandering tribal" is going to kill you in front of your wife. Then maybe I'll kill her too.Hell, maybe I'll kill everyone in this pathetic fucking place. You thought you could all hide from the horror of the wasteland?Well guess what, my naive friend? Horror has found you, and its name is }

{700}{}{Get the hell outta here.}

#added in RP 2.1
{710}{}{Good to see you again. Tom's been a big help around here. Thanks again for sorting all that out. Now, what can I do for you?}
