{100}{}{你看见一个墓地管理员。}
{101}{}{你看见塞缪尔修士，墓地管理员。}
{102}{}{他看上去喝高了，且昏昏欲睡的。}

{200}{}{*摇摇晃晃* 什么，（唲~）我的名字是塞缪尔，什么（唲~）风把你带到这来了？}
{201}{}{*摇摇晃晃*嗨又见面了。}
{202}{}{我是到处走走。你在管理这个墓地。}
{203}{}{你认识塔里神父吗？}
{204}{}{塔里神父，你说？[他开始敲打他的头试着想起什么]对...我 *摇摇晃晃*记得塔里。 那伙计做了什么？从他被这踢出去很多年我都没见过他了。小子他是一个古怪的人。他和我一类的。*摇摇晃晃*多么好的一个团队。}
{205}{}{他现在住在新里诺。你知道的。你俩真的很象。}
{206}{}{新里诺, 哼？ (他靠着他的铲子，拿出一个小瓶大口喝了几口) 我记他说他会*摇摇晃晃*朝那去的。我很高兴他在那很安全。我一直*摇摇晃晃*都很喜欢那伙计。如果你再见到他告诉他塞缪尔仍然活的好着呢。}
{207}{}{我会的。我还有一些别的问题。}
{208}{}{我会的。保重塞缪尔}
{209}{}{别介意。对不起打扰你。}
{210}{}{实际上我只是来替他问声好的。我也会帮你向他问好的。我还有一些别的问题。}
{211}{}{实际上我只是来替他问声好的。我也会帮你向他问好的。保重塞缪尔。}

{300}{}{你他知道什么？*摇摇晃晃*}

{301}{}{你是管理员？}
{302}{}{关于阿比你能告诉我什么？}
{303}{}{我能帮你什么事吗？}

#are you the keeper here?
{400}{}{Yes, *hickup* I tend to these 'ere graves. Nobody else wants to *hickup* do it, so Ol' Sammy got th' job. It'snot as bad as one might think. It's got its?perks, if you know what I mean. [He grins sloppily and wiggles his bushyeyebrows at you.]}
#new in RP 1.3
{401}{}{No. I don't know what you mean, and I never want to. Bye.}
{402}{}{No. I don't know what you mean. But I think I'd rather ask you something else. }
{403}{}{No. I don't know what you mean, but I'm morbidly curious...}
{404}{}{Hell yeah I do. Nothing turns me on like a rotten cadaver.}
{410}{}{Why, I get to be outdoors, and no one's 'round to tell Ol' Sammy when he's had enough. I *know* when I've'ad enough... when 'ere's none left! [He cackles, which quickly turns into a hideous cough. After coughing up a lungor two, he smiles at you.]}
{411}{}{Oh, of *course* that's what you meant. [Sigh of relief.] Let me ask you something else, though.}

{420}{}{[His eyes go wide with shock and he seems to instantly sober.] That's not what I meant, you...you MONSTER! FIEND!Get away from me! }
{421}{}{Whatever, you drunk old fuck. You don't know what you're missing.}

{430}{}{Foul demon! Be gone!}

#Tell me about abbey
{500}{}{The Abbey, well, this place *hickup* has been my 'ome fer most of my life. Everone 'ere *hickup* is nice, andanyone's welcome, long as they *hickup* don't cause trouble. I, myself, don't spend too much time in th'mona-*hickup*-monastery, but I know our 'puters have all kinds of info that's been collected over th' years. Maybesome of it *hickup* might be of some use to you.}
{501}{}{You don't spend much time in the church? You are a monk, aren't you?}
{502}{}{[He grins, revealing a gap filled set of rotten teeth.] Well, *hickup* let's just say that th' other monks don'ttake *hickup* too kindly to my, uh, drinking habits.}
{503}{}{Makes sense I guess. I got some more questions.}
{504}{}{I guess so. See you around Sammy.}
{505}{}{I see. Look I must be going.}

#Need any help
{600}{}{Hmm... *hickup* lemme...lemme tink a minute. Yeah, I might got somethin, if yer up to it.}
{601}{}{Uh, nevermind Sam. I must be going now.}
{602}{}{Sure Sam, what do you need?}
{603}{}{Well, th' past coupla days I've *hickup* noticed some of these graves are bein dug up. Now, whoever's doin thisdon't appear to be gettin that far, but it's a *hickup* a pain fer me to fill 'em back up.}
{604}{}{Hmm, well did you try and figure out who has been doing this?}
{605}{}{Sure *hickup* I tried. One night I stayed around till midnight or so and no one showed up. I must've fallen asleepsoon afterwards. Too much drinking I s'pose. [He grins, pulls out his flask and takes a hefty swig.] So, what do you*hickup* say? You wanna help out?}
{606}{}{Alright, I'll see what I can do. Do you know anything else that might help me?}
{607}{}{Well, now that you mention it, I do *hickup* 'member Mr. Peterson sayin something about hearing some noises cominfrom his field. He might know something about this. He and that pretty little wife a his live right over there.[He points to the building south of the graveyard.]}
{608}{}{I'll see what I can do.}
{609}{}{I think I'll pass. I must be going.}

{700}{}{I took care of the grave digging situation. You shouldn't have any more problems out here.}
{701}{}{Well, that's *hickup* good news. Glad I won't be falling into any more open *hickup* graves. Thanks fer th' help.}
{702}{}{Glad to help. I got some questions though.}
{703}{}{Well, take care then.}
{704}{}{I don't think open graves are the real reason you're falling down Samuel, but you take it easy now.}

{1000}{}{*Whistle*}
{1001}{}{*Cough* *Cough*}
{1002}{}{*Clears throat*}
{1003}{}{*Cough*}
{1004}{}{*Sigh*}
{1005}{}{*Hickup*}

{2000}{}{It's been a *hickup* long day. Come back in th' morning.}