#ipisgfx译
#{100}{}{You see a hunched over old man.}
{100}{}{你看见一个弯腰驼背老头。}
#{101}{}{He seems to be quite old and his clothing is tattered and muddy. He is carrying a shovel.}
{101}{}{他看上去相当老，衣服破烂且满身泥泞。他还带着一个铲子。}
{102}{}{你看见汤姆。}

#{200}{}{(The old man appears startled when you approach him) Look, I really must be going...}
{200}{}{(当他看见你时表现出很惊讶的表情) 听着，我真是得走了...}
#{201}{}{Now you hold on a minute. (You grab the man by the arm as he begins to walk away) Who are you and what are you doing here at this hour?}
{201}{}{你等一会。(他刚要走时你抓住他们手臂) 你是谁？你这个时候还在这干什么？}
#{202}{}{What? Why, uh...the name's Tom and can't an old man enjoy a nightly stroll anymore without getting asked a bunch of questions?}
{202}{}{什么？什么呢，嗯...我的名字是汤姆，难到一个老人不能独自享受夜间漫步，而非要回答一堆问题吗？}
#{203}{}{Not where I come from. So why the need for the shovel?}
{203}{}{那为什么散步需要带着铲子吗？}
#{204}{}{Alright fine, but why are you carrying a shovel?}
{204}{}{那好吧，那你为什么带铲子呢？}
#{205}{}{Whatever, I am out of here.}
{205}{}{什么都行，我要走了。}
{206}{}{别介意，对不起打扰你了。}
#{207}{}{You mean this 'ol thing? (He points to the very rusty shovel he is holding) Well, you never know when you might find something and you have to dig it up. Always be prepared I say.}
{207}{}{你说的是这个东西？ (他指着手里那把生锈的铲子) 噢，是这样的，你永远都不知道当你找到某些东西正好需要挖出来时又没有铲子怎么办，所以通常我都会事先准备好。}
#{208}{}{Find something, eh? You mean like something in a grave?}
{208}{}{找到某些东西，对吗？你是说某些墓地吗？}
#{209}{}{That's a good motto indeed. Well, take care.}
{209}{}{那个是不错的座右铭。那么，保重。}
#{210}{}{(Tom's eyes widen) I'm not quite sure what you, uh, mean.}
{210}{}{(汤姆的眼睛张的很大) 我不太明白你....你的意思。}
#{211}{}{Tom, you're in a graveyard, you've got mud all over you, and its past midnight. Why, even Torr could draw a conclusion from this. It's time to start giving me some answers Tom. Why are you digging up these graves?}
{211}{}{汤姆你在一个墓地里,满身泥泞,又是午夜,就连托尔都能知道为什么。是时候给我一个满意的回答了.你为什么要盗墓？}
#{212}{}{(He puts the shovel down and sighs) Alright, I'll tell you. My body aint anymore what it used to be. I've got no job and no real means to get food. I know grave diggin aint something that folks smile upon, but it's been a way for me to bring in some money. I don't mean no harm.}
{212}{}{(他放下铲子叹了口气) 好吧，我会告诉你的。我身体的情况使得我找不到工作也就是说无法找到吃的。我知道盗墓是可耻的，但是那是我找钱的唯一的方法。}
#{213}{}{I don't think that digging graves is a good thing for a man in your condition. Tell you what. You just mosey on out of here and we'll forget that this conversation ever happened. I never want to see your face again though, Okay?}
{213}{}{我认为就算你的身体不好但盗墓就不是件好事。你走吧，忘了今天的谈话就当什么都没发生。我不想再见到你，明白吗？}
#{214}{}{(The old man looks like he is about to say something then stops) Alright, you win. You've seen the last of poor old Tom. (He picks up his shovel and walks away)}
{214}{}{(老头看上去想说什么但又止住了) 好的，你赢了。你将最后一次看见可怜的老汤姆。(他拿起铲子慢慢走了)}
#{215}{}{On second thought, maybe it would be better for the world if I kill you.}
{215}{}{经过一翻思索。我杀了你对这世界会更好。}
{216}{}{再见汤姆。}
#{217}{}{I heard you've also been stealing crops from the farmer here.}
{217}{}{我听说你还偷了这附近的农作物。}
#{218}{}{(The old man fidgets uncomfortably) I couldn't help it! I was just so hungry and the food looked so good.Please, I don't mean any trouble. Look, I'll just go away and you won't see me here any more. I promise!}
{218}{}{(老头慌张起来)我没办法！我只是很饿而且这些食物看上去很好吃。求求你。我不想找麻烦，这样吧我离开这你再也不会在这看见我了。我发誓！}
#{219}{}{Alright, get going then. Before I change my mind.}
{219}{}{好吧，快滚吧。在我改变主意之前。}
#{220}{}{Wait, no need for any of that. Look, the Petersons' own the farm here and they are extremely nice people. Mr.Peterson even offered to talk with whoever was taking his crops and come to a reasonable agreement. Go talk with him.I am sure he can help you out somehow.}
{220}{}{等等，这个农场的彼得斯家是非常好的人。去和他谈谈。我相信他一定会帮你的。}
#{221}{}{(The old man's eyes light up.) That doesn't sound like a bad idea at all. Hey, thanks. Maybe this world aint as cruel as I thought it was.}
{221}{}{(老头忽然像是看到了一丝希望) 那听起来也不是什么坏主意。嗨，谢谢。也许这个世界不像我想的那么残酷。}
#{222}{}{You take care then Tom. I'll check with you later and see how things are going.}
{222}{}{你保重，汤姆。我会再去看你的。}
#{223}{}{I sure hope that Peterson fella is as friendly as you say he is.}
{223}{}{我希望那彼得斯小伙像你说的那样友善。}

#{300}{}{You see Tom. He is wearing new workers clothing and he is whistling.}
{300}{}{你看见汤姆。他穿上了新的工作服，且正高兴的吹着口哨呢。}
#{301}{}{Hey, there. Wow, you were right. That Mr. Peterson is one kindly fella. He forgave me for what I did and even offered me a job helping out in the field here. I have to first pay off for what I had taken, but after that I'll be able to do whatever I want with the money I'm getting paid. Thanks again for your trouble.}
{301}{}{嗨，你是对的。彼得斯先生是个友善的小伙。他不计较我以前做的事甚至提出给我一个工作让我做。我用第一份工钱为我以前做的事还了债，但那之后我就能用这些钱做我想做的事。再次感谢谢你的费心。}
#{302}{}{You're welcome Tom. You take care of yourself now.}
{302}{}{不用客气，汤姆。现在你保重好你的身体。}
#{303}{}{Alright I wi- Oh, wait a second. I want to give you something for helping an old fella like me out. I found this on some lad I dug up a couple weeks ago. I have no use for it and hopefully you might.}
{303}{}{好的，我会的。喔，稍等一会。我想要给你一点东西为你帮助我这样一个老伙计走出困境。我在一个家伙身上找到这个。这对我没什么用希望对你有用。}
#{304}{}{Thanks Tom. I am sure this will come in handy. See you around.}
{304}{}{谢谢，汤姆。我确定这会派上用处的。回见。}
#{305}{}{(The old man nods and goes back to what he was doing.)}
{305}{}{(老头点点头又回去做事了)}
{306}{}{[结束]}

{307}{}{又见面了。谢谢你所做的一切！}
{308}{}{*吹口哨*}

#{400}{}{You youngins never learn. You aint the boss of me. I think I'll just kill you instead.}
{400}{}{作为补偿我想我只需杀了你。}

#{450}{}{Listen, I've dug up my share of graves too. I'm a bit of a kleptomaniac. What's your reason?}
{450}{}{听着，我也参于盗墓。我有盗墓的嗜好。你有什么理由？}
#{451}{}{I'm not unfamiliar to grave digging, Tom. Every man has his own enjoyment. Now you be on your way.}
{451}{}{我觉得盗墓没什么新奇的，汤姆。每个人都有他的嗜好。现在你可以走了。}

#{1000}{}{You figure out who is digging up the graves and set Tom towards a new life.}
{1000}{}{你找到了是谁盗的墓且你让汤姆走向的新的生活。}
{1001}{}{你找到了是谁盗的墓。}
#{1002}{}{I'm going. No need to rush an old man.}
{1002}{}{我就走，不用催促一个老头。}
#{1003}{}{You see Tom. He's got a smile on his face and he's wearing new worker's clothing.}
{1003}{}{你看见汤姆。他脸上充满笑容，身上穿上了新的工作服。}
#{1004}{}{He seems to be in much better condition and he smiles when you approach.}
{1004}{}{他看上去情况不错，当你出现时他对你微笑。}