{100}{}{你看见一个小型电脑终端。}
{101}{}{你看见阿比的一个小型电脑终端。}
{102}{}{你看见一个小型电脑终端，看起来性能不错。}
{103}{}{你访问这台电脑开始搜索所有可用的文件。你找到了一些含有“伊甸园创造器”和“避难所”关键字的文件。}
{104}{}{阅读有关伊甸园创造器的信息.}
{105}{}{阅读有关避难所的信息.}
{106}{}{错误！权限卡没有找到。请插入权限卡插入加密卡槽。}
{107}{}{(插入权限卡) 哔哔！权限卡确认出。加载Ｗinblows 2075....完成}
{108}{}{输入命令}
{109}{}{搜索任何关于关于伊甸园创造器和13号避难所的文件}
{110}{}{访问其他文件.}
{111}{}{玩“剪刀石头布”}
{112}{}{返回。}
{113}{}{登出。}
{114}{}{[继续]}
{115}{}{你找到一些含有“伊甸园创造器”和“避难所”关键字的文件。}
{116}{}{浏览有关“伊甸园创造器”的文件。}
{117}{}{浏览有关“避难所”的文件。}
{118}{}{搜索程序对你来说有些困难……}
{119}{}{你发现了一个伊甸园创造器的广告，顿时你睁大了眼睛，心跳加速。广告描绘了一个卡通人物笑嘻嘻的穿着避难所制服拿着大箱子，箱子上写着“生存工具”。好像那微笑混蛋是在嘲讽你。}
{120}{}{你浏览了这些文件，文件大都是讲述政府对美好的避难所生活的宣传。你知道了在21世纪中叶，美国政府委托避难所科技在整个美国建造了122个避难所。这每一座避难所被设计容纳1000名美利坚公民，保护他们免受核战争浩劫。在地下掩体的安全环境内，避难所居民可以舒适的生活直到收到信号通知地表世界再次适宜居住。}
{121}{}{当你在系统中搜索时，你发现成百上千的数字化书籍和杂志被归类存放在硬盘上。你甚至不知道如何寻找可用的东西。}
{122}{}{当你在系统中搜索时，你发现成百上千的数字化书籍和杂志被归类存放在硬盘上。由于你熟知信息通常是如何存储的，也许通过搜索主题会找到一些有用的东西。}
{123}{}{[更多]}
{124}{}{根据广告上的描述，该工具包含一个“基础复制单元”，可以“复制用于重建世界的食物和必需物品”。一个“带有数据库的全息卡带读取器”，其“囊括了美国国会图书馆的全部栏目，整套百科全书和其他挽救生命的信息，共计四百六十张全息卡带！”。甚至还包含一个“微型笔装手电筒”！显然，这个奇迹装置正是你拯救你垂死的村庄需要的。}
{125}{}{阅读更多内容。}
{126}{}{你继续浏览文件，你能找到提到第13号避难所的内容，仅仅是它坐落于加利福尼亚州，事实上并没有什么帮助。}

{130}{}{添加信息.}
{131}{}{[你没有什么可添加的] 返回.}
{132}{}{输入植物学信息.}
{133}{}{输入[废话]信息.}
{140}{}{阅读帮助/关于文件.}
{141}{}{Congratulations on successfully installing Winblows 2075! This version is the most advanced Winblows version to date. With the probability of only one crash per million function calls confirmed, our technicians are confident that Winblows is perfectfor any corporate environment. The newest addition to Winblows 2075 is an improved and tweaked code base which now only wastes 15% of your CPU cycles on background administration as opposed to previous versions which would waste up to 25% of your CPU cycles. Of course, much user consideration has been put into this latest release. As with previous versions of Winblows, the common commands of Search, Add, Move, Delete, and Format are available to the user.}
{142}{}{格式化文件系统，包括主机和网络机上的所有备份数据库。}
{143}{}{返回。}
{144}{}{格式化中……备份数据……成功……格式化当前文件系统……等待中……警告：重大的错误 待机中……}
{145}{}{等等。}
{146}{}{……系统错误：操作成功完成……(一个刺耳的声音从计算机内部和附近其他计算机发出)}
{147}{}{[离开]}
{148}{}{错误：找不到键盘。按任意键重起。}

{150}{}{上传EPA植物学信息... 上传完成...美好的一天。}

{200}{}{“剪刀石头布”V.0.3，选择选项}
{201}{}{出石头。}
{202}{}{出布。}
{203}{}{出剪刀。}
{204}{}{返回主菜单。}
{205}{}{电脑先择……计算……电脑胜！}
{206}{}{电脑先择……计算……玩家胜！}
{207}{}{电脑先择……计算……平局！}

{300}{}{(电脑屏幕上呈现各种各样不同颜色的图案)}
{301}{}{噢！漂亮的颜色。}
{302}{}{灰头灰脑的离开。}

{400}{}{阅读更多。}
{401}{}{返回菜单。}

{402}{}{搜索主题}
{403}{}{请输入一个搜索主题。}
{404}{}{科学。}
{405}{}{维修。}
{406}{}{医学。}
{407}{}{武器使用。}
{408}{}{演讲口才。}

{410}{}{经过几小时的阅读，你掌握了许多关于科学的知识。}
{411}{}{经过几小时的阅读，你掌握了许多关于机械修理的知识。}
{412}{}{经过几小时的阅读，你掌握了许多关于医学的知识。}
{413}{}{经过几小时的阅读，你掌握了许多关于用武器保卫自己的知识。}
{414}{}{经过几小时的阅读，你掌握了许多关于说服的知识。}

{420}{}{经过几小时的阅读，你没能够学到新的关于科学的知识。}
{421}{}{经过几小时的阅读，你没能够学到新的关于机械修理的知识。}
{422}{}{经过几小时的阅读，你没能够学到新的关于医学的知识。}
{423}{}{经过几小时的阅读，你没能够学到新的关于用武器保卫自己的知识。}
{424}{}{经过几小时的阅读，你没能够学到新的关于说服的知识。}

{430}{}{返回。}

{500}{}{As you read over more articles, you learn the GECK was developed by Future-Tec, a division of Vault-Tec, and thatit was standard issue in all Vault-Tec vaults. It was meant to be used upon exiting a Vault, to help re-establish life inthe harsh environments of a world devastated by nuclear war.}
{501}{}{Upon further reading, you discover the GECK isn't quite the miracle device the ad made it out to be. The "Base Replicator"is actually nothing more than a fertilizer system containing food seeds, soil supplements, and chemicals specifically engineered toturn arid wasteland into fertile soil. Its claim that it can "build basic items" actually alludes to new codes it provides for theVault's machines, allowing them to create new items from the dispensers. The GECK also contains schematics for basic force fieldsand the construction of "sand-crete" walls and buildings.}
{502}{}{[MORE]}
{503}{}{It seems the GECK itself is meant to be disassembled over the course of its use. You read an example of how its cold fusionpower source is intended be used for main city power production. The GECK even contains instructions on disassembling sections of theVault to create homes and defensive structures for the new community. As you finish reading over the files, you decide that even thoughit's not the magical device the Elder seems to think it is, finding a GECK is still your best option if you hope to save your tribe.}

{1000}{}{You upload the EPA Botany Holodisk.}

{2000}{}{You format the Abbey's book databases.}
