#ipisgfx译
{100}{}{你看见阿比的修士首领。}
{101}{}{这个修士看起来像是某种领导者。}

{200}{}{欢迎你旅行者。}
#{201}{}{Peace to you.}
{201}{}{安静。}
#{202}{}{We are the guardians of knowledge.}
{202}{}{我们是知识的守护者。}
#{203}{}{I'm sorry, but knowledge of our books is of no use to you.}
{203}{}{十分报歉，但是你不能使用。}

#{300}{}{Welcome to The Abbey, traveler. How can I help you?}
{300}{}{欢迎来到阿比，旅行者。我能帮你吗？}
#{301}{}{What can you tell me about your order?}
{301}{}{能和我说说你们现在的情况吗？}
#{302}{}{Have you heard anything about a GECK?.}
{302}{}{你听说过伊甸园创造器吗？}
#{303}{}{Do you know where I could find Vault 13?}
{303}{}{你知道哪能找到13号避难所吗？}
{304}{}{再见。}

{400}{}{你想知道什么？}
{401}{}{好的。我还知道些别的。}
#{402}{}{Hmm....I'm remembering that someone in our order had this knowledge. Yes, I remember now, brother Thomas had studied it recently.}
{402}{}{嗯....好像有点印象。是的，我想起来了。托马斯修士最近研究过。}
#{403}{}{You have? Great! Can I see it?}
{403}{}{你有？太好了！我能见他吗？}
#{404}{}{I don't know anything about that.}
{404}{}{对些我什么都不知道。}
#{405}{}{Well, thanks anyway.}
{405}{}{好吧，总之谢谢你。}
#{406}{}{Well I am afraid Brother Thomas was the only one who personally knew of this information. Our computers probably have it backed up though.}
{406}{}{我想恐怕托马斯修士是知道这个信息最后的人。虽然我们的电脑也许会有备份。}
#{407}{}{He's dead? What happened.}
{407}{}{他死了吗？出什么事？}
#{408}{}{Some kind of powerful beast that lives under our church caves killed him, or at least I think so. He went down there a few days ago and we are too afraid to go down there.}
{408}{}{生活在我们的地下洞穴里的某种强大的怪物杀了他，最少我想是这样的。他下去有几天了，我们很害怕下去那找他。 }
#{409}{}{Hmmm. Maybe I should take a look what's down there. *I AM* the chosen one after all...}
{409}{}{嗯，也许我得下去看看是什么在下面。我可是获选者！}
#{410}{}{I'm adventurous. I can take a look.}
{410}{}{我喜欢冒险，我能下去看看。}
{1411}{}{非~非常有趣。我得走了。}

#{411}{}{You really would do that? Brother Thomas was also carrying an important book on him. It was passed down from our founders and I would love to have it back. I will also grant you access to our computers so you can look for what you need.}
{411}{}{你确定要那样做？托马斯修士身上带了一本很重要的书，那是我们的创始人传下来的书，我很希望能拿回来。如果你拿到我就允许你使用我们的电脑查阅你需要的资料。}
#{412}{}{It's a deal. I'll be back soon.}
{412}{}{成交。我马上就回来。}
#{413}{}{Maybe, let me think about this some more...}
{413}{}{也话让我再考虑一下...}
#{414}{}{Great, let me know when you have the book.}
{414}{}{太好了，你找到书就告诉我。}
{415}{}{好的，再见。}

#{416}{}{Hello again, my friend.}
{416}{}{又见面了，我的朋友。}
#{417}{}{I've killed the beast and recovered the book!}
{417}{}{我杀了那个怪物，书也拿到了！}
{4177}{}{我杀了那个怪物！}
{418}{}{太好了！给我！}
#{4188}{}{Excellent! And how about the book; were you able to recover it?}
{4188}{}{太好了！那本书怎么样了；你找到了吗？}
#{419}{}{Here you go.}
{419}{}{拿去。}
#{420}{}{Not so fast, how much is it worth to you?}
{420}{}{别急，这东西对你来说值多少钱？}

#{421}{}{(He takes the book from you) You have done us a great service. You now have free access to our computers in the library. Tell Brother Paul you have permission to access our files.}
{421}{}{(他接过书) 你为我们做了件好事。你现在可以自由使用图书馆里的电脑了。告诉保罗你获准使用我们的挡案了。}
{422}{}{谢谢。}

#{423}{}{You want money for it? Fine, here's $250. Go see Brother Paul for access to the computers.}
{423}{}{你要用钱换这个？好吧。这是$250。去找保罗谈使用电脑的事吧。}
{424}{}{谢谢你的钱。再见。}

#{425}{}{You should look downstairs, now that you have a free access there.}
{425}{}{你应该去楼下看看，现在你可以自由使用那的电脑了。}
{426}{}{好的，再见。}

#{430}{}{What is the purpose of your order?}
{430}{}{你们的目是什么？}
#{431}{}{What is the history behind the Abbey?}
{431}{}{那之后阿比有什么样的历史？}
#{432}{}{Hmm, I don't have any questions at the moment.}
{432}{}{喔，此刻我没有其他问题了。}
#{433}{}{Our holy mission is to read, copy and take care of our sacred books of knowledge. It is our hope that with this knowledge we are able to create a Memorabilia that might one day help humanity emerge from its self-imposed Dark Age. Any information that we come across is recorded down least it be lost like so much was in the great Flame Deluge.}
{433}{}{我们神圣的任务就是阅读，抄写和保护好这些神圣的书籍中的知识。我们希望有一天我们能帮助人类走出目前的黑暗时期。 }
#{434}{}{After the Great War, our ancestors came here and founded this old church. Luckily this place didn't suffer any structural damage and the radiation count was low enough for living here. After they settled up here, they found quite a large library in this building. There they found a lot of books and information on the library's computers.}
{434}{}{核战后，我们的祖先来到了这创办了这。幸运的是这个建筑没什么损坏而且这的辐射量也很小，适合生存。定居在这之后，他们在这找到了一个很大的图书馆。他们在图书馆里的电脑上找到很多知识，信息。}
#{435}{}{What happened then?}
{435}{}{后面又发生了什么？}
{436}{}{我已经听够了。}
#{437}{}{shortly after that, our ancestors decided to take care of all of this information. They built a small printing works that they used copy and preserve the books. Then they started to call this place "The Abbey". I don't know the origin of this name though.}
{437}{}{不久之后，我们的祖先决定保护好这些知识。他们建了一个小的复印工厂用于复印和保护这些书籍。然后他们将这命名为“阿比”。我不知道这么命名的原因是什么。}
{438}{}{(更多)}
#{439}{}{A few years after that, more and more of the wastelands lone survivors stumbled across this place. They soon realized that this was a safe place to live out their lives. Eventually they created a small independent community with our ancestors. We have lived in peace for many years and hopefully many more to come.}
{439}{}{几年之后，很多很多的废土上的生还者无意中来到了这个地方。他们马上意识到这里比在外面要安全。最后我们的祖先创立了一个小的独立的团体。我们和睦的生活了几年。}
{440}{}{谢谢你的故事。}]
#{441}{}{Where did your ancestor come from}
{441}{}{你的祖先来自哪里?}
#{442}{}{They never told where they originally came from. We suspect that they came here originally from the east.}
{442}{}{他们从来没有说过他们原先来自哪。我们猜测最早来自东方。}
#{443}{}{Well, thanks for the story.}
{443}{}{那好吧，谢谢你的故事。}
#{444}{}{Do you need any help here at the monastery?}
{444}{}{你在这需要什么帮助吗？}
#{445}{}{I found out what is wrong with the water pump.}
{445}{}{我找出了抽水泵出了什么问题。}
#{446}{}{Do you anything about the original founders?}
{446}{}{关于原先的创始人有什么消息？}
#{447}{}{I do not know all the names of our founders but the most important one I am aware of is Edward Leibowitz. Before the Great War he was an electrical engineer working for the United States government. Shortly thereafter he converted to Catholicism and made an oath with himself that we would spend the rest of his life preserving the knowledge of the past. His greatest fear was that this knowledge would be lost forever and thus needed to be preserved so that future generation may benefit.}
{447}{}{我不知道他所有的名字，但是我知道其中最有地位的一个叫爱德华－莱布尼兹。在核战前他是一个电力工程师为US政府工作。不久之后他改信仰天主教且立誓用一生来保护快要逝去的知识。他最害怕的是这些知识永远消失，因此为了未来新一代人们的利益必需保护。}
#{448}{}{You must be quite knowledgeable having read so much.}
{448}{}{你真的非常知识渊博。}
#{449}{}{I remember much of what I have read but I do not understand it all.}
{449}{}{虽然我记得很多以前读过的东西，但是我也不能理解全部内容。}
#{450}{}{Wait, you're telling me that you blindly write down whatever you read. Don't you try to comprehend it?}
{450}{}{慢着，你说你盲目的写下你读过的东西，难道你没有试试领会他们？}
#{451}{}{No, it is our job to preserve this knowledge not to understand it. Our ancestors never spoke of understanding the sacred texts we gather.}
{451}{}{不，我们的工作是保护这些知识而不是理解他们。}
#{452}{}{That's not learning then. True knowledge can only come from comprehension. Society can never progress if it just blindly records and memorizes. You have to act upon what you learn. Actions speak louder than words you know.}
{452}{}{于是没人学习理解？真正的知识来自理解。如果只是盲目记录和记忆，社会将永远不会进步。你知道的事实胜于雄辩。}
#{453}{}{That may be so, but our duty is to preserve and this is what we shall continue to do. I sense great wisdom in you, a pity I have met very few like you.}
{453}{}{那也许是这样的。但是我们的使命是保存，我们将继续这样做。我感到你很有智慧，可惜我不大喜欢见到你。}
#{454}{}{Thanks. I'd like to know something else though.}
{454}{}{谢谢，我还想知道一些事。}
 
#{500}{}{Stop that!}
{500}{}{停住吧！}
{501}{}{你获得200点经验值因为你带回了那本书。}

#{600}{}{I fixed the broken waterpump outside the church.}
{600}{}{我修好了教堂外的那个抽水泵。}
#{601}{}{That is great news indeed. That waterpump is always acting up now and then. Those merchants have been here several days and I don't think they made that much progress. Thank you again.}
{601}{}{那真是个好消息。现在那个抽水泵又起作用了。这些商人在这几天了，我不认为他们对此有什么改观。再次谢谢你。}
#{602}{}{I expect some money for this you know. Now cough it up!}
{602}{}{你知道的我期待得到一点报酬。现在拿来吧！}
#{603}{}{No problem. I have some other questions though.}
{603}{}{没问题。我还有一些其他的问题。}
{604}{}{我很乐意帮忙。保重。}

#{605}{}{(Looks surprised) What? Oh you soulless man. Fine, here, take these coins. Now go and stop bothering me.}
{605}{}{(看上去很惊讶)什么？真是无情的人。好吧，拿去。出去别再来烦我了。}
#{606}{}{Thank you *father.*}
{606}{}{谢谢。}

#{700}{}{Uhh...no I seem to have misplaced it.}
{700}{}{嗯...不，我不知放去哪了。}
#{701}{}{What!? (He sighs deeply) Well, I would have liked to have recovered that book. You say you've killed the beast. At least that is good news. I will still grant you access to our computers. Go see Brother Paul for the access key.}
{701}{}{什么！？ (他深深的叹了口气)好吧，我得重新印制一本了。你杀了那个怪物，最少这是个好消息。我仍然准许你使用我们的电脑。找保罗修士拿通行卡。}
{702}{}{谢谢你。}

#{800}{}{Well, actually yes. Our main water pump has been acting up and now it finally seems to have bit the dust.Is there any chance you could take a look and see if something can be done?  There are a few merchants already there working on it. I fear that little progress has been made though.}
{800}{}{好吧，实际上是的。我们的抽水泵运转不正常。如果你有时间的话去看看能不能做点什么？已经有一些商人在那工作了。我恐怕那没什么进展。}
#{801}{}{I'm happy to help. I'll report back on the progress.}
{801}{}{我乐意帮忙。有进展后我会回来报告的。}
#{802}{}{Sure, I'll be glad to help...for a price of course.}
{802}{}{当然，我很乐意帮忙...那么给个价吧。}
#{803}{}{Actually on second thought, let me ask you something else.}
{803}{}{让我考虑一下。让我问你点别的事吧。}
#{804}{}{What!? Oh, fine. If that's the kind of person you are, then you shall receive payment for your service. Here's25 coins to begin with.  Please let me know if something can be done. [The man sighs as he hands you the coins]}
{804}{}{什么！？喔，好吧。你确是这种人，之后你会得很你的报酬的。这有$25是预付金。 如果可以做什么事。请让我知道。[这个人边叹气边递给你钱]}
#{805}{}{Hey, no need for the sighing. You think everything in life comes for free?  Now, let me get to work.}
{805}{}{嗨，别叹气啊。你认为世上什么都是免费的？既然这样，我去工作了。}

#{806}{}{Really? Please do tell.}
{806}{}{你的？? 请说吧。}
#{807}{}{It seems the motor has gone out and fried all the connectors. I am going to Vault City to get a new part.}
{807}{}{看上去发动机坏了，连接器也烧了。我会去地下掩体城找一个新的。}
{808}{}{谢谢，你真是帮大忙了。装上新的时请报告我。}
{809}{}{我马上回来。}

#{900}{}{You explain to the head monk, though in vain, that progress can only come from action and not blind recording.}
{900}{}{你向修士长解释，虽然那是徒劳的，发展进步来自于把知识实践而不是盲目记录抄写。}
#{901}{}{You learn about the original founder of the Abbey.}
{901}{}{你学到了很多关于阿比的创始人的事。}