#ipisgfx译
{100}{}{你看见一个电脑操作员。}
{101}{}{你看见保罗修士。}
{102}{}{这个修士看上去是一个电脑操作员。}

{200}{}{嗨！}
{201}{}{你好。}
{202}{}{现在，今天我备份了这些文件了了吗...}
{203}{}{报歉，我没时间。}

{300}{}{是的？}
#{301}{}{You guys sure have a lot of computers here.}
{301}{}{你这家伙在这有很多电脑嘛。}
{302}{}{关于阿比你能告诉我什么？}
{303}{}{和我说说你们的领导者。}
{304}{}{你知道伊甸园创造器吗？}
{305}{}{你知道哪能找到13号避难所吗？}
{306}{}{再见。}
{307}{}{我很需要知道一些特别的消息。}
{308}{}{好的，比如什么？}

#{400}{}{Yes, we have. Too many in my opinion. It is so annoying to back up all these files each day. So much information to preserve, but it must be done.}
{400}{}{是的，我们有。在我看来很多。每天都要备份所有的文件那真是烦人。太多资料要保存，不过必需这样做。}
{401}{}{我可以想像。我还有一些别的问题。}
#{402}{}{We are an independent community. Anyone is welcome as long as they behave themselves.}
{402}{}{我们是一个独立的团体。长久以来我们欢迎任何人表现他们自我。}
{403}{}{好的。}
{404}{}{他是一个好的领导者。怪物杀了托马斯修士之后他有一些暴躁。}
{405}{}{什么样的怪物？}
#{406}{}{I haven't see it but I think that it is a large radscorpion.}
{406}{}{我没见过不过我认为是一只巨大的辐射蝎。}
{407}{}{为什么你认为是一只巨大的辐射蝎？}
{408}{}{因为我听见过洞穴传来的声音，听起来就像辐射蝎发出的。}
{409}{}{对。}
#{410}{}{In fact we do, take a look on that computer over there. Use this access card to access our encrypted files. (He hands you an access card)}
{410}{}{实际上我们做了。看看那边的电脑。用这个通行卡解开文件。(他给你一把通行卡)}
{411}{}{噢，非常感谢！}
#{412}{}{I don't know anything about Vault 13, but there is Vault City down south. Maybe they have the info you need.}
{412}{}{我不知道13号避难所。不过南边有一个避难所。也许那有你需要的迅息。}
{413}{}{谢谢。}
#{414}{}{That computer near me should have some information about it. You need an access card to it. We don't normally give access to just anyone, so speak to our leader to get permission first.}
{414}{}{我身边的电脑里有一些相关的信息。用他你需要一把通行卡。我不通常不会给任何人的，所以得先和我们的领导者谈谈获得许可。}
{415}{}{好的，谢谢。}

#{420}{}{You've read a lot of books, both technical and non technical, throughout your life then, right? Is there any particular subject that interests you the most?}
{420}{}{你真的读了很多书，包括非技术方面的和技术方面的，贯穿你的一生，对吧？有什么你特别感兴趣的科目的吗？}
#{421}{}{I've spent almost my entire life in this library, so yes most of what comes through here I have read at some point.There is one area that does interest me the most, however, but sadly I have read only one book on the subject. Botany - the study of plant life. I became fascinated with it after reading a text book about it. I would love to read more on this subject.}
{421}{}{我一生都在用在这个图书馆，所以是的我读了很多。这有一个我最感兴趣的领域，可是，可惜的是我只读过一本关于那个学科的书。 植物学－有关植物的。读过一本关于这个的书后我对此很着迷。我真希望能读到更多关于这个学产的书。}
#{422}{}{Well, I do a lot of traveling. If I come across any information about this I will let you know.}
{422}{}{好的，我旅行过很多地方。如果我有关于这方面的信息我会告诉你的。}
{423}{}{对啊...好吧，我还有一些问题。}
#{424}{}{Would you? I'd appreciate that.}
{424}{}{你愿意？我太感谢了。}
{425}{}{没问题。我还有一点问题。}
{426}{}{好吧，回见。}

#{430}{}{I found some information about Botany that might interest you.}
{430}{}{我找到一些关于植物学的信息，你可能会感兴趣。}
#{431}{}{Really?! That's great. Please, do tell immediately.}
{431}{}{真的吗？！太好了。现在就告诉我。}
#{432}{}{Fascinating! I shall take this holodisk and add it to the computer database immediately. I appreciate you taking the time to find this for me. Thank you for collecting this for me.}
{432}{}{太神奇了！我现在就将这些东西存入电脑的数据库里。 我感谢你花时间为我找到这些东西。谢谢！}
{433}{}{Well you see...Understanding habitat destruction and species extinction is dependent on an accurate and complete catalog of plant systematics and taxonomy. And then this means that...}
{434}{}{Any time. I have some other questions though.}
{435}{}{没问题。回见。}
{436}{}{太神奇了！我感谢你花时间为我找到这些东西。请帮我把这些上传到我们的电脑里。 }
{437}{}{没问题，我会的。回见。}

#{500}{}{Stop that, moron!}
{500}{}{住手！你这个白痴！}

#{550}{}{That computer near me should have some information about it. You now have access, so take a look for yourself.}
{550}{}{我身边的电脑里有一些相关的信息。你现在有通行卡了。自己去查下吧。}

#{600}{}{The Headmonk gave me permission to access the computers here.}
{600}{}{修士长允许我使用这些电脑了。}
#{601}{}{Ah yes, I heard about what you did. Thanks for taking care of that situation. Here is the access key. (He hands you the key.) Enjoy!}
{601}{}{啊是的。我听说了你所做的。谢谢你做的一切。拿去这是通行卡。 (他把通行卡递给你。) }
{602}{}{谢谢，一会见。}

#{650}{}{Greetings traveler! I am Brother Paul and I am in charge of the collection of information for the Abbey. What can I do for you?}
{650}{}{祝福你旅行者！我是保罗修士，我在阿比负责收集信息。我能为什么做什么？}
{651}{}{见到你很高兴。我还有一点问题。}
{652}{}{没事，回见。}