#ipisgfx译
#{100}{}{You see a squatter.}
{100}{}{你看见一个流浪者。}
{101}{}{你看见一个又脏又臭的男人。}
{102}{}{你看见一个又脏又臭的女人。}

#{103}{}{Hey man, we were here first. What do you want?}
{103}{}{嗨伙计，我们先来的。你想干嘛？}
#{104}{}{It has come to my attention that the children of the Den need a place to live and I believe this building is just right for this. I have therefore come to take possession of it.}
{104}{}{我觉得丹恩城的孩子们需要一个地方生活，我觉得这栋建筑很适合做这个。因此我来看看。}
#{105}{}{Wait, what? You can't be serious...}
{105}{}{等等，什么？你不是认真的吧...}
#{106}{}{I am serious. We need a large building to serve as an orphanage and this building is perfect. The only problem is you and your friends are living here.}
{106}{}{我是认真的。我们需要一栋大建筑来开办孤儿院，这正好很合适。唯一的问题是你和你的朋友住在这。}
#{107}{}{Wait...are you trying to evict us? That ain't cool. Fight the system, man! Yeah, that's what we'll do...fight the system!}
{107}{}{等等...你是在驱逐我吗？那一点也不酷。混蛋...开打吧！}
#{108}{}{Listen, you have two choices either vacate this place peacefully or leave here in a body bag.}
{108}{}{听着，你有两个选择要么是平静的离开这，要么把你们的尸体打包扔出去。}
#{109}{}{(The man looks at you.) Nah man, no one is kicking us out of here. We'll fight you for our turf.}
{109}{}{(这个人看看了你) 不伙计，没人能让我们离开这。我们会为我们的地盘而战的。}
#{110}{}{(The man nodes.) OK, no need to get all angry about this. But where would we go? We don't have anywhere else to hang out.}
{110}{}{(这个人强忍住) 好的，不需要为这么生气。不过我们能去哪？出去我们没什么任何地方可住院。}
#{111}{}{I don't know. That's not my problem.}
{111}{}{我不知道。那不是我的问题。}
#{112}{}{I may regret saying this but would you be interested in working at the orphanage? If all of you promise to clean up you all can get free food here and some money in exchange for keeping the building clean.}
{112}{}{这样啊，你们有兴趣在孤儿院工作吗？整理一下你们自己，如果你们愿意可以做这的清洁工，你们还可以得到免费食物和一些钱。}
#{113}{}{Nah man. I changed my mind. We ain't leaving. We're staying right here and fighting.}
{113}{}{不伙计，我改变主意了。我们不离开。我们就在这，开打吧。}
#{114}{}{That sounds great! I'll tell my friends about this. You can count on us man. Don't worry, we'll keep those children safe.}
{114}{}{那听起来不错！我会告诉我的朋友这事的。你可以相信我们。不用担心，我们会保证这些孩子安全的。}
{115}{}{别介意。}

#{120}{}{This is a great idea. We'll get things ready.}
{120}{}{这是个好主意。我们去做下准备。}

{200}{}{哈?}
#{201}{}{This is our turf.}
{201}{}{这是我们的地盘。}
#{202}{}{You squatting here too?}
{202}{}{你也想住这？}
#{203}{}{Got anything to eat?}
{203}{}{弄点东西吃？}

{300}{}{你看见一个穿着工作服的男人。}
{301}{}{你看见一个穿着工作服的女人。}

#{310}{}{Hey, thanks for letting us stay. We'll work hard.}
{310}{}{嗨，谢谢让我们留下。我们会努力工作的。}
#{311}{}{You better. Make sure the children stay out of trouble too.}
{311}{}{你最好不要让孩子们有什么麻烦。}
#{312}{}{We'll do our best.}
{312}{}{我们会尽力的。}
{313}{}{再见。}

#third way to finish quest -added after initial creation, but before official release
#{350}{}{Anywhere but here. The orphans need a place to live and there is no other building around large enough for all of them. I'm sure you can find some other place to live. Come on, do you really want the children to live on the streets.}
{350}{}{孤儿们需要一个地方住，周围没有足够大的房子。我也知道你们找不到其他地方住了。但是，你们真想让孩子们住在大街上？}
#{351}{}{Nah, you're right that ain't cool for the children. This place had a leaky roof anyway. Alright, we'll pack our things and move out. We are squatters anyway, anywhere is good enough for us.}
{351}{}{不，你是对的，这里的房顶还有漏洞。好吧，我们收拾东西后就走。我们去找别处，任何地方对我们来说都行。}
#{352}{}{Thanks. This will mean a lot to them. Take care.}
{352}{}{谢谢，这对他们来说有很大意义。保重。}
#{353}{}{Nah man, that ain't our problem. I've lived on the streets most of my life. Plus, we were here first and we'll fight for it. I've had enough of this conversation, time to kick you out.}
{353}{}{不伙计，那不是我们的问题。我们一生大部时间都露宿街头。再说，我们先到这的，我们谈的够多了，是时候踢你出去了。}

{400}{}{再次感谢！}
{401}{}{我们会努力工作的。}
{402}{}{谢谢让我人留下。}
{403}{}{我们不会让你失望的。}

{500}{}{我们收拾好东西马上就走。}