#ipisgfx译
#You see a small boy.
{100}{}{你看见一个小男孩。}
#You see Little Johnny.
{101}{}{你看见利特尔-约翰。}
#He is wearing dirty clothing and has bruises on his neck and face.
{102}{}{他穿着一身脏乱的衣服而且脸和脖子上都有瘀伤。}
#He is wearing new clothing and has a smile on his face.
{103}{}{他穿上了新衣服而且脸上充满笑容。}
#Hi mister! My name is Johnny and I live here with my Dad.
{104}{}{嗨，先生！我叫约翰，我和爸爸一起住在这。}
#Hi miss! My name is Johnny and I live here with my Dad.
{105}{}{嗨，先生！我叫约翰，我和爸爸一起住在这。}
#I see. Well tha-
{106}{}{我知道，不过你看上去不是很好。}
#Yeah, I don't really like living with my dad though. He is drunk all the time and sometimes beats me when he gets angry. (He lifts up his shirt sleeve and shows a bruise on his arm.) Daddy also has me stealing from other people, like many of the other children around town do. I don't like to steal from people and this makes Daddy mad.
{107}{}{是的，虽然我不是很喜欢和爸爸一起生活。因为他总是在喝酒，而且有时他生气时还会打我。(他拉起衣袖，手臂上都是瘀伤) 爸爸总是叫我去偷别人的东西，就像这个城里的其他小孩一样。我不喜欢偷别人的东西，这使爸爸非常生气。}
#This sounds horrible. No parent should treat their child this way.
{108}{}{这听起来真可怕。没有任何父母会这样对待自己的孩子的。}
#Hah, I would beat my son too if he didn't listen to me. Your father sounds like a good man.
{109}{}{嘿, 我儿子如果不听我的我一定会收拾他的。你老爸做的没错。}
#(His eyes light up) You aren't like the others that come through here. I like you. (He then sighs.) I still love
 my dad but I can't keep living like this. I don't like it here and I wish I could live some place else. I know the other
 children around town don't like what they are doing but stealing is all they got. They don't have a home or anyone to care for them.
 I have a home but life here isn't much better. I wish there was something we could do.
{110}{}{(他眼前一亮) 你和其他人不太一样。(他叹息)虽然我仍然爱我的爸爸但是我不能这样生活下去了。 我不喜欢这，我希望我能住到其他地方。我知道城里其他的小孩也不喜欢他们目前做的事，但是他们没法选择。他们没有家也没有人会照顾他们。虽然我有家但也好不了哪去。我希望我们能做点什么。}
#You're a meanie! Go away. I don't like you.
{111}{}{你是个坏蛋。滚开，我不喜欢你。}
#There's gotta be something that we can do. Is there someone in town I can talk to about this matter?
{112}{}{我想我必需做点什么了。在这城里有什么人可以听我说说这个问题吗？}
#Well, the only person that really cares about people around here is Mom over at the Diner on the East End. She's a nice lady and she always
 gives me and the other children free food. Maybe she could help us?
{113}{}{嗯，唯一会真正担心我们的人是妈妈桑，她在城东的一家餐馆。她是一个很好的女士，她经常免费给我和其他孩子食物。也许她能帮我们吧？}
#Thanks for the information. I will go see Mom now. Bye.
{114}{}{谢谢你的信息。我马上去见见妈妈桑。回见。}
#Your such a little brat. Bye.
{115}{}{你真是个小鬼头。再见。}
#I spoke with Mom and with my help she has opened an orphanage in the large building north west of here. She should have
 things all organized in a few days.
{116}{}{我和妈妈桑谈过了，我帮她在城西北找了一栋大房子开孤儿院。这几天就弄好了。}
{117}{}{(男孩脸上呈现强烈的喜悦表情) 真的吗？ 太棒了！ (他冲上来抱住了你) 我等不及想和其他伙伴一起住去那了。我太兴奋了。 再次谢谢你先生！}
{118}{}{男孩脸上呈现强烈的喜悦表情) 真的吗？ 太棒了！ (他冲上来抱住了你) 我等不及想和其他伙伴一起住去那了。我太兴奋了。 再次谢谢你小姐！}
#You're welcome kid. See you around.
{119}{}{不用客气孩子。一会见。}
#Hi again! Any luck?
{120}{}{嗨有见面了！一切都顺利吗？}
#I'm still working on it. Give me some time.
{121}{}{我正在想办法，给我一点时间。}
#You help Johnny find a better life.
{122}{}{你帮约翰找到了新的生活。}
#Hi again! Thanks for everything. I love this new place. Mom is such a great lady!
{123}{}{嗨有见面了！谢谢你所做的事。我爱这个新家。妈妈桑是一个非常好的女士！：）}
#I love this new place. Mom is such a great lady!
{124}{}{我爱这里。妈妈桑是一个非常好的女士！ ：）}

#I'm so excited! Time to pack my stuff.
{125}{}{我太兴奋了！ 我这就去收拾我的东西。}
#I wonder if dad will notice I am gone.
{126}{}{我很怀疑如果爸爸注意到我走了会怎样。}
#This is going to be so much better.
{127}{}{一切都会变得更好的。}

#I don't like you. Go away!
{200}{}{我不喜欢你。滚开！！！}