# Message file for epac2.ssl 
# Number of nodes: 6

#ipisgfx译
#You see a Hologram.
{100}{}{你看到一个全息摄影。}
#You see the Director of Science.
{101}{}{你看见一个科学主管。}
#Hologram 00000. He looks after the science aspects of the EPA.
{102}{}{全息人00000. 看起来好像是EPA科学方面的东西。}

# Node  0  [Node001]
{200}{}{01100 00 11 00 11 001 0001 00 11 1 0000 111 000 111 0000111000101000011 00 1100010 01000100 1}
#Right, I'll be going then...
{201}{}{好的，我马上要走了...}
#This Hologram seems to be having some trouble expressing himself. Maybe something is wrong with his circuitry?
{202}{}{这个全息人自身好像有些故障。也许电路上出了点问题吧？}

# Node  1  [Node002]
{210}{}{0001010 111000111 011 01111 0110 111 011101 011001 1001 1001 1001 000 10000011011 0111 0011 01100}
#There is definitely something wrong with this Hologram. Maybe I could repair it somehow?
{211}{}{明显这个全息人有一些故障。也许我能修好它吧？}

# Node  2  [Node003]
{220}{}{0000101 011100 11101 01 10 11 0110 10010100001100}
#This Hologram is still having trouble after being repaired. Maybe it could be rebooted.
{221}{}{修过后这个全息人仍然有些故障。也许要重新起动一下。}

# Node  3  [Node004]
#You have managed to repair me! It's been fifteen years since anybody understood me! How can I ever repay you?
{230}{}{你设法修好了我！十五年来没人理我！ 我怎么才能报答你？}
#Well, you could tell me a little about this place.
{231}{}{好吧，你可以和我说说这个地方发生了什么事。}

# Node  4  [Node005]
#Well, what can I tell you? This is the EPA, a large well-established research facility from pre-war times. Luckily, it remained intact after the war, but all but one of the scientists left and now there are only us Holograms left in the facility.
{240}{}{好吧，你想知道什么？这里是EPA（美国环境保护署），战前家喻户晓的研究机构。很幸运，战后还完整保留，但是所有的科学家都离去了现在只有我们这些全息人还在这。}
#Thanks for your time. I'll see you later.
{241}{}{谢谢。一会再见。}

# Node  5  [Node006]
#Hey, thanks for fixing me up! If you ever need anything around here, let me know.
{250}{}{嗨，谢谢你修好我！如果你想要这里的任何东西，告诉我。}
#Thanks. I will.
{251}{}{谢谢，我会的。}
#You fix Hologram 00000.
{252}{}{你修好了全息人00000。}