{100}{}{你看到一个英俊的年轻人。}
{101}{}{你看到达宾。}
{102}{}{你看到一个二十来岁的年轻人。他看起很像葛力斯韩。}

{150}{}{如果你要的话，你可以拥有我。}
{151}{}{麦丽雅在床上的表现并不是那么好。}
{152}{}{我真不敢相信你拉了我的皮条。}
{153}{}{下一次我们试试“三人行”吧。}
{154}{}{喔，他真是一个小可爱。}
{155}{}{问她。}
{156}{}{那很好；谁是下一个？}
{157}{}{嗨！我叫达宾；我在摩多克帮助我爸爸经营屠宰场。}
{158}{}{我正在找孔尼洛斯的金表，你有看到它吗？}
{159}{}{你在屠宰场都做些什么？}
{160}{}{我听了很多有关你与双头牛之间的谣言。}
{161}{}{告诉我有关你爸爸的事。}
{162}{}{你好。}
{163}{}{我就知道你会回来找我的。}
{168}{}{为什么不让我们更“舒服”一点呢？}
{171}{}{待在这边。}
{172}{}{当然，我有时间。问吧。}
{178}{}{不，没有看过。}
{179}{}{可以再问你几个问题吗？}
{180}{}{我负责看着所有的东西。我是老板的儿子，因此，当我爸死之后，那个地方一定会是由我来继承的。}
{182}{}{那是一个谎言。我每天晚上到牛舍只是为了要确定所有的东西都锁好而已。你知道的，有许多的野生动物都会过来攻击．．}
{184}{}{爸爸经营着屠宰场。如果你想要与他做生意，那我给你一些忠告，他跟你谈生意时，都会留个几手的。}
{186}{}{如果你还想要谈话的话，就来找我吧。}
{187}{}{哇，我从来都不敢想像这样漂亮的女人会挑逗我。等一下！你不是一个女人！不过不用担心，像你这样漂亮，如果你不介意的话，我也不介意的。}
{188}{}{我一定是在作梦。我真不敢相信这样漂亮的女人会想要挑逗我。你是在挑逗我，对不对？}
{189}{}{我们都已身在天堂了，让我们不要用言语来破坏了这完美的一刻吧。让我们“马上行动”吧。}
{190}{}{不要说话了；你会破坏气氛的，让我们好好的享受吧。}
{191}{}{你一定是误会了；我只是想要问你一些问题。}
{192}{}{谢谢你，但是我看不要好了。嗯．．我要走了。}
{193}{}{老天吧！上我吧！上我吧！ [他把自己的衣服给撕破，然后将你的也撕破．．接下来玩家们就自己想像吧]}
{194}{}{[呵呵] 让我们来玩玩吧。}
{195}{}{[两个小时之后：真是大地也为之震动啊，这张床看来是完蛋了。]}
{196}{}{[一个小时之后，你感受到了前所未有的性高潮。]}
{197}{}{[在半个小时之后，你全身筋疲力尽的瘫在那边，动弹不得。]}
{198}{}{[十五分钟之后．．]}
{199}{}{[你把你的所有的衣服给脱掉了。]}
{200}{}{我要走了，再见。}

{251}{}{快逃!}

# wedding script dialog
{400}{}{爸爸！}
{401}{}{喔！}
{402}{}{我当然愿意！}
# Seraph's Code: Uncle Biff
{405}{}{毕夫叔叔!}

{410}{}{嗯．．}
{411}{}{嗯．．继续，拜托．．}
{412}{}{我当然．．}
{413}{}{嗯，我愿意。}

{450}{}{嗯，我不是你应该要谈的人。}

{500}{}{天，我一定要成为这边控制大局的人。}

{1000}{}{是的，我的甜心。}
{1001}{}{我可以帮你吗？}
{1100}{}{我的伤完全好了，准备好要走了。}
{1200}{}{我身上的伤口几乎都好了。}
{1300}{}{我身上的伤都好了，但是有时间我还是应该要多治疗一下。}
{1400}{}{我已经尽量的自我治疗了，但是我还是伤得很严重。}
{1500}{}{不，宝贝；我要跟你一起去。}
{1600}{}{当然，我会把它拿开的。}
{1700}{}{好，我会在你面的。}
{1800}{}{那我就无法保护你了。不行，我最好靠近一点。}
{1900}{}{是那要吗？不行。我不让你离开我的视线，你这小枪侠。}
{1005}{}{你不懂的。我只是不想要我在走路的时候搂搂抱抱的。}
{1006}{}{我要你走在我后面很远的地方。}
{1007}{}{但．．但．．我那里做错了？}
{1008}{}{你到底要我干什么，我的甜心？}
{1009}{}{谢谢。现在要怎样呢，爱人？}
{1010}{}{我在屠宰场时很会剥牛皮，因此我使用刀的技术还算不错。还有一次，爸爸让我用一根棒子把牛打死。因此，我也会用棒子。喔，有一次爸爸带我去射击，但是我相当害怕，因此差一点不小心开枪把他给杀了。}
{1020}{}{我想要静一下，达宾。}

{1100}{}{I'm completely healed and ready to go.}
{1200}{}{Just a couple of bruises left, that's all. Don't worry about it, honeybunny.}
{1300}{}{Well, I'm mostly healed -- but I could use more healing when we get a chance.}
{1400}{}{I healed myself as much as I could but I'm still pretty badly hurt.}
{1500}{}{No, baby; I wanna come with you.}
{1600}{}{Sure thing, I'll put it away.}
{1700}{}{Understood. I like it close to you, baby.}
{1800}{}{No, no, honeybunny. I think... Oh, well, let it be then.}
{1900}{}{But then I wouldn't be near to you, honeybunny.}


{5000}{}{What's wrong with me? I'm so sick...}
{5001}{}{If I could only gather more strength...}
{5002}{}{What's happening with me? And where did this cyst came from?}
{5003}{}{My skin is burning, honeybunny! And I feel so itchy!}
{5004}{}{Damn, that was a bonebraking sound.}
{5005}{}{Arrrgrggggrhhh... It looks like a break.}
{5006}{}{The pain! Make it stop, honeybunny, make it stop!}
{5007}{}{God, I'm gonna die here, I'm gonna die...}

{5010}{}{That's what I needed! Thanks, baby.}
{5011}{}{Thanks, honeybunny.}
{5012}{}{Honeybunny, is that needle rusty?}

{5020}{}{Thanks, I... sweeeeet!}
{5021}{}{Hey, gimme more of that!}
{5022}{}{Hey, is that the chicken from Rosas coop? And why it's so pink?}
{5023}{}{I once saw my grandad and some of his friends burn a whole pile of these in the shed... Its wierd, they locked themselves in with the fire. I freaked out and told mom, then she freaked out and... Never mind.}

{5030}{}{Hey, cheers!}
{5031}{}{Yum, this is so... Refreshing!}
{5032}{}{If we keep on drinking, I think I'll ream you tonight 'till you mess both of us.}

{5100}{}{Yeah, yeah.}
{5101}{}{I might poke you a bit! Well, maybe not in public.}
{5102}{}{Hey, stop it.}
{5103}{}{You expect me to go *THERE*?}

{5200}{}{What?}
{5201}{}{It wasn't enough the last time, huh?}
{5202}{}{Yeah, yeah. It's a bump, so what?}
{5203}{}{What? Is there something stuck on my groin?}
{5204}{}{The worm is sleeping now. Come by later.}
{5205}{}{Scanning me again?}
{5206}{}{Whatta woman.}

{5500}{}{La-la-la-la...}
{5501}{}{I got my needs, you know?}
{5502}{}{<whisper> Honeybunny, my pipe is itchy!}
{5503}{}{Anything interesting here?}
{5504}{}{What is this place? Clone camp?}
{5505}{}{What's dad doing now, I wonder? Nah, forget it.}
{5506}{}{Any booze in our inventory?}
{5507}{}{I'm sick of travelling.}
{5508}{}{I wonder how my brahmins are? Well, I have others to take care of them now.}
{5509}{}{Dirt over here, grease over there, I'm so messed up...}
{5510}{}{My neighbour's son, Josh, once told me him and his dad once scared off a super mutant. Said it had two heads like a Brahmin and its legs were as wide as the town well. I'm pretty sure now that he was lying.}
{5511}{}{What's with that blue pyjama? You don't have any other, do you?}
{5512}{}{That blue outfit is full of lice! Take it off!}
{5513}{}{So, ever heard of a soap?}
{5514}{}{Let's play, baby. I'll shoot my cannon, and you can be a fortress which take the shots!}
{5515}{}{I like standing on the doors. Although I don't know why, but I like it! It doesn't bother you honeybunny, does it?}
{5516}{}{I wish my animator gets a fortune on a lottery. Hehe, just kidding! I hope he'll live in misery and pain!}
{5517}{}{Did you have to ride me so hard last night? I can't feel my groin!!}
{5518}{}{::.BURP.:: Oops! Sorry honeybunny!}
{5519}{}{EVERYBODY BE COOL, THIS IS A ROBBERY! Hey, can't you take a joke?}
{5520}{}{<singing> If you want my body and you think I'm sexy...}

# Specific Locations
{5600}{}{What kind of sewer is this place?}
{5601}{}{Dirty, filthy and not healthy.}
{5602}{}{This place is forsaken.}
{5603}{}{Dull place.}
{5604}{}{Look, it's a... Courtyard.}
{5605}{}{I wonder if they have enough water here?}
{5606}{}{Well, this looks better than the courtyard.}
{5607}{}{It's so clean here. I wonder why would someone be SO clean?}
{5608}{}{And here some politicians can be found, I guess.}
{5609}{}{I remember the word "citizen". It's writen on the Cornelius' watch.}
{5610}{}{Whoa! So much steel in this place.}
{5611}{}{These walls are painted with a strange paint...}
{5612}{}{I thought, we could stop by dad and say hello. And we could play doctor with Miria, too... Probably not a good idea.}
{5613}{}{Sweet home... Modoc.}
{5614}{}{I miss those omeletes, yes I do!}
{5615}{}{I thought I'm gonna stay in this place forever.}
{5616}{}{Shit, shit, shitter!}
{5617}{}{Let's get out of here already!}
{5618}{}{Hmmmmm... My nose tells me we should leave this place.}
{5619}{}{Interesting place. Now, let's go outta here!}
{5620}{}{Hey! Are those things real?}
{5621}{}{Honeybunny...}
{5622}{}{I think I'm gonna throw up.}
{5623}{}{Damn, it stinks here!}
{5624}{}{Narrow tunnels... It can't be good.}
{5625}{}{Lighter, anyone?}
{5626}{}{This place is messed up.}
{5627}{}{Anything working around here?}
{5628}{}{I thought we're never gonna find this place. But we did it!}
{5629}{}{And that's where the whole this story started, huh?}
{5630}{}{Look, they have police officers here!}
{5631}{}{Did I ever tell you that joke with a cop... Erhmmm. Forget it.}
{5632}{}{Hey, I hate politics! What are we doing here?}
{5633}{}{It's so... Tidy.}
{5634}{}{It looks like they trade here, honeybunny.}
{5635}{}{So, what's the plan now?}
{5636}{}{I think we found... Tents!}
{5637}{}{Look! There are some crates around here.}
{5638}{}{Hey! Look these sluts!}
{5639}{}{I'd rather die than pimp women like that...}
{5640}{}{Honeybunny, this place sucks...}
{5641}{}{These women are exploited. There must be something someone can do for them!}
{5642}{}{What's so NEW about this place, anyway?}
{5643}{}{There are some shops over there. Let's check'em out!}
{5644}{}{This looks better than the rest of the town.}
{5645}{}{Look, there's a big house over there.}
{5646}{}{So many graves, so many names...}
{5647}{}{So, how long do we stay here..?}
{5648}{}{Crap! This place is worst than a crap.}
{5649}{}{Well, ruins are not on the top of my sight-seeing list.}
{5650}{}{This looks like a western movie. Where's the sheriff?}
{5651}{}{All these miners gambling around...}
{5652}{}{I think I now why this place is called "broken".}
{5653}{}{What kind of townsfolk are these people, anyway?}
{5654}{}{Look, there's a mine!}
{5655}{}{All houses here looks the same. The designer should be shot.}
{5656}{}{Honeybunny, I'd be careful...}
{5657}{}{Hi-tech place, no doubt.}
{5658}{}{A tanker? Where did that come from?}
{5659}{}{Vagrants. If I only knew what kind of people they are.}
{5660}{}{Something's roten in the state of... Oh, it's fish.}
{5661}{}{Do these people take a bath regularly..?}
{5662}{}{Big trouble in little China. Now, where the hell I heard of it?!}
{5663}{}{They have a nice entry gate here.}
{5664}{}{I think "Challenger" would be apropriate name for that thing.}
{5665}{}{I wonder is there a fuel in it?}
{5666}{}{Sweet, someone got this map back in the game!}
{5667}{}{Whoa! I think my pyton would like to meet Vikki!}
{5668}{}{Honeybunny, I'd stay away from this... Group.}
{5669}{}{This guys can't be serious... C'mon, they don't really beleive in all that shit?}
{5670}{}{Impressive...}
{5671}{}{Is there anything for us in this place?}
{5672}{}{What? A detention?}
{5673}{}{I vote for leaving this place. Immediately!}
{5674}{}{Honeybunny... I have a bad feeling about this.}
{5675}{}{So, are you going to listen to me or we're gonna die soon?}
{5676}{}{Look at me! WE - OUT - OF - HERE!}
{5677}{}{Well, I've seen worst things. Or maybe not.}
{5678}{}{Honeybunny, you know what you're doing?}
{5679}{}{No. This can't be good.}
{5680}{}{Honeybunny... I love you. Maybe there won't be the next chance to say that.}

# Caves
{5700}{}{Caves. Caves! Caves!!!}
{5701}{}{Is this a tour through caves, maybe?}
{5702}{}{I mean, why do we have to stick our nose in there?}
{5703}{}{Why do you like caves so much?}
{5704}{}{I'd rather explore your caves, baby.}
# Coastal
{5705}{}{Wow! Look at all that water!}
{5706}{}{Mmmm! Feel how clean that air is!}
{5707}{}{DID YOU SEE THAT?! Something *HUGE* just jumped out of the water!}
{5708}{}{All that yellowish stuff floating on the water is making me think of Rotgut for some reason.}
{5709}{}{Is it true that this water is salty?}
# Desert
{5710}{}{Never seen so much sand in one place.}
{5711}{}{I'm thirsty.}
{5712}{}{Baby, I see some strange things around... Then they disappear!}
{5713}{}{Fuck this.}
{5714}{}{One more minute here and I'll melt.}
# Mountains
{5715}{}{Hmpf. Mountains.}
{5716}{}{I think I like coastal areas more than this.}
{5717}{}{God, why did you have to make all these mountains?}
{5718}{}{Noooo, not another... Mountain!}
{5719}{}{This is a desolate place. Let's move along, baby.}
# Urban Ruins
{5720}{}{This was a town. Look at it now...}
{5721}{}{Hey, I think I heard something behind those walls.}
{5722}{}{This place was alive. Think of it.}
{5723}{}{The Great War really wiped such places off.}
{5724}{}{I wonder what kind of people used to live here before the war?}

# No armour
{6000}{}{Want me to take anything else off?}
{6001}{}{It's your turn to get naked now, honeybunny...}
# Leather Armour
{6005}{}{Well, better than nothing, that's for sure.}
{6006}{}{How do I tighten these straps? Baby, I need help!}
# Leather Jacket / Cured Leather Armour
{6010}{}{God, this is... Sweaty?}
{6011}{}{You can call me "Mad Dave" now.}
# Metal Armour / Metal Armour Mk II / Tesla Armour
{6015}{}{Not bad... This cold metal should come handy in the desert.}
{6016}{}{If I meet someone with a flamer, I'd better say my prayer.}
# Combat Armour / Combat Armour Mk II / Brotherhood Armour
{6020}{}{Damn, I look so good in this outfit!}
{6021}{}{Woah! This protective gear contains a sunglasses, too!}
# Power Armour / Hardened Power Armour
{6025}{}{Now, this is some serious piece of hardware!}
{6026}{}{Hey, I feel stronger wearing this!}
# Advanced Power Armour / Advanced Power Armour Mk II
{6030}{}{Never thought I'd wear something like this!}
{6031}{}{Do I look like a stove?}
# Robes
{6035}{}{Hey, check out how my snake can peek out under this! Wow, thanks honeybunny!}
{6036}{}{I like it, baby! Now I don't have to take my gear off when we want to play doctor.}

# Stay!
{8000}{}{Okay, baby... See you soon!}
{8001}{}{Yeah. And I should go shopping around? Oh, what the hell...}
{8002}{}{OK... But don't be a naughty girl!}
{8003}{}{Sure... Just stay the hell away from any gigolos you 'happen' to find!}
{8004}{}{Fine, fine. Just don't leave me here forever!}
# Come!
{8005}{}{Yeah, yeah... Heard that.}
{8006}{}{You didn't find some other doctor now, did you?}
{8007}{}{So, we're on the road again?}
{8008}{}{Hi honeybunny... Hey, you look a bit tired. Been riding a lot?!}
{8009}{}{So, where to now?}
# Bad rep; wouldn't come if wasn't married & scared shitless.
{8010}{}{Honeybunny... you scare me. I... okay.}
{8011}{}{Yes, darling.}