#ipisgfx译
{100}{}{你看见一个土著女孩。}
{101}{}{你看见克莉苏，史力克的妹妹。}
{102}{}{你看见一个年青的女孩。}

{150}{}{[结束]}

#{200}{}{Sulik! Is...[She catches herself and begins to whisper] Is that really you?}
{200}{}{史力克！真...[她感到很惊讶] 真的是你吗？}
#{201}{}{Me? No, I'm the Chosen One. You must be thinking of old bone nose here.}
{201}{}{我？不，我是获选者。你说的是这个鼻子上穿骨头的家伙吧。}
#{202}{}{[Sulik rushes to the gate door and he and his sister grab each others hands. Tears stream down their faces as they exchange greetings. Suddenly, a twig snaps outside the building, Sulik lets go of his sister and reaches for his weapon as he glaces at the door. No more sounds come from outside.]}
{202}{}{[史力克冲过去拉住他妹妹的手。两人热泪盈眶相互拥抱在一起。此时才注意到我们在房子外面，史力克离开他妹妹拿出武器试图把门打开。]}
{203}{}{[更多]}
#{204}{}{[Sulik's sister then turns to you] Please, get me and out of here. We don't have much time. Tomorrow they are planning to move me from here. They've already moved my other fellow tribespeople. Please, you must do something, I don't want them to touch me again. [Upon hearing this, Sulik's eyes widen and a look of rage comes over his face. He reaches for his weapon.]}
{204}{}{[史力克的妹妹转向你] 求求你，把我从这弄出来。没多少时间了，明天他们就要把我们带去别处了。他们已经把我其他的部落成员带走了。求求你，做点什么吧。我不想他们再碰我了。 [听到这些时，史力克很愤怒。他抓紧手中的武器]}
#{205}{}{Hold on there Sulik, we're outnumbered here. Let me see if I can lockpick this door and we can sneak our way out of here.}
{205}{}{在这等着史力克，我们人没他们多。让我看看能不能把锁撬开，我们可以悄悄离开这。}
{206}{}{在这等着史力克，我们人没他们多。我拿到钥匙了。保持安静我们悄悄离开这。}
#{207}{}{[You nod at Sulik] These bastards will pay. Lock and load ol' buddy.}
{207}{}{[你向史力克点点头] 这些杂种要付出代价的。准备好我的兄弟。}
{208}{}{[几分钟后你听到咯一声。门开了。]}
#{209}{}{[You turn to Kurisu.] Alright, stay close and keep your head down. [To the other slaves.] Keep quite and head for the woods.}
{209}{}{[你转向克莉苏] 好吧，一会跟紧低下头。[对其他奴隶说] 保持安静注意隐藏。}
#{210}{}{[A few minutes pass by and you are unsuccessful unlocking the door.]}
{210}{}{[几分钟后你成功打开门]}
#{211}{}{There must be another way to unlock this door. Let me see if I can get a key to this door. Wait here I'll be back for you.}
{211}{}{一定有别的方法打开门，让我看看能不能弄到钥匙。在这等着我一会回来。}
#{212}{}{Alright Sulik, it's time for your plan. Time to take out the trash.}
{212}{}{好的史力克。是时候执行你的计划了。是时候离开这里了。}
#{213}{}{[You put the key in the lock and unlock the gate, it sreeches as it opens.]}
{213}{}{[你用钥匙打开门]}

#{214}{}{Any luck? Please hurry.}
{214}{}{怎么样了？求求你快点！！}
{215}{}{还没呢。我正在努力。}
{216}{}{我拿到钥匙了。是进时候把你弄出来了。}
{217}{}{外面出什么事了？你是-...史力克是你吗？}
{218}{}{外面出什么事了？你是谁？}
{219}{}{我来救你了。}

{221}{}{喔，感谢上天！求求你，把我们弄出去。}
{222}{}{喔，谢谢！我得走了。请一定要来我们村子。就在海岸边，这里西南边几天时间路程。再次感谢你。}
{223}{}{[史力克冲过去拉住他妹妹的手。两人热泪盈眶相互拥抱在一起。之后他妹妹转向你]奴隶贩都死了？我们自由了？}
{224}{}{是的，奴隶贩都死了。}
{225}{}{太好了，请把门打开让我们出去吧。}
{226}{}{不用担心，我弄到钥匙了。}
{227}{}{好的，让我试着把门撬开。}

{400}{}{继续走。}
{401}{}{求求你带我回家吧。}

{410}{}{[你转向克莉苏]等等，你在这等着，我把其他人一走救走。[转向其他奴隶] 保持安静低下头跟我走。我会去搞定守卫的。}


#{500}{}{No, please don't touch me aga- wait, you're not a slaver. Who are you?}
{500}{}{不，求你别再碰我－等等，你不是奴隶贩。你是谁？}
{501}{}{我是获选者，你是谁？}
{502}{}{我的名字是 }
{503}{}{. 你是谁？}

#{510}{}{My name is Kurisu. I'm from a tribe on the coast south west of here. I was with a small group of my tribesmen when we were attacked by slavers. We were all brought here and with each passing week we have been sold off. Please help me escape. Any day now they are going to move me from here.}
{510}{}{我是克莉苏。我来自西南边海岸附近的一个部落。我们被奴隶贩抓到这来的。再过一个星期我们都会被卖掉。求求你救救我们。过几天他们就要把我们带走了。}

{511}{}{别担心我这就把你弄出去。我拿到钥匙和许可，可以把你带走。}
{512}{}{好吧，让我试试撬开这门。}

{530}{}{安全了，所有奴隶贩都死了？}
{531}{}{是的，安全了。我们现在可以回你的村庄去了。}
{532}{}{是的，不过走之前让我把其他人一起救出来。}

{533}{}{不，还没呢。安全后我会回来的。}

{600}{}{我们做到了！谢谢你救了我。}
{601}{}{不客气，那么你是怎么被抓的。}
#{602}{}{Well, some time ago I went trading at a nearby village. As I was there, the village was attacked by slavers. Those that survived were rounded up and brought to that camp. Every week new shipments of slaves come in and previous shipments leave. It's disgusting how people are treated these days.}
{602}{}{这样的，不久前我到附近的村子去买东西。当我到那时，村子被奴隶贩攻击。所有幸存者都被抓到了这个营地。每一星期就会有奴隶贩带走一些人。}
#{603}{}{Yes, slavery is quite a horrible thing. So, what are you going to do now?}
{603}{}{是的，贩卖奴隶是相当可恶的事。那么，你现在准备去哪？}
#{604}{}{Well, I am safely back at my native village thanks to you. After what happened, I don't think I will venture out of the village for some time. I see also that my brother seems quite fond of you. Though I would love for him to stay, he has mentioned that you are on an important quest. I hope my brother can aid you in this journey and that the gods watch over you.}
{604}{}{谢谢你把我安全送回我的村庄。经过这些事，我不会再冒险离开村子了。我的哥哥看上去很喜欢和你在一起。虽然我希望他留下，但是他常说起你在执行一个很重要的任务。我希望我的哥哥可以帮你，还有神会保佑你的。}
{605}{}{谢谢你克莉苏，保重。}
#{606}{}{Well, I am safely back at my native village thanks to you. After what happened, I don't think I will venture out of the village for some time. At the same time, I wish to go look for my brother Sulik. I fear he went looking for me and got into some kind of trouble.}
{606}{}{好的，谢谢你把我安全送回我的村庄。经过这些，我不会再冒险离开村子了。同时我希望去找我的哥哥史力克。我想他一定去找我了。说不定碰上什么麻烦了。}
{607}{}{实际上，我见过你的哥哥。鼻子上有大骨头，对吗？}
{608}{}{是的，那就是他！你见过他，然后呢？你能把他带来我们村子吗？我真希望再见到他。}
{609}{}{没问题，我会把他带来的。再见克莉苏。}
{610}{}{可时这有个问题。他死了。}
{611}{}{他死了？真不敢相信。我多希望能再见见他。[她看上去很伤心] 对不起我需要单独待会。谢谢你的营救我。}


{650}{}{你好，又见面了。我-....史力克！}
{651}{}{[更多]}
{652}{}{[史力克和克莉苏热泪盈眶的相互拥抱在一起] 谢谢你的找到我的哥哥。你真是个好人。他告诉我你正在做一个很重要的任务。祝你好运，神一定会保佑你的。}
#{653}{}{Hello again. Any luck finding my brother?}
{653}{}{你好，又见面了。我哥哥有消息吗？}
{654}{}{不，我还在找。有消息我会回来的。}

{700}{}{谢谢你做的一切。}
{701}{}{我会想我哥哥的。}

{800}{}{走开讨厌的家伙！}

{810}{}{进房去克莉苏！我会处理这事的。}

{820}{}{求求你不要让他们伤害我。}

{1000}{}{你让史力克和他的妹妹重逢了。}

