#ipisgfx译
{100}{}{你看见一个战士。}
{101}{}{你看见肖恩。}
{102}{}{他上去伤的很重，一只腿也断了。}
{103}{}{你看见肖恩。他上去伤的很重，一只腿也断了。}
{104}{}{你看见肖恩。他的腿绑着绷带，他正蹒跚而行。}
{105}{}{你看见肖恩。他看去好多了，他睡的很沉。}
{106}{}{你看见肖恩。他看起来已经恢复了。}

#{200}{}{*ugh* Die fiend!! You won't ta-}
{200}{}{*啊* 死神！你不会带-}
{201}{}{镇静，你现在安全了。那只蜥蜴死了。}

{202}{}{什么！？喔，谢天谢地。我还以为我死定了。}
{203}{}{这出了什么事？}
#{204}{}{Well, Jerem and I had gone on our weekly hunt for the tribe. There was a passage in this cave which led to a small field where several families of geckos lived. Sadly, the hunt didn't go as planned and we had to leave there quickly. Several of the geckos were hot on our trail though and as we ran through the passage we yelled for assistance. [The pauses for a moment and winces in pain as he tries to rub his leg]}
{204}{}{这是样的，杰里和我去执行我们部落的一周一次的打猎活动。穿过这个洞穴后有一小片原野没想到有几只蜥蜴在这。遗憾的是，打猎没有想计划那样我们必需赶快离开。几只蜥蜴紧紧跟着我们而我们逃跑到这个通道时大声呼救。[疼痛使他停住他揉了揉受伤的腿]}
{205}{}{请继续说。}
#{206}{}{Well, we always knew this passage was not going to last forever. We had found it on one of our scouting missions and realized it was a much quicker way to make it to our hunting grounds. There is a small stream directly above the passage and the ceiling was always dripping a bit. Several times we saw small rocks and mud fall from above. Anyway, our yelling must have been the last straw since just as we were exiting the passage the sky came down on us and rocks came from everywhere.}
{206}{}{我们都知道这个通道不是一通到底的，所以我们必需很快找到洞口守卫的方向这是我们离开这最快的方法。这时墙上出现了裂缝，不一会洞顶落下一些石块泥土，总知，我们的叫声让事情变得更糟，岩石落的到处都是。}

{207}{}{[然后呢]}
#{208}{}{Jerem wasn't lucky and a huge rock crushed him from the waist down. I was pumled with small rocks and just as I thought I was going to make it, a gecko came from behind and crunched straight into my right leg. I stumbled and fell loosing hold of my spear. Just when I thought it was all over, gods be praised the last of the rocks came down and this time right on top of the gecko. Alas, my foot wasn't so lucky and it was also in the path of the falling rocks. I was stuck and weaponless.}
{208}{}{杰里很不幸一块大石压在了他的腰上。我只是被一些小石头砸到我正想离开时一只蜥蜴从后面咬住了我的右腿。我差点绊倒在地，赶紧用矛支撑。就在我以为全完了的时候，谢天谢地一块大石头砸在了那只蜥蜴的头上。唉，我的脚也没那么幸运。同样被落下的岩石压住了。}
{209}{}{[继续]}
#{210}{}{Suddenly, I hear a snarl from the cave. I looked ahead and saw a large gecko. It was a bit dazed from the blast but boy was it pissed. Just as it was about to lunge for my head you came in here. I am truly in your debt.}
{210}{}{突然，我听到咆哮声传来。我看见前面有一只大蜥蜴。刚才的冲击使它有一点眩晕不过它看上去很愤怒。当它刚要攻击我的头时你来了。我真是欠你个人情。}
 
#{211}{}{What a story. Thank goodness you are alive. What about your leg?}
{211}{}{真是惊险的故事。感谢上帝你活着。你的腿怎么样了？}
#{212}{}{Oh, it doesn't look too good. Those falling rocks really did a number on it. I am not sure how I am going to get out of here now since I don't think I can get up on my own.}
{212}{}{噢，看起来不太好。落石确实很多。我不知道我要怎么走出这里，而且我都不知自己能不能站起来。}
{213}{}{我是一个医生。让我看看你的腿。}
{214}{}{我很强壮。我会把你带到巫师那去的，他会治好你的腿的。}
{215}{}{也许你应该让专业人事看看。我去找点人把你弄出去。}
{216}{}{嗯... 我把你带出去有点困难。不过史力克就没问题。 [叫史力克] 让我们把这家伙带出去吧。}
{217}{}{嗯... 我把你带出去有点困难。不过马可世就没问题。[叫马可世] 让我们把这家伙带出去吧。}
{218}{}{[你检查了这个战士的腿。伤的很重有些骨头都露出来了。你止住了流血且治好了他的腿]}
{219}{}{[15分钟后坚苦的工作他的腿比原来好多了。看上去他又能走了。]}
{220}{}{好吧，那就是我能做的。我需要休养几天好好恢复。这段时间要好好休息之后你就会好的。}
{221}{}{真的？噢，谢谢你。我会慢慢走出这去找巫师的。一会营地见。}
{222}{}{[完成]}

{300}{}{谢谢你的帮助。你会在营地见到我的。}

{400}{}{谢谢你救我了。你真是个好人！}

{500}{}{zzzZZzzz...}
{501}{}{...zzZZZZzz...zzz...}

{600}{}{你治好了肖恩的腿。}