#ipisgfx译
{100}{}{你看见一个鬼魂。}
{101}{}{你看见凯拉的鬼魂。}
{102}{}{你看见一个漂浮的鬼魂，在月光照射下发着光芒。}
{103}{}{救救我！}
{104}{}{我无法瞑目。}
{105}{}{请做点什么吧。}

{110}{}{救救我！你能救救我吗？}
{111}{}{哇，你...你是谁？}

{120}{}{我是一个鬼魂！但是我无法离开这。}
{121}{}{为什么？出什么问题了？}
#{122}{}{Hah. Sucks for you. Bye!}
{122}{}{哈. 真烂。再见！}

#{130}{}{I DON'T KNOW! Please help me, the loneliness is killing me.}
{130}{}{我不知道。请帮帮我，寂寞会杀了我的。}
{131}{}{那，我不知道...你是怎么死的？}

#{140}{}{I was murdered just beyond the village by a metal guy with a light gun. I sensed the magic of the man in this tent and thought he could help me. So far though, I've only succeeded in driving him mad!}
{140}{}{我是在村庄不远处被一个金属人用“光枪”杀害的。我感到帐篷里的这个男人有魔力他也许能帮我。但是，看样子我只能让他疯狂。}
#{141}{}{This is making sense now. I'll speak to the shaman. He may be able to help you.}
{141}{}{我会和巫师谈谈的。他也许能帮你。}

#{150}{}{Please do. The silence is unbearable.}
{150}{}{快去吧，寂静让我快疯了。}
{151}{}{[完成]}

#{160}{}{Please do something...}
{160}{}{请做点什么吧...}
#{161}{}{I'm working on it.}
{161}{}{我正在努力。}

{200}{}{这个鬼魂拒绝和你说话。}