#ipisgfx译
#{100}{}{Aaaarrrgghhh!! How... what... who are you?}
{100}{}{啊~~~~~~！！怎么...什么...你是谁？}
#{101}{}{Whoa, calm down. I'm not here to harm you! What's the matter?}
{101}{}{哇喔！冷静。我不是来伤害你的。出什么事了？}
#{102}{}{Someone who is getting annoyed with the way you are acting. What's wrong with you?}
{102}{}{谁使你这么烦躁。你出什么事了？}

#{110}{}{I'm ...here...visited. Visitations. Nighttime - outside the tent. I cannot rest at all.}
{110}{}{我...在这...观察。天罚。午夜帐篷外面。我根本不能休息。}
#{111}{}{What? You're being tormented? I really don't understand.}
{111}{}{什么？你很痛苦？我不太明白你什么意思。}
#{112}{}{Boogie-Woogie! Look out, the monster is coming right for you!}
{112}{}{Boogie-Woogie! 看外面，怪物来找你了！}

#{120}{}{DEMONS, my child. Demons! They come in the night and haunt me! They seek to take me! The end is nigh... I am not long for this world now...}
{120}{}{魔鬼， 我的孩子。魔鬼!他们一到晚上就来缠着我！他们试图带走我！死亡即将来临... 我在这个世界的时日不多了...}
{121}{}{你需要帮助。}

#{125}{}{Waahhhh! (The man hundles in fright)}
{125}{}{哇~~~~! (这个人大吃一惊)}
#{126}{}{Heh, loser.}
{126}{}{嗨，孬种。}
#{127}{}{The shaman is too afraid to speak with you.}
{127}{}{这个巫师非常害怕和你说话。}

#{130}{}{Please, leave me alone. There's nothing that can be done to save me. Save yourself!!}
{130}{}{救救救你，让我一个人待会。没什么可以救我了。自己逃命吧！！}
{131}{}{好吧，再见。}

#{140}{}{What do you want? I told you to save yourself.}
{140}{}{你想干什么？我不是告诉过你让你自己逃命去。}
#{141}{}{Yeah, but I may have solved your problems. I can stop your demons!}
{141}{}{是的，不过我也许能解决你的问题。我能阻止你的魔鬼！}

#{150}{}{*pauses* Really! How? What have you found out?}
{150}{}{*停住* 真的吗？怎么做？! 你找到了什么？}
#{151}{}{The so-called demon that you speak of is the ghost of a young women that was killed just beyond the village. It sought you out as the village shaman to release its spirit from this world. Do that and you'll be free.}
{151}{}{你说的这个所谓的魔鬼是村庄附近被杀害的一个女人的鬼魂。她缠着你是因为你可以超渡她的亡魂。之后就没事了。}

#{160}{}{*eyes sparkle* Yes...oh my, that would explain everything! The visions, the wailing...the ghost... when did you see this ghost?}
{160}{}{*眨了眨眼* 是的...天哪，那说明了一切！幻影，哀号声...鬼魂... 你什么时候看见那个鬼魂？}
#{161}{}{At midnight. Just beyond your tent.}
{161}{}{午夜。就在你的账篷外。}

#{170}{}{Yes, yes I see it now. Would you stay with me? I don't know if I could do it without you. You've already seen the ghost you see...}
{170}{}{是的，是的现在我看见了。你能和我一起去吗？没你在我不知道能不能超渡她。你已经看到了这个鬼魂你明白的...}
#{171}{}{Unbelievable. A shaman with a fear of spirits. No problem. I'll stay with you.}
{171}{}{难以置信。一个巫师害怕幽灵。没问题，我会和你一起去的。}

#{180}{}{Thank you. You have saved my sanity. I cannot thank you enough. Take these healing potions as thanks.}
{180}{}{谢谢你。有你在我就放心了。十分感谢。拿着这些治疗剂以表谢意。}
{181}{}{...不用客气。}

{190}{}{你看见一个衣服破烂的人。}
{191}{}{你看见这个村庄的巫师。}
{192}{}{这个人全身摇摆、跳跃制造出了各种噪声。}
{193}{}{这个巫师看上去平静多了不再摇摆了。}

#{200}{}{I call on the spirits of this holy land!}
{200}{}{我从圣地召唤灵魂。}
{201}{}{请让我解脱吧。我求求你。}
#{202}{}{Allow this poor girl safe passage to the next world and release her from her torment.}
{202}{}{请允许这个可怜的女孩安全到达另一个世界吧。让她从痛苦中解脱吧。}
{203}{}{*哭泣* 妈妈我来了。}
{204}{}{你准备好了吗？凯拉！}
{205}{}{好了。}
#{206}{}{Then be released from this mortal coil.  Go to the light.}
{206}{}{从尘世中解脱吧！走向光明吧！}
#{207}{}{It's so bright...}
{207}{}{这光是...}


#{208}{}{I can't thank you enough for helping me.}
{208}{}{对你的帮助感激不尽。}
#{209}{}{I will forever be in your debt.}
{209}{}{我将永记的你恩情。}

#{300}{}{Thank you for helping to rescue Serin for us. I gave him some herbs to help him rest and ease his pain. He should be back up and about after two days.}
{300}{}{谢谢你为我们营救肖恩。我给他了一点草药帮助他休息和安抚他的痛苦。两天左右他应该就能起来了。}
 
#{301}{}{That is good to hear. Anything else I can do?}
{301}{}{听上去不错。我还能做点什么吗？}
#{302}{}{I'm glad Serin will make it. Take care.}
{302}{}{我很高兴肖恩会好起来。保重。}

#{303}{}{Well actually yes, there is something. I am running low on Broc flower and Xander root. If you could get me a couple bushles, say 5 Xander and 3 Broc Flower, I would be most grateful.}
{303}{}{是的实际上，有一件事。我的布拉克花和山德根快用完了。如果你能找一些给我，比方说5个山德根和3个布拉克花，我将十分感谢。}

#{304}{}{I would be happy to help. I shall return when I obtain these items.} 
{304}{}{我很乐意帮忙。我找到后会回来的。}
#{305}{}{I would be happy to help. In fact, I have all those items on me right now.}
{305}{}{我很乐意帮忙。实际上，我现在就有这些东西。}
{306}{}{对不起，我不是很感兴趣。再见。}

#{307}{}{Have you obtained the items I need?}
{307}{}{你找到那些东西了吗？}
{308}{}{是的，全在这了。}
{309}{}{我正在找。再见。}

#{310}{}{Excellent. These will work well. Here is some healing powder for your time.}
{310}{}{太好了。拿去这是一些治疗剂，谢谢你的帮助。}
{311}{}{谢谢，再见。}

{312}{}{你递给巫师一些草药。}
{1000}{}{你解除了这个部落巫师的烦恼。}