#ipisgfx译
{100}{}{你看见一个强壮的土著战士。}
{101}{}{这个土著看上去很强壮。}

#{200}{}{Halt! Wut you want?}
{200}{}{站住!你要干嘛？}
#{201}{}{What are you doing here?}
{201}{}{你在这做什么？}
#{202}{}{Me guard cave for tribe. Me make sure no bad men sneak up on us.}
{202}{}{我在守护部落的洞穴。为了保证没有任何坏人能偷袭我们。}
#{203}{}{I see. Could I look around the cave?}
{203}{}{我明白了。我能参观一下这个洞穴吗？}
#{204}{}{No. Me no allowed to let strangers in cave. Head warrior told so.}
{204}{}{不，战士队长说过不能让陌生人进去。}
#{205}{}{Maybe later then.}
{205}{}{也许一会再来。}
#{206}{}{You again? Wut dis time?}
{206}{}{你又来了？}
#{207}{}{Just passing through. Keep up the good work.}
{207}{}{只是路过。好好工作。}
#{208}{}{The head warrior told me I am allowed to enter the cave to search for the missing hunters.}
{208}{}{战士队长叫我进去寻找失踪的猎人们。}
#{209}{}{Oh, yeah, me no see those guys in while. Hope they ok. Head warrior say ok to enter? Fine wit me.}
{209}{}{噢，是的，我很久没见过这些家伙了。希望他们还好。战士队长说可以进去？好吧。}
#{210}{}{Thanks. I'll let you know if I need anything.}
{210}{}{谢谢，需要帮忙我会告诉你的。}

#{300}{}{Hey, why you rush? You find sumtin?}
{300}{}{嗨，为什么你这么匆忙？你找到他们了？}
#{301}{}{Yes, I found the missing hunters. One of them is dead but the other is badly hurt. I need your help to carry him out and bring him to the Shaman. I'll go wait with the Shaman while you rescue the hunter.}
{301}{}{是的，我找到失踪的猎人了。其中一个死了，其他的受了伤。我需要你帮忙把他们送去巫师那。我会去巫师那等你。}
#{302}{}{Tribe member need help? Me need help them. In cave? Me coming!}
{302}{}{部落成员需要帮助？我要帮他们。进洞？好的，我来了！}
{303}{}{[完成]}

#{400}{}{Thanks for helpin Serin. He good warrior. You friend of tribe.}
{400}{}{谢谢你帮助肖恩。他是一个好战士。你是部落的朋友。}
#{401}{}{Thanks. Well, I must be going now.}
{401}{}{谢谢，那么，我必需走了。}
#{402}{}{Hello friend. Wut you need?}
{402}{}{你好朋友，你需要什么？}
{403}{}{没什么，只是路过。保重。}